// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Tamil (`ta`).
class AppLocalizationsTa extends AppLocalizations {
  AppLocalizationsTa([String locale = 'ta']) : super(locale);

  @override
  String get about => 'விவரங்கள்';

  @override
  String get active => 'செயலில்';

  @override
  String get add => 'சேர்';

  @override
  String get addAccount => 'கணக்கைச் சேர்க்கவும்';

  @override
  String get addAll => 'அனைத்தையும் சேர்';

  @override
  String get addAllAndRemoveOldOnes => 'அனைத்தையும் சேர்த்து பழையவற்றை அகற்று';

  @override
  String get addAsANewPlaylist => 'புதிய பாடல் பட்டியலாகச் சேர்க்கவும்';

  @override
  String get addAudioToLocalLibrary => 'ஒலியை உள்ளூர் சாதன சேமிப்பில் சேர்க்கவும்';

  @override
  String get addFolder => 'கோப்புறை சேர்க்க';

  @override
  String get addLanguage => 'மொழியைச் சேர்';

  @override
  String get addLanguageSubtitle => 'நமிடாவை உங்கள் சொந்த மொழியில் மொழிபெயர்க்க உதவுங்கள்';

  @override
  String get addLrcFile => 'LRC கோப்பைச் சேர்க்க';

  @override
  String get addMoreFromThisAlbum => 'இந்த ஆல்பத்தில் இருந்து மேலும் சேர்க்க';

  @override
  String get addMoreFromThisArtist => 'இந்த கலைஞரின் மேலும் பாடல்களை வரிசையில் சேர்க்க';

  @override
  String get addMoreFromThisFolder => 'இந்த கோப்புறையில் இருந்து மேலும் பாடல்களை வரிசையில் சேர்க்க';

  @override
  String addMoreFromToQueue({required String media}) {
    return '$media இருந்து மேலும் வரிசையில் சேர்க்க';
  }

  @override
  String get addOnlyMissing => 'விடுபட்டவற்றை மட்டும் சேர்க்கவும்';

  @override
  String get addToFavourites => 'விருப்ப பட்டியலில் சேர்க்க';

  @override
  String get addToPlaylist => 'தற்போதைய பாடல் வரிசையில் சேர்க்க';

  @override
  String get addTracksAtTheBeginning => 'தொடக்கத்தில் தடங்களைச் சேர்க்கவும்';

  @override
  String get added => 'சேர்க்கப்பட்டது';

  @override
  String get advanced => 'மேம்பட்ட';

  @override
  String get advancedSettings => 'மேம்பட்ட அமைப்புகள்';

  @override
  String get advancedSettingsSubtitle => 'இவை மேம்பட்ட அமைப்புகளாகும். தேவையற்ற மாற்றங்களைத் தவிர்க்கவும்';

  @override
  String get alarm => 'அலாரம்';

  @override
  String get album => 'இசைத் தொகுப்பு';

  @override
  String get albumArtist => 'இசை கலைஞர்';

  @override
  String get albumArtists => 'இசைக் கலைஞர்கள்';

  @override
  String get albumIdentifiers => 'இசைத் தொகுப்பு அடையாளங்காட்டி';

  @override
  String get albumThumbnailSizeInList => 'இசைத் தொகுப்பின் சிறு படவுரு அளவு';

  @override
  String get albumTileCustomization => 'இசைத் தொகுப்பு தோற்றத்தைத் தனிப்பயனாக்குதல்';

  @override
  String get albums => 'இசைத் தொகுப்புகள்';

  @override
  String get albumsCount => 'இசைத் தொகுப்பு எண்ணிக்கை';

  @override
  String get all => 'அனைத்தும்';

  @override
  String get allTime => 'என்றும்';

  @override
  String get alreadyExists => 'ஏற்கனவே உள்ளது';

  @override
  String get always => 'எப்போதும்';

  @override
  String get alwaysAsk => 'எப்பொழுதும் கேள்';

  @override
  String get alwaysDim => 'எப்போதும் மங்கலாகி';

  @override
  String get alwaysExpandedSearchbar => 'எப்போதும் விரிவாக்கப்பட்ட தேடல் பட்டி';

  @override
  String get alwaysRestore => 'எப்போதும் மீட்டமை';

  @override
  String get animatingThumbnailIntensity => 'சிறுபட அனிமேஷன் தீவிரம்';

  @override
  String get animatingThumbnailInversed => 'தலைகீழ் அனிமேஷன்கள்';

  @override
  String get animatingThumbnailInversedSubtitle => 'உயர்ந்த சிகரங்கள் சிறுபடத்தை சிறியதாக மாற்றும்';

  @override
  String get anotherProcessIsRunning => 'மற்றொரு செயல்முறை ஏற்கனவே இயங்கிக் கொண்டிருக்கிறது.';

  @override
  String get appIcon => 'பயன்பாட்டு படவுரு';

  @override
  String get appVersion => 'ஆப் பதிப்பு';

  @override
  String get artist => 'இசைக் கலைஞர்';

  @override
  String get artists => 'இசை கலைஞர்கள்';

  @override
  String get artwork => 'கலைப்படைப்பு';

  @override
  String get artworkGestures => 'கலைப்படைப்புச் சைகைகள்';

  @override
  String get artworks => 'கலைப்படைப்புகள்';

  @override
  String get audio => 'ஒலி';

  @override
  String get audioCache => 'ஒலியின் தற்காலிக சேமிப்பு';

  @override
  String get audioOnly => 'ஒலி மட்டுமே';

  @override
  String get auto => 'தானியங்கி';

  @override
  String get autoBackupInterval => 'தானாக காப்புப்பிரதி எடுக்க இடைவெளி';

  @override
  String get autoColoring => 'சுயமாக வண்ணமடித்தல்';

  @override
  String get autoColoringSubtitle => 'வசன வரிகளை சுயமாக வண்ணமடிக்க';

  @override
  String get autoExtractTagsFromFilename => 'குறிச்சொற்களை கோப்பு பெயரில் இருந்து தானாக பிரித்தெடு';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'வீடியோ தலைப்பிலிருந்து தலைப்பையும் கலைஞரையும் தானாகப் பிரித்தெடுக்கவும்';

  @override
  String get autoGenerated => 'தானாக உருவாக்கப்பட்டது';

  @override
  String get autoSkip => 'ஆட்டோ ச்கிப்';

  @override
  String get autoSkipOnce => 'ஒருமுறை ஆட்டோ ச்கிப்';

  @override
  String get autoStartRadio => 'வானொலியை தானாக துவக்க';

  @override
  String get autoStartRadioSubtitle => 'ஒற்றை டிராக்கை இயக்கும்போது தானாகவே மிக்ஸ் பிளேலிஸ்ட்டைச் சேர்க்கிறது';

  @override
  String get automaticBackup => 'தானாக காப்புப்பிரதி எடுக்க';

  @override
  String get automaticBackupSubtitle => 'வசன வரிகளை தானாக காப்புப்பிரதி எடுக்க';

  @override
  String get backupAndRestore => 'காப்புபிரதி மற்றும் மீட்டமை';

  @override
  String get backupAndRestoreSubtitle => 'உங்கள் தரவுத்தளம் மற்றும் அமைப்புகளை காப்புப்பிரதி எடுக்கவும்';

  @override
  String get balanced => 'சமநிலையாக';

  @override
  String get beta => 'பீட்டா';

  @override
  String get betweenDates => 'தேதிகளுக்கு இடையே';

  @override
  String get bitrate => 'பிட்ரேட்';

  @override
  String get blacklist => 'தடுப்புப்பட்டியல்';

  @override
  String get borderRadiusMultiplier => 'எல்லை ஆரம் பெருக்கி';

  @override
  String get cache => 'தற்காலிக சேமிப்பு';

  @override
  String get cancel => 'ரத்துசெய்';

  @override
  String get canceled => 'ரத்து செய்யப்பட்டது';

  @override
  String get changed => 'மாற்றப்பட்டது';

  @override
  String get changelog => 'மாற்றத்தின் பதிவேடு';

  @override
  String get changelogSubtitle => 'நமிடாவிற்குள் புதிதாக சேர்க்கப்பட்ட/நிறுத்தப்பட்டவைகளைப் பார்க்கவும்';

  @override
  String get channel => 'சேனல்';

  @override
  String get channels => 'சேனல்கள்';

  @override
  String get check => 'சரிபார்';

  @override
  String get checkForMore => 'மேலும் சரிபார்க்கவும்';

  @override
  String get checkList => 'சோதனை பட்டியல்';

  @override
  String get choose => 'தேர்வு செய்யவும்';

  @override
  String get chooseWhatToClear => 'எதை அழிக்க வேண்டும் என்பதை தேர்வு செய்யவும்';

  @override
  String get claim => 'உரிமைகோர்';

  @override
  String get clear => 'நீக்கு';

  @override
  String get clearAudioCache => 'ஆடியோ தற்காலிக சேமிப்பை அழிக்கவும்';

  @override
  String get clearImageCache => 'பட தற்காலிக சேமிப்பை அழிக்கவும்';

  @override
  String get clearImageCacheWarning => 'எச்சரிக்கை: படங்கள் இல்லாத நூலகம் உருவாகும், பட தற்காலிக சேமிப்பை மீண்டும் உருவாக்க மட்டும் பயன்படுத்தவும்.';

  @override
  String get clearTrackItem => 'தடங்களை அழி';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString தடங்களை அழி',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'வீடியோ தற்காலிக சேமிப்பை அழிக்கவும்';

  @override
  String get clearVideoCacheNote => 'எதை நீக்க வேண்டும் என்பதை நீங்கள் தேர்வு செய்யலாம்.';

  @override
  String get clock => 'கடிகாரம்';

  @override
  String get colorPalette => 'நிற தட்டு';

  @override
  String get colorPaletteNote1 => 'ஒரு நிறத்தை நீக்க நீண்ட நேரம் அழுத்தவும்';

  @override
  String get colorPaletteNote2 => 'இயல்புநிலை நிறமாகப் பயன்படுத்த ஒரு கலவையைத் தட்டவும்';

  @override
  String get colorPalettes => 'வண்ண தட்டுக்கள்';

  @override
  String get comment => 'கருத்து';

  @override
  String get comments => 'கருத்துக்கள்';

  @override
  String get composer => 'இசையமைப்பாளர்';

  @override
  String get compress => 'சுருக்கு';

  @override
  String get compressImages => 'படத்தை சுருக்கவும்';

  @override
  String get compressionPercentage => 'சுருக்க சதவீதம்';

  @override
  String get configure => 'கட்டமைக்க';

  @override
  String get confirm => 'உறுதிப்படுத்து';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'நகலெடுக்கப்பட்ட கலைப்படைப்பு';

  @override
  String get copiedToClipboard => 'கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது';

  @override
  String get copy => 'நகலெடுக்க';

  @override
  String get corruptedFile => 'சிதைந்த கோப்பு';

  @override
  String get couldntOpen => 'திறக்க இயலவில்லை :(';

  @override
  String get couldntOpenYtLink => 'இந்த டிராக்கிற்கான Youtube இணைப்பு எதுவும் கிடைக்கவில்லை';

  @override
  String get couldntPlayFile => 'கோப்பை இயக்க முடியவில்லை';

  @override
  String get couldntRenamePlaylist => 'பிளேலிஸ்ட்டின் பெயரை மாற்ற முடியவில்லை';

  @override
  String get couldntSaveImage => 'படத்தைச் சேமிக்க முடியவில்லை';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'நாடு';

  @override
  String get coupon => 'கூப்பன்';

  @override
  String get create => 'உருவாக்க';

  @override
  String get createBackup => 'காப்புப்பிரதியை உருவாக்கு';

  @override
  String get createNewPlaylist => 'புதிய பட்டியலை உருவாக்கவும்';

  @override
  String get createdBackupSuccessfully => 'காப்புப்பிரதி உருவாக்கப்பட்டது';

  @override
  String get createdBackupSuccessfullySub => 'காப்பு கோப்பு வெற்றிகரமாக உருவாக்கப்பட்டது';

  @override
  String get crossPlatformSync => 'குறுக்கு-தளம் ஒத்திசைவு';

  @override
  String get crossfadeDuration => 'கிராஸ்ஃபேட் கால அளவு';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'கடைசி $secondsString வினாடிகளில் தானாகவே கிராஸ்ஃபேடை இயக்கு',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'கிராஸ்ஃபேடை தானாகத் தூண்ட வேண்டாம்';

  @override
  String get custom => 'வழக்கம்';

  @override
  String get customizations => 'தனிப்பயனாக்கங்கள்';

  @override
  String get customizationsSubtitle => 'துணைத் தலைப்பு தனிப்பயனாக்குதல்';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'தரவு வழங்கியவர்: $name';
  }

  @override
  String get dataSaver => 'தரவு சேமிப்பான்';

  @override
  String get dataSaverMode => 'டேட்டா சேவர் பயன்முறை';

  @override
  String get database => 'டேட்டாபேஸ்';

  @override
  String get date => 'தேதி';

  @override
  String get dateAdded => 'சேர்க்கப்பட்ட தேதி';

  @override
  String get dateCreated => 'உருவாக்கப்பட்ட தேதி';

  @override
  String get dateModified => 'மாற்றப்பட்ட தேதி';

  @override
  String get dateTimeFormat => 'தேதி நேர வடிவம்';

  @override
  String get day => 'நாள்';

  @override
  String get days => 'நாட்களில்';

  @override
  String get defaultBackupLocation => 'இயல்புநிலை காப்புப் பிரதி இடம்';

  @override
  String get defaultColor => 'இயல்பு வண்ணம்';

  @override
  String get defaultColorSubtitle => 'துணைத் தலைப்பின் இயல்புநிலை வண்ணம்';

  @override
  String get defaultDownloadLocation => 'இயல்புநிலை பதிவிறக்க இருப்பிடம்';

  @override
  String get defaultLabel => 'இயல்புநிலை';

  @override
  String get defaultLibraryTab => 'இயல்புநிலை நூலக தாவல்';

  @override
  String get delete => 'நீக்க';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$totalSizeText ஐக் குறிக்கும் $countString கோப்பை நீக்கவா?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'உங்கள் சேமிப்பகத்திலிருந்து $numberText ஐ நிரந்தரமாக நீக்கவும்';
  }

  @override
  String get deletePlaylist => 'பிளேலிஸ்ட்டை நீக்கு';

  @override
  String get deleteTempFiles => 'தற்காலிக கோப்புகளை நீக்கு';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'விவரிக்க';

  @override
  String get developer => 'உருவாக்குநர்';

  @override
  String get development => 'வளர்ச்சி';

  @override
  String get didYouMean => 'நீங்கள் கூற வருவது';

  @override
  String get dimIntensity => 'திரை மங்கலாக்கல்';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString வினாடிகள் செயலற்ற நிலைக்குப் பிறகு மினிபிளேயரை மங்கலாக்கு',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'கோப்பகம் இல்லை';

  @override
  String get disable => 'முடக்கு';

  @override
  String get disableAll => 'அனைத்தையும் முடக்கு';

  @override
  String get disableReordering => 'மறுவரிசைப்படுத்தலை முடக்கு';

  @override
  String get disableSearchCleanup => 'தேடல் பெட்டி சுத்தம் செய்வதை முடக்கு';

  @override
  String get discNumber => 'டிஸ்க் எண்';

  @override
  String get discNumberTotal => 'மொத்த வட்டு';

  @override
  String get discover => 'கண்டுபிடி';

  @override
  String get dislike => 'பிடிக்கவில்லை';

  @override
  String get dismissibleMiniplayer => 'நிராகரிக்கக்கூடிய மினிபிளேயர்';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'தேடும் போது வித்தியாசத்திற்குப் பதிலாக உண்மையான நிலையைக் காட்டு';

  @override
  String get displayAlbumCardTopRightDate => 'ஆல்பம் அட்டையின் மேல் வலதுபுறம் தேதி';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'ஆல்பம் கார்டின் மேல் வலதுபுறத்தில் ஆல்பம் தேதியைக் காண்பி';

  @override
  String get displayArtistBeforeTitle => 'தலைப்புக்கு முன் கலைஞரைக் காட்டு';

  @override
  String get displayArtworkOnLockscreen => 'பூட்டுத் திரையில் கலைப்படைப்புகளைக் காட்டு';

  @override
  String get displayAudioInfoInMiniplayer => 'ஆடியோ தகவலைக் காட்டு';

  @override
  String get displayFavButtonInNotification => 'அறிவிப்பில் பிடித்த பொத்தானைக் காண்பி';

  @override
  String get displayFavButtonInNotificationSubtitle => 'சிறுபடம் இடம்பெயரக்கூடும்.';

  @override
  String get displayFavouriteIconInTrackTile => 'பிடித்த பொத்தானைக் காட்டு';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'மொத்த கால அளவிற்கு பதிலாக மீதமுள்ள கால அளவைக் காண்பி';

  @override
  String get displayStopButtonInNotification => 'அறிவிப்பில் ச்டாப் பட்டனைக் காண்பி';

  @override
  String get displayThirdItemInRowInTrackTile => 'ஒவ்வொரு வரிசையிலும் மூன்றாவது உருப்படியைக் காட்டு';

  @override
  String get displayThirdRowInTrackTile => 'மூன்றாவது வரிசையைக் காட்டு';

  @override
  String get displayTrackNumberInAlbumPage => 'ஆல்பம் பக்கத்தில் டிராக் எண்ணைக் காட்டு';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'ஆல்பம் பக்கத்தில் டிராக் எண்ணைக் கொண்ட ஒரு சிறிய பெட்டியைக் காண்பி';

  @override
  String get doNothing => 'ஒன்றுமே செய்யாதே';

  @override
  String get donate => 'நன்கொடை';

  @override
  String get donateSubtitle => 'நீங்கள் நினைத்தால் அது தகுதியானது';

  @override
  String get done => 'முடிந்தது';

  @override
  String get dontAskAgain => 'மீண்டும் கேட்க வேண்டாம்';

  @override
  String get dontDim => 'மங்கலாக்காதே';

  @override
  String get dontRestorePosition => 'மீட்டெடுக்க வேண்டாம்';

  @override
  String get dontResume => 'தொடர வேண்டாம்';

  @override
  String get doubleTapToToggleLyrics => 'பாடல் வரிகளை மாற்ற இருமுறை தட்டவும்';

  @override
  String get download => 'பதிவிறக்க';

  @override
  String get downloadingWillOverrideIt => 'பதிவிறக்குவது மேலெழுதப்படும்';

  @override
  String get downloads => 'பதிவிறக்கங்கள்';

  @override
  String get downloadsMetadataTags => 'மெட்டாடேட்டா குறிச்சொற்களைப் பதிவிறக்கு';

  @override
  String get downloadsMetadataTagsSubtitle => 'வீடியோ தகவலிலிருந்து கலைஞர், தலைப்பு மற்றும் ஆல்பத்தை இயல்பாகவே பிரித்தெடுக்கவும்';

  @override
  String get dragToSeek => 'நகர்த்த இழுக்கவும்';

  @override
  String get duckAudio => 'டக் ஆடியோ';

  @override
  String get duplicatedItemsAdding => 'இந்த பிளேலிஸ்ட்டில் ஏற்கனவே உள்ள சில உருப்படிகளைச் சேர்க்க முயற்சிக்கிறீர்கள்';

  @override
  String get duplicatedTracks => 'நகல் தடங்கள்';

  @override
  String get duration => 'கால அளவு';

  @override
  String get edgeColorsSwitching => 'விளிம்பு நிறங்களை மாற்றுதல்';

  @override
  String get edit => 'திருத்து';

  @override
  String get editArtwork => 'கலைப்படைப்பைத் திருத்து';

  @override
  String get editTags => 'குறிச்சொற்களைத் திருத்து';

  @override
  String get email => 'மின்னஞ்சல்';

  @override
  String get emptyNonMeaningfulTagFields =>
      'உங்களிடம் வெற்று/அர்த்தமற்ற மதிப்புகளைக் கொண்ட புலங்கள் உள்ளன, அவற்றை நீங்கள் உண்மையிலேயே திருத்த விரும்புகிறீர்களா என்பதை உறுதிப்படுத்திக் கொள்ளுங்கள்';

  @override
  String get emptyValue => 'வெற்று மதிப்பு';

  @override
  String get enableArtworkCache => 'கலைப்படைப்பு தற்காலிக சேமிப்பை இயக்கு';

  @override
  String get enableArtworkCacheSubtitle => 'வேகமாக ஏற்றுதல் மற்றும் மேம்படுத்தப்பட்ட செயல்திறன், ஆனால் அதிக சேமிப்பிடத்தைப் பயன்படுத்துகிறது';

  @override
  String get enableBlurEffect => 'மங்கலான விளைவை இயக்கு';

  @override
  String get enableBottomNavBar => 'கீழ் வழிசெலுத்தல் பட்டியை இயக்கு';

  @override
  String get enableBottomNavBarSubtitle => 'பொருட்கள் டிராயரின் இருபுறமும் உள்ளே உள்ளன';

  @override
  String get enableClipboardMonitoring => 'கிளிப்போர்டு கண்காணிப்பை இயக்கு';

  @override
  String get enableClipboardMonitoringSubtitle => 'பயணத்தின்போது தேடல் பட்டியில் இணைப்புகள் மற்றும் உரையை ஒட்ட அனுமதிக்கவும்';

  @override
  String get enableCrossfadeEffect => 'கிராஸ்ஃபேட் விளைவை இயக்கு';

  @override
  String get enableFadeEffectOnPlayPause => 'இயக்கு/இடைநிறுத்தத்தில் மங்கலான விளைவை இயக்கு';

  @override
  String get enableFoldersHierarchy => 'கோப்புறைகள் படிநிலையை இயக்கு';

  @override
  String get enableGlowEffect => 'பளபளப்பு விளைவை இயக்கு';

  @override
  String get enableM3uSync => 'M3U ஒத்திசைவை இயக்கு';

  @override
  String get enableM3uSyncNote1 => 'M3U ஒத்திசைவு, பிளேலிஸ்ட் மாற்றங்களை அசல் M3U கோப்பில் சேமிக்க அனுமதிக்கிறது';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'ஏதேனும் தவறு நடந்திருந்தால், இந்தப் பட்டியலின் காப்புப்பிரதி $playlistsBackupPath இல் காணப்படும்';
  }

  @override
  String get enableM3uSyncSubtitle => 'மறுக்கப்பட்டால், இந்த பிளேலிஸ்ட்டில் செய்யப்பட்ட அனைத்து மாற்றங்களும் மறுதொடக்கத்தில் இழக்கப்படும்';

  @override
  String get enableMiniplayerParticles => 'நகரும் துகள்களை இயக்கு';

  @override
  String get enableParallaxEffect => 'இடமாறு விளைவை இயக்கு';

  @override
  String get enablePartyMode => 'பார்ட்டி பயன்முறையை இயக்கவும்';

  @override
  String get enablePartyModeSubtitle => 'ஆடம்பரமான விளிம்பு சுவாச விளைவைப் பயன்படுத்துங்கள்';

  @override
  String get enablePictureInPicture => 'படத்தில் படத்தை இயக்கு';

  @override
  String get enableReordering => 'மறுவரிசைப்படுத்தலை இயக்கு';

  @override
  String get enableReturnYoutubeDislike => 'யூடியூப் பிடிக்காததை திரும்பப் பெறுவதை இயக்கு';

  @override
  String get enableSearchCleanup => 'தேடல் சுத்தம் செய்வதை இயக்கு';

  @override
  String get enableSearchCleanupSubtitle => 'அனைத்து சின்னங்களும் இடைவெளிகளும் புறக்கணிக்கப்படும்';

  @override
  String get enableSponsorblock => 'ஒப்புரவாளர் பிளாக்கை இயக்கவும்';

  @override
  String get enableVideoPlayback => 'வீடியோ பிளேபேக்கை இயக்கு';

  @override
  String get enterSymbol => 'சின்னத்தை உள்ளிடவும்';

  @override
  String get equalizer => 'சமநிலைப்படுத்தி';

  @override
  String get error => 'பிழை';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'டிராக்கை இயக்குவதில் பிழை';

  @override
  String get excludedFodlers => 'விலக்கப்பட்ட கோப்புறைகள்';

  @override
  String get exit => 'வெளியேறு';

  @override
  String get exitAppSubtitle => 'வெளியேற மீண்டும் தட்டவும்';

  @override
  String get expandedMiniplayer => 'விரிவாக்கப்பட்ட மினிபிளேயர்';

  @override
  String get exportAsM3u => 'M3U ஆக ஏற்றுமதி செய்யவும்';

  @override
  String get extension => 'நீட்டிப்பு';

  @override
  String get externalFiles => 'வெளிப்புற கோப்புகள்';

  @override
  String get extract => 'பிரித்தெடுக்க';

  @override
  String get extractAllColorPalettes => 'அனைத்து வண்ணத் தட்டுகளையும் பிரித்தெடுக்கவும்';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'மீதமுள்ள $numberString பிரித்தெடுக்கவா?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'தலைப்பிலிருந்து கலைஞர்களின் சாதனையைப் பிரித்தெடுக்கவும்';

  @override
  String get extractFeatArtistSubtitle => 'ஒரு புதிய கலைஞரின் நுழைவாக, (feat. X) மற்றும் (ft. X) கலைஞர்கள்.';

  @override
  String get extractingInfo => 'தகவலைப் பிரித்தெடுக்கிறது';

  @override
  String get extras => 'கூடுதல்கள்';

  @override
  String get extrasSubtitle => 'கூடுதல் துணை தலைப்பு';

  @override
  String get extreme => 'தீவிர';

  @override
  String get failed => 'தோல்வியடைந்தது';

  @override
  String get failedEdits => 'திருத்துவதில் தோல்வி';

  @override
  String get favourites => 'விருப்பமானவை';

  @override
  String get features => 'நற்பொருத்தங்கள்';

  @override
  String get fetching => 'எடுக்கிறது';

  @override
  String get fetchingOfAllVideos => 'அனைத்து வீடியோக்களையும் எடுக்கிறது';

  @override
  String get file => 'கோப்பு';

  @override
  String get fileAlreadyExists => 'கோப்பு ஏற்கனவே உள்ளது';

  @override
  String get fileBasedServerWarning =>
      'அட்டவணைப்படுத்துவதற்காக கோப்புகள் தற்காலிகமாக பதிவிறக்கம் செய்யப்படும், உங்கள் இணைப்பு நிலையானது என்பதை உறுதிப்படுத்தவும். \nஅதிக டேட்டா உபயோகத்தைத் தவிர்க்க வைஃபை பரிந்துரைக்கப்படுகிறது.';

  @override
  String get fileName => 'கோப்பு பெயர்';

  @override
  String get fileNameWoExt => 'கோப்பு வடிவம் இல்லாத கோப்பு பெயர்';

  @override
  String get filenameShouldntStartWith => 'கோப்பு பெயர் தொடங்கக்கூடாது';

  @override
  String get files => 'கோப்புகள்';

  @override
  String get filler => 'நிரப்பு';

  @override
  String get filterAlbums => 'ஆல்பங்களை வடிகட்டவும்';

  @override
  String get filterArtists => 'கலைஞர்களாக வடிகட்டவும்';

  @override
  String get filterGenres => 'வகைகளை வடிகட்டவும்';

  @override
  String get filterPlaylists => 'பிளேலிஸ்ட்களை வடிகட்டவும்';

  @override
  String get filterTracks => 'தடங்களாக வடிகட்ட';

  @override
  String get filterTracksBy => 'தேடல் பட்டியல்களில் உள்ள தடங்களை இதன்படி வடிகட்டவும்';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'அளவு மற்றும் கால அளவு மூலம் வடிகட்டப்பட்ட தடங்கள்';

  @override
  String get finished => 'முடிந்துவிட்டது';

  @override
  String get finishedUpdatingLibrary => 'நூலகத்தைப் புதுப்பிப்பது முடிந்தது';

  @override
  String get firstListen => 'முதல் முறையாக கேட்டேன்';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp பெரிய சிறுபட அளவை சரிசெய்யவும்';

  @override
  String get floatingActionButton => 'மிதக்கும் செயல் பொத்தான்';

  @override
  String get folder => 'கோப்புறை';

  @override
  String get folderName => 'கோப்புறையின் பெயர்';

  @override
  String get folders => 'கோப்புறைகள்';

  @override
  String get fontScale => 'எழுத்துரு அளவு';

  @override
  String get forceMiniplayerFollowTrackColors => 'மினிபிளேயரை டிராக் வண்ணங்களைப் பின்பற்ற கட்டாயப்படுத்து';

  @override
  String get forceSquaredAlbumThumbnail => 'ஆல்பத்தின் சிறுபடம் சதுர வடிவமாக கட்டாயமாக்கு';

  @override
  String get forceSquaredThumbnailNote => 'சிறுபடவுரு அளவு & டைல் உயரம் சமமாக இல்லை, சதுர வடிவ தோற்றம் எதிர்பார்த்தபடி இருக்காது, அவற்றை சமமாக்க விரும்புகிறீர்களா?';

  @override
  String get forceSquaredTrackThumbnail => 'பாடலின் சிறுபடம் சதுர வடிவமாக கட்டாயமாக்கு';

  @override
  String get forceStopColorPaletteGeneration => 'வண்ணத் தட்டுகளைப் பிரித்தெடுப்பதை கட்டாயமாக நிறுத்தவா? நீங்கள் அதை பின்னர் தொடரலாம்';

  @override
  String get format => 'வடிவம்';

  @override
  String get fullscreen => 'முழு திரை';

  @override
  String get gaplessPlayback => 'இடைவெளியற்ற பின்னணி';

  @override
  String get generate => 'உருவாக்கு';

  @override
  String get generateFromDates => 'நேர வரம்பு';

  @override
  String get generateFromDatesSubtitle => 'நீங்கள் கேட்ட டிராக்குகளை ஒரு குறிப்பிட்ட கால இடைவெளியில் உருவாக்குங்கள்';

  @override
  String get generateRandomPlaylist => 'சீரற்ற பிளேலிஸ்ட்டை உருவாக்கு';

  @override
  String get genre => 'வகை';

  @override
  String get genres => 'வகைகள்';

  @override
  String get goToAlbum => 'ஆல்பத்திற்கு செல்க';

  @override
  String get goToArtist => 'கலைஞருக்குச் செல்லவும்';

  @override
  String get goToChannel => 'சேனலுக்குச் செல்';

  @override
  String get goToFolder => 'கோப்புறைக்கு செல்க';

  @override
  String get goodLooking => 'அழகாக இருக்கிறது';

  @override
  String get grantStoragePermission => 'சேமிப்பக அனுமதியை வழங்கு';

  @override
  String get group => 'குழுவாக';

  @override
  String get groupArtworksByAlbum => 'ஆல்பத்தின் கலைப்படைப்புகளை குழுவாக்கு';

  @override
  String get guide => 'வழிகாட்டி';

  @override
  String get hapticFeedback => 'ஆப்டிக் கருத்து';

  @override
  String get heightOfAlbumTile => 'ஆல்பம் டைலின் உயரம்';

  @override
  String get heightOfTrackTile => 'ட்ராக் டைலின் உயரம்';

  @override
  String get hideSkipButtonAfter => 'பின் தவிர் பொத்தானை மறை';

  @override
  String get highMatches => 'அதிக பொருத்தங்கள்';

  @override
  String get highPerformance => 'உயர் செயல்திறன்';

  @override
  String get highlight => 'முன்னிலைப்படுத்தவும்';

  @override
  String get history => 'வரலாறு';

  @override
  String get historyImportMissingEntriesNote =>
      'இந்த உள்ளீடுகளை நூலகத்திற்குள் காண முடியவில்லை, அவை இருப்பதாக நீங்கள் நம்பினால், அவற்றை கைமுறையாகச் சேர்ப்பதைக் கருத்தில் கொள்ளவும்';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$oldTrackInfo க்கான $listensCountString கேட்பவர்கள் $newTrackInfo உடன் மாற்றப்படும், உறுதிப்படுத்தவா?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'முகப்பு';

  @override
  String get hook => 'கொக்கி';

  @override
  String get host => 'விருந்தோம்பி';

  @override
  String get hourFormat12 => '12 மணிநேர வடிவம்';

  @override
  String get hours => 'மணிநேரம்';

  @override
  String get iReadAndAgree => 'நான் படித்து ஒப்புக்கொள்கிறேன்';

  @override
  String get ifNotPlaying => 'பாடல் ஒலிக்கவில்லை என்றால்';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'செயலி பேட்டரியை மேம்படுத்தும்போது பதிவிறக்கங்களை வேகப்படுத்தலாம்';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'வரிசைப்படுத்தும்போது பொதுவான முன்னொட்டுகளைப் புறக்கணிக்கவும்';

  @override
  String get ignores => 'புறக்கணிக்க';

  @override
  String get imageSource => 'படத்தின் சான்று';

  @override
  String get immersiveMode => 'மூழ்கும் பயன்முறை';

  @override
  String get immersiveModeSubtitle => 'மினிபிளேயர் விரிவாக்கப்படும்போது நிலை & வழிசெலுத்தல் பட்டிகளை மறைக்கவும்';

  @override
  String get import => 'இறக்குமதி';

  @override
  String get importAll => 'அனைத்தையும் இறக்குமதி செய்';

  @override
  String get importLastFmHistory => 'LastFm வரலாற்றை இறக்குமதி செய்';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. $lastfmCsvLink க்குச் செல்லவும்\n\n2. உங்கள் பயனர்பெயரை உள்ளிட்டு, csv கோப்பைப் பெற்று பதிவிறக்கவும்.\n\n3. அடுத்த திரையில் இருந்து கோப்பைத் தேர்ந்தெடுக்கவும்.';
  }

  @override
  String get importTimeRange => 'இறக்குமதி நேர வரம்பு';

  @override
  String get importYoutubeHistory => 'YouTube வரலாற்றை இறக்குமதி செய்';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. $takeoutLink க்குச் செல்லவும்\n\n2. \"பல வடிவங்கள்\" என்பதை அழுத்தி, \"வரலாறு\" என்பதற்கு அருகில் \"JSON\" என்பதைத் தேர்ந்தெடுக்கவும்.\n\n3. \"அனைத்து YouTube தரவும் சேர்க்கப்பட்டுள்ளது\" என்பதை அழுத்தி, அனைத்தையும் தேர்வுநீக்கி வரலாற்றை மட்டும் தேர்வு செய்யவும்.\n\n4. ஏற்றுமதியை உருவாக்கு, பதிவிறக்கு & அன்சிப் செய்யவும்.\n\n5. அடுத்த திரையில் இருந்து \"watch-history.json\" என்பதைத் தேர்ந்தெடுக்கவும்.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString சேனல்கள் வெற்றிகரமாக இறக்குமதி செய்யப்பட்டன',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText சேனல்கள் வெற்றிகரமாக இறக்குமதி செய்யப்பட்டது',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'வீடியோக்களைச் சேர்க்கவும்';

  @override
  String get indexRefreshRequired => 'இதை மாற்றிய பின் புதுப்பிக்கவும்';

  @override
  String get indexer => 'குறியீட்டாளர்';

  @override
  String get indexerNote => 'குறிப்பு: முழுமையற்ற கலைப்படைப்புகளின் எண்ணிக்கை என்பது நகல் எடுக்கப்பட்ட & கண்டுபிடிக்கப்படாத கலைப்படைப்புகளைக் குறிக்கிறது';

  @override
  String get indexerSubtitle => 'உங்கள் இசை நூலகத்தை நிர்வகிக்கவும்';

  @override
  String get infinityQueueOnNextPrev => 'அடுத்தது/முந்தையதில் முடிவிலி வரிசை';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'கடைசி உருப்படியை இயக்கும்போது அடுத்து என்பதை அழுத்தினால் முதல் உருப்படிக்குச் செல்லும், அதற்கு நேர்மாறாகவும் நடக்கும்';

  @override
  String get info => 'தகவல்';

  @override
  String get inserted => 'செருகப்பட்டது';

  @override
  String get instantlyApplies => 'உடனடியாகப் பொருந்தும்';

  @override
  String get interactionReminder => 'தொடர்பு நினைவூட்டல்';

  @override
  String get intro => 'அறிமுகம்';

  @override
  String get invertSelection => 'தேர்வை தலைகீழாக மாற்று';

  @override
  String get issues => 'சிக்கல்கள்';

  @override
  String get item => 'பொருள்';

  @override
  String get jump => 'குதிக்கவும்';

  @override
  String get jumpToDay => 'நாளுக்குச் செல்லவும்';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'வரிசையை முடித்த பிறகு முதல் தடத்திற்குச் செல்லவும்';

  @override
  String get keepCachedVersions => 'தற்காலிக சேமிப்பு பதிப்புகளை வைத்திருங்கள்';

  @override
  String get keepFileDates => 'கோப்பு தேதிகளை வைத்திரு';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'மினிபிளேயர் விரிவாக்கப்பட்டுள்ளது';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'மினிபிளேயர் விரிவாக்கப்பட்டு ஒரு வீடியோ இயங்குகிறது';

  @override
  String get keepScreenAwakeNone => 'திரையை விழித்திருக்க வைக்காதே';

  @override
  String get keepScreenAwakeWhen => 'திரையை விழித்திருக்கச் செய்யும் போது';

  @override
  String get killPlayerAfterDismissingApp => 'செயலியை நிராகரித்த பிறகு பிளேயரைக் கொல்லுங்கள்';

  @override
  String get language => 'மொழி';

  @override
  String get learnMore => 'மேலும் அறிக';

  @override
  String get leftAction => 'இடது நடவடிக்கை';

  @override
  String get legacyAuthentication => 'மரபு ஏற்பு';

  @override
  String get libraryTabs => 'நூலக தாவல்கள்';

  @override
  String get libraryTabsReorder => 'செயல்படுத்தப்பட்ட தாவல்களை நீங்கள் மறுவரிசைப்படுத்தலாம்.';

  @override
  String get license => 'உரிமம்';

  @override
  String get licenseSubtitle => 'நமிடா பயன்படுத்தும் உரிமங்கள் மற்றும் ஒப்பந்தங்கள்';

  @override
  String get like => 'பிடிக்கும்';

  @override
  String get liked => 'பிடித்தது';

  @override
  String get link => 'இணைப்பு';

  @override
  String get listOfFolders => 'கோப்புறைகளின் பட்டியல்';

  @override
  String get loadAll => 'அனைத்தையும் ஏற்று';

  @override
  String get loadingFile => 'கோப்பை ஏற்றுகிறது';

  @override
  String get local => 'உள்ளூர';

  @override
  String get localVideoMatching => 'உள்ளூர் வீடியோ பொருத்தம்';

  @override
  String get login => 'புகுபதிவு';

  @override
  String get longPressAction => 'நீண்ட அழுத்த நடவடிக்கை';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'முழுத்திரையில் நுழைய பாடல் வரிகளை நீண்ட நேரம் அழுத்தவும்';

  @override
  String get lostMemories => 'இழந்த நினைவுகள்';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'இதே நேரத்தில், $numberString ஆண்டுகளுக்கு முன்பு',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'இழந்த பங்குதாரர்கள்';

  @override
  String get loudnessEnhancer => 'சத்தத்தை அதிகரிக்கும் கருவி';

  @override
  String get lyricist => 'பாடலாசிரியர்';

  @override
  String get lyrics => 'பாடல் வரிகள்';

  @override
  String get lyricsSource => 'பாடல் வரிகள் ஆதாரம்';

  @override
  String get m3uPlaylist => 'M3U பிளேலிஸ்ட்';

  @override
  String get makeYourFirstListen => 'நீங்கள் கேட்கும் முதல் பாட்டாக மாற்றுங்கள்!';

  @override
  String get manage => 'நிர்வகிக்கவும்';

  @override
  String get manageYourAccounts => 'உங்கள் கணக்குகளை நிர்வகிக்கவும்';

  @override
  String get manualBackup => 'கையேடு';

  @override
  String get manualBackupSubtitle => 'ஒரு குறிப்பிட்ட கோப்பை எடு';

  @override
  String get markAsRead => 'படித்ததாகக் குறி';

  @override
  String get matchAllTracks => 'எல்லா டிராக்குகளையும் பொருத்து';

  @override
  String get matchAllTracksNote => 'இது உங்கள் நூலகத்தில் உள்ள அனைத்து தடங்களையும் சரிபார்க்கும் என்பதால், பொருத்த வேகத்தில் தாக்கத்தை ஏற்படுத்தலாம்';

  @override
  String get matchingType => 'பொருந்தும் வகை';

  @override
  String get maxAudioCacheSize => 'அதிகபட்ச ஆடியோ கேச் அளவு';

  @override
  String get maxImageCacheSize => 'அதிகபட்ச பட தற்காலிக சேமிப்பு அளவு';

  @override
  String get maxVideoCacheSize => 'அதிகபட்ச வீடியோ கேச் அளவு';

  @override
  String get maximum => 'அதிகபட்ச';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'மீடியா கடை இயக்கப்பட்டுள்ளது, இது எந்த விளைவையும் ஏற்படுத்தாது';

  @override
  String get medium => 'சராசரி';

  @override
  String get membershipCode => 'குறியீடு';

  @override
  String get membershipCodeSentToEmail => 'உங்கள் மின்னஞ்சலுக்கு குறியீடு அனுப்பப்பட்டது';

  @override
  String get membershipDidntChange => 'உறுப்பினர் மாறவில்லை';

  @override
  String get membershipEnjoyNew => 'உங்கள் புதிய மெம்பர்ஷிப்பை அனுபவியுங்கள்';

  @override
  String get membershipFreeCoupon => 'இலவச கூப்பன்';

  @override
  String get membershipManage => 'உங்கள் உறுப்பினர் நிலையை நிர்வகிக்கவும்';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'இந்தப் பயனருக்கான சந்தாக்கள் எதுவும் இல்லை';

  @override
  String get membershipSignInToPatreonAccount => 'உங்கள் புரவலர் கணக்கில் உள்நுழையவும்';

  @override
  String get membershipUnknown => 'அறியப்படாத உறுப்பினர்';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'பல கணக்குகளைச் சேர்க்க $name1 அல்லது $name2 இன் உறுப்பினர் தேவை';
  }

  @override
  String get merge => 'ஒன்றிணை';

  @override
  String get metadataCache => 'மெட்டாடேட்டா தற்காலிக சேமிப்பு';

  @override
  String get metadataEditFailed => 'மெட்டாடேட்டாவை திருத்துவதில் தோல்வி';

  @override
  String get metadataReadFailed => 'மெட்டாடேட்டாவைப் படிப்பதில் தோல்வி';

  @override
  String get minFileDuration => 'குறைந்தபட்ச டிராக் காலம்';

  @override
  String get minFileSize => 'குறைந்தபட்ச கோப்பு அளவு';

  @override
  String get minTrackDurationToRestoreLastPosition => 'கடைசியாக வாசிக்கப்பட்ட பாடலை மீட்டமைக்க குறைந்தபட்ச டிராக் கால அளவு';

  @override
  String get minValueCantBeMoreThanMax => 'குறைந்தபட்ச மதிப்பு அதிகபட்சத்தை விட அதிகமாக இருக்கக்கூடாது';

  @override
  String get minValueToCountTrackListen => 'பிறகு கேளுங்கள் என்று எண்ணுங்கள்: ';

  @override
  String get minimizedMiniplayer => 'சிறிதாக்கப்பட்ட மினிபிளேயர்';

  @override
  String get minimum => 'குறைந்தபட்சம்';

  @override
  String get minimumOneFolderSubtitle => 'குறைந்தது ஒரு கோப்புறையாவது இருக்க வேண்டும், இதை நீக்க விரும்பினால் மேலும் கோப்புறைகளைச் சேர்க்கவும்';

  @override
  String get minimumOneItem => 'பொருளை அகற்ற முடியவில்லை';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'குறைந்தது $numberString உருப்படிகளாவது இருக்க வேண்டும்',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'குறைந்தபட்ச பிரிவு காலம்';

  @override
  String get miniplayerCustomization => 'மினிபிளேயர் தனிப்பயனாக்கம்';

  @override
  String get minutes => 'நிமிடங்கள்';

  @override
  String get missingEntries => 'விடுபட்ட உள்ளீடுகள்';

  @override
  String get missingTracks => 'காணாமல் போன தடங்கள்';

  @override
  String get mix => 'கலவை';

  @override
  String get mixPlaylistGeneratedByYoutube => 'யூடியூப் மூலம் உருவாக்கப்பட்ட மிக்ஸ் பிளேலிஸ்ட்';

  @override
  String get mixes => 'கலவைகள்';

  @override
  String get mobile => 'மொபைல்';

  @override
  String get month => 'மாதம்';

  @override
  String get months => 'மாதங்கள்';

  @override
  String get mood => 'மனநிலை';

  @override
  String get moods => 'மனநிலைகள்';

  @override
  String get more => 'மேலும்';

  @override
  String get mostPlayed => 'அதிகம் கேட்கப்பட்ட';

  @override
  String get multipleTracksTagsEditNote => 'நீங்கள் இந்த தடங்களைத் திருத்தப் போகிறீர்கள்,\nமாற்றப்படாத புலங்கள் தொடப்படாமல் இருக்கும்.';

  @override
  String get musicOfftopic => 'இசை ஆஃப்டோபிக்';

  @override
  String get name => 'பெயர்';

  @override
  String get nameContainsBadCharacter => 'பெயரில் அனுமதிக்கப்படாத எழுதுரு உள்ளது';

  @override
  String get never => 'ஒருபோதும் இல்லை';

  @override
  String get newDirectory => 'புதிய கோப்பகம்';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'தடங்களைச் சேர்க்க';

  @override
  String get newTracksMoods => 'மனோநிலை';

  @override
  String get newTracksMoodsSubtitle => 'கிடைக்கும் மனநிலையின் அடிப்படையில் தடங்களை உருவாக்கவும்';

  @override
  String get newTracksRandom => 'சீரற்ற';

  @override
  String get newTracksRandomSubtitle => 'புதிய ட்ராக்குகள் ரேண்டம் துணைத் தலைப்பு';

  @override
  String get newTracksRatings => 'மதிப்பீடுகள்';

  @override
  String get newTracksRatingsSubtitle => 'குறிப்பிட்ட மதிப்பீட்டைக் கொண்ட தடங்களை உருவாக்குங்கள்';

  @override
  String get newTracksRecommended => 'பரிந்துரைக்கப்படுகிறது';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return '$currentTrack உடன் நீங்கள் வழக்கமாகக் கேட்ட டிராக்குகளை உருவாக்குங்கள்';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'இதேபோன்ற வெளியீட்டு தேதி';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return '$currentTrack வெளியிடப்பட்ட அதே நேரத்தில் வெளியிடப்பட்ட டிராக்குகளை உருவாக்கவும்';
  }

  @override
  String get newTracksUnknownYear => 'ட்ராக் அறியப்படாத ஆண்டு';

  @override
  String get newest => 'புதியது';

  @override
  String get next => 'அடுத்து';

  @override
  String get no => 'இல்லை';

  @override
  String get noChangesFound => 'எந்த மாற்றங்களும் காணப்படவில்லை.';

  @override
  String get noEnoughTracks => 'உங்களிடம் அதிக தடங்கள் இல்லை.';

  @override
  String get noExcludedFolders => 'விலக்கப்பட்ட கோப்புறைகள் எதுவும் உங்களிடம் இல்லை';

  @override
  String get noFolderChosen => 'நீங்கள் எந்த கோப்புறையையும் தேர்வு செய்யவில்லை';

  @override
  String get noMoodsAvailable => 'எந்த மனநிலையும் இல்லை';

  @override
  String get noNetworkAvailableToFetchData => 'தரவைப் பெற எந்த நெட்வொர்க்கும் கிடைக்கவில்லை';

  @override
  String get noTracksFound => 'எந்த தடங்களும் கிடைக்கவில்லை';

  @override
  String get noTracksFoundBetweenDates => 'இந்த நேர வரம்பில் எந்த தடங்களும் இல்லை.';

  @override
  String get noTracksFoundInDirectory => 'இந்த கோப்பகத்தில் எந்த தடங்களும் கிடைக்கவில்லை';

  @override
  String get noTracksInHistory => 'வரலாற்றில் போதுமான தடங்கள் உங்களிடம் இல்லை';

  @override
  String get nonActive => 'செயலில் இல்லாதது';

  @override
  String get nonFavourites => 'விருப்பமற்றவை';

  @override
  String get none => 'எதுவும் இல்லை';

  @override
  String get normalizeAudio => 'ஆடியோவை இயல்பாக்கு';

  @override
  String get normalizeAudioSubtitle => 'ரீப்ளே கெயின் டேக் அல்லது யூடியூப் வழங்கிய தகவலைப் படிப்பதன் மூலம் ஒலியளவை இயல்பாக்குகிறது';

  @override
  String get notAvailableForYourDevice => 'உங்கள் சாதனத்திற்கு கிடைக்கவில்லை';

  @override
  String get notSupportedForNetworkFiles => 'பிணைய கோப்புகள் ஆதரிக்கப்படவில்லை';

  @override
  String get note => 'குறிப்பு';

  @override
  String get notification => 'அறிவிப்பு';

  @override
  String get notifications => 'அறிவிப்புகள்';

  @override
  String get numberOfTracks => 'தடங்களின் எண்ணிக்கை';

  @override
  String get ofLabel => 'இன்';

  @override
  String get offlineSearch => 'ஆஃப்லைன் தேடல்';

  @override
  String get offset => 'ஆஃப்செட்';

  @override
  String get oldDirectory => 'பழைய கோப்பகம்';

  @override
  String get oldDirectoryStillHasTracks => 'பழைய டைரக்டரியில் இன்னும் சில டிராக்குகள் உள்ளன, உறுதியா?';

  @override
  String get oldestWatch => 'பார்க்கப்பட்டவற்றில் மிகப் பழமையானது';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'குறுக்கீடு செய்யப்பட்டது';

  @override
  String get onNotificationTap => 'அறிவிப்பு தட்டலில்';

  @override
  String get onOpeningYoutubeLink => 'யூடியூப் இணைப்பைத் திறக்கும்போது';

  @override
  String get onSwiping => 'ஸ்வைப் செய்யும்போது';

  @override
  String get onVolumeZero => 'சத்தம் 0 அளவில்';

  @override
  String get ongoing => 'நடந்து கொண்டிருக்கிறது';

  @override
  String get open => 'திற';

  @override
  String get openApp => 'பயன்பாட்டைத் திற';

  @override
  String get openInFileExplorer => 'கோப்பு எக்ச்ப்ளோரரில் திறக்கவும்';

  @override
  String get openInYoutubeView => 'Youtube காட்சியில் திறக்கவும்';

  @override
  String get openMiniplayer => 'மினிபிளேயரைத் திற';

  @override
  String get openQueue => 'வரிசையைத் திற';

  @override
  String get openYoutubeLink => 'யூடியூப் இணைப்பைத் திறக்கவும்';

  @override
  String operationRequiresAccount({required String name}) {
    return '$name செயல்பாட்டிற்கு கணக்கு தேவை, தொடர உள்நுழையவும்';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return '$operation செயல்பாட்டிற்கு குறைந்தபட்சம் $name உறுப்பினர் தேவை';
  }

  @override
  String get or => 'அல்லது';

  @override
  String get others => 'மற்றவைகள்';

  @override
  String get output => 'வெளியீட்டு';

  @override
  String get outro => 'மற்றவை';

  @override
  String get overrideOldFilesInTheSameFolder => 'அதே கோப்புறையில் உள்ள பழைய கோப்புகளின் மேலெழுது';

  @override
  String get palette => 'பலகை';

  @override
  String get paletteMix => 'கலக்க';

  @override
  String get paletteNewMix => 'புதிய கலவை';

  @override
  String get paletteSelectedMix => 'தேர்ந்தெடுக்கப்பட்ட கலவை';

  @override
  String get parallelDownloads => 'இணை பதிவிறக்கம்';

  @override
  String get parsed => 'பாகுபடுத்தப்பட்டது';

  @override
  String get password => 'கடவுச்சொல்';

  @override
  String get path => 'கோப்பு முழு பாதை';

  @override
  String get pause => 'இடைநிறுத்து';

  @override
  String get pauseFadeDuration => 'மங்கலான கால அளவை இடைநிறுத்து';

  @override
  String get pausePlayback => 'பிளேபேக்கை இடைநிறுத்து';

  @override
  String get percentage => 'சதவீதம்';

  @override
  String get performanceMode => 'செயல்திறன் முறை';

  @override
  String get performanceNote => 'செயல்திறனைப் பாதிக்கலாம்';

  @override
  String get personalized => 'தனிப்பயனாக்கப்பட்டது';

  @override
  String get personalizedRelatedVideos => 'யூடியூப் தனிப்பயனாக்கப்பட்ட தொடர்புடைய வீடியோ';

  @override
  String get personalizedRelatedVideosSubtitle => 'இதை முடக்குவது தரவு பயன்பாட்டை அதிகரிக்கும்';

  @override
  String get pickColorsFromDeviceWallpaper => 'சாதன வால்பேப்பரிலிருந்து வண்ணங்களைத் தேர்ந்தெடுக்கவும்';

  @override
  String get pickFromStorage => 'சேமிப்பகத்திலிருந்து எடு';

  @override
  String get pinned => 'பின் செய்யப்பட்டது';

  @override
  String get pitch => 'சுருதி';

  @override
  String get plain => 'சமவெளி';

  @override
  String get play => 'இயக்கு';

  @override
  String get playAfter => 'இதற்கு பிறகு இயக்கு';

  @override
  String get playAfterNextPrev => 'அடுத்தது/முந்தையதில் தானாக இயக்கவும்';

  @override
  String get playAll => 'அனைத்தையும் இயக்கு';

  @override
  String get playFadeDuration => 'மங்கலான கால அளவைத் தொடங்கு';

  @override
  String get playLast => 'கடைசியானவற்றை இயக்கு';

  @override
  String get playNext => 'அடுத்ததாக இயக்கு';

  @override
  String get playbackSetting => 'பின்னணி';

  @override
  String get playbackSettingSubtitle => 'ஆடியோ பொத்தானை நீண்ட நேரம் அழுத்துவதன் மூலம் பிளேயரில் நேரடியாக அணுகலாம்';

  @override
  String get playlist => 'பாடல் பட்டியல்';

  @override
  String get playlists => 'பாடல் பட்டியல்கள்';

  @override
  String get playlistsImportM3uNative => 'இது நமீடாவால் மட்டுமே பயன்படுத்த M3U பிளேலிஸ்ட்களை இறக்குமதி செய்யும், நீங்கள் இடம்பெயர்ந்தால் பயன்படுத்தவும்';

  @override
  String get playlistsImportM3uSynced =>
      'இது இன்டெக்ஸர் கோப்புறைகளிலிருந்து M3U பிளேலிஸ்ட்களை தானாகவே இறக்குமதி செய்து, அவற்றை அசல் M3U கோப்போடு ஒத்திசைத்து வைத்திருக்கும். பிற பயன்பாடுகளிலிருந்து பிளேலிஸ்ட்களை அணுகினால்/மாற்றியமைத்தால் இயக்கவும்';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'M3U பிளேலிஸ்ட்களை தானாக இறக்குமதி செய்';

  @override
  String get pleaseEnterADifferentName => 'இந்தப் பெயர் ஏற்கனவே உள்ளது :(\nவேறொரு பெயரை முயற்சிக்கவும்';

  @override
  String get pleaseEnterALink => 'இணைப்பை உள்ளிடவும்';

  @override
  String get pleaseEnterALinkSubtitle => 'ம்ம் ... இது யூடியூப் இணைப்புதானா?';

  @override
  String get pleaseEnterAName => 'தயவுசெய்து ஒரு பெயரை உள்ளிடவும்';

  @override
  String get port => 'துறைமுகம்';

  @override
  String get preventDuplicatedTracks => 'நகல் தடங்களை தடு';

  @override
  String get preventDuplicatedTracksSubtitle => 'தடங்களை தனித்துவமாக அடையாளம் காண கோப்புப் பெயரைப் பயன்படுத்தவும்';

  @override
  String get preview => 'முன்னோட்டம்';

  @override
  String get previous => 'முந்தைய';

  @override
  String get previousButtonReplays => 'முந்தைய பொத்தான் மறு இயக்கமாகும்';

  @override
  String get previousButtonReplaysSubtitle => 'தற்போதைய நிலை தேடு கால அளவை விட அதிகமாக இருக்கும்போது அழுத்தினால்';

  @override
  String get prioritizeEmbeddedLyrics => 'உட்பொதிக்கப்பட்ட பாடல் வரிகளுக்கு முன்னுரிமை கொடுங்கள்';

  @override
  String get priority => 'முன்னுரிமை';

  @override
  String get private => 'தனிப்பட்ட';

  @override
  String get progress => 'முன்னேற்றம்';

  @override
  String get promptToChangeTrackPath =>
      'பொதுவாக இது நமிடாவின் வெளியே கோப்பை நீக்கும்போது/நகர்த்தும்போது/மறுபெயரிடும்போது நடக்கும். தற்போதைய பாதையைப் புதுப்பிக்க விரும்புகிறீர்களா?';

  @override
  String get public => 'பொது';

  @override
  String get queue => 'வரிசை';

  @override
  String get queues => 'வரிசைகள்';

  @override
  String get random => 'சீரற்ற';

  @override
  String get randomPicks => 'சீரற்ற தேர்வுகள்';

  @override
  String get rating => 'மதிப்பீடு';

  @override
  String get reIndex => 'மறு அட்டவணைப்படுத்தல்';

  @override
  String get reIndexSubtitle => 'உங்கள் இசை நூலகத்தை புதிதாக உருவாக்குங்கள்';

  @override
  String get reIndexWarning => 'உங்கள் நூலக அளவைப் பொறுத்து இந்த செயல்முறை சிறிது நேரம் ஆகலாம்.\n\nகலைப்படைப்புகள் இருக்கும் வரை அவை மீண்டும் அட்டவணைப்படுத்தப்படாது';

  @override
  String get recentAlbums => 'சமீபத்திய ஆல்பங்கள்';

  @override
  String get recentArtists => 'சமீபத்திய கலைஞர்கள்';

  @override
  String get recentListens => 'சமீபத்தில் கேட்டவை';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'சமீபத்தில் சேர்க்கப்பட்டது';

  @override
  String get recordLabel => 'இசைப்பதிவுத்தட்டு லேபிள்';

  @override
  String get refresh => 'புதுப்பிக்க';

  @override
  String get refreshLibrary => 'நூலகத்தைப் புதுப்பிக்கவும்';

  @override
  String get refreshLibrarySubtitle => 'புதிதாக இசை சேர்க்கப்பட்டு அல்லது நீக்கப்பட்டு உள்ளதா என பார்க்கவும்';

  @override
  String get refreshOnStartup => 'தொடங்கும் போது புதுப்பிக்க';

  @override
  String get relatedVideos => 'தொடர்பான காணொளிகள்';

  @override
  String get rememberAudioOnlyMode => 'ஆடியோ மட்டும் பயன்முறையை நினைவில் கொள்க';

  @override
  String get remixer => 'ரீமிக்சர்';

  @override
  String get remove => 'நீக்கவும்';

  @override
  String get removeDuplicates => 'நகல்களை அகற்று';

  @override
  String get removeFromFavourites => 'பிடித்தவையிலிருந்து அகற்று';

  @override
  String get removeFromLibrary => 'நூலகத்திலிருந்து நீக்கு';

  @override
  String get removeFromPlaylist => 'பிளேலிஸ்ட்டில் இருந்து நீக்கு';

  @override
  String get removeQueue => 'வரிசையை அகற்று';

  @override
  String get removeSourceFromHistory => 'வரலாற்றிலிருந்து மூலத்தை அகற்று';

  @override
  String get removeWhitespaces => 'இடைவெளிகளை அகற்று';

  @override
  String get removed => 'அகற்றப்பட்டது';

  @override
  String get rename => 'மறுபெயரிடு';

  @override
  String get renamePlaylist => 'பிளேலிஸ்ட்டின் பெயரை மாற்றவும்';

  @override
  String get reorderable => 'மறுவரிசைப்படுத்தக்கூடியது';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'இன்னும் $number முறை இயக்கவும்',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'மீண்டும் முறை';

  @override
  String get repeatModeAll => 'வரிசையில் இருந்து அனைத்தையும் இயக்கு';

  @override
  String get repeatModeNone => 'கடைசி பாடலுடன் நிறுத்தவும்';

  @override
  String get repeatModeOne => 'தற்போதைய பாடலை மீண்டும் கேட்க';

  @override
  String get replaceAllListensWithAnotherTrack => 'எல்லாக் கேட்டல்களையும் வேறொரு பாடலால் மாற்றவும்';

  @override
  String get replies => 'பதில்கள்';

  @override
  String get reply => 'பதில்';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'பட தற்காலிக சேமிப்பை அழித்து மறு அட்டவணைப்படுத்தல் தேவை';

  @override
  String get rescanVideos => 'வீடியோக்களை மீண்டும் ஸ்கேன் செய்யவும்';

  @override
  String get resetBrightness => 'பிரகாசத்தை மீட்டமை';

  @override
  String get resetToDefault => 'அமைக்கவும்';

  @override
  String get respectNoMedia => '.nomedia வை மதிக்கவும்';

  @override
  String get respectNoMediaSubtitle => '.nomedia வில் உள்ள கோப்புறைகளைச் சேர்க்க வேண்டாம்';

  @override
  String get restart => 'மறுதொடக்கம்';

  @override
  String get restoreBackup => 'காப்புப்பிரதியை மீட்டமை';

  @override
  String get restoreDefaults => 'இயல்புநிலைகளை மீட்டமை';

  @override
  String get restoredBackupSuccessfully => 'மீட்டெடுக்கப்பட்ட காப்புப்பிரதி';

  @override
  String get restoredBackupSuccessfullySub => 'காப்புப்பிரதி கோப்பு வெற்றிகரமாக மீட்டமைக்கப்பட்டது';

  @override
  String get resume => 'மீண்டும் தொடர்';

  @override
  String get resumeIfWasInterrupted => 'குறுக்கீட்டால் நிறுத்தப்பட்டிருந்தால் மீண்டும் தொடங்கு';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'ஒலியளவால் நிறுத்தப்பட்டிருந்தால் மீண்டும் தொடங்கு';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString நிமிடங்களுக்கும் குறைவாக இடைநிறுத்தப்பட்டிருந்தால் மீண்டும் தொடங்கு',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Youtube விருப்பமின்மையைத் திரும்பப் பெறவும்';

  @override
  String get reverseOrder => 'தலைகீழ் வரிசை';

  @override
  String get rightAction => 'சரியான நடவடிக்கை';

  @override
  String get ringtone => 'ரிங் டோன்';

  @override
  String get sameDirectoryOnly => 'ஒரே கோப்பகம் மட்டும்';

  @override
  String get sample => 'மாதிரி';

  @override
  String get sampleRate => 'மாதிரியெடுப்பு வீதம்';

  @override
  String get save => 'சேமி';

  @override
  String get saveToLibrary => 'நூலகத்தில் சேமிக்கவும்';

  @override
  String get savedIn => 'சேமிக்கப்பட்டது';

  @override
  String get scaleMultiplier => 'அளவுகோல் பெருக்கி';

  @override
  String get search => 'தேடு';

  @override
  String get searchYoutube => 'யூடியூபில் தேடு';

  @override
  String get seconds => 'வினாடிகள்';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return '$site இல் திட்டக் குறியீட்டைப் பார்க்கவும்';
  }

  @override
  String get seekDuration => 'முன்னேற்றப்பட்டை கால அளவு';

  @override
  String get seekDurationInfo => 'பின்னோக்கிச் செல்ல தற்போதைய கால அளவையும், முன்னோக்கிச் செல்ல மொத்த கால அளவையும் தட்டலாம்';

  @override
  String get seekbar => 'முன்னேற்றப் பட்டை';

  @override
  String get selectAll => 'அனைத்தையும் தேர்ந்தெடுக்கவும்';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'உள்ளக நூலகத்தில் ஏற்கனவே உள்ள கோப்புகளைத் தேர்ந்தெடுக்கவும்';

  @override
  String get selectedTracks => 'தேர்ந்தெடுக்கப்பட்ட பாடல்கள்';

  @override
  String get selfPromotion => 'தன்வய விளம்பரம்';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'இந்த வார்த்தைகள் பிரிக்கப்படாது';

  @override
  String get separatorsMessage =>
      'ஒரு முழு வார்த்தையில் (x மற்றும் ft போன்றவை) காணக்கூடிய ஒரு எழுத்து/குறியீட்டைப் பயன்படுத்த விரும்பினால் தவிர, இடைவெளிகளைச் செருக வேண்டிய அவசியமில்லை';

  @override
  String get serverAddress => 'சேவையக முகவரி';

  @override
  String get setAs => 'என அமைக்க';

  @override
  String get setAsDefault => 'இயல்புநிலையாக அமை';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'கோப்பை கடைசியாக வீடியோ பதிவேற்ற தேதியாக அமைக்கவும்';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'மனநிலைகளை அமைக்கவும்';

  @override
  String get setMoodsSubtitle => 'அவற்றுக்கிடையே பிரிக்க காற்புள்ளிகளைப் (,) பயன்படுத்தவும்';

  @override
  String get setRating => 'மதிப்பீட்டை அமைக்கவும்';

  @override
  String get setTags => 'குறிச்சொற்களை அமைக்கவும்';

  @override
  String get setYoutubeLink => 'யூடியூப் இணைப்பை அமைக்கவும்';

  @override
  String get settings => 'அமைப்புகள்';

  @override
  String get setupFirstStartup => 'முதல் தொடக்கத்தை அமைக்கவும்';

  @override
  String get share => 'பகிர்';

  @override
  String get shareLogs => 'பகிர்வு பதிவுகள்';

  @override
  String get shortcuts => 'குறுக்குவழிகள்';

  @override
  String get shouldDuck => 'வாத்து வேண்டும்';

  @override
  String get shouldDuckNote => 'ஒலியளவைக் குறைக்க வேண்டும் என்பதைக் குறிக்கிறது. எ.கா: அறிவிப்பு';

  @override
  String get shouldPause => 'இடைநிறுத்த வேண்டும்';

  @override
  String get shouldPauseNote => 'பிளேபேக் இடைநிறுத்தப்பட வேண்டும் என்பதைக் குறிக்கிறது. எ.கா: அழைப்புகள்';

  @override
  String get showAll => 'அனைத்தையும் காட்டு';

  @override
  String get showChannelWatermarkInFullscreen => 'சேனல் வாட்டர்மார்க்கை முழுத்திரையில் காட்டு';

  @override
  String get showFailedOnly => 'தோல்வியடைந்ததை மட்டும் காட்டு';

  @override
  String get showHideUnknownFields => 'தெரியாத புலங்களைக் காட்டு/மறை';

  @override
  String get showInSeekbar => 'சீக்பாரில் காட்டு';

  @override
  String get showMixPlaylistsIn => 'மிக்ஸ்களைக் காட்டு';

  @override
  String get showMore => 'மேலும் காட்டு';

  @override
  String get showShortVideosIn => 'சிறிய வீடியோக்களைக் காட்டு';

  @override
  String get showSkipButton => 'தவிர் பொத்தானைக் காட்டு';

  @override
  String get showVideoEndcards => 'வீடியோ எண்ட்கார்டுகளைக் காட்டு';

  @override
  String get showWebm => 'webm காட்டு';

  @override
  String get shuffle => 'கலக்கு';

  @override
  String get shuffleAll => 'அனைத்தையும் கலக்கு';

  @override
  String get shuffleNext => 'அடுத்ததைக் கலக்கவும்';

  @override
  String get signIn => 'உள்நுழையவும்';

  @override
  String get signInCanceled => 'உள்நுழைவு ரத்து செய்யப்பட்டது';

  @override
  String get signInFailed => 'உள்நுழைவு தோல்வியடைந்தது';

  @override
  String get signInToYourAccount => 'உங்கள் கணக்கில் உள்நுழையவும்';

  @override
  String get signInYouDontHaveAccount => 'உங்களிடம் உள்நுழைந்த கணக்கு எதுவும் இல்லை';

  @override
  String get signInYouNeedAccountToViewPage => 'இந்தப் பக்கத்தைக் காண உங்களுக்கு ஒரு கணக்கு தேவை';

  @override
  String get signOut => 'வெளியேறுங்கள்';

  @override
  String signOutFromName({required String name}) {
    return '$name லிருந்து வெளியேறு';
  }

  @override
  String get signingInAllowsBasicUsage => 'உள்நுழைவது அடிப்படை பயன்பாட்டை அனுமதிக்கிறது';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Patreon மூலமாகவோ அல்லது கூப்பன் மூலமாகவோ ஆரம்ப அணுகலைப் பெறுங்கள்';

  @override
  String get similarDiscoverDate => 'இதே போன்ற கண்டுபிடிப்பு தேதி';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return '$currentTrack போன்ற அதே நேரத்தில் கண்டுபிடிக்கப்பட்ட தடங்களை உருவாக்கவும்';
  }

  @override
  String get similarTimeRange => 'இதே போன்ற நேர வரம்பு';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return '$currentTrack போன்ற அதே நேரத்தில் நீங்கள் கேட்ட டிராக்குகளை உருவாக்கவும்';
  }

  @override
  String get singles => 'ஒற்றையர்';

  @override
  String get size => 'அளவு';

  @override
  String get skip => 'தவிர்';

  @override
  String get skipCountTracking => 'எண்ணிக்கை கண்காணிப்பைத் தவிர்க்கவும்';

  @override
  String get skipSilence => 'அமைதியைத் தவிர்';

  @override
  String get skipSponsorSegmentsInVideos => 'வீடியோக்களில் ஒப்புரவாளர் பிரிவுகளைத் தவிர்க்கவும்';

  @override
  String get sleepAfter => 'பிறகு தூங்கு';

  @override
  String get sleepTimer => 'தூக்க நேரம்';

  @override
  String get socials => 'சமூகங்கள்';

  @override
  String get socialsSubtitle => 'புதுப்பிப்புகள், உதவிக்குறிப்புகள், கலந்துரையாடல் மற்றும் யோசனைகளுக்கு எங்கள் தளங்களில் எங்களுடன் சேருங்கள்';

  @override
  String get someWebServersRequireAuthentication => 'சில இணைய சேவையகங்களுக்கு ஏற்பு தேவை. உங்கள் நூலகத்திற்கான அணுகலைப் பராமரிக்க நற்சான்றிதழ்களைப் புதுப்பிக்கவும்.';

  @override
  String get sortBy => 'வரிசைப்படுத்து';

  @override
  String get source => 'ஆதாரம்';

  @override
  String get speed => 'வேகம்';

  @override
  String get sponsor => 'ஒப்புரவாளர்';

  @override
  String get sponsorblock => 'ஒப்புரவாளர் பிளாக்';

  @override
  String get sponsorblockLeaderboard => 'ஒப்புரவாளர் பிளாக் லீடர்போர்டு';

  @override
  String get staggeredAlbumGridView => 'தடுமாறிய ஆல்பம் கட்டக்காட்சி';

  @override
  String get start => 'தொடங்கு';

  @override
  String get stats => 'புள்ளிவிவரங்கள்';

  @override
  String get statsSubtitle => 'உங்கள் நூலகம் பற்றிய சில தகவல்கள் இங்கே';

  @override
  String get stop => 'நிறுத்து';

  @override
  String get stopAfterThisTrack => 'இந்தப் பாடலுக்குப் பிறகு நிறுத்து';

  @override
  String get stopAfterThisVideo => 'இந்த வீடியோவுக்குப் பிறகு நிறுத்து';

  @override
  String get storagePermissionDenied => 'அனுமதி மறுக்கப்பட்டது';

  @override
  String get storagePermissionDeniedSubtitle => 'இந்தச் செயலைச் செய்ய அணுகலை அனுமதிக்கவும்';

  @override
  String get stretchLyricsDuration => 'நீட்சி வரிகள் கால அளவு';

  @override
  String get subdirectory => 'துணை அடைவு';

  @override
  String get subscribe => 'பதிவு செய்யுங்கள்';

  @override
  String get subscribed => 'பதிவு செய்யுப்பட்டது';

  @override
  String get subscriber => 'சந்தாதாரர்';

  @override
  String get subscribers => 'சந்தாதாரர்கள்';

  @override
  String get succeeded => 'வெற்றி பெற்றது';

  @override
  String suggestionSubtitle({required String site}) {
    return 'ஏதேனும் சிக்கல் அல்லது பரிந்துரை உள்ளதா? $site இல் சிக்கலைத் திறக்கவும்';
  }

  @override
  String get support => 'ஆதரவு';

  @override
  String get supremacy => 'மேலாதிக்கம்';

  @override
  String get sussyBaka => 'ப்ரூஹ் தடங்கள் இல்லை';

  @override
  String get swipeActions => 'ச்வைப் செயல்கள்';

  @override
  String get swipeToOpenDrawer => 'டிராயரைத் திறக்க ஸ்வைப் செய்யவும்';

  @override
  String get synced => 'ஒத்திசைக்கப்பட்டது';

  @override
  String get synopsis => 'சுருக்கம்';

  @override
  String get tagFields => 'குறிச்சொல் புலங்கள்';

  @override
  String get tags => 'குறிச்சொற்கள்';

  @override
  String get tapAction => 'செயலைத் தட்டவும்';

  @override
  String get tapToSeek => 'தேட தட்டவும்';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'தீம் பயன்முறை';

  @override
  String get themeModeDark => 'இருள்';

  @override
  String get themeModeLight => 'ஒளி';

  @override
  String get themeModeSystem => 'அமைப்பு';

  @override
  String get themeSettings => 'தீம்';

  @override
  String get themeSettingsSubtitle => 'உங்கள் மியூசிக் பிளேயரின் ஒட்டுமொத்த சூழல்';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'இந்த பிளேலிச்ட்டில் செயலில் உள்ள வரிசையாக்கங்கள் உள்ளன, மறுவரிசைப்படுத்துவதற்கு முன் அவற்றை முடக்கவும்.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'இந்த வீடியோ நீக்கப்பட்டிருக்கலாம் அல்லது தனிப்பட்டதாக அமைக்கப்பட்டிருக்கலாம்.';

  @override
  String get thumbnails => 'சிறுபடங்கள்';

  @override
  String get title => 'தலைப்பு';

  @override
  String get top => 'மேல்';

  @override
  String get topComments => 'சிறந்த கருத்துகள்';

  @override
  String get topCommentsSubtitle => 'கருத்துகளை கீழே காட்டுவதற்கு பதிலாக மேலே காட்டவும்';

  @override
  String get topRecentAlbums => 'சமீபத்திய சிறந்த ஆல்பங்கள்';

  @override
  String get topRecentArtists => 'சமீபத்திய சிறந்த கலைஞர்கள்';

  @override
  String get topRecents => 'சமீபத்திய சிறந்தவை';

  @override
  String get totalListenTime => 'மொத்த கேட்ட நேரம்';

  @override
  String get totalListens => 'மொத்தக் கேட்டவை';

  @override
  String get totalTracks => 'மொத்த தடங்கள்';

  @override
  String get totalTracksDuration => 'மொத்த தடங்களின் கால அளவு';

  @override
  String get track => 'தடம்';

  @override
  String get trackArtistsSeparator => 'கலைஞர்களைப் பிரிப்பவர்கள்';

  @override
  String get trackGenresSeparator => 'வகைகள் பிரிப்பான்கள்';

  @override
  String get trackInfo => 'டிராக் தகவல்';

  @override
  String get trackNotFound => 'டிராக் கிடைக்கவில்லை';

  @override
  String get trackNumber => 'தட எண்';

  @override
  String get trackNumberTotal => 'மொத்த டிராக்குகள்';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'பழைய பெயர்: \"$oldName\"\n\nபுதிய பெயர்: \"$newName\"\n\nநீ சொல்வது உறுதியா?';
  }

  @override
  String get trackPlayMode => 'இசைக்கும் பயன்முறை';

  @override
  String get trackPlayModeSearchResults => 'தேடல் முடிவுகள்';

  @override
  String get trackPlayModeSelectedOnly => 'தேர்ந்தெடுக்கப்பட்ட டிராக் மட்டும்';

  @override
  String get trackPlayModeTrackAlbum => 'டிராக்கின் ஆல்பம்';

  @override
  String get trackPlayModeTrackArtist => 'டிராக்கின் முக்கிய கலைஞர்';

  @override
  String get trackPlayModeTrackGenre => 'டிராக்கின் வகை';

  @override
  String get trackThumbnailSizeInList => 'டிராக் சிறுபடத்தின் அளவு';

  @override
  String get trackTileCustomization => 'டிராக் டைல் தனிப்பயனாக்கம்';

  @override
  String get trackTileItemsSeparator => 'பொருட்களைப் பிரிப்பான்';

  @override
  String get tracks => 'தடங்கள்';

  @override
  String get tracksExcludedByNomedia => '.nomedia ஆல் விலக்கப்பட்ட தடங்கள்';

  @override
  String get tracksInfo => 'தடங்கள் பற்றிய தகவல்';

  @override
  String get underrated => 'குறைத்து மதிப்பிடப்பட்டது';

  @override
  String get undo => 'செயல்தவிர்';

  @override
  String get undoChanges => 'மாற்றங்களைச் செயல்தவிர் ?';

  @override
  String get undoChangesDeletedPlaylist => 'நீக்கப்பட்ட பட்டியலை செயல்தவிர்க்கவும்';

  @override
  String get undoChangesDeletedQueue => 'நீக்கப்பட்ட வரிசையை செயல்தவிர்க்கவும்';

  @override
  String get undoChangesDeletedTrack => 'நீக்கப்பட்ட டிராக்கை செயல்தவிர்க்கவும்';

  @override
  String get uniqueArtworkHash => 'தனித்துவமான கலைப்படைப்பு ஆச்';

  @override
  String get unlimited => 'அளவற்ற';

  @override
  String get unlisted => 'பட்டியலிடப்படாதது';

  @override
  String get unlock => 'திறக்கவும்';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'மேம்படுத்தல்';

  @override
  String get updateDirectoryPath => 'கோப்பக பாதையை மேம்படுத்தவும்';

  @override
  String get updateMissingTracksOnly => 'விடுபட்ட தடங்களை மட்டும் புதுப்பிக்கவும்';

  @override
  String get updating => 'புதுப்பித்தல் நடக்கிறது';

  @override
  String get useCollapsedSettingTiles => 'சுருக்கப்பட்ட அமைப்பு ஓடுகளைப் பயன்படுத்தவும்';

  @override
  String get useMediaStore => 'மீடியா ஸ்டோரைப் பயன்படுத்தவும்';

  @override
  String get useMediaStoreSubtitle =>
      '✓ உடனடி அட்டவணைப்படுத்தல் நேரம் \nx மரியாதை .nomedia கட்டாயமாக இயக்கப்படும் \nx சில மேனிலை தரவு குறிச்சொற்கள் விடுபட்டிருக்கும் \nஉள்ளக நூலகத்திற்கான ஃச் யூடியூப் ஒருங்கிணைப்பு வேலை செய்யாது';

  @override
  String get usePitchBlack => 'கருப்பு நிறத்தைப் பயன்படுத்துங்கள்';

  @override
  String get usePitchBlackSubtitle => 'AMOLED திரைகளுக்கு பயனுள்ளதாக இருக்கும்.. மேலும் குளிர்ச்சியாகவும் இருக்கும்';

  @override
  String get used => 'உபயோகப்படுத்தியது';

  @override
  String get value => 'மதிப்பு';

  @override
  String get valueBetween50200 => 'மதிப்பு 50% முதல் 200% வரை இருக்க வேண்டும்';

  @override
  String get vibration => 'அதிர்வு';

  @override
  String get vibrationType => 'அதிர்வு வகை';

  @override
  String get video => 'காணொளி';

  @override
  String get videoCache => 'காணொளி தற்காலிக சேமிப்பு';

  @override
  String get videoCacheFile => 'தற்காலிகமாக சேமித்த வீடியோ';

  @override
  String get videoCacheFiles => 'தற்காலிகமாகச் சேமித்த வீடியோ';

  @override
  String get videoOnly => 'காணொளி மட்டும்';

  @override
  String get videoPlaybackSource => 'வீடியோ மூலம்';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'இது உள் நினைவக வீடியோக்களுக்கு முன்னுரிமை அளிக்கும், கிடைக்கவில்லை என்றால் யூடியூப்பில் இருந்து பெறப்படும்';

  @override
  String get videoPlaybackSourceLocal => 'சேமிக்கப்பட்ட வீடியோக்கள்';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'ஆலன் வாக்கர் - Faded.m4a \nவீடியோ ஆலன் வாக்கர் - மறைந்த (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle =>
      'எந்த வீடியோ கோப்பிலும் (தேர்ந்தெடுக்கப்பட்ட கோப்புறைகள் பட்டியலில் உள்ளவை) டிராக்கின் கோப்புப் பெயரைக் கொண்ட கோப்புப் பெயர் உள்ளதா எனச் சரிபார்க்கிறது';

  @override
  String get videoPlaybackSourceYoutube => 'யூடியூபில் இருந்து';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'டிராக்கின் கோப்புப்பெயரில் சரிபார்த்தல் மற்றும் பொருந்தக்கூடிய எந்த யூடியூப் இணைப்புக்கான கருத்தும், வீடியோக்கள் பின்னர் பயன்படுத்துவதற்கு தற்காலிகமாக சேமிக்கப்படும்.';

  @override
  String get videoQuality => 'ஒளியின் தரம்';

  @override
  String get videoQualitySubtitle => 'கிடைக்கக்கூடிய மிக உயர்ந்த தரம் தேர்ந்தெடுக்கப்படும்.';

  @override
  String get videoQualitySubtitleNote => 'தகுதி கிடைக்காத பட்சத்தில் அதிக மாற்றுகளை வைத்திருப்பது எப்போதும் நல்லது, இல்லையெனில் அது மோசமான தரத்திற்கு திரும்பும்';

  @override
  String get videos => 'காணொளிகள்';

  @override
  String get view => 'பார்வை';

  @override
  String get viewAll => 'அனைத்தையும் பார்';

  @override
  String get views => 'பார்வைகள்';

  @override
  String get volume => 'சத்தம்';

  @override
  String get warning => 'எச்சரிக்கை';

  @override
  String get waveformBarsCount => 'அலைவடிவ பார்கள் எண்ணிக்கை';

  @override
  String get webmNoEditTagsSupport => 'WEBM வடிவம் டேக் எடிட்டிங்கை ஆதரிக்கவில்லை';

  @override
  String get week => 'வாரம்';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'வருடம்';

  @override
  String get yes => 'ஆம்';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'உங்கள் தற்போதைய உறுப்பினர் $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'உங்கள் தனிப்பயன் ஆர்டர் தொலைந்து போகும், நிச்சயமாகவா?';

  @override
  String get youtube => 'யூடியூப்';

  @override
  String get youtubeMusic => 'யூடியூப் இசை';

  @override
  String get youtubeSettingsSubtitle => 'Youtube அனுபவத்தைத் தனிப்பயனாக்குங்கள்';

  @override
  String get youtubeStyleMiniplayer => 'யூடியூப் பாணி மினிபிளேயர்';

  @override
  String get ytPreferNewComments => 'முடிந்த போதெல்லாம் புதிய கருத்துகளை விரும்புங்கள்';

  @override
  String get ytPreferNewCommentsSubtitle => 'கேச் செய்யப்பட்ட பதிப்பு இணைப்பு இல்லாத போது மட்டுமே பயன்படுத்தப்படும்';
}
