// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AppLocalizationsDe extends AppLocalizations {
  AppLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get about => 'Über';

  @override
  String get active => 'Aktiv';

  @override
  String get add => 'Hinzufügen';

  @override
  String get addAccount => 'Konto hinzufügen';

  @override
  String get addAll => 'Alle hinzufügen';

  @override
  String get addAllAndRemoveOldOnes => 'Alle hinzufügen und alte entfernen';

  @override
  String get addAsANewPlaylist => 'Als neue Playlist hinzufügen';

  @override
  String get addAudioToLocalLibrary => 'Audio zur lokalen Bibliothek hinzufügen';

  @override
  String get addFolder => 'Ordner hinzufügen';

  @override
  String get addLanguage => 'Sprache hinzufügen';

  @override
  String get addLanguageSubtitle => 'Hilf dabei Namida in deine eigene Sprache zu übersetzen';

  @override
  String get addLrcFile => 'LRC Datei hinzufügen';

  @override
  String get addMoreFromThisAlbum => 'Mehr aus diesem Album zur Warteschlange hinzufügen';

  @override
  String get addMoreFromThisArtist => 'Mehr von diesem Künstler zur Warteschlange hinzufügen';

  @override
  String get addMoreFromThisFolder => 'Mehr von diesem Ordner zur Warteschlange hinzufügen';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Mehr von $media zur Warteschlange hinzufügen';
  }

  @override
  String get addOnlyMissing => 'Nur fehlendes hinzufügen';

  @override
  String get addToFavourites => 'Zu Favoriten hinzufügen';

  @override
  String get addToPlaylist => 'Zur Playlist hinzufügen';

  @override
  String get addTracksAtTheBeginning => 'Titel am Anfang hinzufügen';

  @override
  String get added => 'hinzugefügt';

  @override
  String get advanced => 'Erweitert';

  @override
  String get advancedSettings => 'Erweitert';

  @override
  String get advancedSettingsSubtitle => 'Erweiterte Einstellungen, nicht anfassen';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Albenkünstler';

  @override
  String get albumArtists => 'Albenkünstler';

  @override
  String get albumIdentifiers => 'Albumbezeichnung';

  @override
  String get albumThumbnailSizeInList => 'Größe der Album Miniaturansicht';

  @override
  String get albumTileCustomization => 'Albumkachelanpassung';

  @override
  String get albums => 'Alben';

  @override
  String get albumsCount => 'Albenanzahl';

  @override
  String get all => 'Alle';

  @override
  String get allTime => 'Gesamte Zeit';

  @override
  String get alreadyExists => 'Bereits vorhanden';

  @override
  String get always => 'Immer';

  @override
  String get alwaysAsk => 'Immer fragen';

  @override
  String get alwaysDim => 'Immer dunkel';

  @override
  String get alwaysExpandedSearchbar => 'Immer erweiterte Suchleiste';

  @override
  String get alwaysRestore => 'Immer wiederherstellen';

  @override
  String get animatingThumbnailIntensity => 'Vorschaubild Animation Intensität';

  @override
  String get animatingThumbnailInversed => 'Umgekehrte Animationen';

  @override
  String get animatingThumbnailInversedSubtitle => 'Hohe Spitzenwerte führen dazu, dass das Thumbnail kleiner wird';

  @override
  String get anotherProcessIsRunning => 'Ein anderer Prozess läuft bereits.';

  @override
  String get appIcon => 'App Symbol';

  @override
  String get appVersion => 'App-Version';

  @override
  String get artist => 'Künstler';

  @override
  String get artists => 'Künstler';

  @override
  String get artwork => 'Albumcover';

  @override
  String get artworkGestures => 'Albumcover Gesten';

  @override
  String get artworks => 'Albumcover';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Audio Cache';

  @override
  String get audioOnly => 'Nur Audio';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Automatisches Sicherungsintervall';

  @override
  String get autoColoring => 'Auto Färbung';

  @override
  String get autoColoringSubtitle => 'Automatische Auswahl der Playerfarben aus dem aktuellen Albumcover';

  @override
  String get autoExtractTagsFromFilename => 'Automatisches Extrahieren aus Dateinamen';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Automatisches Extrahieren von Titel und Künstler aus Videotitel';

  @override
  String get autoGenerated => 'Autogeneriert';

  @override
  String get autoSkip => 'Automatisch überspringen';

  @override
  String get autoSkipOnce => 'Einmal automatisch überspringen';

  @override
  String get autoStartRadio => 'Auto Start Radio';

  @override
  String get autoStartRadioSubtitle => 'Fügt bei der Wiedergabe eines einzelnen Tracks automatisch eine Mix-Wiedergabeliste hinzu';

  @override
  String get automaticBackup => 'Automatisch';

  @override
  String get automaticBackupSubtitle => 'Wendet automatisch die neueste Sicherungsdatei an, die im Sicherungsort gefunden wurde';

  @override
  String get backupAndRestore => 'Sichern und Wiederherstellen';

  @override
  String get backupAndRestoreSubtitle => 'Datenbank und Einstellungen sichern';

  @override
  String get balanced => 'Ausgeglichen';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Zwischen Terminen';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Sperrliste';

  @override
  String get borderRadiusMultiplier => 'Grenzradius Multiplikator';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Abbrechen';

  @override
  String get canceled => 'Abgebrochen';

  @override
  String get changed => 'Verändert';

  @override
  String get changelog => 'Änderungsliste';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Kanal';

  @override
  String get channels => 'Kanäle';

  @override
  String get check => 'Prüfen';

  @override
  String get checkForMore => 'Mehr Informationen';

  @override
  String get checkList => 'Checkliste';

  @override
  String get choose => 'Wählen';

  @override
  String get chooseWhatToClear => 'Auswählen, was gelöscht werden soll';

  @override
  String get claim => 'Beanspruchen';

  @override
  String get clear => 'Löschen';

  @override
  String get clearAudioCache => 'Audio Cache löschen';

  @override
  String get clearImageCache => 'Image Cache löschen';

  @override
  String get clearImageCacheWarning => 'Warnung: wird zu einer Bibliothek ohne Bilder führen, nur zur Wiederherstellung des Bild-Caches verwenden.';

  @override
  String get clearTrackItem => 'Tracks löschen';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString Titel löschen',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Video Cache löschen';

  @override
  String get clearVideoCacheNote => 'Du kannst auswählen was gelöscht werden soll.';

  @override
  String get clock => 'Uhr';

  @override
  String get colorPalette => 'Farbpalette';

  @override
  String get colorPaletteNote1 => 'Lange auf eine Farbe gedrückt halten, um sie zu entfernen';

  @override
  String get colorPaletteNote2 => 'Tippe auf einen Mix, um eine Standardfarbe zu benutzen';

  @override
  String get colorPalettes => 'Farbpaletten';

  @override
  String get comment => 'Kommentar';

  @override
  String get comments => 'Kommentare';

  @override
  String get composer => 'Komponist';

  @override
  String get compress => 'Komprimieren';

  @override
  String get compressImages => 'Bilder komprimieren';

  @override
  String get compressionPercentage => 'Prozentsatz der Komprimierung';

  @override
  String get configure => 'Konfigurieren';

  @override
  String get confirm => 'Bestätigen';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'Kopiertes Albumcover';

  @override
  String get copiedToClipboard => 'Zur Zwischenablage kopiert';

  @override
  String get copy => 'Kopieren';

  @override
  String get corruptedFile => 'Datei konnte nicht analysiert werden, sie könnte beschädigt sein';

  @override
  String get couldntOpen => 'Konnte nicht geöffnet werden :(';

  @override
  String get couldntOpenYtLink => 'Kein Youtube Link für diesen Track verfügbar';

  @override
  String get couldntPlayFile => 'Datei kann nicht abgespielt werden';

  @override
  String get couldntRenamePlaylist => 'Playlist kann nicht umbenannt werden';

  @override
  String get couldntSaveImage => 'Bild konnte nicht gespeichert werden';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Land';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Erstellen';

  @override
  String get createBackup => 'Sicherung erstellen';

  @override
  String get createNewPlaylist => 'Neue Playlist erstellen';

  @override
  String get createdBackupSuccessfully => 'Sicherung erstellt';

  @override
  String get createdBackupSuccessfullySub => 'Sicherungsdatei wurde erfolgreich erstellt';

  @override
  String get crossPlatformSync => 'Plattformübergreifende Synchronisierung';

  @override
  String get crossfadeDuration => 'Dauer der Überblendung';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Überblendung automatisch in den letzten $secondsString Sekunden auslösen',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Überblendung nicht automatisch auslösen';

  @override
  String get custom => 'Benutzerdefiniert';

  @override
  String get customizations => 'Anpassungen';

  @override
  String get customizationsSubtitle => 'Passe das Aussehen des Players an, mache es zu deinem';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Daten werden bereitgestellt von: $name';
  }

  @override
  String get dataSaver => 'Datensparer';

  @override
  String get dataSaverMode => 'Datensparmodus';

  @override
  String get database => 'Datenbank';

  @override
  String get date => 'Datum';

  @override
  String get dateAdded => 'Datum hinzugefügt';

  @override
  String get dateCreated => 'Datum erstellt';

  @override
  String get dateModified => 'Datum modifiziert';

  @override
  String get dateTimeFormat => 'Datumzeitformat';

  @override
  String get day => 'Tag';

  @override
  String get days => 'Tage';

  @override
  String get defaultBackupLocation => 'Standard-Sicherungsort';

  @override
  String get defaultColor => 'Standardfarbe';

  @override
  String get defaultColorSubtitle => 'Lege eine Farbe fest, die der Player verwenden soll';

  @override
  String get defaultDownloadLocation => 'Standard-Download-Speicherort';

  @override
  String get defaultLabel => 'Standard';

  @override
  String get defaultLibraryTab => 'Standardbibliothek Registerkarte';

  @override
  String get delete => 'Löschen';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Datei $countString löschen, die $totalSizeText repräsentiert?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Dauerhaft $numberText aus deinem Speicher löschen';
  }

  @override
  String get deletePlaylist => 'Playlist löschen';

  @override
  String get deleteTempFiles => 'Temporäre Dateien löschen';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Beschreibung';

  @override
  String get developer => 'Entwickler';

  @override
  String get development => 'Entwicklung';

  @override
  String get didYouMean => 'Meintest du';

  @override
  String get dimIntensity => 'Intensität dimmen';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Miniplayer nach $secondsString Sekunden Inaktivität dimmen',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Verzeichnis existiert nicht';

  @override
  String get disable => 'Deaktivieren';

  @override
  String get disableAll => 'Alle deaktivieren';

  @override
  String get disableReordering => 'Umordnung deaktivieren';

  @override
  String get disableSearchCleanup => 'Suchbereinigung deaktivieren';

  @override
  String get discNumber => 'Scheibe Nummer';

  @override
  String get discNumberTotal => 'Disk Gesamt';

  @override
  String get discover => 'Entdecken';

  @override
  String get dislike => 'Mag ich nicht';

  @override
  String get dismissibleMiniplayer => 'Miniplayer entlassen';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Anzeige der tatsächlichen Position anstelle der Differenz während der Suche';

  @override
  String get displayAlbumCardTopRightDate => 'Albumkarte oben rechts Datum';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Albumdatum auf der Albumkarte oben rechts anzeigen';

  @override
  String get displayArtistBeforeTitle => 'Künstler bevor Titel anzeigen';

  @override
  String get displayArtworkOnLockscreen => 'Albumcover auf dem Sperrbildschirm anzeigen';

  @override
  String get displayAudioInfoInMiniplayer => 'Audioinfo anzeigen';

  @override
  String get displayFavButtonInNotification => 'Favoritentaste in Benachrichtigung anzeigen';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Vorschaubild könnte verschoben werden.';

  @override
  String get displayFavouriteIconInTrackTile => 'Favoritentaste anzeigen';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Restdauer anstatt der Gesamtdauer anzeigen';

  @override
  String get displayStopButtonInNotification => 'Stopp-Schaltfläche in Benachrichtigung anzeigen';

  @override
  String get displayThirdItemInRowInTrackTile => 'Drittes Element in jeder Reihe anzeigen';

  @override
  String get displayThirdRowInTrackTile => 'Dritte Reihe anzeigen';

  @override
  String get displayTrackNumberInAlbumPage => 'Tracknummer auf der Albumseite anzeigen';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Kleines Kästchen mit der Tracknummer auf der Albumseite anzeigen';

  @override
  String get doNothing => 'Nichts tun';

  @override
  String get donate => 'Spenden';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Fertig';

  @override
  String get dontAskAgain => 'Nicht nochmal fragen';

  @override
  String get dontDim => 'Nicht dunkeln';

  @override
  String get dontRestorePosition => 'Nicht wiederherstellen';

  @override
  String get dontResume => 'Nicht fortsetzen';

  @override
  String get doubleTapToToggleLyrics => 'Doppeltippen zum Umschalten des Liedtextes';

  @override
  String get download => 'Herunterladen';

  @override
  String get downloadingWillOverrideIt => 'Herunterladen wird es überschreiben';

  @override
  String get downloads => 'Downloads';

  @override
  String get downloadsMetadataTags => 'Downloads Metadaten Tags';

  @override
  String get downloadsMetadataTagsSubtitle => 'Extrahiert standardmäßig Künstler, Titel und Album aus den Videoinformationen';

  @override
  String get dragToSeek => 'Ziehen zum Suchen';

  @override
  String get duckAudio => 'Senkaudio';

  @override
  String get duplicatedItemsAdding => 'Du versuchst, einige Elemente hinzuzufügen, die bereits in dieser Playlist existieren';

  @override
  String get duplicatedTracks => 'Duplizierte Titel';

  @override
  String get duration => 'Dauer';

  @override
  String get edgeColorsSwitching => 'Umschalten der Randfarben';

  @override
  String get edit => 'Bearbeiten';

  @override
  String get editArtwork => 'Albumcover bearbeiten';

  @override
  String get editTags => 'Tags bearbeiten';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'Du hast Felder mit leeren/nicht aussagekräftigen Werten haben, vergewissere dich, dass du diese wirklich bearbeiten willst';

  @override
  String get emptyValue => 'Leerer Wert';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Unschärfe Effekt aktivieren';

  @override
  String get enableBottomNavBar => 'Untere Navigationsleiste einschalten';

  @override
  String get enableBottomNavBarSubtitle => 'Gegenstände befinden sich in den beiden Schubladen';

  @override
  String get enableClipboardMonitoring => 'Zwischenablage Überwachung einschalten';

  @override
  String get enableClipboardMonitoringSubtitle => 'Ermöglicht das Einfügen von Links und Texten in die Suchleiste';

  @override
  String get enableCrossfadeEffect => 'Überblendungseffekt einschalten';

  @override
  String get enableFadeEffectOnPlayPause => 'Überblendungsffekt bei Wiedergabe/Pause aktivieren';

  @override
  String get enableFoldersHierarchy => 'Ordnerhierarchie aktivieren';

  @override
  String get enableGlowEffect => 'Glüheffekt aktivieren';

  @override
  String get enableM3uSync => 'M3U Sync aktivieren';

  @override
  String get enableM3uSyncNote1 => 'M3U Sync ermöglicht das Speichern von Änderungen an der Playlist in der ursprünglichen M3U-Datei';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Wenn etwas schief gelaufen ist, findest du eine Sicherung dieser Playlist im $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Bei Ablehnung gehen alle Änderungen in dieser Playlist beim Neustart verloren';

  @override
  String get enableMiniplayerParticles => 'Bewegte Partikel aktivieren';

  @override
  String get enableParallaxEffect => 'Parallaxeneffekt einschalten';

  @override
  String get enablePartyMode => 'Partymodus aktivieren';

  @override
  String get enablePartyModeSubtitle => 'Schicker kantiger Atmungseffekt anwenden';

  @override
  String get enablePictureInPicture => 'Bild-in-Bild aktivieren';

  @override
  String get enableReordering => 'Neuordnung aktivieren';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Suchbereinigung aktivieren';

  @override
  String get enableSearchCleanupSubtitle => 'Alle Symbole und Leerzeichen werden ignoriert';

  @override
  String get enableSponsorblock => 'SponsorBlock aktivieren';

  @override
  String get enableVideoPlayback => 'Videowiedergabe aktivieren';

  @override
  String get enterSymbol => 'Bitte gebe ein Symbol ein';

  @override
  String get equalizer => 'Equalizer';

  @override
  String get error => 'Fehler';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Fehler beim Abspielen eines Tracks';

  @override
  String get excludedFodlers => 'Ausgeschlossene Ordner';

  @override
  String get exit => 'Verlassen';

  @override
  String get exitAppSubtitle => 'Erneut tippen um zu beenden';

  @override
  String get expandedMiniplayer => 'Erweiterter Miniplayer';

  @override
  String get exportAsM3u => 'Als M3U exportieren';

  @override
  String get extension => 'Erweiterung';

  @override
  String get externalFiles => 'Externe Dateien';

  @override
  String get extract => 'Extrahieren';

  @override
  String get extractAllColorPalettes => 'Alle Farbpaletten extrahieren';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Verbleibende $numberString extrahieren?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'feat. Künstler aus dem Titel extrahieren';

  @override
  String get extractFeatArtistSubtitle => 'Extrahiert (feat. X) und (ft. X) Künstler, als neuen Künstlereintrag.';

  @override
  String get extractingInfo => 'Info extrahieren';

  @override
  String get extras => 'Extras';

  @override
  String get extrasSubtitle => 'Zusätzliche Einstellungen zur Verfeinerung deiner Erfahrung';

  @override
  String get extreme => 'Extrem';

  @override
  String get failed => 'Fehlgeschlagen';

  @override
  String get failedEdits => 'Fehlgeschlagene Bearbeitungen';

  @override
  String get favourites => 'Favoriten';

  @override
  String get features => 'Funktionen';

  @override
  String get fetching => 'Holt';

  @override
  String get fetchingOfAllVideos => 'Abruf aller Videos';

  @override
  String get file => 'Datei';

  @override
  String get fileAlreadyExists => 'Datei existiert bereits';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Dateiname';

  @override
  String get fileNameWoExt => 'Dateiname ohne Erweiterung';

  @override
  String get filenameShouldntStartWith => 'Dateiname sollte nicht mit starten';

  @override
  String get files => 'Dateien';

  @override
  String get filler => 'Pausenfilm';

  @override
  String get filterAlbums => 'Alben filtern';

  @override
  String get filterArtists => 'Künstler filtern';

  @override
  String get filterGenres => 'Genres filtern';

  @override
  String get filterPlaylists => 'Playlists filtern';

  @override
  String get filterTracks => 'Titel filtern';

  @override
  String get filterTracksBy => 'Titel in Suchlisten filtern nach';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Titel nach Größe und Dauer gefiltert';

  @override
  String get finished => 'Abgeschlossen';

  @override
  String get finishedUpdatingLibrary => 'Aktualisierung der Bibliothek abgeschlossen';

  @override
  String get firstListen => 'Erstes Mal angehört';

  @override
  String get fixYtdlpBigThumbnailSize => 'Große yt-dlp Thumbnail-Größe beheben';

  @override
  String get floatingActionButton => 'Schwebende Aktionstaste';

  @override
  String get folder => 'Ordner';

  @override
  String get folderName => 'Ordnername';

  @override
  String get folders => 'Ordner';

  @override
  String get fontScale => 'Schriftgröße';

  @override
  String get forceMiniplayerFollowTrackColors => 'Miniplayer zwingen, Trackfarben zu folgen';

  @override
  String get forceSquaredAlbumThumbnail => 'Quadratisches Album Vorschaubild erzwingen';

  @override
  String get forceSquaredThumbnailNote =>
      'Größe des Vorschaubild & Höhe der Kacheln sind NICHT gleich, das quadratische Aussehen wird nicht den Erwartungen entsprechen. Möchtest du sie gleich machen?';

  @override
  String get forceSquaredTrackThumbnail => 'Quadratisches Trackvorschaubild erzwingen';

  @override
  String get forceStopColorPaletteGeneration => 'Extrahieren von Farbpaletten erzwingen? Du kannst es später immer noch fortsetzen';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Vollbildschirm';

  @override
  String get gaplessPlayback => 'Lückenlose Wiedergabe';

  @override
  String get generate => 'Generieren';

  @override
  String get generateFromDates => 'Zeitspanne';

  @override
  String get generateFromDatesSubtitle => 'Titel generieren, die du in einem Zeitraum gehört hast';

  @override
  String get generateRandomPlaylist => 'Zufällige Playlist generieren';

  @override
  String get genre => 'Genre';

  @override
  String get genres => 'Genres';

  @override
  String get goToAlbum => 'Zum Album gehen';

  @override
  String get goToArtist => 'Zum Künstler gehen';

  @override
  String get goToChannel => 'Zum Kanal gehen';

  @override
  String get goToFolder => 'Zum Ordner gehen';

  @override
  String get goodLooking => 'Gut aussehend';

  @override
  String get grantStoragePermission => 'Speichererlaubnis erteilen';

  @override
  String get group => 'Gruppe';

  @override
  String get groupArtworksByAlbum => 'Albumcover nach Album gruppieren';

  @override
  String get guide => 'Anleitung';

  @override
  String get hapticFeedback => 'Haptische Rückmeldung';

  @override
  String get heightOfAlbumTile => 'Höhe von Albumkachel';

  @override
  String get heightOfTrackTile => 'Höhe von Track Kachel';

  @override
  String get hideSkipButtonAfter => 'Überspringen-Schaltfläche ausblenden nach';

  @override
  String get highMatches => 'Hohe Übereinstimmung';

  @override
  String get highPerformance => 'Hohe Leistung';

  @override
  String get highlight => 'Markierung';

  @override
  String get history => 'Verlauf';

  @override
  String get historyImportMissingEntriesNote =>
      'Diese Einträge konnten in der Bibliothek nicht gefunden werden, füge sie bitte manuell hinzu, wenn du glaubst, dass sie existieren';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString hört auf $oldTrackInfo wird durch $newTrackInfo ersetzt, bestätigen?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Start';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12 Stundenformat';

  @override
  String get hours => 'Stunden';

  @override
  String get iReadAndAgree => 'Ich habe gelesen und stimme zu';

  @override
  String get ifNotPlaying => 'Wenn nicht wiedergegeben';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Downloads können gedrosselt werden, wenn die App akkubeschränkt ist';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignoriere beim Sortieren gängige Präfixe';

  @override
  String get ignores => 'Ignoriert';

  @override
  String get imageSource => 'Bildquelle';

  @override
  String get immersiveMode => 'Immersiver Modus';

  @override
  String get immersiveModeSubtitle => 'Status- und Navigationsleisten ausblenden, wenn der Miniplayer erweitert ist';

  @override
  String get import => 'Importieren';

  @override
  String get importAll => 'Alle importieren';

  @override
  String get importLastFmHistory => 'LastFm Verlauf importieren';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Gehe zu $lastfmCsvLink\n\n2. Gebe deinen Benutzernamen ein, rufe die csv-Datei ab und lade sie herunter.\n\n3. Wähle die Datei auf dem nächsten Bildschirm aus.';
  }

  @override
  String get importTimeRange => 'Zeitspanne importieren';

  @override
  String get importYoutubeHistory => 'Youtube Verlauf importieren';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Gehe zu $takeoutLink\n\n2. Drücke auf \"Mehrere Formate\" und wähle neben \"Verlauf\" die Option \"JSON\".\n\n3. Drücke auf \"Alle Youtube Daten inbegriffen\", hebe die Auswahl von \"Alle\" auf und wähle \"History only\".\n\n4. Exportieren, Herunterladen & Entpacken erstellen.\n\n5. Wähle auf dem nächsten Bildschirm \"watch-history.json\".';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString Kanäle erfolgreich importiert',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText Playlists erfolgreich importiert',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Videos einbeziehen';

  @override
  String get indexRefreshRequired => 'Nach der Änderung eine Aktualisierung durchführen';

  @override
  String get indexer => 'Indexer';

  @override
  String get indexerNote => 'Hinweis: Unvollständige Anzahl der Albumcover bezieht sich auf die duplizierten & nicht gefundenen Albumcover';

  @override
  String get indexerSubtitle => 'Deine Musikbibliothek verwalten';

  @override
  String get infinityQueueOnNextPrev => 'Unendliche Warteschlange bei Weiter/Vorher';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'Durch Drücken der Taste \"Weiter\" während der Wiedergabe des letzten Elements wird zum ersten Element gesprungen und umgekehrt';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'eingefügt';

  @override
  String get instantlyApplies => 'Sofort anwendbar';

  @override
  String get interactionReminder => 'Interaktionserinnerung';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Auswahl umkehren';

  @override
  String get issues => 'Probleme';

  @override
  String get item => 'Artikel';

  @override
  String get jump => 'Springen';

  @override
  String get jumpToDay => 'Zu Tag springen';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Zum ersten Titel springen nachdem Warteschlange abgeschlossen wurde';

  @override
  String get keepCachedVersions => 'Cachede Versionen behalten';

  @override
  String get keepFileDates => 'Datum von Dateien behalten';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniplayer erweitert wird';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniplayer erweitert und ein Video abgespielt wird';

  @override
  String get keepScreenAwakeNone => 'Bildschirm nicht wach halten';

  @override
  String get keepScreenAwakeWhen => 'Bildschirm wach halten, wenn';

  @override
  String get killPlayerAfterDismissingApp => 'Player nach dem Beenden der App beenden';

  @override
  String get language => 'Sprache';

  @override
  String get learnMore => 'Mehr erfahren';

  @override
  String get leftAction => 'Linke Aktion';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Registerkarten der Bibliothek';

  @override
  String get libraryTabsReorder => 'Du kannst die aktivierten Registerkarten neu anordnen.';

  @override
  String get license => 'Lizenz';

  @override
  String get licenseSubtitle => 'Von Namida verwendete Lizenzen und Vereinbarungen';

  @override
  String get like => 'Mag ich';

  @override
  String get liked => 'Geliked';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Liste von Ordnern';

  @override
  String get loadAll => 'Alle laden';

  @override
  String get loadingFile => 'Datei laden';

  @override
  String get local => 'Lokal';

  @override
  String get localVideoMatching => 'Lokaler Videoabgleich';

  @override
  String get login => 'Anmelden';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Lange auf die Liedtexte drücken um in den Vollbildmodus zu wechseln';

  @override
  String get lostMemories => 'Verlorene Erinnerungen';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'um diese Zeit, vor $numberString Jahren',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Verlorene Partner';

  @override
  String get loudnessEnhancer => 'Lautstärkeverstärker';

  @override
  String get lyricist => 'Lyriker';

  @override
  String get lyrics => 'Liedtext';

  @override
  String get lyricsSource => 'Quelle des Liedtextes';

  @override
  String get m3uPlaylist => 'M3U-Wiedergabeliste';

  @override
  String get makeYourFirstListen => 'Höre zum ersten Mal zu!';

  @override
  String get manage => 'Verwalten';

  @override
  String get manageYourAccounts => 'Verwalte deine Konten';

  @override
  String get manualBackup => 'Manuell';

  @override
  String get manualBackupSubtitle => 'Bestimmte Datei abrufen';

  @override
  String get markAsRead => 'Als gelesen markieren';

  @override
  String get matchAllTracks => 'Alle Titel abgleichen';

  @override
  String get matchAllTracksNote => 'Dies kann sich auf die Abgleichsgeschwindigkeit auswirken, da alle Titel in deiner Bibliothek überprüft werden';

  @override
  String get matchingType => 'Passende Art';

  @override
  String get maxAudioCacheSize => 'Maximale Audio-Cache-Größe';

  @override
  String get maxImageCacheSize => 'Maximale Bild-Cache-Größe';

  @override
  String get maxVideoCacheSize => 'Maximale Video-Cache-Größe';

  @override
  String get maximum => 'Maximum';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store ist aktiviert, dies hat kein Auswirkung';

  @override
  String get medium => 'Mittel';

  @override
  String get membershipCode => 'Code';

  @override
  String get membershipCodeSentToEmail => 'Code an deine E-Mail geschickt';

  @override
  String get membershipDidntChange => 'Mitgliedschaft hat sich nicht verändert';

  @override
  String get membershipEnjoyNew => 'Viel Spaß mit deiner neuen Mitgliedschaft';

  @override
  String get membershipFreeCoupon => 'Kostenloser Coupon';

  @override
  String get membershipManage => 'Verwalte deine Mitgliedschaft';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Keine Abonnements für diesen Nutzer gefunden';

  @override
  String get membershipSignInToPatreonAccount => 'Melde dich bei deinem Patreon-Konto an';

  @override
  String get membershipUnknown => 'Unbekannte Mitgliedschaft';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Du benötigst die Mitgliedschaft von $name1 oder $name2 um mehrere Konten hinzuzufügen';
  }

  @override
  String get merge => 'Zusammenführen';

  @override
  String get metadataCache => 'Metadaten-Cache';

  @override
  String get metadataEditFailed => '­Bearbeitung der Metadaten fehlgeschlagen';

  @override
  String get metadataReadFailed => 'Lesen von Metadaten fehlgeschlagen';

  @override
  String get minFileDuration => 'Mindestdauer des Tracks';

  @override
  String get minFileSize => 'Minimale Dateigröße';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Mindestdauer des Titels zur Wiederherstellung der zuletzt gespielten Position';

  @override
  String get minValueCantBeMoreThanMax => 'Mindestwert kann nicht größer sein als der Höchstwert';

  @override
  String get minValueToCountTrackListen => 'Zähle einen Hörtest nach: ';

  @override
  String get minimizedMiniplayer => 'Minimierter Miniplayer';

  @override
  String get minimum => 'Minimum';

  @override
  String get minimumOneFolderSubtitle => 'Es sollte mindestens 1 Ordner vorhanden sein, füge weitere Ordner hinzu, wenn du diese entfernen möchtest';

  @override
  String get minimumOneItem => 'Element konnte nicht entfernt werden';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Es müssen mindestens $numberString Elemente übrig bleiben',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Mindestdauer eines Segments';

  @override
  String get miniplayerCustomization => 'Miniplayer Anpassung';

  @override
  String get minutes => 'minuten';

  @override
  String get missingEntries => 'Fehlende Einträge';

  @override
  String get missingTracks => 'Fehlende Titel';

  @override
  String get mix => 'Mix';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Von youtube generierte Wiedergabeliste mixen';

  @override
  String get mixes => 'Mixes';

  @override
  String get mobile => 'Mobil';

  @override
  String get month => 'Monat';

  @override
  String get months => 'Monate';

  @override
  String get mood => 'Stimmung';

  @override
  String get moods => 'Stimmungen';

  @override
  String get more => 'Mehr';

  @override
  String get mostPlayed => 'Am meisten gespielt';

  @override
  String get multipleTracksTagsEditNote => 'Du bist dabei, diese Titel zu bearbeiten,\nunveränderte Felder bleiben unangetastet.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Name';

  @override
  String get nameContainsBadCharacter => 'Name enthält schlechtes Zeichen';

  @override
  String get never => 'Nie';

  @override
  String get newDirectory => 'Neues Verzeichnis';

  @override
  String get newLabel => 'Neu';

  @override
  String get newTracksAdd => 'Titel hinzufügen';

  @override
  String get newTracksMoods => 'Stimmung';

  @override
  String get newTracksMoodsSubtitle => 'Titel basierend auf verfügbaren Stimmungen generieren';

  @override
  String get newTracksRandom => 'Zufällig';

  @override
  String get newTracksRandomSubtitle => 'Zufällige Titel aus deiner Bibliothek auswählen';

  @override
  String get newTracksRatings => 'Bewertungen';

  @override
  String get newTracksRatingsSubtitle => 'Titel mit einer bestimmten Bewertung generieren';

  @override
  String get newTracksRecommended => 'Empfohlen';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Die $currentTrack Titel, die du gewöhnlich gehört hast, generieren';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Ähnliches Erscheinungsdatum';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Titel, die etwa zur gleichen Zeit wie $currentTrack veröffentlicht wurden, generieren';
  }

  @override
  String get newTracksUnknownYear => 'Track hat unbekanntes Jahr';

  @override
  String get newest => 'Neueste';

  @override
  String get next => 'Nächstes';

  @override
  String get no => 'nein';

  @override
  String get noChangesFound => 'Keine Änderungen wurden gefunden.';

  @override
  String get noEnoughTracks => 'Du hast nicht viele Titel...';

  @override
  String get noExcludedFolders => 'Du hast keine ausgeschlossenen Ordner';

  @override
  String get noFolderChosen => 'Du hast keinen Ordner ausgewählt';

  @override
  String get noMoodsAvailable => 'Keine Stimmungen verfügbar';

  @override
  String get noNetworkAvailableToFetchData => 'Kein Netzwerk zum Abrufen von Daten verfügbar';

  @override
  String get noTracksFound => 'Es wurden keine Titel gefunden';

  @override
  String get noTracksFoundBetweenDates => 'Dieser Zeitbereich hat keine Titel.';

  @override
  String get noTracksFoundInDirectory => 'Keine Titel in diesem Verzeichnis gefunden';

  @override
  String get noTracksInHistory => 'Du hast nicht genug Titel im Verlauf';

  @override
  String get nonActive => 'nicht aktiv';

  @override
  String get nonFavourites => 'nicht Favoriten';

  @override
  String get none => 'Keine';

  @override
  String get normalizeAudio => 'Audio normalisieren';

  @override
  String get normalizeAudioSubtitle => 'Normalisiert die Lautstärke durch Auslesen des Replay-Gain-Tags oder der von Youtube bereitgestellten Infos';

  @override
  String get notAvailableForYourDevice => 'Für dein Gerät nicht verfügbar';

  @override
  String get notSupportedForNetworkFiles => 'Für Netzwerkdateien nicht unterstützt';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'Notiz';

  @override
  String get notification => 'Benachrichtigung';

  @override
  String get notifications => 'Benachrichtigungen';

  @override
  String get numberOfTracks => 'Anzahl der Titel';

  @override
  String get ofLabel => 'von';

  @override
  String get offlineSearch => 'Offline Suche';

  @override
  String get offset => 'Versetzt';

  @override
  String get oldDirectory => 'Altes Verzeichnis';

  @override
  String get oldDirectoryStillHasTracks => 'Altes Verzeichnis hat noch einige Titel, bestätigen?';

  @override
  String get oldestWatch => 'Älteste Uhr';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Bei Unterbrechung';

  @override
  String get onNotificationTap => 'Auf Benachrichtigung tippen';

  @override
  String get onOpeningYoutubeLink => 'Beim Öffnen des Youtube-Links';

  @override
  String get onSwiping => 'Über Swiping';

  @override
  String get onVolumeZero => 'Bei Lautstärke 0';

  @override
  String get ongoing => 'Laufend';

  @override
  String get open => 'Öffnen';

  @override
  String get openApp => 'Öffne App';

  @override
  String get openInFileExplorer => 'Im Datei-Explorer öffnen';

  @override
  String get openInYoutubeView => 'Öffne in der Youtube-Ansicht';

  @override
  String get openMiniplayer => 'Öffne Miniplayer';

  @override
  String get openQueue => 'Öffne Warteschlange';

  @override
  String get openYoutubeLink => 'Öffne Youtube Link';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operation $name erfordert ein Konto, zum Fortfahren anmelden';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operation $operation erfordert mindestens die Mitgliedschaft $name';
  }

  @override
  String get or => 'oder';

  @override
  String get others => 'Andere';

  @override
  String get output => 'Ausgabe';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Alte Dateien im selben Ordner überschreiben';

  @override
  String get palette => 'Palette';

  @override
  String get paletteMix => 'Mix';

  @override
  String get paletteNewMix => 'Neuer Mix';

  @override
  String get paletteSelectedMix => 'Ausgewählter Mix';

  @override
  String get parallelDownloads => 'Parallele Downloads';

  @override
  String get parsed => 'geparst';

  @override
  String get password => 'Passwort';

  @override
  String get path => 'Vollständiger Pfad der Datei';

  @override
  String get pause => 'Pause';

  @override
  String get pauseFadeDuration => 'Überblenddauer pausieren';

  @override
  String get pausePlayback => 'Wiedergabe anhalten';

  @override
  String get percentage => 'Prozentsatz';

  @override
  String get performanceMode => 'Leistungsmodus';

  @override
  String get performanceNote => 'Könnte die Leistung beeinträchtigen';

  @override
  String get personalized => 'Personalisiert';

  @override
  String get personalizedRelatedVideos => 'Personalisierte verwandte Videos';

  @override
  String get personalizedRelatedVideosSubtitle => 'Das zu deaktivieren erhöht den Datenverbrauch';

  @override
  String get pickColorsFromDeviceWallpaper => 'Farben vom Gerätehintergrund auswählen';

  @override
  String get pickFromStorage => 'Vom Speicher auswählen';

  @override
  String get pinned => 'Angepinnt';

  @override
  String get pitch => 'Tonlage';

  @override
  String get plain => 'Einfach';

  @override
  String get play => 'Abspielen';

  @override
  String get playAfter => 'Als Nächstes abspielen';

  @override
  String get playAfterNextPrev => 'Automatische Wiedergabe beim Nächsten/Vorherigen';

  @override
  String get playAll => 'Alles Spielen';

  @override
  String get playFadeDuration => 'Überblenddauer abspielen';

  @override
  String get playLast => 'Als Letztes abspielen';

  @override
  String get playNext => 'Als nächstes abspielen';

  @override
  String get playbackSetting => 'Wiedergabe';

  @override
  String get playbackSettingSubtitle => 'Kann direkt im Player durch langes Drücken der Audiotaste aufgerufen werden';

  @override
  String get playlist => 'Playlist';

  @override
  String get playlists => 'Wiedergabelisten';

  @override
  String get playlistsImportM3uNative => 'Damit werden M3U Wiedergabelisten importiert, die nur von Namida verwendet werden können, wenn du eine Migration durchführst';

  @override
  String get playlistsImportM3uSynced =>
      'Damit werden M3U-Wiedergabelisten automatisch aus Indexer-Ordnern importiert und mit der ursprünglichen M3U-Datei synchronisiert. Aktiviere, wenn du von anderen Apps aus auf die Wiedergabelisten zugreifen bzw. diese ändern möchtest';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Automatischer Import von M3U-Wiedergabelisten';

  @override
  String get pleaseEnterADifferentName => 'Dieser Name existiert bereits :(\nBitte versuche einen anderen schicken Namen';

  @override
  String get pleaseEnterALink => 'Bitte gebe einen Link ein';

  @override
  String get pleaseEnterALinkSubtitle => 'ähm.. ist das ein youtube link?';

  @override
  String get pleaseEnterAName => 'Bitte gib einen Namen ein';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Duplizierte Titel verhindern';

  @override
  String get preventDuplicatedTracksSubtitle => 'Verwendet Dateinamen zur eindeutigen Identifizierung von Titeln';

  @override
  String get preview => 'Vorschau';

  @override
  String get previous => 'Vorher';

  @override
  String get previousButtonReplays => 'Vorherige Tastenwiederholungen';

  @override
  String get previousButtonReplaysSubtitle => 'wenn gedrückt, während die aktuelle Position länger als die Suchdauer war';

  @override
  String get prioritizeEmbeddedLyrics => 'Eingebettete Liedtexte bevorzugen';

  @override
  String get priority => 'Priorität';

  @override
  String get private => 'Privat';

  @override
  String get progress => 'Fortschritt';

  @override
  String get promptToChangeTrackPath =>
      'Normalerweise passiert dies, wenn du die Datei außerhalb von namida löscht/verschiebst/umbenennst. Möchtest du den aktuellen Pfad aktualisieren?';

  @override
  String get public => 'Öffentlich';

  @override
  String get queue => 'Warteschlange';

  @override
  String get queues => 'Warteschlangen';

  @override
  String get random => 'Zufällig';

  @override
  String get randomPicks => 'Zufällige Auswahl';

  @override
  String get rating => 'Bewertung';

  @override
  String get reIndex => 'Neu indizieren';

  @override
  String get reIndexSubtitle => 'Baue deine Musikbibliothek von Grund auf neu auf';

  @override
  String get reIndexWarning => 'Dieser Vorgang kann je nach Größe deiner Bibliothek eine Weile dauern.\n\nAlbumcover werden nicht neu indiziert, solange sie noch existieren';

  @override
  String get recentAlbums => 'Neueste Alben';

  @override
  String get recentArtists => 'Neueste Künstler';

  @override
  String get recentListens => 'Zuletzt angehört';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Zuletzt hinzugefügt';

  @override
  String get recordLabel => 'Plattenlabel';

  @override
  String get refresh => 'Aktualisieren';

  @override
  String get refreshLibrary => 'Aktualisierungsbücherei';

  @override
  String get refreshLibrarySubtitle => 'Überprüfe neu hinzugefügte oder gelöschte Musik';

  @override
  String get refreshOnStartup => 'Beim Starten aktualisieren';

  @override
  String get relatedVideos => 'Ähnliche Videos';

  @override
  String get rememberAudioOnlyMode => 'Nur-Audio-Modus merken';

  @override
  String get remixer => 'Remixer';

  @override
  String get remove => 'Entferne';

  @override
  String get removeDuplicates => 'Entferne Duplikate';

  @override
  String get removeFromFavourites => 'Aus Favoriten entfernen';

  @override
  String get removeFromLibrary => 'Aus Bibliothek entfernen';

  @override
  String get removeFromPlaylist => 'Entferne aus Playlist';

  @override
  String get removeQueue => 'Entferne Warteschlange';

  @override
  String get removeSourceFromHistory => 'Entferne Quelle aus dem Verlauf';

  @override
  String get removeWhitespaces => 'Entferne Whitespaces';

  @override
  String get removed => 'Entfernt';

  @override
  String get rename => 'Umbenennen';

  @override
  String get renamePlaylist => 'Playlist umbenennen';

  @override
  String get reorderable => 'Reorganisierbar';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Wiederhole den Vorgang noch $number Mal',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Wiederholungsmodus';

  @override
  String get repeatModeAll => 'Alle Warteschlangen wiederholen';

  @override
  String get repeatModeNone => 'Beim letzten Track stoppen';

  @override
  String get repeatModeOne => 'Aktuellen Track wiederholen';

  @override
  String get replaceAllListensWithAnotherTrack => 'Alles Angehörte durch einen anderen Track ersetzen';

  @override
  String get replies => 'Antworten';

  @override
  String get reply => 'Antwort';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Erfordert das Löschen des Bild-Caches und die Neuindizierung';

  @override
  String get rescanVideos => 'Videos erneut scannen';

  @override
  String get resetBrightness => 'Helligkeit zurücksetzen';

  @override
  String get resetToDefault => 'Einstellen auf';

  @override
  String get respectNoMedia => '.nomedia respektieren';

  @override
  String get respectNoMediaSubtitle => 'Ordner mit .nomedia nicht einbeziehen';

  @override
  String get restart => 'Neustart';

  @override
  String get restoreBackup => 'Sicherung wiederherstellen';

  @override
  String get restoreDefaults => 'Standardeinstellungen wiederherstellen';

  @override
  String get restoredBackupSuccessfully => 'Wiederhergestellte Sicherung';

  @override
  String get restoredBackupSuccessfullySub => 'Sicherungsdatei wurde erfolgreich wiederhergestellt';

  @override
  String get resume => 'Fortsetzen';

  @override
  String get resumeIfWasInterrupted => 'Fortsetzen, wenn durch Unterbrechung angehalten wurde';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Fortsetzen, wenn durch Lautstärke angehalten wurde';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Fortsetzen, wenn die Pause weniger als $numberString Minuten gedauert hat',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Umgekehrte Reihenfolge';

  @override
  String get rightAction => 'Rechte Aktion';

  @override
  String get ringtone => 'Klingelton';

  @override
  String get sameDirectoryOnly => 'Nur dasselbe Verzeichnis';

  @override
  String get sample => 'Beispiel';

  @override
  String get sampleRate => 'Stichprobenrate';

  @override
  String get save => 'Speichern';

  @override
  String get saveToLibrary => 'In Bibliothek speichern';

  @override
  String get savedIn => 'Gespeichert in';

  @override
  String get scaleMultiplier => 'Skalenmultiplikator';

  @override
  String get search => 'Suchen';

  @override
  String get searchYoutube => 'Suche YouTube';

  @override
  String get seconds => 'sekunden';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Siehe Projektcode auf $site';
  }

  @override
  String get seekDuration => 'Dauer suchen';

  @override
  String get seekDurationInfo => 'Du kannst auf die aktuelle Dauer tippen, um rückwärts zu suchen & auf die Gesamtdauer, um vorwärts zu suchen';

  @override
  String get seekbar => 'Suchleiste';

  @override
  String get selectAll => 'Alles auswählen';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Wähle Dateien aus, die sich bereits in der lokalen Bibliothek befinden';

  @override
  String get selectedTracks => 'Ausgewählte Titel';

  @override
  String get selfPromotion => 'Selbstvermarktung';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Diese Wörter werden nicht aufgeteilt';

  @override
  String get separatorsMessage =>
      'Leerzeichen sind nicht erforderlich, es sei denn, du möchtest einen Buchstaben/Symbol verwenden, der in einem ganzen Wort vorkommt (wie x und ft.)';

  @override
  String get serverAddress => 'Serveradresse';

  @override
  String get setAs => 'Einstellen als';

  @override
  String get setAsDefault => 'Als Standard festlegen';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Letzte Änderung der Datei als Datum des Video-Uploads festlegen';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Stimmungen einstellen';

  @override
  String get setMoodsSubtitle => 'Verwende Kommas (,) zur Trennung zwischen ihnen';

  @override
  String get setRating => 'Bewertung setzen';

  @override
  String get setTags => 'Tags setzen';

  @override
  String get setYoutubeLink => 'Youtube Link setzen';

  @override
  String get settings => 'Einstellungen';

  @override
  String get setupFirstStartup => 'Richte den ersten Anlauf ein';

  @override
  String get share => 'Teilen';

  @override
  String get shareLogs => 'Protokolle teilen';

  @override
  String get shortcuts => 'Verknüpfungen';

  @override
  String get shouldDuck => 'Sollte senken';

  @override
  String get shouldDuckNote => 'Zeigt an, dass die Lautstärke gesenkt werden soll. z.B.: Benachrichtigung';

  @override
  String get shouldPause => 'Sollte pausieren';

  @override
  String get shouldPauseNote => 'Zeigt an, dass die Wiedergabe pausiert werden soll. z.B.: Anrufe';

  @override
  String get showAll => 'Alle anzeigen';

  @override
  String get showChannelWatermarkInFullscreen => 'Kanal Wasserzeichen im Vollbildmodus anzeigen';

  @override
  String get showFailedOnly => 'Nur fehlgeschlagene anzeigen';

  @override
  String get showHideUnknownFields => 'Unbekannte Felder anzeigen/ausblenden';

  @override
  String get showInSeekbar => 'In Suchleiste anzeigen';

  @override
  String get showMixPlaylistsIn => 'Mixe anzeigen in';

  @override
  String get showMore => 'Mehr anzeigen';

  @override
  String get showShortVideosIn => 'Shorts anzeigen in';

  @override
  String get showSkipButton => 'Überspringen-Schaltfläche anzeigen';

  @override
  String get showVideoEndcards => 'Video Endkarten anzeigen';

  @override
  String get showWebm => 'webm anzeigen';

  @override
  String get shuffle => 'Mischen';

  @override
  String get shuffleAll => 'Alle mischen';

  @override
  String get shuffleNext => 'Als nächstes mischen';

  @override
  String get signIn => 'Anmelden';

  @override
  String get signInCanceled => 'Anmeldung abgebrochen';

  @override
  String get signInFailed => 'Anmeldung fehlgeschlagen';

  @override
  String get signInToYourAccount => 'Bei deinem Konto anmelden';

  @override
  String get signInYouDontHaveAccount => 'Du hast kein angemeldetes Konto';

  @override
  String get signInYouNeedAccountToViewPage => 'Du brauchst ein Konto, um diese Seite zu sehen';

  @override
  String get signOut => 'Abmelden';

  @override
  String signOutFromName({required String name}) {
    return 'Abmeldung von $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Die Anmeldung ermöglicht normales Nutzen';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Erhalte frühzeitigen Zugang über Patreon oder mit einem Coupon';

  @override
  String get similarDiscoverDate => 'Ähnliches Entdeckungsdatum';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Titel, die ungefähr zur gleichen Zeit wie $currentTrack entdeckt wurden, generieren';
  }

  @override
  String get similarTimeRange => 'Ähnliche Zeitspanne';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Titel, die du ungefähr zur gleichen Zeit wie $currentTrack angehört hast, generieren';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'Größe';

  @override
  String get skip => 'Überspringen';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Stille überspringen';

  @override
  String get skipSponsorSegmentsInVideos => 'Sponsor-Segmente in Videos überspringen';

  @override
  String get sleepAfter => 'Danach schlafen';

  @override
  String get sleepTimer => 'Schlaftimer';

  @override
  String get socials => 'Sozialen';

  @override
  String get socialsSubtitle => 'Besuchen Sie uns auf Unseren Plattformen für Updates, Tipps, Diskussionen & Ideen';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Sortieren nach';

  @override
  String get source => 'Quelle';

  @override
  String get speed => 'Geschwindigkeit';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Gestaffelte Album-Rasteransicht';

  @override
  String get start => 'Start';

  @override
  String get stats => 'Statistiken';

  @override
  String get statsSubtitle => 'Hier findest du einige Informationen über deine Bibliothek';

  @override
  String get stop => 'Anhalten';

  @override
  String get stopAfterThisTrack => 'Nach diesem Track anhalten';

  @override
  String get stopAfterThisVideo => 'Nach diesem Video anhalten';

  @override
  String get storagePermissionDenied => 'Erlaubnis verweigert';

  @override
  String get storagePermissionDeniedSubtitle => 'Bitte erlaube den Zugriff, um diese Aktion durchführen zu können';

  @override
  String get stretchLyricsDuration => 'Dehnung Songtext Dauer';

  @override
  String get subdirectory => 'Unterverzeichnis';

  @override
  String get subscribe => 'Abonnieren';

  @override
  String get subscribed => 'Abonniert';

  @override
  String get subscriber => 'Abonnent';

  @override
  String get subscribers => 'Abonnenten';

  @override
  String get succeeded => 'Erfolgreich';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Haben Sie ein Problem oder einen Vorschlag? Öffnen Sie einen Problem auf $site';
  }

  @override
  String get support => 'Unterstützung';

  @override
  String get supremacy => 'Vorherrschaft';

  @override
  String get sussyBaka => 'Bruder, keine Titel';

  @override
  String get swipeActions => 'Wischaktionen';

  @override
  String get swipeToOpenDrawer => 'Wischen zum Öffnen der Schublade';

  @override
  String get synced => 'Synchronisiert';

  @override
  String get synopsis => 'Synopse';

  @override
  String get tagFields => 'Tag Felder';

  @override
  String get tags => 'Tags';

  @override
  String get tapAction => 'Tippaktion';

  @override
  String get tapToSeek => 'Tippen zum Suchen';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Erscheinungsbild Modus';

  @override
  String get themeModeDark => 'Dunkel';

  @override
  String get themeModeLight => 'Hell';

  @override
  String get themeModeSystem => 'System';

  @override
  String get themeSettings => 'Erscheinungsbild';

  @override
  String get themeSettingsSubtitle => 'Die allgemeine Stimmung deines Players';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Diese Playlist verfügt über aktive Sortierfunktionen. Bitte deaktivieren Sie diese vor der Neusortierung.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Dieses Video ist wahrscheinlich gelöscht oder auf privat gesetzt.';

  @override
  String get thumbnails => 'Vorschaubilder';

  @override
  String get title => 'Titel';

  @override
  String get top => 'Top';

  @override
  String get topComments => 'Top Kommentare';

  @override
  String get topCommentsSubtitle => 'Kommentare oben statt unten anzeigen';

  @override
  String get topRecentAlbums => 'Top Neueste Alben';

  @override
  String get topRecentArtists => 'Top Neueste Künstler';

  @override
  String get topRecents => 'Top Aktuelles';

  @override
  String get totalListenTime => 'Gesamte Hördauer';

  @override
  String get totalListens => 'Gesamt angehört';

  @override
  String get totalTracks => 'Gesamte Titel';

  @override
  String get totalTracksDuration => 'Gesamte Titeldauer';

  @override
  String get track => 'Track';

  @override
  String get trackArtistsSeparator => 'Künstler Separatoren';

  @override
  String get trackGenresSeparator => 'Genres Separatoren';

  @override
  String get trackInfo => 'Track Info';

  @override
  String get trackNotFound => 'Track nicht gefunden';

  @override
  String get trackNumber => 'Track Nummer';

  @override
  String get trackNumberTotal => 'Track Gesamt';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Alter Name: \"$oldName\"\n\nNeuer Name: \"$newName\"\n\nBist du sicher?';
  }

  @override
  String get trackPlayMode => 'Wiedergabemodus';

  @override
  String get trackPlayModeSearchResults => 'Suchergebnisse';

  @override
  String get trackPlayModeSelectedOnly => 'Nur ausgewählter Titel';

  @override
  String get trackPlayModeTrackAlbum => 'Album des Tracks';

  @override
  String get trackPlayModeTrackArtist => 'Hauptkünstler des Tracks';

  @override
  String get trackPlayModeTrackGenre => 'Genre des Tracks';

  @override
  String get trackThumbnailSizeInList => 'Größe des Trackvorschaubildes';

  @override
  String get trackTileCustomization => 'Anpassung der Track-Kacheln';

  @override
  String get trackTileItemsSeparator => 'Element-Trennzeichen';

  @override
  String get tracks => 'Titel';

  @override
  String get tracksExcludedByNomedia => 'Titel ausgeschlossen von .nomedia';

  @override
  String get tracksInfo => 'Titelinfo';

  @override
  String get underrated => 'Unterbewertet';

  @override
  String get undo => 'Rückgängig';

  @override
  String get undoChanges => 'Änderungen rückgängig machen?';

  @override
  String get undoChangesDeletedPlaylist => 'Gelöschte Playlist rückgängig machen';

  @override
  String get undoChangesDeletedQueue => 'Gelöschte Warteschlange rückgängig machen';

  @override
  String get undoChangesDeletedTrack => 'Gelöschter Track rückgängig machen';

  @override
  String get uniqueArtworkHash => 'Einzigartiges Kunstwerk Hash';

  @override
  String get unlimited => 'Unendlich';

  @override
  String get unlisted => 'Ungelistet';

  @override
  String get unlock => 'Freischalten';

  @override
  String get unsubscribe => 'Abmelden';

  @override
  String get update => 'Update';

  @override
  String get updateDirectoryPath => 'Verzeichnispfad updaten';

  @override
  String get updateMissingTracksOnly => 'Nur fehlende Titel aktualisieren';

  @override
  String get updating => 'Updated';

  @override
  String get useCollapsedSettingTiles => 'Zusammengeklappte Einstellungskacheln verwenden';

  @override
  String get useMediaStore => 'Medienspeicher verwenden';

  @override
  String get useMediaStoreSubtitle =>
      '✓ sofortige Indizierungszeit\nx .nomedia wird zwangsweise aktiviert\nx ein paar Metadaten-Tags werden fehlen\nx Youtube-Integration für die lokale Bibliothek wird nicht funktionieren';

  @override
  String get usePitchBlack => 'Pechschwarz verwenden';

  @override
  String get usePitchBlackSubtitle => 'Nützlich für AMOLED Bildschirme.. und sieht cooler aus';

  @override
  String get used => 'Benutzt';

  @override
  String get value => 'Wert';

  @override
  String get valueBetween50200 => 'Wert sollte zwischen 50% und 200% liegen';

  @override
  String get vibration => 'Vibration';

  @override
  String get vibrationType => 'Vibrationsart';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Video Cache';

  @override
  String get videoCacheFile => 'Gecachede Videodatei';

  @override
  String get videoCacheFiles => 'Gecachede Videodateien';

  @override
  String get videoOnly => 'Nur Video';

  @override
  String get videoPlaybackSource => 'Videoquelle';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Dies gibt den lokalen Videos die Priorität, wenn sie nicht gefunden werden, werden sie von youtube geholt';

  @override
  String get videoPlaybackSourceLocal => 'Lokale Videos';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle =>
      'Überprüft, ob eine Videodatei (die in der gewählten Ordnerliste gefunden wurde) einen Dateinamen hat, der den Dateinamen des Tracks enthält';

  @override
  String get videoPlaybackSourceYoutube => 'Von Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Überprüft Dateinamen & Kommentar des Tracks auf einen passenden Youtube-Link, Videos werden für die spätere Verwendung gecached.';

  @override
  String get videoQuality => 'Videoqualität';

  @override
  String get videoQualitySubtitle => 'Die beste verfügbare Qualität wird ausgewählt.';

  @override
  String get videoQualitySubtitleNote =>
      'Es ist immer gut, mehrere Alternativen für den Fall bereitzuhalten, dass eine Qualität nicht gefunden wird, da sonst auf die schlechteste Qualität zurückgegriffen wird';

  @override
  String get videos => 'Videos';

  @override
  String get view => 'Aufruf';

  @override
  String get viewAll => 'Alle anzeigen';

  @override
  String get views => 'Aufrufe';

  @override
  String get volume => 'Lautstärke';

  @override
  String get warning => 'Warnung';

  @override
  String get waveformBarsCount => 'Wellenform Balkenanzahl';

  @override
  String get webmNoEditTagsSupport => 'WEBM Format unterstützt keine Tag Bearbeitung';

  @override
  String get week => 'Woche';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Jahr';

  @override
  String get yes => 'ja';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Deine derzeitige Mitgliedschaft lautet $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Ihre Sonderanfertigung geht verloren. Sind Sie sicher?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Musik';

  @override
  String get youtubeSettingsSubtitle => 'Passe deine Youtube Erfahrung an';

  @override
  String get youtubeStyleMiniplayer => 'Youtube Style Miniplayer';

  @override
  String get ytPreferNewComments => 'Neue Kommentare bevorzugen, wenn möglich';

  @override
  String get ytPreferNewCommentsSubtitle => 'Die im Cache gespeicherte Version wird nur verwendet, wenn keine Verbindung besteht';
}
