// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Romanian Moldavian Moldovan (`ro`).
class AppLocalizationsRo extends AppLocalizations {
  AppLocalizationsRo([String locale = 'ro']) : super(locale);

  @override
  String get about => 'Despre';

  @override
  String get active => 'Activ';

  @override
  String get add => 'Adaugă';

  @override
  String get addAccount => 'Adaugă cont';

  @override
  String get addAll => 'Adaugă tot';

  @override
  String get addAllAndRemoveOldOnes => 'Adaugă tot și elimină cele vechi';

  @override
  String get addAsANewPlaylist => 'Adaugă ca playlist nou';

  @override
  String get addAudioToLocalLibrary => 'Adaugă audio la biblioteca locală';

  @override
  String get addFolder => 'Adaugă folder';

  @override
  String get addLanguage => 'Adaugă limbă';

  @override
  String get addLanguageSubtitle => 'Ajută la traducerea Namida în limba ta';

  @override
  String get addLrcFile => 'Adaugă fișier LRC';

  @override
  String get addMoreFromThisAlbum => 'Adaugă mai multe din acest album la coadă';

  @override
  String get addMoreFromThisArtist => 'Adaugă mai multe de la acest artist la coadă';

  @override
  String get addMoreFromThisFolder => 'Adaugă mai multe din acest folder la coadă';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Adaugă mai multe din $media la coadă';
  }

  @override
  String get addOnlyMissing => 'Adaugă doar lipsuri';

  @override
  String get addToFavourites => 'Adaugă la favorite';

  @override
  String get addToPlaylist => 'Adaugă la playlist';

  @override
  String get addTracksAtTheBeginning => 'Adaugă melodii la început';

  @override
  String get added => 'adăugat';

  @override
  String get advanced => 'Avansat';

  @override
  String get advancedSettings => 'Avansat';

  @override
  String get advancedSettingsSubtitle => 'Setări avansate, nu atinge';

  @override
  String get alarm => 'Alarmă';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Artist album';

  @override
  String get albumArtists => 'Artiști album';

  @override
  String get albumIdentifiers => 'Identificatori album';

  @override
  String get albumThumbnailSizeInList => 'Dimensiune miniatură album';

  @override
  String get albumTileCustomization => 'Personalizare element album';

  @override
  String get albums => 'Albume';

  @override
  String get albumsCount => 'Număr albume';

  @override
  String get all => 'Tot';

  @override
  String get allTime => 'Tot timpul';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Întotdeauna';

  @override
  String get alwaysAsk => 'Întreabă întotdeauna';

  @override
  String get alwaysDim => 'Întunecă întotdeauna';

  @override
  String get alwaysExpandedSearchbar => 'Bară de căutare mereu extinsă';

  @override
  String get alwaysRestore => 'Restaurează întotdeauna';

  @override
  String get animatingThumbnailIntensity => 'Intensitate animație miniatură';

  @override
  String get animatingThumbnailInversed => 'Animații inversate';

  @override
  String get animatingThumbnailInversedSubtitle => 'Vârfurile înalte vor face miniatura mai mică';

  @override
  String get anotherProcessIsRunning => 'Un alt proces rulează deja.';

  @override
  String get appIcon => 'Iconiță aplicație';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Artist';

  @override
  String get artists => 'Artiști';

  @override
  String get artwork => 'Copertă';

  @override
  String get artworkGestures => 'Gesturi copertă';

  @override
  String get artworks => 'Coperte';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Cache audio';

  @override
  String get audioOnly => 'Doar audio';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Interval backup automat';

  @override
  String get autoColoring => 'Colorare automată';

  @override
  String get autoColoringSubtitle => 'Alege automat culorile playerului din coperta curentă';

  @override
  String get autoExtractTagsFromFilename => 'Extrage automat din numele fișierului';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Extrage automat titlul și artistul din titlul video';

  @override
  String get autoGenerated => 'Generat automat';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Pornește automat radio';

  @override
  String get autoStartRadioSubtitle => 'Adaugă automat un playlist mixt când redai o singură melodie';

  @override
  String get automaticBackup => 'Automat';

  @override
  String get automaticBackupSubtitle => 'Aplică automat cel mai recent fișier de backup găsit în locația de backup';

  @override
  String get backupAndRestore => 'Backup și restaurare';

  @override
  String get backupAndRestoreSubtitle => 'Fă backup la baza de date și setări';

  @override
  String get balanced => 'Echilibrat';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Între date';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Listă neagră';

  @override
  String get borderRadiusMultiplier => 'Multiplicator rază colț';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Anulează';

  @override
  String get canceled => 'Anulat';

  @override
  String get changed => 'Schimbat';

  @override
  String get changelog => 'Jurnal modificări';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Canal';

  @override
  String get channels => 'Canale';

  @override
  String get check => 'Verifică';

  @override
  String get checkForMore => 'Verifică pentru mai multe';

  @override
  String get checkList => 'Lista de verificat';

  @override
  String get choose => 'Alege';

  @override
  String get chooseWhatToClear => 'Alege ce să ștergi';

  @override
  String get claim => 'Revendică';

  @override
  String get clear => 'Șterge';

  @override
  String get clearAudioCache => 'Șterge cache audio';

  @override
  String get clearImageCache => 'Șterge cache imagini';

  @override
  String get clearImageCacheWarning => 'Atenție: va rezulta o bibliotecă fără imagini. Folosește doar pentru a reconstrui cache-ul de imagini.';

  @override
  String get clearTrackItem => 'Șterge melodia';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Șterge $numberString melodii',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Șterge cache video';

  @override
  String get clearVideoCacheNote => 'Poți alege ce să ștergi.';

  @override
  String get clock => 'Ceas';

  @override
  String get colorPalette => 'Paletă culori';

  @override
  String get colorPaletteNote1 => 'Apasă lung o culoare pentru a o elimina';

  @override
  String get colorPaletteNote2 => 'Atinge un mix pentru a-l folosi ca culoare implicită';

  @override
  String get colorPalettes => 'Palete culori';

  @override
  String get comment => 'Comentariu';

  @override
  String get comments => 'Comentarii';

  @override
  String get composer => 'Compozitor';

  @override
  String get compress => 'Comprimă';

  @override
  String get compressImages => 'Comprimă imagini';

  @override
  String get compressionPercentage => 'Procent comprimare';

  @override
  String get configure => 'Configurează';

  @override
  String get confirm => 'Confirmă';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Copertă copiată';

  @override
  String get copiedToClipboard => 'Copiat în clipboard';

  @override
  String get copy => 'Copiază';

  @override
  String get corruptedFile => 'Nu s-a putut citi fișierul, ar putea fi corupt';

  @override
  String get couldntOpen => 'Nu s-a putut deschide :(';

  @override
  String get couldntOpenYtLink => 'Niciun link Youtube disponibil pentru această melodie';

  @override
  String get couldntPlayFile => 'Nu s-a putut reda fișierul';

  @override
  String get couldntRenamePlaylist => 'Nu s-a putut redenumi playlist-ul';

  @override
  String get couldntSaveImage => 'Nu s-a putut salva imaginea';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Țară';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Creează';

  @override
  String get createBackup => 'Creează backup';

  @override
  String get createNewPlaylist => 'Creează playlist nou';

  @override
  String get createdBackupSuccessfully => 'Backup creat';

  @override
  String get createdBackupSuccessfullySub => 'Fișierul de backup a fost creat cu succes';

  @override
  String get crossPlatformSync => 'Sincronizare cross-platform';

  @override
  String get crossfadeDuration => 'Durată crossfade';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Activează crossfade automat în ultimele $secondsString secunde',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Nu activa crossfade automat';

  @override
  String get custom => 'Personalizat';

  @override
  String get customizations => 'Personalizări';

  @override
  String get customizationsSubtitle => 'Personalizează aspectul playerului, fă-l al tău';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'Bază de date';

  @override
  String get date => 'Dată';

  @override
  String get dateAdded => 'Data adăugării';

  @override
  String get dateCreated => 'Data creării';

  @override
  String get dateModified => 'Data modificării';

  @override
  String get dateTimeFormat => 'Format dată și oră';

  @override
  String get day => 'Zi';

  @override
  String get days => 'Zile';

  @override
  String get defaultBackupLocation => 'Locație backup implicită';

  @override
  String get defaultColor => 'Culoare implicită';

  @override
  String get defaultColorSubtitle => 'Setează o culoare pentru player';

  @override
  String get defaultDownloadLocation => 'Locație descărcare implicită';

  @override
  String get defaultLabel => 'Implicit';

  @override
  String get defaultLibraryTab => 'Tab bibliotecă implicit';

  @override
  String get delete => 'Șterge';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Ștergi $countString fișier reprezentând $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Șterge permanent $numberText din stocare';
  }

  @override
  String get deletePlaylist => 'Șterge playlist';

  @override
  String get deleteTempFiles => 'Șterge fișiere temporare';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Descriere';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Ai vrut să spui';

  @override
  String get dimIntensity => 'Intensitate întuncare';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Întunecă miniplayerul după $secondsString secunde de inactivitate',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Directorul nu există';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Dezactivează tot';

  @override
  String get disableReordering => 'Dezactivează reordonarea';

  @override
  String get disableSearchCleanup => 'Dezactivează curățarea căutării';

  @override
  String get discNumber => 'Număr disc';

  @override
  String get discNumberTotal => 'Total discuri';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Nu-mi place';

  @override
  String get dismissibleMiniplayer => 'Miniplayer care poate fi închis';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Data din colțul dreapta sus al cardului de album';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Afișează data albumului în colțul dreapta sus al cardului';

  @override
  String get displayArtistBeforeTitle => 'Afișează artistul înaintea titlului';

  @override
  String get displayArtworkOnLockscreen => 'Afișează coperta pe ecranul de blocare';

  @override
  String get displayAudioInfoInMiniplayer => 'Afișează info audio';

  @override
  String get displayFavButtonInNotification => 'Afișează butonul de favorite în notificare';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Miniatura ar putea fi deplasată.';

  @override
  String get displayFavouriteIconInTrackTile => 'Afișează butonul de favorite';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Afișează durata rămasă în loc de total';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Afișează al treilea element în fiecare rând';

  @override
  String get displayThirdRowInTrackTile => 'Afișează al treilea rând';

  @override
  String get displayTrackNumberInAlbumPage => 'Afișează numărul melodiei în pagina albumului';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Afișează o casetă mică cu numărul melodiei în pagina albumului';

  @override
  String get doNothing => 'Nu face nimic';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Gata';

  @override
  String get dontAskAgain => 'Nu mai întreba';

  @override
  String get dontDim => 'Nu întuneca';

  @override
  String get dontRestorePosition => 'Nu restaura';

  @override
  String get dontResume => 'Nu relua';

  @override
  String get doubleTapToToggleLyrics => 'Atinge de două ori pentru a comuta versurile';

  @override
  String get download => 'Descarcă';

  @override
  String get downloadingWillOverrideIt => 'Descărcarea îl va suprascrie';

  @override
  String get downloads => 'Descărcări';

  @override
  String get downloadsMetadataTags => 'Descarcă etichete metadata';

  @override
  String get downloadsMetadataTagsSubtitle => 'Extrage artistul, titlul și albumul din informațiile video implicit';

  @override
  String get dragToSeek => 'Trage pentru a naviga';

  @override
  String get duckAudio => 'Coboară volumul';

  @override
  String get duplicatedItemsAdding => 'Încerci să adaugi elemente care există deja în acest playlist';

  @override
  String get duplicatedTracks => 'Melodii duplicate';

  @override
  String get duration => 'Durată';

  @override
  String get edgeColorsSwitching => 'Comutare culori margini';

  @override
  String get edit => 'Editează';

  @override
  String get editArtwork => 'Editează coperta';

  @override
  String get editTags => 'Editează etichete';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'ai câmpuri cu valori goale/fără sens, asigură-te că vrei cu adevărat să le editezi';

  @override
  String get emptyValue => 'Valoare goală';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Activează efect de estompare';

  @override
  String get enableBottomNavBar => 'Activează bara de navigare de jos';

  @override
  String get enableBottomNavBarSubtitle => 'Elementele sunt în meniul lateral oricum';

  @override
  String get enableClipboardMonitoring => 'Activează monitorizarea clipboard-ului';

  @override
  String get enableClipboardMonitoringSubtitle => 'Permite lipirea linkurilor și textelor în bara de căutare din mers';

  @override
  String get enableCrossfadeEffect => 'Activează efect crossfade';

  @override
  String get enableFadeEffectOnPlayPause => 'Activează efect de estompare la redare/pauză';

  @override
  String get enableFoldersHierarchy => 'Activează ierarhia folderelor';

  @override
  String get enableGlowEffect => 'Activează efect de strălucire';

  @override
  String get enableM3uSync => 'Activează sincronizare M3U';

  @override
  String get enableM3uSyncNote1 => 'Sincronizarea M3U permite salvarea modificărilor playlist-ului în fișierul M3U original';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Dacă ceva nu merge, un backup al acestui playlist va fi găsit în $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Dacă e refuzat, toate modificările făcute în acest playlist vor fi pierdute la repornire';

  @override
  String get enableMiniplayerParticles => 'Activează particule în mișcare';

  @override
  String get enableParallaxEffect => 'Activează efect paralaxă';

  @override
  String get enablePartyMode => 'Activează modul petrecere';

  @override
  String get enablePartyModeSubtitle => 'Aplică efect fancy de respirație pe margini';

  @override
  String get enablePictureInPicture => 'Activează Picture-in-Picture';

  @override
  String get enableReordering => 'Activează reordonarea';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Activează curățarea căutării';

  @override
  String get enableSearchCleanupSubtitle => 'Toate simbolurile și spațiile vor fi ignorate';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'Activează redare video';

  @override
  String get enterSymbol => 'Te rog introdu un simbol';

  @override
  String get equalizer => 'Egalizator';

  @override
  String get error => 'Eroare';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Eroare la redarea melodiei';

  @override
  String get excludedFodlers => 'Foldere excluse';

  @override
  String get exit => 'Ieșire';

  @override
  String get exitAppSubtitle => 'Atinge din nou pentru a ieși';

  @override
  String get expandedMiniplayer => 'Miniplayer extins';

  @override
  String get exportAsM3u => 'Exportă ca M3U';

  @override
  String get extension => 'Extensie';

  @override
  String get externalFiles => 'Fișiere externe';

  @override
  String get extract => 'Extrage';

  @override
  String get extractAllColorPalettes => 'Extrage toate paletele de culori';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Extragi paletele rămase $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Extrage artiști feat. din titlu';

  @override
  String get extractFeatArtistSubtitle => 'Extrage artiștii (feat. X) și (ft. X) ca o nouă intrare de artist.';

  @override
  String get extractingInfo => 'Extragere informații';

  @override
  String get extras => 'Extra';

  @override
  String get extrasSubtitle => 'Setări extra pentru a-ți rafina experiența';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Eșuat';

  @override
  String get failedEdits => 'Editări eșuate';

  @override
  String get favourites => 'Favorite';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Se preia';

  @override
  String get fetchingOfAllVideos => 'Preluarea tuturor videourilor';

  @override
  String get file => 'Fișier';

  @override
  String get fileAlreadyExists => 'Fișierul există deja';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Nume fișier';

  @override
  String get fileNameWoExt => 'Nume fișier fără extensie';

  @override
  String get filenameShouldntStartWith => 'Numele fișierului nu ar trebui să înceapă cu';

  @override
  String get files => 'Fișiere';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Filtrează albume';

  @override
  String get filterArtists => 'Filtrează artiști';

  @override
  String get filterGenres => 'Filtrează genuri';

  @override
  String get filterPlaylists => 'Filtrează playlisturi';

  @override
  String get filterTracks => 'Filtrează melodii';

  @override
  String get filterTracksBy => 'Filtrează melodii în listele de căutare după';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Melodii filtrate după dimensiune și durată';

  @override
  String get finished => 'Terminat';

  @override
  String get finishedUpdatingLibrary => 'Actualizare bibliotecă terminată';

  @override
  String get firstListen => 'Prima ascultare';

  @override
  String get fixYtdlpBigThumbnailSize => 'Repară dimensiunea mare a miniaturii yt-dlp';

  @override
  String get floatingActionButton => 'Buton acțiune flotant';

  @override
  String get folder => 'Folder';

  @override
  String get folderName => 'Nume folder';

  @override
  String get folders => 'Foldere';

  @override
  String get fontScale => 'Scară font';

  @override
  String get forceMiniplayerFollowTrackColors => 'Forțează miniplayerul să urmeze culorile melodiei';

  @override
  String get forceSquaredAlbumThumbnail => 'Forțează miniatură album pătrată';

  @override
  String get forceSquaredThumbnailNote => 'Dimensiunea miniaturii și înălțimea elementului NU sunt egale, aspectul pătratic nu va fi conform așteptărilor. Vrei să le faci egale?';

  @override
  String get forceSquaredTrackThumbnail => 'Forțează miniatură melodie pătrată';

  @override
  String get forceStopColorPaletteGeneration => 'Oprești forțat extragerea paletelor de culori? poți continua mai târziu';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Ecran complet';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Generează';

  @override
  String get generateFromDates => 'Interval de timp';

  @override
  String get generateFromDatesSubtitle => 'Generează melodii pe care le-ai ascultat într-un interval de timp';

  @override
  String get generateRandomPlaylist => 'Generează playlist aleatoriu';

  @override
  String get genre => 'Gen';

  @override
  String get genres => 'Genuri';

  @override
  String get goToAlbum => 'Mergi la album';

  @override
  String get goToArtist => 'Mergi la artist';

  @override
  String get goToChannel => 'Mergi la canal';

  @override
  String get goToFolder => 'Mergi la folder';

  @override
  String get goodLooking => 'Arată bine';

  @override
  String get grantStoragePermission => 'Acordă permisiune stocare';

  @override
  String get group => 'Grupează';

  @override
  String get groupArtworksByAlbum => 'Grupează coperte după album';

  @override
  String get guide => 'Ghid';

  @override
  String get hapticFeedback => 'Feedback haptic';

  @override
  String get heightOfAlbumTile => 'Înălțime element album';

  @override
  String get heightOfTrackTile => 'Înălțime element melodie';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Potriviri mari';

  @override
  String get highPerformance => 'Performanță înaltă';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Istoric';

  @override
  String get historyImportMissingEntriesNote => 'Aceste intrări nu au putut fi găsite în bibliotecă, dacă crezi că există, ia în considerare adăugarea lor manuală';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString ascultări pentru $oldTrackInfo vor fi înlocuite cu $newTrackInfo, confirmă?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Acasă';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'Format 12 ore';

  @override
  String get hours => 'Ore';

  @override
  String get iReadAndAgree => 'Am citit și sunt de acord';

  @override
  String get ifNotPlaying => 'Dacă nu redă';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Descărcările pot fi limitate când aplicația are restricții de baterie';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignoră prefixele comune la sortare';

  @override
  String get ignores => 'Ignoră';

  @override
  String get imageSource => 'Sursă imagine';

  @override
  String get immersiveMode => 'Mod imersiv';

  @override
  String get immersiveModeSubtitle => 'Ascunde barele de stare și navigare când miniplayerul e extins';

  @override
  String get import => 'Importă';

  @override
  String get importAll => 'Importă tot';

  @override
  String get importLastFmHistory => 'Importă istoric LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Mergi la $lastfmCsvLink\n\n2. Scrie numele tău de utilizator, preia și descarcă fișierul csv.\n\n3. Alege fișierul din ecranul următor.';
  }

  @override
  String get importTimeRange => 'Importă interval de timp';

  @override
  String get importYoutubeHistory => 'Importă istoric Youtube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Mergi la $takeoutLink\n\n2. Apasă \"Formate multiple\" și lângă \"Istoric\" alege \"JSON\".\n\n3. Apasă \"Toate datele Youtube incluse\", Deselectează tot și alege doar istoricul.\n\n4. Creează export, descarcă și dezarhivează.\n\n5. Alege \"watch-history.json\" din ecranul următor.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString canale importate cu succes',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText playlisturi importate cu succes',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Include videoclipuri';

  @override
  String get indexRefreshRequired => 'Fă o reîmprospătare după ce schimbi asta';

  @override
  String get indexer => 'Indexator';

  @override
  String get indexerNote => 'Notă: Numărul incomplet de coperte se referă la coperte duplicate și negăsite';

  @override
  String get indexerSubtitle => 'Gestionează biblioteca ta muzicală';

  @override
  String get infinityQueueOnNextPrev => 'Coadă infinită la următorul/precedentul';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'apăsând următorul în timp ce redai ultimul element va sări la primul și invers';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'inserat';

  @override
  String get instantlyApplies => 'Se aplică instant';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Inversează selecția';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Element';

  @override
  String get jump => 'Sari';

  @override
  String get jumpToDay => 'Sari la zi';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Sari la prima melodie după terminarea cozii';

  @override
  String get keepCachedVersions => 'Păstrează versiunile din cache';

  @override
  String get keepFileDates => 'Păstrează datele fișierelor';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniplayerul e extins';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniplayerul e extins și un video se redă';

  @override
  String get keepScreenAwakeNone => 'Nu păstra ecranul aprins';

  @override
  String get keepScreenAwakeWhen => 'Păstrează ecranul aprins când';

  @override
  String get killPlayerAfterDismissingApp => 'Oprește playerul după închiderea aplicației';

  @override
  String get language => 'Limbă';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Taburi bibliotecă';

  @override
  String get libraryTabsReorder => 'Poți reordona taburile activate.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Îmi place';

  @override
  String get liked => 'Apreciat';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Lista de foldere';

  @override
  String get loadAll => 'Încarcă tot';

  @override
  String get loadingFile => 'Se încarcă fișierul';

  @override
  String get local => 'Local';

  @override
  String get localVideoMatching => 'Potrivire video locală';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Apasă lung versurile pentru ecran complet';

  @override
  String get lostMemories => 'Amintiri pierdute';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'pe vremea asta, acum $numberString ani',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Amplificator volum';

  @override
  String get lyricist => 'Autor versuri';

  @override
  String get lyrics => 'Versuri';

  @override
  String get lyricsSource => 'Sursă versuri';

  @override
  String get m3uPlaylist => 'Playlist M3U';

  @override
  String get makeYourFirstListen => 'Fă prima ta ascultare!';

  @override
  String get manage => 'Gestionează';

  @override
  String get manageYourAccounts => 'Gestionează-ți conturile';

  @override
  String get manualBackup => 'Manual';

  @override
  String get manualBackupSubtitle => 'alege un fișier specific';

  @override
  String get markAsRead => 'Marchează ca citit';

  @override
  String get matchAllTracks => 'Potrivește toate melodiile';

  @override
  String get matchAllTracksNote => 'asta poate avea impact asupra vitezei de potrivire, deoarece va verifica toate melodiile din biblioteca ta';

  @override
  String get matchingType => 'Tip potrivire';

  @override
  String get maxAudioCacheSize => 'Dimensiune maximă cache audio';

  @override
  String get maxImageCacheSize => 'Dimensiune maximă cache imagini';

  @override
  String get maxVideoCacheSize => 'Dimensiune maximă cache video';

  @override
  String get maximum => 'Maximum';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store este activat, asta nu va avea efect';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Cod';

  @override
  String get membershipCodeSentToEmail => 'Cod trimis la emailul tău';

  @override
  String get membershipDidntChange => 'Abonamentul nu s-a schimbat';

  @override
  String get membershipEnjoyNew => 'Bucură-te de noul tău abonament';

  @override
  String get membershipFreeCoupon => 'Cupon gratuit';

  @override
  String get membershipManage => 'Gestionează abonamentul';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Nu s-au găsit abonamente pentru acest utilizator';

  @override
  String get membershipSignInToPatreonAccount => 'Conectează-te la contul tău patreon';

  @override
  String get membershipUnknown => 'Abonament necunoscut';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Ai nevoie de abonament $name1 sau $name2 pentru a adăuga conturi multiple';
  }

  @override
  String get merge => 'Îmbină';

  @override
  String get metadataCache => 'Cache metadata';

  @override
  String get metadataEditFailed => 'Editarea metadatelor a eșuat';

  @override
  String get metadataReadFailed => 'Citirea metadatelor a eșuat';

  @override
  String get minFileDuration => 'Durată minimă melodie';

  @override
  String get minFileSize => 'Dimensiune minimă fișier';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Durată minimă melodie pentru a restaura ultima poziție redată';

  @override
  String get minValueCantBeMoreThanMax => 'Valoarea minimă nu poate fi mai mare decât maximul';

  @override
  String get minValueToCountTrackListen => 'Numără o ascultare după: ';

  @override
  String get minimizedMiniplayer => 'Miniplayer minimizat';

  @override
  String get minimum => 'Minim';

  @override
  String get minimumOneFolderSubtitle => 'Ar trebui să fie cel puțin 1 folder, adaugă mai multe foldere dacă vrei să elimini acesta';

  @override
  String get minimumOneItem => 'Nu s-a putut elimina elementul';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Cel puțin $numberString elemente trebuie să rămână',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Personalizare miniplayer';

  @override
  String get minutes => 'minute';

  @override
  String get missingEntries => 'Intrări lipsă';

  @override
  String get missingTracks => 'Melodii lipsă';

  @override
  String get mix => 'Mix';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Playlist mix generat de youtube';

  @override
  String get mixes => 'Mixuri';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Lună';

  @override
  String get months => 'Luni';

  @override
  String get mood => 'Stare';

  @override
  String get moods => 'Stări';

  @override
  String get more => 'Mai mult';

  @override
  String get mostPlayed => 'Cele mai redate';

  @override
  String get multipleTracksTagsEditNote => 'Ești pe cale să editezi aceste melodii,\nCâmpurile neschimbate rămân neatinse.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Nume';

  @override
  String get nameContainsBadCharacter => 'Numele conține caracter invalid';

  @override
  String get never => 'Niciodată';

  @override
  String get newDirectory => 'Director nou';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Adaugă melodii';

  @override
  String get newTracksMoods => 'Stare';

  @override
  String get newTracksMoodsSubtitle => 'Generează melodii bazate pe stările disponibile';

  @override
  String get newTracksRandom => 'Aleatoriu';

  @override
  String get newTracksRandomSubtitle => 'Alege melodii aleatorii din biblioteca ta';

  @override
  String get newTracksRatings => 'Evaluări';

  @override
  String get newTracksRatingsSubtitle => 'Generează melodii care au o anumită evaluare';

  @override
  String get newTracksRecommended => 'Recomandate';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Generează melodii pe care le asculți de obicei cu $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Dată lansare similară';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Generează melodii lansate cam în același timp cu $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Melodia are an necunoscut';

  @override
  String get newest => 'Cele mai noi';

  @override
  String get next => 'Următorul';

  @override
  String get no => 'nu';

  @override
  String get noChangesFound => 'Nu s-au găsit modificări.';

  @override
  String get noEnoughTracks => 'Nu ai prea multe melodii..';

  @override
  String get noExcludedFolders => 'Nu ai foldere excluse';

  @override
  String get noFolderChosen => 'Nu ai ales niciun folder';

  @override
  String get noMoodsAvailable => 'Nu sunt stări disponibile';

  @override
  String get noNetworkAvailableToFetchData => 'Nu e disponibilă rețea pentru a prelua datele';

  @override
  String get noTracksFound => 'Nu s-au găsit melodii';

  @override
  String get noTracksFoundBetweenDates => 'Acest interval de timp nu are melodii.';

  @override
  String get noTracksFoundInDirectory => 'Nu s-au găsit melodii în acest director';

  @override
  String get noTracksInHistory => 'Nu ai destule melodii în istoric';

  @override
  String get nonActive => 'Neactiv';

  @override
  String get nonFavourites => 'Nefavorite';

  @override
  String get none => 'Nimic';

  @override
  String get normalizeAudio => 'Normalizează audio';

  @override
  String get normalizeAudioSubtitle => 'Normalizează volumul citind eticheta replay gain sau informațiile furnizate de youtube';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Notă';

  @override
  String get notification => 'Notificare';

  @override
  String get notifications => 'Notificări';

  @override
  String get numberOfTracks => 'Număr melodii';

  @override
  String get ofLabel => 'din';

  @override
  String get offlineSearch => 'Căutare offline';

  @override
  String get offset => 'Decalaj';

  @override
  String get oldDirectory => 'Director vechi';

  @override
  String get oldDirectoryStillHasTracks => 'Directorul vechi mai are melodii, confirmă?';

  @override
  String get oldestWatch => 'Cea mai veche vizionare';

  @override
  String get onInterruption => 'La întrerupere';

  @override
  String get onNotificationTap => 'La atingerea notificării';

  @override
  String get onOpeningYoutubeLink => 'La deschiderea linkului youtube';

  @override
  String get onSwiping => 'La glisare';

  @override
  String get onVolumeZero => 'La volum 0';

  @override
  String get ongoing => 'În desfășurare';

  @override
  String get open => 'Deschide';

  @override
  String get openApp => 'Deschide aplicația';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Deschide în vizualizarea Youtube';

  @override
  String get openMiniplayer => 'Deschide miniplayerul';

  @override
  String get openQueue => 'Deschide coada';

  @override
  String get openYoutubeLink => 'Deschide link Youtube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operațiunea $name necesită cont, Conectează-te pentru a continua';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operațiunea $operation necesită cel puțin abonament $name';
  }

  @override
  String get or => 'sau';

  @override
  String get others => 'Altele';

  @override
  String get output => 'Ieșire';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Suprascrie fișierele vechi din același folder';

  @override
  String get palette => 'Paletă';

  @override
  String get paletteMix => 'Mix';

  @override
  String get paletteNewMix => 'Mix nou';

  @override
  String get paletteSelectedMix => 'Mix selectat';

  @override
  String get parallelDownloads => 'Descărcări paralele';

  @override
  String get parsed => 'analizat';

  @override
  String get password => 'Password';

  @override
  String get path => 'Cale completă fișier';

  @override
  String get pause => 'Pauză';

  @override
  String get pauseFadeDuration => 'Durată estompare pauză';

  @override
  String get pausePlayback => 'Pune pe pauză';

  @override
  String get percentage => 'Procent';

  @override
  String get performanceMode => 'Mod performanță';

  @override
  String get performanceNote => 'Ar putea afecta performanța';

  @override
  String get personalized => 'Personalizat';

  @override
  String get personalizedRelatedVideos => 'Videoclipuri asemănătoare personalizate';

  @override
  String get personalizedRelatedVideosSubtitle => 'Dezactivarea va crește utilizarea datelor';

  @override
  String get pickColorsFromDeviceWallpaper => 'Alege culori din fundalul dispozitivului';

  @override
  String get pickFromStorage => 'Alege din stocare';

  @override
  String get pinned => 'Fixat';

  @override
  String get pitch => 'Tonalitate';

  @override
  String get plain => 'Simplu';

  @override
  String get play => 'Redă';

  @override
  String get playAfter => 'Redă după';

  @override
  String get playAfterNextPrev => 'Redă automat la următorul/precedentul';

  @override
  String get playAll => 'Redă tot';

  @override
  String get playFadeDuration => 'Durată estompare redare';

  @override
  String get playLast => 'Redă ultimul';

  @override
  String get playNext => 'Redă următorul';

  @override
  String get playbackSetting => 'Redare';

  @override
  String get playbackSettingSubtitle => 'Poate fi accesat direct în player apăsând lung butonul audio';

  @override
  String get playlist => 'Playlist';

  @override
  String get playlists => 'Playlisturi';

  @override
  String get playlistsImportM3uNative => 'Asta va importa playlisturile M3U pentru a fi folosite doar de namida, folosește dacă migrezi';

  @override
  String get playlistsImportM3uSynced =>
      'Asta va importa automat playlisturile M3U din folderele indexatorului și le va păstra sincronizate cu fișierul M3U original. activează dacă accesezi/modifici playlisturile din alte aplicații';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Importă automat playlisturi M3U';

  @override
  String get pleaseEnterADifferentName => 'Acest nume există deja :(\nte rog încearcă alt nume fancy';

  @override
  String get pleaseEnterALink => 'Te rog introdu un link';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. asta e un link youtube?';

  @override
  String get pleaseEnterAName => 'Te rog introdu un nume';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Previne melodii duplicate';

  @override
  String get preventDuplicatedTracksSubtitle => 'Folosește numele fișierului pentru a identifica unic melodiile';

  @override
  String get preview => 'Previzualizare';

  @override
  String get previous => 'Precedentul';

  @override
  String get previousButtonReplays => 'Butonul precedent reia';

  @override
  String get previousButtonReplaysSubtitle => 'dacă e apăsat când poziția curentă era mai mare decât durata de navigare';

  @override
  String get prioritizeEmbeddedLyrics => 'Prioritizează versurile încorporate';

  @override
  String get priority => 'Prioritate';

  @override
  String get private => 'Privat';

  @override
  String get progress => 'Progres';

  @override
  String get promptToChangeTrackPath => 'De obicei asta se întâmplă când ștergi/muți/redenumești fișierul în afara namida. Vrei să actualizezi calea curentă?';

  @override
  String get public => 'Public';

  @override
  String get queue => 'Coadă';

  @override
  String get queues => 'Cozi';

  @override
  String get random => 'Aleatoriu';

  @override
  String get randomPicks => 'Alegeri aleatorii';

  @override
  String get rating => 'Evaluare';

  @override
  String get reIndex => 'Reindexează';

  @override
  String get reIndexSubtitle => 'Reconstruiește biblioteca ta muzicală de la zero';

  @override
  String get reIndexWarning => 'Acest proces ar putea dura ceva timp, în funcție de dimensiunea bibliotecii tale.\n\nCopertele nu vor fi reindexate atâta timp cât încă există';

  @override
  String get recentAlbums => 'Albume recente';

  @override
  String get recentArtists => 'Artiști recenți';

  @override
  String get recentListens => 'Ascultări recente';

  @override
  String get recentlyAdded => 'Adăugate recent';

  @override
  String get recordLabel => 'Casă de discuri';

  @override
  String get refresh => 'Reîmprospătează';

  @override
  String get refreshLibrary => 'Reîmprospătează biblioteca';

  @override
  String get refreshLibrarySubtitle => 'Verifică pentru muzică nou adăugată sau ștearsă';

  @override
  String get refreshOnStartup => 'Reîmprospătează la pornire';

  @override
  String get relatedVideos => 'Videoclipuri asemănătoare';

  @override
  String get rememberAudioOnlyMode => 'Ține minte modul doar audio';

  @override
  String get remixer => 'Remixer';

  @override
  String get remove => 'Elimină';

  @override
  String get removeDuplicates => 'Elimină duplicate';

  @override
  String get removeFromFavourites => 'Elimină din favorite';

  @override
  String get removeFromLibrary => 'Elimină din bibliotecă';

  @override
  String get removeFromPlaylist => 'Elimină din playlist';

  @override
  String get removeQueue => 'Elimină coada';

  @override
  String get removeSourceFromHistory => 'Elimină sursa din istoric';

  @override
  String get removeWhitespaces => 'Elimină spațiile';

  @override
  String get removed => 'Eliminat';

  @override
  String get rename => 'Redenumește';

  @override
  String get renamePlaylist => 'Redenumește playlist';

  @override
  String get reorderable => 'Reordonabil';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Repetă încă $number ori',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Mod repetare';

  @override
  String get repeatModeAll => 'Repetă toată coada';

  @override
  String get repeatModeNone => 'Oprește la ultima melodie';

  @override
  String get repeatModeOne => 'Repetă melodia curentă';

  @override
  String get replaceAllListensWithAnotherTrack => 'Înlocuiește toate ascultările cu altă melodie';

  @override
  String get replies => 'Răspunsuri';

  @override
  String get reply => 'Răspunde';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Necesită ștergerea cache-ului de imagini și reindexare';

  @override
  String get rescanVideos => 'Re-scanează videoclipuri';

  @override
  String get resetBrightness => 'Resetează luminozitatea';

  @override
  String get resetToDefault => 'Setează la';

  @override
  String get respectNoMedia => 'Respectă .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Nu include foldere care au .nomedia';

  @override
  String get restart => 'Repornește';

  @override
  String get restoreBackup => 'Restaurează backup';

  @override
  String get restoreDefaults => 'Restaurează valorile implicite';

  @override
  String get restoredBackupSuccessfully => 'Backup restaurat';

  @override
  String get restoredBackupSuccessfullySub => 'Fișierul de backup a fost restaurat cu succes';

  @override
  String get resume => 'Reia';

  @override
  String get resumeIfWasInterrupted => 'Reia dacă a fost întreruptă';

  @override
  String get resumeIfWasPausedByVolume => 'Reia dacă a fost pusă pe pauză de volum';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Reia dacă a fost pusă pe pauză mai puțin de $numberString minute',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Inversează ordinea';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Ton de apel';

  @override
  String get sameDirectoryOnly => 'Doar același director';

  @override
  String get sample => 'Mostră';

  @override
  String get sampleRate => 'Rată eșantionare';

  @override
  String get save => 'Salvează';

  @override
  String get saveToLibrary => 'Salvează în bibliotecă';

  @override
  String get savedIn => 'Salvat în';

  @override
  String get scaleMultiplier => 'Multiplicator scară';

  @override
  String get search => 'Caută';

  @override
  String get searchYoutube => 'Caută pe YouTube';

  @override
  String get seconds => 'secunde';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Durată navigare';

  @override
  String get seekDurationInfo => 'Poți atinge durata curentă pentru a naviga înapoi și durata totală pentru a naviga înainte';

  @override
  String get seekbar => 'Bară navigare';

  @override
  String get selectAll => 'Selectează tot';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Selectează fișiere deja în biblioteca locală';

  @override
  String get selectedTracks => 'Melodii selectate';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Aceste cuvinte nu vor fi împărțite';

  @override
  String get separatorsMessage => 'Nu e nevoie să inserezi spații, decât dacă vrei să folosești o literă/simbol care poate fi găsit într-un cuvânt întreg (cum ar fi x și ft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Setează ca';

  @override
  String get setAsDefault => 'Setează ca implicit';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Setează data ultimei modificări a fișierului ca dată de încărcare video';

  @override
  String get setMoods => 'Setează stări';

  @override
  String get setMoodsSubtitle => 'Folosește virgule (,) pentru a le separa';

  @override
  String get setRating => 'Setează evaluare';

  @override
  String get setTags => 'Setează etichete';

  @override
  String get setYoutubeLink => 'Setează link Youtube';

  @override
  String get settings => 'Setări';

  @override
  String get setupFirstStartup => 'Configurează prima pornire';

  @override
  String get share => 'Distribuie';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Comenzi rapide';

  @override
  String get shouldDuck => 'Ar trebui să coboare';

  @override
  String get shouldDuckNote => 'Indică faptul că volumul ar trebui coborât. ex: notificare';

  @override
  String get shouldPause => 'Ar trebui să pună pe pauză';

  @override
  String get shouldPauseNote => 'Indică faptul că redarea ar trebui pusă pe pauză. ex: apeluri';

  @override
  String get showAll => 'Arată tot';

  @override
  String get showChannelWatermarkInFullscreen => 'Arată watermark-ul canalului pe ecran complet';

  @override
  String get showFailedOnly => 'Arată doar eșuatele';

  @override
  String get showHideUnknownFields => 'Arată/ascunde câmpuri necunoscute';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Arată mixurile în';

  @override
  String get showMore => 'Arată mai mult';

  @override
  String get showShortVideosIn => 'Arată clipurile scurte în';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'Arată cardurile de final video';

  @override
  String get showWebm => 'Arată webm';

  @override
  String get shuffle => 'Amestecă';

  @override
  String get shuffleAll => 'Amestecă tot';

  @override
  String get shuffleNext => 'Amestecă următorul';

  @override
  String get signIn => 'Conectează-te';

  @override
  String get signInCanceled => 'Conectarea a fost anulată';

  @override
  String get signInFailed => 'Conectarea a eșuat';

  @override
  String get signInToYourAccount => 'Conectează-te la contul tău';

  @override
  String get signInYouDontHaveAccount => 'Nu ai niciun cont conectat';

  @override
  String get signInYouNeedAccountToViewPage => 'Ai nevoie de un cont pentru a vizualiza această pagină';

  @override
  String get signOut => 'Deconectează-te';

  @override
  String signOutFromName({required String name}) {
    return 'Deconectează-te de la $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Conectarea permite utilizarea de bază';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Obține acces anticipat prin patreon sau folosind cupon';

  @override
  String get similarDiscoverDate => 'Dată descoperire similară';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generează melodii descoperite cam în același timp cu $currentTrack';
  }

  @override
  String get similarTimeRange => 'Interval de timp similar';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generează melodii pe care le-ai ascultat cam în același timp cu $currentTrack';
  }

  @override
  String get singles => 'Melodii single';

  @override
  String get size => 'Dimensiune';

  @override
  String get skip => 'Sari';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Sari peste tăcere';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Adormire după';

  @override
  String get sleepTimer => 'Temporizator somn';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Sortează după';

  @override
  String get source => 'Sursă';

  @override
  String get speed => 'Viteză';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Vizualizare grilă albume eșalonată';

  @override
  String get start => 'Start';

  @override
  String get stats => 'Statistici';

  @override
  String get statsSubtitle => 'Iată câteva informații despre biblioteca ta';

  @override
  String get stop => 'Oprește';

  @override
  String get stopAfterThisTrack => 'Oprește după această melodie';

  @override
  String get stopAfterThisVideo => 'Oprește după acest videoclip';

  @override
  String get storagePermissionDenied => 'Permisiune refuzată';

  @override
  String get storagePermissionDeniedSubtitle => 'Te rog permite accesul pentru a putea efectua această acțiune';

  @override
  String get stretchLyricsDuration => 'Întinde durata versurilor';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Abonează-te';

  @override
  String get subscribed => 'Abonat';

  @override
  String get subscriber => 'Abonat';

  @override
  String get subscribers => 'Abonați';

  @override
  String get succeeded => 'Reușit';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Suport';

  @override
  String get supremacy => 'Supremație';

  @override
  String get sussyBaka => 'Bruh nu sunt melodii';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Glisează pentru a deschide meniul';

  @override
  String get synced => 'Sincronizat';

  @override
  String get synopsis => 'Sinopsis';

  @override
  String get tagFields => 'Câmpuri etichete';

  @override
  String get tags => 'Etichete';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Atinge pentru a naviga';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Mod temă';

  @override
  String get themeModeDark => 'Întunecat';

  @override
  String get themeModeLight => 'Luminos';

  @override
  String get themeModeSystem => 'Sistem';

  @override
  String get themeSettings => 'Temă';

  @override
  String get themeSettingsSubtitle => 'Atmosfera generală a playerului tău';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Acest playlist are sortări active, te rog dezactivează-le înainte de reordonare.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Acest videoclip e probabil șters sau setat ca privat.';

  @override
  String get thumbnails => 'Miniaturi';

  @override
  String get title => 'Titlu';

  @override
  String get top => 'Top';

  @override
  String get topComments => 'Comentarii top';

  @override
  String get topCommentsSubtitle => 'Afișează comentariile sus în loc de jos';

  @override
  String get topRecentAlbums => 'Top albume recente';

  @override
  String get topRecentArtists => 'Top artiști recenți';

  @override
  String get topRecents => 'Top recente';

  @override
  String get totalListenTime => 'Timp total ascultare';

  @override
  String get totalListens => 'Total ascultări';

  @override
  String get totalTracks => 'Total melodii';

  @override
  String get totalTracksDuration => 'Durată totală melodii';

  @override
  String get track => 'Melodie';

  @override
  String get trackArtistsSeparator => 'Separatori artiști';

  @override
  String get trackGenresSeparator => 'Separatori genuri';

  @override
  String get trackInfo => 'Info melodie';

  @override
  String get trackNotFound => 'Melodie negăsită';

  @override
  String get trackNumber => 'Număr melodie';

  @override
  String get trackNumberTotal => 'Total melodii';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Nume vechi: \"$oldName\"\n\nNume nou: \"$newName\"\n\nEști sigur?';
  }

  @override
  String get trackPlayMode => 'Mod redare';

  @override
  String get trackPlayModeSearchResults => 'Rezultate căutare';

  @override
  String get trackPlayModeSelectedOnly => 'Doar melodia selectată';

  @override
  String get trackPlayModeTrackAlbum => 'Albumul melodiei';

  @override
  String get trackPlayModeTrackArtist => 'Artistul principal al melodiei';

  @override
  String get trackPlayModeTrackGenre => 'Genul melodiei';

  @override
  String get trackThumbnailSizeInList => 'Dimensiune miniatură melodie';

  @override
  String get trackTileCustomization => 'Personalizare element melodie';

  @override
  String get trackTileItemsSeparator => 'Separator elemente';

  @override
  String get tracks => 'Melodii';

  @override
  String get tracksExcludedByNomedia => 'Melodii excluse de .nomedia';

  @override
  String get tracksInfo => 'Info melodii';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Anulează';

  @override
  String get undoChanges => 'Anulezi modificările?';

  @override
  String get undoChangesDeletedPlaylist => 'Anulează playlist șters';

  @override
  String get undoChangesDeletedQueue => 'Anulează coadă ștearsă';

  @override
  String get undoChangesDeletedTrack => 'Anulează melodie ștearsă';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Nelimitat';

  @override
  String get unlisted => 'Nelistat';

  @override
  String get unlock => 'Deblochează';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Actualizează';

  @override
  String get updateDirectoryPath => 'Actualizează calea directorului';

  @override
  String get updateMissingTracksOnly => 'Actualizează doar melodiile lipsă';

  @override
  String get updating => 'Se actualizează';

  @override
  String get useCollapsedSettingTiles => 'Folosește elemente de setări restrânse';

  @override
  String get useMediaStore => 'Folosește Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ timp instant de indexare\n× respectarea .nomedia va fi forțat activată\n× unele etichete metadata vor lipsi\n× integrarea youtube pentru biblioteca locală nu va funcționa';

  @override
  String get usePitchBlack => 'Folosește negru profund';

  @override
  String get usePitchBlackSubtitle => 'Util pentru ecrane AMOLED.. și arată mai cool';

  @override
  String get used => 'Folosit';

  @override
  String get value => 'Valoare';

  @override
  String get valueBetween50200 => 'Valoarea ar trebui să fie între 50% și 200%';

  @override
  String get vibration => 'Vibrare';

  @override
  String get vibrationType => 'Tip vibrare';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Cache video';

  @override
  String get videoCacheFile => 'Fișier video din cache';

  @override
  String get videoCacheFiles => 'Fișiere video din cache';

  @override
  String get videoOnly => 'Doar video';

  @override
  String get videoPlaybackSource => 'Sursă video';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Asta va da prioritate videoclipurilor locale, dacă nu sunt găsite atunci va prelua de pe youtube';

  @override
  String get videoPlaybackSourceLocal => 'Videoclipuri locale';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Verifică dacă vreun fișier video (găsit în lista de foldere alese) are un nume de fișier care conține numele fișierului melodiei';

  @override
  String get videoPlaybackSourceYoutube => 'De pe Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Verifică în numele fișierului melodiei și comentariu pentru orice link youtube potrivit, videoclipurile sunt păstrate în cache pentru utilizare ulterioară.';

  @override
  String get videoQuality => 'Calitate video';

  @override
  String get videoQualitySubtitle => 'Cea mai înaltă calitate disponibilă va fi aleasă.';

  @override
  String get videoQualitySubtitleNote => 'E întotdeauna bine să păstrezi mai multe alternative în caz că o calitate nu e găsită, altfel va reveni la cea mai proastă calitate';

  @override
  String get videos => 'Videoclipuri';

  @override
  String get view => 'vizualizare';

  @override
  String get viewAll => 'Vezi tot';

  @override
  String get views => 'vizualizări';

  @override
  String get volume => 'Volum';

  @override
  String get warning => 'Avertisment';

  @override
  String get waveformBarsCount => 'Număr bare formă de undă';

  @override
  String get webmNoEditTagsSupport => 'Formatul WEBM nu suportă editarea etichetelor';

  @override
  String get week => 'Săptămână';

  @override
  String get year => 'An';

  @override
  String get yes => 'da';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Abonamentul tău curent este $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Ordinea ta personalizată va fi pierdută. Ești sigur?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Music';

  @override
  String get youtubeSettingsSubtitle => 'Personalizează experiența Youtube';

  @override
  String get youtubeStyleMiniplayer => 'Miniplayer în stil Youtube';

  @override
  String get ytPreferNewComments => 'Preferă comentarii noi când e posibil';

  @override
  String get ytPreferNewCommentsSubtitle => 'Versiunea din cache va fi folosită doar când nu e conexiune';
}
