// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Turkish (`tr`).
class AppLocalizationsTr extends AppLocalizations {
  AppLocalizationsTr([String locale = 'tr']) : super(locale);

  @override
  String get about => 'Hakkında';

  @override
  String get active => 'Aktif';

  @override
  String get add => 'Ekle';

  @override
  String get addAccount => 'Hesap ekle';

  @override
  String get addAll => 'Tümünü ekle';

  @override
  String get addAllAndRemoveOldOnes => 'Tümünü ekle ve eskilerini kaldır';

  @override
  String get addAsANewPlaylist => 'Yeni bir Çalma Listesi olarak ekle';

  @override
  String get addAudioToLocalLibrary => 'Ses dosyasını yerel kütüphaneye ekle';

  @override
  String get addFolder => 'Klasör ekle';

  @override
  String get addLanguage => 'Dil ekle';

  @override
  String get addLanguageSubtitle => 'Namida\'yı kendi dilinize çevirmeye yardım edin';

  @override
  String get addLrcFile => 'LRC dosyası ekle';

  @override
  String get addMoreFromThisAlbum => 'Bu Albümden daha fazlasını sıraya ekle';

  @override
  String get addMoreFromThisArtist => 'Bu Sanatçıdan daha fazlasını sıraya ekle';

  @override
  String get addMoreFromThisFolder => 'Bu Klasörden daha fazlasını sıraya ekle';

  @override
  String addMoreFromToQueue({required String media}) {
    return '$media\'dan daha fazlasını sıraya ekle';
  }

  @override
  String get addOnlyMissing => 'Sadece eksik olanları ekle';

  @override
  String get addToFavourites => 'Favorilere ekle';

  @override
  String get addToPlaylist => 'Çalma Listesine ekle';

  @override
  String get addTracksAtTheBeginning => 'Parçaları başa ekle';

  @override
  String get added => 'Eklendi';

  @override
  String get advanced => 'Gelişmiş';

  @override
  String get advancedSettings => 'Gelişmiş Ayarlar';

  @override
  String get advancedSettingsSubtitle => 'Gelişmiş Ayarlar, dokunmayın';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Albüm';

  @override
  String get albumArtist => 'Albüm Sanatçısı';

  @override
  String get albumArtists => 'Albüm Sanatçıları';

  @override
  String get albumIdentifiers => 'Albüm Tanımlayıcıları';

  @override
  String get albumThumbnailSizeInList => 'Albüm Küçük Resim Boyutu';

  @override
  String get albumTileCustomization => 'Albüm Kutucuğu Özelleştirme';

  @override
  String get albums => 'Albümler';

  @override
  String get albumsCount => 'Albüm Sayısı';

  @override
  String get all => 'Tümü';

  @override
  String get allTime => 'Tüm zamanlar';

  @override
  String get alreadyExists => 'Zaten mevcut';

  @override
  String get always => 'Her zaman';

  @override
  String get alwaysAsk => 'Her zaman sor';

  @override
  String get alwaysDim => 'Her Zaman Karart';

  @override
  String get alwaysExpandedSearchbar => 'Her zaman genişletilmiş arama çubuğu';

  @override
  String get alwaysRestore => 'Her zaman geri yükle';

  @override
  String get animatingThumbnailIntensity => 'Küçük Resim Animasyon Yoğunluğu';

  @override
  String get animatingThumbnailInversed => 'Ters Animasyonlar';

  @override
  String get animatingThumbnailInversedSubtitle => 'Yüksek zirveler küçük resmin küçülmesine neden olur';

  @override
  String get anotherProcessIsRunning => 'Başka bir işlem zaten çalışıyor.';

  @override
  String get appIcon => 'Uygulama İkonu';

  @override
  String get appVersion => 'Uygulama Sürümü';

  @override
  String get artist => 'Sanatçı';

  @override
  String get artists => 'Sanatçılar';

  @override
  String get artwork => 'Görsel';

  @override
  String get artworkGestures => 'Görsel Hareketleri';

  @override
  String get artworks => 'Görseller';

  @override
  String get audio => 'Ses';

  @override
  String get audioCache => 'Ses Önbelleği';

  @override
  String get audioOnly => 'Yalnızca Ses';

  @override
  String get auto => 'Otomatik';

  @override
  String get autoBackupInterval => 'Otomatik yedekleme aralığı';

  @override
  String get autoColoring => 'Otomatik Renklendirme';

  @override
  String get autoColoringSubtitle => 'Mevcut görselden otomatik olarak oynatıcı renklerini seç';

  @override
  String get autoExtractTagsFromFilename => 'Dosya adından otomatik çıkarım';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Video başlığından Başlık ve Sanatçıyı otomatik çıkar';

  @override
  String get autoGenerated => 'Otomatik Oluşturuldu';

  @override
  String get autoSkip => 'Oto Geç';

  @override
  String get autoSkipOnce => 'Bir Kez Oto Geç';

  @override
  String get autoStartRadio => 'Radyoyu otomatik başlat';

  @override
  String get autoStartRadioSubtitle => 'Tek bir parça çalındığında karışık çalma listesi otomatik eklenir';

  @override
  String get automaticBackup => 'Otomatik';

  @override
  String get automaticBackupSubtitle => 'Yedekleme konumunda bulunan en son yedek dosyasını otomatik olarak uygular';

  @override
  String get backupAndRestore => 'Yedekleme ve Geri Yükleme';

  @override
  String get backupAndRestoreSubtitle => 'Veritabanınızı ve ayarlarınızı yedekleyin';

  @override
  String get balanced => 'Dengeli';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Tarihler Arasında';

  @override
  String get bitrate => 'Bit Hızı';

  @override
  String get blacklist => 'Kara Liste';

  @override
  String get borderRadiusMultiplier => 'Kenar Yuvarlaklığı Çarpanı';

  @override
  String get cache => 'Önbellek';

  @override
  String get cancel => 'İptal';

  @override
  String get canceled => 'İptal Edildi';

  @override
  String get changed => 'Değiştirildi';

  @override
  String get changelog => 'Değişiklik Günlüğü';

  @override
  String get changelogSubtitle => 'Namida içinde eklenmiş/düzeltilmiş yeni şeyleri görün';

  @override
  String get channel => 'Kanal';

  @override
  String get channels => 'Kanallar';

  @override
  String get check => 'Kontrol Et';

  @override
  String get checkForMore => 'Daha fazlasını kontrol et';

  @override
  String get checkList => 'Kontrol Listesi';

  @override
  String get choose => 'Seç';

  @override
  String get chooseWhatToClear => 'Ne temizleneceğini seç';

  @override
  String get claim => 'Talep et';

  @override
  String get clear => 'Temizle';

  @override
  String get clearAudioCache => 'Ses Önbelleğini Temizle';

  @override
  String get clearImageCache => 'Görsel Önbelleğini Temizle';

  @override
  String get clearImageCacheWarning => 'Uyarı: Görseller olmadan bir kütüphane oluşacaktır. Sadece görsel önbelleğini yeniden oluşturmak için kullanın.';

  @override
  String get clearTrackItem => 'Parçayı Temizle';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString Kaydı Sil',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Video Önbelleğini Temizle';

  @override
  String get clearVideoCacheNote => 'Ne sileceğinizi seçebilirsiniz.';

  @override
  String get clock => 'Saat';

  @override
  String get colorPalette => 'Renk Paleti';

  @override
  String get colorPaletteNote1 => 'Bir rengi kaldırmak için uzun basın';

  @override
  String get colorPaletteNote2 => 'Varsayılan renk olarak kullanmak için bir karışıma dokunun';

  @override
  String get colorPalettes => 'Renk Paletleri';

  @override
  String get comment => 'Yorum';

  @override
  String get comments => 'Yorumlar';

  @override
  String get composer => 'Besteci';

  @override
  String get compress => 'Sıkıştır';

  @override
  String get compressImages => 'Görselleri Sıkıştır';

  @override
  String get compressionPercentage => 'Sıkıştırma yüzdesi';

  @override
  String get configure => 'Yapılandır';

  @override
  String get confirm => 'Onayla';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'Görsel Kopyalandı';

  @override
  String get copiedToClipboard => 'Panoya Kopyalandı';

  @override
  String get copy => 'Kopyala';

  @override
  String get corruptedFile => 'Dosya işlenemedi, bozuk olabilir';

  @override
  String get couldntOpen => 'Açılamadı :(';

  @override
  String get couldntOpenYtLink => 'Bu parça için bir YouTube bağlantısı bulunamadı';

  @override
  String get couldntPlayFile => 'Dosya oynatılamadı';

  @override
  String get couldntRenamePlaylist => 'Çalma listesi yeniden adlandırılamadı';

  @override
  String get couldntSaveImage => 'Görsel kaydedilemedi';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Ülke';

  @override
  String get coupon => 'Kupon';

  @override
  String get create => 'Oluştur';

  @override
  String get createBackup => 'Yedekleme Oluştur';

  @override
  String get createNewPlaylist => 'Yeni Çalma Listesi Oluştur';

  @override
  String get createdBackupSuccessfully => 'Yedekleme Oluşturuldu';

  @override
  String get createdBackupSuccessfullySub => 'Yedekleme dosyası başarıyla oluşturuldu';

  @override
  String get crossPlatformSync => 'Platformlar Arası Eşitleme';

  @override
  String get crossfadeDuration => 'Crossfade süresi';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Son $secondsString saniyede Crossfade otomatik olarak tetiklenir',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Crossfade otomatik olarak tetiklenmesin';

  @override
  String get custom => 'Özel';

  @override
  String get customizations => 'Özelleştirmeler';

  @override
  String get customizationsSubtitle => 'Oynatıcınızı nasıl görüneceğini özelleştirin, kendi tarzınızı yaratın';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Veri sağlayıcısı: $name';
  }

  @override
  String get dataSaver => 'Veri Tasarrufu';

  @override
  String get dataSaverMode => 'Veri Tasarrufu Modu';

  @override
  String get database => 'Veritabanı';

  @override
  String get date => 'Tarih';

  @override
  String get dateAdded => 'Eklenme Tarihi';

  @override
  String get dateCreated => 'Oluşturulma Tarihi';

  @override
  String get dateModified => 'Değiştirilme Tarihi';

  @override
  String get dateTimeFormat => 'Tarih ve Saat Formatı';

  @override
  String get day => 'Gün';

  @override
  String get days => 'Günler';

  @override
  String get defaultBackupLocation => 'Varsayılan Yedekleme Konumu';

  @override
  String get defaultColor => 'Varsayılan Renk';

  @override
  String get defaultColorSubtitle => 'Oynatıcı tarafından kullanılacak bir renk ayarla';

  @override
  String get defaultDownloadLocation => 'Varsayılan İndirme Konumu';

  @override
  String get defaultLabel => 'Varsayılan';

  @override
  String get defaultLibraryTab => 'Varsayılan Kütüphane Sekmesi';

  @override
  String get delete => 'Sil';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Toplam boyutu $totalSizeText olan $countString dosya silinsin mi?',
      one: 'Toplam boyutu $totalSizeText olan $countString dosya silinsin mi?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return '$numberText öğeyi cihaz depolamasından kalıcı olarak sil';
  }

  @override
  String get deletePlaylist => 'Çalma Listesini Sil';

  @override
  String get deleteTempFiles => 'Geçici dosyaları sil';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Açıklama';

  @override
  String get developer => 'Geliştirici';

  @override
  String get development => 'Geliştirme';

  @override
  String get didYouMean => 'Bunu mu demek istediniz';

  @override
  String get dimIntensity => 'Karanlık Yoğunluğu';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Miniplayer\'ı $secondsString saniye hareketsizlikten sonra karart',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Dizin mevcut değil';

  @override
  String get disable => 'Devre Dışı Bırak';

  @override
  String get disableAll => 'Tümünü Devre Dışı Bırak';

  @override
  String get disableReordering => 'Sıralamayı Devre Dışı Bırak';

  @override
  String get disableSearchCleanup => 'Arama Temizliğini Devre Dışı Bırak';

  @override
  String get discNumber => 'Disk Numarası';

  @override
  String get discNumberTotal => 'Toplam Disk';

  @override
  String get discover => 'Keşfet';

  @override
  String get dislike => 'Beğenmedim';

  @override
  String get dismissibleMiniplayer => 'Kapatılabilir Miniplayer';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Sarıyorken fark yerine gerçek konumu göster';

  @override
  String get displayAlbumCardTopRightDate => 'Albüm Kartının sağ üstünde tarihi göster';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Albüm Kartının sağ üstünde albüm tarihini göster';

  @override
  String get displayArtistBeforeTitle => 'Başlıktan önce sanatçıyı göster';

  @override
  String get displayArtworkOnLockscreen => 'Kilit ekranında görseli göster';

  @override
  String get displayAudioInfoInMiniplayer => 'Ses Bilgisini Göster';

  @override
  String get displayFavButtonInNotification => 'Bildirimde Favori Butonunu Göster';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Küçük resim yer değiştirebilir.';

  @override
  String get displayFavouriteIconInTrackTile => 'Favori Butonunu Göster';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Toplam süre yerine kalan süreyi göster';

  @override
  String get displayStopButtonInNotification => 'Bildirimde Durdur Butonunu Göster';

  @override
  String get displayThirdItemInRowInTrackTile => 'Satırdaki Üçüncü Öğeyi Göster';

  @override
  String get displayThirdRowInTrackTile => 'Üçüncü Satırı Göster';

  @override
  String get displayTrackNumberInAlbumPage => 'Albüm Sayfasında Parça Numarasını Göster';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Albüm sayfasında küçük bir kutuda parça numarasını göster';

  @override
  String get doNothing => 'Hiçbir şey yapma';

  @override
  String get donate => 'Bağış';

  @override
  String get donateSubtitle => 'Buna değer diyorsanız';

  @override
  String get done => 'Tamamlandı';

  @override
  String get dontAskAgain => 'Tekrar sorma';

  @override
  String get dontDim => 'Karartma';

  @override
  String get dontRestorePosition => 'Konumu geri yükleme';

  @override
  String get dontResume => 'Devam ettirme';

  @override
  String get doubleTapToToggleLyrics => 'Şarkı sözlerini aç/kapatmak için çift dokunun';

  @override
  String get download => 'İndir';

  @override
  String get downloadingWillOverrideIt => 'İndirme, mevcut veriyi geçersiz kılar';

  @override
  String get downloads => 'İndirilenler';

  @override
  String get downloadsMetadataTags => 'İndirilenler Meta Etiketleri';

  @override
  String get downloadsMetadataTagsSubtitle => 'Sanatçı, başlık ve albümü varsayılan olarak video bilgisinden çıkarır';

  @override
  String get dragToSeek => 'Araştırmak için sürükle';

  @override
  String get duckAudio => 'Sesi alçalt';

  @override
  String get duplicatedItemsAdding => 'Bu çalma listesine zaten eklenmiş bazı öğeleri eklemeye çalışıyorsunuz';

  @override
  String get duplicatedTracks => 'Yinelenen Parçalar';

  @override
  String get duration => 'Süre';

  @override
  String get edgeColorsSwitching => 'Kenar Renkleri Değişimi';

  @override
  String get edit => 'Düzenle';

  @override
  String get editArtwork => 'Görseli Düzenle';

  @override
  String get editTags => 'Etiketleri Düzenle';

  @override
  String get email => 'E-posta';

  @override
  String get emptyNonMeaningfulTagFields => 'Anlamsız veya boş alanlarınız var, bunları düzenlemek istediğinizden emin olun';

  @override
  String get emptyValue => 'Boş Değer';

  @override
  String get enableArtworkCache => 'Kapak Önbelleğini Aç';

  @override
  String get enableArtworkCacheSubtitle => 'Daha hızlı yükleme ve performans sağlar, fakat alanı daha fazla kullanır';

  @override
  String get enableBlurEffect => 'Bulanıklık Efektini Etkinleştir';

  @override
  String get enableBottomNavBar => 'Alt Gezinme Çubuğunu Etkinleştir';

  @override
  String get enableBottomNavBarSubtitle => 'Öğeler her iki şekilde de menüde bulunur';

  @override
  String get enableClipboardMonitoring => 'Panoyu İzlemeyi Etkinleştir';

  @override
  String get enableClipboardMonitoringSubtitle => 'Arama çubuğuna bağlantı ve metin yapıştırmayı hızlıca yapmanızı sağlar';

  @override
  String get enableCrossfadeEffect => 'Geçişli Solma Efektini Etkinleştir';

  @override
  String get enableFadeEffectOnPlayPause => 'Oynat/Duraklat sırasında Solma Efektini Etkinleştir';

  @override
  String get enableFoldersHierarchy => 'Klasör Hiyerarşisini Etkinleştir';

  @override
  String get enableGlowEffect => 'Parlama Efektini Etkinleştir';

  @override
  String get enableM3uSync => 'M3U Eşitlemeyi Etkinleştir';

  @override
  String get enableM3uSyncNote1 => 'M3U Eşitleme, çalma listesi değişikliklerini orijinal M3U dosyasına kaydetmenize olanak tanır';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Bir şeyler ters giderse, bu çalma listesinin bir yedeği $playlistsBackupPath içinde bulunacaktır';
  }

  @override
  String get enableM3uSyncSubtitle => 'Reddedilirse, bu çalma listesinde yapılan tüm değişiklikler yeniden başlatıldığında kaybolur';

  @override
  String get enableMiniplayerParticles => 'Hareketli Parçacıkları Etkinleştir';

  @override
  String get enableParallaxEffect => 'Paralaks Efektini Etkinleştir';

  @override
  String get enablePartyMode => 'Parti Modunu Etkinleştir';

  @override
  String get enablePartyModeSubtitle => 'Şık kenar nefes alma efektini uygular';

  @override
  String get enablePictureInPicture => 'Resim içinde Resim Modunu Etkinleştir';

  @override
  String get enableReordering => 'Yeniden Sıralamayı Etkinleştir';

  @override
  String get enableReturnYoutubeDislike => 'Beğenmemeleri Aç';

  @override
  String get enableSearchCleanup => 'Arama Temizliğini Etkinleştir';

  @override
  String get enableSearchCleanupSubtitle => 'Tüm Semboller ve Boşluklar görmezden gelinecek';

  @override
  String get enableSponsorblock => 'Sponsor engelini kaldır';

  @override
  String get enableVideoPlayback => 'Video Oynatmayı Etkinleştir';

  @override
  String get enterSymbol => 'Lütfen bir Sembol Girin';

  @override
  String get equalizer => 'Ekolayzer';

  @override
  String get error => 'Hata';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Parça oynatılırken hata oluştu';

  @override
  String get excludedFodlers => 'Hariç Tutulan Klasörler';

  @override
  String get exit => 'Çıkış';

  @override
  String get exitAppSubtitle => 'Çıkmak için tekrar dokunun';

  @override
  String get expandedMiniplayer => 'Genişletilmiş Mini Oynatıcı';

  @override
  String get exportAsM3u => 'M3U olarak Dışa Aktar';

  @override
  String get extension => 'Uzantı';

  @override
  String get externalFiles => 'Harici Dosyalar';

  @override
  String get extract => 'Çıkar';

  @override
  String get extractAllColorPalettes => 'Tüm Renk Paletlerini Çıkar';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Kalan $numberString palet çıkarılsın mı?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'feat. sanatçılarını başlıktan çıkar';

  @override
  String get extractFeatArtistSubtitle => '(feat. X) ve (ft. X) sanatçılarını yeni bir sanatçı girişi olarak çıkarır.';

  @override
  String get extractingInfo => 'Bilgi Çıkarılıyor';

  @override
  String get extras => 'Ekstralar';

  @override
  String get extrasSubtitle => 'Deneyiminizi ince ayarlarla kişiselleştirin';

  @override
  String get extreme => 'Ekstrem';

  @override
  String get failed => 'Başarısız';

  @override
  String get failedEdits => 'Başarısız Düzenlemeler';

  @override
  String get favourites => 'Favoriler';

  @override
  String get features => 'Özellikler';

  @override
  String get fetching => 'Getiriliyor';

  @override
  String get fetchingOfAllVideos => 'Tüm videolar getiriliyor';

  @override
  String get file => 'Dosya';

  @override
  String get fileAlreadyExists => 'Dosya zaten mevcut';

  @override
  String get fileBasedServerWarning => 'Dosyalar, indeksleme için geçici olarak indirilecektir.\nBağlantınızın stabil olduğundan emin olun.';

  @override
  String get fileName => 'Dosya Adı';

  @override
  String get fileNameWoExt => 'Uzantısız Dosya Adı';

  @override
  String get filenameShouldntStartWith => 'Dosya adı ile başlamamalıdır';

  @override
  String get files => 'Dosyalar';

  @override
  String get filler => 'Dolgu bölümler';

  @override
  String get filterAlbums => 'Albümleri Filtrele';

  @override
  String get filterArtists => 'Sanatçıları Filtrele';

  @override
  String get filterGenres => 'Türleri Filtrele';

  @override
  String get filterPlaylists => 'Çalma Listelerini Filtrele';

  @override
  String get filterTracks => 'Parçaları Filtrele';

  @override
  String get filterTracksBy => 'Arama Listelerinde Parçaları Şuna Göre Filtrele';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Boyut ve süreye göre filtrelenmiş parçalar';

  @override
  String get finished => 'Tamamlandı';

  @override
  String get finishedUpdatingLibrary => 'Kütüphane Güncellemesi Tamamlandı';

  @override
  String get firstListen => 'İlk dinleme';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp büyük küçük resim boyutunu düzelt';

  @override
  String get floatingActionButton => 'Yüzen Eylem Düğmesi';

  @override
  String get folder => 'Klasör';

  @override
  String get folderName => 'Klasör Adı';

  @override
  String get folders => 'Klasörler';

  @override
  String get fontScale => 'Yazı Tipi Ölçeği';

  @override
  String get forceMiniplayerFollowTrackColors => 'Mini oynatıcının parça renklerini takip etmesini zorla';

  @override
  String get forceSquaredAlbumThumbnail => 'Kare Albüm Küçük Resmini Zorla';

  @override
  String get forceSquaredThumbnailNote => 'Küçük Resim Boyutu ve Karo Yüksekliği eşit DEĞİLDİR, Kare görünüm beklenildiği gibi olmayabilir, eşitlemek ister misiniz?';

  @override
  String get forceSquaredTrackThumbnail => 'Kare Parça Küçük Resmini Zorla';

  @override
  String get forceStopColorPaletteGeneration => 'Renk paleti çıkarımını zorla durdur? Daha sonra devam edebilirsiniz';

  @override
  String get format => 'Biçim';

  @override
  String get fullscreen => 'Tam Ekran';

  @override
  String get gaplessPlayback => 'Kesintisiz Çalma';

  @override
  String get generate => 'Oluştur';

  @override
  String get generateFromDates => 'Tarih Aralığı';

  @override
  String get generateFromDatesSubtitle => 'Belirli bir zaman aralığında dinlediğiniz parçaları oluşturun';

  @override
  String get generateRandomPlaylist => 'Rastgele Çalma Listesi Oluştur';

  @override
  String get genre => 'Tür';

  @override
  String get genres => 'Türler';

  @override
  String get goToAlbum => 'Albümüne Git';

  @override
  String get goToArtist => 'Sanatçısına Git';

  @override
  String get goToChannel => 'Kanala Git';

  @override
  String get goToFolder => 'Klasöre Git';

  @override
  String get goodLooking => 'Şık görünüm';

  @override
  String get grantStoragePermission => 'Depolama İznini Ver';

  @override
  String get group => 'Grup';

  @override
  String get groupArtworksByAlbum => 'Sanat eserlerini albüme göre grupla';

  @override
  String get guide => 'Rehber';

  @override
  String get hapticFeedback => 'Titreşimli Geri Bildirim';

  @override
  String get heightOfAlbumTile => 'Albüm Karosu Yüksekliği';

  @override
  String get heightOfTrackTile => 'Parça Karosu Yüksekliği';

  @override
  String get hideSkipButtonAfter => 'Atla butonunu gizle';

  @override
  String get highMatches => 'Yüksek eşleşmeler';

  @override
  String get highPerformance => 'Yüksek performans';

  @override
  String get highlight => 'Öne çıkanlar';

  @override
  String get history => 'Geçmiş';

  @override
  String get historyImportMissingEntriesNote => 'Bu girişler kütüphanede bulunamadı, var olduklarına inanıyorsanız, lütfen manuel olarak eklemeyi düşünün';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$oldTrackInfo için mevcut olan $listensCountString dinleme kaydı $newTrackInfo ile değiştirilecek, onaylıyor musunuz?',
      one: '$oldTrackInfo için mevcut olan $listensCountString dinleme kaydı $newTrackInfo ile değiştirilecek, onaylıyor musunuz?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Ana Sayfa';

  @override
  String get hook => 'Kanca';

  @override
  String get host => 'Barındırıcı';

  @override
  String get hourFormat12 => '12 Saat Formatı';

  @override
  String get hours => 'Saatler';

  @override
  String get iReadAndAgree => 'Okudum ve kabul ediyorum';

  @override
  String get ifNotPlaying => 'Oynatılmıyorsa';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Uygulama pil kısıtlaması altındayken indirmeler yavaşlatılabilir';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Sıralarken yaygın örnekleri yok say';

  @override
  String get ignores => 'Görmezden Gel';

  @override
  String get imageSource => 'Resim kaynağı';

  @override
  String get immersiveMode => 'Tam Ekran Modu';

  @override
  String get immersiveModeSubtitle => 'Mini oynatıcı genişletildiğinde Durum ve Navigasyon çubuklarını gizle';

  @override
  String get import => 'İçe Aktar';

  @override
  String get importAll => 'Tümünü İçe Aktar';

  @override
  String get importLastFmHistory => 'LastFm Geçmişini İçe Aktar';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. $lastfmCsvLink adresine gidin\n\n2. Kullanıcı adınızı girin, verileri alın ve CSV dosyasını indirin.\n\n3. Bir sonraki ekrandan dosyayı seçin.';
  }

  @override
  String get importTimeRange => 'Zaman Aralığını İçe Aktar';

  @override
  String get importYoutubeHistory => 'YouTube Geçmişini İçe Aktar';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. $takeoutLink adresine gidin\n\n2. \"Çoklu Formatlar\"a tıklayın ve \"Geçmiş\"in yanında \"JSON\"u seçin.\n\n3. \"Tüm YouTube verileri dahil\" seçeneğine tıklayın, Tümünü Kaldır seçeneğini işaretleyin ve sadece geçmişi seçin.\n\n4. Dışa Aktar oluşturun, indirin ve çıkarın.\n\n5. Bir sonraki ekrandan \"watch-history.json\" dosyasını seçin.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString kanal başarıyla içe aktarıldı',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText çalma listesi başarıyla içe aktarıldı',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Videoları Dahil Et';

  @override
  String get indexRefreshRequired => 'Bu değişiklikten sonra bir yenileme yapın';

  @override
  String get indexer => 'Dizinleyici';

  @override
  String get indexerNote => 'Not: Eksik Sanat Eserleri, yinelenen ve bulunamayan sanat eserlerini ifade eder';

  @override
  String get indexerSubtitle => 'Müzik Kitaplığınızı Yönetin';

  @override
  String get infinityQueueOnNextPrev => 'Sonraki/Önceki\'de Sonsuz Kuyruk';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'son öğe çalarken sonraki düğmesine basıldığında ilk öğeye geçer ve tersi';

  @override
  String get info => 'Bilgi';

  @override
  String get inserted => 'Eklendi';

  @override
  String get instantlyApplies => 'Anında Uygulanır';

  @override
  String get interactionReminder => 'Etkileşim Uyarısı';

  @override
  String get intro => 'Giriş';

  @override
  String get invertSelection => 'Seçimi Ters Çevir';

  @override
  String get issues => 'Sorunlar';

  @override
  String get item => 'Öğe';

  @override
  String get jump => 'Atla';

  @override
  String get jumpToDay => 'Güne Atla';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Kuyruk tamamlandıktan sonra ilk parçaya atla';

  @override
  String get keepCachedVersions => 'Önbelleğe Alınmış Sürümleri Sakla';

  @override
  String get keepFileDates => 'Dosya Tarihlerini Sakla';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Mini Oynatıcı Genişletilmiş';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Mini Oynatıcı Genişletilmiş ve Bir Video Çalıyor';

  @override
  String get keepScreenAwakeNone => 'Ekranı açık tutma';

  @override
  String get keepScreenAwakeWhen => 'Ekranı şu durumlarda açık tut';

  @override
  String get killPlayerAfterDismissingApp => 'Uygulama kapatıldığında oynatıcıyı kapat';

  @override
  String get language => 'Dil';

  @override
  String get learnMore => 'Daha fazla öğren';

  @override
  String get leftAction => 'Sol Eylem';

  @override
  String get legacyAuthentication => 'Eski Kimlik Doğrulama';

  @override
  String get libraryTabs => 'Kitaplık Sekmeleri';

  @override
  String get libraryTabsReorder => 'Aktif sekmeleri yeniden sıralayabilirsiniz.';

  @override
  String get license => 'Lisans';

  @override
  String get licenseSubtitle => 'Namida tarafından kullanılan lisanslar ve sözleşmeler';

  @override
  String get like => 'Beğen';

  @override
  String get liked => 'Beğenildi';

  @override
  String get link => 'Bağlantı';

  @override
  String get listOfFolders => 'Klasör Listesi';

  @override
  String get loadAll => 'Tümünü Yükle';

  @override
  String get loadingFile => 'Dosya Yükleniyor';

  @override
  String get local => 'Yerel';

  @override
  String get localVideoMatching => 'Yerel Video Eşleştirme';

  @override
  String get login => 'Giriş Yap';

  @override
  String get longPressAction => 'Uzun Basma Eylemi';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Tam ekran için şarkı sözlerine uzun basın';

  @override
  String get lostMemories => 'Kayıp Anılar';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'bu zamanlarda, $numberString yıl önce',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Bağlantısız İçerikler';

  @override
  String get loudnessEnhancer => 'Ses Güçlendirici';

  @override
  String get lyricist => 'Söz Yazarı';

  @override
  String get lyrics => 'Şarkı Sözleri';

  @override
  String get lyricsSource => 'Şarkı Sözü Kaynağı';

  @override
  String get m3uPlaylist => 'M3U Çalma Listesi';

  @override
  String get makeYourFirstListen => 'İlk dinlemenizi yapın!';

  @override
  String get manage => 'Yönet';

  @override
  String get manageYourAccounts => 'Hesaplarınızı Yönetin';

  @override
  String get manualBackup => 'Manuel';

  @override
  String get manualBackupSubtitle => 'belirli bir dosya seçin';

  @override
  String get markAsRead => 'Okundu Olarak İşaretle';

  @override
  String get matchAllTracks => 'Tüm Parçaları Eşleştir';

  @override
  String get matchAllTracksNote => 'bu, eşleştirme hızını etkileyebilir, çünkü kitaplığınızdaki tüm parçaları kontrol eder';

  @override
  String get matchingType => 'Eşleştirme Türü';

  @override
  String get maxAudioCacheSize => 'Maksimum ses önbellek boyutu';

  @override
  String get maxImageCacheSize => 'Maksimum görsel önbellek boyutu';

  @override
  String get maxVideoCacheSize => 'Maksimum video önbellek boyutu';

  @override
  String get maximum => 'Maksimum';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Ortam Deposu etkin, bu ayarın bir etkisi olmayacak';

  @override
  String get medium => 'Orta';

  @override
  String get membershipCode => 'Kod';

  @override
  String get membershipCodeSentToEmail => 'Kod e-postanıza gönderildi';

  @override
  String get membershipDidntChange => 'Üyelik değişmedi';

  @override
  String get membershipEnjoyNew => 'Yeni üyeliğinizin keyfini çıkarın';

  @override
  String get membershipFreeCoupon => 'Ücretsiz Kupon';

  @override
  String get membershipManage => 'Üyeliğinizi yönetin';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Bu kullanıcı için abonelik bulunamadı';

  @override
  String get membershipSignInToPatreonAccount => 'Patreon hesabınıza giriş yapın';

  @override
  String get membershipUnknown => 'Bilinmeyen Üyelik';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Birden fazla hesap eklemek için $name1 veya $name2 üyeliğine ihtiyacınız var';
  }

  @override
  String get merge => 'Birleştir';

  @override
  String get metadataCache => 'Meta Veri Önbelleği';

  @override
  String get metadataEditFailed => 'Meta veriyi düzenleme başarısız oldu';

  @override
  String get metadataReadFailed => 'Meta veriyi okuma başarısız oldu';

  @override
  String get minFileDuration => 'Minimum Parça Süresi';

  @override
  String get minFileSize => 'Minimum Dosya Boyutu';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Son oynatma konumunu geri yüklemek için minimum parça süresi';

  @override
  String get minValueCantBeMoreThanMax => 'Minimum değer, maksimumdan fazla olamaz';

  @override
  String get minValueToCountTrackListen => 'Bir dinleme olarak saymak için gereken süre: ';

  @override
  String get minimizedMiniplayer => 'Küçültülmüş Mini Oynatıcı';

  @override
  String get minimum => 'Minimum';

  @override
  String get minimumOneFolderSubtitle => 'En az 1 klasör olmalı, bu klasörü kaldırmak istiyorsanız daha fazla klasör ekleyin';

  @override
  String get minimumOneItem => 'Öğe kaldırılamadı';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'En az $numberString öğe kalmalıdır',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum bölüm süresi';

  @override
  String get miniplayerCustomization => 'Mini Oynatıcı Özelleştirme';

  @override
  String get minutes => 'dakika';

  @override
  String get missingEntries => 'Eksik Kayıtlar';

  @override
  String get missingTracks => 'Eksik Parçalar';

  @override
  String get mix => 'Karıştır';

  @override
  String get mixPlaylistGeneratedByYoutube => 'YouTube tarafından oluşturulan karışım çalma listesi';

  @override
  String get mixes => 'Karışımlar';

  @override
  String get mobile => 'Mobil';

  @override
  String get month => 'Ay';

  @override
  String get months => 'Aylar';

  @override
  String get mood => 'Ruh Hali';

  @override
  String get moods => 'Ruh Hali';

  @override
  String get more => 'Daha Fazla';

  @override
  String get mostPlayed => 'En Çok Çalınan';

  @override
  String get multipleTracksTagsEditNote => 'Bu parçaları düzenlemek üzeresiniz,\nDeğiştirilmemiş alanlar dokunulmadan kalacak.';

  @override
  String get musicOfftopic => 'Müzik Dışı Kısımlar';

  @override
  String get name => 'Ad';

  @override
  String get nameContainsBadCharacter => 'Ad geçersiz bir karakter içeriyor';

  @override
  String get never => 'Asla';

  @override
  String get newDirectory => 'Yeni dizin';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Parça Ekle';

  @override
  String get newTracksMoods => 'Ruh Hali';

  @override
  String get newTracksMoodsSubtitle => 'Mevcut ruh hallerine göre parçalar oluştur';

  @override
  String get newTracksRandom => 'Rastgele';

  @override
  String get newTracksRandomSubtitle => 'Kütüphanenizden rastgele parçalar seçin';

  @override
  String get newTracksRatings => 'Değerlendirmeler';

  @override
  String get newTracksRatingsSubtitle => 'Belirli bir değerlendirmeye sahip parçalar oluştur';

  @override
  String get newTracksRecommended => 'Önerilen';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return '$currentTrack ile genellikle dinlediğiniz parçaları oluştur';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Benzer Çıkış Tarihi';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return '$currentTrack ile aynı zamanlarda yayınlanan parçaları oluştur';
  }

  @override
  String get newTracksUnknownYear => 'Yılı bilinmeyen parça';

  @override
  String get newest => 'En Yeni';

  @override
  String get next => 'Sonraki';

  @override
  String get no => 'hayır';

  @override
  String get noChangesFound => 'Hiçbir değişiklik bulunamadı.';

  @override
  String get noEnoughTracks => 'Yeterli parçanız yok..';

  @override
  String get noExcludedFolders => 'Hariç tutulan klasörünüz yok';

  @override
  String get noFolderChosen => 'Herhangi bir klasör seçmediniz';

  @override
  String get noMoodsAvailable => 'Mevcut ruh hali yok';

  @override
  String get noNetworkAvailableToFetchData => 'Veri almak için ağ bağlantısı yok';

  @override
  String get noTracksFound => 'Hiçbir parça bulunamadı';

  @override
  String get noTracksFoundBetweenDates => 'Bu zaman aralığında hiçbir parça yok.';

  @override
  String get noTracksFoundInDirectory => 'Bu dizinde hiçbir parça bulunamadı';

  @override
  String get noTracksInHistory => 'Geçmişte yeterli parçanız yok';

  @override
  String get nonActive => 'Aktif Olmayan';

  @override
  String get nonFavourites => 'Favori Olmayanlar';

  @override
  String get none => 'Hiçbiri';

  @override
  String get normalizeAudio => 'Sesi normalize et';

  @override
  String get normalizeAudioSubtitle => 'Ses seviyesini tekrar kazanç etiketi veya YouTube tarafından sağlanan bilgilerle normalize eder';

  @override
  String get notAvailableForYourDevice => 'Senin Cihazın için Uygun Değil';

  @override
  String get notSupportedForNetworkFiles => 'Ağ Dosyaları Desteklenmiyor';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'Not';

  @override
  String get notification => 'Bildirim';

  @override
  String get notifications => 'Bildirimler';

  @override
  String get numberOfTracks => 'Parça Sayısı';

  @override
  String get ofLabel => 'of';

  @override
  String get offlineSearch => 'Çevrimdışı Arama';

  @override
  String get offset => 'Ofset';

  @override
  String get oldDirectory => 'Eski dizin';

  @override
  String get oldDirectoryStillHasTracks => 'Eski Dizin hala bazı parçalara sahip, onaylıyor musunuz?';

  @override
  String get oldestWatch => 'En Eski İzleme';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Kesintide';

  @override
  String get onNotificationTap => 'Bildirime Tıklama';

  @override
  String get onOpeningYoutubeLink => 'YouTube bağlantısı açıldığında';

  @override
  String get onSwiping => 'Kaydırmada';

  @override
  String get onVolumeZero => 'Ses 0 olduğunda';

  @override
  String get ongoing => 'Devam Ediyor';

  @override
  String get open => 'Aç';

  @override
  String get openApp => 'Uygulamayı Aç';

  @override
  String get openInFileExplorer => 'Dosya Gezgininde Aç';

  @override
  String get openInYoutubeView => 'YouTube görünümünde aç';

  @override
  String get openMiniplayer => 'Mini oynatıcıyı aç';

  @override
  String get openQueue => 'Sırayı Aç';

  @override
  String get openYoutubeLink => 'YouTube Bağlantısını Aç';

  @override
  String operationRequiresAccount({required String name}) {
    return '$name işlemi hesap gerektiriyor, devam etmek için oturum açın';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return '$operation işlemi en az $name üyelik gerektirir';
  }

  @override
  String get or => 'veya';

  @override
  String get others => 'Diğerleri';

  @override
  String get output => 'Çıktı';

  @override
  String get outro => 'Çıkış';

  @override
  String get overrideOldFilesInTheSameFolder => 'Aynı klasördeki eski dosyaların üzerine yaz';

  @override
  String get palette => 'Palet';

  @override
  String get paletteMix => 'Karışım';

  @override
  String get paletteNewMix => 'Yeni Karışım';

  @override
  String get paletteSelectedMix => 'Seçili Karışım';

  @override
  String get parallelDownloads => 'Paralel İndirmeler';

  @override
  String get parsed => 'analiz edildi';

  @override
  String get password => 'Şifre';

  @override
  String get path => 'Dosya Tam Yolu';

  @override
  String get pause => 'Duraklat';

  @override
  String get pauseFadeDuration => 'Duraklatma Geçiş Süresi';

  @override
  String get pausePlayback => 'Oynatmayı duraklat';

  @override
  String get percentage => 'Yüzde';

  @override
  String get performanceMode => 'Performans modu';

  @override
  String get performanceNote => 'Performansı etkileyebilir';

  @override
  String get personalized => 'Kişiselleştirilmiş';

  @override
  String get personalizedRelatedVideos => 'Kişiselleştirilmiş İlgili Videolar';

  @override
  String get personalizedRelatedVideosSubtitle => 'Bunu devre dışı bırakmak veri kullanımını artırır';

  @override
  String get pickColorsFromDeviceWallpaper => 'Cihaz Duvar Kağıdından Renkleri Seç';

  @override
  String get pickFromStorage => 'Depolamadan seç';

  @override
  String get pinned => 'Sabitlenmiş';

  @override
  String get pitch => 'Perde';

  @override
  String get plain => 'Düz';

  @override
  String get play => 'Oynat';

  @override
  String get playAfter => 'Sonra Oynat';

  @override
  String get playAfterNextPrev => 'Sonraki/Önceki Oynatma';

  @override
  String get playAll => 'Tümünü Oynat';

  @override
  String get playFadeDuration => 'Oynatma Geçiş Süresi';

  @override
  String get playLast => 'Sonuncuyu Oynat';

  @override
  String get playNext => 'Sonrakini Oynat';

  @override
  String get playbackSetting => 'Oynatma';

  @override
  String get playbackSettingSubtitle => 'Doğrudan oynatıcıda ses düğmesine uzun basarak erişilebilir';

  @override
  String get playlist => 'Çalma Listesi';

  @override
  String get playlists => 'Çalma Listeleri';

  @override
  String get playlistsImportM3uNative => 'Bu, M3U çalma listelerini yalnızca Namida tarafından kullanılmak üzere içe aktarır, geçiş yapıyorsanız kullanın';

  @override
  String get playlistsImportM3uSynced =>
      'Bu, dizin klasörlerinden M3U çalma listelerini otomatik olarak içe aktarır ve orijinal M3U dosyasıyla senkronize tutar. Çalma listelerine diğer uygulamalardan erişiyorsanız/düzenliyorsanız etkinleştirin';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'M3U Çalma Listelerini Otomatik İçe Aktar';

  @override
  String get pleaseEnterADifferentName => 'Bu isim zaten mevcut :(\nLütfen başka bir hoş isim deneyin';

  @override
  String get pleaseEnterALink => 'Lütfen bir bağlantı girin';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. bu bir YouTube bağlantısı mı?';

  @override
  String get pleaseEnterAName => 'Lütfen bir isim girin';

  @override
  String get port => 'Bağlantı noktası';

  @override
  String get preventDuplicatedTracks => 'Yinelenen parçaları önle';

  @override
  String get preventDuplicatedTracksSubtitle => 'Parçaları benzersiz bir şekilde tanımlamak için dosya adını kullanır';

  @override
  String get preview => 'Önizleme';

  @override
  String get previous => 'Önceki';

  @override
  String get previousButtonReplays => 'Önceki düğmesi tekrar çalar';

  @override
  String get previousButtonReplaysSubtitle => 'mevcut konum ileri sarma süresinden fazlaysa basıldığında';

  @override
  String get prioritizeEmbeddedLyrics => 'Gömülü sözlere öncelik ver';

  @override
  String get priority => 'Öncelik';

  @override
  String get private => 'Özel';

  @override
  String get progress => 'İlerleme';

  @override
  String get promptToChangeTrackPath => 'Genellikle bu, dosyayı Namida dışında sildiğiniz/taşıdığınız/yeni adlandırdığınız zaman olur, Mevcut yolu güncellemek ister misiniz?';

  @override
  String get public => 'Herkese Açık';

  @override
  String get queue => 'Kuyruk';

  @override
  String get queues => 'Kuyruklar';

  @override
  String get random => 'Rastgele';

  @override
  String get randomPicks => 'Rastgele Seçimler';

  @override
  String get rating => 'Derecelendirme';

  @override
  String get reIndex => 'Yeniden İndeksle';

  @override
  String get reIndexSubtitle => 'Müzik kütüphanenizi sıfırdan yeniden oluşturun';

  @override
  String get reIndexWarning => 'Bu işlem kütüphanenizin boyutuna bağlı olarak biraz zaman alabilir.\n\nGörseller var olduğu sürece yeniden indekslenmeyecek';

  @override
  String get recentAlbums => 'Son Albümler';

  @override
  String get recentArtists => 'Son Sanatçılar';

  @override
  String get recentListens => 'Son Dinlemeler';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Son Eklenenler';

  @override
  String get recordLabel => 'Plak Şirketi';

  @override
  String get refresh => 'Yenile';

  @override
  String get refreshLibrary => 'Kütüphaneyi Yenile';

  @override
  String get refreshLibrarySubtitle => 'Yeni eklenen veya silinen müzikleri kontrol et';

  @override
  String get refreshOnStartup => 'Başlangıçta yenile';

  @override
  String get relatedVideos => 'İlgili videolar';

  @override
  String get rememberAudioOnlyMode => 'Yalnızca ses modunu hatırla';

  @override
  String get remixer => 'Remiks Yapan';

  @override
  String get remove => 'Kaldır';

  @override
  String get removeDuplicates => 'Yinelenenleri Kaldır';

  @override
  String get removeFromFavourites => 'Favorilerden kaldır';

  @override
  String get removeFromLibrary => 'Kütüphaneden kaldır';

  @override
  String get removeFromPlaylist => 'Çalma Listesinden Kaldır';

  @override
  String get removeQueue => 'Kuyruğu Kaldır';

  @override
  String get removeSourceFromHistory => 'Kaynağı geçmişten kaldır';

  @override
  String get removeWhitespaces => 'Boşlukları Kaldır';

  @override
  String get removed => 'Kaldırıldı';

  @override
  String get rename => 'Yeniden Adlandır';

  @override
  String get renamePlaylist => 'Çalma Listesini Yeniden Adlandır';

  @override
  String get reorderable => 'Yeniden sıralanabilir';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number kez daha tekrarla',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Tekrar Modu';

  @override
  String get repeatModeAll => 'Tüm Kuyruğu Tekrarla';

  @override
  String get repeatModeNone => 'Son Parçada Durdur';

  @override
  String get repeatModeOne => 'Geçerli Parçayı Tekrarla';

  @override
  String get replaceAllListensWithAnotherTrack => 'Tüm dinlemeleri başka bir parçayla değiştir';

  @override
  String get replies => 'Yanıtlar';

  @override
  String get reply => 'Yanıtla';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Görsel önbelleğini temizlemeyi ve yeniden indekslemeyi gerektirir';

  @override
  String get rescanVideos => 'Videoları yeniden tara';

  @override
  String get resetBrightness => 'Parlaklığı sıfırla';

  @override
  String get resetToDefault => 'Varsayılana ayarla';

  @override
  String get respectNoMedia => '.nomedia\'ya saygı göster';

  @override
  String get respectNoMediaSubtitle => '.nomedia dosyası bulunan klasörleri dahil etme';

  @override
  String get restart => 'Yeniden başlat';

  @override
  String get restoreBackup => 'Yedeği Geri Yükle';

  @override
  String get restoreDefaults => 'Varsayılanları Geri Yükle';

  @override
  String get restoredBackupSuccessfully => 'Yedek Başarıyla Geri Yüklendi';

  @override
  String get restoredBackupSuccessfullySub => 'Yedek dosyası başarıyla geri yüklendi';

  @override
  String get resume => 'Devam Et';

  @override
  String get resumeIfWasInterrupted => 'Kesintiye uğradıysa devam et';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Ses nedeniyle duraklatıldıysa devam et';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString dakikadan az duraklatıldıysa devam et',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Beğenmemeleri Göster';

  @override
  String get reverseOrder => 'Sıralamayı Ters Çevir';

  @override
  String get rightAction => 'Sağ Eylem';

  @override
  String get ringtone => 'Zil Sesi';

  @override
  String get sameDirectoryOnly => 'Yalnızca aynı dizin';

  @override
  String get sample => 'Örnek';

  @override
  String get sampleRate => 'Örnekleme Hızı';

  @override
  String get save => 'Kaydet';

  @override
  String get saveToLibrary => 'Kütüphaneye Kaydet';

  @override
  String get savedIn => 'Kaydedildiği yer';

  @override
  String get scaleMultiplier => 'Ölçek Çarpanı';

  @override
  String get search => 'Ara';

  @override
  String get searchYoutube => 'YouTube\'da Ara';

  @override
  String get seconds => 'saniye';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Proje Kodunu $site de görün';
  }

  @override
  String get seekDuration => 'Kaydırma Süresi';

  @override
  String get seekDurationInfo => 'Geri almak için mevcut süreye, ileri almak için toplam süreye dokunabilirsiniz';

  @override
  String get seekbar => 'Kaydırma Çubuğu';

  @override
  String get selectAll => 'Tümünü Seç';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Yerel kütüphanede zaten mevcut olan dosyaları seç';

  @override
  String get selectedTracks => 'Seçilen Parçalar';

  @override
  String get selfPromotion => 'Kendi Reklamı';

  @override
  String get semitones => 'Yarım sesler';

  @override
  String get separatorsBlacklistSubtitle => 'Bu kelimeler ayrılmaz';

  @override
  String get separatorsMessage => 'Boşluk eklemenize gerek yok, yalnızca bir kelimenin içinde bulunabilecek bir harf/simge kullanmak istiyorsanız (ör. x ve ft.) kullanabilirsiniz';

  @override
  String get serverAddress => 'Sunucu Adresi';

  @override
  String get setAs => 'Olarak ayarla';

  @override
  String get setAsDefault => 'Varsayılan olarak ayarla';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Son düzenleme tarihini video yükleme tarihi olarak ayarla';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Modları ayarla';

  @override
  String get setMoodsSubtitle => 'Aralarına virgül (,) koyarak ayırın';

  @override
  String get setRating => 'Puan Ver';

  @override
  String get setTags => 'Etiketleri Ayarla';

  @override
  String get setYoutubeLink => 'YouTube Bağlantısını Ayarla';

  @override
  String get settings => 'Ayarlar';

  @override
  String get setupFirstStartup => 'İlk başlangıç ayarı';

  @override
  String get share => 'Paylaş';

  @override
  String get shareLogs => 'Logları Paylaş';

  @override
  String get shortcuts => 'Kısayollar';

  @override
  String get shouldDuck => 'Sesi kısmalı';

  @override
  String get shouldDuckNote => 'Ses seviyesinin düşürülmesi gerektiğini belirtir. Örn: bildirim';

  @override
  String get shouldPause => 'Duraklatmalı';

  @override
  String get shouldPauseNote => 'Oynatmanın duraklatılması gerektiğini belirtir. Örn: aramalar';

  @override
  String get showAll => 'Tümünü Göster';

  @override
  String get showChannelWatermarkInFullscreen => 'Tam ekranda kanal filigranını göster';

  @override
  String get showFailedOnly => 'Sadece Başarısızları Göster';

  @override
  String get showHideUnknownFields => 'Bilinmeyen Alanları Göster/Gizle';

  @override
  String get showInSeekbar => 'İlerleme Çubuğunda Göster';

  @override
  String get showMixPlaylistsIn => 'Karışık Çalma Listelerini Göster';

  @override
  String get showMore => 'Daha fazla göster';

  @override
  String get showShortVideosIn => 'Kısa Videoları Göster';

  @override
  String get showSkipButton => 'Atla Butonunu Göster';

  @override
  String get showVideoEndcards => 'Video Son Kartlarını Göster';

  @override
  String get showWebm => 'WebM Göster';

  @override
  String get shuffle => 'Karıştır';

  @override
  String get shuffleAll => 'Hepsini Karıştır';

  @override
  String get shuffleNext => 'Sonraki Karıştır';

  @override
  String get signIn => 'Giriş Yap';

  @override
  String get signInCanceled => 'Giriş iptal edildi';

  @override
  String get signInFailed => 'Giriş başarısız oldu';

  @override
  String get signInToYourAccount => 'Hesabınıza giriş yapın';

  @override
  String get signInYouDontHaveAccount => 'Hiçbir hesabınız giriş yapmış değil';

  @override
  String get signInYouNeedAccountToViewPage => 'Bu sayfayı görmek için bir hesaba ihtiyacınız var';

  @override
  String get signOut => 'Çıkış Yap';

  @override
  String signOutFromName({required String name}) {
    return '$name hesabından çıkış yap';
  }

  @override
  String get signingInAllowsBasicUsage => 'Oturum açmak temel kullanıma izin verir';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Patreon üzerinden erken erişim sağlayın veya kupon kullanın';

  @override
  String get similarDiscoverDate => 'Benzer Keşif Tarihi';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return '$currentTrack ile yakın tarihlerde keşfedilen parçaları oluştur';
  }

  @override
  String get similarTimeRange => 'Benzer Zaman Aralığı';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return '$currentTrack ile yakın zamanlarda dinlediğin parçaları oluştur';
  }

  @override
  String get singles => 'Tekliler';

  @override
  String get size => 'Boyut';

  @override
  String get skip => 'Atla';

  @override
  String get skipCountTracking => 'Atlama Sayısını Takip Et';

  @override
  String get skipSilence => 'Sessizliği Atla';

  @override
  String get skipSponsorSegmentsInVideos => 'Sponsorlu bölümleri atla';

  @override
  String get sleepAfter => 'Şu kadar sonra uykuya geç';

  @override
  String get sleepTimer => 'Uyku Zamanlayıcısı';

  @override
  String get socials => 'Bağlantılar';

  @override
  String get socialsSubtitle => 'Güncellemeler, İpuçları ve Tartışmalar için topluluğumuza katılın';

  @override
  String get someWebServersRequireAuthentication => 'Bazı sunucular kimlik doğrulama gerektiriyor. Erişimi sürdürmek için bilgileri güncelleyin.';

  @override
  String get sortBy => 'Şuna göre sırala';

  @override
  String get source => 'Kaynak';

  @override
  String get speed => 'Hız';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'Sponsor Engeli';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Sıralaması';

  @override
  String get staggeredAlbumGridView => 'Dağınık Albüm Izgara Görünümü';

  @override
  String get start => 'Başlat';

  @override
  String get stats => 'İstatistikler';

  @override
  String get statsSubtitle => 'Kütüphanenizle ilgili bazı bilgiler burada';

  @override
  String get stop => 'Durdur';

  @override
  String get stopAfterThisTrack => 'Bu Parçadan Sonra Durdur';

  @override
  String get stopAfterThisVideo => 'Bu Videodan Sonra Durdur';

  @override
  String get storagePermissionDenied => 'İzin Reddedildi';

  @override
  String get storagePermissionDeniedSubtitle => 'Bu işlemi gerçekleştirmek için lütfen erişim izni verin';

  @override
  String get stretchLyricsDuration => 'Şarkı Sözü Süresini Genişlet';

  @override
  String get subdirectory => 'Alt dizin';

  @override
  String get subscribe => 'Abone Ol';

  @override
  String get subscribed => 'Abone Olundu';

  @override
  String get subscriber => 'Abone';

  @override
  String get subscribers => 'Aboneler';

  @override
  String get succeeded => 'Başarılı';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Sorunun veya Önerin mi var? $site de bir sorun bildirin';
  }

  @override
  String get support => 'Destek';

  @override
  String get supremacy => 'Üstünlük';

  @override
  String get sussyBaka => 'Bruh, parça yok';

  @override
  String get swipeActions => 'Kaydırma Hareketleri';

  @override
  String get swipeToOpenDrawer => 'Çekmeceyi açmak için kaydırın';

  @override
  String get synced => 'Eşitlendi';

  @override
  String get synopsis => 'Özet';

  @override
  String get tagFields => 'Etiket Alanları';

  @override
  String get tags => 'Etiketler';

  @override
  String get tapAction => 'Dokunma Eylemi';

  @override
  String get tapToSeek => 'Gitmek için dokunun';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Tema Modu';

  @override
  String get themeModeDark => 'Karanlık';

  @override
  String get themeModeLight => 'Aydınlık';

  @override
  String get themeModeSystem => 'Sistem';

  @override
  String get themeSettings => 'Tema Ayarları';

  @override
  String get themeSettingsSubtitle => 'Oynatıcınızın genel havası';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Bu çalma listesinde aktif sıralayıcılar var, yeniden sıralamadan önce devre dışı bırakın.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Bu video muhtemelen silinmiş veya özel olarak ayarlanmış.';

  @override
  String get thumbnails => 'Küçük Resimler';

  @override
  String get title => 'Başlık';

  @override
  String get top => 'En Üst';

  @override
  String get topComments => 'En İyi Yorumlar';

  @override
  String get topCommentsSubtitle => 'Yorumları altta yerine üstte göster';

  @override
  String get topRecentAlbums => 'En Son Albümler';

  @override
  String get topRecentArtists => 'En Son Sanatçılar';

  @override
  String get topRecents => 'En Sonlar';

  @override
  String get totalListenTime => 'Toplam Dinleme Süresi';

  @override
  String get totalListens => 'Toplam Dinlenme';

  @override
  String get totalTracks => 'Toplam Parçalar';

  @override
  String get totalTracksDuration => 'Toplam Parça Süresi';

  @override
  String get track => 'Parça';

  @override
  String get trackArtistsSeparator => 'Sanatçı Ayırıcıları';

  @override
  String get trackGenresSeparator => 'Tür Ayırıcıları';

  @override
  String get trackInfo => 'Parça Bilgisi';

  @override
  String get trackNotFound => 'Parça bulunamadı';

  @override
  String get trackNumber => 'Parça Numarası';

  @override
  String get trackNumberTotal => 'Toplam Parça';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Eski adı: \"$oldName\"\n\nYeni adı: \"$newName\"\n\nEmin misiniz?';
  }

  @override
  String get trackPlayMode => 'Oynatma Modu';

  @override
  String get trackPlayModeSearchResults => 'Arama Sonuçları';

  @override
  String get trackPlayModeSelectedOnly => 'Sadece seçilen parça';

  @override
  String get trackPlayModeTrackAlbum => 'Parçanın Albümü';

  @override
  String get trackPlayModeTrackArtist => 'Parçanın Ana Sanatçısı';

  @override
  String get trackPlayModeTrackGenre => 'Parçanın Türü';

  @override
  String get trackThumbnailSizeInList => 'Parça Küçük Resim Boyutu';

  @override
  String get trackTileCustomization => 'Parça Karo Özelleştirme';

  @override
  String get trackTileItemsSeparator => 'Öğeler Ayırıcı';

  @override
  String get tracks => 'Parçalar';

  @override
  String get tracksExcludedByNomedia => '.nomedia ile Hariç Tutulan Parçalar';

  @override
  String get tracksInfo => 'Parçalar Bilgisi';

  @override
  String get underrated => 'Bilinmeyen Cevherler';

  @override
  String get undo => 'Geri Al';

  @override
  String get undoChanges => 'Değişiklikleri Geri Al?';

  @override
  String get undoChangesDeletedPlaylist => 'Silinen çalma listesini geri al';

  @override
  String get undoChangesDeletedQueue => 'Silinen sırayı geri al';

  @override
  String get undoChangesDeletedTrack => 'Silinen parçayı geri al';

  @override
  String get uniqueArtworkHash => 'Benzersiz kapak resmi kodu';

  @override
  String get unlimited => 'Sınırsız';

  @override
  String get unlisted => 'Liste Dışı';

  @override
  String get unlock => 'Kilidi Aç';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Güncelle';

  @override
  String get updateDirectoryPath => 'Dizin yolunu güncelle';

  @override
  String get updateMissingTracksOnly => 'Sadece eksik parçaları güncelle';

  @override
  String get updating => 'Güncelleniyor';

  @override
  String get useCollapsedSettingTiles => 'Daraltılmış Ayar Karolarını Kullan';

  @override
  String get useMediaStore => 'Ortam Deposu Kullan';

  @override
  String get useMediaStoreSubtitle =>
      '✓ anında indeksleme süresi\nx .nomedia zorunlu olarak etkin olacak\nx bazı meta veri etiketleri eksik olacak\nx yerel kütüphane için YouTube entegrasyonu çalışmayacak';

  @override
  String get usePitchBlack => 'Siyah Arka Plan Kullan';

  @override
  String get usePitchBlackSubtitle => 'AMOLED ekranlar için faydalı... ve daha havalı görünüyor';

  @override
  String get used => 'Kullanılan';

  @override
  String get value => 'Değer';

  @override
  String get valueBetween50200 => 'Değer %50 ile %200 arasında olmalı';

  @override
  String get vibration => 'Titreşim';

  @override
  String get vibrationType => 'Titreşim türü';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Video Önbelleği';

  @override
  String get videoCacheFile => 'Önbelleğe Alınmış Video Dosyası';

  @override
  String get videoCacheFiles => 'Önbelleğe Alınmış Video Dosyaları';

  @override
  String get videoOnly => 'Sadece Video';

  @override
  String get videoPlaybackSource => 'Video Kaynağı';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Bu öncelikle yerel videolara öncelik verir, bulunamazsa youtubedan alır';

  @override
  String get videoPlaybackSourceLocal => 'Yerel Videolar';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Örnek Ses: Alan Walker - Faded.m4a\nÖrnek Video: Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle =>
      'Herhangi bir video dosyasının (seçilen klasörler listesinde bulunan) parçanın dosya adını içeren bir dosya adına sahip olup olmadığını kontrol eder';

  @override
  String get videoPlaybackSourceYoutube => 'YouTube\'dan';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Parçanın dosya adı ve yorumlarında eşleşen bir YouTube bağlantısı olup olmadığını kontrol eder, videolar daha sonra kullanılmak üzere önbelleğe alınır.';

  @override
  String get videoQuality => 'Video Kalitesi';

  @override
  String get videoQualitySubtitle => 'Mevcut olan en yüksek kalite seçilecektir.';

  @override
  String get videoQualitySubtitleNote => 'Bir kalite bulunamazsa en kötü kaliteye geçiş yapacağı için daha fazla alternatif bulundurmak her zaman iyidir';

  @override
  String get videos => 'Videolar';

  @override
  String get view => 'Görüntüle';

  @override
  String get viewAll => 'Hepsini Gör';

  @override
  String get views => 'Görüntüleme';

  @override
  String get volume => 'Ses';

  @override
  String get warning => 'Uyarı';

  @override
  String get waveformBarsCount => 'Dalga Çubuğu Sayısı';

  @override
  String get webmNoEditTagsSupport => 'WEBM formatı etiket düzenlemeyi desteklemez';

  @override
  String get week => 'Hafta';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Yıl';

  @override
  String get yes => 'Evet';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Mevcut üyeliğiniz $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Özel sıranız kaybolacak, emin misiniz?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Müzik';

  @override
  String get youtubeSettingsSubtitle => 'YouTube deneyiminizi özelleştirin';

  @override
  String get youtubeStyleMiniplayer => 'YouTube Tarzı Mini Oynatıcı';

  @override
  String get ytPreferNewComments => 'Mümkün olduğunda yeni yorumları tercih et';

  @override
  String get ytPreferNewCommentsSubtitle => 'Bağlantı yoksa yalnızca önbelleğe alınmış sürüm kullanılacak';
}
