// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Italian (`it`).
class AppLocalizationsIt extends AppLocalizations {
  AppLocalizationsIt([String locale = 'it']) : super(locale);

  @override
  String get about => 'Riguardo';

  @override
  String get active => 'Attivo';

  @override
  String get add => 'Aggiungi';

  @override
  String get addAccount => 'Aggiungi account';

  @override
  String get addAll => 'Aggiungi tutto';

  @override
  String get addAllAndRemoveOldOnes => 'Aggiungi tutto e rimuovi i vecchi';

  @override
  String get addAsANewPlaylist => 'Aggiungi come nuova playlist';

  @override
  String get addAudioToLocalLibrary => 'Aggiungi audio alla libreria locale';

  @override
  String get addFolder => 'Aggiungi cartella';

  @override
  String get addLanguage => 'Aggiungi lingua';

  @override
  String get addLanguageSubtitle => 'Aiutaci a tradurre Namida nella tua lingua';

  @override
  String get addLrcFile => 'Aggiungi file LRC';

  @override
  String get addMoreFromThisAlbum => 'Aggiungi altro da questo album in coda';

  @override
  String get addMoreFromThisArtist => 'Aggiungi altro da questo artista in coda';

  @override
  String get addMoreFromThisFolder => 'Aggiungi altro da questa cartella in coda';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Aggiungi altro da $media in coda';
  }

  @override
  String get addOnlyMissing => 'Aggiungi solo mancanti';

  @override
  String get addToFavourites => 'Aggiungi ai preferiti';

  @override
  String get addToPlaylist => 'Aggiungi alla playlist';

  @override
  String get addTracksAtTheBeginning => 'Aggiungi tracce all\'inizio';

  @override
  String get added => 'aggiunto';

  @override
  String get advanced => 'Avanzate';

  @override
  String get advancedSettings => 'Avanzate';

  @override
  String get advancedSettingsSubtitle => 'Impostazioni avanzate, non toccare';

  @override
  String get alarm => 'Allarme';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Artista dell\'album';

  @override
  String get albumArtists => 'Artisti dell\'album';

  @override
  String get albumIdentifiers => 'Identificatori dell\'album';

  @override
  String get albumThumbnailSizeInList => 'Dimensione della copertina dell\'album';

  @override
  String get albumTileCustomization => 'Personalizzazione riquadro album';

  @override
  String get albums => 'Album';

  @override
  String get albumsCount => 'Numero di album';

  @override
  String get all => 'Tutti';

  @override
  String get allTime => 'Tutto il tempo';

  @override
  String get alreadyExists => 'Esiste già';

  @override
  String get always => 'Sempre';

  @override
  String get alwaysAsk => 'Chiedi sempre';

  @override
  String get alwaysDim => 'Riduci sempre';

  @override
  String get alwaysExpandedSearchbar => 'Searchbar Sempre Espanso';

  @override
  String get alwaysRestore => 'Ripristina sempre';

  @override
  String get animatingThumbnailIntensity => 'Intensità animazione copertina';

  @override
  String get animatingThumbnailInversed => 'Inverti animazioni';

  @override
  String get animatingThumbnailInversedSubtitle => 'I picchi alti ridurranno le dimensioni della copertina';

  @override
  String get anotherProcessIsRunning => 'Un altro processo è già in esecuzione.';

  @override
  String get appIcon => 'Icona App';

  @override
  String get appVersion => 'Versione dell\'app';

  @override
  String get artist => 'Artista';

  @override
  String get artists => 'Artisti';

  @override
  String get artwork => 'Copertina';

  @override
  String get artworkGestures => 'Gesti Artistici';

  @override
  String get artworks => 'Copertine';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Cache audio';

  @override
  String get audioOnly => 'Solo audio';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Intervallo Backup Automatico';

  @override
  String get autoColoring => 'Colorazione automatica';

  @override
  String get autoColoringSubtitle => 'Scegli automaticamente i colori del player dalla copertina corrente';

  @override
  String get autoExtractTagsFromFilename => 'Estrai automaticamente dal nome file';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Estrai automaticamente titolo e artista dal titolo del video';

  @override
  String get autoGenerated => 'Generato automaticamente';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Avvio automatico radio';

  @override
  String get autoStartRadioSubtitle => 'Aggiungi automaticamente un playlist mix quando ascolti un singolo brano';

  @override
  String get automaticBackup => 'Automatico';

  @override
  String get automaticBackupSubtitle => 'Applica automaticamente il file di backup più recente trovato all\'interno della posizione di backup';

  @override
  String get backupAndRestore => 'Backup e ripristino';

  @override
  String get backupAndRestoreSubtitle => 'Esegui il backup del tuo database e delle impostazioni';

  @override
  String get balanced => 'Bilanciato';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Tra date';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Lista nera';

  @override
  String get borderRadiusMultiplier => 'Moltiplicatore raggio bordo';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Cancella';

  @override
  String get canceled => 'Annullato';

  @override
  String get changed => 'Modificato';

  @override
  String get changelog => 'Registro modifiche';

  @override
  String get changelogSubtitle => 'Guarda cosa è stato aggiunto/fixato dentro Namida';

  @override
  String get channel => 'Canale';

  @override
  String get channels => 'Canali';

  @override
  String get check => 'Controlla';

  @override
  String get checkForMore => 'Controlla altri';

  @override
  String get checkList => 'Checklist';

  @override
  String get choose => 'Scegli';

  @override
  String get chooseWhatToClear => 'Scegli cosa cancellare';

  @override
  String get claim => 'Richiesta';

  @override
  String get clear => 'Cancella';

  @override
  String get clearAudioCache => 'Cancella cache audio';

  @override
  String get clearImageCache => 'Cancella cache immagini';

  @override
  String get clearImageCacheWarning => 'Attenzione: risulterà in una libreria senza immagini, da usare solo per ricostruire la cache immagini.';

  @override
  String get clearTrackItem => 'Cancella elementi traccia';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Cancella elementi $numberString tracce',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Cancella cache video';

  @override
  String get clearVideoCacheNote => 'Puoi scegliere cosa eliminare.';

  @override
  String get clock => 'Orologio';

  @override
  String get colorPalette => 'Palette Colori';

  @override
  String get colorPaletteNote1 => 'Tieni premuto a lungo su un colore per rimuoverlo';

  @override
  String get colorPaletteNote2 => 'Tocca su una combinazione per usarla come colore predefinito';

  @override
  String get colorPalettes => 'Palette dei colori';

  @override
  String get comment => 'Commento';

  @override
  String get comments => 'Commenti';

  @override
  String get composer => 'Compositore';

  @override
  String get compress => 'Comprimi';

  @override
  String get compressImages => 'Comprimi immagini';

  @override
  String get compressionPercentage => 'Percentuale di compressione';

  @override
  String get configure => 'Configura';

  @override
  String get confirm => 'Conferma';

  @override
  String get confirmRefresh => 'Confermi il ricaricamento?';

  @override
  String get copiedArtwork => 'Copertina copiata';

  @override
  String get copiedToClipboard => 'Copiato negli appunti';

  @override
  String get copy => 'Copia';

  @override
  String get corruptedFile => 'File danneggiato, potrebbe essere corrotto';

  @override
  String get couldntOpen => 'Impossibile aprire :(';

  @override
  String get couldntOpenYtLink => 'Nessun link Youtube disponibile per questa traccia';

  @override
  String get couldntPlayFile => 'Impossibile riprodurre il file';

  @override
  String get couldntRenamePlaylist => 'Impossibile rinominare la playlist';

  @override
  String get couldntSaveImage => 'Impossibile salvare l\'immagine';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Paese';

  @override
  String get coupon => 'Buono';

  @override
  String get create => 'Crea';

  @override
  String get createBackup => 'Crea backup';

  @override
  String get createNewPlaylist => 'Crea nuova playlist';

  @override
  String get createdBackupSuccessfully => 'Backup creato';

  @override
  String get createdBackupSuccessfullySub => 'Il file di backup è stato creato con successo';

  @override
  String get crossPlatformSync => 'Sincronizzazione Cross-Platform';

  @override
  String get crossfadeDuration => 'Durata dissolvenza';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Attiva dissolvenza incrociata automaticamente negli ultimi $secondsString secondi',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Non attivare dissolvenza incrociata automaticamente';

  @override
  String get custom => 'Personalizza';

  @override
  String get customizations => 'Personalizzazioni';

  @override
  String get customizationsSubtitle => 'Personalizza l\'aspetto del tuo player, rendilo tuo';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Salvatore di dati';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'Database';

  @override
  String get date => 'Data';

  @override
  String get dateAdded => 'Data di aggiunta';

  @override
  String get dateCreated => 'Data di creazione';

  @override
  String get dateModified => 'Data di modifica';

  @override
  String get dateTimeFormat => 'Formato data e ora';

  @override
  String get day => 'Giorno';

  @override
  String get days => 'Giorni';

  @override
  String get defaultBackupLocation => 'Posizione predefinita backup';

  @override
  String get defaultColor => 'Colore predefinito';

  @override
  String get defaultColorSubtitle => 'Imposta un colore da usare nel player';

  @override
  String get defaultDownloadLocation => 'Posizione predefinita download';

  @override
  String get defaultLabel => 'Predefinito';

  @override
  String get defaultLibraryTab => 'Scheda libreria predefinita';

  @override
  String get delete => 'Elimina';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Delete $countString file representing $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Cancella in modo permanente $numberText dalla tua archiviazione';
  }

  @override
  String get deletePlaylist => 'Elimina playlist';

  @override
  String get deleteTempFiles => 'Cancella file temporanei';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Descrizione';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Intendevi dire';

  @override
  String get dimIntensity => 'Intensità oscuramento';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Oscura miniplayer dopo $secondsString secondi di inattività',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'La cartella non esiste';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Disattiva tutto';

  @override
  String get disableReordering => 'Disabilita riordinamento';

  @override
  String get disableSearchCleanup => 'Disabilita pulizia ricerca';

  @override
  String get discNumber => 'Numero disco';

  @override
  String get discNumberTotal => 'Numero totale dischi';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Non mi piace';

  @override
  String get dismissibleMiniplayer => 'Miniplayer eliminabile';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Data in alto a destra scheda album';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Visualizza la data dell\'album in alto a destra nella scheda dell\'album';

  @override
  String get displayArtistBeforeTitle => 'Visualizza artista prima del titolo';

  @override
  String get displayArtworkOnLockscreen => 'Mostra artwork nella schermata di blocco';

  @override
  String get displayAudioInfoInMiniplayer => 'Visualizza informazioni audio';

  @override
  String get displayFavButtonInNotification => 'Visualizza pulsante Preferiti nella notifica';

  @override
  String get displayFavButtonInNotificationSubtitle => 'La copertina potrebbe essere spostata.';

  @override
  String get displayFavouriteIconInTrackTile => 'Visualizza pulsante Preferiti';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Visualizza durata rimanente invece del totale';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Visualizza terzo elemento in ogni riga';

  @override
  String get displayThirdRowInTrackTile => 'Visualizza terza riga';

  @override
  String get displayTrackNumberInAlbumPage => 'Visualizza numero traccia nella pagina dell\'album';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Visualizza un piccolo riquadro contenente il numero della traccia nella pagina dell\'album';

  @override
  String get doNothing => 'Non fare nulla';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Fatto';

  @override
  String get dontAskAgain => 'Non chiedere di nuovo';

  @override
  String get dontDim => 'Non diminuire';

  @override
  String get dontRestorePosition => 'Non ripristinare';

  @override
  String get dontResume => 'Non riprendere';

  @override
  String get doubleTapToToggleLyrics => 'Doppio tocco per attivare/disattivare testo';

  @override
  String get download => 'Scarica';

  @override
  String get downloadingWillOverrideIt => 'Il download sovrascriverà';

  @override
  String get downloads => 'Downloads';

  @override
  String get downloadsMetadataTags => 'Scarica tag metadati';

  @override
  String get downloadsMetadataTagsSubtitle => 'Estrai artista, titolo e album dalle informazioni video di default';

  @override
  String get dragToSeek => 'Trascina per cercare';

  @override
  String get duckAudio => 'Abbassa audio';

  @override
  String get duplicatedItemsAdding => 'Stai aggiungendo brani esistenti in questa playlist';

  @override
  String get duplicatedTracks => 'Tracce duplicate';

  @override
  String get duration => 'Durata';

  @override
  String get edgeColorsSwitching => 'Transizione colori bordo';

  @override
  String get edit => 'Modifica';

  @override
  String get editArtwork => 'Modifica copertina';

  @override
  String get editTags => 'Modifica tag';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'hai campi con valori vuoti/non significativi, assicurati di modificare';

  @override
  String get emptyValue => 'Valore vuoto';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Abilita effetto sfocatura';

  @override
  String get enableBottomNavBar => 'Abilita barra di navigazione inferiore';

  @override
  String get enableBottomNavBarSubtitle => 'Gli elementi sono all\'interno del cassetto';

  @override
  String get enableClipboardMonitoring => 'Attiva Controllo Appunti';

  @override
  String get enableClipboardMonitoringSubtitle => 'Consenti di incollare link e testo nella barra di ricerca';

  @override
  String get enableCrossfadeEffect => 'Abilita effetto dissolvenza incrociata';

  @override
  String get enableFadeEffectOnPlayPause => 'Abilita effetto dissolvenza su Ripendi/Pausa';

  @override
  String get enableFoldersHierarchy => 'Abilita gerarchia cartelle';

  @override
  String get enableGlowEffect => 'Abilita effetto brillantezza';

  @override
  String get enableM3uSync => 'Abilita sincronizzazione M3U';

  @override
  String get enableM3uSyncNote1 => 'La sincronizzazione M3U permette di salvare le modifiche alla playlist nel file M3U originale';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Se qualcosa andasse storto, un backup di questa playlist si troverà in $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Se negato, tutte le modifiche fatte in questa playlist andranno perse al riavvio';

  @override
  String get enableMiniplayerParticles => 'Abilita particelle in movimento';

  @override
  String get enableParallaxEffect => 'Abilita effetto parallasse';

  @override
  String get enablePartyMode => 'Abilita modalità festa';

  @override
  String get enablePartyModeSubtitle => 'Applica un efffetto di respirazione colori sui bordi';

  @override
  String get enablePictureInPicture => 'Abilita Picture-in-Picture';

  @override
  String get enableReordering => 'Abilita riordinamento';

  @override
  String get enableReturnYoutubeDislike => 'Riabilita i Dislike di Youtube';

  @override
  String get enableSearchCleanup => 'Abilita pulizia ricerca';

  @override
  String get enableSearchCleanupSubtitle => 'Tutti i simboli e gli spazi verranno ignorati';

  @override
  String get enableSponsorblock => 'Abilita SponsorBlock';

  @override
  String get enableVideoPlayback => 'Abilita riproduzione video';

  @override
  String get enterSymbol => 'Inserisci simbolo';

  @override
  String get equalizer => 'Equalizzatore';

  @override
  String get error => 'Errore';

  @override
  String get errorFetchingVideoList => 'Errore nel recuperare la lista video';

  @override
  String get errorPlayingTrack => 'Errore nella riproduzione della traccia';

  @override
  String get excludedFodlers => 'Cartelle escluse';

  @override
  String get exit => 'Esci';

  @override
  String get exitAppSubtitle => 'Tocca di nuovo per uscire';

  @override
  String get expandedMiniplayer => 'Espandi Miniplayer';

  @override
  String get exportAsM3u => 'Esporta come M3U';

  @override
  String get extension => 'Estensione';

  @override
  String get externalFiles => 'File esterni';

  @override
  String get extract => 'Estrai';

  @override
  String get extractAllColorPalettes => 'Estrai tutte le palette colori';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Estrai rimanenti $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Estrai artisti feat. dal titolo';

  @override
  String get extractFeatArtistSubtitle => 'Estrae artisti (feat. X) e (ft. X), come nuova voce artista.';

  @override
  String get extractingInfo => 'Estrazione informazioni';

  @override
  String get extras => 'Extra';

  @override
  String get extrasSubtitle => 'Impostazioni extra per migliorare l\'esperienza';

  @override
  String get extreme => 'Estremo';

  @override
  String get failed => 'Fallito';

  @override
  String get failedEdits => 'Modifiche fallite';

  @override
  String get favourites => 'Preferiti';

  @override
  String get features => 'Funzionalità';

  @override
  String get fetching => 'Caricamento';

  @override
  String get fetchingOfAllVideos => 'Caricamento dei video';

  @override
  String get file => 'File';

  @override
  String get fileAlreadyExists => 'Il file esiste già';

  @override
  String get fileBasedServerWarning =>
      'I file verranno temporaneamente scaricati per l\'indicizzazione. Assicurati che la connessione sia stabile.\nLa Wi-Fi è raccomandata per evitare un alto consumo di dati.';

  @override
  String get fileName => 'Nome file';

  @override
  String get fileNameWoExt => 'Nome file senza estensione';

  @override
  String get filenameShouldntStartWith => 'Il nome del file non deve iniziare per';

  @override
  String get files => 'File';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Filtra album';

  @override
  String get filterArtists => 'Filtra artisti';

  @override
  String get filterGenres => 'Filtra generi';

  @override
  String get filterPlaylists => 'Filtra playlist';

  @override
  String get filterTracks => 'Filtra tracce';

  @override
  String get filterTracksBy => 'Filtra tracce nelle liste di ricerca per';

  @override
  String get filtered => 'Filtrato';

  @override
  String get filteredBySizeAndDuration => 'Tracce filtrate per dimensione e durata';

  @override
  String get finished => 'Finito';

  @override
  String get finishedUpdatingLibrary => 'Aggiornamento libreria completato';

  @override
  String get firstListen => 'Primo ascolto';

  @override
  String get fixYtdlpBigThumbnailSize => 'Correggi dimensione copertina grande yt-dlp';

  @override
  String get floatingActionButton => 'Action Button Fluttuante';

  @override
  String get folder => 'Cartella';

  @override
  String get folderName => 'Nome cartella';

  @override
  String get folders => 'Cartelle';

  @override
  String get fontScale => 'Scala carattere';

  @override
  String get forceMiniplayerFollowTrackColors => 'Forza miniplayer a seguire i colori della traccia';

  @override
  String get forceSquaredAlbumThumbnail => 'Forza copertina album quadrata';

  @override
  String get forceSquaredThumbnailNote =>
      'Le dimensioni della copertina e l\'altezza del riquadro NON sono uguali, l\'aspetto quadrato non sarà come previsto, vuoi renderli uguali?';

  @override
  String get forceSquaredTrackThumbnail => 'Forza copertina traccia quadrata';

  @override
  String get forceStopColorPaletteGeneration => 'Arresta l\'estrazione dellapalette dei colori? Puoi continuare dopo';

  @override
  String get format => 'Formato';

  @override
  String get fullscreen => 'Schermo Intero';

  @override
  String get gaplessPlayback => 'Riproduzione senza interruzioni';

  @override
  String get generate => 'Genera';

  @override
  String get generateFromDates => 'Intervallo temporale';

  @override
  String get generateFromDatesSubtitle => 'Genera le tracce che hai ascoltato in un intervallo temporale';

  @override
  String get generateRandomPlaylist => 'Genera Playlist casuale';

  @override
  String get genre => 'Genere';

  @override
  String get genres => 'Generi';

  @override
  String get goToAlbum => 'Vai all\'album';

  @override
  String get goToArtist => 'Vai all\'artista';

  @override
  String get goToChannel => 'Vai al canale';

  @override
  String get goToFolder => 'Vai alla cartella';

  @override
  String get goodLooking => 'Bello';

  @override
  String get grantStoragePermission => 'Concedi permesso di archiviazione';

  @override
  String get group => 'Gruppo';

  @override
  String get groupArtworksByAlbum => 'Raggruppa copertine per album';

  @override
  String get guide => 'Guida';

  @override
  String get hapticFeedback => 'Feedback Aptico';

  @override
  String get heightOfAlbumTile => 'Altezza riquadro album';

  @override
  String get heightOfTrackTile => 'Altezza riquadro traccia';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Corrispondenze alte';

  @override
  String get highPerformance => 'Prestazioni elevate';

  @override
  String get highlight => 'Evidenziona';

  @override
  String get history => 'Cronologia';

  @override
  String get historyImportMissingEntriesNote => 'Queste voci non sono state trovate nella libreria, se pensi che esistano, considera di aggiungerle manualmente';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: 'Sostituire $listensCountString ascolti di $oldTrackInfo con $newTrackInfo, confermare?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Home';

  @override
  String get hook => 'Aggancia';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'Formato 12 ore';

  @override
  String get hours => 'Ore';

  @override
  String get iReadAndAgree => 'Ho letto e accetto';

  @override
  String get ifNotPlaying => 'Se non in riproduzione';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'I download possono essere limitati quando l\'app è in risparmio batteria';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignora prefissi comuni mentre ordini';

  @override
  String get ignores => 'Ignora';

  @override
  String get imageSource => 'Fonte Immagine';

  @override
  String get immersiveMode => 'Modalità a schermo intero';

  @override
  String get immersiveModeSubtitle => 'Nasconde barre di stato e di navigazione quando il miniplayer è espanso';

  @override
  String get import => 'Import';

  @override
  String get importAll => 'Importa tutto';

  @override
  String get importLastFmHistory => 'Importa cronologia LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Vai a $lastfmCsvLink\n\n2. Inserisci il tuo username, recupera e scarica il file csv.\n\n3. Scegli il file nella prossima schermata.';
  }

  @override
  String get importTimeRange => 'Importa intervallo temporale';

  @override
  String get importYoutubeHistory => 'Importa cronologia Youtube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Vai a $takeoutLink\n\n2. Premi \"Multiple Formats\" e accanto a \"History\" scegli \"JSON\".\n\n3. Premi \"All Youtube data included\", deseleziona Tutto e scegli solo la cronologia.\n\n4. Crea esportazione, scarica e decomprimi.\n\n5. Scegli \"watch-history.json\" dalla prossima schermata.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Importo $numberString canali correttamente',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Imported $numberText playlists successfully',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Includi video';

  @override
  String get indexRefreshRequired => 'Esegui un aggiornamento dopo aver cambiato questa impostazione';

  @override
  String get indexer => 'Indicizzatore';

  @override
  String get indexerNote => 'Nota: Artworks incomplete si riferisce alle copertine duplicate e non trovate';

  @override
  String get indexerSubtitle => 'Gestisci la tua libreria musicale';

  @override
  String get infinityQueueOnNextPrev => 'Coda infinita su Successivo/Precedente';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'premere successivo mentre si riproduce l\'ultimo elemento salterà al primo, e viceversa';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'inserito';

  @override
  String get instantlyApplies => 'Applica istantaneamente';

  @override
  String get interactionReminder => 'Promemoria di interazione';

  @override
  String get intro => 'Introduzione';

  @override
  String get invertSelection => 'Inverti Selezione';

  @override
  String get issues => 'Problemi';

  @override
  String get item => 'Elemento';

  @override
  String get jump => 'Salta';

  @override
  String get jumpToDay => 'Salta al giorno';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Salta alla prima traccia dopo aver finito la coda';

  @override
  String get keepCachedVersions => 'Mantieni versioni in cache';

  @override
  String get keepFileDates => 'Mantieni date file';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Il miniplayer è espanso';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Il miniplayer è espanso e un video è in riproduzione';

  @override
  String get keepScreenAwakeNone => 'Non mantenere lo schermo acceso';

  @override
  String get keepScreenAwakeWhen => 'Mantieni schermo acceso quando';

  @override
  String get killPlayerAfterDismissingApp => 'Termina player dopo aver chiuso l\'app';

  @override
  String get language => 'Lingua';

  @override
  String get learnMore => 'Scopri di più';

  @override
  String get leftAction => 'Azione sinistra';

  @override
  String get legacyAuthentication => 'Autenticazione Legacy';

  @override
  String get libraryTabs => 'Schede libreria';

  @override
  String get libraryTabsReorder => 'Puoi riordinare le schede attivate.';

  @override
  String get license => 'Licenza';

  @override
  String get licenseSubtitle => 'Licenze ed Accordi usati da Namida';

  @override
  String get like => 'Mi piace';

  @override
  String get liked => 'Piaciuti';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Elenco cartelle';

  @override
  String get loadAll => 'Carica tutto';

  @override
  String get loadingFile => 'Caricamento file';

  @override
  String get local => 'Locale';

  @override
  String get localVideoMatching => 'Corrispondenza video locale';

  @override
  String get login => 'Accesso';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Tieni premuto testo per schermo intero';

  @override
  String get lostMemories => 'Ricordi perduti';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'circa questo periodo, $numberString anni fa',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Partner persi';

  @override
  String get loudnessEnhancer => 'Amplificatore Volume';

  @override
  String get lyricist => 'Paroliere';

  @override
  String get lyrics => 'Testo';

  @override
  String get lyricsSource => 'Fonti testo';

  @override
  String get m3uPlaylist => 'Playlist M3U';

  @override
  String get makeYourFirstListen => 'Fai il tuo primo ascolto!';

  @override
  String get manage => 'Gestisci';

  @override
  String get manageYourAccounts => 'Gestisci i tuoi account';

  @override
  String get manualBackup => 'Manuale';

  @override
  String get manualBackupSubtitle => 'scegli un file specifico';

  @override
  String get markAsRead => 'Segna come letto';

  @override
  String get matchAllTracks => 'Corrispondenza per tutte le tracce';

  @override
  String get matchAllTracksNote => 'questo può avere un impatto sulla velocità di corrispondenza, poiché controllerà tutte le tracce nella tua libreria';

  @override
  String get matchingType => 'Tipo di corrispondenza';

  @override
  String get maxAudioCacheSize => 'Cache audio massimo';

  @override
  String get maxImageCacheSize => 'Dimensione massima cache immagini';

  @override
  String get maxVideoCacheSize => 'Dimensione massima cache video';

  @override
  String get maximum => 'Massimo';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media store attivato, questo non avrà effetto';

  @override
  String get medium => 'Medio';

  @override
  String get membershipCode => 'Codice';

  @override
  String get membershipCodeSentToEmail => 'Codice inviato nella tua email';

  @override
  String get membershipDidntChange => 'L\'abbonamento non è cambiato';

  @override
  String get membershipEnjoyNew => 'Divertiti con il tuo nuovo abbonamento';

  @override
  String get membershipFreeCoupon => 'Coupon gratuito';

  @override
  String get membershipManage => 'Gestisci il tuo abbonamento';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Niente abbonamenti trovati per questo utente';

  @override
  String get membershipSignInToPatreonAccount => 'Accedi al tuo account patreon';

  @override
  String get membershipUnknown => 'Abbonamento Sconosciuto';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Ti serve un abbonamento di $name1 o $name2 per aggiungere più account';
  }

  @override
  String get merge => 'Unisci';

  @override
  String get metadataCache => 'Cache metadati';

  @override
  String get metadataEditFailed => 'Modifica metadati fallita';

  @override
  String get metadataReadFailed => 'Lettura metadati fallita';

  @override
  String get minFileDuration => 'Durata minima traccia';

  @override
  String get minFileSize => 'Dimensione minima file';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Durata minima traccia per ripristinare l\'ultima posizione riprodotta';

  @override
  String get minValueCantBeMoreThanMax => 'Il valore minimo non può essere maggiore del massimo';

  @override
  String get minValueToCountTrackListen => 'Conta un ascolto dopo: ';

  @override
  String get minimizedMiniplayer => 'Miniplayer minimizzato';

  @override
  String get minimum => 'Minimo';

  @override
  String get minimumOneFolderSubtitle => 'Dovrebbe esserci almeno 1 cartella, aggiungi altre cartelle se vuoi rimuovere questa';

  @override
  String get minimumOneItem => 'Impossibile rimuovere elemento';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Almeno $numberString elementi dovrebbero rimanere',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Durata minima del segmento';

  @override
  String get miniplayerCustomization => 'Personalizzazione miniplayer';

  @override
  String get minutes => 'minuti';

  @override
  String get missingEntries => 'Voci mancanti';

  @override
  String get missingTracks => 'Tracce Mancanti';

  @override
  String get mix => 'Combinazione';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Playlist mista generata da youtube';

  @override
  String get mixes => 'Mix';

  @override
  String get mobile => 'Cellulare';

  @override
  String get month => 'Mese';

  @override
  String get months => 'Mesi';

  @override
  String get mood => 'Umore';

  @override
  String get moods => 'Mood';

  @override
  String get more => 'Altro';

  @override
  String get mostPlayed => 'Più riprodotte';

  @override
  String get multipleTracksTagsEditNote => 'Stai per modificare queste tracce,\nI campi non modificati rimarranno invariati.';

  @override
  String get musicOfftopic => 'Musica fuori tema';

  @override
  String get name => 'Nome';

  @override
  String get nameContainsBadCharacter => 'Il nome contiene un carattere non valido';

  @override
  String get never => 'Mai';

  @override
  String get newDirectory => 'Nuova cartella';

  @override
  String get newLabel => 'Nuovo/Nuova';

  @override
  String get newTracksAdd => 'Aggiungi tracce';

  @override
  String get newTracksMoods => 'Atmosfera';

  @override
  String get newTracksMoodsSubtitle => 'Genera tracce in base ai mood disponibili';

  @override
  String get newTracksRandom => 'Casuale';

  @override
  String get newTracksRandomSubtitle => 'Scegli tracce casuali dalla tua libreria';

  @override
  String get newTracksRatings => 'Valutazioni';

  @override
  String get newTracksRatingsSubtitle => 'Genera tracce che hanno una valutazione specifica';

  @override
  String get newTracksRecommended => 'Suggeriti';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Genera tracce che di solito ascolti con $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Data di uscita simile';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Genera tracce pubblicate più o meno nello stesso periodo di $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Traccia con anno sconosciuto';

  @override
  String get newest => 'Più recente';

  @override
  String get next => 'Prossimo';

  @override
  String get no => 'no';

  @override
  String get noChangesFound => 'Nessuna modifica trovata.';

  @override
  String get noEnoughTracks => 'Non hai molte tracce..';

  @override
  String get noExcludedFolders => 'Non hai cartelle escluse';

  @override
  String get noFolderChosen => 'Non hai scelto nessuna cartella';

  @override
  String get noMoodsAvailable => 'Nessun mood disponibile';

  @override
  String get noNetworkAvailableToFetchData => 'Nessuna connessione disponibile per caricare dati';

  @override
  String get noTracksFound => 'Nessuna traccia trovata';

  @override
  String get noTracksFoundBetweenDates => 'In questo intervallo temporale non ci sono tracce.';

  @override
  String get noTracksFoundInDirectory => 'Nessuna traccia trovata in questa cartella';

  @override
  String get noTracksInHistory => 'Non hai abbastanza tracce nella cronologia';

  @override
  String get nonActive => 'Non attivo';

  @override
  String get nonFavourites => 'Non-Preferiti';

  @override
  String get none => 'Nessuna';

  @override
  String get normalizeAudio => 'Normalizzazione audio';

  @override
  String get normalizeAudioSubtitle => 'Normalizza il volume dai replay gain tag o dai info fornito da youtube';

  @override
  String get notAvailableForYourDevice => 'Non disponibile per il tuo dispositivo';

  @override
  String get notSupportedForNetworkFiles => 'Non supportato per file di Rete';

  @override
  String get note => 'Nota';

  @override
  String get notification => 'Notification';

  @override
  String get notifications => 'Notifiche';

  @override
  String get numberOfTracks => 'Numero di tracce';

  @override
  String get ofLabel => 'di';

  @override
  String get offlineSearch => 'Ricerca Offline';

  @override
  String get offset => 'Offset';

  @override
  String get oldDirectory => 'Vecchia cartella';

  @override
  String get oldDirectoryStillHasTracks => 'La vecchia cartella contiene ancora alcune tracce, confermare?';

  @override
  String get oldestWatch => 'Guardata più vecchia';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Su interruzione';

  @override
  String get onNotificationTap => 'Su tocco notifica';

  @override
  String get onOpeningYoutubeLink => 'All\'apertura di un link youtube';

  @override
  String get onSwiping => 'Scorrendo';

  @override
  String get onVolumeZero => 'Con volume 0';

  @override
  String get ongoing => 'In corso';

  @override
  String get open => 'Open';

  @override
  String get openApp => 'Apri app';

  @override
  String get openInFileExplorer => 'Apri l\'esplora risorse';

  @override
  String get openInYoutubeView => 'Apri in vista Youtube';

  @override
  String get openMiniplayer => 'Apri miniplayer';

  @override
  String get openQueue => 'Apri coda';

  @override
  String get openYoutubeLink => 'Apri link Youtube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'L\'operazione $name richiede un account, accedi per procedere';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'L\'operazione $operation richiede almeno un abbonamento $name';
  }

  @override
  String get or => 'o';

  @override
  String get others => 'Altri';

  @override
  String get output => 'Output';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Sovrascrivi file vecchi nella stessa cartella';

  @override
  String get palette => 'Tavolozza';

  @override
  String get paletteMix => 'Mix Palette';

  @override
  String get paletteNewMix => 'Nuovo mix';

  @override
  String get paletteSelectedMix => 'Mix selezionato';

  @override
  String get parallelDownloads => 'Download Paralleli';

  @override
  String get parsed => 'analizzato';

  @override
  String get password => 'Password';

  @override
  String get path => 'Percorso file completo';

  @override
  String get pause => 'Pause';

  @override
  String get pauseFadeDuration => 'Durata dissolvenza pausa';

  @override
  String get pausePlayback => 'Pausa riproduzione';

  @override
  String get percentage => 'Percentuale';

  @override
  String get performanceMode => 'Modalità performance';

  @override
  String get performanceNote => 'Può influire sulle prestazioni';

  @override
  String get personalized => 'Personalizzato';

  @override
  String get personalizedRelatedVideos => 'Personalizza Video Coerenti';

  @override
  String get personalizedRelatedVideosSubtitle => 'Disattivando questa funzione, l\'uso dei dati aumenterà';

  @override
  String get pickColorsFromDeviceWallpaper => 'Scegli i colori dallo sfondo del dispositivo';

  @override
  String get pickFromStorage => 'Scegli dall\'archivio';

  @override
  String get pinned => 'Fissati';

  @override
  String get pitch => 'Tono';

  @override
  String get plain => 'Semplice';

  @override
  String get play => 'Riproduci';

  @override
  String get playAfter => 'Riproduci dopo';

  @override
  String get playAfterNextPrev => 'Riproduzione automatica su Successivo/Precedente';

  @override
  String get playAll => 'Riproduci tutto';

  @override
  String get playFadeDuration => 'Durata dissolvenza riproduzione';

  @override
  String get playLast => 'Riproduci ultima';

  @override
  String get playNext => 'Riproduci prossima';

  @override
  String get playbackSetting => 'Riproduzione';

  @override
  String get playbackSettingSubtitle => 'Accessibile direttamente nel player con la pressione prolungata del pulsante audio';

  @override
  String get playlist => 'Playlist';

  @override
  String get playlists => 'Playlist';

  @override
  String get playlistsImportM3uNative => 'Questo importerà playlist M3U per essere utilizzati da Namida, utilizza solo se stai migrando';

  @override
  String get playlistsImportM3uSynced =>
      'Questo importerà automaticamente i playlist M3U dalle cartelle indicizzate e tenerle sincronizzate con il file originale M3U. Attiva se vuoi accedere/modificare le playlist dalle altre app';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Importa automaticamente playlist M3U';

  @override
  String get pleaseEnterADifferentName => 'Questo nome esiste già :(\nprova con un altro nome originale';

  @override
  String get pleaseEnterALink => 'Inserisci un link';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. per caso è un link youtube?';

  @override
  String get pleaseEnterAName => 'Inserisci un nome';

  @override
  String get port => 'Porta';

  @override
  String get preventDuplicatedTracks => 'Impedisci tracce duplicate';

  @override
  String get preventDuplicatedTracksSubtitle => 'Usa il nome file per identificare univocamente le tracce';

  @override
  String get preview => 'Anteprima';

  @override
  String get previous => 'Precedente';

  @override
  String get previousButtonReplays => 'Pulsante replay precendente';

  @override
  String get previousButtonReplaysSubtitle => 'if pressed while current position was more than seek duration';

  @override
  String get prioritizeEmbeddedLyrics => 'Dai priorità ai testi incorporati';

  @override
  String get priority => 'Priorità';

  @override
  String get private => 'Privato';

  @override
  String get progress => 'Progresso';

  @override
  String get promptToChangeTrackPath => 'Di solito accade quando elimini/sposti/rinomini il file al di fuori di namida, vuoi aggiornare il percorso corrente?';

  @override
  String get public => 'Pubblico';

  @override
  String get queue => 'Coda';

  @override
  String get queues => 'Code';

  @override
  String get random => 'Casuale';

  @override
  String get randomPicks => 'Scelte casuali';

  @override
  String get rating => 'Valutazione';

  @override
  String get reIndex => 'Re-indicizza';

  @override
  String get reIndexSubtitle => 'Ricostruisci la tua libreria musicale da zero';

  @override
  String get reIndexWarning =>
      'Questo processo potrebbe richiedere un po\' di tempo, a seconda della dimensione della tua libreria.\n\nLe copertine non verranno reindicizzate finché esistono ancora';

  @override
  String get recentAlbums => 'Album recenti';

  @override
  String get recentArtists => 'Artisti recenti';

  @override
  String get recentListens => 'Ascoltate di recente';

  @override
  String get recentlyAdded => 'Aggiunte di recente';

  @override
  String get recordLabel => 'Etichetta';

  @override
  String get refresh => 'Aggiornare';

  @override
  String get refreshLibrary => 'Aggiorna libreria';

  @override
  String get refreshLibrarySubtitle => 'Controlla musica aggiunta o rimossa di recente';

  @override
  String get refreshOnStartup => 'Aggiorna durante l\'avvio';

  @override
  String get relatedVideos => 'Video a riguardo';

  @override
  String get rememberAudioOnlyMode => 'Ricorda la modalità solo audio';

  @override
  String get remixer => 'Remixer';

  @override
  String get remove => 'Rimuovi';

  @override
  String get removeDuplicates => 'Rimuovi duplicati';

  @override
  String get removeFromFavourites => 'Rimuovi dai preferiti';

  @override
  String get removeFromLibrary => 'Rimuovi dalla libreria';

  @override
  String get removeFromPlaylist => 'Rimuovi dalla playlist';

  @override
  String get removeQueue => 'Rimuovi coda';

  @override
  String get removeSourceFromHistory => 'Rimuovi sorgente dalla cronologia';

  @override
  String get removeWhitespaces => 'Rimuovi spazi';

  @override
  String get removed => 'Rimosso';

  @override
  String get rename => 'Rinomina';

  @override
  String get renamePlaylist => 'Rinomina playlist';

  @override
  String get reorderable => 'Riordinabile';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ripeti per $number volta',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Modalità ripeti';

  @override
  String get repeatModeAll => 'Ripeti tutta la coda';

  @override
  String get repeatModeNone => 'Interrompi all\'ultima traccia';

  @override
  String get repeatModeOne => 'Ripeti traccia corrente';

  @override
  String get replaceAllListensWithAnotherTrack => 'Sostituisci tutti gli ascolti con un\'altra traccia';

  @override
  String get replies => 'Risposte';

  @override
  String get reply => 'Rispondi';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Richiede la cancellazione della cache immagini e la reindicizzazione';

  @override
  String get rescanVideos => 'Riscansiona video';

  @override
  String get resetBrightness => 'Reimposta luminosità';

  @override
  String get resetToDefault => 'Reimposta';

  @override
  String get respectNoMedia => 'Rispetta .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Non includere le cartelle con .nomedia';

  @override
  String get restart => 'Riavvia';

  @override
  String get restoreBackup => 'Ripristina backup';

  @override
  String get restoreDefaults => 'Ripristina impostazioni predefinite';

  @override
  String get restoredBackupSuccessfully => 'Ripristino backup effettuato';

  @override
  String get restoredBackupSuccessfullySub => 'Il file di backup è stato ripristinato con successo';

  @override
  String get resume => 'Riprendi';

  @override
  String get resumeIfWasInterrupted => 'Riprendi se interrotto';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Riprendi se messo in pausa dal volume';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Riprendi se messo in pausa in meno di $numberString minuti',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Riabilita i Dislike di Youtube';

  @override
  String get reverseOrder => 'Inverti ordine';

  @override
  String get rightAction => 'Azione destra';

  @override
  String get ringtone => 'Suoneria';

  @override
  String get sameDirectoryOnly => 'Solo stessa cartella';

  @override
  String get sample => 'Esempio';

  @override
  String get sampleRate => 'Frequenza di campionamento';

  @override
  String get save => 'Salva';

  @override
  String get saveToLibrary => 'Salva nella libreria';

  @override
  String get savedIn => 'Salvato in';

  @override
  String get scaleMultiplier => 'Moltiplicatore di Scala';

  @override
  String get search => 'Cerca';

  @override
  String get searchYoutube => 'Cerca su YouTube';

  @override
  String get seconds => 'secondi';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Durata ricerca';

  @override
  String get seekDurationInfo => 'Puoi toccare la durata corrente per tornare indietro e la durata totale per andare avanti';

  @override
  String get seekbar => 'Barra di avanzamento';

  @override
  String get selectAll => 'Seleziona tutto';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Seleziona file esistenti nella libreria locale';

  @override
  String get selectedTracks => 'Tracce selezionate';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitoni';

  @override
  String get separatorsBlacklistSubtitle => 'Queste parole non verranno divise';

  @override
  String get separatorsMessage => 'Non servono spazi, a meno che non si vuole usare una lettera/simbolo che può trovarsi in una parola intera (come x e ft.)';

  @override
  String get serverAddress => 'Indirizzo del Server';

  @override
  String get setAs => 'Imposta come';

  @override
  String get setAsDefault => 'Imposta come predefinito';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Imposta ultima modifica file come data di caricamento video';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Imposta mood';

  @override
  String get setMoodsSubtitle => 'Usa virgole (,) per separarli';

  @override
  String get setRating => 'Imposta valutazione';

  @override
  String get setTags => 'Imposta tag';

  @override
  String get setYoutubeLink => 'Imposta link Youtube';

  @override
  String get settings => 'Impostazioni';

  @override
  String get setupFirstStartup => 'Configurazione primo avvio';

  @override
  String get share => 'Condividi';

  @override
  String get shareLogs => 'Condividi Logs';

  @override
  String get shortcuts => 'Scorciatoie';

  @override
  String get shouldDuck => 'Dovrebbe abbassarsi';

  @override
  String get shouldDuckNote => 'Indica che il volume dovrebbe essere abbassato. es: notifica';

  @override
  String get shouldPause => 'Dovrebbe mettere in pausa';

  @override
  String get shouldPauseNote => 'Indica che la riproduzione dovrebbe essere messa in pausa. es: chiamate';

  @override
  String get showAll => 'Mostra Tutto';

  @override
  String get showChannelWatermarkInFullscreen => 'Mostra il watermark del canale a schermo intero';

  @override
  String get showFailedOnly => 'Mostra Solo Falliti';

  @override
  String get showHideUnknownFields => 'Mostra/nascondi campi sconosciuti';

  @override
  String get showInSeekbar => 'Mostra nella barra di progresso';

  @override
  String get showMixPlaylistsIn => 'Mostra Mix nei';

  @override
  String get showMore => 'Mostra altro';

  @override
  String get showShortVideosIn => 'Mostra Shorts in';

  @override
  String get showSkipButton => 'Mostra bottone di skip';

  @override
  String get showVideoEndcards => 'Mostra i video endcards';

  @override
  String get showWebm => 'Mostra webm';

  @override
  String get shuffle => 'Casuale';

  @override
  String get shuffleAll => 'Riproduci tutto in modo casuale';

  @override
  String get shuffleNext => 'Mescola il prossimo';

  @override
  String get signIn => 'Accedi';

  @override
  String get signInCanceled => 'L\'accesso è stato annullato';

  @override
  String get signInFailed => 'Accesso fallito';

  @override
  String get signInToYourAccount => 'Accedi al tuo account';

  @override
  String get signInYouDontHaveAccount => 'Non hai nessun account accesso';

  @override
  String get signInYouNeedAccountToViewPage => 'Ti serve un account per visualizzare questa pagina';

  @override
  String get signOut => 'Disconnettiti';

  @override
  String signOutFromName({required String name}) {
    return 'Disconnettiti da $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Accedere permette un uso minimo';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Ottieni accesso anticipato da patreon o usando un coupon';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Intervallo di tempo';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Genera tracce che hai ascoltato intorno allo stesso tempo di $currentTrack';
  }

  @override
  String get singles => 'Singoli';

  @override
  String get size => 'Dimensione';

  @override
  String get skip => 'Salta';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Salta silenzio';

  @override
  String get skipSponsorSegmentsInVideos => 'Salta i segmenti di pubblicità nei video';

  @override
  String get sleepAfter => 'Sospendi dopo';

  @override
  String get sleepTimer => 'Timer sospensione';

  @override
  String get socials => 'Social';

  @override
  String get socialsSubtitle => 'Unisciti a noi sulle nostre piattaforme per Aggiornamenti, Consigli, Discussioni ed Idee';

  @override
  String get someWebServersRequireAuthentication => 'Alcuni Server Web richiedono l\'atenticazione. Aggiorna le credenziali per mantenere l\'accesso alla tua libreria.';

  @override
  String get sortBy => 'Ordina per';

  @override
  String get source => 'Sorgente';

  @override
  String get speed => 'Velocità';

  @override
  String get sponsor => 'Pubblicità';

  @override
  String get sponsorblock => 'SponsorBlock (if referred to the service)';

  @override
  String get sponsorblockLeaderboard => 'Classifica SponsorBlock';

  @override
  String get staggeredAlbumGridView => 'Vista griglia album sfalsata';

  @override
  String get start => 'Inizio';

  @override
  String get stats => 'Statistiche';

  @override
  String get statsSubtitle => 'Alcune informazioni sulla tua libreria';

  @override
  String get stop => 'Stop';

  @override
  String get stopAfterThisTrack => 'Interrompi dopo questa traccia';

  @override
  String get stopAfterThisVideo => 'Arresta dopo questo video';

  @override
  String get storagePermissionDenied => 'Permesso negato';

  @override
  String get storagePermissionDeniedSubtitle => 'Per favore consenti l\'accesso per eseguire questa azione';

  @override
  String get stretchLyricsDuration => 'Allunga durata del testo';

  @override
  String get subdirectory => 'Sottocartella';

  @override
  String get subscribe => 'Iscriviti';

  @override
  String get subscribed => 'Iscritto';

  @override
  String get subscriber => 'Iscritto';

  @override
  String get subscribers => 'Iscritti';

  @override
  String get succeeded => 'Riuscito';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Supporto';

  @override
  String get supremacy => 'Supremazia';

  @override
  String get sussyBaka => 'O\'Frà, nisciuna traccia';

  @override
  String get swipeActions => 'Azioni di scorrimento';

  @override
  String get swipeToOpenDrawer => 'Scorri per aprire il cassetto';

  @override
  String get synced => 'Sincronizzato';

  @override
  String get synopsis => 'Sinossi';

  @override
  String get tagFields => 'Campi tag';

  @override
  String get tags => 'Tag';

  @override
  String get tapAction => 'Azioni di tocco';

  @override
  String get tapToSeek => 'Premi per scorrere';

  @override
  String get theFollowingChangesWereDetected => 'Le seguenti modifiche sono state rilevate';

  @override
  String get themeMode => 'Tema';

  @override
  String get themeModeDark => 'Scuro';

  @override
  String get themeModeLight => 'Chiaro';

  @override
  String get themeModeSystem => 'Sistema';

  @override
  String get themeSettings => 'Tema';

  @override
  String get themeSettingsSubtitle => 'L\'atmosfera generale del tuo player';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Questa playlist ha dei filtri attivi, disattivali prima di riordinare.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Questo video è probabilmente cancellato o è stato messo in privato';

  @override
  String get thumbnails => 'Copertine';

  @override
  String get title => 'Titolo';

  @override
  String get top => 'Cima';

  @override
  String get topComments => 'Migliori Commenti';

  @override
  String get topCommentsSubtitle => 'Mostra i commenti sopra invece che sotto';

  @override
  String get topRecentAlbums => 'Album recenti migliori';

  @override
  String get topRecentArtists => 'Artisti recenti migliori';

  @override
  String get topRecents => 'Top recenti';

  @override
  String get totalListenTime => 'Tempo di ascolto totale';

  @override
  String get totalListens => 'Ascolti totali';

  @override
  String get totalTracks => 'Tracce totali';

  @override
  String get totalTracksDuration => 'Durata totale tracce';

  @override
  String get track => 'Traccia';

  @override
  String get trackArtistsSeparator => 'Separatori artisti traccia';

  @override
  String get trackGenresSeparator => 'Separatori generi traccia';

  @override
  String get trackInfo => 'Info traccia';

  @override
  String get trackNotFound => 'Traccia non trovata';

  @override
  String get trackNumber => 'Numero traccia';

  @override
  String get trackNumberTotal => 'Numero totale tracce';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Vecchio nome: \"$oldName\"\n\nNuovo nome: \"$newName\"\n\nSei sicuro?';
  }

  @override
  String get trackPlayMode => 'Modalità riproduzione';

  @override
  String get trackPlayModeSearchResults => 'Risultati ricerca';

  @override
  String get trackPlayModeSelectedOnly => 'Solo traccia selezionata';

  @override
  String get trackPlayModeTrackAlbum => 'Album della traccia';

  @override
  String get trackPlayModeTrackArtist => 'Artista principale della traccia';

  @override
  String get trackPlayModeTrackGenre => 'Genere della traccia';

  @override
  String get trackThumbnailSizeInList => 'Dimensione copertina traccia';

  @override
  String get trackTileCustomization => 'Personalizzazione riquadro traccia';

  @override
  String get trackTileItemsSeparator => 'Separatore elementi';

  @override
  String get tracks => 'Tracce';

  @override
  String get tracksExcludedByNomedia => 'Tracce escluse da .nomedia';

  @override
  String get tracksInfo => 'Info tracce';

  @override
  String get underrated => 'Sottovalutato';

  @override
  String get undo => 'Annulla';

  @override
  String get undoChanges => 'Annullare le modifiche?';

  @override
  String get undoChangesDeletedPlaylist => 'Annulla playlist eliminata';

  @override
  String get undoChangesDeletedQueue => 'Annulla coda eliminata';

  @override
  String get undoChangesDeletedTrack => 'Annulla traccia eliminata';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Illimitato';

  @override
  String get unlisted => 'Non in elenco';

  @override
  String get unlock => 'Sblocca';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Aggiorna';

  @override
  String get updateDirectoryPath => 'Aggiorna percorso cartella';

  @override
  String get updateMissingTracksOnly => 'Aggiorna solo tracce mancanti';

  @override
  String get updating => 'Aggiornamento in corso';

  @override
  String get useCollapsedSettingTiles => 'Usa riquadri impostazioni compressi';

  @override
  String get useMediaStore => 'Usa Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ tempo di indicizzazione istantaneo\nx rispetta .nomedia sarà abilitato forzatamente\nx alcuni tag metadati mancheranno\nx integrazione youtube per libreria locale non funzionerà';

  @override
  String get usePitchBlack => 'Usa nero assoluto';

  @override
  String get usePitchBlackSubtitle => 'Utile per schermi AMOLED.. e sembra più cool';

  @override
  String get used => 'Usato';

  @override
  String get value => 'Valore';

  @override
  String get valueBetween50200 => 'Il valore dovrebbe essere tra 50% e 200%';

  @override
  String get vibration => 'Vibrazione';

  @override
  String get vibrationType => 'Tipo di Vibrazione';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Cache video';

  @override
  String get videoCacheFile => 'File video in cache';

  @override
  String get videoCacheFiles => 'File video in cache';

  @override
  String get videoOnly => 'Solo video';

  @override
  String get videoPlaybackSource => 'Sorgente video';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Darà priorità ai video locali, se non trovati verranno recuperati da youtube';

  @override
  String get videoPlaybackSourceLocal => 'Video locali';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Controlla se nella lista di cartelle scelte esiste un file video (il cui nome contiene il nome file della traccia)';

  @override
  String get videoPlaybackSourceYoutube => 'Da Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Controlla nel nome file e nei commenti della traccia eventuali link youtube corrispondenti, i video vengono messi in cache per un uso successivo.';

  @override
  String get videoQuality => 'Qualità video';

  @override
  String get videoQualitySubtitle => 'Verrà selezionata la qualità più alta disponibile.';

  @override
  String get videoQualitySubtitleNote => 'È sempre bene tenere alternative in più nel caso una qualità non venga trovata, altrimenti si passerà alla qualità peggiore';

  @override
  String get videos => 'Video';

  @override
  String get view => 'visualizzazione';

  @override
  String get viewAll => 'Mostra tutto';

  @override
  String get views => 'visualizzazioni';

  @override
  String get volume => 'Volume';

  @override
  String get warning => 'Attenzione';

  @override
  String get waveformBarsCount => 'Numero colonne d\'onda';

  @override
  String get webmNoEditTagsSupport => 'Il formato WEBM non supporta la modifica dei tag';

  @override
  String get week => 'Settimana';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Anno';

  @override
  String get yes => 'sì';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Il tuo abbonamento corrente è $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Il tuo ordine personalizzato sarà perso, sei sicuro di continuare?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'YT Music';

  @override
  String get youtubeSettingsSubtitle => 'Personalizza l\'esperienza Youtube';

  @override
  String get youtubeStyleMiniplayer => 'Youtube-style Miniplayer';

  @override
  String get ytPreferNewComments => 'Preferisci i nuovi commenti quando possibile';

  @override
  String get ytPreferNewCommentsSubtitle => 'La versione in cache verrà usata solo se non c\'è connessione';
}
