// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Polish (`pl`).
class AppLocalizationsPl extends AppLocalizations {
  AppLocalizationsPl([String locale = 'pl']) : super(locale);

  @override
  String get about => 'O aplikacji';

  @override
  String get active => 'Aktywny';

  @override
  String get add => 'Dodaj';

  @override
  String get addAccount => 'Dodaj konto';

  @override
  String get addAll => 'Dodaj wszystko';

  @override
  String get addAllAndRemoveOldOnes => 'Dodaj wszystko i usuń stare';

  @override
  String get addAsANewPlaylist => 'Dodaj jako nową playlistę';

  @override
  String get addAudioToLocalLibrary => 'Dodaj audio do lokalnej biblioteki';

  @override
  String get addFolder => 'Dodaj folder';

  @override
  String get addLanguage => 'Dodaj język';

  @override
  String get addLanguageSubtitle => 'Pomóż w tłumaczeniu Namidy na swój język';

  @override
  String get addLrcFile => 'Dodaj plik LRC';

  @override
  String get addMoreFromThisAlbum => 'Dodaj więcej z tego albumu do kolejki';

  @override
  String get addMoreFromThisArtist => 'Dodaj więcej od tego wykonawcy do kolejki';

  @override
  String get addMoreFromThisFolder => 'Dodaj więcej z tego folderu do kolejki';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Dodaj więcej z $media do kolejki';
  }

  @override
  String get addOnlyMissing => 'Dodaj tylko brakujące';

  @override
  String get addToFavourites => 'Dodaj do ulubionych';

  @override
  String get addToPlaylist => 'Dodaj do playlisty';

  @override
  String get addTracksAtTheBeginning => 'Dodaj ścieżki na początku';

  @override
  String get added => 'dodano';

  @override
  String get advanced => 'Zaawansowane';

  @override
  String get advancedSettings => 'Zaawansowane';

  @override
  String get advancedSettingsSubtitle => 'Ustawienia zaawansowane, nie ruszaj';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Wykonawca albumu';

  @override
  String get albumArtists => 'Wykonawcy albumu';

  @override
  String get albumIdentifiers => 'Identyfikatory albumu';

  @override
  String get albumThumbnailSizeInList => 'Rozmiar miniatury albumu';

  @override
  String get albumTileCustomization => 'Dostosowanie kafelka albumu';

  @override
  String get albums => 'Albumy';

  @override
  String get albumsCount => 'Liczba albumów';

  @override
  String get all => 'Wszystko';

  @override
  String get allTime => 'Cały czas';

  @override
  String get alreadyExists => 'Już istnieje';

  @override
  String get always => 'Zawsze';

  @override
  String get alwaysAsk => 'Zawsze pytaj';

  @override
  String get alwaysDim => 'Zawsze przyciemnij';

  @override
  String get alwaysExpandedSearchbar => 'Zawsze rozszerzony pasek wyszukiwania';

  @override
  String get alwaysRestore => 'Zawsze przywracaj';

  @override
  String get animatingThumbnailIntensity => 'Intensywność animacji miniatur';

  @override
  String get animatingThumbnailInversed => 'Odwrotne animacje';

  @override
  String get animatingThumbnailInversedSubtitle => 'Wysokie wartości spowodują zmniejszenie miniatury';

  @override
  String get anotherProcessIsRunning => 'Inny proces jest już uruchomiony.';

  @override
  String get appIcon => 'Ikona aplikacji';

  @override
  String get appVersion => 'Wersja aplikacji';

  @override
  String get artist => 'Wykonawca';

  @override
  String get artists => 'Wykonawcy';

  @override
  String get artwork => 'Okładka';

  @override
  String get artworkGestures => 'Gesty okładki';

  @override
  String get artworks => 'Okładki';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Pamięć podręczna audio';

  @override
  String get audioOnly => 'Tylko audio';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Interwał automatycznego tworzenia kopii zapasowych';

  @override
  String get autoColoring => 'Automatyczne kolorowanie';

  @override
  String get autoColoringSubtitle => 'Automatycznie wybieraj kolory odtwarzacza z aktualnej okładki';

  @override
  String get autoExtractTagsFromFilename => 'Automatyczne wyodrębnianie z nazwy pliku';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Automatyczne wyodrębnianie tytułu i wykonawcy z tytułu wideo';

  @override
  String get autoGenerated => 'Wygenerowane automatycznie';

  @override
  String get autoSkip => 'Automatyczne pomijanie';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Automatyczne uruchamianie radia';

  @override
  String get autoStartRadioSubtitle => 'Automatycznie dodaje miks playlisty podczas odtwarzania pojedynczego utworu';

  @override
  String get automaticBackup => 'Automatyczny';

  @override
  String get automaticBackupSubtitle => 'Automatycznie stosuje najnowszy plik kopii zapasowej znajdujący się w lokalizacji kopii zapasowej';

  @override
  String get backupAndRestore => 'Kopia zapasowa i przywracanie';

  @override
  String get backupAndRestoreSubtitle => 'Utwórz kopię zapasową bazy danych i ustawień';

  @override
  String get balanced => 'Zrównoważony';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Pomiędzy datami';

  @override
  String get bitrate => 'Jakość';

  @override
  String get blacklist => 'Czarna lista';

  @override
  String get borderRadiusMultiplier => 'Mnożnik promienia krawędzi';

  @override
  String get cache => 'Pamięć podręczna';

  @override
  String get cancel => 'Anuluj';

  @override
  String get canceled => 'Anulowano';

  @override
  String get changed => 'Zmieniono';

  @override
  String get changelog => 'Dziennik zmian';

  @override
  String get changelogSubtitle => 'Zobacz, co zostało dodane/naprawione w Namidzie';

  @override
  String get channel => 'Kanał';

  @override
  String get channels => 'Kanały';

  @override
  String get check => 'Sprawdź';

  @override
  String get checkForMore => 'Sprawdź więcej';

  @override
  String get checkList => 'Lista kontrolna';

  @override
  String get choose => 'Wybierz';

  @override
  String get chooseWhatToClear => 'Wybierz, co chcesz wyczyścić';

  @override
  String get claim => 'Roszczenie';

  @override
  String get clear => 'Wyczyść';

  @override
  String get clearAudioCache => 'Wyczyść pamięć podręczną audio';

  @override
  String get clearImageCache => 'Wyczyść pamięć podręczną obrazów';

  @override
  String get clearImageCacheWarning => 'Ostrzeżenie: spowoduje utworzenie biblioteki bez obrazów. Używaj tylko do odbudowy pamięci podręcznej obrazów.';

  @override
  String get clearTrackItem => 'Wyczyść utwory';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Wyczyść $numberString utworów',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Wyczyść pamięć podręczną wideo';

  @override
  String get clearVideoCacheNote => 'Możesz wybrać, co chcesz usunąć.';

  @override
  String get clock => 'Zegar';

  @override
  String get colorPalette => 'Paleta kolorów';

  @override
  String get colorPaletteNote1 => 'Naciśnij i przytrzymaj kolor, aby go usunąć';

  @override
  String get colorPaletteNote2 => 'Kliknij mix, którego chcesz użyć jako domyślnego koloru';

  @override
  String get colorPalettes => 'Palety kolorów';

  @override
  String get comment => 'Komentarz';

  @override
  String get comments => 'Komentarze';

  @override
  String get composer => 'Kompozytor';

  @override
  String get compress => 'Kompresja';

  @override
  String get compressImages => 'Kompresuj obrazy';

  @override
  String get compressionPercentage => 'Procent kompresji';

  @override
  String get configure => 'Skonfiguruj';

  @override
  String get confirm => 'Potwierdź';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Skopiowano okładkę';

  @override
  String get copiedToClipboard => 'Skopiowano do schowka';

  @override
  String get copy => 'Kopiuj';

  @override
  String get corruptedFile => 'Nie można przeanalizować pliku. Może być uszkodzony';

  @override
  String get couldntOpen => 'Nie można otworzyć :(';

  @override
  String get couldntOpenYtLink => 'Brak linku YouTube do tego utworu';

  @override
  String get couldntPlayFile => 'Nie można odtworzyć pliku';

  @override
  String get couldntRenamePlaylist => 'Nie można zmienić nazwy playlisty';

  @override
  String get couldntSaveImage => 'Nie można zapisać obrazu';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Kraj';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Utwórz';

  @override
  String get createBackup => 'Utwórz kopię zapasową';

  @override
  String get createNewPlaylist => 'Utwórz nową playlistę';

  @override
  String get createdBackupSuccessfully => 'Utworzono kopię zapasową';

  @override
  String get createdBackupSuccessfullySub => 'Plik kopii zapasowej został pomyślnie utworzony';

  @override
  String get crossPlatformSync => 'Synchronizacja międzyplatformowa';

  @override
  String get crossfadeDuration => 'Czas przejścia';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Włącz funkcję przejścia automatycznie w ciągu ostatnich $secondsString sekund',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Nie włączaj przejścia automatycznie';

  @override
  String get custom => 'Własny';

  @override
  String get customizations => 'Dostosowanie';

  @override
  String get customizationsSubtitle => 'Dostosuj wygląd odtwarzacza, według własnego uznania';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Dane dostarcza: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Tryb oszczędzania danych';

  @override
  String get database => 'Baza danych';

  @override
  String get date => 'Data';

  @override
  String get dateAdded => 'Data dodania';

  @override
  String get dateCreated => 'Data utworzenia';

  @override
  String get dateModified => 'Data modyfikacji';

  @override
  String get dateTimeFormat => 'Format daty i godziny';

  @override
  String get day => 'Dzień';

  @override
  String get days => 'Dni';

  @override
  String get defaultBackupLocation => 'Domyślna lokalizacja kopii zapasowej';

  @override
  String get defaultColor => 'Domyślny kolor';

  @override
  String get defaultColorSubtitle => 'Ustaw kolor, który będzie używany przez odtwarzacz';

  @override
  String get defaultDownloadLocation => 'Domyślna lokalizacja pobierania';

  @override
  String get defaultLabel => 'Domyślny';

  @override
  String get defaultLibraryTab => 'Domyślna karta Biblioteka';

  @override
  String get delete => 'Usuń';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Usunąć $countString plik reprezentujący $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Usuń trwale $numberText ze swojej pamięci';
  }

  @override
  String get deletePlaylist => 'Usuń playlistę';

  @override
  String get deleteTempFiles => 'Usuń pliki tymczasowe';

  @override
  String get deleted => 'Usunięte';

  @override
  String get description => 'Opis';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Czy miałeś na myśli';

  @override
  String get dimIntensity => 'Intensywność przyciemnienia';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Przyciemnij miniodtwarzacz po $secondsString sekundach bezczynności',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Katalog nie istnieje';

  @override
  String get disable => 'Wyłącz';

  @override
  String get disableAll => 'Wyłącz wszystko';

  @override
  String get disableReordering => 'Wyłącz zmianę kolejności';

  @override
  String get disableSearchCleanup => 'Wyłącz czyszczenie wyszukiwania';

  @override
  String get discNumber => 'Numer płyty';

  @override
  String get discNumberTotal => 'Łącznie płyt';

  @override
  String get discover => 'Odkrywaj';

  @override
  String get dislike => 'Nie lubię';

  @override
  String get dismissibleMiniplayer => 'Odrzucanie miniodtwarzacza';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Data karty albumu w prawym górnym rogu';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Wyświetl datę albumu w prawym górnym rogu karty albumu';

  @override
  String get displayArtistBeforeTitle => 'Wyświetl wykonawcę przed tytułem';

  @override
  String get displayArtworkOnLockscreen => 'Wyświetl okładkę na ekranie blokady';

  @override
  String get displayAudioInfoInMiniplayer => 'Wyświetl informacje audio';

  @override
  String get displayFavButtonInNotification => 'Wyświetl przycisk Ulubione w powiadomieniu';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Miniatura może zostać przemieszczona.';

  @override
  String get displayFavouriteIconInTrackTile => 'Wyświetl przycisk Ulubione';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Wyświetl pozostały czas trwania zamiast całkowitego';

  @override
  String get displayStopButtonInNotification => 'Wyświetlaj przycisk stop w powiadomieniach';

  @override
  String get displayThirdItemInRowInTrackTile => 'Wyświetl trzeci element w każdym rzędzie';

  @override
  String get displayThirdRowInTrackTile => 'Wyświetl trzeci rząd';

  @override
  String get displayTrackNumberInAlbumPage => 'Wyświetl numer utworu na stronie albumu';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Wyświetl małe pole zawierające numer utworu na stronie albumu';

  @override
  String get doNothing => 'Nic nie rób';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Gotowe';

  @override
  String get dontAskAgain => 'Nie pytaj ponownie';

  @override
  String get dontDim => 'Nie przyciemniaj';

  @override
  String get dontRestorePosition => 'Nie przywracaj';

  @override
  String get dontResume => 'Nie wznawiaj';

  @override
  String get doubleTapToToggleLyrics => 'Kliknij dwukrotnie, aby przełączyć tekst';

  @override
  String get download => 'Pobierz';

  @override
  String get downloadingWillOverrideIt => 'Pobieranie zastąpi to';

  @override
  String get downloads => 'Pobrane';

  @override
  String get downloadsMetadataTags => 'Pobrane tagi metadanych';

  @override
  String get downloadsMetadataTagsSubtitle => 'Domyślnie wyodrębnij wykonawcę, tytuł i album z informacji wideo';

  @override
  String get dragToSeek => 'Przeciągnij, aby wyszukać';

  @override
  String get duckAudio => 'Dźwięk kaczki';

  @override
  String get duplicatedItemsAdding => 'Próbujesz dodać elementy, które już istnieją na tej playliście';

  @override
  String get duplicatedTracks => 'Zduplikowane utwory';

  @override
  String get duration => 'Czas trwania';

  @override
  String get edgeColorsSwitching => 'Przełączanie kolorów krawędzi';

  @override
  String get edit => 'Edytuj';

  @override
  String get editArtwork => 'Edytuj okładkę';

  @override
  String get editTags => 'Edytuj tagi';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'Masz pola z pustymi/nieznaczącymi wartościami, upewnij się, że naprawdę chcesz je edytować';

  @override
  String get emptyValue => 'Pusta wartość';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Szybsze ładowanie i poprawiona wydajność, ale wykorzystuje więcej pamięci';

  @override
  String get enableBlurEffect => 'Włącz efekt rozmycia';

  @override
  String get enableBottomNavBar => 'Włącz dolny pasek nawigacji';

  @override
  String get enableBottomNavBarSubtitle => 'Elementy znajdują się w szufladzie po obu stronach';

  @override
  String get enableClipboardMonitoring => 'Włącz monitorowanie schowka';

  @override
  String get enableClipboardMonitoringSubtitle => 'Umożliwia od razu na wklejanie linków i tekstu w pasku wyszukiwania';

  @override
  String get enableCrossfadeEffect => 'Włącz efekt przejścia';

  @override
  String get enableFadeEffectOnPlayPause => 'Włącz efekt zanikania podczas odtwarzania/pauzy';

  @override
  String get enableFoldersHierarchy => 'Włącz hierarchię folderów';

  @override
  String get enableGlowEffect => 'Włącz efekt blasku';

  @override
  String get enableM3uSync => 'Włącz synchronizację M3U';

  @override
  String get enableM3uSyncNote1 => 'Synchronizacja M3U umożliwia zapisywanie zmian w playliście w oryginalnym pliku M3U';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Jeśli coś pójdzie nie tak, kopia zapasowa tej playlisty będzie dostępna w $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'W przypadku odrzucenia wszystkie zmiany na tej playliście zostaną utracone po ponownym uruchomieniu';

  @override
  String get enableMiniplayerParticles => 'Włącz poruszające się cząstki';

  @override
  String get enableParallaxEffect => 'Włącz efekt paralaksy';

  @override
  String get enablePartyMode => 'Włącz tryb imprezy';

  @override
  String get enablePartyModeSubtitle => 'Zastosuj fantazyjny efekt oddychania krawędzi';

  @override
  String get enablePictureInPicture => 'Włącz obraz w obrazie';

  @override
  String get enableReordering => 'Włącz zmianę kolejności';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Włącz czyszczenie wyszukiwania';

  @override
  String get enableSearchCleanupSubtitle => 'Wszystkie symbole i spacje zostaną zignorowane';

  @override
  String get enableSponsorblock => 'Włącz SponsorBlocka';

  @override
  String get enableVideoPlayback => 'Włącz odtwarzanie wideo';

  @override
  String get enterSymbol => 'Proszę wprowadzić symbol';

  @override
  String get equalizer => 'Korektor';

  @override
  String get error => 'Błąd';

  @override
  String get errorFetchingVideoList => 'Błąd podczas pobierania listy wideo';

  @override
  String get errorPlayingTrack => 'Błąd podczas odtwarzania utworu';

  @override
  String get excludedFodlers => 'Wykluczone foldery';

  @override
  String get exit => 'Wyjdź';

  @override
  String get exitAppSubtitle => 'Kliknij ponownie, aby wyjść';

  @override
  String get expandedMiniplayer => 'Rozszerzony miniodtwarzacz';

  @override
  String get exportAsM3u => 'Eksportuj jako M3U';

  @override
  String get extension => 'Rozszerzenie';

  @override
  String get externalFiles => 'Pliki zewnętrzne';

  @override
  String get extract => 'Wyodrębnij';

  @override
  String get extractAllColorPalettes => 'Wyodrębnij wszystkie palety kolorów';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Wyodrębnić pozostałe $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Wyodrębnij wykonawcę feat. z tytułu';

  @override
  String get extractFeatArtistSubtitle => 'Wyodrębnij (feat. X) i (ft. X) wykonawców jako wpis nowy wykonawca.';

  @override
  String get extractingInfo => 'Wyodrębnianie informacji';

  @override
  String get extras => 'Dodatkowe';

  @override
  String get extrasSubtitle => 'Dodatkowe ustawienia, które udoskonalą Twoje wrażenia';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Niepowodzenie';

  @override
  String get failedEdits => 'Nieudane edycje';

  @override
  String get favourites => 'Ulubione';

  @override
  String get features => 'Funkcje';

  @override
  String get fetching => 'Pobieranie';

  @override
  String get fetchingOfAllVideos => 'Pobieranie wszystkich filmów';

  @override
  String get file => 'Plik';

  @override
  String get fileAlreadyExists => 'Plik już istnieje';

  @override
  String get fileBasedServerWarning =>
      'Pliki zostaną tymczasowo pobrane w celu zindeksowania. Upewnij się, że twoje połączenie jest stabilne. \nZaleca się skorzystanie z Wi-Fi, aby uniknąć dużego zużycia danych.';

  @override
  String get fileName => 'Nazwa pliku';

  @override
  String get fileNameWoExt => 'Nazwa pliku bez rozszerzenia';

  @override
  String get filenameShouldntStartWith => 'Nazwa pliku nie powinna zaczynać się od';

  @override
  String get files => 'Pliki';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Filtruj albumy';

  @override
  String get filterArtists => 'Filtruj wykonawców';

  @override
  String get filterGenres => 'Filtruj gatunki';

  @override
  String get filterPlaylists => 'Filtruj playlisty';

  @override
  String get filterTracks => 'Filtruj utwory';

  @override
  String get filterTracksBy => 'Filtruj utwory na listach wyszukiwania według';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Filtrowane utwory według rozmiaru i czasu trwania';

  @override
  String get finished => 'Ukończono';

  @override
  String get finishedUpdatingLibrary => 'Ukończono aktualizowanie biblioteki';

  @override
  String get firstListen => 'Pierwsze odsłuchanie';

  @override
  String get fixYtdlpBigThumbnailSize => 'Napraw duży rozmiar miniatury yt-dlp';

  @override
  String get floatingActionButton => 'Pływający przycisk akcji';

  @override
  String get folder => 'Folder';

  @override
  String get folderName => 'Nazwa folderu';

  @override
  String get folders => 'Foldery';

  @override
  String get fontScale => 'Skala czcionki';

  @override
  String get forceMiniplayerFollowTrackColors => 'Wymuś, aby miniodtwarzacz podążał za kolorami utworów';

  @override
  String get forceSquaredAlbumThumbnail => 'Wymuś kwadratową miniaturę albumu';

  @override
  String get forceSquaredThumbnailNote => 'Rozmiar miniatury i wysokość kafelka NIE są równe. Kwadratowy wygląd nie będzie zgodny z oczekiwaniami. Czy chcesz, aby były równe?';

  @override
  String get forceSquaredTrackThumbnail => 'Wymuś kwadratową miniaturę utworu';

  @override
  String get forceStopColorPaletteGeneration => 'Wymusić zatrzymanie wyodrębniania palet kolorów? Możesz kontynuować to później';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Pełny ekran';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Generuj';

  @override
  String get generateFromDates => 'Zakres czasu';

  @override
  String get generateFromDatesSubtitle => 'Generuj utwory, których słuchałeś w określonym przedziale czasowym';

  @override
  String get generateRandomPlaylist => 'Wygeneruj losową playlistę';

  @override
  String get genre => 'Gatunek';

  @override
  String get genres => 'Gatunki';

  @override
  String get goToAlbum => 'Przejdź do albumu';

  @override
  String get goToArtist => 'Przejdź do wykonawcy';

  @override
  String get goToChannel => 'Przejdź do kanału';

  @override
  String get goToFolder => 'Przejdź do folderu';

  @override
  String get goodLooking => 'Dobrze wyglądający';

  @override
  String get grantStoragePermission => 'Przyznaj uprawnienie dostępu do pamięci';

  @override
  String get group => 'Grupa';

  @override
  String get groupArtworksByAlbum => 'Grupuj okładki według albumu';

  @override
  String get guide => 'Przewodnik';

  @override
  String get hapticFeedback => 'Wibracje haptyczne';

  @override
  String get heightOfAlbumTile => 'Wysokość kafelka albumu';

  @override
  String get heightOfTrackTile => 'Wysokość kafelka utworu';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Wysokie dopasowanie';

  @override
  String get highPerformance => 'Wysoka wydajność';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Historia';

  @override
  String get historyImportMissingEntriesNote => 'Tych wpisów nie można znaleźć w bibliotece. Jeśli uważasz, że istnieją, rozważ dodanie ich ręcznie';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString odsłuchań $oldTrackInfo zostanie zastąpionych przez $newTrackInfo, potwierdzasz?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Główna';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'Format 12-godzinny';

  @override
  String get hours => 'Godziny';

  @override
  String get iReadAndAgree => 'Przeczytałem i zgadzam się';

  @override
  String get ifNotPlaying => 'Jeśli nieodtwarzane';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Pobierania mogą zostać ograniczone, gdy aplikacja ma ograniczone korzystanie z baterii';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignoruj często używane prefiksy podczas sortowania';

  @override
  String get ignores => 'Ignorowane';

  @override
  String get imageSource => 'Źródło obrazu';

  @override
  String get immersiveMode => 'Tryb pełnego ekranu';

  @override
  String get immersiveModeSubtitle => 'Ukryj paski stanu i nawigacji, gdy miniodtwarzacz jest rozszerzony';

  @override
  String get import => 'Importuj';

  @override
  String get importAll => 'Importuj wszystko';

  @override
  String get importLastFmHistory => 'Importuj historię LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Przejdź do $lastfmCsvLink\n\n2. Wpisz swoją nazwę użytkownika, pobierz i pobierz plik CSV.\n\n3. Wybierz plik na następnym ekranie.';
  }

  @override
  String get importTimeRange => 'Importuj zakres czasu';

  @override
  String get importYoutubeHistory => 'Importuj historię YouTube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Przejdź do $takeoutLink\n\n2. Naciśnij \"Wiele formatów\" i obok \"Historia\" wybierz \"JSON\".\n\n3. Naciśnij \"Wszystkie dane Youtube\", odznacz Wszystko i wybierz tylko historię.\n\n4. Utwórz eksport, pobierz i rozpakuj.\n\n5. Na następnym ekranie wybierz \"watch-history.json\".';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Pomyślnie zaimportowano kanały $numberString',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Pomyślnie zaimportowano playlisty $numberText',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Zawrzyj wideo';

  @override
  String get indexRefreshRequired => 'Odśwież po zmianie tego';

  @override
  String get indexer => 'Indeksator';

  @override
  String get indexerNote => 'Notatka: Niekompletna liczba okładek odnosi się do zduplikowanych i nieznalezionych okładek';

  @override
  String get indexerSubtitle => 'Zarządzaj swoją biblioteką muzyczną';

  @override
  String get infinityQueueOnNextPrev => 'Nieskończona kolejka na Następny/Poprzedni';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'naciśnięcie przycisku Następny podczas odtwarzania ostatniej pozycji spowoduje przejście do pierwszej i odwrotnie';

  @override
  String get info => 'Informacje';

  @override
  String get inserted => 'wstawione';

  @override
  String get instantlyApplies => 'Natychmiastowe zastosowanie';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Wybór odwrotny';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Element';

  @override
  String get jump => 'Skok';

  @override
  String get jumpToDay => 'Skocz do dnia';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Skocz do pierwszego utworu po zakończeniu kolejki';

  @override
  String get keepCachedVersions => 'Zachowaj wersje z pamięci podręcznej';

  @override
  String get keepFileDates => 'Zachowaj daty plików';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniodtwarzacz jest rozszerzony';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniodtwarzacz jest rozszerzony i odtwarzane jest wideo';

  @override
  String get keepScreenAwakeNone => 'Nie wybudzaj ekranu';

  @override
  String get keepScreenAwakeWhen => 'Utrzymuj ekran włączony, gdy';

  @override
  String get killPlayerAfterDismissingApp => 'Zamknij odtwarzacz po odrzuceniu aplikacji';

  @override
  String get language => 'Język';

  @override
  String get learnMore => 'Dowiedz się więcej';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Karty biblioteki';

  @override
  String get libraryTabsReorder => 'Możesz zmienić kolejność aktywowanych kart.';

  @override
  String get license => 'Licencja';

  @override
  String get licenseSubtitle => 'Licencje i umowy używane przez Namidę';

  @override
  String get like => 'Lubię to';

  @override
  String get liked => 'Polubiono';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Lista folderów';

  @override
  String get loadAll => 'Załaduj wszystko';

  @override
  String get loadingFile => 'Ładowanie pliku';

  @override
  String get local => 'Lokalnie';

  @override
  String get localVideoMatching => 'Lokalne dopasowanie wideo';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Przytrzymaj tekst utworu, aby wejść w tryb pełnego ekranu';

  @override
  String get lostMemories => 'Zagubione wspomnienia';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'mniej więcej o tej porze, $numberString lat temu',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Wzmacniacz głośności';

  @override
  String get lyricist => 'Twórca tekstu';

  @override
  String get lyrics => 'Tekst';

  @override
  String get lyricsSource => 'Źródło tekstu';

  @override
  String get m3uPlaylist => 'Playlista M3U';

  @override
  String get makeYourFirstListen => 'Posłuchaj po raz pierwszy!';

  @override
  String get manage => 'Zarządzaj';

  @override
  String get manageYourAccounts => 'Zarządzaj swoimi kontami';

  @override
  String get manualBackup => 'Ręcznie';

  @override
  String get manualBackupSubtitle => 'wybierz konkretny plik';

  @override
  String get markAsRead => 'Oznacz jako przeczytane';

  @override
  String get matchAllTracks => 'Dopasuj wszystkie utwory';

  @override
  String get matchAllTracksNote => 'może to mieć wpływ na prędkość dopasowywania, ponieważ zostaną sprawdzone wszystkie utwory w Twojej bibliotece';

  @override
  String get matchingType => 'Typ dopasowania';

  @override
  String get maxAudioCacheSize => 'Maksymalny rozmiar pamięci podręcznej audio';

  @override
  String get maxImageCacheSize => 'Maksymalny rozmiar pamięci podręcznej obrazu';

  @override
  String get maxVideoCacheSize => 'Maksymalny rozmiar pamięci podręcznej wideo';

  @override
  String get maximum => 'Maksymalny';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Sklep z mediami jest włączony, nie przyniesie to żadnego efektu';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Kod';

  @override
  String get membershipCodeSentToEmail => 'Kod wysłany na Twój e-mail';

  @override
  String get membershipDidntChange => 'Członkostwo nie uległo zmianie';

  @override
  String get membershipEnjoyNew => 'Ciesz się nowym członkostwem';

  @override
  String get membershipFreeCoupon => 'Darmowy kupon';

  @override
  String get membershipManage => 'Zarządzaj swoim członkostwem';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Nie znaleziono subskrypcji dla tego użytkownika';

  @override
  String get membershipSignInToPatreonAccount => 'Zaloguj się na swoje konto Patreon';

  @override
  String get membershipUnknown => 'Nieznane członkostwo';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Aby dodać wiele kont, musisz mieć członkostwo $name1 lub $name2';
  }

  @override
  String get merge => 'Złącz';

  @override
  String get metadataCache => 'Pamięć podręczna metadanych';

  @override
  String get metadataEditFailed => 'Nie udało się edytować metadanych';

  @override
  String get metadataReadFailed => 'Nie udało się odczytać metadanych';

  @override
  String get minFileDuration => 'Minimalny czas trwania utworu';

  @override
  String get minFileSize => 'Minimalny rozmiar pliku';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimalny czas trwania utworu potrzebny do przywrócenia ostatnio odtwarzanej pozycji';

  @override
  String get minValueCantBeMoreThanMax => 'Wartość minimalna nie może być większa niż maksymalna';

  @override
  String get minValueToCountTrackListen => 'Licz odsłuchania po: ';

  @override
  String get minimizedMiniplayer => 'Zminimalizowany miniodtwarzacz';

  @override
  String get minimum => 'Minimalny';

  @override
  String get minimumOneFolderSubtitle => 'Powinien istnieć co najmniej 1 folder. Dodaj więcej folderów, jeśli chcesz usunąć ten';

  @override
  String get minimumOneItem => 'Nie udało się usunąć elementu';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Powinno pozostać co najmniej $numberString elementów',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Dostosowanie miniodtwarzacza';

  @override
  String get minutes => 'minut';

  @override
  String get missingEntries => 'Brakujące wpisy';

  @override
  String get missingTracks => 'Brakujące utwory';

  @override
  String get mix => 'Miks';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Miks playlist wygenerowany przez YouTube';

  @override
  String get mixes => 'Mixy';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Miesiąc';

  @override
  String get months => 'Miesiące';

  @override
  String get mood => 'Nastrój';

  @override
  String get moods => 'Nastroje';

  @override
  String get more => 'Więcej';

  @override
  String get mostPlayed => 'Najczęściej odtwarzane';

  @override
  String get multipleTracksTagsEditNote => 'Zaraz zedytujesz te utwory,\nNiezmienione pola pozostaną nietknięte.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Nazwa';

  @override
  String get nameContainsBadCharacter => 'Nazwa zawiera zły znak';

  @override
  String get never => 'Nigdy';

  @override
  String get newDirectory => 'Nowy katalog';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Dodaj utwory';

  @override
  String get newTracksMoods => 'Nastrój';

  @override
  String get newTracksMoodsSubtitle => 'Generuj utwory w oparciu o dostępne nastroje';

  @override
  String get newTracksRandom => 'Losowo';

  @override
  String get newTracksRandomSubtitle => 'Wybieraj losowe utwory ze swojej biblioteki';

  @override
  String get newTracksRatings => 'Oceny';

  @override
  String get newTracksRatingsSubtitle => 'Generuj utwory, które mają określoną ocenę';

  @override
  String get newTracksRecommended => 'Polecane';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Generuj utwory, których zwykle słuchałeś z $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Podobna data wydania';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Generuj utwory, które zostały wydane mniej więcej w tym samym czasie co $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Utwór ma nieznany rok';

  @override
  String get newest => 'Najnowsze';

  @override
  String get next => 'Następny';

  @override
  String get no => 'nie';

  @override
  String get noChangesFound => 'Nie znaleziono żadnych zmian.';

  @override
  String get noEnoughTracks => 'Nie masz zbyt wielu utworów..';

  @override
  String get noExcludedFolders => 'Nie masz żadnych wykluczonych folderów';

  @override
  String get noFolderChosen => 'Nie wybrałeś żadnego folderu';

  @override
  String get noMoodsAvailable => 'Brak dostępnych nastrojów';

  @override
  String get noNetworkAvailableToFetchData => 'Brak sieci do pobrania danych';

  @override
  String get noTracksFound => 'Nie znaleziono żadnych utworów';

  @override
  String get noTracksFoundBetweenDates => 'W tym przedziale czasowym nie ma żadnych utworów.';

  @override
  String get noTracksFoundInDirectory => 'Nie znaleziono utworów w tym katalogu';

  @override
  String get noTracksInHistory => 'Nie masz wystarczającej liczby utworów w historii';

  @override
  String get nonActive => 'Nieaktywny';

  @override
  String get nonFavourites => 'Nieulubione';

  @override
  String get none => 'Brak';

  @override
  String get normalizeAudio => 'Normalizuj dźwięk';

  @override
  String get normalizeAudioSubtitle => 'Normalizuje głośność poprzez czytanie tagu replay gain lub informacji pobranych z YouTube';

  @override
  String get notAvailableForYourDevice => 'Niedostępne na twoim urządzeniu';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Notatka';

  @override
  String get notification => 'Powiadomienie';

  @override
  String get notifications => 'Powiadomienia';

  @override
  String get numberOfTracks => 'Liczba utworów';

  @override
  String get ofLabel => 'z';

  @override
  String get offlineSearch => 'Wyszukiwanie offline';

  @override
  String get offset => 'Przesunięcie';

  @override
  String get oldDirectory => 'Stary katalog';

  @override
  String get oldDirectoryStillHasTracks => 'W starym katalogu wciąż znajdują się jakieś utwory, potwierdzasz?';

  @override
  String get oldestWatch => 'Najpóźniej oglądane';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Przy przerwaniu';

  @override
  String get onNotificationTap => 'Przy kliknięciu powiadomienia';

  @override
  String get onOpeningYoutubeLink => 'Przy otwarciu linku YouTube';

  @override
  String get onSwiping => 'Z Przesunięciem';

  @override
  String get onVolumeZero => 'Przy głośności 0';

  @override
  String get ongoing => 'Trwające';

  @override
  String get open => 'Otwórz';

  @override
  String get openApp => 'Otwórz aplikację';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Otwórz w Youtube';

  @override
  String get openMiniplayer => 'Otwórz miniodtwarzacz';

  @override
  String get openQueue => 'Otwórz kolejkę';

  @override
  String get openYoutubeLink => 'Otwórz link YouTube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operacja $name wymaga konta. Zaloguj się, aby kontynuować';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operacja $operation wymaga co najmniej członkostwa $name';
  }

  @override
  String get or => 'lub';

  @override
  String get others => 'Inne';

  @override
  String get output => 'Wyjście';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Zastąp stare pliki w tym samym folderze';

  @override
  String get palette => 'Paleta';

  @override
  String get paletteMix => 'Miks';

  @override
  String get paletteNewMix => 'Nowy mix';

  @override
  String get paletteSelectedMix => 'Wybrany mix';

  @override
  String get parallelDownloads => 'Pobieranie równoległe';

  @override
  String get parsed => 'przeanalizowane';

  @override
  String get password => 'Password';

  @override
  String get path => 'Pełna ścieżka pliku';

  @override
  String get pause => 'Pauza';

  @override
  String get pauseFadeDuration => 'Czas trwania zanikania';

  @override
  String get pausePlayback => 'Wstrzymaj odtwarzanie';

  @override
  String get percentage => 'Procent';

  @override
  String get performanceMode => 'Tryb wydajności';

  @override
  String get performanceNote => 'Może mieć wpływ na wydajność';

  @override
  String get personalized => 'Spersonalizowane';

  @override
  String get personalizedRelatedVideos => 'Spersonalizowane powiązane filmy';

  @override
  String get personalizedRelatedVideosSubtitle => 'Wyłączenie tego zwiększy zużycie danych';

  @override
  String get pickColorsFromDeviceWallpaper => 'Wybierz kolory z tapety urządzenia';

  @override
  String get pickFromStorage => 'Wybierz z pamięci';

  @override
  String get pinned => 'Przypięte';

  @override
  String get pitch => 'Tonacja';

  @override
  String get plain => 'Prosty';

  @override
  String get play => 'Odtwarzaj';

  @override
  String get playAfter => 'Odtwórz po';

  @override
  String get playAfterNextPrev => 'Automatyczne odtwarzanie na Następny/Poprzedni';

  @override
  String get playAll => 'Odtwórz wszystko';

  @override
  String get playFadeDuration => 'Czas trwania zanikania';

  @override
  String get playLast => 'Odtwórz ostatnie';

  @override
  String get playNext => 'Odtwórz następne';

  @override
  String get playbackSetting => 'Odtwarzanie';

  @override
  String get playbackSettingSubtitle => 'Dostęp można uzyskać bezpośrednio w odtwarzaczu, naciskając i przytrzymując przycisk audio';

  @override
  String get playlist => 'Playlista';

  @override
  String get playlists => 'Playlisty';

  @override
  String get playlistsImportM3uNative => 'Spowoduje to zaimportowanie playlist M3U do użytku tylko przez Namidę. Użyj, jeśli przeprowadzasz migrację';

  @override
  String get playlistsImportM3uSynced =>
      'Spowoduje to automatyczne zaimportowanie playlist M3U z folderów indeksujących i zsynchronizowanie ich z oryginalnym plikiem M3U. Włącz, jeśli uzyskujesz dostęp do list odtwarzania z innych aplikacji lub je modyfikujesz';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Automatycznie importuj playlisty M3U';

  @override
  String get pleaseEnterADifferentName => 'Ta nazwa już istnieje :(\nSpróbuj innej wymyślnej nazwy';

  @override
  String get pleaseEnterALink => 'Proszę wprowadzić link';

  @override
  String get pleaseEnterALinkSubtitle => 'Hmm.. czy to jest link do YouTube?';

  @override
  String get pleaseEnterAName => 'Proszę wpisać nazwę';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Zapobiegaj duplikowaniu utworów';

  @override
  String get preventDuplicatedTracksSubtitle => 'Używa nazwy pliku do jednoznacznej identyfikacji utworów';

  @override
  String get preview => 'Podgląd';

  @override
  String get previous => 'Poprzedni';

  @override
  String get previousButtonReplays => 'Powtórzenie przez wciśnięcie przycisku poprzedni';

  @override
  String get previousButtonReplaysSubtitle => 'jeśli zostanie naciśnięty, gdy aktualna pozycja będzie dłuższa niż czas trwania wyszukiwania';

  @override
  String get prioritizeEmbeddedLyrics => 'Nadaj priorytet osadzonym tekstom';

  @override
  String get priority => 'Priorytet';

  @override
  String get private => 'Prywatny';

  @override
  String get progress => 'Postęp';

  @override
  String get promptToChangeTrackPath => 'Zwykle dzieje się tak, gdy usuniesz/przeniesiesz/zmienisz nazwę pliku poza namida. Czy chcesz zaktualizować aktualną ścieżkę?';

  @override
  String get public => 'Publiczny';

  @override
  String get queue => 'Kolejka';

  @override
  String get queues => 'Kolejki';

  @override
  String get random => 'Losowo';

  @override
  String get randomPicks => 'Losowe wybory';

  @override
  String get rating => 'Ocena';

  @override
  String get reIndex => 'Ponowne indeksowanie';

  @override
  String get reIndexSubtitle => 'Odbuduj swoją bibliotekę muzyczną od podstaw';

  @override
  String get reIndexWarning => 'Ten proces może zająć trochę czasu, w zależności od rozmiaru biblioteki.\n\nOkładki nie będą ponownie indeksowane, dopóki nadal istnieją';

  @override
  String get recentAlbums => 'Ostatnie albumy';

  @override
  String get recentArtists => 'Ostatni wykonawcy';

  @override
  String get recentListens => 'Ostatnio odsłuchane';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Ostatnio dodane';

  @override
  String get recordLabel => 'Wytwórnia';

  @override
  String get refresh => 'Odśwież';

  @override
  String get refreshLibrary => 'Odśwież bibliotekę';

  @override
  String get refreshLibrarySubtitle => 'Sprawdź, czy nie ma nowo dodanej lub usuniętej muzyki';

  @override
  String get refreshOnStartup => 'Odśwież przy uruchomieniu';

  @override
  String get relatedVideos => 'Powiązane filmy';

  @override
  String get rememberAudioOnlyMode => 'Zapamiętaj tryb tylko audio';

  @override
  String get remixer => 'Twórca remixu';

  @override
  String get remove => 'Usuń';

  @override
  String get removeDuplicates => 'Usuń duplikaty';

  @override
  String get removeFromFavourites => 'Usuń z ulubionych';

  @override
  String get removeFromLibrary => 'Usuń z biblioteki';

  @override
  String get removeFromPlaylist => 'Usuń z playlisty';

  @override
  String get removeQueue => 'Usuń kolejkę';

  @override
  String get removeSourceFromHistory => 'Usuń źródło z historii';

  @override
  String get removeWhitespaces => 'Usuń spacje';

  @override
  String get removed => 'Usunięto';

  @override
  String get rename => 'Zmień nazwę';

  @override
  String get renamePlaylist => 'Zmień nazwę playlisty';

  @override
  String get reorderable => 'Możliwość zmiany kolejności';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Powtórz dla $number więcej razy',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Tryb powtarzania';

  @override
  String get repeatModeAll => 'Powtórz całą kolejkę';

  @override
  String get repeatModeNone => 'Zatrzymaj się na ostatnim utworze';

  @override
  String get repeatModeOne => 'Powtórz aktualny utwór';

  @override
  String get replaceAllListensWithAnotherTrack => 'Zamień wszystkie odsłuchania na inny utwór';

  @override
  String get replies => 'Odpowiedzi';

  @override
  String get reply => 'Odpowiedź';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Wymaga wyczyszczenia pamięci podręcznej obrazów i ponownego indeksowania';

  @override
  String get rescanVideos => 'Przeskanuj ponownie widea';

  @override
  String get resetBrightness => 'Zresetuj jasność';

  @override
  String get resetToDefault => 'Ustaw na';

  @override
  String get respectNoMedia => 'Respektuj .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Nie uwzględniaj folderów zawierających .nomedia';

  @override
  String get restart => 'Uruchom ponownie';

  @override
  String get restoreBackup => 'Przywróć kopię zapasową';

  @override
  String get restoreDefaults => 'Przywróć domyślne';

  @override
  String get restoredBackupSuccessfully => 'Przywracanie kopii zapasowej';

  @override
  String get restoredBackupSuccessfullySub => 'Plik kopii zapasowej został pomyślnie przywrócony';

  @override
  String get resume => 'Kontynuuj';

  @override
  String get resumeIfWasInterrupted => 'Wznów, jeśli zostało wstrzymane z powodu przerwania';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Wznów, jeśli zostało wstrzymane ze względu na głośność';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Wznów, jeśli wstrzymano na mniej niż $numberString minut',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Odwrotna kolejność';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Dzwonek';

  @override
  String get sameDirectoryOnly => 'Tylko ten sam katalog';

  @override
  String get sample => 'Próbka';

  @override
  String get sampleRate => 'Częstotliwość próbkowania';

  @override
  String get save => 'Zapisz';

  @override
  String get saveToLibrary => 'Zapisz w bibliotece';

  @override
  String get savedIn => 'Zapisano w';

  @override
  String get scaleMultiplier => 'Mnożnik skali';

  @override
  String get search => 'Wyszukaj';

  @override
  String get searchYoutube => 'Wyszukaj w YouTube';

  @override
  String get seconds => 'sekund';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Czas trwania wyszukiwania';

  @override
  String get seekDurationInfo => 'Możesz dotknąć aktualnego czasu trwania, aby przeszukać do tyłu i całkowitego czasu trwania, aby przeszukać do przodu';

  @override
  String get seekbar => 'Pasek wyszukiwania';

  @override
  String get selectAll => 'Wybierz wszystko';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Wybierz pliki, które już znajdują się w lokalnej bibliotece';

  @override
  String get selectedTracks => 'Wybrane utwory';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Te słowa nie zostaną rozdzielone';

  @override
  String get separatorsMessage => 'Nie ma potrzeby wstawiania spacji, chyba że chcesz użyć litery/symbolu, który można znaleźć w całym słowie (np. x i ft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Ustaw jako';

  @override
  String get setAsDefault => 'Ustaw jako domyślne';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Ustaw plik ostatniej modyfikacji jako datę przesłania wideo';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Ustaw nastroje';

  @override
  String get setMoodsSubtitle => 'Aby je rozdzielić, użyj przecinków (,)';

  @override
  String get setRating => 'Ustaw ocenę';

  @override
  String get setTags => 'Ustaw tagi';

  @override
  String get setYoutubeLink => 'Ustaw link YouTube';

  @override
  String get settings => 'Ustawienia';

  @override
  String get setupFirstStartup => 'Skonfiguruj pierwsze uruchomienie';

  @override
  String get share => 'Udostepnij';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Skróty';

  @override
  String get shouldDuck => 'Powinien zmniejszyć głośność';

  @override
  String get shouldDuckNote => 'Wskazuje, że należy zmniejszyć głośność. np. powiadomienie';

  @override
  String get shouldPause => 'Powinien wstrzymać';

  @override
  String get shouldPauseNote => 'Wskazuje, że odtwarzanie powinno zostać wstrzymane. np.: połączenia';

  @override
  String get showAll => 'Pokaż wszystkie';

  @override
  String get showChannelWatermarkInFullscreen => 'Pokaż znak wodny kanału na pełnym ekranie';

  @override
  String get showFailedOnly => 'Pokaż tylko nieudane';

  @override
  String get showHideUnknownFields => 'Pokaż/ukryj nieznane pola';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Pokaż miksy w';

  @override
  String get showMore => 'Pokaż więcej';

  @override
  String get showShortVideosIn => 'Pokaż shorty w';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'Pokaż plansze końcowe fimu';

  @override
  String get showWebm => 'Pokaż webm';

  @override
  String get shuffle => 'Losowo';

  @override
  String get shuffleAll => 'Losowo wszystko';

  @override
  String get shuffleNext => 'Następny losowo';

  @override
  String get signIn => 'Zaloguj się';

  @override
  String get signInCanceled => 'Logowanie zostało anulowane';

  @override
  String get signInFailed => 'Logowanie nie powiodło się';

  @override
  String get signInToYourAccount => 'Zaloguj się na swoje konto';

  @override
  String get signInYouDontHaveAccount => 'Nie masz żadnego zalogowanego konta';

  @override
  String get signInYouNeedAccountToViewPage => 'Aby wyświetlić tę stronę, potrzebujesz konta';

  @override
  String get signOut => 'Wyloguj się';

  @override
  String signOutFromName({required String name}) {
    return 'Wyloguj się z $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Zalogowanie umożliwia podstawowe korzystanie';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Uzyskaj wcześniejszy dostęp za pośrednictwem Patreon lub korzystając z kuponu';

  @override
  String get similarDiscoverDate => 'Podobna data odnalezienia';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generuj utwory, które zostały odnalezione w tym samym czasie, co $currentTrack';
  }

  @override
  String get similarTimeRange => 'Podobny przedział czasowy';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generuj odsłuchane w tym samym czasie utwory, co $currentTrack';
  }

  @override
  String get singles => 'Single';

  @override
  String get size => 'Rozmiar';

  @override
  String get skip => 'Pomiń';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Pomiń ciszę';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Wyłącz po';

  @override
  String get sleepTimer => 'Wyłącznik czasowy';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Sortuj według';

  @override
  String get source => 'Źródło';

  @override
  String get speed => 'Prędkość';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Przesunięty widok siatki albumu';

  @override
  String get start => 'Start';

  @override
  String get stats => 'Statystyki';

  @override
  String get statsSubtitle => 'Oto kilka informacji o Twojej bibliotece';

  @override
  String get stop => 'Zatrzymaj';

  @override
  String get stopAfterThisTrack => 'Zatrzymaj po tym utworze';

  @override
  String get stopAfterThisVideo => 'Zatrzymaj po tym wideo';

  @override
  String get storagePermissionDenied => 'Odmowa uprawnienia';

  @override
  String get storagePermissionDeniedSubtitle => 'Zezwól na dostęp, aby móc wykonać tę akcję';

  @override
  String get stretchLyricsDuration => 'Rozciągnij długość tekstu';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Subskrybuj';

  @override
  String get subscribed => 'Zasubskrybowano';

  @override
  String get subscriber => 'Subskrybent';

  @override
  String get subscribers => 'Subskrybenci';

  @override
  String get succeeded => 'Pomyślnie';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Wsparcie';

  @override
  String get supremacy => 'Supremacja';

  @override
  String get sussyBaka => 'No cóż, brak utworów';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Przesuń, aby otworzyć szufladę';

  @override
  String get synced => 'Zsynchronizowano';

  @override
  String get synopsis => 'Streszczenie';

  @override
  String get tagFields => 'Pola tagów';

  @override
  String get tags => 'Tagi';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Dotknij, aby wyszukać';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Tryb motywu';

  @override
  String get themeModeDark => 'Ciemny';

  @override
  String get themeModeLight => 'Jasny';

  @override
  String get themeModeSystem => 'System';

  @override
  String get themeSettings => 'Motyw';

  @override
  String get themeSettingsSubtitle => 'Ogólny klimat Twojego odtwarzacza';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Ta playlista ma aktywne sortowniki, wyłącz je przed zmianą kolejności.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Ten film najpewniej został usunięty lub ustawiony na prywatny.';

  @override
  String get thumbnails => 'Miniatury';

  @override
  String get title => 'Tytuł';

  @override
  String get top => 'Top';

  @override
  String get topComments => 'Najlepsze komentarze';

  @override
  String get topCommentsSubtitle => 'Wyświetlaj komentarze na górze zamiast na dole';

  @override
  String get topRecentAlbums => 'Najlepsze ostatnie albumy';

  @override
  String get topRecentArtists => 'Najlepsi ostatni wykonawcy';

  @override
  String get topRecents => 'Najlepsze ostatnie';

  @override
  String get totalListenTime => 'Łączny czas słuchania';

  @override
  String get totalListens => 'Łącznie odsłuchań';

  @override
  String get totalTracks => 'Łącznie utworów';

  @override
  String get totalTracksDuration => 'Łączny czas trwania utworów';

  @override
  String get track => 'Utwór';

  @override
  String get trackArtistsSeparator => 'Separatory wykonawców';

  @override
  String get trackGenresSeparator => 'Separatory gatunków';

  @override
  String get trackInfo => 'Informacje o utworze';

  @override
  String get trackNotFound => 'Nie znaleziono utworu';

  @override
  String get trackNumber => 'Numer utworu';

  @override
  String get trackNumberTotal => 'Łącznie utworów';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Stara nazwa: \"$oldName\"\n\nNowa nazwa: \"$newName\"\n\nJesteś pewny?';
  }

  @override
  String get trackPlayMode => 'Tryb odtwarzania';

  @override
  String get trackPlayModeSearchResults => 'Wyniki wyszukiwania';

  @override
  String get trackPlayModeSelectedOnly => 'Tylko wybrany utwór';

  @override
  String get trackPlayModeTrackAlbum => 'Album utworu';

  @override
  String get trackPlayModeTrackArtist => 'Główny wykonawca utworu';

  @override
  String get trackPlayModeTrackGenre => 'Gatunek utworu';

  @override
  String get trackThumbnailSizeInList => 'Rozmiar miniatury utworu';

  @override
  String get trackTileCustomization => 'Dostosowanie kafelka utworu';

  @override
  String get trackTileItemsSeparator => 'Separator elementów';

  @override
  String get tracks => 'Utwory';

  @override
  String get tracksExcludedByNomedia => 'Utwory wykluczone przez .nomedia';

  @override
  String get tracksInfo => 'Informacje o utworach';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Cofnij';

  @override
  String get undoChanges => 'Cofnąć zmiany?';

  @override
  String get undoChangesDeletedPlaylist => 'Cofnij usunięta playlistę';

  @override
  String get undoChangesDeletedQueue => 'Cofnij usuniętą kolejkę';

  @override
  String get undoChangesDeletedTrack => 'Cofnij usunięty utwór';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Nielimitowany';

  @override
  String get unlisted => 'Niekatalogowany';

  @override
  String get unlock => 'Odblokuj';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Aktualizuj';

  @override
  String get updateDirectoryPath => 'Zaktualizuj ścieżkę katalogu';

  @override
  String get updateMissingTracksOnly => 'Zaktualizuj tylko brakujące utwory';

  @override
  String get updating => 'Aktualizowanie';

  @override
  String get useCollapsedSettingTiles => 'Użyj zwiniętych kafelków ustawień';

  @override
  String get useMediaStore => 'Użyj pamięci multimediów';

  @override
  String get useMediaStoreSubtitle =>
      '✓ natychmiastowy czas indeksowania\nx respektuj .nomedia zostanie wymuszono włączone\nx będzie brakować niektórych tagów metadanych\nx Integracja YouTube z lokalną biblioteką nie będzie działać';

  @override
  String get usePitchBlack => 'Użyj Pitch Black';

  @override
  String get usePitchBlackSubtitle => 'Przydatne dla ekranów AMOLED i wygląda fajniej';

  @override
  String get used => 'W użyciu';

  @override
  String get value => 'Wartość';

  @override
  String get valueBetween50200 => 'Wartość powinna mieścić się w przedziale od 50% do 200%';

  @override
  String get vibration => 'Wibracje';

  @override
  String get vibrationType => 'Typ wibracji';

  @override
  String get video => 'Wideo';

  @override
  String get videoCache => 'Pamięć podręczna wideo';

  @override
  String get videoCacheFile => 'Plik wideo z pamięci podręcznej';

  @override
  String get videoCacheFiles => 'Pliki wideo z pamięci podręcznej';

  @override
  String get videoOnly => 'Tylko wideo';

  @override
  String get videoPlaybackSource => 'Źródło wideo';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Dzięki temu priorytet będą miały lokalne wideo. Jeśli nie zostaną znalezione, zostaną pobrane z YouTube';

  @override
  String get videoPlaybackSourceLocal => 'Lokalne wideo';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nWideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Sprawdza, czy dowolny plik wideo (znaleziony na liście wybranych folderów) ma nazwę pliku zawierającą nazwę pliku utworu';

  @override
  String get videoPlaybackSourceYoutube => 'Z YouTube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Sprawdza nazwę pliku utworu i komentarz pod kątem pasującego linku do YouTube, filmy są zapisywane w pamięci podręcznej do późniejszego wykorzystania.';

  @override
  String get videoQuality => 'Jakość wideo';

  @override
  String get videoQualitySubtitle => 'Wybrana zostanie najwyższa dostępna jakość.';

  @override
  String get videoQualitySubtitleNote => 'Zawsze dobrze jest mieć więcej opcji, jeśli jakość nie zostanie znaleziona, w przeciwnym razie powróci do najniższej jakości';

  @override
  String get videos => 'Widea';

  @override
  String get view => 'Podgląd';

  @override
  String get viewAll => 'Pokaż wszystko';

  @override
  String get views => 'Wyświetlenia';

  @override
  String get volume => 'Głośność';

  @override
  String get warning => 'Ostrzeżenie';

  @override
  String get waveformBarsCount => 'Liczba słupków kształtu fali';

  @override
  String get webmNoEditTagsSupport => 'Format WEBM nie obsługuje edycji tagów';

  @override
  String get week => 'Tydzień';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Rok';

  @override
  String get yes => 'tak';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Twoje obecne członkostwo to $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Twoja niestandardowa kolejność zostanie utracona, Czy jesteś pewien?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Music';

  @override
  String get youtubeSettingsSubtitle => 'Dostosuj doświadczenie YouTube';

  @override
  String get youtubeStyleMiniplayer => 'Miniodtwarzacz w stylu Youtube';

  @override
  String get ytPreferNewComments => 'Jeśli to możliwe, preferuj nowe komentarze';

  @override
  String get ytPreferNewCommentsSubtitle => 'Wersja z pamięci podręcznej będzie używana tylko w przypadku braku połączenia';
}
