// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Esperanto (`eo`).
class AppLocalizationsEo extends AppLocalizations {
  AppLocalizationsEo([String locale = 'eo']) : super(locale);

  @override
  String get about => 'Pri';

  @override
  String get active => 'Aktiva';

  @override
  String get add => 'Aldoni';

  @override
  String get addAccount => 'Aldoni konton';

  @override
  String get addAll => 'Aldoni ĉion';

  @override
  String get addAllAndRemoveOldOnes => 'Aldoni ĉion kaj forigi malnovajn';

  @override
  String get addAsANewPlaylist => 'Aldoni kiel novan ludliston';

  @override
  String get addAudioToLocalLibrary => 'Aldoni aŭdion al loka biblioteko';

  @override
  String get addFolder => 'Aldoni dosierujon';

  @override
  String get addLanguage => 'Aldoni lingvon';

  @override
  String get addLanguageSubtitle => 'Helpu traduki Namida al via propra lingvo';

  @override
  String get addLrcFile => 'Aldoni LRC-dosieron';

  @override
  String get addMoreFromThisAlbum => 'Aldoni pli de ĉi tiu albumo al vico';

  @override
  String get addMoreFromThisArtist => 'Aldoni pli de ĉi tiu artisto al vico';

  @override
  String get addMoreFromThisFolder => 'Aldoni pli de ĉi tiu dosierujo al vico';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Aldoni pli de $media al vico';
  }

  @override
  String get addOnlyMissing => 'Aldoni nur mankantajn';

  @override
  String get addToFavourites => 'Aldoni al ŝatataj';

  @override
  String get addToPlaylist => 'Aldoni al ludlisto';

  @override
  String get addTracksAtTheBeginning => 'Aldoni trakojn ĉe la komenco';

  @override
  String get added => 'aldonita';

  @override
  String get advanced => 'Altnivela';

  @override
  String get advancedSettings => 'Altnivela';

  @override
  String get advancedSettingsSubtitle => 'Altnivelaj agordoj, ne tuŝu';

  @override
  String get alarm => 'Alarmo';

  @override
  String get album => 'Albumo';

  @override
  String get albumArtist => 'Albumartisto';

  @override
  String get albumArtists => 'Albumartistoj';

  @override
  String get albumIdentifiers => 'Albumidentigiloj';

  @override
  String get albumThumbnailSizeInList => 'Grandeco de albuma bildeteto';

  @override
  String get albumTileCustomization => 'Agordo de albumkahelo';

  @override
  String get albums => 'Albumoj';

  @override
  String get albumsCount => 'Nombro de albumoj';

  @override
  String get all => 'Ĉio';

  @override
  String get allTime => 'Ĉiuj tempoj';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Ĉiam';

  @override
  String get alwaysAsk => 'Ĉiam demandi';

  @override
  String get alwaysDim => 'Ĉiam malheligi';

  @override
  String get alwaysExpandedSearchbar => 'Ĉiam vastigita serĉbreto';

  @override
  String get alwaysRestore => 'Ĉiam restarigi';

  @override
  String get animatingThumbnailIntensity => 'Intenseco de bildeteta animacio';

  @override
  String get animatingThumbnailInversed => 'Inversaj animacioj';

  @override
  String get animatingThumbnailInversedSubtitle => 'Altaj pintoj igos la bildeteton pli malgranda';

  @override
  String get anotherProcessIsRunning => 'Alia procezo jam ruliĝas.';

  @override
  String get appIcon => 'Aplikaĵa ikono';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Artisto';

  @override
  String get artists => 'Artistoj';

  @override
  String get artwork => 'Kovrilbildo';

  @override
  String get artworkGestures => 'Kovrilbildaj gestoj';

  @override
  String get artworks => 'Kovrilbildoj';

  @override
  String get audio => 'Aŭdio';

  @override
  String get audioCache => 'Aŭdia kaŝmemoro';

  @override
  String get audioOnly => 'Nur aŭdio';

  @override
  String get auto => 'Aŭto';

  @override
  String get autoBackupInterval => 'Aŭtomata savkopia intervalo';

  @override
  String get autoColoring => 'Aŭtomata kolorigo';

  @override
  String get autoColoringSubtitle => 'Aŭtomate elekti ludilajn kolorojn el nuna kovrilbildo';

  @override
  String get autoExtractTagsFromFilename => 'Aŭtomate ĉerpi el dosiernomo';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Aŭtomate ĉerpi titolon & artiston el videotitolo';

  @override
  String get autoGenerated => 'Aŭtomate generita';

  @override
  String get autoSkip => 'Aŭtomata preterpaso';

  @override
  String get autoSkipOnce => 'Aŭtomate preterpasi unufoje';

  @override
  String get autoStartRadio => 'Aŭtomate komenci radion';

  @override
  String get autoStartRadioSubtitle => 'Aŭtomate aldonas miksan ludliston kiam oni ludas unuopan trakon';

  @override
  String get automaticBackup => 'Aŭtomata';

  @override
  String get automaticBackupSubtitle => 'Aŭtomate aplikas la plej freŝan savkopian dosieron trovitan en la savkopia loko';

  @override
  String get backupAndRestore => 'Savkopio & Restarigo';

  @override
  String get backupAndRestoreSubtitle => 'Faru savkopion de via datumbazo kaj agordoj';

  @override
  String get balanced => 'Ekvilibra';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Inter datoj';

  @override
  String get bitrate => 'Bitrapido';

  @override
  String get blacklist => 'Nigra listo';

  @override
  String get borderRadiusMultiplier => 'Obliganto de randa radiuso';

  @override
  String get cache => 'Kaŝmemoro';

  @override
  String get cancel => 'Nuligi';

  @override
  String get canceled => 'Nuligita';

  @override
  String get changed => 'Ŝanĝita';

  @override
  String get changelog => 'Ŝanĝloglibro';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Kanalo';

  @override
  String get channels => 'Kanaloj';

  @override
  String get check => 'Kontroli';

  @override
  String get checkForMore => 'Kontroli por pli';

  @override
  String get checkList => 'Kontrollisto';

  @override
  String get choose => 'Elekti';

  @override
  String get chooseWhatToClear => 'Elektu kion forigi';

  @override
  String get claim => 'Postuli';

  @override
  String get clear => 'Forigi';

  @override
  String get clearAudioCache => 'Forigi aŭdian kaŝmemoron';

  @override
  String get clearImageCache => 'Forigi bildan kaŝmemoron';

  @override
  String get clearImageCacheWarning => 'Averto: rezultigos bibliotekon sen bildoj. Uzu nur por rekonstrui bildan kaŝmemoron.';

  @override
  String get clearTrackItem => 'Forigi tiujn de trako';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Forigi tiujn de $numberString trakoj',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Forigi videan kaŝmemoron';

  @override
  String get clearVideoCacheNote => 'Vi povas elekti kion forigi.';

  @override
  String get clock => 'Horloĝo';

  @override
  String get colorPalette => 'Kolorpaletro';

  @override
  String get colorPaletteNote1 => 'Longe premu koloron por forigi ĝin';

  @override
  String get colorPaletteNote2 => 'Frapetu miksaĵon por uzi kiel defaŭltan koloron';

  @override
  String get colorPalettes => 'Kolorpaletroj';

  @override
  String get comment => 'Komento';

  @override
  String get comments => 'Komentoj';

  @override
  String get composer => 'Komponisto';

  @override
  String get compress => 'Kunpremi';

  @override
  String get compressImages => 'Kunpremi bildojn';

  @override
  String get compressionPercentage => 'Procento de kunpremo';

  @override
  String get configure => 'Agordi';

  @override
  String get confirm => 'Konfirmi';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'Kovrilbildo kopiita';

  @override
  String get copiedToClipboard => 'Kopiita al tondujo';

  @override
  String get copy => 'Kopii';

  @override
  String get corruptedFile => 'Ne povis analizi dosieron, ĝi eble estas koruptita';

  @override
  String get couldntOpen => 'Ne povis malfermi :(';

  @override
  String get couldntOpenYtLink => 'Neniu Youtube-ligilo havebla por ĉi tiu trako';

  @override
  String get couldntPlayFile => 'Ne povis ludi dosieron';

  @override
  String get couldntRenamePlaylist => 'Ne povis alinomi ludliston';

  @override
  String get couldntSaveImage => 'Ne povis konservi bildon';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Lando';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Krei';

  @override
  String get createBackup => 'Krei savkopion';

  @override
  String get createNewPlaylist => 'Krei novan ludliston';

  @override
  String get createdBackupSuccessfully => 'Savkopio kreita';

  @override
  String get createdBackupSuccessfullySub => 'Savkopia dosiero estis sukcese kreita';

  @override
  String get crossPlatformSync => 'Interplatforma sinkronigo';

  @override
  String get crossfadeDuration => 'Daŭro de miksfando';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Aŭtomate aktivigi miksfandon en la lastaj $secondsString sekundoj',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Ne aktivigi miksfandon aŭtomate';

  @override
  String get custom => 'Propra';

  @override
  String get customizations => 'Personigoj';

  @override
  String get customizationsSubtitle => 'Agordu kiel via ludilo aspektas, faru ĝin via';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Datumoj provizitaj de: $name';
  }

  @override
  String get dataSaver => 'Datuma ŝparado';

  @override
  String get dataSaverMode => 'Reĝimo de datuma ŝparado';

  @override
  String get database => 'Datumbazo';

  @override
  String get date => 'Dato';

  @override
  String get dateAdded => 'Dato aldonita';

  @override
  String get dateCreated => 'Dato kreita';

  @override
  String get dateModified => 'Dato modifita';

  @override
  String get dateTimeFormat => 'Dato-tempa formato';

  @override
  String get day => 'Tago';

  @override
  String get days => 'Tagoj';

  @override
  String get defaultBackupLocation => 'Defaŭlta savkopia loko';

  @override
  String get defaultColor => 'Defaŭlta koloro';

  @override
  String get defaultColorSubtitle => 'Agordu koloron uzotan de la ludilo';

  @override
  String get defaultDownloadLocation => 'Defaŭlta elŝuta loko';

  @override
  String get defaultLabel => 'Defaŭlta';

  @override
  String get defaultLibraryTab => 'Defaŭlta biblioteka langeto';

  @override
  String get delete => 'Forigi';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Ĉu forigi $countString dosieron reprezentantan $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Konstante forigi $numberText el via stokado';
  }

  @override
  String get deletePlaylist => 'Forigi ludliston';

  @override
  String get deleteTempFiles => 'Forigi tempajn dosierojn';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Priskribo';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Ĉu vi celis';

  @override
  String get dimIntensity => 'Intenseco de malheligo';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Malheligi miniludilon post $secondsString sekundoj de neaktivieco',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Dosierujo ne ekzistas';

  @override
  String get disable => 'Malŝalti';

  @override
  String get disableAll => 'Malŝalti ĉion';

  @override
  String get disableReordering => 'Malŝalti reordigadon';

  @override
  String get disableSearchCleanup => 'Malŝalti serĉpurigon';

  @override
  String get discNumber => 'Diska numero';

  @override
  String get discNumberTotal => 'Diska totalo';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Malŝati';

  @override
  String get dismissibleMiniplayer => 'Forigebla miniludilo';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Montri realan pozicion anstataŭ diferencon dum serĉado';

  @override
  String get displayAlbumCardTopRightDate => 'Dato supre dekstre de albumkarto';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Montri albuman daton supre dekstre de albumkarto';

  @override
  String get displayArtistBeforeTitle => 'Montri artiston antaŭ titolo';

  @override
  String get displayArtworkOnLockscreen => 'Montri kovrilbildon sur ŝlosita ekrano';

  @override
  String get displayAudioInfoInMiniplayer => 'Montri aŭdian informon';

  @override
  String get displayFavButtonInNotification => 'Montri ŝatbutonon en sciigo';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Bildeteto eble moviĝos.';

  @override
  String get displayFavouriteIconInTrackTile => 'Montri ŝatbutonon';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Montri restantan daŭron anstataŭ totalon';

  @override
  String get displayStopButtonInNotification => 'Montri stop-butonon en sciigo';

  @override
  String get displayThirdItemInRowInTrackTile => 'Montri trian eron en ĉiu vico';

  @override
  String get displayThirdRowInTrackTile => 'Montri trian vicon';

  @override
  String get displayTrackNumberInAlbumPage => 'Montri trakan numeron en albumpaĝo';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Montri malgrandan skatolon enhavantan la trakan numeron en la albumpaĝo';

  @override
  String get doNothing => 'Fari nenion';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Farita';

  @override
  String get dontAskAgain => 'Ne demandu denove';

  @override
  String get dontDim => 'Ne malheligi';

  @override
  String get dontRestorePosition => 'Ne restarigi';

  @override
  String get dontResume => 'Ne daŭrigi';

  @override
  String get doubleTapToToggleLyrics => 'Duoble frapetu por ŝalti kantotekston';

  @override
  String get download => 'Elŝuti';

  @override
  String get downloadingWillOverrideIt => 'Elŝutado anstataŭigos ĝin';

  @override
  String get downloads => 'Elŝutoj';

  @override
  String get downloadsMetadataTags => 'Metadatumaj etikedoj de elŝutoj';

  @override
  String get downloadsMetadataTagsSubtitle => 'Defaŭlte ĉerpi artiston, titolon & albumon el video-informoj';

  @override
  String get dragToSeek => 'Trenu por serĉi';

  @override
  String get duckAudio => 'Malaltigi aŭdion';

  @override
  String get duplicatedItemsAdding => 'Vi provas aldoni kelkajn erojn kiuj jam ekzistas en ĉi tiu ludlisto';

  @override
  String get duplicatedTracks => 'Duobligitaj trakoj';

  @override
  String get duration => 'Daŭro';

  @override
  String get edgeColorsSwitching => 'Ŝanĝo de randaj koloroj';

  @override
  String get edit => 'Redakti';

  @override
  String get editArtwork => 'Redakti kovrilbildon';

  @override
  String get editTags => 'Redakti etikedojn';

  @override
  String get email => 'Retpoŝto';

  @override
  String get emptyNonMeaningfulTagFields => 'vi havas kampojn kun malplenaj/sensencaj valoroj, certigu ke vi vere volas redakti ilin';

  @override
  String get emptyValue => 'Malplena valoro';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Ŝalti malklarigan efikon';

  @override
  String get enableBottomNavBar => 'Ŝalti malsupran navigadbreton';

  @override
  String get enableBottomNavBarSubtitle => 'Eroj estas ene de la tirkesto ambaŭdirekte';

  @override
  String get enableClipboardMonitoring => 'Ŝalti tondujan monitoradon';

  @override
  String get enableClipboardMonitoringSubtitle => 'Ebligas glui ligilojn kaj tekstojn ene de serĉbreto dum la irado';

  @override
  String get enableCrossfadeEffect => 'Ŝalti miksfandan efikon';

  @override
  String get enableFadeEffectOnPlayPause => 'Ŝalti fandan efikon ĉe ludo/paŭzo';

  @override
  String get enableFoldersHierarchy => 'Ŝalti hierarkion de dosierujoj';

  @override
  String get enableGlowEffect => 'Ŝalti brilan efikon';

  @override
  String get enableM3uSync => 'Ŝalti M3U-sinkronigon';

  @override
  String get enableM3uSyncNote1 => 'M3U-sinkronigo ebligas konservi ŝanĝojn de ludlisto al la originala M3U-dosiero';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Se io misfunkcios, savkopio de ĉi tiu ludlisto troviĝos en $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Se rifuzita, ĉiuj ŝanĝoj faritaj en ĉi tiu ludlisto estos perditaj ĉe restartigo';

  @override
  String get enableMiniplayerParticles => 'Ŝalti moviĝantajn partiklojn';

  @override
  String get enableParallaxEffect => 'Ŝalti paralaksan efikon';

  @override
  String get enablePartyMode => 'Ŝalti festan reĝimon';

  @override
  String get enablePartyModeSubtitle => 'Apliki elegantan randan spiran efikon';

  @override
  String get enablePictureInPicture => 'Ŝalti bildo-en-bildo';

  @override
  String get enableReordering => 'Ŝalti reordigadon';

  @override
  String get enableReturnYoutubeDislike => 'Ŝalti Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Ŝalti serĉpurigon';

  @override
  String get enableSearchCleanupSubtitle => 'Ĉiuj simboloj kaj spacoj estos ignoritaj';

  @override
  String get enableSponsorblock => 'Ŝalti SponsorBlock';

  @override
  String get enableVideoPlayback => 'Ŝalti videoludadon';

  @override
  String get enterSymbol => 'Bonvolu enigi simbolon';

  @override
  String get equalizer => 'Egaligilo';

  @override
  String get error => 'Eraro';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Eraro ludante trakon';

  @override
  String get excludedFodlers => 'Ekskluditaj dosierujoj';

  @override
  String get exit => 'Eliri';

  @override
  String get exitAppSubtitle => 'Frapetu denove por eliri';

  @override
  String get expandedMiniplayer => 'Vastigita miniludilo';

  @override
  String get exportAsM3u => 'Eksporti kiel M3U';

  @override
  String get extension => 'Etendaĵo';

  @override
  String get externalFiles => 'Eksteraj dosieroj';

  @override
  String get extract => 'Ĉerpi';

  @override
  String get extractAllColorPalettes => 'Ĉerpi ĉiujn kolorpaletrojn';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ĉu ĉerpi restantajn $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Ĉerpi feat. artistojn el titolo';

  @override
  String get extractFeatArtistSubtitle => 'Ĉerpas (feat. X) kaj (ft. X) artistojn, kiel novan artistan eniron.';

  @override
  String get extractingInfo => 'Ĉerpante informojn';

  @override
  String get extras => 'Ekstraĵoj';

  @override
  String get extrasSubtitle => 'Ekstraj agordoj por fajnigi vian sperton';

  @override
  String get extreme => 'Ekstrema';

  @override
  String get failed => 'Malsukcesis';

  @override
  String get failedEdits => 'Malsukcesaj redaktoj';

  @override
  String get favourites => 'Ŝatataj';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Prenante';

  @override
  String get fetchingOfAllVideos => 'Prenante ĉiujn videojn';

  @override
  String get file => 'Dosiero';

  @override
  String get fileAlreadyExists => 'Dosiero jam ekzistas';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Dosiernomo';

  @override
  String get fileNameWoExt => 'Dosiernomo sen etendaĵo';

  @override
  String get filenameShouldntStartWith => 'Dosiernomo ne devus komenciĝi per';

  @override
  String get files => 'Dosieroj';

  @override
  String get filler => 'Plenigilo';

  @override
  String get filterAlbums => 'Filtrili albumojn';

  @override
  String get filterArtists => 'Filtrili artistojn';

  @override
  String get filterGenres => 'Filtrili ĝenrojn';

  @override
  String get filterPlaylists => 'Filtrili ludlistojn';

  @override
  String get filterTracks => 'Filtrili trakojn';

  @override
  String get filterTracksBy => 'Filtrili trakojn en serĉlistoj laŭ';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Trakoj filtritaj laŭ grandeco kaj daŭro';

  @override
  String get finished => 'Finita';

  @override
  String get finishedUpdatingLibrary => 'Finis ĝisdatigon de biblioteko';

  @override
  String get firstListen => 'Unua aŭskulto';

  @override
  String get fixYtdlpBigThumbnailSize => 'Ripari grandan bildetetgrandon de yt-dlp';

  @override
  String get floatingActionButton => 'Flosanta aga butono';

  @override
  String get folder => 'Dosierujo';

  @override
  String get folderName => 'Dosierujnomo';

  @override
  String get folders => 'Dosierujoj';

  @override
  String get fontScale => 'Tipara skalo';

  @override
  String get forceMiniplayerFollowTrackColors => 'Devigi miniludilon sekvi trakajn kolorojn';

  @override
  String get forceSquaredAlbumThumbnail => 'Devigi kvadratan albuman bildeteton';

  @override
  String get forceSquaredThumbnailNote => 'Bildeteta grandeco & Kahela alto NE estas egalaj, kvadrata aspekto ne estos kiel atendite, ĉu vi volas egaligi ilin?';

  @override
  String get forceSquaredTrackThumbnail => 'Devigi kvadratan trakan bildeteton';

  @override
  String get forceStopColorPaletteGeneration => 'Ĉu devigi halton de kolorpaletra generado? vi ankoraŭ povas daŭrigi ĝin poste';

  @override
  String get format => 'Formato';

  @override
  String get fullscreen => 'Plenekrano';

  @override
  String get gaplessPlayback => 'Sengapa ludado';

  @override
  String get generate => 'Generi';

  @override
  String get generateFromDates => 'Tempa intervalo';

  @override
  String get generateFromDatesSubtitle => 'Generi trakojn kiujn vi aŭskultis en tempa intervalo';

  @override
  String get generateRandomPlaylist => 'Generi hazardan ludliston';

  @override
  String get genre => 'Ĝenro';

  @override
  String get genres => 'Ĝenroj';

  @override
  String get goToAlbum => 'Iru al albumo';

  @override
  String get goToArtist => 'Iru al artisto';

  @override
  String get goToChannel => 'Iru al kanalo';

  @override
  String get goToFolder => 'Iru al dosierujo';

  @override
  String get goodLooking => 'Bela aspekto';

  @override
  String get grantStoragePermission => 'Doni stokan permeson';

  @override
  String get group => 'Grupo';

  @override
  String get groupArtworksByAlbum => 'Grupigi kovrilbildojn laŭ albumo';

  @override
  String get guide => 'Gvidilo';

  @override
  String get hapticFeedback => 'Haptika reigo';

  @override
  String get heightOfAlbumTile => 'Alto de albumkahelo';

  @override
  String get heightOfTrackTile => 'Alto de trakkahelo';

  @override
  String get hideSkipButtonAfter => 'Kaŝi preterpasan butonon post';

  @override
  String get highMatches => 'Altaj kongruoj';

  @override
  String get highPerformance => 'Alta rendimento';

  @override
  String get highlight => 'Elstarigi';

  @override
  String get history => 'Historio';

  @override
  String get historyImportMissingEntriesNote => 'Ĉi tiuj eroj ne povis esti trovitaj en la biblioteko, se vi kredas ke ili ekzistas, bonvolu konsideri aldoni ilin mane';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString aŭskultoj por $oldTrackInfo estos anstataŭigitaj per $newTrackInfo, ĉu konfirmi?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Hejmo';

  @override
  String get hook => 'Hoko';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12-hora formato';

  @override
  String get hours => 'Horoj';

  @override
  String get iReadAndAgree => 'Mi legis & konsentas';

  @override
  String get ifNotPlaying => 'Se ne ludas';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Elŝutoj povas esti bremsitaj kiam la aplikaĵo estas baterie limigita';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignori komunajn prefiksojn dum ordigo';

  @override
  String get ignores => 'Ignoras';

  @override
  String get imageSource => 'Bilda fonto';

  @override
  String get immersiveMode => 'Imersiva reĝimo';

  @override
  String get immersiveModeSubtitle => 'Kaŝi statusan & navigadan bretojn dum miniludilo estas vastigita';

  @override
  String get import => 'Imposti';

  @override
  String get importAll => 'Imposti ĉion';

  @override
  String get importLastFmHistory => 'Imposti LastFm Historion';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Iru al $lastfmCsvLink\n\n2. Tajpu vian uzantnomon, prenu kaj elŝutu csv-dosieron.\n\n3. Elektu la dosieron de la sekva ekrano.';
  }

  @override
  String get importTimeRange => 'Imposti tempan intervalon';

  @override
  String get importYoutubeHistory => 'Imposti Youtube Historion';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Iru al $takeoutLink\n\n2. Premu \"Multiple Formats\" kaj apud \"History\" elektu \"JSON\".\n\n3. Premu \"All Youtube data included\", Malelektu Ĉion kaj elektu nur historion.\n\n4. Kreu Eksporton, Elŝutu & Malzipigu.\n\n5. Elektu \"watch-history.json\" de la sekva ekrano.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Importis $numberString kanalojn sukcese',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Importis $numberText ludlistojn sukcese',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Inkluzivi videojn';

  @override
  String get indexRefreshRequired => 'Faru refreŝigon post ŝanĝo de tio';

  @override
  String get indexer => 'Indeksilo';

  @override
  String get indexerNote => 'Noto: Nekompleta Nombro de Kovrilbildoj rilatas al la duobligitaj & ne trovitaj Kovrilbildoj';

  @override
  String get indexerSubtitle => 'Administru vian muzikan bibliotekon';

  @override
  String get infinityQueueOnNextPrev => 'Senfina vico ĉe Sekva/Antaŭa';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'premi sekvan dum ludas la lasta ero saltos al la unua, kaj inverse';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'enmetita';

  @override
  String get instantlyApplies => 'Tuj aplikiĝas';

  @override
  String get interactionReminder => 'Interaga memorigilo';

  @override
  String get intro => 'Enkonduko';

  @override
  String get invertSelection => 'Inversigi elekton';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Ero';

  @override
  String get jump => 'Salti';

  @override
  String get jumpToDay => 'Salti al Tago';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Salti al unua trako post fino de vico';

  @override
  String get keepCachedVersions => 'Konservi kaŝmemorigitajn versiojn';

  @override
  String get keepFileDates => 'Konservi dosierajn datojn';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniludilo estas Vastigita';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniludilo estas Vastigita kaj Video Ludas';

  @override
  String get keepScreenAwakeNone => 'Ne teni ekranon vekita';

  @override
  String get keepScreenAwakeWhen => 'Teni ekranon vekita kiam';

  @override
  String get killPlayerAfterDismissingApp => 'Mortigi ludilon post forigo de aplikaĵo';

  @override
  String get language => 'Lingvo';

  @override
  String get learnMore => 'Lerni pli';

  @override
  String get leftAction => 'Maldekstra Ago';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Bibliotekaj Langetoj';

  @override
  String get libraryTabsReorder => 'Vi povas reordigi la aktivigitajn langetojn.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Ŝati';

  @override
  String get liked => 'Ŝatita';

  @override
  String get link => 'Ligilo';

  @override
  String get listOfFolders => 'Listo de Dosierujoj';

  @override
  String get loadAll => 'Ŝargi ĉion';

  @override
  String get loadingFile => 'Ŝargante dosieron';

  @override
  String get local => 'Loka';

  @override
  String get localVideoMatching => 'Loka Videa Kongruo';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-prema Ago';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Longe premu la kantotekston por eniri plenekranon';

  @override
  String get lostMemories => 'Perditaj Memoroj';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'ĉirkaŭ ĉi tiu tempo, antaŭ $numberString jaroj',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Laŭteca Plibonigilo';

  @override
  String get lyricist => 'Kantverkisto';

  @override
  String get lyrics => 'Kantoteksto';

  @override
  String get lyricsSource => 'Fonto de kantoteksto';

  @override
  String get m3uPlaylist => 'M3U Ludlisto';

  @override
  String get makeYourFirstListen => 'Faru vian unuan aŭskulton!';

  @override
  String get manage => 'Administri';

  @override
  String get manageYourAccounts => 'Administru viajn kontojn';

  @override
  String get manualBackup => 'Manuale';

  @override
  String get manualBackupSubtitle => 'elektu specifan dosieron';

  @override
  String get markAsRead => 'Marki kiel legita';

  @override
  String get matchAllTracks => 'Kongrui Ĉiujn Trakojn';

  @override
  String get matchAllTracksNote => 'tio povas havi efikon sur la kongrua rapido, ĉar ĝi kontrolos ĉiujn trakojn en via biblioteko';

  @override
  String get matchingType => 'Kongrua tipo';

  @override
  String get maxAudioCacheSize => 'Maksimuma aŭdia kaŝmemora grandeco';

  @override
  String get maxImageCacheSize => 'Maksimuma bilda kaŝmemora grandeco';

  @override
  String get maxVideoCacheSize => 'Maksimuma videa kaŝmemora grandeco';

  @override
  String get maximum => 'Maksimumo';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store estas ŝaltita, tio ne havos efikon';

  @override
  String get medium => 'Meza';

  @override
  String get membershipCode => 'Kodo';

  @override
  String get membershipCodeSentToEmail => 'Kodo sendita al via retpoŝto';

  @override
  String get membershipDidntChange => 'Membreco ne ŝanĝiĝis';

  @override
  String get membershipEnjoyNew => 'Ĝuu vian novan membrecon';

  @override
  String get membershipFreeCoupon => 'Senpaga Kupono';

  @override
  String get membershipManage => 'Administru vian membrecon';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Neniuj abonoj trovitaj por ĉi tiu uzanto';

  @override
  String get membershipSignInToPatreonAccount => 'Ensalutu al via patreon-konto';

  @override
  String get membershipUnknown => 'Nekonata Membreco';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Vi bezonas membrecon de $name1 aŭ $name2 por aldoni plurajn kontojn';
  }

  @override
  String get merge => 'Kunfandi';

  @override
  String get metadataCache => 'Metadatuma Kaŝmemoro';

  @override
  String get metadataEditFailed => 'Malsukcesis redakti metadatumojn';

  @override
  String get metadataReadFailed => 'Malsukcesis legi metadatumojn';

  @override
  String get minFileDuration => 'Minimuma Traka Daŭro';

  @override
  String get minFileSize => 'Minimuma Dosiera Grandeco';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimuma traka daŭro por restarigi lastan luditan pozicion';

  @override
  String get minValueCantBeMoreThanMax => 'Minimuma valoro ne povas esti pli ol la maksimumo';

  @override
  String get minValueToCountTrackListen => 'Nombri aŭskulton post: ';

  @override
  String get minimizedMiniplayer => 'Minimumigita Miniludilo';

  @override
  String get minimum => 'Minimumo';

  @override
  String get minimumOneFolderSubtitle => 'Devus esti almenaŭ 1 dosierujo, aldonu pli da dosierujoj se vi volas forigi ĉi tiun';

  @override
  String get minimumOneItem => 'Ne povis forigi eron';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Almenaŭ $numberString eroj devus resti',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimuma Segmenta Daŭro';

  @override
  String get miniplayerCustomization => 'Miniludila Personigo';

  @override
  String get minutes => 'minutoj';

  @override
  String get missingEntries => 'Mankantaj Eroj';

  @override
  String get missingTracks => 'Mankantaj Trakoj';

  @override
  String get mix => 'Miksaĵo';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Miksa ludlisto generita de youtube';

  @override
  String get mixes => 'Miksaĵoj';

  @override
  String get mobile => 'Poŝtelefono';

  @override
  String get month => 'Monato';

  @override
  String get months => 'Monatoj';

  @override
  String get mood => 'Humoro';

  @override
  String get moods => 'Humoroj';

  @override
  String get more => 'Pli';

  @override
  String get mostPlayed => 'Plej Luditaj';

  @override
  String get multipleTracksTagsEditNote => 'Vi estas redaktonta ĉi tiujn trakojn,\nNeŝanĝitaj kampoj restas netuŝitaj.';

  @override
  String get musicOfftopic => 'Muziko Ekster-tema';

  @override
  String get name => 'Nomo';

  @override
  String get nameContainsBadCharacter => 'Nomo enhavas malbonan signon';

  @override
  String get never => 'Neniam';

  @override
  String get newDirectory => 'Nova dosierujo';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Aldoni Trakojn';

  @override
  String get newTracksMoods => 'Humoro';

  @override
  String get newTracksMoodsSubtitle => 'Generi trakojn bazitajn sur haveblaj humoroj';

  @override
  String get newTracksRandom => 'Hazarda';

  @override
  String get newTracksRandomSubtitle => 'Elekti hazardajn trakojn el via biblioteko';

  @override
  String get newTracksRatings => 'Taksoj';

  @override
  String get newTracksRatingsSubtitle => 'Generi trakojn kiuj havas specifan takson';

  @override
  String get newTracksRecommended => 'Rekomendita';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Generi trakojn kiujn vi kutime aŭskultis kun $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Simila Eldondato';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Generi trakojn kiuj estis eldonitaj ĉirkaŭ la sama tempo kiel $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Trako havas nekonatan jaron';

  @override
  String get newest => 'Plej nova';

  @override
  String get next => 'Sekva';

  @override
  String get no => 'ne';

  @override
  String get noChangesFound => 'Neniuj ŝanĝoj trovitaj.';

  @override
  String get noEnoughTracks => 'Vi ne havas multajn trakojn..';

  @override
  String get noExcludedFolders => 'Vi ne havas ekskluditajn dosierujojn';

  @override
  String get noFolderChosen => 'Vi ne elektis iun dosierujon';

  @override
  String get noMoodsAvailable => 'Neniuj humoroj haveblaj';

  @override
  String get noNetworkAvailableToFetchData => 'Neniu reto havebla por preni datumojn';

  @override
  String get noTracksFound => 'Neniuj trakoj estis trovitaj';

  @override
  String get noTracksFoundBetweenDates => 'Ĉi tiu tempintervalo ne havas trakojn.';

  @override
  String get noTracksFoundInDirectory => 'Neniuj trakoj trovitaj en ĉi tiu dosierujo';

  @override
  String get noTracksInHistory => 'Vi ne havas sufiĉe da trakoj en historio';

  @override
  String get nonActive => 'Ne-Aktiva';

  @override
  String get nonFavourites => 'Ne-Ŝatataj';

  @override
  String get none => 'Neniu';

  @override
  String get normalizeAudio => 'Normaligi aŭdion';

  @override
  String get normalizeAudioSubtitle => 'Normaligas volumon legante la reproduktan gajnan etikedon aŭ la informojn provizitajn de youtube';

  @override
  String get notAvailableForYourDevice => 'Ne Havebla por via Aparato';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'Noto';

  @override
  String get notification => 'Sciigo';

  @override
  String get notifications => 'Sciigoj';

  @override
  String get numberOfTracks => 'Nombro de Trakoj';

  @override
  String get ofLabel => 'de';

  @override
  String get offlineSearch => 'Senreta Serĉo';

  @override
  String get offset => 'Ofseto';

  @override
  String get oldDirectory => 'Malnova dosierujo';

  @override
  String get oldDirectoryStillHasTracks => 'Malnova Dosierujo ankoraŭ havas iujn trakojn, ĉu konfirmi?';

  @override
  String get oldestWatch => 'Plej Malnova Spekto';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Ĉe Interrompo';

  @override
  String get onNotificationTap => 'Ĉe Sciiga Frapeto';

  @override
  String get onOpeningYoutubeLink => 'Ĉe malfermo de youtube-ligilo';

  @override
  String get onSwiping => 'Ĉe Svingo';

  @override
  String get onVolumeZero => 'Ĉe volumo 0';

  @override
  String get ongoing => 'Daŭranta';

  @override
  String get open => 'Malfermi';

  @override
  String get openApp => 'Malfermi Aplikaĵon';

  @override
  String get openInFileExplorer => 'Malfermi en Dosiera Esplorilo';

  @override
  String get openInYoutubeView => 'Malfermi en Youtube-vido';

  @override
  String get openMiniplayer => 'Malfermi Miniludilon';

  @override
  String get openQueue => 'Malfermi Vicon';

  @override
  String get openYoutubeLink => 'Malfermi Youtube-Ligilon';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operacio $name postulas konton, Ensalutu por daŭrigi';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operacio $operation postulas almenaŭ membrecon $name';
  }

  @override
  String get or => 'aŭ';

  @override
  String get others => 'Aliaj';

  @override
  String get output => 'Eligo';

  @override
  String get outro => 'Elkonduko';

  @override
  String get overrideOldFilesInTheSameFolder => 'Anstataŭigi malnovajn dosierojn en la sama dosierujo';

  @override
  String get palette => 'Paletro';

  @override
  String get paletteMix => 'Miksaĵo';

  @override
  String get paletteNewMix => 'Nova Miksaĵo';

  @override
  String get paletteSelectedMix => 'Elektita Miksaĵo';

  @override
  String get parallelDownloads => 'Paralelaj Elŝutoj';

  @override
  String get parsed => 'analizita';

  @override
  String get password => 'Password';

  @override
  String get path => 'Dosiera Plena Vojo';

  @override
  String get pause => 'Paŭzo';

  @override
  String get pauseFadeDuration => 'Daŭro de Paŭza Fando';

  @override
  String get pausePlayback => 'Paŭzi ludadon';

  @override
  String get percentage => 'Procento';

  @override
  String get performanceMode => 'Efikeca reĝimo';

  @override
  String get performanceNote => 'Povas influi efikecon';

  @override
  String get personalized => 'Personigita';

  @override
  String get personalizedRelatedVideos => 'Personigitaj Rilataj Videoj';

  @override
  String get personalizedRelatedVideosSubtitle => 'Malŝalti tion pliigos datuman uzadon';

  @override
  String get pickColorsFromDeviceWallpaper => 'Elekti Kolorojn el Aparata Fonbildo';

  @override
  String get pickFromStorage => 'Elekti el stokado';

  @override
  String get pinned => 'Alpinglita';

  @override
  String get pitch => 'Tonalteco';

  @override
  String get plain => 'Simpla';

  @override
  String get play => 'Ludi';

  @override
  String get playAfter => 'Ludi Post';

  @override
  String get playAfterNextPrev => 'Aŭtomata Ludo ĉe Sekva/Antaŭa';

  @override
  String get playAll => 'Ludi Ĉion';

  @override
  String get playFadeDuration => 'Daŭro de Luda Fando';

  @override
  String get playLast => 'Ludi Lastan';

  @override
  String get playNext => 'Ludi Sekvan';

  @override
  String get playbackSetting => 'Ludado';

  @override
  String get playbackSettingSubtitle => 'Povas esti alirita rekte en la ludilo per longa premo de la aŭdia butono';

  @override
  String get playlist => 'Ludlisto';

  @override
  String get playlists => 'Ludlistoj';

  @override
  String get playlistsImportM3uNative => 'Ĉi tio importos M3U-ludlistojn por esti uzataj nur de namida, uzu se vi migras';

  @override
  String get playlistsImportM3uSynced =>
      'Ĉi tio aŭtomate importos M3U-ludlistojn de indeksilaj dosierujoj kaj tenos ilin sinkronigitaj kun la originala M3U-dosiero. ŝaltu se vi aliras/modifas la ludlistojn de aliaj aplikaĵoj';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Aŭtomate importi M3U Ludlistojn';

  @override
  String get pleaseEnterADifferentName => 'Ĉi tiu nomo jam ekzistas :(\nbonvolu provi alian belan nomon';

  @override
  String get pleaseEnterALink => 'Bonvolu enigi ligilon';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. ĉu ĉi tio estas youtube-ligilo?';

  @override
  String get pleaseEnterAName => 'Bonvolu enigi nomon';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Malhelpi Duobligitajn trakojn';

  @override
  String get preventDuplicatedTracksSubtitle => 'Uzas dosiernomon por unike identigi trakojn';

  @override
  String get preview => 'Antaŭrigardo';

  @override
  String get previous => 'Antaŭa';

  @override
  String get previousButtonReplays => 'Antaŭa butono reludas';

  @override
  String get previousButtonReplaysSubtitle => 'se premita dum nuna pozicio estis pli ol serĉa daŭro';

  @override
  String get prioritizeEmbeddedLyrics => 'Prioritatigi enmetitan kantotekston';

  @override
  String get priority => 'Prioritato';

  @override
  String get private => 'Privata';

  @override
  String get progress => 'Progreso';

  @override
  String get promptToChangeTrackPath => 'Kutime tio okazas kiam vi forigas/movas/alinomas la dosieron ekster namida, Ĉu vi volas ĝisdatigi nunan vojon?';

  @override
  String get public => 'Publika';

  @override
  String get queue => 'Vico';

  @override
  String get queues => 'Vicoj';

  @override
  String get random => 'Hazarda';

  @override
  String get randomPicks => 'Hazardaj Elektoj';

  @override
  String get rating => 'Takso';

  @override
  String get reIndex => 'Re-indeksi';

  @override
  String get reIndexSubtitle => 'Rekonstrui vian muzikan bibliotekon de nulo';

  @override
  String get reIndexWarning => 'Ĉi tiu procezo eble daŭros iom, depende de via biblioteka grandeco.\n\nKovrilbildoj ne estos re-indeksitaj tiom longe kiom ili ankoraŭ ekzistas';

  @override
  String get recentAlbums => 'Lastatempaj Albumoj';

  @override
  String get recentArtists => 'Lastatempaj Artistoj';

  @override
  String get recentListens => 'Lastatempaj Aŭskultoj';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Lastatempe Aldonitaj';

  @override
  String get recordLabel => 'Diskeldonejo';

  @override
  String get refresh => 'Refreŝigi';

  @override
  String get refreshLibrary => 'Refreŝigi Bibliotekon';

  @override
  String get refreshLibrarySubtitle => 'Kontroli por nove aldonita aŭ forigita muziko';

  @override
  String get refreshOnStartup => 'Refreŝigi ĉe komenco';

  @override
  String get relatedVideos => 'Rilataj videoj';

  @override
  String get rememberAudioOnlyMode => 'Memori nur-aŭdian reĝimon';

  @override
  String get remixer => 'Remiksisto';

  @override
  String get remove => 'Forigi';

  @override
  String get removeDuplicates => 'Forigi Duplikatojn';

  @override
  String get removeFromFavourites => 'Forigi el ŝatataj';

  @override
  String get removeFromLibrary => 'Forigi el biblioteko';

  @override
  String get removeFromPlaylist => 'Forigi El Ludlisto';

  @override
  String get removeQueue => 'Forigi Vicon';

  @override
  String get removeSourceFromHistory => 'Forigi fonton el historio';

  @override
  String get removeWhitespaces => 'Forigi Blankajn Spacojn';

  @override
  String get removed => 'Forigita';

  @override
  String get rename => 'Alinomi';

  @override
  String get renamePlaylist => 'Alinomi Ludliston';

  @override
  String get reorderable => 'Reordigebla';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ripeti por $number pliaj fojoj',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Ripeta reĝimo';

  @override
  String get repeatModeAll => 'Ripeti Tutan Vicon';

  @override
  String get repeatModeNone => 'Halti ĉe Lasta Trako';

  @override
  String get repeatModeOne => 'Ripeti Nunan Trakon';

  @override
  String get replaceAllListensWithAnotherTrack => 'Anstataŭigi ĉiujn aŭskultojn per alia trako';

  @override
  String get replies => 'Respondoj';

  @override
  String get reply => 'Respondi';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Postulas forigon de bilda kaŝmemoro kaj re-indeksadon';

  @override
  String get rescanVideos => 'Reskani videojn';

  @override
  String get resetBrightness => 'Restarigi helecon';

  @override
  String get resetToDefault => 'Agordi al';

  @override
  String get respectNoMedia => 'Respekti .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Ne inkluzivi dosierujojn kiuj havas .nomedia';

  @override
  String get restart => 'Rekomenci';

  @override
  String get restoreBackup => 'Restarigi Savkopion';

  @override
  String get restoreDefaults => 'Restarigi Defaŭltojn';

  @override
  String get restoredBackupSuccessfully => 'Restarigis Savkopion';

  @override
  String get restoredBackupSuccessfullySub => 'Savkopia dosiero estis sukcese restarigita';

  @override
  String get resume => 'Daŭrigi';

  @override
  String get resumeIfWasInterrupted => 'Daŭrigi se estis paŭzita per interrompo';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Daŭrigi se estis paŭzita per volumo';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Daŭrigi se estis paŭzita por malpli ol $numberString minutoj',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Inversa Ordo';

  @override
  String get rightAction => 'Dekstra Ago';

  @override
  String get ringtone => 'Sonoro';

  @override
  String get sameDirectoryOnly => 'Sama dosierujo nur';

  @override
  String get sample => 'Specimeno';

  @override
  String get sampleRate => 'Specimena Ofteco';

  @override
  String get save => 'Konservi';

  @override
  String get saveToLibrary => 'Konservi al biblioteko';

  @override
  String get savedIn => 'Konservita en';

  @override
  String get scaleMultiplier => 'Skala Obliganto';

  @override
  String get search => 'Serĉi';

  @override
  String get searchYoutube => 'Serĉi YouTube';

  @override
  String get seconds => 'sekundoj';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Serĉa Daŭro';

  @override
  String get seekDurationInfo => 'Vi povas frapeti nunan daŭron por serĉi malantaŭen & totalan daŭron por serĉi antaŭen';

  @override
  String get seekbar => 'Serĉbreto';

  @override
  String get selectAll => 'Elekti Ĉion';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Elekti dosierojn jam en loka biblioteko';

  @override
  String get selectedTracks => 'Elektitaj Trakoj';

  @override
  String get selfPromotion => 'Mem-Promocio';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Ĉi tiuj vortoj ne estos disigitaj';

  @override
  String get separatorsMessage => 'Ne necesas enmeti spacojn, krom se vi volas uzi literon/simbolon kiu troviĝas en tuta vorto (kiel x kaj ft.)';

  @override
  String get serverAddress => 'Servila Adreso';

  @override
  String get setAs => 'Agordi kiel';

  @override
  String get setAsDefault => 'Agordi kiel Defaŭltan';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Agordi dosieran lastan modifon kiel videan alŝutdaton';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Agordi humorojn';

  @override
  String get setMoodsSubtitle => 'Uzu komojn (,) por disigi inter ili';

  @override
  String get setRating => 'Agordi Takson';

  @override
  String get setTags => 'Agordi etikedojn';

  @override
  String get setYoutubeLink => 'Agordi Youtube-Ligilon';

  @override
  String get settings => 'Agordoj';

  @override
  String get setupFirstStartup => 'Agordi unuan komencon';

  @override
  String get share => 'Kunhavigi';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Mallongigoj';

  @override
  String get shouldDuck => 'Devus malaltigi';

  @override
  String get shouldDuckNote => 'Indikas ke la volumo devus esti malaltigita. ekz: sciigo';

  @override
  String get shouldPause => 'Devus paŭzi';

  @override
  String get shouldPauseNote => 'Indikas ke la ludado devus esti paŭzita. ekz: vokoj';

  @override
  String get showAll => 'Montri Ĉion';

  @override
  String get showChannelWatermarkInFullscreen => 'Montri kanalan akvomarkon en plenekrano';

  @override
  String get showFailedOnly => 'Montri Malsukcesajn nur';

  @override
  String get showHideUnknownFields => 'Montri/kaŝi Nekonatajn Kampojn';

  @override
  String get showInSeekbar => 'Montri en Serĉbreto';

  @override
  String get showMixPlaylistsIn => 'Montri Miksaĵojn en';

  @override
  String get showMore => 'Montri pli';

  @override
  String get showShortVideosIn => 'Montri Shorts en';

  @override
  String get showSkipButton => 'Montri Preterpasan Butonon';

  @override
  String get showVideoEndcards => 'Montri videajn finajn kartojn';

  @override
  String get showWebm => 'Montri webm';

  @override
  String get shuffle => 'Miksi';

  @override
  String get shuffleAll => 'Miksi Ĉion';

  @override
  String get shuffleNext => 'Miksi Sekvan';

  @override
  String get signIn => 'Ensaluti';

  @override
  String get signInCanceled => 'Ensaluto estis nuligita';

  @override
  String get signInFailed => 'Ensaluto malsukcesis';

  @override
  String get signInToYourAccount => 'Ensalutu al via konto';

  @override
  String get signInYouDontHaveAccount => 'Vi ne havas konton ensalutita';

  @override
  String get signInYouNeedAccountToViewPage => 'Vi bezonas konton por vidi ĉi tiun paĝon';

  @override
  String get signOut => 'Elsaluti';

  @override
  String signOutFromName({required String name}) {
    return 'Elsaluti de $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Ensaluto permesas bazan uzadon';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Akiru fruan aliron per patreon aŭ uzante kuponon';

  @override
  String get similarDiscoverDate => 'Simila Malkovra Dato';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generi trakojn kiuj estis malkovritaj ĉirkaŭ la sama tempo kiel $currentTrack';
  }

  @override
  String get similarTimeRange => 'Simila Tempa Intervalo';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generi trakojn kiujn vi aŭskultis ĉirkaŭ la sama tempo kiel $currentTrack';
  }

  @override
  String get singles => 'Unuopaĵoj';

  @override
  String get size => 'Grandeco';

  @override
  String get skip => 'Preterpasi';

  @override
  String get skipCountTracking => 'Spurado de preterpasa nombro';

  @override
  String get skipSilence => 'Preterpasi Silenton';

  @override
  String get skipSponsorSegmentsInVideos => 'Preterpasi Sponsorajn Segmentojn en Videoj';

  @override
  String get sleepAfter => 'Dormi Post';

  @override
  String get sleepTimer => 'Dormtempon';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Ordigi laŭ';

  @override
  String get source => 'Fonto';

  @override
  String get speed => 'Rapido';

  @override
  String get sponsor => 'Sponsoro';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Gvidlisto';

  @override
  String get staggeredAlbumGridView => 'Ŝancelita Albuma Kradvido';

  @override
  String get start => 'Komenco';

  @override
  String get stats => 'Statistiko';

  @override
  String get statsSubtitle => 'Jen kelkaj informoj pri via biblioteko';

  @override
  String get stop => 'Halti';

  @override
  String get stopAfterThisTrack => 'Halti post ĉi tiu trako';

  @override
  String get stopAfterThisVideo => 'Halti post ĉi tiu video';

  @override
  String get storagePermissionDenied => 'Permeso Rifuzita';

  @override
  String get storagePermissionDeniedSubtitle => 'Bonvolu permesi aliron por povi plenumi ĉi tiun agon';

  @override
  String get stretchLyricsDuration => 'Etendi Kantotekstan Daŭron';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Aboni';

  @override
  String get subscribed => 'Abonita';

  @override
  String get subscriber => 'Abonanto';

  @override
  String get subscribers => 'Abonantoj';

  @override
  String get succeeded => 'Sukcesis';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Subteno';

  @override
  String get supremacy => 'Supereco';

  @override
  String get sussyBaka => 'Bruh neniuj trakoj';

  @override
  String get swipeActions => 'Svingaj Agoj';

  @override
  String get swipeToOpenDrawer => 'Svingu por malfermi tirkeston';

  @override
  String get synced => 'Sinkronigita';

  @override
  String get synopsis => 'Sinoptiko';

  @override
  String get tagFields => 'Etikedaj Kampoj';

  @override
  String get tags => 'Etikedoj';

  @override
  String get tapAction => 'Frapeta Ago';

  @override
  String get tapToSeek => 'Frapetu por serĉi';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Tema Reĝimo';

  @override
  String get themeModeDark => 'Malhela';

  @override
  String get themeModeLight => 'Hela';

  @override
  String get themeModeSystem => 'Sistemo';

  @override
  String get themeSettings => 'Temo';

  @override
  String get themeSettingsSubtitle => 'La ĝenerala etoso de via ludilo';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Ĉi tiu ludlisto havas aktivajn ordigilojn, bonvolu malŝalti ilin antaŭ reordigado.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Ĉi tiu video estas verŝajne forigita aŭ agordita al privata.';

  @override
  String get thumbnails => 'Bildetetoj';

  @override
  String get title => 'Titolo';

  @override
  String get top => 'Supre';

  @override
  String get topComments => 'Supraj komentoj';

  @override
  String get topCommentsSubtitle => 'Montri komentojn supre anstataŭ malsupre';

  @override
  String get topRecentAlbums => 'Supraj Lastatempaj Albumoj';

  @override
  String get topRecentArtists => 'Supraj Lastatempaj Artistoj';

  @override
  String get topRecents => 'Supraj Lastatempaj';

  @override
  String get totalListenTime => 'Totala Aŭskulta Tempo';

  @override
  String get totalListens => 'Totalaj Aŭskultoj';

  @override
  String get totalTracks => 'Totalaj Trakoj';

  @override
  String get totalTracksDuration => 'Totala Traka Daŭro';

  @override
  String get track => 'Trako';

  @override
  String get trackArtistsSeparator => 'Artistaj Disigiloj';

  @override
  String get trackGenresSeparator => 'Ĝenraj Disigiloj';

  @override
  String get trackInfo => 'Traka Info';

  @override
  String get trackNotFound => 'Trako ne trovita';

  @override
  String get trackNumber => 'Traka Numero';

  @override
  String get trackNumberTotal => 'Traka Totalo';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Malnova nomo: \"$oldName\"\n\nNova nomo: \"$newName\"\n\nĈu vi certas?';
  }

  @override
  String get trackPlayMode => 'Luda Reĝimo';

  @override
  String get trackPlayModeSearchResults => 'Serĉaj Rezultoj';

  @override
  String get trackPlayModeSelectedOnly => 'Elektita trako nur';

  @override
  String get trackPlayModeTrackAlbum => 'Albumo de Trako';

  @override
  String get trackPlayModeTrackArtist => 'Ĉefa Artisto de Trako';

  @override
  String get trackPlayModeTrackGenre => 'Ĝenro de Trako';

  @override
  String get trackThumbnailSizeInList => 'Grandeco de Traka Bildeteto';

  @override
  String get trackTileCustomization => 'Traka Kahela Personigo';

  @override
  String get trackTileItemsSeparator => 'Eroj Disigilo';

  @override
  String get tracks => 'Trakoj';

  @override
  String get tracksExcludedByNomedia => 'Trakoj Ekskluditaj per .nomedia';

  @override
  String get tracksInfo => 'Trakaj Info';

  @override
  String get underrated => 'Subtaksita';

  @override
  String get undo => 'Malfari';

  @override
  String get undoChanges => 'Ĉu Malfari Ŝanĝojn?';

  @override
  String get undoChangesDeletedPlaylist => 'Malfari forigitan ludliston';

  @override
  String get undoChangesDeletedQueue => 'Malfari forigitan Vicon';

  @override
  String get undoChangesDeletedTrack => 'Malfari forigitan trakon';

  @override
  String get uniqueArtworkHash => 'Unika Kovrilbilda Haketaĵo';

  @override
  String get unlimited => 'Senlima';

  @override
  String get unlisted => 'Nelistigita';

  @override
  String get unlock => 'Malŝlosi';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Ĝisdatigi';

  @override
  String get updateDirectoryPath => 'Ĝisdatigi dosierujan vojon';

  @override
  String get updateMissingTracksOnly => 'Ĝisdatigi mankantajn trakojn nur';

  @override
  String get updating => 'Ĝisdatigante';

  @override
  String get useCollapsedSettingTiles => 'Uzi Kolapsigitajn Agordajn Kahelojn';

  @override
  String get useMediaStore => 'Uzi Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ tuja indeksada tempo\nx respekto al .nomedia estos devige ŝaltita\nx iuj metadatumaj etikedoj mankos\nx youtube-integriĝo por loka biblioteko ne funkcios';

  @override
  String get usePitchBlack => 'Uzi Tute Nigran';

  @override
  String get usePitchBlackSubtitle => 'Utila por AMOLED-ekranoj.. kaj aspektas pli bone';

  @override
  String get used => 'Uzata';

  @override
  String get value => 'Valoro';

  @override
  String get valueBetween50200 => 'Valoro devus esti inter 50% kaj 200%';

  @override
  String get vibration => 'Vibrado';

  @override
  String get vibrationType => 'Vibrada tipo';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Videa Kaŝmemoro';

  @override
  String get videoCacheFile => 'Kaŝmemorigita Videa Dosiero';

  @override
  String get videoCacheFiles => 'Kaŝmemorigitaj Videaj Dosieroj';

  @override
  String get videoOnly => 'Nur Video';

  @override
  String get videoPlaybackSource => 'Videa Fonto';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Ĉi tio donos prioritaton al lokaj videoj, se ne trovitaj tiam ĝi prenos de youtube';

  @override
  String get videoPlaybackSourceLocal => 'Lokaj Videoj';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle =>
      'Kontrolas ĉu iu videa dosiero (trovita ene de la elektita dosieruja listo) havas dosiernomon kiu enhavas la dosiernomon de la trako';

  @override
  String get videoPlaybackSourceYoutube => 'De Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Kontrolas en traka dosiernomo & komento por iu kongrua youtube-ligilo, videoj estas kaŝmemorigitaj por posta uzo.';

  @override
  String get videoQuality => 'Videa Kvalito';

  @override
  String get videoQualitySubtitle => 'Plej alta kvalito havebla estos elektita.';

  @override
  String get videoQualitySubtitleNote => 'Estas ĉiam bone teni pli da alternativoj kaze ke kvalito ne estas trovita, alie ĝi revenos al la plej malbona kvalito';

  @override
  String get videos => 'Videoj';

  @override
  String get view => 'vido';

  @override
  String get viewAll => 'Vidi Ĉion';

  @override
  String get views => 'vidoj';

  @override
  String get volume => 'Volumo';

  @override
  String get warning => 'Averto';

  @override
  String get waveformBarsCount => 'Ondformaj Bastonoj Nombro';

  @override
  String get webmNoEditTagsSupport => 'WEBM-formato ne subtenas etikdan redaktadon';

  @override
  String get week => 'Semajno';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Jaro';

  @override
  String get yes => 'jes';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Via nuna membreco estas $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Via propra ordo estos perdita, Ĉu vi certas?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Music';

  @override
  String get youtubeSettingsSubtitle => 'Agordu Youtube-sperton';

  @override
  String get youtubeStyleMiniplayer => 'Youtube-stila Miniludilo';

  @override
  String get ytPreferNewComments => 'Preferi novajn komentojn kiam eble';

  @override
  String get ytPreferNewCommentsSubtitle => 'Kaŝmemorigita versio estos uzata nur kiam ne estas konekto';
}
