// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Ukrainian (`uk`).
class AppLocalizationsUk extends AppLocalizations {
  AppLocalizationsUk([String locale = 'uk']) : super(locale);

  @override
  String get about => 'Про додаток';

  @override
  String get active => 'Активний';

  @override
  String get add => 'Додати';

  @override
  String get addAccount => 'Додати обліковий запис';

  @override
  String get addAll => 'Додати все';

  @override
  String get addAllAndRemoveOldOnes => 'Додати все та видалити старе';

  @override
  String get addAsANewPlaylist => 'Додати як новий плейлист';

  @override
  String get addAudioToLocalLibrary => 'Додати аудіо в локальну бібліотеку';

  @override
  String get addFolder => 'Додати теку';

  @override
  String get addLanguage => 'Додати мову';

  @override
  String get addLanguageSubtitle => 'Допоможіть перекласти Namida на Вашу мову';

  @override
  String get addLrcFile => 'Додати LRC-файл';

  @override
  String get addMoreFromThisAlbum => 'Додати ще з цього альбому в чергу';

  @override
  String get addMoreFromThisArtist => 'Додати ще від цього виконавця в чергу';

  @override
  String get addMoreFromThisFolder => 'Додати ще з цієї теки в чергу';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Додати ще з $media в чергу';
  }

  @override
  String get addOnlyMissing => 'Додати тільки відсутні';

  @override
  String get addToFavourites => 'Додати до обраного';

  @override
  String get addToPlaylist => 'Додати в плейлист';

  @override
  String get addTracksAtTheBeginning => 'Додати треки на початку';

  @override
  String get added => 'додано';

  @override
  String get advanced => 'Просунуте';

  @override
  String get advancedSettings => 'Просунуті';

  @override
  String get advancedSettingsSubtitle => 'Просунуті налаштування, не чіпати';

  @override
  String get alarm => 'Будильник';

  @override
  String get album => 'Альбом';

  @override
  String get albumArtist => 'Виконавець альбому';

  @override
  String get albumArtists => 'Виконавці альбому';

  @override
  String get albumIdentifiers => 'Ідентифікатори альбому';

  @override
  String get albumThumbnailSizeInList => 'Розмір мініатюр альбому';

  @override
  String get albumTileCustomization => 'Налаштування плитки альбому';

  @override
  String get albums => 'Альбоми';

  @override
  String get albumsCount => 'Кількість альбомів';

  @override
  String get all => 'Усі';

  @override
  String get allTime => 'За весь час';

  @override
  String get alreadyExists => 'Вже існує';

  @override
  String get always => 'Завжди';

  @override
  String get alwaysAsk => 'Завжди питати';

  @override
  String get alwaysDim => 'Завжди затемнювати';

  @override
  String get alwaysExpandedSearchbar => 'Завжди розгорнута панель пошуку';

  @override
  String get alwaysRestore => 'Завжди відновлювати';

  @override
  String get animatingThumbnailIntensity => 'Інтенсивність анімації мініатюр';

  @override
  String get animatingThumbnailInversed => 'Інверсія анімації';

  @override
  String get animatingThumbnailInversedSubtitle => 'Високі піки призведуть до зменшення розміру мініатюри';

  @override
  String get anotherProcessIsRunning => 'Інший процес уже запущено.';

  @override
  String get appIcon => 'Значок додатка';

  @override
  String get appVersion => 'Версія додатка';

  @override
  String get artist => 'Виконавець';

  @override
  String get artists => 'Виконавці';

  @override
  String get artwork => 'Обкладинка';

  @override
  String get artworkGestures => 'Жести обкладинок';

  @override
  String get artworks => 'Обкладинки';

  @override
  String get audio => 'Аудіо';

  @override
  String get audioCache => 'Кеш аудіо';

  @override
  String get audioOnly => 'Тільки аудіо';

  @override
  String get auto => 'Автоматично';

  @override
  String get autoBackupInterval => 'Інтервал автоматичних резервних копій';

  @override
  String get autoColoring => 'Автоколір';

  @override
  String get autoColoringSubtitle => 'Автоматичний вибір кольорів плеєра на основі обкладинок';

  @override
  String get autoExtractTagsFromFilename => 'Автоматично витягувати з імені файлу';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Автоматично витягувати назву та виконавця з назви відео';

  @override
  String get autoGenerated => 'Автоматично згенерований';

  @override
  String get autoSkip => 'Автопропуск';

  @override
  String get autoSkipOnce => 'Автопропуск один раз';

  @override
  String get autoStartRadio => 'Автозапуск радіо';

  @override
  String get autoStartRadioSubtitle => 'Автоматично додає плейлист «Мікс» під час відтворення одного треку';

  @override
  String get automaticBackup => 'Автоматичний';

  @override
  String get automaticBackupSubtitle => 'Автоматично застосовує останній файл резервної копії, знайдений у місці їх зберігання';

  @override
  String get backupAndRestore => 'Резервне копіювання та відновлення';

  @override
  String get backupAndRestoreSubtitle => 'Резервне копіювання бази даних та налаштувань';

  @override
  String get balanced => 'Збалансований';

  @override
  String get beta => 'Бета';

  @override
  String get betweenDates => 'Між датами';

  @override
  String get bitrate => 'Бітрейт';

  @override
  String get blacklist => 'Чорний список';

  @override
  String get borderRadiusMultiplier => 'Множник радіуса меж';

  @override
  String get cache => 'Кеш';

  @override
  String get cancel => 'Скасувати';

  @override
  String get canceled => 'Скасовано';

  @override
  String get changed => 'Змінено';

  @override
  String get changelog => 'Список змін';

  @override
  String get changelogSubtitle => 'Переглянути, що нового додано/виправлено в Namida';

  @override
  String get channel => 'Канал';

  @override
  String get channels => 'Канали';

  @override
  String get check => 'Перевірити';

  @override
  String get checkForMore => 'Детальніше';

  @override
  String get checkList => 'Контрольний список';

  @override
  String get choose => 'Обрати';

  @override
  String get chooseWhatToClear => 'Обрати, що очистити';

  @override
  String get claim => 'Подати заявку';

  @override
  String get clear => 'Очистити';

  @override
  String get clearAudioCache => 'Очистити кеш аудіо';

  @override
  String get clearImageCache => 'Очистити кеш зображень';

  @override
  String get clearImageCacheWarning => 'Попередження: буде створена бібліотека без зображень. Використовуйте тільки для перебудови кешу зображень.';

  @override
  String get clearTrackItem => 'Видалити у треку';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString треках',
      few: '$numberString треках',
      one: '$numberString треку',
    );
    return 'Очистити у $_temp0';
  }

  @override
  String get clearVideoCache => 'Очистити кеш відео';

  @override
  String get clearVideoCacheNote => 'Ви можете обрати, що видалити.';

  @override
  String get clock => 'Годинник';

  @override
  String get colorPalette => 'Кольорова палітра';

  @override
  String get colorPaletteNote1 => 'Натисніть і утримуйте колір, щоб прибрати його';

  @override
  String get colorPaletteNote2 => 'Натисніть на мікс, щоб використовувати його як колір за замовчуванням';

  @override
  String get colorPalettes => 'Кольорові палітри';

  @override
  String get comment => 'Коментар';

  @override
  String get comments => 'Коментарі';

  @override
  String get composer => 'Композитор';

  @override
  String get compress => 'Стиснути';

  @override
  String get compressImages => 'Стиснути зображення';

  @override
  String get compressionPercentage => 'Відсоток стиснення';

  @override
  String get configure => 'Налаштувати';

  @override
  String get confirm => 'ОК';

  @override
  String get confirmRefresh => 'Підтвердити оновлення?';

  @override
  String get copiedArtwork => 'Обкладинку скопійовано';

  @override
  String get copiedToClipboard => 'Скопіювати в буфер обміну';

  @override
  String get copy => 'Скопіювати';

  @override
  String get corruptedFile => 'Не вдалося прочитати файл. Можливо, він пошкоджений';

  @override
  String get couldntOpen => 'Не вдалося відкрити :(';

  @override
  String get couldntOpenYtLink => 'Для цього треку не встановлено YouTube-посилання';

  @override
  String get couldntPlayFile => 'Не вдалося відтворити файл';

  @override
  String get couldntRenamePlaylist => 'Не вдалося перейменувати плейлист';

  @override
  String get couldntSaveImage => 'Не вдалося зберегти зображення';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString виконавців',
      few: '$countString виконавці',
      one: '$countString виконавець',
    );
    return '$_temp0 альбому';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString альбомів',
      few: '$countString альбоми',
      one: '$countString альбом',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString виконавців',
      few: '$countString виконавці',
      one: '$countString виконавець',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString композиторів',
      few: '$countString композитори',
      one: '$countString композитор',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString днів',
      few: '$countString дні',
      one: '$countString день',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString файлів',
      few: '$countString файли',
      one: '$countString файл',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString тек',
      few: '$countString теки',
      one: '$countString тека',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString жанрів',
      few: '$countString жанри',
      one: '$countString жанр',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString місяців',
      few: '$countString місяці',
      one: '$countString місяць',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString плейлистів',
      few: '$countString плейлисти',
      one: '$countString плейлист',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString підписників',
      few: '$countString підписники',
      one: '$countString підписник',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString підписників',
      few: '$countString підписники',
      one: '$countString підписник',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString треків',
      few: '$countString треки',
      one: '$countString трек',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString відео',
      few: '$countString відео',
      one: '$countString відео',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString переглядів',
      few: '$countString перегляди',
      one: '$countString перегляд',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString переглядів',
      few: '$countString перегляди',
      one: '$countString перегляд',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Країна';

  @override
  String get coupon => 'Купон';

  @override
  String get create => 'Створити';

  @override
  String get createBackup => 'Створити резервну копію';

  @override
  String get createNewPlaylist => 'Створити новий плейлист';

  @override
  String get createdBackupSuccessfully => 'Резервну копію створено';

  @override
  String get createdBackupSuccessfullySub => 'Резервну копію успішно створено';

  @override
  String get crossPlatformSync => 'Синхронізація між платформами';

  @override
  String get crossfadeDuration => 'Тривалість згасаючого переходу';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString останні секунд',
      few: '$secondsString останні секунди',
      one: '$secondsString останню секунду',
    );
    return 'Автоматично вмикати згасаючий перехід за $_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Не запускати згасаючий перехід автоматично';

  @override
  String get custom => 'Користувацький';

  @override
  String get customizations => 'Персоналізація';

  @override
  String get customizationsSubtitle => 'Налаштуйте зовнішній вигляд свого плеєра під себе';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Дані надано: $name';
  }

  @override
  String get dataSaver => 'Заощадження трафіку';

  @override
  String get dataSaverMode => 'Режим заощадження трафіку';

  @override
  String get database => 'База даних';

  @override
  String get date => 'Дата';

  @override
  String get dateAdded => 'Дата додавання';

  @override
  String get dateCreated => 'Дата створення';

  @override
  String get dateModified => 'Дата зміни';

  @override
  String get dateTimeFormat => 'Формат дати і часу';

  @override
  String get day => 'День';

  @override
  String get days => 'Днів';

  @override
  String get defaultBackupLocation => 'Розташування резервних копій за замовчуванням';

  @override
  String get defaultColor => 'Тема за замовчуванням';

  @override
  String get defaultColorSubtitle => 'Встановлення кольору, що буде використовуватись плеєром';

  @override
  String get defaultDownloadLocation => 'Папка для завантаження за замовчуванням';

  @override
  String get defaultLabel => 'За замовчуванням';

  @override
  String get defaultLibraryTab => 'Бібліотека за замовчуванням';

  @override
  String get delete => 'Видалити';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString файлів, які займають',
      few: '$countString файли, які займають',
      one: '$countString файл, який займає',
    );
    return 'Видалити $_temp0 $totalSizeText?';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Назавжди видалити $numberText зі сховища';
  }

  @override
  String get deletePlaylist => 'Видалити плейлист';

  @override
  String get deleteTempFiles => 'Видалити тимчасові файли';

  @override
  String get deleted => 'Видалено';

  @override
  String get description => 'Опис';

  @override
  String get developer => 'Розробник';

  @override
  String get development => 'Розробка';

  @override
  String get didYouMean => 'Можливо, Ви мали на увазі';

  @override
  String get dimIntensity => 'Інтенсивність затемнення';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString секунд',
      few: '$secondsString секунди',
      one: '$secondsString секунду',
    );
    return 'Затемняти мініплеєр через $_temp0 бездіяльності';
  }

  @override
  String get directoryDoesntExist => 'Каталог не існує';

  @override
  String get disable => 'Вимкнути';

  @override
  String get disableAll => 'Вимкнути всі';

  @override
  String get disableReordering => 'Вимкнути впорядкування';

  @override
  String get disableSearchCleanup => 'Вимкнути очистку пошуку';

  @override
  String get discNumber => 'Номер диска';

  @override
  String get discNumberTotal => 'Усього дисків';

  @override
  String get discover => 'Огляд';

  @override
  String get dislike => 'Не подобається';

  @override
  String get dismissibleMiniplayer => 'Мініплеєр, який можна закрити';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Відображати фактичну позицію замість різниці під час пошуку';

  @override
  String get displayAlbumCardTopRightDate => 'Дата альбому в правому верхньому кутку картки';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Відображати дату альбому в правому верхньому кутку картки альбому';

  @override
  String get displayArtistBeforeTitle => 'Відображати виконавця перед назвою';

  @override
  String get displayArtworkOnLockscreen => 'Відображати обкладинку на екрані блокування';

  @override
  String get displayAudioInfoInMiniplayer => 'Відображати інформацію про аудіо';

  @override
  String get displayFavButtonInNotification => 'Відображати кнопку «Обране» в сповіщеннях';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Мініатюра може бути зміщена.';

  @override
  String get displayFavouriteIconInTrackTile => 'Відображати кнопку «Обране»';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Відображати тривалість що залишилася, замість загальної';

  @override
  String get displayStopButtonInNotification => 'Показувати кнопку «Стоп» у сповіщеннях';

  @override
  String get displayThirdItemInRowInTrackTile => 'Відображати третій елемент у кожному рядку';

  @override
  String get displayThirdRowInTrackTile => 'Відображати третій рядок';

  @override
  String get displayTrackNumberInAlbumPage => 'Відображати номер треку на сторінці альбому';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Відображати невелике поле з номером треку на сторінці альбому';

  @override
  String get doNothing => 'Нічого не робити';

  @override
  String get donate => 'Пожертвуйте';

  @override
  String get donateSubtitle => 'Якщо вважаєте, що це того варте';

  @override
  String get done => 'Готово';

  @override
  String get dontAskAgain => 'Більше не питати';

  @override
  String get dontDim => 'Не затемнювати';

  @override
  String get dontRestorePosition => 'Не відновлювати';

  @override
  String get dontResume => 'Не продовжувати відтворення';

  @override
  String get doubleTapToToggleLyrics => 'Подвійний тап для відображення тексту пісні';

  @override
  String get download => 'Завантажити';

  @override
  String get downloadingWillOverrideIt => 'Завантаження перезапише його';

  @override
  String get downloads => 'Завантаження';

  @override
  String get downloadsMetadataTags => 'Завантажити теги метаданих';

  @override
  String get downloadsMetadataTagsSubtitle => 'За замовчуванням витягувати виконавця, назву та альбом з інформації про відео';

  @override
  String get dragToSeek => 'Перетягуйте для перемотування';

  @override
  String get duckAudio => 'Приглушувати аудіо';

  @override
  String get duplicatedItemsAdding => 'Ви намагаєтеся додати елементи, що вже є в плейлисті';

  @override
  String get duplicatedTracks => 'Дубльовані треки';

  @override
  String get duration => 'Тривалість';

  @override
  String get edgeColorsSwitching => 'Перемикання кольорів по краях';

  @override
  String get edit => 'Редагувати';

  @override
  String get editArtwork => 'Редагувати обкладинку';

  @override
  String get editTags => 'Редагувати теги';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'Є поля з порожніми/незначними значеннями, переконайтеся, що Ви дійсно хочете їх редагувати';

  @override
  String get emptyValue => 'Порожнє значення';

  @override
  String get enableArtworkCache => 'Увімкнути кеш обкладинок';

  @override
  String get enableArtworkCacheSubtitle => 'Швидше завантажується і покращує продуктивність, але займає більше місця у сховищі';

  @override
  String get enableBlurEffect => 'Увімкнути ефект розмиття';

  @override
  String get enableBottomNavBar => 'Увімкнути нижню панель навігації';

  @override
  String get enableBottomNavBarSubtitle => 'Елементи знаходяться в обох діалогових вікнах';

  @override
  String get enableClipboardMonitoring => 'Увімкнути моніторинг буфера обміну';

  @override
  String get enableClipboardMonitoringSubtitle => 'Дозволяє вставляти посилання та текст у поле пошуку на льоту';

  @override
  String get enableCrossfadeEffect => 'Увімкнути ефект переходу з згасанням';

  @override
  String get enableFadeEffectOnPlayPause => 'Увімкнути ефект згасання при відтворенні/паузі';

  @override
  String get enableFoldersHierarchy => 'Увімкнути ієрархію тек';

  @override
  String get enableGlowEffect => 'Увімкнути ефект світіння';

  @override
  String get enableM3uSync => 'Увімкнути синхронізацію M3U';

  @override
  String get enableM3uSyncNote1 => 'Синхронізація M3U дозволяє зберігати зміни плейлиста в оригінальному M3U-файлі';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Якщо щось пішло не так, резервну копію цього плейлиста можна буде знайти в $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'У випадку відмови всі зміни, зроблені в цьому плейлисті, будуть втрачені при перезавантаженні';

  @override
  String get enableMiniplayerParticles => 'Увімкнути рухливі частинки';

  @override
  String get enableParallaxEffect => 'Увімкнути ефект паралаксу';

  @override
  String get enablePartyMode => 'Увімкнути режим вечірки';

  @override
  String get enablePartyModeSubtitle => 'Увімкнути ефект дихання країв';

  @override
  String get enablePictureInPicture => 'Увімкнути «Картинку в картинці»';

  @override
  String get enableReordering => 'Дозволити впорядкування';

  @override
  String get enableReturnYoutubeDislike => 'Увімкнути кнопку «Не подобається» на YouTube';

  @override
  String get enableSearchCleanup => 'Увімкнути очистку пошуку';

  @override
  String get enableSearchCleanupSubtitle => 'Усі символи та пробіли будуть проігноровані';

  @override
  String get enableSponsorblock => 'Увімкнути SponsorBlock';

  @override
  String get enableVideoPlayback => 'Увімкнути відтворення відео';

  @override
  String get enterSymbol => 'Будь ласка, введіть символ';

  @override
  String get equalizer => 'Еквалайзер';

  @override
  String get error => 'Помилка';

  @override
  String get errorFetchingVideoList => 'Помилка при отриманні списку відео';

  @override
  String get errorPlayingTrack => 'Помилка відтворення треку';

  @override
  String get excludedFodlers => 'Виключені теки';

  @override
  String get exit => 'Вихід';

  @override
  String get exitAppSubtitle => 'Натисніть ще раз, щоб вийти';

  @override
  String get expandedMiniplayer => 'Розгорнутий мініплеєр';

  @override
  String get exportAsM3u => 'Експорт у форматі M3U';

  @override
  String get extension => 'Розширення';

  @override
  String get externalFiles => 'Зовнішні файли';

  @override
  String get extract => 'Витягти';

  @override
  String get extractAllColorPalettes => 'Витягти всі кольорові палітри';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString палітр',
      few: '$numberString палітри',
      one: '$numberString палітру',
    );
    return 'Витягти решту $_temp0?';
  }

  @override
  String get extractFeatArtist => 'Витягти виконавців з назви';

  @override
  String get extractFeatArtistSubtitle => 'Витягти (feat. X) та (ft. X) виконавців у вигляді запису нового виконавця.';

  @override
  String get extractingInfo => 'Витяг інформації';

  @override
  String get extras => 'Додатково';

  @override
  String get extrasSubtitle => 'Додаткові налаштування для покращення Вашого досвіду';

  @override
  String get extreme => 'Екстремальний';

  @override
  String get failed => 'Не вдалося';

  @override
  String get failedEdits => 'Невдалі зміни';

  @override
  String get favourites => 'Обране';

  @override
  String get features => 'Функції';

  @override
  String get fetching => 'Витягти';

  @override
  String get fetchingOfAllVideos => 'Отримання всіх відео';

  @override
  String get file => 'Файл';

  @override
  String get fileAlreadyExists => 'Файл уже існує';

  @override
  String get fileBasedServerWarning =>
      'Файли будуть тимчасово завантажені для індексації. Переконайтеся, що з’єднання стабільне.\nРекомендується використовувати Wi-Fi, щоб уникнути значного використання даних.';

  @override
  String get fileName => 'Назва файлу';

  @override
  String get fileNameWoExt => 'Назва файлу без розширення';

  @override
  String get filenameShouldntStartWith => 'Назва файлу не повинна починатися з';

  @override
  String get files => 'Файли';

  @override
  String get filler => 'Філер';

  @override
  String get filterAlbums => 'Відфільтрувати альбоми';

  @override
  String get filterArtists => 'Відфільтрувати виконавців';

  @override
  String get filterGenres => 'Відфільтрувати жанри';

  @override
  String get filterPlaylists => 'Відфільтрувати плейлисти';

  @override
  String get filterTracks => 'Відфільтрувати треки';

  @override
  String get filterTracksBy => 'Відфільтрувати треки в списках пошуку за';

  @override
  String get filtered => 'Відфільтровані';

  @override
  String get filteredBySizeAndDuration => 'Треки, відфільтровані за розміром і тривалістю';

  @override
  String get finished => 'Завершено';

  @override
  String get finishedUpdatingLibrary => 'Оновлення бібліотеки завершено';

  @override
  String get firstListen => 'Перше прослуховування';

  @override
  String get fixYtdlpBigThumbnailSize => 'Виправити великий розмір мініатюри yt-dlp';

  @override
  String get floatingActionButton => 'Плаваюча кнопка дії';

  @override
  String get folder => 'Тека';

  @override
  String get folderName => 'Назва теки';

  @override
  String get folders => 'Теки';

  @override
  String get fontScale => 'Розмір шрифту';

  @override
  String get forceMiniplayerFollowTrackColors => 'Змусити мініплеєр використовувати кольори треку';

  @override
  String get forceSquaredAlbumThumbnail => 'Примусово зробити мініатюру альбому квадратною';

  @override
  String get forceSquaredThumbnailNote => 'Розмір мініатюри та висота плитки НЕ збігаються, квадратний вигляд може не відповідати очікуванням. Ви точно хочете зрівняти їх?';

  @override
  String get forceSquaredTrackThumbnail => 'Примусово зробити мініатюру треку квадратною';

  @override
  String get forceStopColorPaletteGeneration => 'Примусово припинити витяг кольорових палітр? Ви можете продовжити це пізніше';

  @override
  String get format => 'Формат';

  @override
  String get fullscreen => 'На весь екран';

  @override
  String get gaplessPlayback => 'Відтворення без пауз';

  @override
  String get generate => 'Згенерувати';

  @override
  String get generateFromDates => 'Діапазон часу';

  @override
  String get generateFromDatesSubtitle => 'Згенерувати треки, прослухані в певному часовому діапазоні';

  @override
  String get generateRandomPlaylist => 'Згенерувати випадковий плейлист';

  @override
  String get genre => 'Жанр';

  @override
  String get genres => 'Жанри';

  @override
  String get goToAlbum => 'Перейти до альбому';

  @override
  String get goToArtist => 'Перейти до виконавця';

  @override
  String get goToChannel => 'Перейти на канал';

  @override
  String get goToFolder => 'Перейти до теки';

  @override
  String get goodLooking => 'Виглядає добре';

  @override
  String get grantStoragePermission => 'Надати дозвіл на використання сховища';

  @override
  String get group => 'Група';

  @override
  String get groupArtworksByAlbum => 'Групувати обкладинки за альбомом';

  @override
  String get guide => 'Посібник';

  @override
  String get hapticFeedback => 'Тактильний відгук';

  @override
  String get heightOfAlbumTile => 'Висота альбомної плитки';

  @override
  String get heightOfTrackTile => 'Висота плиток для треків';

  @override
  String get hideSkipButtonAfter => 'Прибирати кнопку «Пропустити» через';

  @override
  String get highMatches => 'Високі показники відповідності';

  @override
  String get highPerformance => 'Висока продуктивність';

  @override
  String get highlight => 'Рекомендована сцена';

  @override
  String get history => 'Історія';

  @override
  String get historyImportMissingEntriesNote => 'Не вдалося знайти такі записи в бібліотеці. Якщо Ви вважаєте, що вони існують, будь ласка, додайте їх вручну';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString прослуховувань $oldTrackInfo',
      few: '$listensCountString прослуховування $oldTrackInfo',
      one: '$listensCountString прослуховування $oldTrackInfo',
    );
    return '$_temp0 буде змінено на $newTrackInfo. Продовжити?';
  }

  @override
  String get home => 'Головна';

  @override
  String get hook => 'Захопливий початок';

  @override
  String get host => 'Хост';

  @override
  String get hourFormat12 => '12-годинний формат';

  @override
  String get hours => 'Годин';

  @override
  String get iReadAndAgree => 'Я прочитав та погоджуюсь';

  @override
  String get ifNotPlaying => 'Якщо не відтворюється';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Завантаження може бути обмежено, якщо для додатка обмежено споживання заряду акумулятора';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ігнорувати поширені префікси під час сортування';

  @override
  String get ignores => 'Ігнорує';

  @override
  String get imageSource => 'Джерело зображень';

  @override
  String get immersiveMode => 'Режим занурення';

  @override
  String get immersiveModeSubtitle => 'Приховує статусну та навігаційну панелі при розгорнутому мініплеєрі';

  @override
  String get import => 'Імпорт';

  @override
  String get importAll => 'Імпортувати все';

  @override
  String get importLastFmHistory => 'Імпорт історії LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Перейдіть на сторінку $lastfmCsvLink\n\n2. Уведіть своє ім’я користувача, отримайте та завантажте файл CSV.\n\n3. Оберіть файл на наступному екрані.';
  }

  @override
  String get importTimeRange => 'Імпортувати діапазон часу';

  @override
  String get importYoutubeHistory => 'Імпорт історії YouTube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Перейдіть за посиланням $takeoutLink\n\n2. Натисніть «Декілька форматів» та навпроти «Історія» оберіть «JSON».\n\n3. Натисніть кнопку «Обрані всі дані YouTube», натисніть на «Скасувати вибір» та оберіть «Тільки історію».\n\n4. Створіть Експорт, завантажте та розархівуйте.\n\n5. На наступному екрані оберіть «watch-history.json».';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString каналів',
      few: '$numberString канали',
      one: '$numberString канал',
    );
    return '$_temp0 імпортовано успішно';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText плейлистів',
      few: '$numberText плейлисти',
      one: '$numberText плейлист',
    );
    return '$_temp0 імпортовано успішно';
  }

  @override
  String get includeVideos => 'Включити відео';

  @override
  String get indexRefreshRequired => 'Виконайте оновлення після зміни цього параметра';

  @override
  String get indexer => 'Індексатор';

  @override
  String get indexerNote => 'Примітка: неповна кількість обкладинок відноситься до дубльованих та незнайдених обкладинок';

  @override
  String get indexerSubtitle => 'Керування музичною бібліотекою';

  @override
  String get infinityQueueOnNextPrev => 'Безкінечна черга на наступний/попередній';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'При натисканні кнопки «Наступний» під час відтворення останнього елемента відбувається перехід до першого, та навпаки';

  @override
  String get info => 'Інформація';

  @override
  String get inserted => 'Введено';

  @override
  String get instantlyApplies => 'Миттєво застосувати';

  @override
  String get interactionReminder => 'Нагадування про взаємодію';

  @override
  String get intro => 'Вступ';

  @override
  String get invertSelection => 'Інвертувати виділення';

  @override
  String get issues => 'Проблеми';

  @override
  String get item => 'Елемент';

  @override
  String get jump => 'Перейти';

  @override
  String get jumpToDay => 'Перейти до дня';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Перейти до першого треку після завершення черги';

  @override
  String get keepCachedVersions => 'Зберігати кешовані версії';

  @override
  String get keepFileDates => 'Зберігати дати файлів';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Мініплеєр розгорнутий';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Мініплеєр розгорнутий та відворюється відео';

  @override
  String get keepScreenAwakeNone => 'Не тримати екран увімкненим';

  @override
  String get keepScreenAwakeWhen => 'Тримати екран увімкненим, коли';

  @override
  String get killPlayerAfterDismissingApp => 'Закривати плеєр після виходу з додатка';

  @override
  String get language => 'Мова';

  @override
  String get learnMore => 'Дізнатися більше';

  @override
  String get leftAction => 'Провести ліворуч';

  @override
  String get legacyAuthentication => 'Стара система автентифікації';

  @override
  String get libraryTabs => 'Вкладки бібліотеки';

  @override
  String get libraryTabsReorder => 'Можна змінити порядок активних вкладок.';

  @override
  String get license => 'Ліцензія';

  @override
  String get licenseSubtitle => 'Ліцензії та угоди, що використовуються Namida';

  @override
  String get like => 'Подобається';

  @override
  String get liked => 'Вподобані';

  @override
  String get link => 'Посилання';

  @override
  String get listOfFolders => 'Список тек';

  @override
  String get loadAll => 'Завантажити все';

  @override
  String get loadingFile => 'Завантаження файлу';

  @override
  String get local => 'Локально';

  @override
  String get localVideoMatching => 'Локальне зіставлення відео';

  @override
  String get login => 'Логін';

  @override
  String get longPressAction => 'Тривале натискання';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Натисніть і утримуйте текст пісні для переходу в повноекранний режим';

  @override
  String get lostMemories => 'Давно прослухане';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString років',
      few: '$numberString роки',
      one: '$numberString рік',
    );
    return 'Приблизно в цей час, $_temp0 тому';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Підсилення гучності';

  @override
  String get lyricist => 'Автор тексту';

  @override
  String get lyrics => 'Текст пісні';

  @override
  String get lyricsSource => 'Джерело тексту';

  @override
  String get m3uPlaylist => 'Плейлист M3U';

  @override
  String get makeYourFirstListen => 'Прослухай вперше!';

  @override
  String get manage => 'Керувати';

  @override
  String get manageYourAccounts => 'Керувати обліковими записами';

  @override
  String get manualBackup => 'Ручний';

  @override
  String get manualBackupSubtitle => 'оберіть конкретний файл';

  @override
  String get markAsRead => 'Позначити як прочитане';

  @override
  String get matchAllTracks => 'Співставити всі треки';

  @override
  String get matchAllTracksNote => 'Це може вплинути на швидкість співставлення, оскільки при цьому будуть перевірятись усі треки у Вашій бібліотеці';

  @override
  String get matchingType => 'Тип відповідності';

  @override
  String get maxAudioCacheSize => 'Максимальний розмір кешу аудіо';

  @override
  String get maxImageCacheSize => 'Максимальний розмір кешу зображень';

  @override
  String get maxVideoCacheSize => 'Максимальний розмір кешу відео';

  @override
  String get maximum => 'Максимум';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Увімкнено сховище медіафайлів, тому це налаштування не діятиме';

  @override
  String get medium => 'Помірний';

  @override
  String get membershipCode => 'Код';

  @override
  String get membershipCodeSentToEmail => 'Код надіслано на Вашу електронну пошту';

  @override
  String get membershipDidntChange => 'Участь не змінилася';

  @override
  String get membershipEnjoyNew => 'Вітаємо з новою участю';

  @override
  String get membershipFreeCoupon => 'Безкоштовний купон';

  @override
  String get membershipManage => 'Керувати своєю участю';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Для цього користувача не знайдено підписок';

  @override
  String get membershipSignInToPatreonAccount => 'Увійдіть у свій обліковий запис Patreon';

  @override
  String get membershipUnknown => 'Невідома участь';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Щоб додати кілька облікових записів, Вам потрібно бути учасником $name1 або $name2';
  }

  @override
  String get merge => 'Об’єднати';

  @override
  String get metadataCache => 'Кеш метаданих';

  @override
  String get metadataEditFailed => 'Не вдалося відредагувати метадані';

  @override
  String get metadataReadFailed => 'Не вдалося прочитати метадані';

  @override
  String get minFileDuration => 'Мінімальна тривалість треку';

  @override
  String get minFileSize => 'Мінімальний розмір файлу';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Мінімальна тривалість треку для продовження відтворення з минулого момента';

  @override
  String get minValueCantBeMoreThanMax => 'Мінімальне значення не може бути більше максимального';

  @override
  String get minValueToCountTrackListen => 'Вважати, що трек прослуханий через: ';

  @override
  String get minimizedMiniplayer => 'Мінімізований мініплеєр';

  @override
  String get minimum => 'Мінімум';

  @override
  String get minimumOneFolderSubtitle => 'Повинна бути хоча б одна тека. Додайте ще теки, якщо хочете видалити цю';

  @override
  String get minimumOneItem => 'Не вдалося видалити елемент';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString елементів',
      few: '$numberString елементів',
      one: '$numberString елемента',
    );
    return 'Повинно залишатися не менше $_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Мінімальна тривалість фрагмента';

  @override
  String get miniplayerCustomization => 'Налаштування мініплеєра';

  @override
  String get minutes => 'хвилин';

  @override
  String get missingEntries => 'Відсутні записи';

  @override
  String get missingTracks => 'Відсутні треки';

  @override
  String get mix => 'Мікс';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Плейлист «Мікс», згенерований на YouTube';

  @override
  String get mixes => 'Мікси';

  @override
  String get mobile => 'Мобільний';

  @override
  String get month => 'Місяць';

  @override
  String get months => 'Місяці';

  @override
  String get mood => 'Настрій';

  @override
  String get moods => 'Настрої';

  @override
  String get more => 'Детальніше';

  @override
  String get mostPlayed => 'Відтворювані частіше всього';

  @override
  String get multipleTracksTagsEditNote => 'Ви збираєтеся редагувати ці треки,\nНезмінені поля залишаться недоторканими.';

  @override
  String get musicOfftopic => 'Музичний офтопік';

  @override
  String get name => 'Назва';

  @override
  String get nameContainsBadCharacter => 'Назва містить недопустимий символ';

  @override
  String get never => 'Ніколи';

  @override
  String get newDirectory => 'Новий каталог';

  @override
  String get newLabel => 'Нові';

  @override
  String get newTracksAdd => 'Додати треки';

  @override
  String get newTracksMoods => 'Настрій';

  @override
  String get newTracksMoodsSubtitle => 'Згенерувати треки на основі настроїв';

  @override
  String get newTracksRandom => 'Випадково';

  @override
  String get newTracksRandomSubtitle => 'Вибір випадкових треків з бібліотеки';

  @override
  String get newTracksRatings => 'Оцінки';

  @override
  String get newTracksRatingsSubtitle => 'Згенерувати треки з певним рейтингом';

  @override
  String get newTracksRecommended => 'Рекомендовані';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Згенерувати треки, котрі Ви зазвичай слухаєте з $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Схожа дата виходу';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Згенерувати треки, котрі були випущені приблизно в той же час, що й $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Рік випуску треку невідомий';

  @override
  String get newest => 'Найновіші';

  @override
  String get next => 'Далі';

  @override
  String get no => 'ні';

  @override
  String get noChangesFound => 'Змін не знайдено.';

  @override
  String get noEnoughTracks => 'У Вас не так багато треків.';

  @override
  String get noExcludedFolders => 'У Вас немає виключених тек';

  @override
  String get noFolderChosen => 'Ви не обрали жодної теки';

  @override
  String get noMoodsAvailable => 'Настрої відсутні';

  @override
  String get noNetworkAvailableToFetchData => 'Немає доступу до мережі, щоб отримати дані';

  @override
  String get noTracksFound => 'Треки не знайдено';

  @override
  String get noTracksFoundBetweenDates => 'У цьому часовому діапазоні немає треків.';

  @override
  String get noTracksFoundInDirectory => 'У цьому каталозі не знайдено жодного треку';

  @override
  String get noTracksInHistory => 'У Вас недостатньо треків в історії';

  @override
  String get nonActive => 'Неактивний';

  @override
  String get nonFavourites => 'Необране';

  @override
  String get none => 'Нічого';

  @override
  String get normalizeAudio => 'Нормалізація звуку';

  @override
  String get normalizeAudioSubtitle => 'Нормалізує гучність, зчитуючи тег посилення відтворення або інформацію, надану YouTube';

  @override
  String get notAvailableForYourDevice => 'Недоступно для Вашого пристрою';

  @override
  String get notSupportedForNetworkFiles => 'Не підтримується для мережевих файлів';

  @override
  String get note => 'Примітка';

  @override
  String get notification => 'Сповіщення';

  @override
  String get notifications => 'Сповіщення';

  @override
  String get numberOfTracks => 'Кількість треків';

  @override
  String get ofLabel => 'з';

  @override
  String get offlineSearch => 'Офлайн-пошук';

  @override
  String get offset => 'Зміщення звуку';

  @override
  String get oldDirectory => 'Старий каталог';

  @override
  String get oldDirectoryStillHasTracks => 'У старому каталозі все ще є треки. Продовжити?';

  @override
  String get oldestWatch => 'Переглянуті найдавніше';

  @override
  String get onDeviceConnect => 'При підключенні пристрою';

  @override
  String get onInterruption => 'При перериванні';

  @override
  String get onNotificationTap => 'При натисканні на сповіщення';

  @override
  String get onOpeningYoutubeLink => 'При відкритті YouTube-посилання';

  @override
  String get onSwiping => 'Дії гортанням';

  @override
  String get onVolumeZero => 'При гучності 0';

  @override
  String get ongoing => 'У процесі';

  @override
  String get open => 'Відкрити';

  @override
  String get openApp => 'Відкрити додаток';

  @override
  String get openInFileExplorer => 'Відкрити у файловому менеджері';

  @override
  String get openInYoutubeView => 'Відкрити в режимі перегляду YouTube';

  @override
  String get openMiniplayer => 'Відкрити мініплеєр';

  @override
  String get openQueue => 'Відкрити чергу';

  @override
  String get openYoutubeLink => 'Відкрити посилання YouTube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Для виконання $name потрібен обліковий запис. Увійдіть, щоб продовжити';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Для виконання $operation необхідна принаймні участь $name';
  }

  @override
  String get or => 'або';

  @override
  String get others => 'Інші';

  @override
  String get output => 'Вивід';

  @override
  String get outro => 'Завершальні титри';

  @override
  String get overrideOldFilesInTheSameFolder => 'Перезаписати старі файли в тій самій теці';

  @override
  String get palette => 'Палітра';

  @override
  String get paletteMix => 'Мікс';

  @override
  String get paletteNewMix => 'Новий мікс';

  @override
  String get paletteSelectedMix => 'Обраний мікс';

  @override
  String get parallelDownloads => 'Паралельні завантаження';

  @override
  String get parsed => 'розібраний';

  @override
  String get password => 'Пароль';

  @override
  String get path => 'Повний шлях до файлу';

  @override
  String get pause => 'Зупинити';

  @override
  String get pauseFadeDuration => 'Продовжити згасання при паузі';

  @override
  String get pausePlayback => 'Призупинити відтворення';

  @override
  String get percentage => 'Відсоток';

  @override
  String get performanceMode => 'Продуктивний режим';

  @override
  String get performanceNote => 'Може вплинути на продуктивність';

  @override
  String get personalized => 'Персоналізований';

  @override
  String get personalizedRelatedVideos => 'Персоналізовані схожі відео';

  @override
  String get personalizedRelatedVideosSubtitle => 'Якщо вимкнено, зростає використання даних';

  @override
  String get pickColorsFromDeviceWallpaper => 'Обрати колір зі шпалер на пристрої';

  @override
  String get pickFromStorage => 'Обрати зі сховища';

  @override
  String get pinned => 'Закріплено';

  @override
  String get pitch => 'Висота';

  @override
  String get plain => 'Звичайний';

  @override
  String get play => 'Відтворити';

  @override
  String get playAfter => 'Відтворити після';

  @override
  String get playAfterNextPrev => 'Автовідтворення при наступному/попередньому';

  @override
  String get playAll => 'Відтворити все';

  @override
  String get playFadeDuration => 'Тривалість згасання відтворення';

  @override
  String get playLast => 'Відтворити останнім';

  @override
  String get playNext => 'Відтворити наступним';

  @override
  String get playbackSetting => 'Відтворення';

  @override
  String get playbackSettingSubtitle => 'Доступ до них можливий безпосередньо в плеєрі шляхом тривалого натискання кнопки аудіо';

  @override
  String get playlist => 'Плейлист';

  @override
  String get playlists => 'Плейлисти';

  @override
  String get playlistsImportM3uNative => 'Імпорт плейлистів M3U для використання тільки в Namida. Використовуйте, якщо мігруєте';

  @override
  String get playlistsImportM3uSynced =>
      'Автоматичний імпорт плейлистів M3U з тек індексатора та синхронізація їх з оригінальним файлом M3U. Використовуйте, якщо отримуєте доступ/модифікуєте плейлисти з інших додатків';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Автоматичний імпорт плейлистів M3U';

  @override
  String get pleaseEnterADifferentName => 'Така назва вже існує :(\nБудь ласка, спробуйте іншу, незвичну назву';

  @override
  String get pleaseEnterALink => 'Будь ласка, введіть посилання';

  @override
  String get pleaseEnterALinkSubtitle => 'Емм... Це точно посилання на YouTube?';

  @override
  String get pleaseEnterAName => 'Будь ласка, введіть назву';

  @override
  String get port => 'Порт';

  @override
  String get preventDuplicatedTracks => 'Запобігати дублюванню треків';

  @override
  String get preventDuplicatedTracksSubtitle => 'Використовує назву файлу для однозначної ідентифікації треків';

  @override
  String get preview => 'Передперегляд';

  @override
  String get previous => 'Попередній';

  @override
  String get previousButtonReplays => 'Перезавантажувати трек при виборі попереднього треку';

  @override
  String get previousButtonReplaysSubtitle => 'Якщо натиснуто, коли поточна позиція більше довжини перемотки';

  @override
  String get prioritizeEmbeddedLyrics => 'Пріоритезувати вбудований текст пісні';

  @override
  String get priority => 'Пріоритет';

  @override
  String get private => 'Приватний';

  @override
  String get progress => 'Прогрес';

  @override
  String get promptToChangeTrackPath => 'Зазвичай це відбувається, коли Ви видаляєте / переміщуєте / перейменовуєте файл поза Namida. Хочете оновити поточний шлях?';

  @override
  String get public => 'Публічний';

  @override
  String get queue => 'Черга';

  @override
  String get queues => 'Черги';

  @override
  String get random => 'Випадково';

  @override
  String get randomPicks => 'Випадковий вибір';

  @override
  String get rating => 'Оцінка';

  @override
  String get reIndex => 'Переіндексувати';

  @override
  String get reIndexSubtitle => 'Перезбирає музичну бібліотеку з нуля';

  @override
  String get reIndexWarning => 'Цей процес може зайняти певний час, в залежності від розміру Вашої бібліотеки.\n\nОбкладинки не будуть переіндексовані, поки вони існують';

  @override
  String get recentAlbums => 'Нещодавні альбоми';

  @override
  String get recentArtists => 'Нещодавні виконавці';

  @override
  String get recentListens => 'Нещодавно прослухане';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Нещодавно додані';

  @override
  String get recordLabel => 'Студія звукозапису';

  @override
  String get refresh => 'Оновити';

  @override
  String get refreshLibrary => 'Оновити бібліотеку';

  @override
  String get refreshLibrarySubtitle => 'Перевірити наявність нових доданих або видалених треків';

  @override
  String get refreshOnStartup => 'Оновити при запуску';

  @override
  String get relatedVideos => 'Схожі відео';

  @override
  String get rememberAudioOnlyMode => 'Запам’ятати режим «Тільки аудіо»';

  @override
  String get remixer => 'Реміксер';

  @override
  String get remove => 'Видалити';

  @override
  String get removeDuplicates => 'Видалити дублікати';

  @override
  String get removeFromFavourites => 'Видалити з обраного';

  @override
  String get removeFromLibrary => 'Видалити з бібліотеки';

  @override
  String get removeFromPlaylist => 'Видалити з плейлиста';

  @override
  String get removeQueue => 'Видалити чергу';

  @override
  String get removeSourceFromHistory => 'Видалити джерело з історії';

  @override
  String get removeWhitespaces => 'Видалити пробіли';

  @override
  String get removed => 'Видалено';

  @override
  String get rename => 'Перейменувати';

  @override
  String get renamePlaylist => 'Перейменувати плейлист';

  @override
  String get reorderable => 'Впорядкувати';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number разів',
      few: '$number рази',
      one: '$number раз',
    );
    return 'Повторити ще $_temp0';
  }

  @override
  String get repeatMode => 'Режим повтору';

  @override
  String get repeatModeAll => 'Повторити всю чергу';

  @override
  String get repeatModeNone => 'Зупинитись на останньому треку';

  @override
  String get repeatModeOne => 'Повторити поточний трек';

  @override
  String get replaceAllListensWithAnotherTrack => 'Замінити всі прослухані іншим треком';

  @override
  String get replies => 'Відповіді';

  @override
  String get reply => 'Відповідь';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Необхідно очистити кеш зображень та виконати переіндексування';

  @override
  String get rescanVideos => 'Повторне сканування відео';

  @override
  String get resetBrightness => 'Скидання яскравості';

  @override
  String get resetToDefault => 'Встановити на';

  @override
  String get respectNoMedia => 'Дотримуватися .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Виключає теки, що містять .nomedia';

  @override
  String get restart => 'Перезавантажити';

  @override
  String get restoreBackup => 'Відновити резервну копію';

  @override
  String get restoreDefaults => 'Відновити значення за замовчуванням';

  @override
  String get restoredBackupSuccessfully => 'Резервну копію відновлено';

  @override
  String get restoredBackupSuccessfullySub => 'Файл резервної копії успішно відновлено';

  @override
  String get resume => 'Продовжити';

  @override
  String get resumeIfWasInterrupted => 'Продовжити відтворення, якщо було призупинено через преривання';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Продовжити відтворення, якщо було призупинено через від’єднання пристрою';

  @override
  String get resumeIfWasPausedByVolume => 'Продовжити відтворення, якщо було призупинено через гучність';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString хвилин',
      few: '$numberString хвилин',
      one: '$numberString хвилини',
    );
    return 'Продовжити відтворення, якщо пауза тривала менше $_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Кнопка «Не подобається» на YouTube';

  @override
  String get reverseOrder => 'Зворотний порядок';

  @override
  String get rightAction => 'Провести праворуч';

  @override
  String get ringtone => 'Рингтон';

  @override
  String get sameDirectoryOnly => 'Тільки в тому ж каталозі';

  @override
  String get sample => 'Зразок';

  @override
  String get sampleRate => 'Частота дискретизації';

  @override
  String get save => 'Зберегти';

  @override
  String get saveToLibrary => 'Зберегти в бібліотеку';

  @override
  String get savedIn => 'Збережено в';

  @override
  String get scaleMultiplier => 'Множник розміру';

  @override
  String get search => 'Пошук';

  @override
  String get searchYoutube => 'Пошук на YouTube';

  @override
  String get seconds => 'секунд';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Переглянути код проєкту на $site';
  }

  @override
  String get seekDuration => 'Тривалість пошуку';

  @override
  String get seekDurationInfo => 'Можна натискати на поточну тривалість для перемотки назад та загальну тривалість для перемотки вперед';

  @override
  String get seekbar => 'Смуга перемотки';

  @override
  String get selectAll => 'Обрати все';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Вибрати файли, копії яких є в локальній бібліотеці';

  @override
  String get selectedTracks => 'Обрані треки';

  @override
  String get selfPromotion => 'Саморозкручування';

  @override
  String get semitones => 'Напівтони';

  @override
  String get separatorsBlacklistSubtitle => 'Ці слова не будуть розділені';

  @override
  String get separatorsMessage =>
      'Пробіли вставляти не потрібно, якщо тільки Ви не хочете використовувати літеру/символ, котрий зустрічається в цілому слові (наприклад, x та ft.)';

  @override
  String get serverAddress => 'Адреса сервера';

  @override
  String get setAs => 'Встановити як';

  @override
  String get setAsDefault => 'Встановити як значення за замовчуванням';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Встановити дату зміни файлу датою завантаження відео';

  @override
  String get setMonoAudio => 'Встановити монозвук';

  @override
  String get setMoods => 'Встановити настрої';

  @override
  String get setMoodsSubtitle => 'Для розділення використовуйте коми (,)';

  @override
  String get setRating => 'Встановити оцінку';

  @override
  String get setTags => 'Встановити теги';

  @override
  String get setYoutubeLink => 'Встановити посилання на YouTube';

  @override
  String get settings => 'Налаштування';

  @override
  String get setupFirstStartup => 'Налаштування першого запуску';

  @override
  String get share => 'Поділитися';

  @override
  String get shareLogs => 'Надсилати журнали';

  @override
  String get shortcuts => 'Скорочення';

  @override
  String get shouldDuck => 'Повинен приглушитися';

  @override
  String get shouldDuckNote => 'Вказує на те, що гучність повинна бути знижена. Приклад: сповіщення';

  @override
  String get shouldPause => 'Необхідно поставити на паузу';

  @override
  String get shouldPauseNote => 'Вказує, що відтворення повинно бути призупинене. Приклад: при дзвінку';

  @override
  String get showAll => 'Показувати всі';

  @override
  String get showChannelWatermarkInFullscreen => 'Показувати водяний знак каналу в повноекранному режимі';

  @override
  String get showFailedOnly => 'Показувати лише невдалі';

  @override
  String get showHideUnknownFields => 'Показати/приховати невідомі поля';

  @override
  String get showInSeekbar => 'Показувати в смузі перемотки';

  @override
  String get showMixPlaylistsIn => 'Показувати мікси в';

  @override
  String get showMore => 'Детально';

  @override
  String get showShortVideosIn => 'Показувати Shorts у';

  @override
  String get showSkipButton => 'Показувати кнопку «Пропустити»';

  @override
  String get showVideoEndcards => 'Показувати кінцеві картки відеороликів';

  @override
  String get showWebm => 'Показати webm';

  @override
  String get shuffle => 'Перемішати';

  @override
  String get shuffleAll => 'Перемішати все';

  @override
  String get shuffleNext => 'Перемішати наступне';

  @override
  String get signIn => 'Увійти';

  @override
  String get signInCanceled => 'Вхід скасовано';

  @override
  String get signInFailed => 'Не вдалося увійти';

  @override
  String get signInToYourAccount => 'Увійти у свій обліковий запис';

  @override
  String get signInYouDontHaveAccount => 'Ви не ввійшли до жодного облікового запису';

  @override
  String get signInYouNeedAccountToViewPage => 'Щоб переглянути цю сторінку, Вам потрібен обліковий запис';

  @override
  String get signOut => 'Вийти';

  @override
  String signOutFromName({required String name}) {
    return 'Вийти з $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Увійшовши, Ви зможете користуватися основними функціями';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Отримайте ранній доступ через Patreon або використавши купон';

  @override
  String get similarDiscoverDate => 'Схожа дата виявлення';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Згенерувати треки, виявлені приблизно в той самий час, що й $currentTrack';
  }

  @override
  String get similarTimeRange => 'Схожий часовий діапазон';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Згенерувати треки, прослухані приблизно в той самий час, що й $currentTrack';
  }

  @override
  String get singles => 'Сингли';

  @override
  String get size => 'Розмір';

  @override
  String get skip => 'Пропустити';

  @override
  String get skipCountTracking => 'Підрахунок пропусків';

  @override
  String get skipSilence => 'Пропустити тишу';

  @override
  String get skipSponsorSegmentsInVideos => 'Пропускати спонсорські вставки в відео';

  @override
  String get sleepAfter => 'Заснути через';

  @override
  String get sleepTimer => 'Таймер сну';

  @override
  String get socials => 'Соцмережі';

  @override
  String get socialsSubtitle => 'Приєднуйтеся до обговорень, діліться ідеями, будьте в курсі оновлень та порад';

  @override
  String get someWebServersRequireAuthentication => 'Деякі веб-сервери вимагають автентифікації. Оновіть свої облікові дані, щоб зберегти доступ до бібліотеки.';

  @override
  String get sortBy => 'Сортувати за';

  @override
  String get source => 'Джерело';

  @override
  String get speed => 'Швидкість';

  @override
  String get sponsor => 'Спонсор';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'Рейтинг SponsorBlock';

  @override
  String get staggeredAlbumGridView => 'Послідовне відображення сітки альбомів';

  @override
  String get start => 'Початок';

  @override
  String get stats => 'Статистика';

  @override
  String get statsSubtitle => 'Деякі відомості про Вашу бібліотеку';

  @override
  String get stop => 'Стоп';

  @override
  String get stopAfterThisTrack => 'Зупинити після цього треку';

  @override
  String get stopAfterThisVideo => 'Зупинити після цього відео';

  @override
  String get storagePermissionDenied => 'Дозвіл відхилено';

  @override
  String get storagePermissionDeniedSubtitle => 'Будь ласка, дозвольте доступ для виконання цієї дії';

  @override
  String get stretchLyricsDuration => 'Розтягувати тривалість показу тексту';

  @override
  String get subdirectory => 'Підкаталог';

  @override
  String get subscribe => 'Підписатися';

  @override
  String get subscribed => 'Підписаний';

  @override
  String get subscriber => 'Підписник';

  @override
  String get subscribers => 'Підписники';

  @override
  String get succeeded => 'Успішно';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Маєте пропозицію чи зіткнулися з проблемою? Відкрийте задачу на $site';
  }

  @override
  String get support => 'Підтримати';

  @override
  String get supremacy => 'Перевага';

  @override
  String get sussyBaka => 'Дідько, немає треків';

  @override
  String get swipeActions => 'Дії жестів';

  @override
  String get swipeToOpenDrawer => 'Проведіть пальцем, щоб відкрити панель';

  @override
  String get synced => 'Синхронізований';

  @override
  String get synopsis => 'Синопсис';

  @override
  String get tagFields => 'Поля для тегів';

  @override
  String get tags => 'Теги';

  @override
  String get tapAction => 'Дія при натисканні';

  @override
  String get tapToSeek => 'Тапнути для перемотки';

  @override
  String get theFollowingChangesWereDetected => 'Виявлено такі зміни';

  @override
  String get themeMode => 'Тема';

  @override
  String get themeModeDark => 'Темна';

  @override
  String get themeModeLight => 'Світла';

  @override
  String get themeModeSystem => 'Як у системі';

  @override
  String get themeSettings => 'Тема';

  @override
  String get themeSettingsSubtitle => 'Загальна атмосфера Вашого плеєра';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'До цього плейлиста застосовується сортування, вимкніть його перед початком впорядкування.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Це відео, ймовірно, видалено або позначено як приватне.';

  @override
  String get thumbnails => 'Мініатюри';

  @override
  String get title => 'Назва';

  @override
  String get top => 'Найкращі';

  @override
  String get topComments => 'Коментарі зверху';

  @override
  String get topCommentsSubtitle => 'Відображати коментарі зверху, а не знизу';

  @override
  String get topRecentAlbums => 'Найкращі нещодавні альбоми';

  @override
  String get topRecentArtists => 'Найкращі нещодавні виконавці';

  @override
  String get topRecents => 'Найкращі нещодавні';

  @override
  String get totalListenTime => 'Загальний час прослуховування';

  @override
  String get totalListens => 'Усього прослуховувань';

  @override
  String get totalTracks => 'Усього треків';

  @override
  String get totalTracksDuration => 'Загальна тривалість треків';

  @override
  String get track => 'Трек';

  @override
  String get trackArtistsSeparator => 'Роздільник виконавців';

  @override
  String get trackGenresSeparator => 'Роздільник жанрів';

  @override
  String get trackInfo => 'Інформація про трек';

  @override
  String get trackNotFound => 'Трек не знайдено';

  @override
  String get trackNumber => 'Номер треку';

  @override
  String get trackNumberTotal => 'Усього треків';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Стара назва: «$oldName»\n\nНова назва: «$newName»\n\nВи впевнені?';
  }

  @override
  String get trackPlayMode => 'Режим відтворення';

  @override
  String get trackPlayModeSearchResults => 'Результати пошуку';

  @override
  String get trackPlayModeSelectedOnly => 'Тільки обрані треки';

  @override
  String get trackPlayModeTrackAlbum => 'Альбом треку';

  @override
  String get trackPlayModeTrackArtist => 'Основний виконавець треку';

  @override
  String get trackPlayModeTrackGenre => 'Жанр треку';

  @override
  String get trackThumbnailSizeInList => 'Розмір мініатюри треку';

  @override
  String get trackTileCustomization => 'Налаштування плитки треків';

  @override
  String get trackTileItemsSeparator => 'Роздільник елементів';

  @override
  String get tracks => 'Треки';

  @override
  String get tracksExcludedByNomedia => 'Треки, виключені через .nomedia';

  @override
  String get tracksInfo => 'Інформація про треки';

  @override
  String get underrated => 'Недооцінене';

  @override
  String get undo => 'Скасувати';

  @override
  String get undoChanges => 'Скасувати зміни?';

  @override
  String get undoChangesDeletedPlaylist => 'Скасувати видалення плейлиста';

  @override
  String get undoChangesDeletedQueue => 'Скасувати видалення черги';

  @override
  String get undoChangesDeletedTrack => 'Скасувати видалення треку';

  @override
  String get uniqueArtworkHash => 'Унікальний хеш обкладинки';

  @override
  String get unlimited => 'Необмежений';

  @override
  String get unlisted => 'Не вказано';

  @override
  String get unlock => 'Розблокувати';

  @override
  String get unsubscribe => 'Відписатися';

  @override
  String get update => 'Оновити';

  @override
  String get updateDirectoryPath => 'Оновити шлях до каталогу';

  @override
  String get updateMissingTracksOnly => 'Оновити тільки відсутні треки';

  @override
  String get updating => 'Оновлення';

  @override
  String get useCollapsedSettingTiles => 'Використовувати згорнуті плитки налаштувань';

  @override
  String get useMediaStore => 'Використовувати сховище медіафайлів';

  @override
  String get useMediaStoreSubtitle =>
      '✓ моментальна індексація\nx дотримання .nomedia буде примусово ввімкнено\nx деякі теги метаданих будуть відсутні\nx інтеграція YouTube для локальної бібліотеки не буде працювати';

  @override
  String get usePitchBlack => 'Використовувати вугільно-чорний колір';

  @override
  String get usePitchBlackSubtitle => 'Корисно для AMOLED-екранів... і виглядає крутіше';

  @override
  String get used => 'Використовується';

  @override
  String get value => 'Значення';

  @override
  String get valueBetween50200 => 'Значення повинно бути від 50% до 200%';

  @override
  String get vibration => 'Вібрація';

  @override
  String get vibrationType => 'Тип вібрації';

  @override
  String get video => 'Відео';

  @override
  String get videoCache => 'Кеш відео';

  @override
  String get videoCacheFile => 'Кешований відеофайл';

  @override
  String get videoCacheFiles => 'Кешовані відеофайли';

  @override
  String get videoOnly => 'Тільки відео';

  @override
  String get videoPlaybackSource => 'Джерело відео';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Дає пріорітет відео на пристрої. Якщо воно не знайдено, то буде отримано з YouTube';

  @override
  String get videoPlaybackSourceLocal => 'Відео на пристрої';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nВідео Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Перевіряє, чи не має якийсь відеофайл (знайдений у списку обраних тек) назву файлу, яка містить назву треку';

  @override
  String get videoPlaybackSourceYoutube => 'З YouTube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Перевіряє назву файлу та коментар до треку на наявність підходящих посилань на YouTube, відео кешується для подальшого використання.';

  @override
  String get videoQuality => 'Якість відео';

  @override
  String get videoQualitySubtitle => 'Буде обрана найкраща доступна якість.';

  @override
  String get videoQualitySubtitleNote => 'Завжди корисно мати більше альтернатив на випадок, якщо якість не буде знайдено, інакше відбудеться відкат до гіршої якості';

  @override
  String get videos => 'Відео';

  @override
  String get view => 'перегляд';

  @override
  String get viewAll => 'Переглянути все';

  @override
  String get views => 'переглядів';

  @override
  String get volume => 'Гучність';

  @override
  String get warning => 'Попередження';

  @override
  String get waveformBarsCount => 'Кількість смуг хвиль гучності';

  @override
  String get webmNoEditTagsSupport => 'Формат WEBM не підтримує редагування тегів';

  @override
  String get week => 'Тиждень';

  @override
  String get wiredDevice => 'Підключення через кабель';

  @override
  String get wirelessDevice => 'Бездротове з’єднання';

  @override
  String get year => 'Рік';

  @override
  String get yes => 'так';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Наразі Ваша участь $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Ваше впорядкування буде втрачено. Ви впевнені?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'Налаштування YouTube';

  @override
  String get youtubeStyleMiniplayer => 'YouTube-стиль мініплеєра';

  @override
  String get ytPreferNewComments => 'Завантаження нових коментарів по можливості';

  @override
  String get ytPreferNewCommentsSubtitle => 'Кешована версія буде використана тільки при відсутності підключення до Інтернету';
}
