// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Persian (`fa`).
class AppLocalizationsFa extends AppLocalizations {
  AppLocalizationsFa([String locale = 'fa']) : super(locale);

  @override
  String get about => 'درباره';

  @override
  String get active => 'فعال';

  @override
  String get add => 'افزودن';

  @override
  String get addAccount => 'افزودن حساب';

  @override
  String get addAll => 'همه را اضافه کن';

  @override
  String get addAllAndRemoveOldOnes => 'همه را اضافه و قدیمی ها را حذف کن';

  @override
  String get addAsANewPlaylist => 'افزودن بعنوان لیست پخش جدید';

  @override
  String get addAudioToLocalLibrary => 'افزودن آهنگ به حافظه داخلی';

  @override
  String get addFolder => 'افزودن پوشه';

  @override
  String get addLanguage => 'افزودن زبان';

  @override
  String get addLanguageSubtitle => 'به زبانت سهیم باش Namida در ترجمه شدن';

  @override
  String get addLrcFile => 'LRC افزودن فایل';

  @override
  String get addMoreFromThisAlbum => 'افزودن بیشتر از آلبوم به صف پخش';

  @override
  String get addMoreFromThisArtist => 'افزودن بیشتر از هنرمند به صف پخش';

  @override
  String get addMoreFromThisFolder => 'افزودن بیشتر از پوشه به صف پخش';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'افزودن بیشتر از $media به صف پخش';
  }

  @override
  String get addOnlyMissing => 'فقط گمشده ها را اضافه کن';

  @override
  String get addToFavourites => 'افزودن به علاقه‌مندی‌ها';

  @override
  String get addToPlaylist => 'افزودن به لیست پخش';

  @override
  String get addTracksAtTheBeginning => 'Add tracks at the beginning';

  @override
  String get added => 'افزوده شد';

  @override
  String get advanced => 'پیشرفته';

  @override
  String get advancedSettings => 'تنظیمات پیشرفته';

  @override
  String get advancedSettingsSubtitle => 'تنظیمات پیشرفته، دست نزن';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'آلبوم';

  @override
  String get albumArtist => 'هنرمند آلبوم';

  @override
  String get albumArtists => 'هنرمندان آلبوم';

  @override
  String get albumIdentifiers => 'مشخصه های آلبوم';

  @override
  String get albumThumbnailSizeInList => 'اندازه کاور آلبوم';

  @override
  String get albumTileCustomization => 'شخصی سازی نمایش آلبوم';

  @override
  String get albums => 'آلبوم ها';

  @override
  String get albumsCount => 'شماره آلبوم ها';

  @override
  String get all => 'همه';

  @override
  String get allTime => 'درکل';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'همیشه';

  @override
  String get alwaysAsk => 'همیشه بپرس';

  @override
  String get alwaysDim => 'Always Dim';

  @override
  String get alwaysExpandedSearchbar => 'Always Expanded Searchbar';

  @override
  String get alwaysRestore => 'همیشه بازگردان';

  @override
  String get animatingThumbnailIntensity => 'شدت انیمیشن کاور';

  @override
  String get animatingThumbnailInversed => 'انیمیشن معکوس';

  @override
  String get animatingThumbnailInversedSubtitle => 'قله های بلند باعث کوچک شدن کاور میشوند';

  @override
  String get anotherProcessIsRunning => 'پردازش دیگری درحال اجرا است.';

  @override
  String get appIcon => 'App Icon';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'هنرمند';

  @override
  String get artists => 'هنرمندان';

  @override
  String get artwork => 'کاور';

  @override
  String get artworkGestures => 'ژست های لمسی برروی کاور';

  @override
  String get artworks => 'کاور ها';

  @override
  String get audio => 'صدا';

  @override
  String get audioCache => 'حافظه پنهان صدا';

  @override
  String get audioOnly => 'فقط صدا';

  @override
  String get auto => 'خودکار';

  @override
  String get autoBackupInterval => 'فاصله پشتیبان گیری خودکار';

  @override
  String get autoColoring => 'رنگ خودکار';

  @override
  String get autoColoringSubtitle => 'بصورت خودکار رنگ پخش کننده را همرنگ کاور آهنگ میکند';

  @override
  String get autoExtractTagsFromFilename => 'استخراج خودکار از نام فایل';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'استخراج خودکار عنوان و نام هنرمند از عنوان ویدیو';

  @override
  String get autoGenerated => 'بصورت خودکار ایجاد شده';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'شروع خودکار رادیو';

  @override
  String get autoStartRadioSubtitle => 'Automatically adds a mix playlist when playing a single track';

  @override
  String get automaticBackup => 'بصورت خودکار';

  @override
  String get automaticBackupSubtitle => 'بصورت خودکار جدیدترین فایل پشتیبان گیری را از محل آن، اعمال میکند';

  @override
  String get backupAndRestore => 'پشتیبان گیری و بازیابی';

  @override
  String get backupAndRestoreSubtitle => 'پشتیبان گیری از تنظیمات و دیتابیس شما';

  @override
  String get balanced => 'متعادل';

  @override
  String get beta => 'بتا';

  @override
  String get betweenDates => 'بین تواریخ';

  @override
  String get bitrate => 'بیت ریت';

  @override
  String get blacklist => 'بلک لیست';

  @override
  String get borderRadiusMultiplier => 'مقدار قوس گوشه ها';

  @override
  String get cache => 'حافظه پنهان';

  @override
  String get cancel => 'لغو';

  @override
  String get canceled => 'لغو شده';

  @override
  String get changed => 'تغییر کرد';

  @override
  String get changelog => 'تغییرات';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'کانال';

  @override
  String get channels => 'کانال ها';

  @override
  String get check => 'بررسی';

  @override
  String get checkForMore => 'بررسی بیشتر';

  @override
  String get checkList => 'لیست کنترل';

  @override
  String get choose => 'انتخاب کردن';

  @override
  String get chooseWhatToClear => 'موارد حذفی را انتخاب کنید';

  @override
  String get claim => 'گرفتن';

  @override
  String get clear => 'حذف کردن';

  @override
  String get clearAudioCache => 'کش صدا پاک شود';

  @override
  String get clearImageCache => 'حذف حافظه پنهان عکس';

  @override
  String get clearImageCacheWarning => 'اخطار : موجب حذف عکس ها میشود، تنها برای بازسازی حافظه پنهان عکس استفاده شود.';

  @override
  String get clearTrackItem => 'موارد حذفی آهنگ';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'موارد حذفی $numberString آهنگ',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'حذف حافظه پنهان ویدیو';

  @override
  String get clearVideoCacheNote => '. می توانید موارد حذفی را انتخاب کنید';

  @override
  String get clock => 'ساعت';

  @override
  String get colorPalette => 'پالت رنگ';

  @override
  String get colorPaletteNote1 => 'انگشت را روی رنگ نگهدارید تا حذفش کنید';

  @override
  String get colorPaletteNote2 => 'مخلوط رنگی را برای رنگ پیش فرض انتخاب نمایید';

  @override
  String get colorPalettes => 'پالت های رنگ';

  @override
  String get comment => 'نظر';

  @override
  String get comments => 'نظرها';

  @override
  String get composer => 'آهنگساز';

  @override
  String get compress => 'متراکم سازی';

  @override
  String get compressImages => 'متراکم سازی عکس ها';

  @override
  String get compressionPercentage => 'درصد متراکم سازی';

  @override
  String get configure => 'تنظیم کردن';

  @override
  String get confirm => 'تایید کردن';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'کاور کپی شد';

  @override
  String get copiedToClipboard => 'در کلیپ بورد کپی شد';

  @override
  String get copy => 'کپی';

  @override
  String get corruptedFile => 'خطا در خوانش فایل، ممکن است خراب باشد';

  @override
  String get couldntOpen => ':( خطا در باز کردن';

  @override
  String get couldntOpenYtLink => 'هیچ لینک یوتیوبی برای این آهنگ موجود نیست';

  @override
  String get couldntPlayFile => 'خطا در پخش فایل';

  @override
  String get couldntRenamePlaylist => 'خطا در عوض کردن نام لیست پخش';

  @override
  String get couldntSaveImage => 'خطا در ذخیره عکس';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'کشور';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'ایجاد';

  @override
  String get createBackup => 'ایجاد پشتیبان گیری';

  @override
  String get createNewPlaylist => 'ایجاد لیست پخش جدید';

  @override
  String get createdBackupSuccessfully => 'پشتیبان گیری ایجاد شد';

  @override
  String get createdBackupSuccessfullySub => 'فایل پشتیبان گیری با موفقیت ایجاد شد';

  @override
  String get crossPlatformSync => 'Cross-Platform Sync';

  @override
  String get crossfadeDuration => 'Crossfade مدت';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'در آخرین Crossfade فعالسازی خودکار اثر $secondsString ثانیه',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'را به طور خودکار فعال نکن Crossfade اثر';

  @override
  String get custom => 'سفارشی';

  @override
  String get customizations => 'شخصی سازی';

  @override
  String get customizationsSubtitle => 'پخش کننده را شخصی سازی کن';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'دیتابیس';

  @override
  String get date => 'تاریخ';

  @override
  String get dateAdded => 'تاریخ افزودن';

  @override
  String get dateCreated => 'تاریخ ایجاد';

  @override
  String get dateModified => 'تاریخ ویرایش';

  @override
  String get dateTimeFormat => 'فورمت تاریخ';

  @override
  String get day => 'روز';

  @override
  String get days => 'روز';

  @override
  String get defaultBackupLocation => 'محل پشتیبان گیری پیش فرض';

  @override
  String get defaultColor => 'رنگ پیش فرض';

  @override
  String get defaultColorSubtitle => 'رنگی برای پخش کننده انتخاب کن';

  @override
  String get defaultDownloadLocation => 'محل دانلود پیش فرض';

  @override
  String get defaultLabel => 'پیش فرض';

  @override
  String get defaultLibraryTab => 'سربرگ پیش فرض';

  @override
  String get delete => 'حذف';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Delete $countString file representing $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return '$numberText را برای همیشه از حافظه خود پاک کنید';
  }

  @override
  String get deletePlaylist => 'حذف لیست پخش';

  @override
  String get deleteTempFiles => 'پاک سازی فایل های موقت';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'شرح';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'منظورتان این بود';

  @override
  String get dimIntensity => 'شدت تیرگی';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'صفحه پخش را پس از $secondsString ثانیه بی فعالیتی تیره کن',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'دایرکتوری موجود نیست';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Disable All';

  @override
  String get disableReordering => 'بازچینش را غیرفعال کن';

  @override
  String get disableSearchCleanup => 'جستجوی تمیز را غیرفعال کن';

  @override
  String get discNumber => 'شماره دیسک';

  @override
  String get discNumberTotal => 'شمار دیسک';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'ناپسند';

  @override
  String get dismissibleMiniplayer => 'قابلیت خروج صفحه پخش';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'نمایش تاریخ برروی کاور آلبوم';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'تاریخ آلبوم را بالا سمت راست کاور آن بنویس';

  @override
  String get displayArtistBeforeTitle => 'نمایش هنرمند بالای عنوان آهنگ';

  @override
  String get displayArtworkOnLockscreen => 'نمایش آثار هنری روی صفحه قفل';

  @override
  String get displayAudioInfoInMiniplayer => 'نمایش اطلاعات آهنگ';

  @override
  String get displayFavButtonInNotification => 'نمایش دکمه مورد علاقه در اعلان ها';

  @override
  String get displayFavButtonInNotificationSubtitle => 'شاید کاور جابه جا شود';

  @override
  String get displayFavouriteIconInTrackTile => 'نمایش دکمه موردعلاقه';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'نمایش زمان باقیمانده به جای کل زمان';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'نمایش سومین آیتم در هر ردیف';

  @override
  String get displayThirdRowInTrackTile => 'نمایش سومین ردیف';

  @override
  String get displayTrackNumberInAlbumPage => 'نمایش شماره آهنگ در صفحه آلبوم';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'یک کادر کوچک حاوی شماره آهنگ را در صفحه آلبوم نمایش دهید';

  @override
  String get doNothing => 'کاری نکن';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'انجام شد';

  @override
  String get dontAskAgain => 'دوباره نپرس';

  @override
  String get dontDim => 'Don\'t Dim';

  @override
  String get dontRestorePosition => 'بازیابی نکن';

  @override
  String get dontResume => 'ادامه نده';

  @override
  String get doubleTapToToggleLyrics => 'دوبار زدن برروی کاور متن آهنگ را فعال میکند';

  @override
  String get download => 'دانلود';

  @override
  String get downloadingWillOverrideIt => 'دانلود کردن بازنویسی اش میکند';

  @override
  String get downloads => 'دانلود ها';

  @override
  String get downloadsMetadataTags => 'برچسب های متادیتا را دانلود میکند';

  @override
  String get downloadsMetadataTagsSubtitle => 'استخراج هنرمند، عنوان و آلبوم از اطلاعات ویدیو بصورت پیش فرض';

  @override
  String get dragToSeek => 'برای جستجو بکشید';

  @override
  String get duckAudio => 'بی صدا';

  @override
  String get duplicatedItemsAdding => 'در حال تلاش برای افزودن مواردی هستید که هم اکنون در لیست پخش موجود هستند';

  @override
  String get duplicatedTracks => 'آهنگ های یکسان';

  @override
  String get duration => 'مدت زمان';

  @override
  String get edgeColorsSwitching => 'عوض شدن رنگ لبه';

  @override
  String get edit => 'ویرایش';

  @override
  String get editArtwork => 'ویرایش کاور';

  @override
  String get editTags => 'ویرایش برچسب ها';

  @override
  String get email => 'ایمیل';

  @override
  String get emptyNonMeaningfulTagFields => 'شما فیلد هایی با مقادیر خالی یا بی معنی دارید، از ویرایش آنها اطمینان حاصل فرمایید';

  @override
  String get emptyValue => 'مقدار خالی';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Blur اثر';

  @override
  String get enableBottomNavBar => 'فعالسازی نوار ناوبری';

  @override
  String get enableBottomNavBarSubtitle => 'سربرگ ها درهر صورت داخل کشو نیز هستند';

  @override
  String get enableClipboardMonitoring => 'رصد بریده دان';

  @override
  String get enableClipboardMonitoringSubtitle => 'اجازه دسترسی به بریده دان و در نتیجه جایگذاری سریع در قسمت جست و جو';

  @override
  String get enableCrossfadeEffect => 'Crossfade اثر';

  @override
  String get enableFadeEffectOnPlayPause => 'در توقف/پخش Fade فعالسازی اثر';

  @override
  String get enableFoldersHierarchy => 'فعالسازی سلسله پوشه ها';

  @override
  String get enableGlowEffect => 'فعالسازی اثر درخشش';

  @override
  String get enableM3uSync => 'M3U فعالسازی هماهنگ سازی';

  @override
  String get enableM3uSyncNote1 => 'میدهد M3U اجازه ذخیره ویرایش های لیست پخش را به فایل اصلی  M3U هماهنگ سازی';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'اگر اشتباهی صورت گرفت، فایل پشتیبان گیری این لیست پخش در $playlistsBackupPath خواهد بود';
  }

  @override
  String get enableM3uSyncSubtitle => 'اگر رد شود، تمام تغییرات صورت گرفته در این لیست پخش پس از ریستارت از بین میروند';

  @override
  String get enableMiniplayerParticles => 'فعالسازی ذره های متحرک';

  @override
  String get enableParallaxEffect => 'فعالسازی اثر اختلاف منظر';

  @override
  String get enablePartyMode => 'فعالسازی حالت پارتی';

  @override
  String get enablePartyModeSubtitle => 'فعالسازی اثر تنفسی فانتزی لبه';

  @override
  String get enablePictureInPicture => 'فعالسازی قابلیت تصویر در تصویر';

  @override
  String get enableReordering => 'فعالسازی بازچینش';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'فعالسازی پاکسازی جست و جو';

  @override
  String get enableSearchCleanupSubtitle => 'تمام علامت ها و فواصل نادیده گرفته میشوند';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'فعالسازی پخش ویدیو';

  @override
  String get enterSymbol => 'لطفاً علامتی وارد کنید';

  @override
  String get equalizer => 'برابر کننده';

  @override
  String get error => 'خطا';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'خطا در پخش آهنگ';

  @override
  String get excludedFodlers => 'پوشه های مستثنی';

  @override
  String get exit => 'خارج شدن';

  @override
  String get exitAppSubtitle => 'دوباره بزن تا خارج شی';

  @override
  String get expandedMiniplayer => 'Expanded Miniplayer';

  @override
  String get exportAsM3u => 'M3U خروجی گرفتن بعنوان';

  @override
  String get extension => 'پسوند';

  @override
  String get externalFiles => 'فایل های خارجی';

  @override
  String get extract => 'استخراج';

  @override
  String get extractAllColorPalettes => 'تمام پالت های رنگ را استخراج کن';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'آیا$numberString استخراج شود؟',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'از آهنگ feat. استخراج هنرمندان';

  @override
  String get extractFeatArtistSubtitle => 'و ثبت آنان بعنوان ورودی هنرمند جدید (ft. X) و (feat. X) استخراج نام هنرمندان در';

  @override
  String get extractingInfo => 'درحال استخراج اطلاعات';

  @override
  String get extras => 'اضافه بر سازمان';

  @override
  String get extrasSubtitle => 'تنظیمات اضافی برای تغییرات ریز و دقیق';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'ناموفق';

  @override
  String get failedEdits => 'ویرایش های ناموفق';

  @override
  String get favourites => 'موردعلاقه ها';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'دریافت کردن';

  @override
  String get fetchingOfAllVideos => 'دریافت کردن همه ویدیو‌ها';

  @override
  String get file => 'فایل';

  @override
  String get fileAlreadyExists => 'فایل همین الانشم موجود است';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'نام فایل';

  @override
  String get fileNameWoExt => 'نام فایل بدون پسوند';

  @override
  String get filenameShouldntStartWith => 'نام فایل نباید شروع شود با';

  @override
  String get files => 'فایل ها';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'مرتب کردن آلبوم ها';

  @override
  String get filterArtists => 'مرتب کردن هنرمندان';

  @override
  String get filterGenres => 'مرتب کردن سبک ها';

  @override
  String get filterPlaylists => 'مرتب کردن لیست پخش ها';

  @override
  String get filterTracks => 'مرتب کردن آهنگ ها';

  @override
  String get filterTracksBy => 'مرتب کردن آهنگ هابر اساس';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'مرتب کردن آهنگ ها بر اساس اندازه و زمان';

  @override
  String get finished => 'تمام شد';

  @override
  String get finishedUpdatingLibrary => 'بروزرسانی مجموعه به پایان رسید';

  @override
  String get firstListen => 'First listen';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp تعمیر اندازه بزرگ کاور';

  @override
  String get floatingActionButton => 'دکمه شناور';

  @override
  String get folder => 'پوشه';

  @override
  String get folderName => 'نام پوشه';

  @override
  String get folders => 'پوشه ها';

  @override
  String get fontScale => 'اندازه فونت';

  @override
  String get forceMiniplayerFollowTrackColors => 'تبعیت صفحه پخش از رنگ آهنگ';

  @override
  String get forceSquaredAlbumThumbnail => 'کاور های آلبوم مربعی';

  @override
  String get forceSquaredThumbnailNote => 'اندازه کاور و بلندای آیتم ها مساوی نیستند، ظاهر مربع شکل آنطور که انتظار میرود نخواهد بود، آیا میخواهید آنها را برابر کنید؟';

  @override
  String get forceSquaredTrackThumbnail => 'کاور های مربعی';

  @override
  String get forceStopColorPaletteGeneration => 'توقف اجباری استخراج پالت های رنگ؟ بعداً میتوانید کارتان را ادامه دهید';

  @override
  String get format => 'فورمت';

  @override
  String get fullscreen => 'Fullscreen';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'ایجاد کردن';

  @override
  String get generateFromDates => 'بازه زمانی';

  @override
  String get generateFromDatesSubtitle => 'ایجاد آهنگ هایی که در یک بازه زمانی گوش داده اید';

  @override
  String get generateRandomPlaylist => 'ایجاد کردن لیست پخش به صورت شانسی';

  @override
  String get genre => 'سبک';

  @override
  String get genres => 'سبک ها';

  @override
  String get goToAlbum => 'برو به آلبوم';

  @override
  String get goToArtist => 'برو به هنرمند';

  @override
  String get goToChannel => 'برو به کانال';

  @override
  String get goToFolder => 'برو به پوشه';

  @override
  String get goodLooking => 'زیبا';

  @override
  String get grantStoragePermission => 'اجازه دسترسی حافظه';

  @override
  String get group => 'گروه';

  @override
  String get groupArtworksByAlbum => 'گروه بندی کاور ها از روی آلبوم';

  @override
  String get guide => 'راهنما';

  @override
  String get hapticFeedback => 'Haptic Feedback';

  @override
  String get heightOfAlbumTile => 'بلندای آیتم های آلبوم';

  @override
  String get heightOfTrackTile => 'بلندای آیتم های آهنگ';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'تطابق های بالا';

  @override
  String get highPerformance => 'عملکرد بالا';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'تاریخچه';

  @override
  String get historyImportMissingEntriesNote => 'این درایه ها داخل مجموعه یافت نشدند، اگر فکر میکنید وجود دارند، بصورت دستی وارد کنید';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString بار گوش دادن به $oldTrackInfo با $newTrackInfo, جایگزین میشود، تایید؟',
    );
    return '$_temp0';
  }

  @override
  String get home => 'خانه';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'فورمت ۱۲ ساعته';

  @override
  String get hours => 'ساعت';

  @override
  String get iReadAndAgree => 'خواندم و قبول میکنم';

  @override
  String get ifNotPlaying => 'اگر پخش نمیشود';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'ممکن است در دانلود ها وقفه ایجاد شود اگر برنامه دسترسی محدودی به باتری داشته باشد';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignore common prefixes while sorting';

  @override
  String get ignores => 'نادیده میگیرد';

  @override
  String get imageSource => 'Image source';

  @override
  String get immersiveMode => 'حالت مسحور کننده';

  @override
  String get immersiveModeSubtitle => 'نوار وضعیت و ناوبری را زمانیکه پخش کننده بزرگ است، محو میکند';

  @override
  String get import => 'وارد کردن';

  @override
  String get importAll => 'بارگذاری همه';

  @override
  String get importLastFmHistory => 'LastFm بارگذاری تاریخچه';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. برو به $lastfmCsvLink\n\n2. را بارگذاری و دانلود کن csv نام کاربری را بنویس و فایل\n\n3. در صفحه بعدی فایل را انتخاب کن';
  }

  @override
  String get importTimeRange => 'بارگذاری بازه زمانی';

  @override
  String get importYoutubeHistory => 'بارگذاری تاریخچه یوتیوب';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. برو به $takeoutLink\n\n2. بزن رو \"Multiple Formats\" و کنار \"History\" انتخاب کن \"JSON\".\n\n3. بزن رو \"All Youtube data included\", همه را غیر فعال کن و بزن رو تنها تاریخچه\n\n4. استخراج را درست کن، دانلود و آنزیپ کن\n\n5. \"watch-history.json\" را در صفحه بعدی انتخاب کن';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString کانال با موفقیت وارد شدند',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText لیست پخش با موفقیت اضافه شدن',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Include videos';

  @override
  String get indexRefreshRequired => 'پس از تغییر این گزینه، بروزرسانی انجام شود';

  @override
  String get indexer => 'جستجوگر';

  @override
  String get indexerNote => 'توجه: منظور از شمار ناکامل کاور ها، کاور های یکسان و ناپیدا است';

  @override
  String get indexerSubtitle => 'مدیریت مجموعه آهنگ ها';

  @override
  String get infinityQueueOnNextPrev => 'صف پخش بی نهایت';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'زدن بعدی هنگام پخش آخرین آیتم، شما را به اولین آیتم میبرد و بلعکس';

  @override
  String get info => 'اطلاعات';

  @override
  String get inserted => 'وارد شده';

  @override
  String get instantlyApplies => 'بلافاصله اعمال میشود';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'انتخاب معکوس';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'آیتم';

  @override
  String get jump => 'برو';

  @override
  String get jumpToDay => 'برو به روز';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'برو به اولین آهنگ پس از اتمام صف پخش';

  @override
  String get keepCachedVersions => 'شده cache نسخه های';

  @override
  String get keepFileDates => 'تاریخ فایل ها را نگهدار';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'پخش کننده بزرگ شد';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'پخش کننده بزرگ شده و ویدیو درحال پخش است';

  @override
  String get keepScreenAwakeNone => 'صفحه را روشن نزار';

  @override
  String get keepScreenAwakeWhen => 'زمانی صفحه را روشن بزار که';

  @override
  String get killPlayerAfterDismissingApp => 'کشتن پخش کننده پس از خروج کامل از برنامه';

  @override
  String get language => 'زبان';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'سربرگ ها';

  @override
  String get libraryTabsReorder => '.میتوانید چینش سربرگ های فعال شده را با نگهداشتن انگشت تغییر دهید';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'پسند';

  @override
  String get liked => 'پسندیده';

  @override
  String get link => 'لینک';

  @override
  String get listOfFolders => 'لیست پوشه ها';

  @override
  String get loadAll => 'بارگیری کردن همه';

  @override
  String get loadingFile => 'بارگذاری فایل';

  @override
  String get local => 'داخلی';

  @override
  String get localVideoMatching => 'تطابق ویدیو های داخلی';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Long press the lyrics to enter fullscreen';

  @override
  String get lostMemories => 'خاطره های گم شده';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'روزی روزگاری $numberString سال پیش',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'تقویت کننده بلندی';

  @override
  String get lyricist => 'متن ساز';

  @override
  String get lyrics => 'متن ها';

  @override
  String get lyricsSource => 'منبع متن موسیقی';

  @override
  String get m3uPlaylist => 'M3U لیست پخش';

  @override
  String get makeYourFirstListen => '!برای اولین بار گوش بده';

  @override
  String get manage => 'مدیریت کردن';

  @override
  String get manageYourAccounts => 'مدیریت کردن حساب های کاربری خود';

  @override
  String get manualBackup => 'دستی';

  @override
  String get manualBackupSubtitle => 'انتخاب کردن فایل مشخص';

  @override
  String get markAsRead => 'علامت زدن به عنوان خوانده شده';

  @override
  String get matchAllTracks => 'تطابق تمام آهنگ ها';

  @override
  String get matchAllTracksNote => 'این میتواند بر سرعت تطابق تاثرگذار باشد، از آنجایی که کل آهنگ های مجموعه تان را بررسی میکند';

  @override
  String get matchingType => 'نوع تطابق';

  @override
  String get maxAudioCacheSize => 'Max audio cache size';

  @override
  String get maxImageCacheSize => 'حداکثر حافظه پنهان عکس';

  @override
  String get maxVideoCacheSize => 'حداکثر حافظه پنهان ویدیو';

  @override
  String get maximum => 'حداکثر';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store is enabled, this will have no effect';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Code';

  @override
  String get membershipCodeSentToEmail => 'کد به ایمیلتان ارسال شد';

  @override
  String get membershipDidntChange => 'عضویت تغییر نکرد';

  @override
  String get membershipEnjoyNew => 'از عضویت جدید خود لذت ببرید';

  @override
  String get membershipFreeCoupon => 'کوپن رایگان';

  @override
  String get membershipManage => 'عضویت خود را مدیریت کنید';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'هیچ اشتراکی برای این کاربر پیدا نشد';

  @override
  String get membershipSignInToPatreonAccount => 'وارد حساب کاربری patreon خود شوید';

  @override
  String get membershipUnknown => 'عضویت ناشناخته';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'You need membership of $name1 or $name2 to add multiple accounts';
  }

  @override
  String get merge => 'Merge';

  @override
  String get metadataCache => 'حافظه پنهان متادیتا';

  @override
  String get metadataEditFailed => 'ناموفقیت در ویرایش متادیتا';

  @override
  String get metadataReadFailed => 'ناموفقیت در خواندن متادیتا';

  @override
  String get minFileDuration => 'حداقل زمان آهنگ';

  @override
  String get minFileSize => 'حداقل اندازه فایل';

  @override
  String get minTrackDurationToRestoreLastPosition => 'حداقل زمان کل آهنگ برای بازیابی وضعیت زمانی قبلی';

  @override
  String get minValueCantBeMoreThanMax => 'مقدار حداقل نمیتواند بیشتر از حداکثر باشد';

  @override
  String get minValueToCountTrackListen => 'یک گوش دادن حساب کن پس از:';

  @override
  String get minimizedMiniplayer => 'Minimized Miniplayer';

  @override
  String get minimum => 'حداقل';

  @override
  String get minimumOneFolderSubtitle => 'باید حداقل یک پوشه باشد، پوشه های بیشتری اضافه کن اگر قصد حذف این پوشه را داری';

  @override
  String get minimumOneItem => 'ناتوانی در حذف آیتم';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'حداقل $numberString آیتم باید بماند',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'شخصی سازی صفحه پخش';

  @override
  String get minutes => 'دقیقه';

  @override
  String get missingEntries => 'درایه های از قلم افتاده';

  @override
  String get missingTracks => 'آهنگ های گمشده';

  @override
  String get mix => 'Mix';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Mix playlist generated by youtube';

  @override
  String get mixes => 'میکس ها';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'ماه';

  @override
  String get months => 'ماه';

  @override
  String get mood => 'حال و هوا';

  @override
  String get moods => 'حال و هوا ها';

  @override
  String get more => 'بیشتر';

  @override
  String get mostPlayed => 'بیشترین پخش';

  @override
  String get multipleTracksTagsEditNote => 'شما درحال ویرایش این آهنگ ها هستید،\nفیلد های تغییر نکرده دست نخورده باقی میمانند';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'نام';

  @override
  String get nameContainsBadCharacter => 'نام حاوی حرف نامطلوب است';

  @override
  String get never => 'هرگز';

  @override
  String get newDirectory => 'دایرکتوری جدید';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'افزودن آهنگ ها';

  @override
  String get newTracksMoods => 'حال و هوای آهنگ ها';

  @override
  String get newTracksMoodsSubtitle => 'ایجاد آهنگ ها براساس حال و هوا های موجود';

  @override
  String get newTracksRandom => 'تصادفی';

  @override
  String get newTracksRandomSubtitle => 'انتخاب آهنگ های تصادفی از مجموعه شما';

  @override
  String get newTracksRatings => 'امتیازات';

  @override
  String get newTracksRatingsSubtitle => 'ایجاد آهنگ هایی با امتیاز مشخص';

  @override
  String get newTracksRecommended => 'پیشنهادی';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'ایجاد آهنگ هایی که اغلب به آنها گوش میدادید با $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'تاریخ عرضه متشابه';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'ایجاد آهنگ هایی که تاریخ عرضه مشابه $currentTrack داشتند';
  }

  @override
  String get newTracksUnknownYear => 'آهنگ سال نامشخصی دارد';

  @override
  String get newest => 'جدیدترین';

  @override
  String get next => 'بعدی';

  @override
  String get no => 'نه';

  @override
  String get noChangesFound => 'هیچ تغییری یافت نشد.';

  @override
  String get noEnoughTracks => 'آهنگ به اندازه کافی موجود نیست';

  @override
  String get noExcludedFolders => 'هیچ پوشه مستثنی ای ندارید';

  @override
  String get noFolderChosen => 'هیچ پوشه ای انتخاب نکرده اید';

  @override
  String get noMoodsAvailable => 'هیچ حال و هوایی یافت نشد';

  @override
  String get noNetworkAvailableToFetchData => 'هیچ شبکه ای برای دریافت اطاعات در دسترسی نیست';

  @override
  String get noTracksFound => 'هیچ آهنگی یافت نشد';

  @override
  String get noTracksFoundBetweenDates => 'این محدوده زمانی هیچ آهنگی ندارد.';

  @override
  String get noTracksFoundInDirectory => 'هیچ آهنگی در این دایرکتوری یافت نشد';

  @override
  String get noTracksInHistory => 'آهنگ کافی در تاریخچه موجود نیست';

  @override
  String get nonActive => 'غیرفعال';

  @override
  String get nonFavourites => 'غیرعلاقه‌مندی‌ها';

  @override
  String get none => 'هیچ';

  @override
  String get normalizeAudio => 'عادی کردن صدا';

  @override
  String get normalizeAudioSubtitle => 'Normalizes volume by reading the replay gain tag or the info provided by youtube';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'توجه';

  @override
  String get notification => 'اعلان';

  @override
  String get notifications => 'اعلان‌ها';

  @override
  String get numberOfTracks => 'شماره آهنگ ها';

  @override
  String get ofLabel => 'از';

  @override
  String get offlineSearch => 'جست و جوی آفلاین';

  @override
  String get offset => 'آفست صدا';

  @override
  String get oldDirectory => 'دایرکتوری قدیمی';

  @override
  String get oldDirectoryStillHasTracks => 'دایرکتوری قدیمی هنوز دارای آهنگ میباشد، مطمئنی ؟';

  @override
  String get oldestWatch => 'قدیمی ترین تماشا';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'اگر وقفه ای صورت گرفت';

  @override
  String get onNotificationTap => 'زدن روی اعلان باعث';

  @override
  String get onOpeningYoutubeLink => 'در باز شدن لینک یوتیوب';

  @override
  String get onSwiping => 'On Swiping';

  @override
  String get onVolumeZero => 'اگر درجه صدا صفر شود';

  @override
  String get ongoing => 'درحال وقوع';

  @override
  String get open => 'باز کردن';

  @override
  String get openApp => 'باز کردن برنامه';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'در یوتیوب ویو باز شود';

  @override
  String get openMiniplayer => 'صفحه پخش باز شود';

  @override
  String get openQueue => 'صف پخش باز شود';

  @override
  String get openYoutubeLink => 'لینک یوتیوب باز شود';

  @override
  String operationRequiresAccount({required String name}) {
    return 'عملیت $name به حساب کاربری نیاز دارد, برای ادامه وارد شوید';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'عملیات $operation حداقل به عضویت $name نیاز دارد';
  }

  @override
  String get or => 'یا';

  @override
  String get others => 'غیره';

  @override
  String get output => 'خروجی';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'بازنویسی فایل های قدیمی در همان پوشه';

  @override
  String get palette => 'پالت';

  @override
  String get paletteMix => 'میکس';

  @override
  String get paletteNewMix => 'میکس جدید';

  @override
  String get paletteSelectedMix => 'میکس انتخاب شده';

  @override
  String get parallelDownloads => 'دانلود های موازی';

  @override
  String get parsed => 'parsed';

  @override
  String get password => 'Password';

  @override
  String get path => 'محل دقیق فایل';

  @override
  String get pause => 'توقف';

  @override
  String get pauseFadeDuration => 'حین توقف آهنگ Fade مدت زمان اثر';

  @override
  String get pausePlayback => 'توقف پخش';

  @override
  String get percentage => 'درصد';

  @override
  String get performanceMode => 'حالت عملکرد';

  @override
  String get performanceNote => 'شاید عملکرد را تحت تاثیر قرار دهد (کند شود)';

  @override
  String get personalized => 'شخصی‌سازی شده';

  @override
  String get personalizedRelatedVideos => 'Personalized Related Videos';

  @override
  String get personalizedRelatedVideosSubtitle => 'Disabling this will increase data usage';

  @override
  String get pickColorsFromDeviceWallpaper => 'انتخاب رنگ ها از عکس پس زمینه گوشی';

  @override
  String get pickFromStorage => 'انتخاب از حافظه داخلی';

  @override
  String get pinned => 'سنجاق شده';

  @override
  String get pitch => 'گام صدا';

  @override
  String get plain => 'ساده';

  @override
  String get play => 'پخش';

  @override
  String get playAfter => 'پخش بعدی';

  @override
  String get playAfterNextPrev => 'پخش خودکار آهنگ پس از زدن بعدی/قبلی';

  @override
  String get playAll => 'بخش همه';

  @override
  String get playFadeDuration => 'حین پخش آهنگ Fade مدت زمان اثر';

  @override
  String get playLast => 'پخش آخر آهنگ';

  @override
  String get playNext => 'پخش بعد آهنگ';

  @override
  String get playbackSetting => 'پخش';

  @override
  String get playbackSettingSubtitle => 'میتوانید از صفحه پخش کننده نیز با نگه داشتن دکمه پایین سمت چپ صدا به اینجا دسترسی پیدا کنید';

  @override
  String get playlist => 'لیست پخش';

  @override
  String get playlists => 'لیست پخش';

  @override
  String get playlistsImportM3uNative => 'This will import M3U playlists to be used only by namida, use if you are migrating';

  @override
  String get playlistsImportM3uSynced =>
      'This will automatically import M3U playlists from indexer folders and keep them synced with the original M3U file. enable if you access/modify the playlists from other apps';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Auto import M3U Playlists';

  @override
  String get pleaseEnterADifferentName => 'این نام همین الانشم موجود است :(\nلطفا نامی دیگر انتخاب کنید';

  @override
  String get pleaseEnterALink => 'لطفاً لینک را وارد کنید';

  @override
  String get pleaseEnterALinkSubtitle => 'آم... این لینک یوتیوب است؟';

  @override
  String get pleaseEnterAName => 'لطفاً نام را وارد کنید';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'جلوگیری از آهنگ های یکسان';

  @override
  String get preventDuplicatedTracksSubtitle => 'از نام آهنگ جهت تشخیص منحصر به فرد آهنگ ها استفاده میکند';

  @override
  String get preview => 'پیش نمایش';

  @override
  String get previous => 'Previous';

  @override
  String get previousButtonReplays => 'Previous button replays';

  @override
  String get previousButtonReplaysSubtitle => 'if pressed while current position was more than seek duration';

  @override
  String get prioritizeEmbeddedLyrics => 'به نمایش متن های درون خود فایل آهنگ اولویت بده';

  @override
  String get priority => 'Priority';

  @override
  String get private => 'خصوصی';

  @override
  String get progress => 'پیشرفت';

  @override
  String get promptToChangeTrackPath => 'معمولاً زمانی اتفاق می اُفتد که فایل خارج از برنامه حذف/ویرایش نام/جابه جا میشود، مایل به بروزرسانی محل کنونی هستید؟';

  @override
  String get public => 'عمومی';

  @override
  String get queue => 'صف پخش';

  @override
  String get queues => 'صف های پخش';

  @override
  String get random => 'تصادفی';

  @override
  String get randomPicks => 'انتخاب های تصادفی';

  @override
  String get rating => 'امتیاز';

  @override
  String get reIndex => 'فهرست مجدد';

  @override
  String get reIndexSubtitle => 'بازتولیدی مجموعه آهنگ های شما از نو';

  @override
  String get reIndexWarning => 'این فرآیند، بسته به اندازه مجموعه، شما ممکن است طول بکشد.\n\nکاور ها تا زمانیکه هنوز موجود هستند، فهرست مجدد نخواهند شد';

  @override
  String get recentAlbums => 'آلبوم های اخیر';

  @override
  String get recentArtists => 'هنرمندان اخیر';

  @override
  String get recentListens => 'گوش دادن های اخیر';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'اضافه شده های اخیر';

  @override
  String get recordLabel => 'ناشر آهنگ';

  @override
  String get refresh => 'بروزرسانی';

  @override
  String get refreshLibrary => 'بروزرسانی مجموعه';

  @override
  String get refreshLibrarySubtitle => 'بررسی کردن برای آهنگ های حذف شده یا اضافه شده';

  @override
  String get refreshOnStartup => 'بروزرسانی در هنگام شروع';

  @override
  String get relatedVideos => 'ویدیو های مرتبط';

  @override
  String get rememberAudioOnlyMode => 'حالت فقط صدا را به یاد داشته باش';

  @override
  String get remixer => 'تنظیم کننده';

  @override
  String get remove => 'حذف کردن';

  @override
  String get removeDuplicates => 'حذف یکسان ها';

  @override
  String get removeFromFavourites => 'حذف کردن از علاقه‌مندی‌‌ها';

  @override
  String get removeFromLibrary => 'حذف کردن از مجموعه';

  @override
  String get removeFromPlaylist => 'حذف از لیست پخش';

  @override
  String get removeQueue => 'حذف صف پخش';

  @override
  String get removeSourceFromHistory => 'حذف منبع از تاریخچه';

  @override
  String get removeWhitespaces => 'حذف فضا های خالی';

  @override
  String get removed => 'حذف شد';

  @override
  String get rename => 'تغییر نام';

  @override
  String get renamePlaylist => 'تغییر نام لیست پخش';

  @override
  String get reorderable => 'قابل بازچینش';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'بازپخش برای $number بار',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Repeat mode';

  @override
  String get repeatModeAll => 'بازپخش تمام آهنگ های صف پخش';

  @override
  String get repeatModeNone => 'توقف در آخرین آهنگ';

  @override
  String get repeatModeOne => 'بازپخش این آهنگ';

  @override
  String get replaceAllListensWithAnotherTrack => 'جایگزینی تمام آهنگ های گوش داده شده با آهنگ های دیگر';

  @override
  String get replies => 'جواب ها';

  @override
  String get reply => 'پاسخ';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'نیازمند حذف حافظه پنهان عکس و فهرست مجدد';

  @override
  String get rescanVideos => 'دوباره اسکن کردن ویدیو ها';

  @override
  String get resetBrightness => 'بازنشاندن روشنایی';

  @override
  String get resetToDefault => 'تنظیم به';

  @override
  String get respectNoMedia => 'تابع .nomedia';

  @override
  String get respectNoMediaSubtitle => 'هستند را نادیده بگیر .nomedia پوشه هایی که دارای';

  @override
  String get restart => 'شروع مجدد';

  @override
  String get restoreBackup => 'پشتیبان گیری';

  @override
  String get restoreDefaults => 'برگرداندن پیش فرض ها';

  @override
  String get restoredBackupSuccessfully => 'پشتیبان گیری صورت گرفت';

  @override
  String get restoredBackupSuccessfullySub => 'فایل پشتیبان گیری با موفقیت برگردانده شد';

  @override
  String get resume => 'ادامه';

  @override
  String get resumeIfWasInterrupted => 'اگر وقفه ای صورت گرفت، پخش ادامه یابد';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'افزایش صدا باعث ادامه پخش شود';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'اكر كمتر از$numberString دقيقه مكث شده بود، ازسركيرى كنيد',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'چینش بلعکس';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Ringtone';

  @override
  String get sameDirectoryOnly => 'فقط همین دایرکتوری';

  @override
  String get sample => 'Sample';

  @override
  String get sampleRate => 'نرخ نمونه';

  @override
  String get save => 'ذخیره';

  @override
  String get saveToLibrary => 'ذخیره در مجموعه';

  @override
  String get savedIn => 'ذخیره در';

  @override
  String get scaleMultiplier => 'بزرگ کردن نسبت';

  @override
  String get search => 'جست و جو';

  @override
  String get searchYoutube => 'جست و جوی یوتیوب';

  @override
  String get seconds => 'ثانیه';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'زمان رد';

  @override
  String get seekDurationInfo => 'زدن روی زمان فعلی و زمان کل آهنگ باعث جلو/عقب شدن آن میشود';

  @override
  String get seekbar => 'Seekbar';

  @override
  String get selectAll => 'انتخاب همه';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Select files already in local library';

  @override
  String get selectedTracks => 'آهنگ های انتخاب شده';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'این کلمات جدا نخواهند شد';

  @override
  String get separatorsMessage => '(feat. و x نیازی به فاصله گذاری نیست، مگرآنکه قصد نوشتن حرف یا علامتی که در کلمه کامل پیدا میشود را داشته باشی (مانند';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Set as';

  @override
  String get setAsDefault => 'بعنوان پیش فرض قرار بده';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'آخرین ویرایش فایل را بعنوان تاریخ آپلود ویدیو قرار بده';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'حال و هوا را مشخص کن';

  @override
  String get setMoodsSubtitle => 'از کاما (,) برای جداسازی استفاده کن';

  @override
  String get setRating => 'امتیازدهی';

  @override
  String get setTags => 'برچسب گذاری';

  @override
  String get setYoutubeLink => 'لینک یوتیوب را بگذار';

  @override
  String get settings => 'تنظیمات';

  @override
  String get setupFirstStartup => 'راه اندازی اولیه';

  @override
  String get share => 'اشتراک گذاری';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Shortcuts';

  @override
  String get shouldDuck => 'باید کم شود';

  @override
  String get shouldDuckNote => 'نشان دهنده کم شدن صداست. مثال: حین اعلان ';

  @override
  String get shouldPause => 'باید متوقت شود';

  @override
  String get shouldPauseNote => 'نشان دهنده توقف صداست. مثال: حین تماس';

  @override
  String get showAll => 'Show All';

  @override
  String get showChannelWatermarkInFullscreen => 'Show channel watermark in fullscreen';

  @override
  String get showFailedOnly => 'Show Failed only';

  @override
  String get showHideUnknownFields => 'نمایش دادن/ندادن فیلد های نامعلوم';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Show Mixes in';

  @override
  String get showMore => 'نمایش بیشتر';

  @override
  String get showShortVideosIn => 'نشان دادن ویدیو‌های کوتاه در';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'Show video endcards';

  @override
  String get showWebm => 'webm نمایش';

  @override
  String get shuffle => 'پخش تصادفی';

  @override
  String get shuffleAll => 'پخش تصادفی همه';

  @override
  String get shuffleNext => 'پخش تصادفی بعدی';

  @override
  String get signIn => 'وارد شدن';

  @override
  String get signInCanceled => 'وارد شدن لغو شد';

  @override
  String get signInFailed => 'وارد شدن نا‌موفقیت آمیز بود';

  @override
  String get signInToYourAccount => 'وارد شدن به حساب کاربری خود';

  @override
  String get signInYouDontHaveAccount => 'هیچ حساب کاربری وارد شده ای ندارید';

  @override
  String get signInYouNeedAccountToViewPage => 'شما به یک حساب کاربی برای دیدن این صفحه نیاز دارید';

  @override
  String get signOut => 'خارج شدن';

  @override
  String signOutFromName({required String name}) {
    return 'خارج شدن از $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Signing in allows basic usage';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'دسترسی زودرس بگیرید از طریق patreaon یا کوپن';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Similar Time Range';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generate tracks you listened to around the same time as $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'اندازه';

  @override
  String get skip => 'رد کردن';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'رد کردن سکوت';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'بخواب بعد از';

  @override
  String get sleepTimer => 'زمان سنج خواب';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'نحوه چینش';

  @override
  String get source => 'منبع';

  @override
  String get speed => 'سرعت';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'نمایش زیگزاگی آلبوم ها در چینش شبکه ای';

  @override
  String get start => 'شروع';

  @override
  String get stats => 'آمار';

  @override
  String get statsSubtitle => 'اینجا اطلاعاتی درباره مجموعه شماست';

  @override
  String get stop => 'توقف';

  @override
  String get stopAfterThisTrack => 'توقف بعد از این آهنگ';

  @override
  String get stopAfterThisVideo => 'توقف بعد از ویدیو';

  @override
  String get storagePermissionDenied => 'اجازه دسترسی رد شد';

  @override
  String get storagePermissionDeniedSubtitle => 'لطفاً اجازه دسترسی بدهید تا امکان انجام این کار فراهم شود';

  @override
  String get stretchLyricsDuration => 'Stretch Lyrics Duration';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'دنبال کردن';

  @override
  String get subscribed => 'دنبال میشود';

  @override
  String get subscriber => 'دنبال کننده';

  @override
  String get subscribers => 'دنبال کننده ها';

  @override
  String get succeeded => 'موفقیت آمیز بود';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'پشتیبانی';

  @override
  String get supremacy => 'برتری';

  @override
  String get sussyBaka => 'آهنگی موجود نیست';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'بکش سمت راست تا کشو باز شود';

  @override
  String get synced => 'هماهنگ سازی شده';

  @override
  String get synopsis => 'خلاصه';

  @override
  String get tagFields => 'فیلد برچسب ها';

  @override
  String get tags => 'برچسب ها';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Tap to seek';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'حالت پس زمینه';

  @override
  String get themeModeDark => 'تاریک';

  @override
  String get themeModeLight => 'روشن';

  @override
  String get themeModeSystem => 'خودکار';

  @override
  String get themeSettings => 'پس زمینه';

  @override
  String get themeSettingsSubtitle => 'حس و حال پخش کننده';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'This playlist has active sorters, please disable them before reordering.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'This video is likely deleted or set to private.';

  @override
  String get thumbnails => 'کاور ها';

  @override
  String get title => 'عنوان';

  @override
  String get top => 'برترین';

  @override
  String get topComments => 'بیشترین نظرات';

  @override
  String get topCommentsSubtitle => 'نمایش نظرات بالا به جای پایین';

  @override
  String get topRecentAlbums => 'برترین آلبوم های اخیر';

  @override
  String get topRecentArtists => 'برترین هنرمندان اخیر';

  @override
  String get topRecents => 'برترین های اخیر';

  @override
  String get totalListenTime => 'زمان کل گوش دادن';

  @override
  String get totalListens => 'شمار گوش دادن';

  @override
  String get totalTracks => 'شمار آهنگ ها';

  @override
  String get totalTracksDuration => 'زمان کل آهنگ ها';

  @override
  String get track => 'آهنگ';

  @override
  String get trackArtistsSeparator => 'جدا کننده هنرمندان';

  @override
  String get trackGenresSeparator => 'جدا کننده سبک ها';

  @override
  String get trackInfo => 'اطلاعات آهنگ';

  @override
  String get trackNotFound => 'آهنگ یافت نشد';

  @override
  String get trackNumber => 'شماره آهنگ';

  @override
  String get trackNumberTotal => 'شمار آهنگ ها';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'نام قدیمی: \"$oldName\"\n\nنام جدید: \"$newName\"\n\nمطمئنی؟';
  }

  @override
  String get trackPlayMode => 'حالت پخش';

  @override
  String get trackPlayModeSearchResults => 'نتایج جست و جو';

  @override
  String get trackPlayModeSelectedOnly => 'فقط آهنگ انتخاب شده';

  @override
  String get trackPlayModeTrackAlbum => 'آلبوم آهنگ';

  @override
  String get trackPlayModeTrackArtist => 'هنرمند اصلی آهنگ';

  @override
  String get trackPlayModeTrackGenre => 'سبک آهنگ';

  @override
  String get trackThumbnailSizeInList => 'اندازه کاور آهنگ';

  @override
  String get trackTileCustomization => 'شخصی سازی لیست آهنگ';

  @override
  String get trackTileItemsSeparator => 'جدا کننده آیتم ها';

  @override
  String get tracks => 'آهنگ ها';

  @override
  String get tracksExcludedByNomedia => 'مستثنی شده اند .nomedia آهنگ هایی که با';

  @override
  String get tracksInfo => 'اطلاعات آهنگ ها';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'بازگردان';

  @override
  String get undoChanges => 'بازگردانی تغییرات؟';

  @override
  String get undoChangesDeletedPlaylist => 'بازگردانی لیست پخش حذف شده';

  @override
  String get undoChangesDeletedQueue => 'بازگردانی صف پخش حذف شده';

  @override
  String get undoChangesDeletedTrack => 'بازگردانی آهنگ حذف شده';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'بی نهایت';

  @override
  String get unlisted => 'لیست نشده';

  @override
  String get unlock => 'باز کردن';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'بروزرسانی';

  @override
  String get updateDirectoryPath => 'بروزرسانی مسیر دایرکتوری';

  @override
  String get updateMissingTracksOnly => 'فقط آهنگ های از قلم افتاده بروزرسانی شوند';

  @override
  String get updating => 'درحال بروزرسانی';

  @override
  String get useCollapsedSettingTiles => 'طبقه بندی صفحه تنظیمات';

  @override
  String get useMediaStore => 'استفاده شود Media Store از';

  @override
  String get useMediaStoreSubtitle =>
      '✓ فهرست کردن سریع\nx اجباراً فعال خواهد شد .nomedia تابع\nx برخی برچسب های متادیتا از قلم می اُفتند\nx ادغام یوتیوب با مجموعه داخلی کار نخواهد کرد';

  @override
  String get usePitchBlack => 'سیاه مطلق';

  @override
  String get usePitchBlackSubtitle => 'برای صفحات امولد... باحال ترم هست';

  @override
  String get used => 'استفاده شده';

  @override
  String get value => 'مقدار';

  @override
  String get valueBetween50200 => 'مقدار باید بین %50 و %200 باشد';

  @override
  String get vibration => 'Vibration';

  @override
  String get vibrationType => 'Vibration type';

  @override
  String get video => 'ویدیو';

  @override
  String get videoCache => 'حافظه پنهان ویدیو';

  @override
  String get videoCacheFile => 'فایل پنهان ویدیو';

  @override
  String get videoCacheFiles => 'فایل های پنهان ویدیو';

  @override
  String get videoOnly => 'فقط ویدیو';

  @override
  String get videoPlaybackSource => 'منبع ویدیو';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'این اولویت را به ویدیو های داخلی میدهد، اگر پیدا نشد از یوتیوب دریافت خواهد شد';

  @override
  String get videoPlaybackSourceLocal => 'ویدیو های داخلی';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'بررسی وجود نام فایل آهنگ در نام فایل ویدیو (که درون فهرست پوشه های منتخب است)';

  @override
  String get videoPlaybackSourceYoutube => 'از یوتیوب';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'خواهند شد cache بررسی قسمت های نام و نظر آهنگ برای لینک یوتیوب، ویدیو ها برای استفاده آینده';

  @override
  String get videoQuality => 'کیفیت ویدیو';

  @override
  String get videoQualitySubtitle => 'بالاترین کیفیت موجود انتخاب میشود';

  @override
  String get videoQualitySubtitleNote => 'خوب است که در صورت پیدا نشدن کیفیت، جایگزین های بیشتری را حفظ کنید، در غیر این صورت به بدترین کیفیت رجوع میکند.';

  @override
  String get videos => 'ویدیو ها';

  @override
  String get view => 'بازدید';

  @override
  String get viewAll => 'مشاهده همه';

  @override
  String get views => 'بازدید';

  @override
  String get volume => 'صدا';

  @override
  String get warning => 'اخطار';

  @override
  String get waveformBarsCount => 'تعداد خطوط موج';

  @override
  String get webmNoEditTagsSupport => 'پشتیبانی نمیشود WEBM ویرایش برچسب برای فورمت';

  @override
  String get week => 'هفته';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'سال';

  @override
  String get yes => 'بله';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'عضویت فعلی شما $name است';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Your custom order will be lost, Are you sure?';

  @override
  String get youtube => 'یوتیوب';

  @override
  String get youtubeMusic => 'یوتیوب موزیک';

  @override
  String get youtubeSettingsSubtitle => 'شخصی سازی تجربه یوتیوب';

  @override
  String get youtubeStyleMiniplayer => 'مینی پلیر به سبک یوتیوب';

  @override
  String get ytPreferNewComments => 'نظرات جدید را اولویت قرار بده';

  @override
  String get ytPreferNewCommentsSubtitle => 'شده تنها زمان بدون اینترنت استفاده خواهد شد cache نسخه';
}
