// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Hindi (`hi`).
class AppLocalizationsHi extends AppLocalizations {
  AppLocalizationsHi([String locale = 'hi']) : super(locale);

  @override
  String get about => 'हमारे बारे में';

  @override
  String get active => 'सक्रिय';

  @override
  String get add => 'जोड़े';

  @override
  String get addAccount => 'Account जोड़े';

  @override
  String get addAll => 'सभी को जोड़ो';

  @override
  String get addAllAndRemoveOldOnes => 'सभी जोड़ें और पुराने हटाएं';

  @override
  String get addAsANewPlaylist => 'नई playlist के रूप में जोड़ें';

  @override
  String get addAudioToLocalLibrary => 'Local library में ऑडियो जोड़ें';

  @override
  String get addFolder => 'Folder जोड़े';

  @override
  String get addLanguage => 'भासा जोड़े';

  @override
  String get addLanguageSubtitle => 'Namida को अपनी भाषा में अनुवाद करने में सहायता करें';

  @override
  String get addLrcFile => 'LRC file जोड़े';

  @override
  String get addMoreFromThisAlbum => 'इस album और जोड़े';

  @override
  String get addMoreFromThisArtist => 'इस कलाकार से और जोड़ें कतार में';

  @override
  String get addMoreFromThisFolder => 'इस folder से और जोड़ें queue में';

  @override
  String addMoreFromToQueue({required String media}) {
    return '$media से queue में और जोड़े';
  }

  @override
  String get addOnlyMissing => 'केवल लुप्त को ही जोड़ें';

  @override
  String get addToFavourites => 'पसंदीदा में जोड़ें';

  @override
  String get addToPlaylist => 'Playlist में जोड़ें';

  @override
  String get addTracksAtTheBeginning => 'शुरुआत में ट्रैक जोड़ें';

  @override
  String get added => 'जोड़ा गया है';

  @override
  String get advanced => 'उन्नत';

  @override
  String get advancedSettings => 'उन्नत settings';

  @override
  String get advancedSettingsSubtitle => 'उन्नत सेटिंग्स, स्पर्श न करें';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'एल्बम कलाकार';

  @override
  String get albumArtists => 'एल्बम कलाकार';

  @override
  String get albumIdentifiers => 'एल्बम पहचानकर्ता';

  @override
  String get albumThumbnailSizeInList => 'सूची में एल्बम थंबनेल का आकार';

  @override
  String get albumTileCustomization => 'एल्बम टाइल अनुकूलन';

  @override
  String get albums => 'एल्बम';

  @override
  String get albumsCount => 'एल्बम गणना';

  @override
  String get all => 'सभी';

  @override
  String get allTime => 'सभी समय';

  @override
  String get alreadyExists => 'पहले से मौजूद है';

  @override
  String get always => 'हमेशा';

  @override
  String get alwaysAsk => 'हमेशा पूछें';

  @override
  String get alwaysDim => 'हमेशा धुंधला करें';

  @override
  String get alwaysExpandedSearchbar => 'हमेशा विस्तारित खोज पट्टी';

  @override
  String get alwaysRestore => 'हमेशा बहाल करें';

  @override
  String get animatingThumbnailIntensity => 'थंबनेल एनिमेशन तीव्रता';

  @override
  String get animatingThumbnailInversed => 'उल्टे एनिमेशन';

  @override
  String get animatingThumbnailInversedSubtitle => 'उच्च चोटियों के कारण थंबनेल छोटा हो जाएगा';

  @override
  String get anotherProcessIsRunning => 'एक अन्य प्रक्रिया पहले ही चल रही है।';

  @override
  String get appIcon => 'ऐप आइकन';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'कलाकार';

  @override
  String get artists => 'कलाकार';

  @override
  String get artwork => 'कलाकृति';

  @override
  String get artworkGestures => 'कलाकृति इशारे';

  @override
  String get artworks => 'कलाकृतियाँ';

  @override
  String get audio => 'ऑडियो';

  @override
  String get audioCache => 'ऑडियो कैश';

  @override
  String get audioOnly => 'केवल ऑडियो';

  @override
  String get auto => 'ऑटो';

  @override
  String get autoBackupInterval => 'स्वचालित बैकअप अंतराल';

  @override
  String get autoColoring => 'ऑटो कलरिंग';

  @override
  String get autoColoringSubtitle => 'वर्तमान कलाकृति से स्वचालित रूप से खिलाड़ी रंग चुनें';

  @override
  String get autoExtractTagsFromFilename => 'फ़ाइल नाम से स्वतः निकालें';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'वीडियो शीर्षक से शीर्षक और कलाकार को स्वचालित रूप से निकालें';

  @override
  String get autoGenerated => 'स्वतः उत्पन्न';

  @override
  String get autoSkip => 'स्वतः स्किप करें';

  @override
  String get autoSkipOnce => 'एक बार ऑटो स्किप';

  @override
  String get autoStartRadio => 'अपने आप शुरू करें रेडियो';

  @override
  String get autoStartRadioSubtitle => 'अकेले ट्रैक चलाने पर स्वचालित रूप से मिक्स प्लेलिस्ट जोड़ता है';

  @override
  String get automaticBackup => 'स्वचालित';

  @override
  String get automaticBackupSubtitle => 'बैकअप स्थान के अंदर पाए गए सबसे हाल के बैकअप फ़ाइल को स्वचालित रूप से लागू करता है';

  @override
  String get backupAndRestore => 'बैकअप और पुनर्स्थापना';

  @override
  String get backupAndRestoreSubtitle => 'अपना डेटाबेस और सेटिंग्स बैकअप करें';

  @override
  String get balanced => 'संतुलित';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'तिथियों के बीच';

  @override
  String get bitrate => 'बिटरेट';

  @override
  String get blacklist => 'ब्लैकलिस्ट';

  @override
  String get borderRadiusMultiplier => 'बॉर्डर रेडियस मल्टीप्लायर';

  @override
  String get cache => 'कैश';

  @override
  String get cancel => 'रद्द करें';

  @override
  String get canceled => 'रद्द किया गया है';

  @override
  String get changed => 'बदल गया';

  @override
  String get changelog => 'चेंजलॉग';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'चैनल';

  @override
  String get channels => 'चैनल';

  @override
  String get check => 'विचार';

  @override
  String get checkForMore => 'और जांचें';

  @override
  String get checkList => 'जांच सूची';

  @override
  String get choose => 'चुनें';

  @override
  String get chooseWhatToClear => 'साफ़ करने के लिए क्या चुनें';

  @override
  String get claim => 'Claim';

  @override
  String get clear => 'स्वच्छ';

  @override
  String get clearAudioCache => 'ऑडियो कैश साफ़ करें';

  @override
  String get clearImageCache => 'छवि कैश साफ़ करें';

  @override
  String get clearImageCacheWarning => 'चेतावनी: छवियों के बिना एक पुस्तकालय का परिणाम होगा, केवल छवि कैश को पुनर्निर्माण करने के लिए उपयोग करें।';

  @override
  String get clearTrackItem => 'ट्रैक के साफ़ करें';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString ट्रैक साफ़ करें',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'वीडियो कैश साफ़ करें';

  @override
  String get clearVideoCacheNote => 'आप चुन सकते हैं कि क्या हटाना है।';

  @override
  String get clock => 'घड़ी';

  @override
  String get colorPalette => 'रंग पैलेट';

  @override
  String get colorPaletteNote1 => 'किसी रंग को हटाने के लिए उसे लंबे समय तक दबाएँ';

  @override
  String get colorPaletteNote2 => 'डिफ़ॉल्ट रंग के रूप में उपयोग करने के लिए मिश्रण पर टैप करें';

  @override
  String get colorPalettes => 'रंग पैलेट';

  @override
  String get comment => 'कॉमेंट';

  @override
  String get comments => 'कॉमेंटे';

  @override
  String get composer => 'संगीतकार';

  @override
  String get compress => 'कंप्रेस करें';

  @override
  String get compressImages => 'छवियों को संपीड़ित करें';

  @override
  String get compressionPercentage => 'संपीड़न प्रतिशत';

  @override
  String get configure => 'कॉन्फ़िगर करें';

  @override
  String get confirm => 'पुष्टि करें';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'कलाकृति कॉपी की गई';

  @override
  String get copiedToClipboard => 'क्लिपबोर्ड पर नकल';

  @override
  String get copy => 'कॉपी करें';

  @override
  String get corruptedFile => 'फ़ाइल को पार्स नहीं कर सका, यह दूषित हो सकता है';

  @override
  String get couldntOpen => 'खुल नहीं सका :(';

  @override
  String get couldntOpenYtLink => 'इस ट्रैक के लिए कोई यूट्यूब लिंक उपलब्ध नहीं है।';

  @override
  String get couldntPlayFile => 'फ़ाइल नहीं चला सका';

  @override
  String get couldntRenamePlaylist => 'प्लेलिस्ट का नाम नहीं बदल सका';

  @override
  String get couldntSaveImage => 'छवि सहेज नहीं सका';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'देश';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'बनाएं';

  @override
  String get createBackup => 'बैकअप बनाएं';

  @override
  String get createNewPlaylist => 'नई playlist बनाएं';

  @override
  String get createdBackupSuccessfully => 'बैकअप बनाया';

  @override
  String get createdBackupSuccessfullySub => 'बैकअप फ़ाइल सफलतापूर्वक बनाई गई है';

  @override
  String get crossPlatformSync => 'क्रॉस-प्लेटफ़ॉर्म सिंक';

  @override
  String get crossfadeDuration => 'Crossfade अवधि';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'अंतिम $secondsString सेकंडों में स्वचालित रूप से crossfade को trigger करे',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Crossfade को स्वचालित रूप से trigger न करें';

  @override
  String get custom => 'कस्टम';

  @override
  String get customizations => 'अनुकूलन';

  @override
  String get customizationsSubtitle => 'अपने player को देखने के तरीके को अनुकूलित करें, इसे अपना बनाएं';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'डेटा प्रदान किया गया है: $name';
  }

  @override
  String get dataSaver => 'डेटा सेवर';

  @override
  String get dataSaverMode => 'डेटा सेवर मोड';

  @override
  String get database => 'डेटाबेस';

  @override
  String get date => 'दिनांक';

  @override
  String get dateAdded => 'जोड़ा गया दिनांक';

  @override
  String get dateCreated => 'बनाए गए दिनांक';

  @override
  String get dateModified => 'दिनांक संशोधित';

  @override
  String get dateTimeFormat => 'दिनांक समय प्रारूप';

  @override
  String get day => 'दिन';

  @override
  String get days => 'दिन';

  @override
  String get defaultBackupLocation => 'डिफ़ॉल्ट बैकअप स्थान';

  @override
  String get defaultColor => 'डिफ़ॉल्ट रंग';

  @override
  String get defaultColorSubtitle => 'Player द्वारा उपयोग किए जाने वाले रंग को सेट करें';

  @override
  String get defaultDownloadLocation => 'डिफ़ॉल्ट डाउनलोड स्थान';

  @override
  String get defaultLabel => 'डिफ़ॉल्ट';

  @override
  String get defaultLibraryTab => 'डिफ़ॉल्ट लाइब्रेरी टैब';

  @override
  String get delete => 'हटाएँ';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString दिखाने वाले $totalSizeText को रद करें?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'अपने स्टोरेज से $numberText को स्थायी रूप से हटाएं';
  }

  @override
  String get deletePlaylist => 'प्लेलिस्ट हटाएं';

  @override
  String get deleteTempFiles => 'अस्थायी फ़ाइलें हटाएँ';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'विवरण';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'क्या आपका मतलब ये था';

  @override
  String get dimIntensity => 'मंद तीव्रता';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'निष्क्रियता के $secondsString सेकंड के बाद मिनिप्लेयर कम करें',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'निर्देशिका मौजूद नहीं है';

  @override
  String get disable => 'अक्षम करें';

  @override
  String get disableAll => 'सभी अक्षम करें';

  @override
  String get disableReordering => 'पुनर्निर्धारण अक्षम करें';

  @override
  String get disableSearchCleanup => 'खोज सफाई अक्षम करें';

  @override
  String get discNumber => 'डिस्क नंबर';

  @override
  String get discNumberTotal => 'कुल डिस्क';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'नापसंद';

  @override
  String get dismissibleMiniplayer => 'खारिज करने योग्य मिनिप्लेयर';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'सीक करते समय अंतर की जगह वास्तविक स्थिति दिखाएँ';

  @override
  String get displayAlbumCardTopRightDate => 'एल्बम कार्ड शीर्ष दायां तिथि';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'एल्बम कार्ड शीर्ष दाएं पर एल्बम तिथि प्रदर्श';

  @override
  String get displayArtistBeforeTitle => 'कलाकार को शीर्षक से पहले प्रदर्शित करें';

  @override
  String get displayArtworkOnLockscreen => 'लॉकस्क्रीन पर कलाकृति प्रदर्शित करें';

  @override
  String get displayAudioInfoInMiniplayer => 'ऑडियो जानकारी प्रदर्शित करें';

  @override
  String get displayFavButtonInNotification => 'Notification में पसंदीदा बटन प्रदर्शित करें';

  @override
  String get displayFavButtonInNotificationSubtitle => 'थंबनेल विस्थापित हो सकता है।';

  @override
  String get displayFavouriteIconInTrackTile => 'ट्रैक टाइल में पसंदीदा बटन प्रदर्शित करें';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'कुल के बजाय शेष अवधि प्रदर्शित करें';

  @override
  String get displayStopButtonInNotification => 'नोटिफिकेशन में स्टॉप बटन दिखाएँ';

  @override
  String get displayThirdItemInRowInTrackTile => 'ट्रैक टाइल में तीसरा आइटम प्रदर्शित करें';

  @override
  String get displayThirdRowInTrackTile => 'तीसरी पंक्ति प्रदर्शित करें';

  @override
  String get displayTrackNumberInAlbumPage => 'एल्बम पृष्ठ में ट्रैक नंबर प्रदर्शित करें';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'एल्बम पृष्ठ में ट्रैक नंबर वाला एक छोटा बॉक्स प्रदर्शित करें';

  @override
  String get doNothing => 'कुछ मत करो';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'किया हुआ';

  @override
  String get dontAskAgain => 'फिर पूछना मत';

  @override
  String get dontDim => 'धुंधला न करें';

  @override
  String get dontRestorePosition => 'पुनर्स्थापित न करें';

  @override
  String get dontResume => 'फिर से शुरू न करें';

  @override
  String get doubleTapToToggleLyrics => 'लिरिक्रस टॉगल करने के लिए डबल टैप करें';

  @override
  String get download => 'डाउनलोड';

  @override
  String get downloadingWillOverrideIt => 'Download करने से यह override हो जायेगा';

  @override
  String get downloads => 'डाउनलोड्स';

  @override
  String get downloadsMetadataTags => 'डाउनलोड्स मेटाडेटा टैग';

  @override
  String get downloadsMetadataTagsSubtitle => 'वीडियो जानकारी से कलाकार, शीर्षक और एल्बम को डिफ़ॉल्ट रूप से निकालें';

  @override
  String get dragToSeek => 'करने के लिए खींचें तलाश';

  @override
  String get duckAudio => 'डक ऑडियो';

  @override
  String get duplicatedItemsAdding => 'आप कुछ ऐसे आइटम जोड़ने का प्रयास कर रहे हैं जो पहले से ही इस प्लेलिस्ट में मौजूद हैं';

  @override
  String get duplicatedTracks => 'डुप्लिकेट ट्रैक';

  @override
  String get duration => 'अवधि';

  @override
  String get edgeColorsSwitching => 'किनारे रंग स्विचिंग';

  @override
  String get edit => 'संपादित करें';

  @override
  String get editArtwork => 'कलाकृति संपादित करें';

  @override
  String get editTags => 'टैग संपादित करें';

  @override
  String get email => 'ईमेल';

  @override
  String get emptyNonMeaningfulTagFields => 'आपके पास खाली/अर्थहीन टैग फ़ील्ड हैं, सुनिश्चित करें कि आप उन्हें वास्तव में संपादित करना चाहते हैं';

  @override
  String get emptyValue => 'खाली मूल्य';

  @override
  String get enableArtworkCache => 'Artwork Cache सक्षम करें';

  @override
  String get enableArtworkCacheSubtitle => 'तेज़ लोडिंग और बेहतर प्रदर्शन, लेकिन अधिक स्टोरेज का उपयोग करता है';

  @override
  String get enableBlurEffect => 'ब्लर प्रभाव सक्षम करें';

  @override
  String get enableBottomNavBar => 'बॉटम नेविगेशन बार सक्षम करें';

  @override
  String get enableBottomNavBarSubtitle => 'आइटम दोनों तरह से ड्रॉअर के अंदर होते हैं';

  @override
  String get enableClipboardMonitoring => 'Clipboard monitoring को सक्षम करें';

  @override
  String get enableClipboardMonitoringSubtitle => 'Search bar को लिंक और टेक्स्ट चिपकाने की अनुमति दें';

  @override
  String get enableCrossfadeEffect => 'Crossfade प्रभाव सक्षम करें';

  @override
  String get enableFadeEffectOnPlayPause => 'प्ले/पॉज़ पर फेड प्रभाव सक्षम करें';

  @override
  String get enableFoldersHierarchy => 'फ़ोल्डर्स पदानुक्रम सक्षम करें';

  @override
  String get enableGlowEffect => 'चमक प्रभाव सक्षम करें';

  @override
  String get enableM3uSync => 'M3U सिंक सक्षम करें';

  @override
  String get enableM3uSyncNote1 => 'M3U सिंक मूल M3U फ़ाइल में प्लेलिस्ट परिवर्तनों को सहेजने की अनुमति देता है';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'अगर कुछ गलत हो जाता है, तो इस प्लेलिस्ट का बैकअप $playlistsBackupPath में पाया जाएगा';
  }

  @override
  String get enableM3uSyncSubtitle => 'यदि अस्वीकार कर दिया गया है, तो इस प्लेलिस्ट में किए गए सभी परिवर्तन पुनः आरंभ करने पर खो जाएंगे';

  @override
  String get enableMiniplayerParticles => 'चलते कणों को सक्षम करें';

  @override
  String get enableParallaxEffect => 'पैरालैक्स प्रभाव सक्षम करें';

  @override
  String get enablePartyMode => 'पार्टी मोड सक्षम करें';

  @override
  String get enablePartyModeSubtitle => 'फैंसी एज ब्रीदिंग प्रभाव लागू करें';

  @override
  String get enablePictureInPicture => 'पिक्चर-इन-पिक्चर सक्षम करें';

  @override
  String get enableReordering => 'पुनर्व्यवस्था सक्षम करें';

  @override
  String get enableReturnYoutubeDislike => 'यूट्यूब डिसलाइक दिखाना सक्षम करें';

  @override
  String get enableSearchCleanup => 'खोज सफाई सक्षम करें';

  @override
  String get enableSearchCleanupSubtitle => 'सभी प्रतीकों और रिक्त स्थानों को अनदेखा कर दिया जाएगा';

  @override
  String get enableSponsorblock => 'SponsorBlock सक्षम करें';

  @override
  String get enableVideoPlayback => 'वीडियो प्लेबैक सक्षम करें';

  @override
  String get enterSymbol => 'कृपया एक प्रतीक दर्ज करें';

  @override
  String get equalizer => 'Equalizer';

  @override
  String get error => 'त्रुटि';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'ट्रैक चलाने में त्रुटि';

  @override
  String get excludedFodlers => 'बहिष्कृत फ़ोल्डर';

  @override
  String get exit => 'बाहर जाएं';

  @override
  String get exitAppSubtitle => 'बाहर निकलने के लिए फिर से टैप करें';

  @override
  String get expandedMiniplayer => 'विस्तारित मिनीप्लेयर';

  @override
  String get exportAsM3u => 'M3U के रूप में निर्यात करें';

  @override
  String get extension => 'विस्तार';

  @override
  String get externalFiles => 'बाह्य फ़ाइलें';

  @override
  String get extract => 'निकालें';

  @override
  String get extractAllColorPalettes => 'सभी रंग palette निकालें';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'शेष $numberString निकालें?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'शीर्षक से feat. कलाकारों को निकालें';

  @override
  String get extractFeatArtistSubtitle => 'नए कलाकार प्रविष्टि के रूप में (feat. X) और (ft. X) कलाकारों को निकालता है।';

  @override
  String get extractingInfo => 'जानकारी निकाल रहा है';

  @override
  String get extras => 'अतिरिक्त';

  @override
  String get extrasSubtitle => 'अपने अनुभव को ठीक करने के लिए अतिरिक्त सेटिंग्स';

  @override
  String get extreme => 'अत्यधिक';

  @override
  String get failed => 'विफल';

  @override
  String get failedEdits => 'विफल संपादन';

  @override
  String get favourites => 'पसंदीदा';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'प्राप्त कर रहा है';

  @override
  String get fetchingOfAllVideos => 'सारे वीडियो को प्राप्त कर रहा';

  @override
  String get file => 'फ़ाइल';

  @override
  String get fileAlreadyExists => 'फ़ाइल पहले से मौजूद है';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'फ़ाइल का नाम';

  @override
  String get fileNameWoExt => 'बिना extension के फ़ाइल नाम';

  @override
  String get filenameShouldntStartWith => 'फ़ाइल नाम की शुरुआत इस प्रकार नहीं होनी चाहिए';

  @override
  String get files => 'फ़ाइलें';

  @override
  String get filler => 'फिलर';

  @override
  String get filterAlbums => 'एल्बम फ़िल्टर करें';

  @override
  String get filterArtists => 'कलाकारों को फ़िल्टर करें';

  @override
  String get filterGenres => 'शैलियाँ फ़िल्टर करें';

  @override
  String get filterPlaylists => 'प्लेलिस्ट फ़िल्टर करें';

  @override
  String get filterTracks => 'ट्रैक फ़िल्टर करें';

  @override
  String get filterTracksBy => 'खोज सूचियों में ट्रैक फ़िल्टर करें';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'आकार और अवधि के अनुसार फ़िल्टर किए गए ट्रैक';

  @override
  String get finished => 'समाप्त';

  @override
  String get finishedUpdatingLibrary => 'लाइब्रेरी अपडेट करना समाप्त हुआ';

  @override
  String get firstListen => 'पहले सुना';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp के बड़े थंबनेल आकार को ठीक करें';

  @override
  String get floatingActionButton => 'फ़्लोटिंग एक्शन बटन';

  @override
  String get folder => 'फ़ोल्डर';

  @override
  String get folderName => 'फ़ोल्डर नाम';

  @override
  String get folders => 'फ़ोल्डर्स';

  @override
  String get fontScale => 'फ़ॉन्ट स्केल';

  @override
  String get forceMiniplayerFollowTrackColors => 'ट्रैक रंगों का पालन करने के लिए miniplayer को बाध्य करें';

  @override
  String get forceSquaredAlbumThumbnail => 'वर्ग एल्बम थंबनेल को लागू करें';

  @override
  String get forceSquaredThumbnailNote => 'थंबनाइल का आकार और टाइल की ऊंचाई बराबर नहीं है, वर्गाकार जैसा लुक अपेक्षित नहीं होगा, क्या आप उन्हें बराबर करना चाहते हैं?';

  @override
  String get forceSquaredTrackThumbnail => 'वर्ग ट्रैक थंबनाइल को मजबूर करें';

  @override
  String get forceStopColorPaletteGeneration => 'क्या आप रंग पैलेट निकालना बंद करना चाहते हैं? आप इसे बाद में भी जारी रख सकते हैं';

  @override
  String get format => 'प्रारूप';

  @override
  String get fullscreen => 'फुलस्क्रीन';

  @override
  String get gaplessPlayback => 'बिना विराम प्लेबैक';

  @override
  String get generate => 'उत्पन्न करना';

  @override
  String get generateFromDates => 'समय सीमा';

  @override
  String get generateFromDatesSubtitle => 'उन ट्रैक्स को जेनरेट करें जिन्हें आपने एक समय सीमा में सुना था';

  @override
  String get generateRandomPlaylist => 'यादृच्छिक प्लेलिस्ट बनाएं';

  @override
  String get genre => 'शैली';

  @override
  String get genres => 'शैलियाँ';

  @override
  String get goToAlbum => 'एल्बम में जाएं';

  @override
  String get goToArtist => 'कलाकार के पास जाएं';

  @override
  String get goToChannel => 'चैनल में जाएं';

  @override
  String get goToFolder => 'फ़ोल्डर में जाएं';

  @override
  String get goodLooking => 'सुंदर दिखने वाला';

  @override
  String get grantStoragePermission => 'स्टोरेज अनुमति प्रदान करें';

  @override
  String get group => 'ग्रुप';

  @override
  String get groupArtworksByAlbum => 'ग्रुप आर्टवर्क बाय एल्बम';

  @override
  String get guide => 'गाइड';

  @override
  String get hapticFeedback => 'हैप्टिक फ़ीडबैक';

  @override
  String get heightOfAlbumTile => 'एल्बम टाइल की ऊंचाई';

  @override
  String get heightOfTrackTile => 'ट्रैक टाइल की ऊंचाई';

  @override
  String get hideSkipButtonAfter => 'इसके बाद स्किप बटन छिपाएँ';

  @override
  String get highMatches => 'उच्च मिलान';

  @override
  String get highPerformance => 'उच्च performance';

  @override
  String get highlight => 'हाइलाइट';

  @override
  String get history => 'इतिहास';

  @override
  String get historyImportMissingEntriesNote =>
      'ये प्रविष्टियां लाइब्रेरी के अंदर नहीं मिलीं, यदि आपको लगता है कि वे मौजूद हैं, तो कृपया उन्हें मैन्युअल रूप से जोड़ने पर विचार करें';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString सुनता है OLD${track}INFO के लिए NEW${track}INFO के साथ बदल दिया जाएगा, पुष्टि करें?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'होम';

  @override
  String get hook => 'हुक';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12 घंटे का प्रारूप';

  @override
  String get hours => 'घंटे';

  @override
  String get iReadAndAgree => 'मैंने पढ़ा और सहमत हूं';

  @override
  String get ifNotPlaying => 'यदि नहीं चल रहा है';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'जब ऐप बैटरी प्रतिबंधित होती है तो डाउनलोड को कम किया जा सकता है';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'सॉर्ट करते समय सामान्य प्रीफिक्स को अनदेखा करें';

  @override
  String get ignores => 'अनदेखा करता';

  @override
  String get imageSource => 'इमेज स्रोत';

  @override
  String get immersiveMode => 'इमर्सिव मोड';

  @override
  String get immersiveModeSubtitle => 'Miniplayer के विस्तारित होने पर स्टेटस और नेविगेशन बार छुपाएं';

  @override
  String get import => 'आयात';

  @override
  String get importAll => 'सभी आयात करें';

  @override
  String get importLastFmHistory => 'लस्ट एफएम इतिहास आयात करें';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. $lastfmCsvLink पर जाएं\n\n2. अपना उपयोगकर्ता नाम टाइप करें, फ़ेच करें और csv फ़ाइल डाउनलोड करें।\n\n3. अगली स्क्रीन से फ़ाइल चुनें।';
  }

  @override
  String get importTimeRange => 'समय सीमा आयात करें';

  @override
  String get importYoutubeHistory => 'यूट्यूब इतिहास आयात करें';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. $takeoutLink पर जाएं\n\n2. \"कई प्रारूप\" दबाएं और \"इतिहास\" के बगल में \"JSON\" चुनें।\n\n3. \"सभी यूट्यूब डेटा शामिल\" दबाएं, सभी का चयन रद्द करें और केवल इतिहास चुनें।\n\n4. निर्यात बनाएं, डाउनलोड करें और अनज़िप करें।\n\n5. अगली स्क्रीन से \"watch-history.json\" चुनें।';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString को चैनल से प्राप्त करना सफल हुआ',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText प्लेलिस्ट की प्राप्ति सफल हुई',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'वीडियो शामिल करें';

  @override
  String get indexRefreshRequired => 'इसे बदलने के बाद रिफ्रेश करें';

  @override
  String get indexer => 'अनुक्रमक';

  @override
  String get indexerNote => 'नोट: अधूरा संख्या कलाकृतियों का तात्पर्य दोहराए गए और नहीं पाए गए कलाकृतियों से है';

  @override
  String get indexerSubtitle => 'अपनी संगीत लाइब्रेरी प्रबंधित करें';

  @override
  String get infinityQueueOnNextPrev => 'अगला/पिछला पर इन्फिनिटी कतार';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'अंतिम आइटम चलाते समय अगला दबाने से पहले कूद जाएगा, और इसके विपरीत';

  @override
  String get info => 'जानकारी';

  @override
  String get inserted => 'सम्मिलित किया गया';

  @override
  String get instantlyApplies => 'तुरंत लागू होता है';

  @override
  String get interactionReminder => 'इंटरैक्शन रिमाइंडर';

  @override
  String get intro => 'इंट्रो';

  @override
  String get invertSelection => 'उलट चयन';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'आइटम';

  @override
  String get jump => 'कूदें';

  @override
  String get jumpToDay => 'दिन में कूदें';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Queue समाप्त होने के बाद पहले ट्रैक पर जाएं';

  @override
  String get keepCachedVersions => 'संस्करण कैश करें';

  @override
  String get keepFileDates => 'फ़ाइल तिथियां रखें';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniplayer का विस्तार किया गया है';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniplayer का विस्तार किया गया है और एक वीडियो चल रहा है';

  @override
  String get keepScreenAwakeNone => 'स्क्रीन को जगाए नहीं रखें';

  @override
  String get keepScreenAwakeWhen => 'स्क्रीन को जगाए रखें जब';

  @override
  String get killPlayerAfterDismissingApp => 'ऐप को बंद करने के बाद player को भी बंद कर दें';

  @override
  String get language => 'भाषा';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'लाइब्रेरी टैब्स';

  @override
  String get libraryTabsReorder => 'आप सक्रिय टैब्स को पुनः व्यवस्थित कर सकते हैं।';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'पसंद';

  @override
  String get liked => 'पसंद किया';

  @override
  String get link => 'लिंक';

  @override
  String get listOfFolders => 'फ़ोल्डरों की सूची';

  @override
  String get loadAll => 'सब लोड करें';

  @override
  String get loadingFile => 'फ़ाइल लोड हो रही है';

  @override
  String get local => 'स्थानीय';

  @override
  String get localVideoMatching => 'स्थानीय वीडियो मिलान';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Long press the lyrics to enter fullscreen';

  @override
  String get lostMemories => 'खोई यादें';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'इस समय के आसपास, $numberString साल पहले',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'प्रबलता बढ़ाने वाला';

  @override
  String get lyricist => 'Lyricist(रचयिता)';

  @override
  String get lyrics => 'लिरिक्स';

  @override
  String get lyricsSource => 'लिरिक्स स्रोत';

  @override
  String get m3uPlaylist => 'M3U प्लेलिस्ट';

  @override
  String get makeYourFirstListen => 'अपनी पहली सुनवाई करें!';

  @override
  String get manage => 'परिचालन';

  @override
  String get manageYourAccounts => 'अपनी अकाउंट्स के परिचालन करें';

  @override
  String get manualBackup => 'मैनुअल';

  @override
  String get manualBackupSubtitle => 'एक विशिष्ट फ़ाइल चुनें';

  @override
  String get markAsRead => 'देखा गया है चिन्हित करें';

  @override
  String get matchAllTracks => 'सभी ट्रैक्स को मिलाएं';

  @override
  String get matchAllTracksNote => 'इसका मिलान गति पर प्रभाव पड़ सकता है, क्योंकि यह आपकी लाइब्रेरी में सभी ट्रैक्स की जाँच करेगा';

  @override
  String get matchingType => 'मिलान प्रकार';

  @override
  String get maxAudioCacheSize => 'अधिकतम ऑडियो कैश आकार';

  @override
  String get maxImageCacheSize => 'अधिकतम छवि कैश आकार';

  @override
  String get maxVideoCacheSize => 'अधिकतम वीडियो कैश आकार';

  @override
  String get maximum => 'अधिकतम';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store is enabled, this will have no effect';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'कोड';

  @override
  String get membershipCodeSentToEmail => 'कोड आपके ईमेल पर भेजा गया है';

  @override
  String get membershipDidntChange => 'मेंबरशिप परिवर्तन नही हुई';

  @override
  String get membershipEnjoyNew => 'आपकी नई मेमेबरशिप की आनंद उठाएं';

  @override
  String get membershipFreeCoupon => 'मुफ्त की कूपन';

  @override
  String get membershipManage => 'आपकी मेंबरशिप की परिचालन करें';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'इस बाबाहरकार की कोई subscription नही मिली';

  @override
  String get membershipSignInToPatreonAccount => 'अपने योगदाता अकाउंट पर sign in करें';

  @override
  String get membershipUnknown => 'अज्ञात मेंबरशिप';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'आपको $name1 या $name2 जोड़ने के लिए मेंबरशिप चहिए';
  }

  @override
  String get merge => 'मर्ज';

  @override
  String get metadataCache => 'Metadata Cache';

  @override
  String get metadataEditFailed => 'Metadata संपादित करने में विफल';

  @override
  String get metadataReadFailed => 'Metadata पढ़ने में विफल';

  @override
  String get minFileDuration => 'न्यूनतम ट्रैक अवधि';

  @override
  String get minFileSize => 'न्यूनतम फ़ाइल आकार';

  @override
  String get minTrackDurationToRestoreLastPosition => 'अंतिम प्लेबैक स्थिति को पुनर्स्थापित करने के लिए न्यूनतम ट्रैक अवधि';

  @override
  String get minValueCantBeMoreThanMax => 'न्यूनतम मान अधिकतम से अधिक नहीं हो सकता';

  @override
  String get minValueToCountTrackListen => 'इसके बाद सुनें: ';

  @override
  String get minimizedMiniplayer => 'न्यूनतम Miniplayer';

  @override
  String get minimum => 'न्यूनतम';

  @override
  String get minimumOneFolderSubtitle => 'कम से कम 1 फ़ोल्डर होना चाहिए, यदि आप इसे निकालना चाहते हैं तो अधिक फ़ोल्डर जोड़ें';

  @override
  String get minimumOneItem => 'आइटम नहीं हटा सका';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'कम से कम $numberString आइटम रहना चाहिए',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'मिनिप्लेयर अनुकूलन';

  @override
  String get minutes => 'मिनट';

  @override
  String get missingEntries => 'गायब प्रविष्टियाँ';

  @override
  String get missingTracks => 'लापता ट्रैक';

  @override
  String get mix => 'मिलाए';

  @override
  String get mixPlaylistGeneratedByYoutube => 'यूट्यूब द्वारा निर्मित मिक्स प्लेलिस्ट';

  @override
  String get mixes => 'मिक्स';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'महीना';

  @override
  String get months => 'महीने';

  @override
  String get mood => 'मूड';

  @override
  String get moods => 'मूड';

  @override
  String get more => 'अधिक';

  @override
  String get mostPlayed => 'सबसे ज्यादा खेला गया';

  @override
  String get multipleTracksTagsEditNote => 'आप इन ट्रैक्स को संपादित करने वाले हैं,\nबदल न किए गए क्षेत्र अछूते रहते हैं।';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'नाम';

  @override
  String get nameContainsBadCharacter => 'नाम में खराब चरित्र शामिल है';

  @override
  String get never => 'कभी नहीं';

  @override
  String get newDirectory => 'नई निर्देशिका';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'ट्रैक जोड़ें';

  @override
  String get newTracksMoods => 'मूड';

  @override
  String get newTracksMoodsSubtitle => 'उपलब्ध मूड के आधार पर ट्रैक उत्पन्न करें';

  @override
  String get newTracksRandom => 'यादृच्छिक';

  @override
  String get newTracksRandomSubtitle => 'अपनी लाइब्रेरी से यादृच्छिक ट्रैक चुनें';

  @override
  String get newTracksRatings => 'रेटिंग';

  @override
  String get newTracksRatingsSubtitle => 'ऐसे ट्रैक उत्पन्न करें जिनकी विशिष्ट रेटिंग है';

  @override
  String get newTracksRecommended => 'सुझाया गया';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return '$currentTrack के साथ आमतौर पर आपने जो ट्रैक सुने हैं, उन्हें उत्पन्न करें';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'समान रिलीज़ तिथि';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return '$currentTrack के समान समय के आसपास रिलीज़ किए गए ट्रैक उत्पन्न करें';
  }

  @override
  String get newTracksUnknownYear => 'ट्रैक में अज्ञात वर्ष है';

  @override
  String get newest => 'सबसे नया';

  @override
  String get next => 'Next';

  @override
  String get no => 'नहीं';

  @override
  String get noChangesFound => 'कोई परिवर्तन नहीं मिला।';

  @override
  String get noEnoughTracks => 'आपके पास ज्यादा ट्रैक नहीं हैं..';

  @override
  String get noExcludedFolders => 'आपके पास कोई बहिष्कृत फ़ोल्डर नहीं है';

  @override
  String get noFolderChosen => 'आपने कोई फ़ोल्डर नहीं चुना है';

  @override
  String get noMoodsAvailable => 'कोई मूड उपलब्ध नहीं है';

  @override
  String get noNetworkAvailableToFetchData => 'तथ्य प्राप्त करने के लिए कोई भी नेटवर्क नही है';

  @override
  String get noTracksFound => 'कोई ट्रैक नहीं मिला';

  @override
  String get noTracksFoundBetweenDates => 'इस timerange में कोई track नही है।';

  @override
  String get noTracksFoundInDirectory => 'इस निर्देशिका में कोई track नहीं मिला';

  @override
  String get noTracksInHistory => 'आपके पास इतिहास में पर्याप्त track नहीं हैं';

  @override
  String get nonActive => 'गैर-सक्रिय';

  @override
  String get nonFavourites => 'गैर-पसंदीदा';

  @override
  String get none => 'कोई नहीं';

  @override
  String get normalizeAudio => 'ऑडियो को सामान्य करें';

  @override
  String get normalizeAudioSubtitle => 'रीप्ले गेन टैग या यूट्यूब द्वारा प्रदान की गई जानकारी को पढ़कर वॉल्यूम को सामान्य करता है';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'ध्यान दें';

  @override
  String get notification => 'Notification';

  @override
  String get notifications => 'Notifications';

  @override
  String get numberOfTracks => 'Tracks की संख्या';

  @override
  String get ofLabel => 'का';

  @override
  String get offlineSearch => 'ऑफ़लाइन खोज';

  @override
  String get offset => 'ऑफ़सेट';

  @override
  String get oldDirectory => 'पुरानी निर्देशिका';

  @override
  String get oldDirectoryStillHasTracks => 'पुराने डायरेक्टरी में अभी भी कुछ track हैं, पुष्टि करें?';

  @override
  String get oldestWatch => 'सबसे पुराना वॉच';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'बाधित होने पर';

  @override
  String get onNotificationTap => 'Notification टैप पर';

  @override
  String get onOpeningYoutubeLink => 'यूट्यूब लिंक खोलते समय';

  @override
  String get onSwiping => 'स्वाइप करने पर';

  @override
  String get onVolumeZero => 'वॉल्यूम 0 पर';

  @override
  String get ongoing => 'चल रहा है';

  @override
  String get open => 'खोले';

  @override
  String get openApp => 'ऐप खोलें';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'YouTube view में खोलें';

  @override
  String get openMiniplayer => 'Miniplayer खोले';

  @override
  String get openQueue => 'Queue खोलें';

  @override
  String get openYoutubeLink => 'यूट्यूब लिंक खोलें';

  @override
  String operationRequiresAccount({required String name}) {
    return 'कार्य $name को करने के लिए अकाउंट चाहिए, आगे बढ़ने के लिए sign in करें';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'कार्य $operation करने के लिए कमसेकम membership $name चाहिए';
  }

  @override
  String get or => 'या';

  @override
  String get others => 'अन्य';

  @override
  String get output => 'बहिर्गमन';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'उसी folder में पुरानी फ़ाइलों को override करें';

  @override
  String get palette => 'पैलेट';

  @override
  String get paletteMix => 'मिक्स';

  @override
  String get paletteNewMix => 'नया मिक्स';

  @override
  String get paletteSelectedMix => 'चयनित मिक्स';

  @override
  String get parallelDownloads => 'समानांतर डाउनलोड';

  @override
  String get parsed => 'पार्स किया गया';

  @override
  String get password => 'Password';

  @override
  String get path => 'फाइल फुल पाथ';

  @override
  String get pause => 'रोकें';

  @override
  String get pauseFadeDuration => 'रोकें फीका अवधि';

  @override
  String get pausePlayback => 'प्लेबैक रोकें';

  @override
  String get percentage => 'प्रतिशत';

  @override
  String get performanceMode => 'प्रदर्शन मोड';

  @override
  String get performanceNote => 'प्रदर्शन को प्रभावित कर सकता है';

  @override
  String get personalized => 'वेक्तिगत';

  @override
  String get personalizedRelatedVideos => 'व्यक्तिगत संबंधित वीडियो';

  @override
  String get personalizedRelatedVideosSubtitle => 'इसे अक्षम करने से डेटा उपयोग बढ़ जाएगा';

  @override
  String get pickColorsFromDeviceWallpaper => 'डिवाइस वॉलपेपर से रंग चुनें';

  @override
  String get pickFromStorage => 'स्टोरेज से चुनें';

  @override
  String get pinned => 'पिन किया गया';

  @override
  String get pitch => 'पिच';

  @override
  String get plain => 'सादा';

  @override
  String get play => 'खेल';

  @override
  String get playAfter => 'बाद में चलाएं';

  @override
  String get playAfterNextPrev => 'अगले/पिछले पर ऑटो प्ले';

  @override
  String get playAll => 'सभी चलाएं';

  @override
  String get playFadeDuration => 'प्ले फीका अवधि';

  @override
  String get playLast => 'आखिरी चलाएं';

  @override
  String get playNext => 'अगला चलाएं';

  @override
  String get playbackSetting => 'प्लेबैक';

  @override
  String get playbackSettingSubtitle => 'प्लेयर में सीधे ऑडियो बटन को लंबे समय तक दबाकर एक्सेस किया जा सकता है';

  @override
  String get playlist => 'प्लेलिस्ट';

  @override
  String get playlists => 'प्लेलिस्ट';

  @override
  String get playlistsImportM3uNative => 'यह M3U प्लेलिस्ट को केवल नामीदा द्वारा उपयोग करने के लिए आयात करेगा, यदि आप माइग्रेट कर रहे हैं तो इसका उपयोग करें';

  @override
  String get playlistsImportM3uSynced =>
      'यह स्वचालित रूप से इंडेक्सर फ़ोल्डरों से M3U प्लेलिस्ट आयात करेगा और उन्हें मूल M3U फ़ाइल के साथ सिंक करेगा। यदि आप अन्य ऐप्स से प्लेलिस्ट तक पहुंचते हैं / संशोधित करते हैं तो सक्षम करें';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'M3U प्लेलिस्ट स्वचालित रूप से आयात करें';

  @override
  String get pleaseEnterADifferentName => 'यह नाम पहले से मौजूद है :(\nकृपया एक और फैंसी नाम आज़माएं';

  @override
  String get pleaseEnterALink => 'कृपया एक लिंक दर्ज करें';

  @override
  String get pleaseEnterALinkSubtitle => 'उमम.. क्या यह एक यूट्यूब लिंक है?';

  @override
  String get pleaseEnterAName => 'कृपया एक नाम दर्ज करें';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'डुप्लिकेट ट्रैक को रोकें';

  @override
  String get preventDuplicatedTracksSubtitle => 'ट्रैक को विशिष्ट रूप से पहचानने के लिए फ़ाइलनाम का उपयोग करता है';

  @override
  String get preview => 'पूर्वावलोकन(preview)';

  @override
  String get previous => 'Previous';

  @override
  String get previousButtonReplays => 'पिछले बटन रिप्ले';

  @override
  String get previousButtonReplaysSubtitle => 'यदि दबाया गया जबकि वर्तमान स्थिति खोज अवधि से अधिक थी';

  @override
  String get prioritizeEmbeddedLyrics => 'Embedded गीतों को प्राथमिकता दें';

  @override
  String get priority => 'Priority';

  @override
  String get private => 'निजी';

  @override
  String get progress => 'प्रगति';

  @override
  String get promptToChangeTrackPath =>
      'आमतौर पर ऐसा तब होता है जब आप फ़ाइल को Namida से बाहर निकालते हैं/स्थानांतरित करते हैं/नाम बदलते हैं, क्या आप वर्तमान पथ को अपडेट करना चाहते हैं?';

  @override
  String get public => 'जनता';

  @override
  String get queue => 'Queue';

  @override
  String get queues => 'Queues';

  @override
  String get random => 'बेतरतीब';

  @override
  String get randomPicks => 'बेतरतीब ढंग से चुने गए';

  @override
  String get rating => 'रेटिंग';

  @override
  String get reIndex => 'पुनः अनुक्रमित करें';

  @override
  String get reIndexSubtitle => 'अपनी संगीत लाइब्रेरी को खरोंच से फिर से बनाएं';

  @override
  String get reIndexWarning => 'यह प्रक्रिया आपकी लाइब्रेरी के आकार के आधार पर कुछ समय ले सकती है।\n\nजब तक वे मौजूद हैं, कलाकृतियों को फिर से अनुक्रमित नहीं किया जाएगा';

  @override
  String get recentAlbums => 'हाल ही में जोड़े गए एल्बम';

  @override
  String get recentArtists => 'हाल ही में जोड़े गए कलाकार';

  @override
  String get recentListens => 'हाल ही में सुने गए';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'हाल ही में जोड़ा गया';

  @override
  String get recordLabel => 'रिकॉर्ड लेबल';

  @override
  String get refresh => 'Refresh करें';

  @override
  String get refreshLibrary => 'लाइब्रेरी refresh करें';

  @override
  String get refreshLibrarySubtitle => 'हाल ही में जोड़े गए या हटाए गए संगीत की जांच करें';

  @override
  String get refreshOnStartup => 'स्टार्टअप पर रिफ्रेश करें';

  @override
  String get relatedVideos => 'सम्मांधित वीडियो';

  @override
  String get rememberAudioOnlyMode => 'केवल ऑडियो मोड याद रखें';

  @override
  String get remixer => 'रीमिक्सर';

  @override
  String get remove => 'हटाएं';

  @override
  String get removeDuplicates => 'डुप्लिकेट हटाएं';

  @override
  String get removeFromFavourites => 'पसंदीदा से हटाए';

  @override
  String get removeFromLibrary => 'Library से निकालें';

  @override
  String get removeFromPlaylist => 'Playlist से निकालें';

  @override
  String get removeQueue => 'Queue हटाएं';

  @override
  String get removeSourceFromHistory => 'स्रोत को इतिहास से हटाएं';

  @override
  String get removeWhitespaces => 'Whitespaces हटाएं';

  @override
  String get removed => 'हटाया गया';

  @override
  String get rename => 'नाम बदलें';

  @override
  String get renamePlaylist => 'प्लेलिस्ट का नाम बदलें';

  @override
  String get reorderable => 'पुनर्व्यवस्थित करने योग्य';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number और बार दोहराएं',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Repeat mode';

  @override
  String get repeatModeAll => 'Queue से सभी दोहराएं';

  @override
  String get repeatModeNone => 'अंतिम ट्रैक पर रुकें';

  @override
  String get repeatModeOne => 'वर्तमान ट्रैक दोहराएं';

  @override
  String get replaceAllListensWithAnotherTrack => 'सभी सूचियों को किसी अन्य ट्रैक से बदलें';

  @override
  String get replies => 'उत्तर';

  @override
  String get reply => 'जवाब';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Image Cache साफ़ करने और पुन: अनुक्रमण की आवश्यकता है';

  @override
  String get rescanVideos => 'वीडियो फिर से स्कैन करें';

  @override
  String get resetBrightness => 'चमक रीसेट करें';

  @override
  String get resetToDefault => 'सेट करें';

  @override
  String get respectNoMedia => '.nomedia का सम्मान करें';

  @override
  String get respectNoMediaSubtitle => 'ऐसे फ़ोल्डर शामिल न करें जिनमें .nomedia हो';

  @override
  String get restart => 'पुनः आरंभ करें';

  @override
  String get restoreBackup => 'बैकअप बहाल करें';

  @override
  String get restoreDefaults => 'डिफ़ॉल्ट्स पुनर्स्थापित करें';

  @override
  String get restoredBackupSuccessfully => 'बैकअप सफलतापूर्वक बहाल किया गया';

  @override
  String get restoredBackupSuccessfullySub => 'बैकअप फ़ाइल सफलतापूर्वक बहाल कर दी गई है';

  @override
  String get resume => 'जारी रखें';

  @override
  String get resumeIfWasInterrupted => 'यदि रुकावट के कारण रोक दिया गया था तो फिर से शुरू करें';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'यदि वॉल्यूम द्वारा रोक दिया गया था तो फिर से शुरू करें';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'यदि $numberString मिनट से कम समय के लिए रोका गया था तो पुनः आरंभ करें',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'उलटा क्रम';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'रिंगटोन';

  @override
  String get sameDirectoryOnly => 'केवल एक ही निर्देशिका';

  @override
  String get sample => 'Sample';

  @override
  String get sampleRate => 'नमूना दर';

  @override
  String get save => 'सहेजें';

  @override
  String get saveToLibrary => 'Library में save करें';

  @override
  String get savedIn => 'में सहेजा गया';

  @override
  String get scaleMultiplier => 'स्केल गुणक';

  @override
  String get search => 'खोज';

  @override
  String get searchYoutube => 'यूट्यूब खोजें';

  @override
  String get seconds => 'सेकंड';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'सीक अवधि';

  @override
  String get seekDurationInfo => 'आप पिछड़ी ओर जाने के लिए वर्तमान अवधि पर टैप कर सकते हैं और आगे बढ़ने के लिए कुल अवधि पर टैप कर सकते हैं';

  @override
  String get seekbar => 'बढ़ेगा';

  @override
  String get selectAll => 'सबका चयन करें';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Select files already in local library';

  @override
  String get selectedTracks => 'चयनित ट्रैक';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'ये शब्द विभाजित नहीं होंगे';

  @override
  String get separatorsMessage =>
      'रिक्त स्थान जोड़ने की आवश्यकता नहीं है, जब तक कि आप उस अक्षर/प्रतीक का उपयोग नहीं करना चाहते हैं जो पूरे शब्द में पाया जा सकता है (जैसे x और ft।)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Set as';

  @override
  String get setAsDefault => 'डिफ़ॉल्ट के रूप में सेट करें';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'वीडियो अपलोड दिनांक के रूप में फ़ाइल को अंतिम रूप से संशोधित करें';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'मूड सेट करें';

  @override
  String get setMoodsSubtitle => 'उन्हें अलग करने के लिए अल्पविराम (,) का उपयोग करें';

  @override
  String get setRating => 'रेटिंग सेट करें';

  @override
  String get setTags => 'Tags सेट करें';

  @override
  String get setYoutubeLink => 'YouTube लिंक सेट करें';

  @override
  String get settings => 'सेटिंग्स';

  @override
  String get setupFirstStartup => 'पहला स्टार्टअप सेट करें';

  @override
  String get share => 'साझा करें';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Shortcuts';

  @override
  String get shouldDuck => 'दुबक जाना चाहिए';

  @override
  String get shouldDuckNote => 'इंगित करता है कि वॉल्यूम कम किया जाना चाहिए। उदाहरण: अधिसूचना';

  @override
  String get shouldPause => 'रुक जाना चाहिए';

  @override
  String get shouldPauseNote => 'इंगित करता है कि playback रोका जाना चाहिए। उदाहरण: कॉल';

  @override
  String get showAll => 'Show All';

  @override
  String get showChannelWatermarkInFullscreen => 'चैनल वॉटरमार्क को पूर्ण स्क्रीन में दिखाएं';

  @override
  String get showFailedOnly => 'Show Failed only';

  @override
  String get showHideUnknownFields => 'अज्ञात फ़ील्ड दिखाएँ/छिपाएँ';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Mixes दिखाए';

  @override
  String get showMore => 'और दिखाएं';

  @override
  String get showShortVideosIn => 'Shorts दिखाए';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'वीडियो एंडकार्ड दिखाएं';

  @override
  String get showWebm => 'वेबम दिखाएं';

  @override
  String get shuffle => 'फेरबदल';

  @override
  String get shuffleAll => 'सबको मिलाएं';

  @override
  String get shuffleNext => 'अगला मिलाएं';

  @override
  String get signIn => 'साइन इन';

  @override
  String get signInCanceled => 'Sign को रद किया गया';

  @override
  String get signInFailed => 'Sign in असफल हुई';

  @override
  String get signInToYourAccount => 'अपनी अकाउंट पे sign in करें';

  @override
  String get signInYouDontHaveAccount => 'आपका कोई भी अकाउंट signed in नही है';

  @override
  String get signInYouNeedAccountToViewPage => 'आपको ये पेज देखने के लिए एक अकाउंट चाहिए';

  @override
  String get signOut => 'साइन आउट';

  @override
  String signOutFromName({required String name}) {
    return '$name से sign out करें';
  }

  @override
  String get signingInAllowsBasicUsage => 'Sign in साधारण इस्तमाल को करने देता है';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'जल्दी access पाएं सयाहतों या कूपन इस्तमाल करके';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Similar Time Range';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generate tracks you listened to around the same time as $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'आकार';

  @override
  String get skip => 'छोड़ें';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'चुप्पी छोड़ें';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'बाद में सोएं';

  @override
  String get sleepTimer => 'स्लीप टाइमर';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'दर्शाना';

  @override
  String get source => 'स्रोत';

  @override
  String get speed => 'गति';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'स्टैगरड एल्बम ग्रिडव्यू';

  @override
  String get start => 'शुरू';

  @override
  String get stats => 'आँकड़े';

  @override
  String get statsSubtitle => 'आपकी लाइब्रेरी के बारे में कुछ जानकारी';

  @override
  String get stop => 'रोकें';

  @override
  String get stopAfterThisTrack => 'इस ट्रैक के बाद रुकें';

  @override
  String get stopAfterThisVideo => 'इस वीडियो के बाद रुकें';

  @override
  String get storagePermissionDenied => 'अनुमति अस्वीकार कर दी गई';

  @override
  String get storagePermissionDeniedSubtitle => 'कृपया इस क्रिया को करने में सक्षम होने के लिए अनुमति दें';

  @override
  String get stretchLyricsDuration => 'Stretch Lyrics Duration';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Subscribe';

  @override
  String get subscribed => 'Subscribe';

  @override
  String get subscriber => 'Subscriber';

  @override
  String get subscribers => 'Subscribers';

  @override
  String get succeeded => 'सफल';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'समर्थन';

  @override
  String get supremacy => 'सर्वोच्चता';

  @override
  String get sussyBaka => 'अबे यार कोई track ही नहीं है';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'दराज खोलने के लिए स्वाइप करें';

  @override
  String get synced => 'सिंक्रनाइज़';

  @override
  String get synopsis => 'सारांश';

  @override
  String get tagFields => 'टैग फ़ील्ड';

  @override
  String get tags => 'टैग';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Tap to seek';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'थीम मोड';

  @override
  String get themeModeDark => 'Dark';

  @override
  String get themeModeLight => 'Light';

  @override
  String get themeModeSystem => 'System';

  @override
  String get themeSettings => 'Theme';

  @override
  String get themeSettingsSubtitle => 'आपके player का समग्र वातावरण';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'This playlist has active sorters, please disable them before reordering.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'This video is likely deleted or set to private.';

  @override
  String get thumbnails => 'थंबनेल';

  @override
  String get title => 'शीर्षक';

  @override
  String get top => 'शीर्ष';

  @override
  String get topComments => 'शीर्ष comments';

  @override
  String get topCommentsSubtitle => 'comments को नीचे की जगह शीर्ष में दिखाई';

  @override
  String get topRecentAlbums => 'हाल ही में शीर्ष एल्बम';

  @override
  String get topRecentArtists => 'हाल ही में शीर्ष कलाकार';

  @override
  String get topRecents => 'हाल ही में शीर्ष गाने';

  @override
  String get totalListenTime => 'कुल सुनने का समय';

  @override
  String get totalListens => 'कुल सुनते है';

  @override
  String get totalTracks => 'कुल ट्रैक';

  @override
  String get totalTracksDuration => 'कुल ट्रैक अवधि';

  @override
  String get track => 'ट्रैक';

  @override
  String get trackArtistsSeparator => 'कलाकार विभाजक';

  @override
  String get trackGenresSeparator => 'शैली विभाजक';

  @override
  String get trackInfo => 'ट्रैक जानकारी';

  @override
  String get trackNotFound => 'ट्रैक नहीं मिला';

  @override
  String get trackNumber => 'ट्रैक नंबर';

  @override
  String get trackNumberTotal => 'ट्रैक कुल';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'पुराना नाम: \"$oldName\"\n\nनया नाम: \"$newName\"\n\nक्या आप सुनिश्चित हैं?';
  }

  @override
  String get trackPlayMode => 'प्ले मोड';

  @override
  String get trackPlayModeSearchResults => 'खोज परिणाम';

  @override
  String get trackPlayModeSelectedOnly => 'केवल चयनित ट्रैक';

  @override
  String get trackPlayModeTrackAlbum => 'ट्रैक का एल्बम';

  @override
  String get trackPlayModeTrackArtist => 'ट्रैक का मुख्य कलाकार';

  @override
  String get trackPlayModeTrackGenre => 'ट्रैक की शैली';

  @override
  String get trackThumbnailSizeInList => 'ट्रैक थंबनेल का आकार';

  @override
  String get trackTileCustomization => 'ट्रैक टाइल अनुकूलन';

  @override
  String get trackTileItemsSeparator => 'आइटम विभाजक';

  @override
  String get tracks => 'ट्रैक';

  @override
  String get tracksExcludedByNomedia => '.nomedia द्वारा बहिष्कृत ट्रैक';

  @override
  String get tracksInfo => 'ट्रैक जानकारी';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'पूर्ववत करें';

  @override
  String get undoChanges => 'बदलाव पूर्ववत करें?';

  @override
  String get undoChangesDeletedPlaylist => 'हटाई गई प्लेसूची पूर्ववत करें';

  @override
  String get undoChangesDeletedQueue => 'हटाए गए क्यू को पूर्ववत करें';

  @override
  String get undoChangesDeletedTrack => 'हटाए गए ट्रैक को पूर्ववत करें';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'असीमित';

  @override
  String get unlisted => 'असूचीबद्ध';

  @override
  String get unlock => 'अनलॉक करें';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'अपडेट करें';

  @override
  String get updateDirectoryPath => 'डायरेक्टरी पथ अपडेट करें';

  @override
  String get updateMissingTracksOnly => 'केवल गायब ट्रैक अपडेट करें';

  @override
  String get updating => 'अपडेट हो रहा है';

  @override
  String get useCollapsedSettingTiles => 'Collapsed सेटिंग टाइल्स का उपयोग करें';

  @override
  String get useMediaStore => 'मीडिया स्टोर का उपयोग करें';

  @override
  String get useMediaStoreSubtitle =>
      '✓ त्वरित अनुक्रमण समय\nx सम्मान .nomedia जबरन सक्षम किया जाएगा\nx कुछ मेटाडेटा टैग गायब होंगे\nx स्थानीय लाइब्रेरी के लिए youtube एकीकरण काम नहीं करेगा';

  @override
  String get usePitchBlack => 'पिच ब्लैक का उपयोग करें';

  @override
  String get usePitchBlackSubtitle => 'AMOLED स्क्रीन के लिए उपयोगी.. और कूलर दिखता है';

  @override
  String get used => 'प्रयुक्त';

  @override
  String get value => 'मूल्य';

  @override
  String get valueBetween50200 => 'मान 50% और 200% के बीच होना चाहिए';

  @override
  String get vibration => 'Vibration';

  @override
  String get vibrationType => 'Vibration type';

  @override
  String get video => 'वीडियो';

  @override
  String get videoCache => 'वीडियो कैश';

  @override
  String get videoCacheFile => 'सहेजे गए वीडियो फ़ाइल';

  @override
  String get videoCacheFiles => 'सहेजी गई वीडियो फ़ाइलें';

  @override
  String get videoOnly => 'केवल वीडियो';

  @override
  String get videoPlaybackSource => 'वीडियो स्रोत';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'यह प्राथमिकता स्थानीय वीडियो देगा, यदि नहीं मिला तो यह YouTube से लाएगा';

  @override
  String get videoPlaybackSourceLocal => 'स्थानीय वीडियो';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nवीडियो Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle =>
      'जांचता है कि क्या कोई वीडियो फ़ाइल (चुने गए फ़ोल्डर सूची के अंदर पाई गई है) में एक फ़ाइल नाम है जिसमें ट्रैक का फ़ाइल नाम शामिल है';

  @override
  String get videoPlaybackSourceYoutube => 'YouTube से';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Track के फ़ाइल नाम और comment में किसी भी मिलान करने वाले YouTube link की जांच करता है, वीडियो को बाद में उपयोग के लिए cache किया जाता है।';

  @override
  String get videoQuality => 'वीडियो गुणवत्ता';

  @override
  String get videoQualitySubtitle => 'उच्चतम गुणवत्ता उपलब्ध होगी।';

  @override
  String get videoQualitySubtitleNote => 'यह हमेशा गुणवत्ता न मिलने की स्थिति में अधिक विकल्प रखना अच्छा होता है, अन्यथा यह सबसे खराब गुणवत्ता पर वापस आ जाएगा';

  @override
  String get videos => 'वीडियो';

  @override
  String get view => 'दृश्य';

  @override
  String get viewAll => 'सभी देखें';

  @override
  String get views => 'देखें';

  @override
  String get volume => 'आवाज़';

  @override
  String get warning => 'चेतावनी';

  @override
  String get waveformBarsCount => 'लहर बार्स गिनती';

  @override
  String get webmNoEditTagsSupport => 'WEBM प्रारूप टैग संपादन का समर्थन नहीं करता है';

  @override
  String get week => 'सप्ताह';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'साल';

  @override
  String get yes => 'हाँ';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'आपकी वर्तमान membership है $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Your custom order will be lost, Are you sure?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube music';

  @override
  String get youtubeSettingsSubtitle => 'YouTube अनुभव अनुकूलित करें';

  @override
  String get youtubeStyleMiniplayer => 'Youtube-style Miniplayer';

  @override
  String get ytPreferNewComments => 'जब संभव हो, नई comments को प्राथमिकता दें';

  @override
  String get ytPreferNewCommentsSubtitle => 'Cache किए गए संस्करण का उपयोग केवल तभी किया जाएगा जब कोई कनेक्शन नहीं होगा';
}
