// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get about => 'About';

  @override
  String get active => 'Active';

  @override
  String get add => 'Add';

  @override
  String get addAccount => 'Add account';

  @override
  String get addAll => 'Add all';

  @override
  String get addAllAndRemoveOldOnes => 'Add all and remove old ones';

  @override
  String get addAsANewPlaylist => 'Add as a new Playlist';

  @override
  String get addAudioToLocalLibrary => 'Add audio to local library';

  @override
  String get addFolder => 'Add Folder';

  @override
  String get addLanguage => 'Add Language';

  @override
  String get addLanguageSubtitle => 'Help translating Namida to your own language';

  @override
  String get addLrcFile => 'Add LRC file';

  @override
  String get addMoreFromThisAlbum => 'Add more from this Album to queue';

  @override
  String get addMoreFromThisArtist => 'Add more from this Artist to queue';

  @override
  String get addMoreFromThisFolder => 'Add more from this Folder to queue';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Add more from $media to queue';
  }

  @override
  String get addOnlyMissing => 'Add only missing';

  @override
  String get addToFavourites => 'Add to favourites';

  @override
  String get addToPlaylist => 'Add to Playlist';

  @override
  String get addTracksAtTheBeginning => 'Add tracks at the beginning';

  @override
  String get added => 'added';

  @override
  String get advanced => 'Advanced';

  @override
  String get advancedSettings => 'Advanced';

  @override
  String get advancedSettingsSubtitle => 'Advanced Settings, don\'t touch';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Album Artist';

  @override
  String get albumArtists => 'Album Artists';

  @override
  String get albumIdentifiers => 'Album Identifiers';

  @override
  String get albumThumbnailSizeInList => 'Size of Album Thumbnail';

  @override
  String get albumTileCustomization => 'Album Tile Customization';

  @override
  String get albums => 'Albums';

  @override
  String get albumsCount => 'Albums Count';

  @override
  String get all => 'All';

  @override
  String get allTime => 'All time';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Always';

  @override
  String get alwaysAsk => 'Always ask';

  @override
  String get alwaysDim => 'Always Dim';

  @override
  String get alwaysExpandedSearchbar => 'Always Expanded Searchbar';

  @override
  String get alwaysRestore => 'Always restore';

  @override
  String get animatingThumbnailIntensity => 'Thumbnail Animation Intensity';

  @override
  String get animatingThumbnailInversed => 'Inverse Animations';

  @override
  String get animatingThumbnailInversedSubtitle => 'High peaks will cause the thumbnail to get smaller';

  @override
  String get anotherProcessIsRunning => 'Another process is already running.';

  @override
  String get appIcon => 'App Icon';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Artist';

  @override
  String get artists => 'Artists';

  @override
  String get artwork => 'Artwork';

  @override
  String get artworkGestures => 'Artwork Gestures';

  @override
  String get artworks => 'Artworks';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Audio Cache';

  @override
  String get audioOnly => 'Audio Only';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Auto backup interval';

  @override
  String get autoColoring => 'Auto Coloring';

  @override
  String get autoColoringSubtitle => 'Automatically pick player colors from current artwork';

  @override
  String get autoExtractTagsFromFilename => 'Auto extract from filename';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Auto extract Title & Artist from video title';

  @override
  String get autoGenerated => 'Auto Generated';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Auto start radio';

  @override
  String get autoStartRadioSubtitle => 'Automatically adds a mix playlist when playing a single track';

  @override
  String get automaticBackup => 'Automatic';

  @override
  String get automaticBackupSubtitle => 'Automatically applies the most recent backup file found inside backup location';

  @override
  String get backupAndRestore => 'Backup & Restore';

  @override
  String get backupAndRestoreSubtitle => 'Backup your database and settings';

  @override
  String get balanced => 'Balanced';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Between Dates';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Blacklist';

  @override
  String get borderRadiusMultiplier => 'Border Radius Multiplier';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Cancel';

  @override
  String get canceled => 'Canceled';

  @override
  String get changed => 'Changed';

  @override
  String get changelog => 'Changelog';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Channel';

  @override
  String get channels => 'Channels';

  @override
  String get check => 'Check';

  @override
  String get checkForMore => 'Check for more';

  @override
  String get checkList => 'Check List';

  @override
  String get choose => 'Choose';

  @override
  String get chooseWhatToClear => 'Choose what to clear';

  @override
  String get claim => 'Claim';

  @override
  String get clear => 'Clear';

  @override
  String get clearAudioCache => 'Clear Audio Cache';

  @override
  String get clearImageCache => 'Clear Image cache';

  @override
  String get clearImageCacheWarning => 'Warning: will result in a library without images, Use only to rebuild image cache.';

  @override
  String get clearTrackItem => 'Clear Track\'s';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Clear $numberString Tracks\'',
      one: 'Clear Track\'s',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Clear Video Cache';

  @override
  String get clearVideoCacheNote => 'You can choose what to delete.';

  @override
  String get clock => 'Clock';

  @override
  String get colorPalette => 'Color Palette';

  @override
  String get colorPaletteNote1 => 'Long press a color to remove it';

  @override
  String get colorPaletteNote2 => 'Tap on a mix to use as a default color';

  @override
  String get colorPalettes => 'Color Palettes';

  @override
  String get comment => 'Comment';

  @override
  String get comments => 'Comments';

  @override
  String get composer => 'Composer';

  @override
  String get compress => 'Compress';

  @override
  String get compressImages => 'Compress Images';

  @override
  String get compressionPercentage => 'Compression percentage';

  @override
  String get configure => 'Configure';

  @override
  String get confirm => 'Confirm';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Copied Artwork';

  @override
  String get copiedToClipboard => 'Copied to Clipboard';

  @override
  String get copy => 'Copy';

  @override
  String get corruptedFile => 'Couldn\'t parse file, it might be corrupted';

  @override
  String get couldntOpen => 'Couldn\'t open :(';

  @override
  String get couldntOpenYtLink => 'No Youtube Link Available for this track';

  @override
  String get couldntPlayFile => 'Couldn\'t play file';

  @override
  String get couldntRenamePlaylist => 'Couldn\'t rename playlist';

  @override
  String get couldntSaveImage => 'Couldn\'t save image';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Country';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Create';

  @override
  String get createBackup => 'Create Backup';

  @override
  String get createNewPlaylist => 'Create new Playlist';

  @override
  String get createdBackupSuccessfully => 'Created Backup';

  @override
  String get createdBackupSuccessfullySub => 'Backup file has been created successfully';

  @override
  String get crossPlatformSync => 'Cross-Platform Sync';

  @override
  String get crossfadeDuration => 'Crossfade duration';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Trigger Crossfade automatically in the last $secondsString seconds',
      one: 'Trigger Crossfade automatically in the last $secondsString second',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Do not trigger crossfade automatically';

  @override
  String get custom => 'Custom';

  @override
  String get customizations => 'Customizations';

  @override
  String get customizationsSubtitle => 'Customize how your player looks, make it yours';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'Database';

  @override
  String get date => 'Date';

  @override
  String get dateAdded => 'Date Added';

  @override
  String get dateCreated => 'Date Created';

  @override
  String get dateModified => 'Date Modified';

  @override
  String get dateTimeFormat => 'Date Time Format';

  @override
  String get day => 'Day';

  @override
  String get days => 'Days';

  @override
  String get defaultBackupLocation => 'Default Backup Location';

  @override
  String get defaultColor => 'Default Color';

  @override
  String get defaultColorSubtitle => 'Set a color to be used by the player';

  @override
  String get defaultDownloadLocation => 'Default Download Location';

  @override
  String get defaultLabel => 'Default';

  @override
  String get defaultLibraryTab => 'Default Library Tab';

  @override
  String get delete => 'Delete';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Delete $countString files representing $totalSizeText?',
      one: 'Delete $countString file representing $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Permanently delete $numberText from your storage';
  }

  @override
  String get deletePlaylist => 'Delete Playlist';

  @override
  String get deleteTempFiles => 'Delete temp files';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Description';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Did you mean';

  @override
  String get dimIntensity => 'Dim Intensity';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Dim miniplayer after $secondsString seconds of inactivity',
      one: 'Dim miniplayer after $secondsString second of inactivity',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Directory doesn\'t exist';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Disable All';

  @override
  String get disableReordering => 'Disable Reordering';

  @override
  String get disableSearchCleanup => 'Disable Search Cleanup';

  @override
  String get discNumber => 'Disc Number';

  @override
  String get discNumberTotal => 'Disc Total';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Dislike';

  @override
  String get dismissibleMiniplayer => 'Dismissible Miniplayer';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Album Card top right date';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Display Album date at Album Card top right';

  @override
  String get displayArtistBeforeTitle => 'Display artist before title';

  @override
  String get displayArtworkOnLockscreen => 'Display artwork on lockscreen';

  @override
  String get displayAudioInfoInMiniplayer => 'Display Audio Info';

  @override
  String get displayFavButtonInNotification => 'Display Favourite Button in Notification';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Thumbnail might get displaced.';

  @override
  String get displayFavouriteIconInTrackTile => 'Display Favourite Button';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Display remaining duration instead of total';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Display Third Item in each Row';

  @override
  String get displayThirdRowInTrackTile => 'Display Third Row';

  @override
  String get displayTrackNumberInAlbumPage => 'Display Track number in Album Page';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Display a small box containing the track number in the album page';

  @override
  String get doNothing => 'Do nothing';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Done';

  @override
  String get dontAskAgain => 'Don\'t ask again';

  @override
  String get dontDim => 'Don\'t Dim';

  @override
  String get dontRestorePosition => 'Don\'t restore';

  @override
  String get dontResume => 'Dont resume';

  @override
  String get doubleTapToToggleLyrics => 'Double tap to toggle lyrics';

  @override
  String get download => 'Download';

  @override
  String get downloadingWillOverrideIt => 'Downloading will override it';

  @override
  String get downloads => 'Downloads';

  @override
  String get downloadsMetadataTags => 'Downloads Metadata tags';

  @override
  String get downloadsMetadataTagsSubtitle => 'Extract artist, title & album from video info by default';

  @override
  String get dragToSeek => 'Drag to seek';

  @override
  String get duckAudio => 'Duck audio';

  @override
  String get duplicatedItemsAdding => 'You are trying to add some items that already exist in this playlist';

  @override
  String get duplicatedTracks => 'Duplicated Tracks';

  @override
  String get duration => 'Duration';

  @override
  String get edgeColorsSwitching => 'Edge Colors Switching';

  @override
  String get edit => 'Edit';

  @override
  String get editArtwork => 'Edit Artwork';

  @override
  String get editTags => 'Edit Tags';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'you have fields with empty/non-meaningful values, make sure you really want to edit them';

  @override
  String get emptyValue => 'Empty Value';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Enable Blur Effect';

  @override
  String get enableBottomNavBar => 'Enable Bottom Navigation Bar';

  @override
  String get enableBottomNavBarSubtitle => 'Items are inside the drawer bothways';

  @override
  String get enableClipboardMonitoring => 'Enable Clipboard Monitoring';

  @override
  String get enableClipboardMonitoringSubtitle => 'Allows pasting links and texts inside searchbar on the go';

  @override
  String get enableCrossfadeEffect => 'Enable Crossfade Effect';

  @override
  String get enableFadeEffectOnPlayPause => 'Enable Fade Effect on Play/Pause';

  @override
  String get enableFoldersHierarchy => 'Enable Folders Hierarchy';

  @override
  String get enableGlowEffect => 'Enable Glow Effect';

  @override
  String get enableM3uSync => 'Enable M3U Sync';

  @override
  String get enableM3uSyncNote1 => 'M3U Sync allows saving playlist changes to the original M3U file';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'If anything went wrong, a backup of this playlist will be found in $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'If Denied, all changes done in this playlist will be lost on restart';

  @override
  String get enableMiniplayerParticles => 'Enable moving particles';

  @override
  String get enableParallaxEffect => 'Enable Parallax Effect';

  @override
  String get enablePartyMode => 'Enable Party Mode';

  @override
  String get enablePartyModeSubtitle => 'Apply fancy edge breathing effect';

  @override
  String get enablePictureInPicture => 'Enable Picture-in-Picture';

  @override
  String get enableReordering => 'Enable Reordering';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Enable Search Cleanup';

  @override
  String get enableSearchCleanupSubtitle => 'All Symbols and Spaces will be ignored';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'Enable Video Playback';

  @override
  String get enterSymbol => 'Please Enter a Symbol';

  @override
  String get equalizer => 'Equalizer';

  @override
  String get error => 'Error';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Error playing track';

  @override
  String get excludedFodlers => 'Excluded Folders';

  @override
  String get exit => 'Exit';

  @override
  String get exitAppSubtitle => 'Tap again to exit';

  @override
  String get expandedMiniplayer => 'Expanded Miniplayer';

  @override
  String get exportAsM3u => 'Export as M3U';

  @override
  String get extension => 'Extension';

  @override
  String get externalFiles => 'External Files';

  @override
  String get extract => 'Extract';

  @override
  String get extractAllColorPalettes => 'Extract All Color Palettes';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Extract Remaining $numberString?',
      one: 'Extract Remaining $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Extract feat. artists from title';

  @override
  String get extractFeatArtistSubtitle => 'Extracts (feat. X) and (ft. X) artists, as a new artist entry.';

  @override
  String get extractingInfo => 'Extracting Info';

  @override
  String get extras => 'Extras';

  @override
  String get extrasSubtitle => 'Extra Settings to fine your experience';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Failed';

  @override
  String get failedEdits => 'Failed Edits';

  @override
  String get favourites => 'Favourites';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Fetching';

  @override
  String get fetchingOfAllVideos => 'Fetching of all videos';

  @override
  String get file => 'File';

  @override
  String get fileAlreadyExists => 'File already exists';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'File Name';

  @override
  String get fileNameWoExt => 'Filename without extension';

  @override
  String get filenameShouldntStartWith => 'Filename shouldn\'t start with';

  @override
  String get files => 'Files';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Filter Albums';

  @override
  String get filterArtists => 'Filter Artists';

  @override
  String get filterGenres => 'Filter Genres';

  @override
  String get filterPlaylists => 'Filter Playlists';

  @override
  String get filterTracks => 'Filter Tracks';

  @override
  String get filterTracksBy => 'Filter Tracks in Search Lists By';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Tracks Filtered by size and duration';

  @override
  String get finished => 'Finished';

  @override
  String get finishedUpdatingLibrary => 'Finished Updating Library';

  @override
  String get firstListen => 'First listen';

  @override
  String get fixYtdlpBigThumbnailSize => 'Fix yt-dlp big thumbnail size';

  @override
  String get floatingActionButton => 'Floating Action Button';

  @override
  String get folder => 'Folder';

  @override
  String get folderName => 'Folder Name';

  @override
  String get folders => 'Folders';

  @override
  String get fontScale => 'Font Scale';

  @override
  String get forceMiniplayerFollowTrackColors => 'Force miniplayer to follow track colors';

  @override
  String get forceSquaredAlbumThumbnail => 'Force Squared Album Thumbnail';

  @override
  String get forceSquaredThumbnailNote => 'Thumbnail Size & Tile Height are NOT equal, Square-ish look will not be as expected, Do you wish to make them equal?';

  @override
  String get forceSquaredTrackThumbnail => 'Force Squared Track Thumbnail';

  @override
  String get forceStopColorPaletteGeneration => 'Force stop extracting color palettes? you can still continue it later';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Fullscreen';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Generate';

  @override
  String get generateFromDates => 'Time Range';

  @override
  String get generateFromDatesSubtitle => 'Generate tracks you listened to in a time range';

  @override
  String get generateRandomPlaylist => 'Generate random Playlist';

  @override
  String get genre => 'Genre';

  @override
  String get genres => 'Genres';

  @override
  String get goToAlbum => 'Go to Album';

  @override
  String get goToArtist => 'Go to Artist';

  @override
  String get goToChannel => 'Go to channel';

  @override
  String get goToFolder => 'Go to Folder';

  @override
  String get goodLooking => 'Good looking';

  @override
  String get grantStoragePermission => 'Grant Storage Permission';

  @override
  String get group => 'Group';

  @override
  String get groupArtworksByAlbum => 'Group Artworks by Album';

  @override
  String get guide => 'Guide';

  @override
  String get hapticFeedback => 'Haptic Feedback';

  @override
  String get heightOfAlbumTile => 'Height of Album Tile';

  @override
  String get heightOfTrackTile => 'Height of Track Tile';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'High matches';

  @override
  String get highPerformance => 'High performance';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'History';

  @override
  String get historyImportMissingEntriesNote => 'These entries couldn\'t be found inside library, if you believe they exist, please consider adding them manually';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString listens for $oldTrackInfo will be replaced with $newTrackInfo, confirm?',
      one: '$listensCountString listen for $oldTrackInfo will be replaced with $newTrackInfo, confirm?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Home';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12 Hour Format';

  @override
  String get hours => 'Hours';

  @override
  String get iReadAndAgree => 'I read & agree';

  @override
  String get ifNotPlaying => 'If not playing';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Downloads can be throttled when the app is battery restricted';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignore common prefixes while sorting';

  @override
  String get ignores => 'Ignores';

  @override
  String get imageSource => 'Image source';

  @override
  String get immersiveMode => 'Immersive Mode';

  @override
  String get immersiveModeSubtitle => 'Hide Status & Navigation bars while Miniplayer is expanded';

  @override
  String get import => 'Import';

  @override
  String get importAll => 'Import all';

  @override
  String get importLastFmHistory => 'Import LastFm History';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Go to $lastfmCsvLink\n\n2. Type your username, fetch and download csv file.\n\n3. Choose the file from the next screen.';
  }

  @override
  String get importTimeRange => 'Import time range';

  @override
  String get importYoutubeHistory => 'Import Youtube History';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Go to $takeoutLink\n\n2. Press \"Multiple Formats\" and beside \"History\" choose \"JSON\".\n\n3. Press \"All Youtube data included\", Deselect All and choose history only.\n\n4. Create Export, Download & Unzip.\n\n5. Choose \"watch-history.json\" from the next screen.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Imported $numberString channels successfully',
      one: 'Imported $numberString channel successfully',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Imported $numberText playlists successfully',
      one: 'Imported $numberText playlist successfully',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Include videos';

  @override
  String get indexRefreshRequired => 'Do a Refresh after changing this';

  @override
  String get indexer => 'Indexer';

  @override
  String get indexerNote => 'Note: Incomplete Number of Artworks refers to the duplicated & not found Artworks';

  @override
  String get indexerSubtitle => 'Manage your music Library';

  @override
  String get infinityQueueOnNextPrev => 'Infinity Queue on Next/Previous';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'pressing next while playing the last item will jump to first, and vice versa';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'inserted';

  @override
  String get instantlyApplies => 'Instantly Applies';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Invert Selection';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Item';

  @override
  String get jump => 'Jump';

  @override
  String get jumpToDay => 'Jump to Day';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Jump to first track after finishing queue';

  @override
  String get keepCachedVersions => 'Keep cached versions';

  @override
  String get keepFileDates => 'Keep file dates';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniplayer is Expanded';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniplayer is Expanded and a Video is Playing';

  @override
  String get keepScreenAwakeNone => 'Don\'t keep screen awake';

  @override
  String get keepScreenAwakeWhen => 'Keep screen awake when';

  @override
  String get killPlayerAfterDismissingApp => 'Kill player after dismissing app';

  @override
  String get language => 'Language';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Library Tabs';

  @override
  String get libraryTabsReorder => 'You can reorder the activated tabs.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Like';

  @override
  String get liked => 'Liked';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'List of Folders';

  @override
  String get loadAll => 'Load all';

  @override
  String get loadingFile => 'Loading File';

  @override
  String get local => 'Local';

  @override
  String get localVideoMatching => 'Local Video Matching';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Long press the lyrics to enter fullscreen';

  @override
  String get lostMemories => 'Lost Memories';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'around this time, $numberString years ago',
      one: 'around this time, $numberString year ago',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Loudness Enhancer';

  @override
  String get lyricist => 'Lyricist';

  @override
  String get lyrics => 'Lyrics';

  @override
  String get lyricsSource => 'Lyrics source';

  @override
  String get m3uPlaylist => 'M3U Playlist';

  @override
  String get makeYourFirstListen => 'Make your first listen!';

  @override
  String get manage => 'Manage';

  @override
  String get manageYourAccounts => 'Manage your accounts';

  @override
  String get manualBackup => 'Manual';

  @override
  String get manualBackupSubtitle => 'pick up a specific file';

  @override
  String get markAsRead => 'Mark as read';

  @override
  String get matchAllTracks => 'Match All Tracks';

  @override
  String get matchAllTracksNote => 'this can have an impact on the matching speed, as it will check all tracks in your library';

  @override
  String get matchingType => 'Matching type';

  @override
  String get maxAudioCacheSize => 'Max audio cache size';

  @override
  String get maxImageCacheSize => 'Max image cache size';

  @override
  String get maxVideoCacheSize => 'Max video cache size';

  @override
  String get maximum => 'Maximum';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store is enabled, this will have no effect';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Code';

  @override
  String get membershipCodeSentToEmail => 'Code sent to your email';

  @override
  String get membershipDidntChange => 'Membership didn\'t change';

  @override
  String get membershipEnjoyNew => 'Enjoy your new membership';

  @override
  String get membershipFreeCoupon => 'Free Coupon';

  @override
  String get membershipManage => 'Manage your membership';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'No subscriptions found for this user';

  @override
  String get membershipSignInToPatreonAccount => 'Sign in to your patreon account';

  @override
  String get membershipUnknown => 'Unknown Membership';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'You need membership of $name1 or $name2 to add multiple accounts';
  }

  @override
  String get merge => 'Merge';

  @override
  String get metadataCache => 'Metadata Cache';

  @override
  String get metadataEditFailed => 'Failed to edit metadata';

  @override
  String get metadataReadFailed => 'Failed to read metadata';

  @override
  String get minFileDuration => 'Minimum Track Duration';

  @override
  String get minFileSize => 'Minimum File Size';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimum track duration to restore last played position';

  @override
  String get minValueCantBeMoreThanMax => 'Minimum value can\'t be more than the maximum';

  @override
  String get minValueToCountTrackListen => 'Count a listen after: ';

  @override
  String get minimizedMiniplayer => 'Minimized Miniplayer';

  @override
  String get minimum => 'Minimum';

  @override
  String get minimumOneFolderSubtitle => 'There should be at least 1 folder, add more folders if you want to remove this one';

  @override
  String get minimumOneItem => 'Couldn\'t remove item';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'At least $numberString items should remain',
      one: 'At least $numberString item should remain',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Miniplayer Customization';

  @override
  String get minutes => 'minutes';

  @override
  String get missingEntries => 'Missing Entries';

  @override
  String get missingTracks => 'Missing Tracks';

  @override
  String get mix => 'Mix';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Mix playlist generated by youtube';

  @override
  String get mixes => 'Mixes';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Month';

  @override
  String get months => 'Months';

  @override
  String get mood => 'Mood';

  @override
  String get moods => 'Moods';

  @override
  String get more => 'More';

  @override
  String get mostPlayed => 'Most Played';

  @override
  String get multipleTracksTagsEditNote => 'You are about to edit these tracks,\nUnchanged fields remain untouched.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Name';

  @override
  String get nameContainsBadCharacter => 'Name contains bad character';

  @override
  String get never => 'Never';

  @override
  String get newDirectory => 'New directory';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Add Tracks';

  @override
  String get newTracksMoods => 'Mood';

  @override
  String get newTracksMoodsSubtitle => 'Generate tracks based on available moods';

  @override
  String get newTracksRandom => 'Random';

  @override
  String get newTracksRandomSubtitle => 'Pick up random tracks from your library';

  @override
  String get newTracksRatings => 'Ratings';

  @override
  String get newTracksRatingsSubtitle => 'Generate tracks that has specific rating';

  @override
  String get newTracksRecommended => 'Recommended';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Generate tracks you usually listened to with $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Similar Release Date';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were released around the same time as $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Track has unknown year';

  @override
  String get newest => 'Newest';

  @override
  String get next => 'Next';

  @override
  String get no => 'no';

  @override
  String get noChangesFound => 'No changes has been found.';

  @override
  String get noEnoughTracks => 'You don\'t have much tracks..';

  @override
  String get noExcludedFolders => 'You Don\'t have any excluded folders';

  @override
  String get noFolderChosen => 'You haven\'t chosen any folder';

  @override
  String get noMoodsAvailable => 'No moods available';

  @override
  String get noNetworkAvailableToFetchData => 'No network available to fetch data';

  @override
  String get noTracksFound => 'No tracks were found';

  @override
  String get noTracksFoundBetweenDates => 'This time range doesn\'t have any tracks.';

  @override
  String get noTracksFoundInDirectory => 'No tracks found in this directory';

  @override
  String get noTracksInHistory => 'You don\'t have enough tracks in history';

  @override
  String get nonActive => 'Non-Active';

  @override
  String get nonFavourites => 'Non-Favourites';

  @override
  String get none => 'None';

  @override
  String get normalizeAudio => 'Normalize audio';

  @override
  String get normalizeAudioSubtitle => 'Normalizes volume by reading the replay gain tag or the info provided by youtube';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Note';

  @override
  String get notification => 'Notification';

  @override
  String get notifications => 'Notifications';

  @override
  String get numberOfTracks => 'Number of Tracks';

  @override
  String get ofLabel => 'of';

  @override
  String get offlineSearch => 'Offline Search';

  @override
  String get offset => 'Offset';

  @override
  String get oldDirectory => 'Old directory';

  @override
  String get oldDirectoryStillHasTracks => 'Old Directory still have some tracks, confirm?';

  @override
  String get oldestWatch => 'Oldest Watch';

  @override
  String get onInterruption => 'On Interruption';

  @override
  String get onNotificationTap => 'On Notification Tap';

  @override
  String get onOpeningYoutubeLink => 'On opening youtube link';

  @override
  String get onSwiping => 'On Swiping';

  @override
  String get onVolumeZero => 'On volume 0';

  @override
  String get ongoing => 'Ongoing';

  @override
  String get open => 'Open';

  @override
  String get openApp => 'Open App';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Open in Youtube view';

  @override
  String get openMiniplayer => 'Open Miniplayer';

  @override
  String get openQueue => 'Open Queue';

  @override
  String get openYoutubeLink => 'Open Youtube Link';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operation $name requires account, Sign in to proceed';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operation $operation requires at least membership $name';
  }

  @override
  String get or => 'or';

  @override
  String get others => 'Others';

  @override
  String get output => 'Output';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Override old files in the same folder';

  @override
  String get palette => 'Palette';

  @override
  String get paletteMix => 'Mix';

  @override
  String get paletteNewMix => 'New Mix';

  @override
  String get paletteSelectedMix => 'Selected Mix';

  @override
  String get parallelDownloads => 'Parallel Downloads';

  @override
  String get parsed => 'parsed';

  @override
  String get password => 'Password';

  @override
  String get path => 'File Full Path';

  @override
  String get pause => 'Pause';

  @override
  String get pauseFadeDuration => 'Pause Fade Duration';

  @override
  String get pausePlayback => 'Pause playback';

  @override
  String get percentage => 'Percentage';

  @override
  String get performanceMode => 'Performance mode';

  @override
  String get performanceNote => 'Might affect performance';

  @override
  String get personalized => 'Personalized';

  @override
  String get personalizedRelatedVideos => 'Personalized Related Videos';

  @override
  String get personalizedRelatedVideosSubtitle => 'Disabling this will increase data usage';

  @override
  String get pickColorsFromDeviceWallpaper => 'Pick Colors from Device Wallpaper';

  @override
  String get pickFromStorage => 'Pick from storage';

  @override
  String get pinned => 'Pinned';

  @override
  String get pitch => 'Pitch';

  @override
  String get plain => 'Plain';

  @override
  String get play => 'Play';

  @override
  String get playAfter => 'Play After';

  @override
  String get playAfterNextPrev => 'Auto Play on Next/Previous';

  @override
  String get playAll => 'Play All';

  @override
  String get playFadeDuration => 'Play Fade Duration';

  @override
  String get playLast => 'Play Last';

  @override
  String get playNext => 'Play Next';

  @override
  String get playbackSetting => 'Playback';

  @override
  String get playbackSettingSubtitle => 'Can be accessed directly in the player by long pressing the audio button';

  @override
  String get playlist => 'Playlist';

  @override
  String get playlists => 'Playlists';

  @override
  String get playlistsImportM3uNative => 'This will import M3U playlists to be used only by namida, use if you are migrating';

  @override
  String get playlistsImportM3uSynced =>
      'This will automatically import M3U playlists from indexer folders and keep them synced with the original M3U file. enable if you access/modify the playlists from other apps';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Auto import M3U Playlists';

  @override
  String get pleaseEnterADifferentName => 'This name already exists :(\nplease try another fancy name';

  @override
  String get pleaseEnterALink => 'Please enter a link';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. is this a youtube link?';

  @override
  String get pleaseEnterAName => 'Please enter a name';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Prevent Duplicated tracks';

  @override
  String get preventDuplicatedTracksSubtitle => 'Uses filename to uniqely identify tracks';

  @override
  String get preview => 'Preview';

  @override
  String get previous => 'Previous';

  @override
  String get previousButtonReplays => 'Previous button replays';

  @override
  String get previousButtonReplaysSubtitle => 'if pressed while current position was more than seek duration';

  @override
  String get prioritizeEmbeddedLyrics => 'Prioritize embedded lyrics';

  @override
  String get priority => 'Priority';

  @override
  String get private => 'Private';

  @override
  String get progress => 'Progress';

  @override
  String get promptToChangeTrackPath => 'Usually this happens when you delete/move/rename the file outside namida, Would you like to update current path?';

  @override
  String get public => 'Public';

  @override
  String get queue => 'Queue';

  @override
  String get queues => 'Queues';

  @override
  String get random => 'Random';

  @override
  String get randomPicks => 'Random Picks';

  @override
  String get rating => 'Rating';

  @override
  String get reIndex => 'Re-index';

  @override
  String get reIndexSubtitle => 'Rebuild your music library from scratch';

  @override
  String get reIndexWarning => 'This process might take a while, depending on your library size.\n\nArtworks will not get re-indexed as long as they still exist';

  @override
  String get recentAlbums => 'Recent Albums';

  @override
  String get recentArtists => 'Recent Artists';

  @override
  String get recentListens => 'Recent Listens';

  @override
  String get recentlyAdded => 'Recently Added';

  @override
  String get recordLabel => 'Record Label';

  @override
  String get refresh => 'Refresh';

  @override
  String get refreshLibrary => 'Refresh Library';

  @override
  String get refreshLibrarySubtitle => 'Check for newly added or deleted music';

  @override
  String get refreshOnStartup => 'Refresh on startup';

  @override
  String get relatedVideos => 'Related videos';

  @override
  String get rememberAudioOnlyMode => 'Remember audio only mode';

  @override
  String get remixer => 'Remixer';

  @override
  String get remove => 'Remove';

  @override
  String get removeDuplicates => 'Remove Duplicates';

  @override
  String get removeFromFavourites => 'Remove from favourites';

  @override
  String get removeFromLibrary => 'Remove from library';

  @override
  String get removeFromPlaylist => 'Remove From Playlist';

  @override
  String get removeQueue => 'Remove Queue';

  @override
  String get removeSourceFromHistory => 'Remove source from history';

  @override
  String get removeWhitespaces => 'Remove Whitespaces';

  @override
  String get removed => 'Removed';

  @override
  String get rename => 'Rename';

  @override
  String get renamePlaylist => 'Rename Playlist';

  @override
  String get reorderable => 'Reorderable';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Repeat for $number more times',
      one: 'Repeat for $number more time',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Repeat mode';

  @override
  String get repeatModeAll => 'Repeat All Queue';

  @override
  String get repeatModeNone => 'Stop on Last Track';

  @override
  String get repeatModeOne => 'Repeat Current Track';

  @override
  String get replaceAllListensWithAnotherTrack => 'Replace all listens with another track';

  @override
  String get replies => 'Replies';

  @override
  String get reply => 'Reply';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Requires clearing image cache and re indexing';

  @override
  String get rescanVideos => 'Re-scan videos';

  @override
  String get resetBrightness => 'Reset brightness';

  @override
  String get resetToDefault => 'Set to';

  @override
  String get respectNoMedia => 'Respect .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Don\'t include folders that has .nomedia';

  @override
  String get restart => 'Restart';

  @override
  String get restoreBackup => 'Restore Backup';

  @override
  String get restoreDefaults => 'Restore Defaults';

  @override
  String get restoredBackupSuccessfully => 'Restored Backup';

  @override
  String get restoredBackupSuccessfullySub => 'Backup file has been restored successfully';

  @override
  String get resume => 'Resume';

  @override
  String get resumeIfWasInterrupted => 'Resume if was paused by interruption';

  @override
  String get resumeIfWasPausedByVolume => 'Resume if was paused by volume';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Resume if was paused for less than $numberString minutes',
      one: 'Resume if was paused for less than $numberString minute',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Reverse Order';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Ringtone';

  @override
  String get sameDirectoryOnly => 'Same directory only';

  @override
  String get sample => 'Sample';

  @override
  String get sampleRate => 'Sample Rate';

  @override
  String get save => 'Save';

  @override
  String get saveToLibrary => 'Save to library';

  @override
  String get savedIn => 'Saved in';

  @override
  String get scaleMultiplier => 'Scale Multiplier';

  @override
  String get search => 'Search';

  @override
  String get searchYoutube => 'Search YouTube';

  @override
  String get seconds => 'seconds';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Seek Duration';

  @override
  String get seekDurationInfo => 'You can tap on current duration to seek backwards & total duration to seek forwards';

  @override
  String get seekbar => 'Seekbar';

  @override
  String get selectAll => 'Select All';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Select files already in local library';

  @override
  String get selectedTracks => 'Selected Tracks';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'These words will not get split';

  @override
  String get separatorsMessage => 'No need to insert spaces, unless you wanna use a letter/symbol that can be found in a whole word (like x and ft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Set as';

  @override
  String get setAsDefault => 'Set as Default';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Set file last modified as video upload date';

  @override
  String get setMoods => 'Set moods';

  @override
  String get setMoodsSubtitle => 'Use commas (,) to separate between them';

  @override
  String get setRating => 'Set Rating';

  @override
  String get setTags => 'Set tags';

  @override
  String get setYoutubeLink => 'Set Youtube Link';

  @override
  String get settings => 'Settings';

  @override
  String get setupFirstStartup => 'Setup first startup';

  @override
  String get share => 'Share';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Shortcuts';

  @override
  String get shouldDuck => 'Should duck';

  @override
  String get shouldDuckNote => 'Indicates that the volume should be lowered. ex: notification';

  @override
  String get shouldPause => 'Should pause';

  @override
  String get shouldPauseNote => 'Indicates that the playback should be paused. ex: calls';

  @override
  String get showAll => 'Show All';

  @override
  String get showChannelWatermarkInFullscreen => 'Show channel watermark in fullscreen';

  @override
  String get showFailedOnly => 'Show Failed only';

  @override
  String get showHideUnknownFields => 'Show/hide Unknown Fields';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Show Mixes in';

  @override
  String get showMore => 'Show more';

  @override
  String get showShortVideosIn => 'Show Shorts in';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'Show video endcards';

  @override
  String get showWebm => 'Show webm';

  @override
  String get shuffle => 'Shuffle';

  @override
  String get shuffleAll => 'Shuffle All';

  @override
  String get shuffleNext => 'Shuffle Next';

  @override
  String get signIn => 'Sign in';

  @override
  String get signInCanceled => 'Sign in was canceled';

  @override
  String get signInFailed => 'Sign in failed';

  @override
  String get signInToYourAccount => 'Sign in to your account';

  @override
  String get signInYouDontHaveAccount => 'You don\'t have any account signed in';

  @override
  String get signInYouNeedAccountToViewPage => 'You need an account to view this page';

  @override
  String get signOut => 'Sign out';

  @override
  String signOutFromName({required String name}) {
    return 'Sign out from $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Signing in allows basic usage';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Get early access through patreon or by using coupon';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Similar Time Range';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generate tracks you listened to around the same time as $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'Size';

  @override
  String get skip => 'Skip';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Skip Silence';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Sleep After';

  @override
  String get sleepTimer => 'Sleep timer';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Sort by';

  @override
  String get source => 'Source';

  @override
  String get speed => 'Speed';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Staggered Album Gridview';

  @override
  String get start => 'Start';

  @override
  String get stats => 'Statistics';

  @override
  String get statsSubtitle => 'Here is some info about your library';

  @override
  String get stop => 'Stop';

  @override
  String get stopAfterThisTrack => 'Stop after this track';

  @override
  String get stopAfterThisVideo => 'Stop after this video';

  @override
  String get storagePermissionDenied => 'Permission Denied';

  @override
  String get storagePermissionDeniedSubtitle => 'Please allow access to be able to perform this action';

  @override
  String get stretchLyricsDuration => 'Stretch Lyrics Duration';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Subscribe';

  @override
  String get subscribed => 'Subscribed';

  @override
  String get subscriber => 'Subscriber';

  @override
  String get subscribers => 'Subscribers';

  @override
  String get succeeded => 'Succeeded';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Support';

  @override
  String get supremacy => 'Supremacy';

  @override
  String get sussyBaka => 'Bruh no tracks';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Swipe to open drawer';

  @override
  String get synced => 'Synced';

  @override
  String get synopsis => 'Synopsis';

  @override
  String get tagFields => 'Tag Fields';

  @override
  String get tags => 'Tags';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Tap to seek';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Theme Mode';

  @override
  String get themeModeDark => 'Dark';

  @override
  String get themeModeLight => 'Light';

  @override
  String get themeModeSystem => 'System';

  @override
  String get themeSettings => 'Theme';

  @override
  String get themeSettingsSubtitle => 'The overall vibe of your player';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'This playlist has active sorters, please disable them before reordering.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'This video is likely deleted or set to private.';

  @override
  String get thumbnails => 'Thumbnails';

  @override
  String get title => 'Title';

  @override
  String get top => 'Top';

  @override
  String get topComments => 'Top comments';

  @override
  String get topCommentsSubtitle => 'Display comments at top instead of bottom';

  @override
  String get topRecentAlbums => 'Top Recent Albums';

  @override
  String get topRecentArtists => 'Top Recent Artists';

  @override
  String get topRecents => 'Top Recents';

  @override
  String get totalListenTime => 'Total Listen Time';

  @override
  String get totalListens => 'Total Listens';

  @override
  String get totalTracks => 'Total Tracks';

  @override
  String get totalTracksDuration => 'Total Tracks Duration';

  @override
  String get track => 'Track';

  @override
  String get trackArtistsSeparator => 'Artists Separators';

  @override
  String get trackGenresSeparator => 'Genres Separators';

  @override
  String get trackInfo => 'Track Info';

  @override
  String get trackNotFound => 'Track not found';

  @override
  String get trackNumber => 'Track Number';

  @override
  String get trackNumberTotal => 'Track Total';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Old name: \"$oldName\"\n\nNew name: \"$newName\"\n\nAre you sure?';
  }

  @override
  String get trackPlayMode => 'Play Mode';

  @override
  String get trackPlayModeSearchResults => 'Search Results';

  @override
  String get trackPlayModeSelectedOnly => 'Selected track only';

  @override
  String get trackPlayModeTrackAlbum => 'Track\'s Album';

  @override
  String get trackPlayModeTrackArtist => 'Track\'s Main Artist';

  @override
  String get trackPlayModeTrackGenre => 'Track\'s Genre';

  @override
  String get trackThumbnailSizeInList => 'Size of Track Thumbnail';

  @override
  String get trackTileCustomization => 'Track Tile Customization';

  @override
  String get trackTileItemsSeparator => 'Items Separator';

  @override
  String get tracks => 'Tracks';

  @override
  String get tracksExcludedByNomedia => 'Tracks Excluded by .nomedia';

  @override
  String get tracksInfo => 'Tracks Info';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Undo';

  @override
  String get undoChanges => 'Undo Changes?';

  @override
  String get undoChangesDeletedPlaylist => 'Undo deleted playlist';

  @override
  String get undoChangesDeletedQueue => 'Undo deleted Queue';

  @override
  String get undoChangesDeletedTrack => 'Undo deleted track';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Unlimited';

  @override
  String get unlisted => 'Unlisted';

  @override
  String get unlock => 'Unlock';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Update';

  @override
  String get updateDirectoryPath => 'Update directory path';

  @override
  String get updateMissingTracksOnly => 'Update missing tracks only';

  @override
  String get updating => 'Updating';

  @override
  String get useCollapsedSettingTiles => 'Use Collapsed Setting Tiles';

  @override
  String get useMediaStore => 'Use Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ instant indexing time\nx respect .nomedia will be forcely enabled\nx some metadata tags will be missing\nx youtube integration for local library will not work';

  @override
  String get usePitchBlack => 'Use Pitch Black';

  @override
  String get usePitchBlackSubtitle => 'Useful for AMOLED screens.. and looks cooler';

  @override
  String get used => 'Used';

  @override
  String get value => 'Value';

  @override
  String get valueBetween50200 => 'Value should be between 50% and 200%';

  @override
  String get vibration => 'Vibration';

  @override
  String get vibrationType => 'Vibration type';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Video Cache';

  @override
  String get videoCacheFile => 'Cached Video File';

  @override
  String get videoCacheFiles => 'Cached Video Files';

  @override
  String get videoOnly => 'Video Only';

  @override
  String get videoPlaybackSource => 'Video Source';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'This will give priority to local videos, if not found then it will fetch from youtube';

  @override
  String get videoPlaybackSourceLocal => 'Local Videos';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Checks if any video file (found inside the chosen folders list) has a filename that contains the filename of the track';

  @override
  String get videoPlaybackSourceYoutube => 'From Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Checks in track\'s filename & comment for any matching youtube link, videos are cached for later use.';

  @override
  String get videoQuality => 'Video Quality';

  @override
  String get videoQualitySubtitle => 'Highest quality available will be picked.';

  @override
  String get videoQualitySubtitleNote => 'It\'s always good to keep more alternatives in case a quality isn\'t found, otherwise it will fallback to the worst quality';

  @override
  String get videos => 'Videos';

  @override
  String get view => 'view';

  @override
  String get viewAll => 'View All';

  @override
  String get views => 'views';

  @override
  String get volume => 'Volume';

  @override
  String get warning => 'Warning';

  @override
  String get waveformBarsCount => 'Waveform Bars Count';

  @override
  String get webmNoEditTagsSupport => 'WEBM format doesn\'t support tag editing';

  @override
  String get week => 'Week';

  @override
  String get year => 'Year';

  @override
  String get yes => 'yes';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Your current membership is $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Your custom order will be lost, Are you sure?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Music';

  @override
  String get youtubeSettingsSubtitle => 'Customize Youtube experience';

  @override
  String get youtubeStyleMiniplayer => 'Youtube-style Miniplayer';

  @override
  String get ytPreferNewComments => 'Prefer new comments when possible';

  @override
  String get ytPreferNewCommentsSubtitle => 'Cached version will only be used when there is no connection';
}
