// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Vietnamese (`vi`).
class AppLocalizationsVi extends AppLocalizations {
  AppLocalizationsVi([String locale = 'vi']) : super(locale);

  @override
  String get about => 'Thông tin';

  @override
  String get active => 'Hoạt động';

  @override
  String get add => 'Thêm';

  @override
  String get addAccount => 'Thêm tài khoản';

  @override
  String get addAll => 'Thêm tất cả';

  @override
  String get addAllAndRemoveOldOnes => 'Thêm tất cả và xóa những thứ cũ';

  @override
  String get addAsANewPlaylist => 'Thêm dưới dạng danh sách phát mới';

  @override
  String get addAudioToLocalLibrary => 'Thêm nhạc vào thư viện của máy';

  @override
  String get addFolder => 'Thêm thư mục';

  @override
  String get addLanguage => 'Thêm ngôn ngữ';

  @override
  String get addLanguageSubtitle => 'Hỗ trợ dịch Namida sang ngôn ngữ của bạn';

  @override
  String get addLrcFile => 'Thêm tập tin LRC';

  @override
  String get addMoreFromThisAlbum => 'Thêm nhiều hơn từ Album này vào hàng đợi';

  @override
  String get addMoreFromThisArtist => 'Thêm nhiều hơn từ nghệ sĩ này vào hàng đợi';

  @override
  String get addMoreFromThisFolder => 'Thêm nhiều hơn từ thư mục này vào hàng đợi';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Thêm nội dung khác từ $media vào hàng đợi';
  }

  @override
  String get addOnlyMissing => 'Chỉ thêm khi thiếu';

  @override
  String get addToFavourites => 'Thêm vào mục ưa thích';

  @override
  String get addToPlaylist => 'Thêm vào danh sách phát';

  @override
  String get addTracksAtTheBeginning => 'Thêm những bài hát ở đầu';

  @override
  String get added => 'Đã thêm';

  @override
  String get advanced => 'Nâng cao';

  @override
  String get advancedSettings => 'Nâng cao';

  @override
  String get advancedSettingsSubtitle => 'Cài đặt nâng cao, vui lòng bỏ qua';

  @override
  String get alarm => 'Báo thức';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Album của Nghệ sĩ';

  @override
  String get albumArtists => 'Album của Nghệ sĩ';

  @override
  String get albumIdentifiers => 'Truy xuất album';

  @override
  String get albumThumbnailSizeInList => 'Kích thước hình thu nhỏ của Album';

  @override
  String get albumTileCustomization => 'Tùy chỉnh tiêu đề Album';

  @override
  String get albums => 'Album';

  @override
  String get albumsCount => 'Số lượng Album';

  @override
  String get all => 'Tất cả';

  @override
  String get allTime => 'Mọi lúc';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Luôn luôn';

  @override
  String get alwaysAsk => 'Luôn hỏi';

  @override
  String get alwaysDim => 'Luôn làm tối';

  @override
  String get alwaysExpandedSearchbar => 'Luôn mở rộng thanh tìm kiếm';

  @override
  String get alwaysRestore => 'Luôn khôi phục';

  @override
  String get animatingThumbnailIntensity => 'Cường độ hoạt ảnh hình thu nhỏ';

  @override
  String get animatingThumbnailInversed => 'Đảo ngược hoạt ảnh';

  @override
  String get animatingThumbnailInversedSubtitle => 'Thiết lập ở mức cao sẽ khiến hình thu nhỏ bé lại';

  @override
  String get anotherProcessIsRunning => 'Một tiến trình khác đang chạy.';

  @override
  String get appIcon => 'App Icon';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Nghệ sĩ';

  @override
  String get artists => 'Nghệ sĩ';

  @override
  String get artwork => 'Bìa';

  @override
  String get artworkGestures => 'Cử chỉ trên ảnh bìa';

  @override
  String get artworks => 'Bìa';

  @override
  String get audio => 'Âm thanh';

  @override
  String get audioCache => 'Bộ nhớ đệm âm thanh';

  @override
  String get audioOnly => 'Chỉ âm thanh';

  @override
  String get auto => 'Tự động';

  @override
  String get autoBackupInterval => 'Khoảng thời gian sao lưu tự động';

  @override
  String get autoColoring => 'Tự động đổi màu';

  @override
  String get autoColoringSubtitle => 'Tự động chuyển màu theo bìa nhạc đang mở';

  @override
  String get autoExtractTagsFromFilename => 'Tự động trích xuất từ tên tập tin';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Tự động trích xuất Tiêu đề và Nghệ sĩ từ tiêu đề video';

  @override
  String get autoGenerated => 'Tự động tạo';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Tự chạy radio bài hát';

  @override
  String get autoStartRadioSubtitle => 'Tự động thêm các bản mix khi phát một bài hát';

  @override
  String get automaticBackup => 'Tự động';

  @override
  String get automaticBackupSubtitle => 'Tự động áp dụng tệp sao lưu gần đây nhất được tìm thấy bên trong vị trí sao lưu';

  @override
  String get backupAndRestore => 'Sao lưu & Khôi phục';

  @override
  String get backupAndRestoreSubtitle => 'Sao lưu cơ sở dữ liệu và cài đặt';

  @override
  String get balanced => 'Cân bằng';

  @override
  String get beta => 'Thử nghiệm';

  @override
  String get betweenDates => 'Giữa các ngày';

  @override
  String get bitrate => 'Tốc độ bit';

  @override
  String get blacklist => 'Danh sách đen';

  @override
  String get borderRadiusMultiplier => 'Bán kính đường viền';

  @override
  String get cache => 'Bộ nhớ đệm';

  @override
  String get cancel => 'Hủy bỏ';

  @override
  String get canceled => 'Đã hủy';

  @override
  String get changed => 'Đã thay đổi';

  @override
  String get changelog => 'Có gì mới';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Kênh';

  @override
  String get channels => 'Kênh';

  @override
  String get check => 'Kiểm tra';

  @override
  String get checkForMore => 'Kiểm tra thêm';

  @override
  String get checkList => 'Kiểm tra danh sách';

  @override
  String get choose => 'Chọn';

  @override
  String get chooseWhatToClear => 'Chọn nội dung cần xoá';

  @override
  String get claim => 'Yêu cầu';

  @override
  String get clear => 'Xoá';

  @override
  String get clearAudioCache => 'Xoá bộ nhớ đệm âm thanh';

  @override
  String get clearImageCache => 'Xoá bộ nhớ đệm hình ảnh';

  @override
  String get clearImageCacheWarning => 'Cảnh báo: sẽ dẫn đến việc thư viện không có hình ảnh. Chỉ sử dụng để xây dựng lại bộ nhớ đệm hình ảnh.';

  @override
  String get clearTrackItem => 'Xoá bài hát';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Xoá $numberString bài hát',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Xoá bộ nhớ đệm video';

  @override
  String get clearVideoCacheNote => 'Chọn nội dung cần xoá.';

  @override
  String get clock => 'Đồng hồ';

  @override
  String get colorPalette => 'Bảng màu';

  @override
  String get colorPaletteNote1 => 'Nhấn giữ một màu để loại bỏ';

  @override
  String get colorPaletteNote2 => 'Chạm vào hỗn hợp để sử dụng màu mặc định';

  @override
  String get colorPalettes => 'Bảng màu';

  @override
  String get comment => 'Bình luận';

  @override
  String get comments => 'Bình luận';

  @override
  String get composer => 'Nhà soạn nhạc';

  @override
  String get compress => 'Nén';

  @override
  String get compressImages => 'Nén hình ảnh';

  @override
  String get compressionPercentage => 'Phần trăm nén';

  @override
  String get configure => 'Tùy chỉnh';

  @override
  String get confirm => 'Xác nhận';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Đã sao chép bìa';

  @override
  String get copiedToClipboard => 'Đã sao chép vào bộ nhớ tạm';

  @override
  String get copy => 'Sao chép';

  @override
  String get corruptedFile => 'Không thể phân tích tập tin, có thể tệp bị hỏng';

  @override
  String get couldntOpen => 'Không thể mở (╥﹏╥)';

  @override
  String get couldntOpenYtLink => 'Không có sẵn liên kết Youtube cho bài hát này';

  @override
  String get couldntPlayFile => 'Không thể phát tập tin';

  @override
  String get couldntRenamePlaylist => 'Không thể đổi tên danh sách phát';

  @override
  String get couldntSaveImage => 'Không thể lưu hình ảnh';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Quốc gia';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Tạo';

  @override
  String get createBackup => 'Tạo bản sao lưu';

  @override
  String get createNewPlaylist => 'Tạo danh sách phát mới';

  @override
  String get createdBackupSuccessfully => 'Đã tạo bản sao lưu';

  @override
  String get createdBackupSuccessfullySub => 'Tập tin sao lưu đã được tạo thành công';

  @override
  String get crossPlatformSync => 'Đồng bộ hóa đa thiết bị';

  @override
  String get crossfadeDuration => 'Thời lượng Chuyển đổi mượt';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Tự động bật Chuyển tiếp mượt sau$secondsString giây',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Không tự động bật Chuyển tiếp mượt';

  @override
  String get custom => 'Tùy chỉnh';

  @override
  String get customizations => 'Tùy chỉnh';

  @override
  String get customizationsSubtitle => 'Tùy chỉnh giao diện trình phát đẹp như bạn :3';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'Cơ sở dữ liệu';

  @override
  String get date => 'Ngày';

  @override
  String get dateAdded => 'Ngày thêm';

  @override
  String get dateCreated => 'Ngày tạo';

  @override
  String get dateModified => 'Ngày sửa đổi';

  @override
  String get dateTimeFormat => 'Định dạng ngày giờ';

  @override
  String get day => 'Ngày';

  @override
  String get days => 'Ngày';

  @override
  String get defaultBackupLocation => 'Vị trí sao lưu mặc định';

  @override
  String get defaultColor => 'Màu mặc định';

  @override
  String get defaultColorSubtitle => 'Thiết lập màu cho trình phát';

  @override
  String get defaultDownloadLocation => 'Vị trí tải xuống mặc định';

  @override
  String get defaultLabel => 'Mặc định';

  @override
  String get defaultLibraryTab => 'Thư viện mặc định';

  @override
  String get delete => 'Xoá';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Xóa $countString tập tin để giải phóng $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Xóa vĩnh viễn $numberText bài hát';
  }

  @override
  String get deletePlaylist => 'Xoá danh sách phát';

  @override
  String get deleteTempFiles => 'Xóa tập tin tạm thời';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Mô tả';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Ý bạn là';

  @override
  String get dimIntensity => 'Cường độ tối';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Trình phát thu nhỏ sẽ tối đi sau $secondsString giây không hoạt động',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Đường dẫn không tồn tại';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Tắt tất cả thông báo';

  @override
  String get disableReordering => 'Tắt sắp xếp lại';

  @override
  String get disableSearchCleanup => 'Tắt xóa lịch sử tìm kiếm';

  @override
  String get discNumber => 'Đĩa số';

  @override
  String get discNumberTotal => 'Tổng số lượng đĩa nhạc';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Không thích';

  @override
  String get dismissibleMiniplayer => 'Tắt trình phát thu nhỏ';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Hiện thẻ album góc phải trên cùng ngày';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Hiển thị ngày của Album ở Thẻ Album trên cùng bên phải';

  @override
  String get displayArtistBeforeTitle => 'Hiển thị tên nghệ sĩ trước tiêu đề';

  @override
  String get displayArtworkOnLockscreen => 'Hiển thị ảnh bìa trên màn hình khóa';

  @override
  String get displayAudioInfoInMiniplayer => 'Hiển thị thông tin âm thanh';

  @override
  String get displayFavButtonInNotification => 'Hiển thị nút Yêu thích trong Thông báo';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Hình thu nhỏ có thể bị lệch.';

  @override
  String get displayFavouriteIconInTrackTile => 'Hiển thị nút Yêu thích';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Hiển thị thời lượng còn lại thay vì tổng thời lượng';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Hiển thị mục thứ ba trong mỗi hàng';

  @override
  String get displayThirdRowInTrackTile => 'Hiển thị hàng thứ ba';

  @override
  String get displayTrackNumberInAlbumPage => 'Hiển thị số thứ tự bài hát trong Album';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Hiển thị ô nhỏ chứa số thứ tự bài hát trong Album';

  @override
  String get doNothing => 'Không làm gì cả';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Đã hoàn thành';

  @override
  String get dontAskAgain => 'Không hỏi lại';

  @override
  String get dontDim => 'Không làm tối';

  @override
  String get dontRestorePosition => 'Không phục hồi';

  @override
  String get dontResume => 'Không tiếp tục';

  @override
  String get doubleTapToToggleLyrics => 'Ấn hai lần để hiện lời bài hát';

  @override
  String get download => 'Tải xuống';

  @override
  String get downloadingWillOverrideIt => 'Việc tải xuống tập tin trùng khớp sẽ ghi đè lên nó';

  @override
  String get downloads => 'Tải xuống';

  @override
  String get downloadsMetadataTags => 'Tải xuống thẻ Metadata';

  @override
  String get downloadsMetadataTagsSubtitle => 'Mặc định trích xuất tên nghệ sĩ, tiêu đề và album từ thông tin video';

  @override
  String get dragToSeek => 'Kéo để tìm kiếm';

  @override
  String get duckAudio => 'Thiết lập giảm âm lượng ở mức ngưỡng 50%';

  @override
  String get duplicatedItemsAdding => 'Bạn đang thêm một số mục đã tồn tại trong danh sách phát này';

  @override
  String get duplicatedTracks => 'Bài hát trùng lặp';

  @override
  String get duration => 'Thời lượng';

  @override
  String get edgeColorsSwitching => 'Chuyển đổi màu góc cạnh';

  @override
  String get edit => 'Chỉnh sửa';

  @override
  String get editArtwork => 'Chỉnh sửa ảnh bìa';

  @override
  String get editTags => 'Chỉnh sửa thẻ';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'Có các trường có giá trị trống/không có ý nghĩa, hãy đảm bảo rằng bạn thực sự muốn chỉnh sửa chúng';

  @override
  String get emptyValue => 'Giá trị trống';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Kích hoạt hiệu ứng làm mờ';

  @override
  String get enableBottomNavBar => 'Bật thanh điều hướng phía dưới';

  @override
  String get enableBottomNavBarSubtitle => 'Mục nằm bên trong ngăn kéo theo cả hai hướng';

  @override
  String get enableClipboardMonitoring => 'Kích hoạt giám sát bảng nhớ tạm';

  @override
  String get enableClipboardMonitoringSubtitle => 'Cho phép dán liên kết và văn bản bên trong thanh tìm kiếm khi đang di chuyển';

  @override
  String get enableCrossfadeEffect => 'Bật Chuyển tiếp mượt';

  @override
  String get enableFadeEffectOnPlayPause => 'Kích hoạt hiệu ứng âm thanh nhỏ/lớn khi phát/tạm dừng';

  @override
  String get enableFoldersHierarchy => 'Bật Phân cấp thư mục';

  @override
  String get enableGlowEffect => 'Bật hiệu ứng phát sáng';

  @override
  String get enableM3uSync => 'Bật đồng bộ hóa file M3U';

  @override
  String get enableM3uSyncNote1 => 'M3U Sync cho phép lưu các thay đổi danh sách phát vào tệp M3U gốc';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Nếu có sự cố xảy ra, bản sao lưu của danh sách phát này sẽ được tìm thấy trong $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Nếu bị từ chối, tất cả các thay đổi được thực hiện trong danh sách phát này sẽ bị mất khi khởi động lại ứng dụng';

  @override
  String get enableMiniplayerParticles => 'Kích hoạt các hạt chuyển động';

  @override
  String get enableParallaxEffect => 'Kích hoạt hiệu ứng Parallax';

  @override
  String get enablePartyMode => 'Kích hoạt chế độ Party';

  @override
  String get enablePartyModeSubtitle => 'Áp dụng hiệu ứng thở cạnh lạ mắt';

  @override
  String get enablePictureInPicture => 'Kích hoạt tính năng Hình trong Hình | PIP';

  @override
  String get enableReordering => 'Sắp xếp lại';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Xóa lịch sử tìm kiếm';

  @override
  String get enableSearchCleanupSubtitle => 'Tất cả các Biểu tượng và Dấu cách sẽ bị bỏ qua';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'Kích hoạt tính năng phát lại Video';

  @override
  String get enterSymbol => 'Xin vui lòng nhập một biểu tượng';

  @override
  String get equalizer => 'Bộ chỉnh cân bằng âm thanh';

  @override
  String get error => 'Lỗi';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Lỗi khi phát bài hát';

  @override
  String get excludedFodlers => 'Loại trừ Thư mục';

  @override
  String get exit => 'Thoát ra';

  @override
  String get exitAppSubtitle => 'Chạm một lần nữa để thoát';

  @override
  String get expandedMiniplayer => 'Trình phát thu nhỏ mở rộng';

  @override
  String get exportAsM3u => 'Xuất dưới dạng M3U';

  @override
  String get extension => 'Phần mở rộng';

  @override
  String get externalFiles => 'Tập tin bên ngoài';

  @override
  String get extract => 'Trích xuất';

  @override
  String get extractAllColorPalettes => 'Trích xuất tất cả bảng màu';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Trích xuất còn lại $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Trích xuất feat. Nghệ sĩ từ tiêu đề';

  @override
  String get extractFeatArtistSubtitle => 'Trích xuất (feat. X) và (ft. X) nghệ sĩ, với tư cách là nghệ sĩ mới tham gia.';

  @override
  String get extractingInfo => 'Trích xuất Thông tin';

  @override
  String get extras => 'Bổ sung';

  @override
  String get extrasSubtitle => 'Cài đặt bổ sung để cải thiện trải nghiệm';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Thất bại';

  @override
  String get failedEdits => 'Chỉnh sửa thất bại';

  @override
  String get favourites => 'Yêu Thích';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Đang tải';

  @override
  String get fetchingOfAllVideos => 'Tìm nạp tất cả video';

  @override
  String get file => 'Tập tin';

  @override
  String get fileAlreadyExists => 'Tập tin đã tồn tại';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Tên tập tin';

  @override
  String get fileNameWoExt => 'Tên tệp không có phần mở rộng';

  @override
  String get filenameShouldntStartWith => 'Tên tệp không được bắt đầu bằng';

  @override
  String get files => 'Tập tin';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Lọc Album';

  @override
  String get filterArtists => 'Lọc Nghệ sĩ';

  @override
  String get filterGenres => 'Lọc Thể loại';

  @override
  String get filterPlaylists => 'Lọc Danh sách phát';

  @override
  String get filterTracks => 'Lọc Bài hát';

  @override
  String get filterTracksBy => 'Lọc các bản nhạc trong danh sách tìm kiếm theo';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Bài hát được lọc theo kích thước và thời lượng';

  @override
  String get finished => 'Đã hoàn thành';

  @override
  String get finishedUpdatingLibrary => 'Đã cập nhật xong thư viện';

  @override
  String get firstListen => 'Nghe đầu tiên';

  @override
  String get fixYtdlpBigThumbnailSize => 'Sửa kích thước hình thu nhỏ lớn của yt-dlp';

  @override
  String get floatingActionButton => 'Nút hành động nổi';

  @override
  String get folder => 'Thư mục';

  @override
  String get folderName => 'Tên thư mục';

  @override
  String get folders => 'Thư mục';

  @override
  String get fontScale => 'Kích cỡ phông chữ';

  @override
  String get forceMiniplayerFollowTrackColors => 'Buộc trình phát thu nhỏ tuân theo màu sắc của bản nhạc';

  @override
  String get forceSquaredAlbumThumbnail => 'Buộc hình thu nhỏ của Album phải vuông góc';

  @override
  String get forceSquaredThumbnailNote =>
      'Kích thước hình thu nhỏ & Chiều cao của ô KHÔNG bằng nhau, Giao diện hình vuông sẽ không như mong đợi, Bạn có muốn làm cho chúng bằng nhau không?';

  @override
  String get forceSquaredTrackThumbnail => 'Buộc hình thu nhỏ của bài hát phải vuông góc';

  @override
  String get forceStopColorPaletteGeneration => 'Buộc ngừng trích xuất bảng màu ? bạn vẫn có thể tiếp tục nó sau';

  @override
  String get format => 'Định dạng';

  @override
  String get fullscreen => 'Toàn màn hình';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Tạo ra';

  @override
  String get generateFromDates => 'Phạm vi thời gian';

  @override
  String get generateFromDatesSubtitle => 'Tạo các bản nhạc bạn đã nghe trong một khoảng thời gian';

  @override
  String get generateRandomPlaylist => 'Tạo danh sách phát ngẫu nhiên';

  @override
  String get genre => 'Thể loại';

  @override
  String get genres => 'Thể loại';

  @override
  String get goToAlbum => 'Đi tới Album';

  @override
  String get goToArtist => 'Đi tới Nghệ sĩ';

  @override
  String get goToChannel => 'Đi tới Kênh';

  @override
  String get goToFolder => 'Đi tới Thư mục';

  @override
  String get goodLooking => 'Có vẻ tốt';

  @override
  String get grantStoragePermission => 'Cấp quyền lưu trữ';

  @override
  String get group => 'Nhóm';

  @override
  String get groupArtworksByAlbum => 'Nhóm bìa theo Album';

  @override
  String get guide => 'Hướng dẫn';

  @override
  String get hapticFeedback => 'Haptic Feedback';

  @override
  String get heightOfAlbumTile => 'Chiều cao của ô Album';

  @override
  String get heightOfTrackTile => 'Chiều cao của ô Bài hát';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Trùng khớp cao';

  @override
  String get highPerformance => 'Hiệu suất cao';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Lịch sử';

  @override
  String get historyImportMissingEntriesNote =>
      'Những mục này không thể tìm thấy trong thư viện, nếu bạn cho rằng chúng tồn tại, vui lòng cân nhắc việc thêm chúng theo cách thủ công';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString lắng nghe $oldTrackInfo sẽ được thay thế $newTrackInfo, xác nhận ?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Trang chính';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'Định dạng 12 giờ';

  @override
  String get hours => 'Giờ';

  @override
  String get iReadAndAgree => 'Tôi đã đọc và đồng ý';

  @override
  String get ifNotPlaying => 'Nếu không phát';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Tải xuống có thể sẽ bị vấn đề nếu ứng dụng bị hạn chế về Pin';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Bỏ qua tiền tố thông dụng khi sắp xếp';

  @override
  String get ignores => 'Bỏ qua';

  @override
  String get imageSource => 'Nguồn';

  @override
  String get immersiveMode => 'Chế độ Immersive';

  @override
  String get immersiveModeSubtitle => 'Ẩn thanh Trạng thái và Điều hướng trong khi Trình phát thu nhỏ được mở rộng';

  @override
  String get import => 'Nhập vào';

  @override
  String get importAll => 'Nhập tất cả';

  @override
  String get importLastFmHistory => 'Nhập lịch sử LastFM';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Đi tới $lastfmCsvLink\n\n2. Nhập tên tài khoản, tìm nạp và tải xuống tệp csv.\n\n3. Chọn tệp tin từ màn hình tiếp theo.';
  }

  @override
  String get importTimeRange => 'Nhập phạm vi thời gian';

  @override
  String get importYoutubeHistory => 'Nhập lịch sử Youtube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Đi tới $takeoutLink\n\n2. Nhấn \"Nhiều định dạng\" và bên cạnh \"Lịch sử\" chọn \"JSON\".\n\n3. nhấn \"Bao gồm tất cả dữ liệu trên Youtube\", Bỏ chọn Tất cả và chỉ chọn lịch sử.\n\n4. Tạo bản xuất, Tải xuống và giải nén.\n\n5. Chọn \"watch-history.json\" từ màn hình tiếp theo.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Đã nhập $numberString kênh thành công',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Đã nhập $numberText danh sách phát thành công',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Bao gồm video';

  @override
  String get indexRefreshRequired => 'Thực hiện Làm mới sau khi thay đổi';

  @override
  String get indexer => 'Lập chỉ mục';

  @override
  String get indexerNote => 'Lưu ý: Số lượng bìa không đầy đủ đề cập đến bìa trùng lặp và không tìm thấy';

  @override
  String get indexerSubtitle => 'Quản lý thư viện Âm Nhạc';

  @override
  String get infinityQueueOnNextPrev => 'Hàng đợi vô hạn ở Tiếp theo/Trước đó';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'Nhấn tiếp theo trong khi phát lại mục cuối cùng sẽ nhảy về đầu tiên và ngược lại';

  @override
  String get info => 'Thông tin';

  @override
  String get inserted => 'Chèn vào';

  @override
  String get instantlyApplies => 'Áp dụng ngay lập tức';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Lựa chọn đối nghịch';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Mục';

  @override
  String get jump => 'Nhảy';

  @override
  String get jumpToDay => 'Nhảy sang Ngày';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Nhảy sang bài hát đầu tiên sau khi kết thúc hàng đợi';

  @override
  String get keepCachedVersions => 'Giữ bộ nhớ đệm của các phiên bản được lưu';

  @override
  String get keepFileDates => 'Giữ ngày trong tập tin';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Trình phát thủ nhỏ được mở rộng';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Trình phát thu nhỏ được mở rộng và video đang phát';

  @override
  String get keepScreenAwakeNone => 'Không để màn hình sáng';

  @override
  String get keepScreenAwakeWhen => 'Chỉ để màn hình sáng khi';

  @override
  String get killPlayerAfterDismissingApp => 'Tắt trình phát sau khi ứng dụng bị tắt';

  @override
  String get language => 'Ngôn ngữ';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Trang Thư viện';

  @override
  String get libraryTabsReorder => 'Bạn có thể sắp xếp lại các trang khi đã kích hoạt..';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Thích';

  @override
  String get liked => 'Đã thích';

  @override
  String get link => 'Liên kết';

  @override
  String get listOfFolders => 'Danh sách các thư mục';

  @override
  String get loadAll => 'Tải tất cả';

  @override
  String get loadingFile => 'Đang tải tập tin';

  @override
  String get local => 'Cục bộ';

  @override
  String get localVideoMatching => 'Video cục bộ trùng khớp';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Ấn giữ lời bài hát để vào chế độ toàn màn hình';

  @override
  String get lostMemories => 'Ký ức đã mất';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Khoảng thời gian này, $numberString năm trước',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Tăng cường âm lượng';

  @override
  String get lyricist => 'Người viết lời';

  @override
  String get lyrics => 'Lời bài hát';

  @override
  String get lyricsSource => 'Nguồn lời bài hát';

  @override
  String get m3uPlaylist => 'Danh sách phát M3U';

  @override
  String get makeYourFirstListen => 'Lắng nghe lần đầu tiên!';

  @override
  String get manage => 'Quản lý';

  @override
  String get manageYourAccounts => 'Quản lý tài khoản';

  @override
  String get manualBackup => 'Thủ công';

  @override
  String get manualBackupSubtitle => 'Lấy một tập tin cụ thể';

  @override
  String get markAsRead => 'Đánh dấu là đã đọc';

  @override
  String get matchAllTracks => 'Tất cả bài hát trùng khớp';

  @override
  String get matchAllTracksNote => 'Điều này có thể ảnh hưởng đến tốc độ trùng khớp vì nó sẽ kiểm tra tất cả các bản nhạc trong thư viện của bạn';

  @override
  String get matchingType => 'Loại phù hợp';

  @override
  String get maxAudioCacheSize => 'Kích thước bộ nhớ đệm âm thanh tối đa';

  @override
  String get maxImageCacheSize => 'Kích thước bộ nhớ đệm hình ảnh tối đa';

  @override
  String get maxVideoCacheSize => 'Kích thước bộ nhớ đệm Video tối đa';

  @override
  String get maximum => 'Tối đa';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Không thể thực hiện do Media Store đang bật';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Mật mã';

  @override
  String get membershipCodeSentToEmail => 'Mã gửi đến email của bạn';

  @override
  String get membershipDidntChange => 'Tư cách thành viên không thay đổi';

  @override
  String get membershipEnjoyNew => 'Tận hưởng tư cách thành viên mới';

  @override
  String get membershipFreeCoupon => 'Phiếu giảm giá miễn phí';

  @override
  String get membershipManage => 'Quản lý thành viên';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Không tìm thấy đăng ký của người dùng này';

  @override
  String get membershipSignInToPatreonAccount => 'Đăng nhập vào tài khoản Patreon';

  @override
  String get membershipUnknown => 'Thành viên không xác định';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Bạn cần có tư cách thành viên của $name1 hoặc $name2 để thêm nhiều tài khoản';
  }

  @override
  String get merge => 'Hợp nhất';

  @override
  String get metadataCache => 'Bộ nhớ đệm Siêu dữ liệu';

  @override
  String get metadataEditFailed => 'Không thể chỉnh sửa siêu dữ liệu';

  @override
  String get metadataReadFailed => 'Không đọc được siêu dữ liệu';

  @override
  String get minFileDuration => 'Thời lượng tối thiểu của Bài hát';

  @override
  String get minFileSize => 'Kích thước tập tin tối thiểu';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Thời lượng bản nhạc tối thiểu để khôi phục vị trí đã phát cuối cùng';

  @override
  String get minValueCantBeMoreThanMax => 'Giá trị tối thiểu không được lớn hơn giá trị tối đa';

  @override
  String get minValueToCountTrackListen => 'Đếm lượt nghe sau: ';

  @override
  String get minimizedMiniplayer => 'Trình phát thu nhỏ được thu nhỏ';

  @override
  String get minimum => 'Tối thiểu';

  @override
  String get minimumOneFolderSubtitle => 'Phải có ít nhất 1 thư mục, tạo thêm nhiều thư mục hơn nếu muốn xóa thư mục này';

  @override
  String get minimumOneItem => 'Không thể xoá mục này';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Phải còn lại ít nhất $numberString mục vẫn còn',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Tùy biến Trình phát thu nhỏ';

  @override
  String get minutes => 'Phút';

  @override
  String get missingEntries => 'Mục còn thiếu';

  @override
  String get missingTracks => 'Bài hát bị thiếu';

  @override
  String get mix => 'danh sách phát tổng hợp của youtube (tương tự như radio trong youtube music)';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Kết hợp danh sách phát được tạo bởi youtube';

  @override
  String get mixes => 'Bản mix';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Tháng';

  @override
  String get months => 'Tháng';

  @override
  String get mood => 'Tâm trạng';

  @override
  String get moods => 'Tâm trạng';

  @override
  String get more => 'Thêm nữa';

  @override
  String get mostPlayed => 'Phát lại nhiều nhất';

  @override
  String get multipleTracksTagsEditNote => 'Thông tin của các bài hát này sẽ được thay đổi,\nCác trường không thay đổi vẫn được giữ nguyên..';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Tên';

  @override
  String get nameContainsBadCharacter => 'Tên chưa những ký tự xấu';

  @override
  String get never => 'Không bao giờ';

  @override
  String get newDirectory => 'Danh mục mới';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Thêm bản nhạc';

  @override
  String get newTracksMoods => 'Tâm trạng';

  @override
  String get newTracksMoodsSubtitle => 'Tạo ra các bản nhạc dựa trên tâm trạng có sẵn';

  @override
  String get newTracksRandom => 'Ngẫu nhiên';

  @override
  String get newTracksRandomSubtitle => 'Lấy ngẫu nhiên một vài Bài hát từ thư viện';

  @override
  String get newTracksRatings => 'Đánh giá';

  @override
  String get newTracksRatingsSubtitle => 'Tạo ra các bản nhạc có xếp hạng cụ thể';

  @override
  String get newTracksRecommended => 'Khuyến khích';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Tạo ra các bản nhạc bạn thường nghe $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Ngày phát hành tương tự';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Tạo ra các bản nhạc được phát hành cùng thời điểm với $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Bài hát không rõ năm';

  @override
  String get newest => 'Mới nhất';

  @override
  String get next => 'Tiếp theo';

  @override
  String get no => 'Không';

  @override
  String get noChangesFound => 'Không có thay đổi nào được tìm thấy.';

  @override
  String get noEnoughTracks => 'Bạn không có nhiều bài hát..';

  @override
  String get noExcludedFolders => 'Bạn không có thư mục loại trừ nào';

  @override
  String get noFolderChosen => 'Bạn chưa chọn thư mục nào';

  @override
  String get noMoodsAvailable => 'Không có tâm trạng nào có sẵn';

  @override
  String get noNetworkAvailableToFetchData => 'Không có mạng để tìm nạp dữ liệu';

  @override
  String get noTracksFound => 'Không có bài hát nào được tìm thấy';

  @override
  String get noTracksFoundBetweenDates => 'Khoảng thời gian này không có bất kỳ bản nhạc nào.';

  @override
  String get noTracksFoundInDirectory => 'Không tìm thấy bài hát nào trong thư mục này';

  @override
  String get noTracksInHistory => 'Bạn không có đủ Bài hát trong lịch sử';

  @override
  String get nonActive => 'Không hoạt động';

  @override
  String get nonFavourites => 'Không yêu thích';

  @override
  String get none => 'Không có';

  @override
  String get normalizeAudio => 'Chuẩn hóa âm thanh';

  @override
  String get normalizeAudioSubtitle => 'Chuẩn hóa âm lượng bằng cách đọc thẻ tag phát lại hoặc thông tin do youtube cung cấp';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Lưu ý';

  @override
  String get notification => 'Thông báo';

  @override
  String get notifications => 'Thông báo';

  @override
  String get numberOfTracks => 'Số lượng bài hát';

  @override
  String get ofLabel => 'của';

  @override
  String get offlineSearch => 'Tìm kiếm ngoại tuyến';

  @override
  String get offset => 'Bù lại';

  @override
  String get oldDirectory => 'Thư mục cũ';

  @override
  String get oldDirectoryStillHasTracks => 'Thư mục cũ nhưng vẫn còn một số Bài hát, xác nhận?';

  @override
  String get oldestWatch => 'Video cũ nhất';

  @override
  String get onInterruption => 'Khi bị gián đoạn';

  @override
  String get onNotificationTap => 'Khi nhấn vào thông báo';

  @override
  String get onOpeningYoutubeLink => 'Khi mở liên kết Youtube';

  @override
  String get onSwiping => 'Khi vuốt sang một bên';

  @override
  String get onVolumeZero => 'Khi âm lượng còn 0%';

  @override
  String get ongoing => 'Đang diễn ra';

  @override
  String get open => 'Mở';

  @override
  String get openApp => 'Mở ứng dụng';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Mở trong chế độ xem Youtube';

  @override
  String get openMiniplayer => 'Mở trình phát thu nhỏ';

  @override
  String get openQueue => 'Mở hàng đợi';

  @override
  String get openYoutubeLink => 'Mở liên kết Youtube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Thao tác $name yêu cầu tài khoản, Đăng nhập để tiếp tục';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Hoạt động $operation yêu cầu ít nhất thành viên $name';
  }

  @override
  String get or => 'hoặc';

  @override
  String get others => 'Cái khác';

  @override
  String get output => 'Đầu ra';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Ghi đè tập tin cũ trong cùng thư mục';

  @override
  String get palette => 'Bảng màu';

  @override
  String get paletteMix => 'Pha trộn';

  @override
  String get paletteNewMix => 'Hỗn hợp mới';

  @override
  String get paletteSelectedMix => 'Lựa chọn hỗn hợp';

  @override
  String get parallelDownloads => 'Tải xuống Song song';

  @override
  String get parsed => 'Đã phân tích cú pháp';

  @override
  String get password => 'Password';

  @override
  String get path => 'Đường dẫn đầy đủ của tập tin';

  @override
  String get pause => 'Tạm dừng';

  @override
  String get pauseFadeDuration => 'Thời lượng tạm dừng âm thanh nhỏ/lớn dần';

  @override
  String get pausePlayback => 'Tạm dừng phát lại';

  @override
  String get percentage => 'Phần trăm';

  @override
  String get performanceMode => 'Chế độ Hiệu suất cao';

  @override
  String get performanceNote => 'Có thể ảnh hưởng tới trải nghiệm';

  @override
  String get personalized => 'Cá nhân hóa';

  @override
  String get personalizedRelatedVideos => 'Dành cho bạn';

  @override
  String get personalizedRelatedVideosSubtitle => 'Tắt tính năng này sẽ làm tăng mức sử dụng dữ liệu';

  @override
  String get pickColorsFromDeviceWallpaper => 'Chọn màu từ hình nền của thiết bị';

  @override
  String get pickFromStorage => 'Chọn từ Bộ nhớ';

  @override
  String get pinned => 'Đã ghim';

  @override
  String get pitch => 'Cao độ';

  @override
  String get plain => 'Đơn giản';

  @override
  String get play => 'Phát';

  @override
  String get playAfter => 'Phát lại sau';

  @override
  String get playAfterNextPrev => 'Tự động phát Tiếp theo/Trước đó';

  @override
  String get playAll => 'Phát tất cả';

  @override
  String get playFadeDuration => 'Thời lượng âm thanh nhỏ/lớn khi phát';

  @override
  String get playLast => 'Phát lại cuối cùng';

  @override
  String get playNext => 'Phát bài tiếp theo';

  @override
  String get playbackSetting => 'Phát lại';

  @override
  String get playbackSettingSubtitle => 'Có thể truy cập trực tiếp trong trình phát bằng cách nhấn và giữ nút âm thanh';

  @override
  String get playlist => 'Danh sách phát';

  @override
  String get playlists => 'Danh sách phát';

  @override
  String get playlistsImportM3uNative => 'Điều này sẽ nhập danh sách phát M3U chỉ namida sử dụng, hãy sử dụng nếu bạn đang di chuyển';

  @override
  String get playlistsImportM3uSynced =>
      'Các danh sách phát M3U từ các thư mục chỉ mục sẽ được tự động nhập và đồng bộ với tệp M3U gốc. Chỉ bật nếu bạn truy cập/chỉnh sửa danh sách phát từ các ứng dụng khác';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Tự động nhập Danh sách phát M3U';

  @override
  String get pleaseEnterADifferentName => 'Tên này đã tồn tại :(\n hãy thử một cái tên lạ khác';

  @override
  String get pleaseEnterALink => 'Vui lòng nhập đường liên kết';

  @override
  String get pleaseEnterALinkSubtitle => 'ừm.. đây có phải là liên kết youtube không?';

  @override
  String get pleaseEnterAName => 'Vui lòng nhập tên';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Ngăn chặn các bản nhạc trùng lặp';

  @override
  String get preventDuplicatedTracksSubtitle => 'Sử dụng tên tệp để xác định các bản nhạc';

  @override
  String get preview => 'Xem trước';

  @override
  String get previous => 'Trở về';

  @override
  String get previousButtonReplays => 'Phát lại nút trước';

  @override
  String get previousButtonReplaysSubtitle => 'Nếu được nhấn trong khi vị trí hiện tại dài hơn thời lượng tìm kiếm';

  @override
  String get prioritizeEmbeddedLyrics => 'Ưu tiên lời bài hát được nhúng';

  @override
  String get priority => 'Ưu tiên';

  @override
  String get private => 'Riêng tư';

  @override
  String get progress => 'Tiến độ';

  @override
  String get promptToChangeTrackPath => 'Thông thường điều này xảy ra khi bạn xóa/di chuyển/đổi tên tệp bên ngoài Namida. Bạn có muốn cập nhật đường dẫn hiện tại không?';

  @override
  String get public => 'Công khai';

  @override
  String get queue => 'Hàng đợi';

  @override
  String get queues => 'Hàng đợi';

  @override
  String get random => 'Ngẫu nhiên';

  @override
  String get randomPicks => 'Chọn ngẫu nhiên';

  @override
  String get rating => 'Đánh giá';

  @override
  String get reIndex => 'Xây dựng lại chỉ mục';

  @override
  String get reIndexSubtitle => 'Xây dựng lại thư viện nhạc của bạn từ đầu';

  @override
  String get reIndexWarning => 'Quá trình này có thể mất một lúc, tùy thuộc vào kích thước thư viện của bạn.\n\nCác bìa sẽ không được lập chỉ mục lại miễn là chúng vẫn tồn tại';

  @override
  String get recentAlbums => 'Album gần đây';

  @override
  String get recentArtists => 'Nghệ sĩ gần đây';

  @override
  String get recentListens => 'Lượt nghe gần đây';

  @override
  String get recentlyAdded => 'Được thêm gần đây';

  @override
  String get recordLabel => 'Hãng thu âm';

  @override
  String get refresh => 'Làm mới';

  @override
  String get refreshLibrary => 'Làm mới thư viện';

  @override
  String get refreshLibrarySubtitle => 'Kiểm tra những bài nhạc mới được thêm hoặc bị xóa';

  @override
  String get refreshOnStartup => 'Làm mới khi khởi động';

  @override
  String get relatedVideos => 'Video liên quan';

  @override
  String get rememberAudioOnlyMode => 'Ghi nhớ chế độ chỉ có âm thanh';

  @override
  String get remixer => 'Phối lại';

  @override
  String get remove => 'Loại bỏ';

  @override
  String get removeDuplicates => 'Loại bỏ các bản trùng lặp';

  @override
  String get removeFromFavourites => 'Loại bỏ khỏi mục ưa thích';

  @override
  String get removeFromLibrary => 'xóa danh sách phát youtube khỏi thư viện/danh sách phát trực tuyến của bạn';

  @override
  String get removeFromPlaylist => 'Loại bỏ khỏi Danh sách phát';

  @override
  String get removeQueue => 'Loại bỏ khỏi hàng chờ';

  @override
  String get removeSourceFromHistory => 'Loại bỏ nguồn khỏi lịch sử';

  @override
  String get removeWhitespaces => 'Loại bỏ các khoảng trắng';

  @override
  String get removed => 'Đã loại bỏ';

  @override
  String get rename => 'Đổi tên';

  @override
  String get renamePlaylist => 'Đổi tên danh sách phát';

  @override
  String get reorderable => 'Sắp xếp lại';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Lặp lại thêm $number lần nữa',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Lặp lại';

  @override
  String get repeatModeAll => 'Lặp lại tất cả trong Hàng chờ';

  @override
  String get repeatModeNone => 'Dừng lại ở bài hát cuối cùng';

  @override
  String get repeatModeOne => 'Lặp lại bài hát hiện tại';

  @override
  String get replaceAllListensWithAnotherTrack => 'Thay thế tất cả các bài nghe bằng một bài hát khác';

  @override
  String get replies => 'Đáp lại';

  @override
  String get reply => 'Trả lời';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Yêu cầu xóa bộ nhớ đệm hình ảnh và lập chỉ mục';

  @override
  String get rescanVideos => 'Quét lại video';

  @override
  String get resetBrightness => 'Khôi phục độ sáng về mặc định';

  @override
  String get resetToDefault => 'Đặt thành';

  @override
  String get respectNoMedia => 'Chú ý .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Không bao gồm các thư mục có .nomedia';

  @override
  String get restart => 'Khởi động lại';

  @override
  String get restoreBackup => 'Khôi phục sao lưu';

  @override
  String get restoreDefaults => 'Khôi phục về mặc định';

  @override
  String get restoredBackupSuccessfully => 'Khôi phục bản sao lưu';

  @override
  String get restoredBackupSuccessfullySub => 'Tập tin sao lưu đã được khôi phục thành công';

  @override
  String get resume => 'Tiếp tục';

  @override
  String get resumeIfWasInterrupted => 'Tiếp tục nếu bị tạm dừng do gián đoạn';

  @override
  String get resumeIfWasPausedByVolume => 'Tiếp tục nếu bị tạm dừng bởi âm lượng';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Tiếp tục nếu bị tạm dừng dưới $numberString phút',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Đảo ngược';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Nhạc chuông';

  @override
  String get sameDirectoryOnly => 'Chỉ cùng một thư mục';

  @override
  String get sample => 'Mẫu';

  @override
  String get sampleRate => 'Tốt độ lấy mẫu';

  @override
  String get save => 'Lưu';

  @override
  String get saveToLibrary => 'lưu danh sách phát youtube vào thư viện/danh sách phát trực tuyến của bạn';

  @override
  String get savedIn => 'Lưu trong';

  @override
  String get scaleMultiplier => 'Nhân tỷ lệ kích thước Bìa nhạc';

  @override
  String get search => 'Tìm kiếm';

  @override
  String get searchYoutube => 'Tìm kiếm Youtube';

  @override
  String get seconds => 'Giây';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Thời lượng tìm kiếm';

  @override
  String get seekDurationInfo => 'Bạn có thể nhấn vào thời lượng hiện tại để lùi về phía sau và tổng thời lượng để tiến về phía trước';

  @override
  String get seekbar => 'Thanh tìm kiếm';

  @override
  String get selectAll => 'Chọn tất cả';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Chọn tệp tin có sẵn trong thư viện thiết bị';

  @override
  String get selectedTracks => 'Đã chọn bài hát';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Những từ này sẽ không bị chia cắt';

  @override
  String get separatorsMessage => 'Không cần chèn dấu cách, trừ khi bạn muốn sử dụng một chữ cái/ký hiệu có thể tìm thấy trong cả một từ (như x và ft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Đặt làm';

  @override
  String get setAsDefault => 'Đặt làm mặc định';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Đặt tệp được sửa đổi lần cuối làm ngày tải lên video';

  @override
  String get setMoods => 'Đặt tâm trạng';

  @override
  String get setMoodsSubtitle => 'Dùng dấu phẩy (,) để phân cách giữa chúng';

  @override
  String get setRating => 'Đặt đánh giá';

  @override
  String get setTags => 'Đặt thẻ';

  @override
  String get setYoutubeLink => 'Đặt liên kết Youtube';

  @override
  String get settings => 'Cài đặt';

  @override
  String get setupFirstStartup => 'Thiết lập lần khởi động đầu tiên';

  @override
  String get share => 'Chia sẻ';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Lối tắt';

  @override
  String get shouldDuck => 'Nên giảm âm lượng';

  @override
  String get shouldDuckNote => 'Cho biết âm lượng nên được giảm xuống. ví dụ: thông báo';

  @override
  String get shouldPause => 'Nên tạm dừng';

  @override
  String get shouldPauseNote => 'Cho biết rằng việc phát lại sẽ bị tạm dừng. ví dụ: cuộc gọi';

  @override
  String get showAll => 'Hiển thị tất cả';

  @override
  String get showChannelWatermarkInFullscreen => 'Hiển thị hình mờ kênh ở chế độ toàn màn hình';

  @override
  String get showFailedOnly => 'Chỉ hiển thị tải thất bại';

  @override
  String get showHideUnknownFields => 'Hiển thị/ẩn các trường không xác định';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Hiển thị Bản mix';

  @override
  String get showMore => 'Xem thêm';

  @override
  String get showShortVideosIn => 'Hiển thị video ngắn ở';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'thẻ kết thúc hoặc màn hình kết thúc cho video youtube';

  @override
  String get showWebm => 'Hiển thị webm';

  @override
  String get shuffle => 'Xáo trộn';

  @override
  String get shuffleAll => 'Xáo trộn tất cả';

  @override
  String get shuffleNext => 'Xáo trộn tiếp theo';

  @override
  String get signIn => 'Đăng nhập';

  @override
  String get signInCanceled => 'Đăng nhập đã bị hủy bỏ';

  @override
  String get signInFailed => 'Đăng nhập thất bại';

  @override
  String get signInToYourAccount => 'Đăng nhập tài khoản của bạn';

  @override
  String get signInYouDontHaveAccount => 'Bạn chưa có tài khoản nào đăng nhập';

  @override
  String get signInYouNeedAccountToViewPage => 'Bạn cần có tài khoản để xem trang này';

  @override
  String get signOut => 'Đăng xuất';

  @override
  String signOutFromName({required String name}) {
    return 'Đăng xuất khỏi $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Đăng nhập cho phép sử dụng cơ bản';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Nhận quyền truy cập sớm thông qua Patreon hoặc bằng cách sử dụng phiếu giảm giá';

  @override
  String get similarDiscoverDate => 'Cùng ngày nghe';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Phát nhạc nghe cùng thời điểm với $currentTrack';
  }

  @override
  String get similarTimeRange => 'Cùng thời điểm';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Những bản nhạc nghe cùng thời điểm với $currentTrack';
  }

  @override
  String get singles => 'Đĩa đơn';

  @override
  String get size => 'Kích thước';

  @override
  String get skip => 'Bỏ qua';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Bỏ qua trong im lặng';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Ngủ sau khi';

  @override
  String get sleepTimer => 'Thời gian ngủ';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Sắp xếp theo';

  @override
  String get source => 'Nguồn';

  @override
  String get speed => 'Tốc độ';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Chế độ xem lưới album';

  @override
  String get start => 'Bắt đầu';

  @override
  String get stats => 'Số liệu thống kê';

  @override
  String get statsSubtitle => 'Đây là một số thông tin về thư viện của bạn';

  @override
  String get stop => 'Dừng lại';

  @override
  String get stopAfterThisTrack => 'Dừng lại sau bài hát này';

  @override
  String get stopAfterThisVideo => 'Dừng lại sau video này';

  @override
  String get storagePermissionDenied => 'Quyền bị từ chối';

  @override
  String get storagePermissionDeniedSubtitle => 'Vui lòng cấp phép truy cập để có thể thực hiện hành động này';

  @override
  String get stretchLyricsDuration => 'Thời lượng giãn lời bài hát';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Đăng ký';

  @override
  String get subscribed => 'Đã đăng ký';

  @override
  String get subscriber => 'Người đăng ký';

  @override
  String get subscribers => 'Người đăng ký';

  @override
  String get succeeded => 'Đã thành công';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Hỗ trợ';

  @override
  String get supremacy => 'Quyền cao';

  @override
  String get sussyBaka => 'Bruh không có bài hát nào';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Vuốt để mở bảng điều hướng';

  @override
  String get synced => 'Đã đồng bộ';

  @override
  String get synopsis => 'Tóm tắt';

  @override
  String get tagFields => 'Trường gắn thẻ';

  @override
  String get tags => 'Thẻ';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Nhấn để tìm kiếm';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Chủ đề';

  @override
  String get themeModeDark => 'Tối';

  @override
  String get themeModeLight => 'Sáng';

  @override
  String get themeModeSystem => 'Hệ thống';

  @override
  String get themeSettings => 'Chủ đề';

  @override
  String get themeSettingsSubtitle => 'Điều chỉnh trình phát nhạc theo tâm trạng mà bạn muốn';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Vui lòng tắt bộ sắp xếp của danh sách này trước khi chỉnh sửa.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Video này đã bị xóa hoặc đặt trong chế độ riêng tư.';

  @override
  String get thumbnails => 'Hình thủ nhỏ';

  @override
  String get title => 'Tiêu đề';

  @override
  String get top => 'Đầu';

  @override
  String get topComments => 'Bình luận hàng đầu';

  @override
  String get topCommentsSubtitle => 'Hiển thị bình luận ở trên cùng thay vì ở dưới cùng';

  @override
  String get topRecentAlbums => 'Album gần đây nhất';

  @override
  String get topRecentArtists => 'Nghệ sĩ gần đây nhất';

  @override
  String get topRecents => 'Gần đây nhất';

  @override
  String get totalListenTime => 'Tổng thời gian nghe';

  @override
  String get totalListens => 'Tổng số lượt nghe';

  @override
  String get totalTracks => 'Tổng số bài hát';

  @override
  String get totalTracksDuration => 'Tổng thời lượng bài hát';

  @override
  String get track => 'Bài hát';

  @override
  String get trackArtistsSeparator => 'Dấu phân cách nghệ sĩ';

  @override
  String get trackGenresSeparator => 'Dấu phân cách thể loại';

  @override
  String get trackInfo => 'Thông tin bài hát';

  @override
  String get trackNotFound => 'Không tìm thấy bài hát';

  @override
  String get trackNumber => 'Số lượng bài hát';

  @override
  String get trackNumberTotal => 'Tổng số bài hát';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Tên cũ: \"$oldName\"\n\nTên mới: \"$newName\"\n\nBạn có chắc không?';
  }

  @override
  String get trackPlayMode => 'Chế độ phát';

  @override
  String get trackPlayModeSearchResults => 'Kết quả tìm kiếm';

  @override
  String get trackPlayModeSelectedOnly => 'Chỉ bài hát đã chọn';

  @override
  String get trackPlayModeTrackAlbum => 'Album của bài hát';

  @override
  String get trackPlayModeTrackArtist => 'Nghệ sĩ chính của ca khúc';

  @override
  String get trackPlayModeTrackGenre => 'Thể loại bài hát';

  @override
  String get trackThumbnailSizeInList => 'Kích thước của hình thu nhỏ bài hát';

  @override
  String get trackTileCustomization => 'Tùy chỉnh ô theo dõi';

  @override
  String get trackTileItemsSeparator => 'Dấu cách phân mục';

  @override
  String get tracks => 'Bài hát';

  @override
  String get tracksExcludedByNomedia => 'Các bài hát bị loại trừ bởi .nomedia';

  @override
  String get tracksInfo => 'Thông tin bài hát';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Hoàn tác';

  @override
  String get undoChanges => 'Hoàn tác các thay đổi?';

  @override
  String get undoChangesDeletedPlaylist => 'Hoàn tác danh sách phát đã xóa';

  @override
  String get undoChangesDeletedQueue => 'Hoàn tác hàng đợi đã xóa';

  @override
  String get undoChangesDeletedTrack => 'Hoàn tác bài hát đã xóa';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Không giới hạn';

  @override
  String get unlisted => 'Không công khai';

  @override
  String get unlock => 'Mở khóa';

  @override
  String get update => 'Cập nhật';

  @override
  String get updateDirectoryPath => 'Cập nhật đường dẫn thư mục';

  @override
  String get updateMissingTracksOnly => 'Chỉ cập nhật các bài hát còn thiếu';

  @override
  String get updating => 'Đang cập nhật';

  @override
  String get useCollapsedSettingTiles => 'Sử dụng ô cài đặt thu gọn';

  @override
  String get useMediaStore => 'Sử dụng kho phương tiện';

  @override
  String get useMediaStoreSubtitle =>
      '✓ thời gian lập chỉ mục ngay lập tức\nx chú ý .nomedia sẽ được kích hoạt bắt buộc\nx một số thẻ siêu dữ liệu sẽ bị thiếu\nx tích hợp Youtube cho thư viện cục bộ sẽ không hoạt động';

  @override
  String get usePitchBlack => 'Sử dụng nền đen cực tối';

  @override
  String get usePitchBlackSubtitle => 'Hữu ích cho màn hình AMOLED.. và trông ngầu hơn';

  @override
  String get used => 'Đã sử dụng';

  @override
  String get value => 'Giá trị';

  @override
  String get valueBetween50200 => 'Giá trị nằm trong khoảng từ 50% đến 200%';

  @override
  String get vibration => 'Rung thiết bị';

  @override
  String get vibrationType => 'Chế độ rung';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Bộ nhớ đệm Video';

  @override
  String get videoCacheFile => 'Tệp video được lưu trong bộ nhớ đệm';

  @override
  String get videoCacheFiles => 'Tệp video được lưu trong bộ nhớ đệm';

  @override
  String get videoOnly => 'Mỗi Video';

  @override
  String get videoPlaybackSource => 'Nguồn Video';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Việc này sẽ ưu tiên cho các video cục bộ, nếu không tìm thấy thì nó sẽ tìm nạp từ Youtube';

  @override
  String get videoPlaybackSourceLocal => 'Video cục bộ';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Ví dụ : Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Kiểm tra bất kỳ tệp video nào (được tìm thấy trong danh sách thư mục đã chọn) có tên tệp chứa tên tệp của bản nhạc hay không';

  @override
  String get videoPlaybackSourceYoutube => 'Từ Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Kiểm tra tên tệp và nhận xét của bài hát để tìm bất kỳ liên kết Youtube phù hợp nào, video sẽ được lưu vào bộ nhớ đệm để sử dụng sau.';

  @override
  String get videoQuality => 'Chất lượng Video';

  @override
  String get videoQualitySubtitle => 'Chất lượng cao nhất có sẵn sẽ được chọn.';

  @override
  String get videoQualitySubtitleNote =>
      'Luôn tốt nếu có nhiều lựa chọn thay thế hơn trong trường hợp không tìm thấy chất lượng phù hợp, nếu không nó sẽ chuyển sang chất lượng kém nhất';

  @override
  String get videos => 'Videos';

  @override
  String get view => 'Lượt xem';

  @override
  String get viewAll => 'Xem tất cả';

  @override
  String get views => 'Lượt xem';

  @override
  String get volume => 'Âm lượng';

  @override
  String get warning => 'Cảnh báo';

  @override
  String get waveformBarsCount => 'Số thanh dạng sóng';

  @override
  String get webmNoEditTagsSupport => 'Định dạng WebM không hỗ trợ chỉnh sửa thẻ';

  @override
  String get week => 'Tuần';

  @override
  String get year => 'Năm';

  @override
  String get yes => 'Đúng';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Thành viên hiện tại của bạn là $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Thứ tự sắp xếp của bạn sẽ mất, bạn chắc chứ?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Music';

  @override
  String get youtubeSettingsSubtitle => 'Tùy chỉnh trải nghiệm Youtube';

  @override
  String get youtubeStyleMiniplayer => 'Trình phát thu nhỏ theo phong cách Youtube';

  @override
  String get ytPreferNewComments => 'Thích những bình luận mới khi có thể';

  @override
  String get ytPreferNewCommentsSubtitle => 'Bộ nhớ đệm của Phiên bản đã lưu sẽ được sử dụng khi không có kết nối';
}
