// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Bosnian (`bs`).
class AppLocalizationsBs extends AppLocalizations {
  AppLocalizationsBs([String locale = 'bs']) : super(locale);

  @override
  String get about => 'O aplikaciji';

  @override
  String get active => 'Aktivno';

  @override
  String get add => 'Dodaj';

  @override
  String get addAccount => 'Dodaj račun';

  @override
  String get addAll => 'Dodaj sve';

  @override
  String get addAllAndRemoveOldOnes => 'Dodaj sve i ukloni stare';

  @override
  String get addAsANewPlaylist => 'Dodaj kao novu listu';

  @override
  String get addAudioToLocalLibrary => 'Dodaj zvuk u moju zbirku';

  @override
  String get addFolder => 'Dodaj direktorij';

  @override
  String get addLanguage => 'Dodaj jezik';

  @override
  String get addLanguageSubtitle => 'Pomozite u prevođenju Namide na Vaš jezik';

  @override
  String get addLrcFile => 'Dodaj LRC datoteku';

  @override
  String get addMoreFromThisAlbum => 'Dodaj više s ovog albuma u red čekanja';

  @override
  String get addMoreFromThisArtist => 'Dodaj više od ovog izvođača u red čekanja';

  @override
  String get addMoreFromThisFolder => 'Dodaj više iz ove fascikle u red čekanja';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Dodaj više iz $media u red čekanja';
  }

  @override
  String get addOnlyMissing => 'Dodaj samo nedostajuće';

  @override
  String get addToFavourites => 'Dodaj u omiljene';

  @override
  String get addToPlaylist => 'Dodaj na listu';

  @override
  String get addTracksAtTheBeginning => 'Dodaj pjesme na početak';

  @override
  String get added => 'Dodano';

  @override
  String get advanced => 'Napredno';

  @override
  String get advancedSettings => 'Napredno';

  @override
  String get advancedSettingsSubtitle => 'Napredne postavke, ne dirajte ako niste sigurni šta radite';

  @override
  String get alarm => 'Budilnik';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Izvođač albuma';

  @override
  String get albumArtists => 'Izvođači albuma';

  @override
  String get albumIdentifiers => 'Identifikatori albuma';

  @override
  String get albumThumbnailSizeInList => 'Veličina sličice albuma';

  @override
  String get albumTileCustomization => 'Prilagođavanje pločice albuma';

  @override
  String get albums => 'Albumi';

  @override
  String get albumsCount => 'Broj albuma';

  @override
  String get all => 'Sve';

  @override
  String get allTime => 'Sve vrijeme';

  @override
  String get alreadyExists => 'Već postoji';

  @override
  String get always => 'Uvijek';

  @override
  String get alwaysAsk => 'Uvijek pitaj';

  @override
  String get alwaysDim => 'Uvijek zatamni';

  @override
  String get alwaysExpandedSearchbar => 'Uvijek proširena traka za pretraživanje';

  @override
  String get alwaysRestore => 'Uvijek vrati';

  @override
  String get animatingThumbnailIntensity => 'Intenzitet animacije sličice';

  @override
  String get animatingThumbnailInversed => 'Obrnute animacije';

  @override
  String get animatingThumbnailInversedSubtitle => 'Visoki tonovi će smanjiti sličicu';

  @override
  String get anotherProcessIsRunning => 'Drugi proces je već pokrenut.';

  @override
  String get appIcon => 'Ikona aplikacije';

  @override
  String get appVersion => 'Izdanje aplikacije';

  @override
  String get artist => 'Izvođač';

  @override
  String get artists => 'Izvođači';

  @override
  String get artwork => 'Omot';

  @override
  String get artworkGestures => 'Pokreti na omotu';

  @override
  String get artworks => 'Omoti';

  @override
  String get audio => 'Zvuk';

  @override
  String get audioCache => 'Predmemorija zvuka';

  @override
  String get audioOnly => 'Samo zvuk';

  @override
  String get auto => 'Automatski';

  @override
  String get autoBackupInterval => 'Interval automatske rezervne kopije';

  @override
  String get autoColoring => 'Automatsko bojenje';

  @override
  String get autoColoringSubtitle => 'Automatski odaberi boje plejera iz trenutnog omota';

  @override
  String get autoExtractTagsFromFilename => 'Automatski izdvoj iz naziva datoteke';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Automatski izdvoj naslov i izvođača iz naslova videa';

  @override
  String get autoGenerated => 'Automatski generisano';

  @override
  String get autoSkip => 'Automatsko preskakanje';

  @override
  String get autoSkipOnce => 'Automatski preskoči jednom';

  @override
  String get autoStartRadio => 'Automatski pokreni radio';

  @override
  String get autoStartRadioSubtitle => 'Automatski dodaje miks listu kada se pusti jedna numera';

  @override
  String get automaticBackup => 'Automatski backup';

  @override
  String get automaticBackupSubtitle => 'Automatski primjenjuje najnoviju datoteku rezervne kopije pronađenu na lokaciji';

  @override
  String get backupAndRestore => 'Rezervna kopija i vraćanje';

  @override
  String get backupAndRestoreSubtitle => 'Napravite rezervnu kopiju baze podataka i postavki';

  @override
  String get balanced => 'Uravnoteženo';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Između datuma';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Crna lista';

  @override
  String get borderRadiusMultiplier => 'Množitelj zaobljenosti ivica';

  @override
  String get cache => 'Predmemorija';

  @override
  String get cancel => 'Otkaži';

  @override
  String get canceled => 'Otkazano';

  @override
  String get changed => 'Promijenjeno';

  @override
  String get changelog => 'Dnevnik promjena';

  @override
  String get changelogSubtitle => 'Pogledajte šta je novo dodano/ispravljeno u Namidi';

  @override
  String get channel => 'Kanal';

  @override
  String get channels => 'Kanali';

  @override
  String get check => 'Provjeri';

  @override
  String get checkForMore => 'Provjeri još';

  @override
  String get checkList => 'Upravljačka lista';

  @override
  String get choose => 'Odaberi';

  @override
  String get chooseWhatToClear => 'Odaberi šta je za očistiti';

  @override
  String get claim => 'Zatraži';

  @override
  String get clear => 'Očisti';

  @override
  String get clearAudioCache => 'Očisti predmemoriju zvuka';

  @override
  String get clearImageCache => 'Očisti predmemoriju slika';

  @override
  String get clearImageCacheWarning => 'Upozorenje: ovo će rezultirati bibliotekom bez slika. Koristite samo za ponovnu izgradnju predmemorije slika.';

  @override
  String get clearTrackItem => 'Očisti za numeru';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Očisti za $numberString numera',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Očisti predmemoriju videa';

  @override
  String get clearVideoCacheNote => 'Možete odabrati šta želite izbrisati.';

  @override
  String get clock => 'Sat';

  @override
  String get colorPalette => 'Paleta boja';

  @override
  String get colorPaletteNote1 => 'Dugo pritisnite boju da je uklonite';

  @override
  String get colorPaletteNote2 => 'Dodirnite miks da ga koristite kao zadanu boju';

  @override
  String get colorPalettes => 'Palete boja';

  @override
  String get comment => 'Komentar';

  @override
  String get comments => 'Komentari';

  @override
  String get composer => 'Kompozitor';

  @override
  String get compress => 'Sažmi';

  @override
  String get compressImages => 'Sažmi slike';

  @override
  String get compressionPercentage => 'Postotak sažimanja';

  @override
  String get configure => 'Konfiguriši';

  @override
  String get confirm => 'Potvrdi';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'Kopiran omot';

  @override
  String get copiedToClipboard => 'Kopirano u međuspremnik';

  @override
  String get copy => 'Kopiraj';

  @override
  String get corruptedFile => 'Nije moguće parsirati datoteku, možda je oštećena';

  @override
  String get couldntOpen => 'Nije moguće otvoriti :(';

  @override
  String get couldntOpenYtLink => 'Nema YouTube linka za ovu numeru';

  @override
  String get couldntPlayFile => 'Nije moguće reproducirati datoteku';

  @override
  String get couldntRenamePlaylist => 'Nije moguće preimenovati listu numera';

  @override
  String get couldntSaveImage => 'Nije moguće sačuvati sliku';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Država';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Stvori';

  @override
  String get createBackup => 'Kreiraj rezervnu kopiju';

  @override
  String get createNewPlaylist => 'Kreiraj novu listu numera';

  @override
  String get createdBackupSuccessfully => 'Rezervna kopija kreirana';

  @override
  String get createdBackupSuccessfullySub => 'Datoteka rezervne kopije je uspješno kreirana';

  @override
  String get crossPlatformSync => 'Međuplatformskl usklađivanje';

  @override
  String get crossfadeDuration => 'Trajanje pretapanja';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Automatski pokreni pretapanje u posljednjih $secondsString sekundi',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Ne pokreći pretapanje automatski';

  @override
  String get custom => 'Prilagođeno';

  @override
  String get customizations => 'Prilagođavanja';

  @override
  String get customizationsSubtitle => 'Prilagodite izgled plejera, učinite ga svojim';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Podatke osigurava: $name';
  }

  @override
  String get dataSaver => 'Ušteda podataka';

  @override
  String get dataSaverMode => 'Režim uštede podataka';

  @override
  String get database => 'Baza podataka';

  @override
  String get date => 'Datum';

  @override
  String get dateAdded => 'Datum dodavanja';

  @override
  String get dateCreated => 'Datum kreiranja';

  @override
  String get dateModified => 'Datum izmjene';

  @override
  String get dateTimeFormat => 'Format datuma i vremena';

  @override
  String get day => 'Dan';

  @override
  String get days => 'Dana';

  @override
  String get defaultBackupLocation => 'Zadana lokacija rezervne kopije';

  @override
  String get defaultColor => 'Zadana boja';

  @override
  String get defaultColorSubtitle => 'Postavite boju koju će koristiti plejer';

  @override
  String get defaultDownloadLocation => 'Zadana lokacija preuzimanja';

  @override
  String get defaultLabel => 'Zadano';

  @override
  String get defaultLibraryTab => 'Zadana kartica biblioteke';

  @override
  String get delete => 'Izbriši';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Izbrisati $countString datoteku/a ukupne veličine $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Trajno izbrisati $numberText iz pohrane';
  }

  @override
  String get deletePlaylist => 'Izbriši listu numera';

  @override
  String get deleteTempFiles => 'Izbriši privremene datoteke';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Opis';

  @override
  String get developer => 'Razvijalac';

  @override
  String get development => 'Razvoj';

  @override
  String get didYouMean => 'Jeste li mislili';

  @override
  String get dimIntensity => 'Intenzitet zatamnjenja';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Zatamni mini-plejer nakon $secondsString sekunde/i neaktivnosti',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Direktorij ne postoji';

  @override
  String get disable => 'Onemogući';

  @override
  String get disableAll => 'Onemogući sve';

  @override
  String get disableReordering => 'Onemogući promjenu redoslijeda';

  @override
  String get disableSearchCleanup => 'Onemogući čišćenje pretrage';

  @override
  String get discNumber => 'Broj diska';

  @override
  String get discNumberTotal => 'Ukupno diskova';

  @override
  String get discover => 'Otkrij novitete';

  @override
  String get dislike => 'Ne sviđa mi se';

  @override
  String get dismissibleMiniplayer => 'Uklonjiv mini-plejer';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Prikaži stvarnu poziciju umjesto razlike tokom traženja';

  @override
  String get displayAlbumCardTopRightDate => 'Datum u gornjem desnom uglu kartice albuma';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Prikaži datum albuma u gornjem desnom uglu';

  @override
  String get displayArtistBeforeTitle => 'Prikaži izvođača prije naslova';

  @override
  String get displayArtworkOnLockscreen => 'Prikaži omot na zaključanom ekranu';

  @override
  String get displayAudioInfoInMiniplayer => 'Prikaži informacije o zvuku';

  @override
  String get displayFavButtonInNotification => 'Prikaži dugme za omiljene u obavijestima';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Sličica se može pomjeriti.';

  @override
  String get displayFavouriteIconInTrackTile => 'Prikaži dugme za omiljene';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Prikaži preostalo trajanje umjesto ukupnog';

  @override
  String get displayStopButtonInNotification => 'Prikaži dugme za zaustavljanje u obavijestima';

  @override
  String get displayThirdItemInRowInTrackTile => 'Prikaži treću stavku u svakom redu';

  @override
  String get displayThirdRowInTrackTile => 'Prikaži treći red';

  @override
  String get displayTrackNumberInAlbumPage => 'Prikaži broj numere na stranici albuma';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Prikaži mali okvir s brojem numere na stranici albuma';

  @override
  String get doNothing => 'Ne radi ništa';

  @override
  String get donate => 'Podrži nas';

  @override
  String get donateSubtitle => 'ako mislite da je zasluženo';

  @override
  String get done => 'Gotovo';

  @override
  String get dontAskAgain => 'Ne pitaj ponovo';

  @override
  String get dontDim => 'Ne zatamnjuj';

  @override
  String get dontRestorePosition => 'Ne vraćaj';

  @override
  String get dontResume => 'Ne nastavljaj';

  @override
  String get doubleTapToToggleLyrics => 'Dvaput dodirnite za prikaz teksta pjesme';

  @override
  String get download => 'Preuzmi';

  @override
  String get downloadingWillOverrideIt => 'Preuzimanje će ga zamijeniti';

  @override
  String get downloads => 'Preuzimanja';

  @override
  String get downloadsMetadataTags => 'Oznake metapodataka preuzimanja';

  @override
  String get downloadsMetadataTagsSubtitle => 'Zadano izvlači izvođača, naslov i album iz informacija videa';

  @override
  String get dragToSeek => 'Povuci za traženje';

  @override
  String get duckAudio => 'Utišaj zvuk';

  @override
  String get duplicatedItemsAdding => 'Pokušavate dodati stavke koje već postoje u ovoj listi';

  @override
  String get duplicatedTracks => 'Duplicirane numere';

  @override
  String get duration => 'Trajanje';

  @override
  String get edgeColorsSwitching => 'Prebacivanje boja ivica';

  @override
  String get edit => 'Uredi';

  @override
  String get editArtwork => 'Uredi omot';

  @override
  String get editTags => 'Uredi oznake';

  @override
  String get email => 'E-pošta';

  @override
  String get emptyNonMeaningfulTagFields => 'Imate polja s praznim/besmislenim vrijednostima, provjerite želite li ih zaista urediti';

  @override
  String get emptyValue => 'Prazna vrijednost';

  @override
  String get enableArtworkCache => 'Omogući keširanje omota';

  @override
  String get enableArtworkCacheSubtitle => 'Brže učitavanje i poboljšana brzina, ali koristi više pohrane';

  @override
  String get enableBlurEffect => 'Omogući efekt zamućenja';

  @override
  String get enableBottomNavBar => 'Omogući donju navigacijsku traku';

  @override
  String get enableBottomNavBarSubtitle => 'Stavke su unutar ladice u oba smjera';

  @override
  String get enableClipboardMonitoring => 'Omogući praćenje međuspremnika';

  @override
  String get enableClipboardMonitoringSubtitle => 'Omogućava lijepljenje linkova i teksta unutar trake za pretraživanje u hodu';

  @override
  String get enableCrossfadeEffect => 'Omogući efekt pretapanja';

  @override
  String get enableFadeEffectOnPlayPause => 'Omogući efekt blijeđenja pri reprodukciji/pauziranju';

  @override
  String get enableFoldersHierarchy => 'Omogući hijerarhiju direktorija';

  @override
  String get enableGlowEffect => 'Omogući efekt sjaja';

  @override
  String get enableM3uSync => 'Omogući M3U sinhronizaciju';

  @override
  String get enableM3uSyncNote1 => 'M3U sinhronizacija omogućava spremanje promjena liste numera u originalnu M3U datoteku';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Ako nešto pođe po zlu, rezervna kopija ove liste će se naći u $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Ako se odbije, sve promjene u ovoj listi bit će izgubljene pri ponovnom pokretanju';

  @override
  String get enableMiniplayerParticles => 'Omogući pokretne čestice';

  @override
  String get enableParallaxEffect => 'Omogući paralaks efekt';

  @override
  String get enablePartyMode => 'Omogući Party način';

  @override
  String get enablePartyModeSubtitle => 'Primijeni fensi efekt disanja ivica';

  @override
  String get enablePictureInPicture => 'Omogući slika-u-slici';

  @override
  String get enableReordering => 'Omogući promjenu redoslijeda';

  @override
  String get enableReturnYoutubeDislike => 'Omogući Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Omogući čišćenje pretrage';

  @override
  String get enableSearchCleanupSubtitle => 'Svi simboli i razmaci će biti ignorisani';

  @override
  String get enableSponsorblock => 'Omogući SponsorBlock';

  @override
  String get enableVideoPlayback => 'Omogući video reprodukciju';

  @override
  String get enterSymbol => 'Unesite simbol';

  @override
  String get equalizer => 'Ekvilajzer';

  @override
  String get error => 'Greška';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Greška pri reprodukciji numere';

  @override
  String get excludedFodlers => 'Isključeni direktoriji';

  @override
  String get exit => 'Izlaz';

  @override
  String get exitAppSubtitle => 'Dodirnite ponovo za izlaz';

  @override
  String get expandedMiniplayer => 'Prošireni mini-plejer';

  @override
  String get exportAsM3u => 'Izvezi kao M3U';

  @override
  String get extension => 'Ekstenzija';

  @override
  String get externalFiles => 'Vanjske datoteke';

  @override
  String get extract => 'Izdvoj';

  @override
  String get extractAllColorPalettes => 'Izdvoj sve palete boja';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Izdvojiti preostale $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Izdvoj gostujuće umjetnike iz naslova';

  @override
  String get extractFeatArtistSubtitle => 'Izvlači (feat. X) i (ft. X) umjetnike kao novi unos izvođača.';

  @override
  String get extractingInfo => 'Izvlačenje informacija';

  @override
  String get extras => 'Dodaci';

  @override
  String get extrasSubtitle => 'Dodatne postavke za poboljšanje vašeg iskustva';

  @override
  String get extreme => 'Ekstremno';

  @override
  String get failed => 'Neuspjelo';

  @override
  String get failedEdits => 'Neuspjele izmjene';

  @override
  String get favourites => 'Omiljeni';

  @override
  String get features => 'Mogućnosti';

  @override
  String get fetching => 'Dohvatanje';

  @override
  String get fetchingOfAllVideos => 'Dohvatanje svih videa';

  @override
  String get file => 'Datoteka';

  @override
  String get fileAlreadyExists => 'Datoteka već postoji';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Naziv datoteke';

  @override
  String get fileNameWoExt => 'Naziv datoteke bez ekstenzije';

  @override
  String get filenameShouldntStartWith => 'Naziv datoteke ne bi trebao počinjati sa';

  @override
  String get files => 'Datoteke';

  @override
  String get filler => 'Popuna';

  @override
  String get filterAlbums => 'Filtriraj albume';

  @override
  String get filterArtists => 'Filtriraj izvođače';

  @override
  String get filterGenres => 'Filtriraj žanrove';

  @override
  String get filterPlaylists => 'Filtriraj liste numera';

  @override
  String get filterTracks => 'Filtriraj numere';

  @override
  String get filterTracksBy => 'Filtriraj numere u listama pretrage po';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Numere filtrirane po veličini i trajanju';

  @override
  String get finished => 'Završeno';

  @override
  String get finishedUpdatingLibrary => 'Završeno ažuriranje biblioteke';

  @override
  String get firstListen => 'Prvo slušanje';

  @override
  String get fixYtdlpBigThumbnailSize => 'Popravi veliku veličinu sličice yt-dlp';

  @override
  String get floatingActionButton => 'Plutajuće akcijsko dugme';

  @override
  String get folder => 'Direktorij';

  @override
  String get folderName => 'Naziv direktorija';

  @override
  String get folders => 'Direktoriji';

  @override
  String get fontScale => 'Veličina fonta';

  @override
  String get forceMiniplayerFollowTrackColors => 'Prisili mini-plejer da prati boje numere';

  @override
  String get forceSquaredAlbumThumbnail => 'Prisili kvadratnu sličicu albuma';

  @override
  String get forceSquaredThumbnailNote => 'Veličina sličice i visina pločice NISU jednake, kvadratni izgled neće biti očekivan. Želite li ih izjednačiti?';

  @override
  String get forceSquaredTrackThumbnail => 'Prisili kvadratnu sličicu numere';

  @override
  String get forceStopColorPaletteGeneration => 'Prisilno zaustaviti izvlačenje paleta boja? Možete nastaviti kasnije';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Cijeli ekran';

  @override
  String get gaplessPlayback => 'Reprodukcija bez pauze';

  @override
  String get generate => 'Generiši';

  @override
  String get generateFromDates => 'Vremenski raspon';

  @override
  String get generateFromDatesSubtitle => 'Generiši numere koje ste slušali u vremenskom rasponu';

  @override
  String get generateRandomPlaylist => 'Generiši nasumičnu listu numera';

  @override
  String get genre => 'Žanr';

  @override
  String get genres => 'Žanrovi';

  @override
  String get goToAlbum => 'Idi na album';

  @override
  String get goToArtist => 'Idi na izvođača';

  @override
  String get goToChannel => 'Idi na kanal';

  @override
  String get goToFolder => 'Idi na direktorij';

  @override
  String get goodLooking => 'Izgleda dobro';

  @override
  String get grantStoragePermission => 'Odobri pristup pohrani';

  @override
  String get group => 'Grupa';

  @override
  String get groupArtworksByAlbum => 'Grupiši omote po albumu';

  @override
  String get guide => 'Vodič';

  @override
  String get hapticFeedback => 'Haptička povratna informacija';

  @override
  String get heightOfAlbumTile => 'Visina pločice albuma';

  @override
  String get heightOfTrackTile => 'Visina pločice numere';

  @override
  String get hideSkipButtonAfter => 'Sakrij dugme za preskakanje nakon';

  @override
  String get highMatches => 'Visoka podudaranja';

  @override
  String get highPerformance => 'Visoke performanse';

  @override
  String get highlight => 'Istaknuto';

  @override
  String get history => 'Historija';

  @override
  String get historyImportMissingEntriesNote => 'Ovi unosi nisu pronađeni u biblioteci. Ako vjerujete da postoje, razmislite o ručnom dodavanju';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString slušanja za $oldTrackInfo bit će zamijenjeno sa $newTrackInfo, potvrdi?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Početna';

  @override
  String get hook => 'Refren';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12-satni format';

  @override
  String get hours => 'Sati';

  @override
  String get iReadAndAgree => 'Pročitao sam i slažem se';

  @override
  String get ifNotPlaying => 'Ako ne svira';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Preuzimanja mogu biti usporena kada je aplikacija ograničena baterijom';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignoriši uobičajene prefikse pri sortiranju';

  @override
  String get ignores => 'Ignoriše';

  @override
  String get imageSource => 'Izvor slike';

  @override
  String get immersiveMode => 'Impresivni režim';

  @override
  String get immersiveModeSubtitle => 'Sakrij statusnu i navigacijsku traku dok je mini-plejer proširen';

  @override
  String get import => 'Uvezi';

  @override
  String get importAll => 'Uvezi sve';

  @override
  String get importLastFmHistory => 'Uvezi Last.fm historiju';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Idite na $lastfmCsvLink\n\n2. Unesite svoje korisničko ime, dohvatite i preuzmite CSV datoteku.\n\n3. Odaberite datoteku na sljedećem ekranu.';
  }

  @override
  String get importTimeRange => 'Uvezi vremenski raspon';

  @override
  String get importYoutubeHistory => 'Uvezi YouTube historiju';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Idite na $takeoutLink\n\n2. Pritisnite \"Multiple Formats\" i pored \"History\" odaberite \"JSON\".\n\n3. Pritisnite \"All Youtube data included\", poništite sve i odaberite samo historiju.\n\n4. Kreirajte izvoz, preuzmite i raspakujte.\n\n5. Odaberite \"watch-history.json\" na sljedećem ekranu.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Uspješno uvezeno $numberString kanala',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Uspješno uvezeno $numberText lista numera',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Uključi videe';

  @override
  String get indexRefreshRequired => 'Osvježite nakon promjene ovoga';

  @override
  String get indexer => 'Indekser';

  @override
  String get indexerNote => 'Napomena: Nepotpuni broj omota odnosi se na duplicirane i nepronađene omote';

  @override
  String get indexerSubtitle => 'Upravljajte svojom muzičkom bibliotekom';

  @override
  String get infinityQueueOnNextPrev => 'Beskonačni red čekanja na Sljedeće/Prethodno';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'Pritiskom na sljedeće dok svira zadnja stavka skočit će na prvu, i obrnuto';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'umetnuto';

  @override
  String get instantlyApplies => 'Trenutno se primjenjuje';

  @override
  String get interactionReminder => 'Podsjetnik na interakciju';

  @override
  String get intro => 'Uvod';

  @override
  String get invertSelection => 'Obrni odabir';

  @override
  String get issues => 'Problemi';

  @override
  String get item => 'Stavka';

  @override
  String get jump => 'Skoči';

  @override
  String get jumpToDay => 'Skoči na dan';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Skoči na prvu numeru nakon završetka reda';

  @override
  String get keepCachedVersions => 'Zadrži keširane verzije';

  @override
  String get keepFileDates => 'Zadrži datume datoteka';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Mini-plejer je proširen';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Mini-plejer je proširen i video se reproducira';

  @override
  String get keepScreenAwakeNone => 'Ne drži ekran budnim';

  @override
  String get keepScreenAwakeWhen => 'Drži ekran budnim kada';

  @override
  String get killPlayerAfterDismissingApp => 'Ugasi plejer nakon zatvaranja aplikacije';

  @override
  String get language => 'Jezik';

  @override
  String get learnMore => 'Saznaj više';

  @override
  String get leftAction => 'Lijeva radnja';

  @override
  String get legacyAuthentication => 'Zastarjela provjera identiteta';

  @override
  String get libraryTabs => 'Kartice biblioteke';

  @override
  String get libraryTabsReorder => 'Možete promijeniti redoslijed aktiviranih kartica.';

  @override
  String get license => 'Licenca';

  @override
  String get licenseSubtitle => 'Licence i ugovori koje koristi Namida';

  @override
  String get like => 'Sviđa mi se';

  @override
  String get liked => 'Sviđa mi se';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Lista direktorija';

  @override
  String get loadAll => 'Učitaj sve';

  @override
  String get loadingFile => 'Učitavanje datoteke';

  @override
  String get local => 'Lokalno';

  @override
  String get localVideoMatching => 'Lokalno podudaranje videa';

  @override
  String get login => 'Prijava';

  @override
  String get longPressAction => 'Radnja dugog pritiska';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Dugo pritisnite tekst pjesme za cijeli ekran';

  @override
  String get lostMemories => 'Izgubljena sjećanja';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'oko ovog vremena, prije $numberString godina',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Izgubljene veze';

  @override
  String get loudnessEnhancer => 'Pojačivač glasnoće';

  @override
  String get lyricist => 'Tekstopisac';

  @override
  String get lyrics => 'Tekst pjesme';

  @override
  String get lyricsSource => 'Izvor teksta';

  @override
  String get m3uPlaylist => 'M3U lista numera';

  @override
  String get makeYourFirstListen => 'Napravite svoje prvo slušanje!';

  @override
  String get manage => 'Upravljaj';

  @override
  String get manageYourAccounts => 'Upravljajte svojim računima';

  @override
  String get manualBackup => 'Ručno';

  @override
  String get manualBackupSubtitle => 'odaberite specifičnu datoteku';

  @override
  String get markAsRead => 'Označi kao pročitano';

  @override
  String get matchAllTracks => 'Podudari sve numere';

  @override
  String get matchAllTracksNote => 'Ovo može utjecati na brzinu podudaranja jer će provjeriti sve numere u vašoj biblioteci';

  @override
  String get matchingType => 'Tip podudaranja';

  @override
  String get maxAudioCacheSize => 'Maksimalna veličina predmemorije zvuka';

  @override
  String get maxImageCacheSize => 'Maksimalna veličina predmemorije slika';

  @override
  String get maxVideoCacheSize => 'Maksimalna veličina predmemorije videa';

  @override
  String get maximum => 'Maksimalno';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store je omogućen, ovo neće imati efekta';

  @override
  String get medium => 'Srednje';

  @override
  String get membershipCode => 'Kod';

  @override
  String get membershipCodeSentToEmail => 'Kod poslan na vašu e-poštu';

  @override
  String get membershipDidntChange => 'Članstvo se nije promijenilo';

  @override
  String get membershipEnjoyNew => 'Uživajte u novom članstvu';

  @override
  String get membershipFreeCoupon => 'Besplatan kupon';

  @override
  String get membershipManage => 'Upravljajte svojim članstvom';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Nisu pronađene pretplate za ovog korisnika';

  @override
  String get membershipSignInToPatreonAccount => 'Prijavite se na svoj Patreon račun';

  @override
  String get membershipUnknown => 'Nepoznato članstvo';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Trebate članstvo $name1 ili $name2 za dodavanje više računa';
  }

  @override
  String get merge => 'Spoji';

  @override
  String get metadataCache => 'Predmemorija metapodataka';

  @override
  String get metadataEditFailed => 'Uređivanje metapodataka nije uspjelo';

  @override
  String get metadataReadFailed => 'Čitanje metapodataka nije uspjeslo';

  @override
  String get minFileDuration => 'Minimalno trajanje numere';

  @override
  String get minFileSize => 'Minimalna veličina datoteke';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimalno trajanje numere za vraćanje zadnje pozicije';

  @override
  String get minValueCantBeMoreThanMax => 'Minimalna vrijednost ne može biti veća od maksimalne';

  @override
  String get minValueToCountTrackListen => 'Broji slušanje nakon: ';

  @override
  String get minimizedMiniplayer => 'Minimiziran mini-plejer';

  @override
  String get minimum => 'Minimalno';

  @override
  String get minimumOneFolderSubtitle => 'Trebao bi postojati barem 1 direktorij, dodajte više direktorija ako želite ukloniti ovaj';

  @override
  String get minimumOneItem => 'Nije moguće ukloniti stavku';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Najmanje $numberString stavki treba ostati',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimalno trajanje segmenta';

  @override
  String get miniplayerCustomization => 'Prilagođavanje mini-plejera';

  @override
  String get minutes => 'minuta';

  @override
  String get missingEntries => 'Nedostajući unosi';

  @override
  String get missingTracks => 'Nedostajuće numere';

  @override
  String get mix => 'Miks';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Miks lista numera generisana od strane YouTube-a';

  @override
  String get mixes => 'Miksevi';

  @override
  String get mobile => 'Mobilni';

  @override
  String get month => 'Mjesec';

  @override
  String get months => 'Mjeseci';

  @override
  String get mood => 'Raspoloženje';

  @override
  String get moods => 'Raspoloženja';

  @override
  String get more => 'Više';

  @override
  String get mostPlayed => 'Najslušanije';

  @override
  String get multipleTracksTagsEditNote => 'Upravo ćete urediti ove numere,\nNepromijenjena polja ostaju netaknuta.';

  @override
  String get musicOfftopic => 'Muzika van teme';

  @override
  String get name => 'Ime';

  @override
  String get nameContainsBadCharacter => 'Ime sadrži loš karakter';

  @override
  String get never => 'Nikad';

  @override
  String get newDirectory => 'Novi direktorij';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Dodaj numere';

  @override
  String get newTracksMoods => 'Raspoloženje';

  @override
  String get newTracksMoodsSubtitle => 'Generiši numere na osnovu dostupnih raspoloženja';

  @override
  String get newTracksRandom => 'Nasumično';

  @override
  String get newTracksRandomSubtitle => 'Odaberi nasumične numere iz biblioteke';

  @override
  String get newTracksRatings => 'Ocjene';

  @override
  String get newTracksRatingsSubtitle => 'Generiši numere koje imaju specifičnu ocjenu';

  @override
  String get newTracksRecommended => 'Preporučeno';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Generiši numere koje obično slušate uz $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Sličan datum izdanja';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Generiši numere koje su objavljene otprilike u isto vrijeme kao $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Numera ima nepoznatu godinu';

  @override
  String get newest => 'Najnovije';

  @override
  String get next => 'Sljedeće';

  @override
  String get no => 'ne';

  @override
  String get noChangesFound => 'Nisu pronađene promjene.';

  @override
  String get noEnoughTracks => 'Nemate dovoljno numera..';

  @override
  String get noExcludedFolders => 'Nemate isključenih direktorija';

  @override
  String get noFolderChosen => 'Niste odabrali nijedan direktorij';

  @override
  String get noMoodsAvailable => 'Nema dostupnih raspoloženja';

  @override
  String get noNetworkAvailableToFetchData => 'Nema dostupne mreže za dohvatanje podataka';

  @override
  String get noTracksFound => 'Numere nisu pronađene';

  @override
  String get noTracksFoundBetweenDates => 'Ovaj vremenski raspon nema numera.';

  @override
  String get noTracksFoundInDirectory => 'Nisu pronađene numere u ovom direktoriju';

  @override
  String get noTracksInHistory => 'Nemate dovoljno numera u historiji';

  @override
  String get nonActive => 'Neaktivno';

  @override
  String get nonFavourites => 'Nisu omiljeni';

  @override
  String get none => 'Nijedno';

  @override
  String get normalizeAudio => 'Normalizuj zvuk';

  @override
  String get normalizeAudioSubtitle => 'Normalizuje glasnoću čitanjem oznake replay gain ili informacija s YouTube-a';

  @override
  String get notAvailableForYourDevice => 'Nije dostupno za vaš uređaj';

  @override
  String get notSupportedForNetworkFiles => 'Nije podržano za mrežne datoteke';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'Napomena';

  @override
  String get notification => 'Obavijest';

  @override
  String get notifications => 'Obavijesti';

  @override
  String get numberOfTracks => 'Broj numera';

  @override
  String get ofLabel => 'od';

  @override
  String get offlineSearch => 'Pretraga van mreže';

  @override
  String get offset => 'Pomak';

  @override
  String get oldDirectory => 'Stari direktorij';

  @override
  String get oldDirectoryStillHasTracks => 'Stari direktorij još uvijek ima neke numere, potvrdi?';

  @override
  String get oldestWatch => 'Najstarije gledano';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Pri prekidu';

  @override
  String get onNotificationTap => 'Pri dodiru obavijesti';

  @override
  String get onOpeningYoutubeLink => 'Pri otvaranju YouTube linka';

  @override
  String get onSwiping => 'Pri prevlačenju';

  @override
  String get onVolumeZero => 'Na glasnoći 0';

  @override
  String get ongoing => 'U toku';

  @override
  String get open => 'Otvori';

  @override
  String get openApp => 'Otvori aplikaciju';

  @override
  String get openInFileExplorer => 'Otvori u File Exploreru';

  @override
  String get openInYoutubeView => 'Otvori u YouTube prikazu';

  @override
  String get openMiniplayer => 'Otvori mini-plejer';

  @override
  String get openQueue => 'Otvori red čekanja';

  @override
  String get openYoutubeLink => 'Otvori YouTube link';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operacija $name zahtijeva račun, prijavite se za nastavak';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operacija $operation zahtijeva najmanje članstvo $name';
  }

  @override
  String get or => 'ili';

  @override
  String get others => 'Ostali';

  @override
  String get output => 'Izlaz';

  @override
  String get outro => 'Odjava';

  @override
  String get overrideOldFilesInTheSameFolder => 'Zamijeni stare datoteke u istom direktoriju';

  @override
  String get palette => 'Paleta';

  @override
  String get paletteMix => 'Miks';

  @override
  String get paletteNewMix => 'Novi miks';

  @override
  String get paletteSelectedMix => 'Odabrani miks';

  @override
  String get parallelDownloads => 'Paralelna preuzimanja';

  @override
  String get parsed => 'parsirano';

  @override
  String get password => 'Lozinka';

  @override
  String get path => 'Puna putanja datoteke';

  @override
  String get pause => 'Pauza';

  @override
  String get pauseFadeDuration => 'Trajanje blijeđenja pri pauzi';

  @override
  String get pausePlayback => 'Pauziraj reprodukciju';

  @override
  String get percentage => 'Postotak';

  @override
  String get performanceMode => 'Režim performansi';

  @override
  String get performanceNote => 'Može utjecati na performanse';

  @override
  String get personalized => 'Personalizirano';

  @override
  String get personalizedRelatedVideos => 'Personalizirani povezani videi';

  @override
  String get personalizedRelatedVideosSubtitle => 'Onemogućavanje ovoga povećat će potrošnju podataka';

  @override
  String get pickColorsFromDeviceWallpaper => 'Odaberi boje iz pozadine uređaja';

  @override
  String get pickFromStorage => 'Odaberi iz pohrane';

  @override
  String get pinned => 'Zakačeno';

  @override
  String get pitch => 'Visina tona';

  @override
  String get plain => 'Obično';

  @override
  String get play => 'Sviraj';

  @override
  String get playAfter => 'Sviraj poslije';

  @override
  String get playAfterNextPrev => 'Automatska reprodukcija na Sljedeće/Prethodno';

  @override
  String get playAll => 'Sviraj sve';

  @override
  String get playFadeDuration => 'Trajanje blijeđenja pri sviranju';

  @override
  String get playLast => 'Sviraj zadnje';

  @override
  String get playNext => 'Sviraj sljedeće';

  @override
  String get playbackSetting => 'Reprodukcija';

  @override
  String get playbackSettingSubtitle => 'Može se pristupiti direktno u plejeru dugim pritiskom na audio dugme';

  @override
  String get playlist => 'Lista numera';

  @override
  String get playlists => 'Liste numera';

  @override
  String get playlistsImportM3uNative => 'Ovo će uvesti M3U liste samo za korištenje u Namidi, koristite ako migrirate';

  @override
  String get playlistsImportM3uSynced =>
      'Ovo će automatski uvesti M3U liste iz direktorija indeksera i držati ih sinhroniziranim s originalnom M3U datotekom. Omogućite ako pristupate/mijenjate liste iz drugih aplikacija';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Automatski uvezi M3U liste';

  @override
  String get pleaseEnterADifferentName => 'Ovo ime već postoji :(\nmolim pokušajte drugo fensi ime';

  @override
  String get pleaseEnterALink => 'Molim unesite link';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. je li ovo YouTube link?';

  @override
  String get pleaseEnterAName => 'Molim unesite ime';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Spriječi duplicirane numere';

  @override
  String get preventDuplicatedTracksSubtitle => 'Koristi naziv datoteke za jedinstvenu identifikaciju numera';

  @override
  String get preview => 'Pregled';

  @override
  String get previous => 'Prethodno';

  @override
  String get previousButtonReplays => 'Dugme prethodno ponavlja';

  @override
  String get previousButtonReplaysSubtitle => 'ako je pritisnuto dok je trenutna pozicija bila veća od trajanja traženja';

  @override
  String get prioritizeEmbeddedLyrics => 'Prioritet ugrađenim tekstovima';

  @override
  String get priority => 'Prioritet';

  @override
  String get private => 'Privatno';

  @override
  String get progress => 'Napredak';

  @override
  String get promptToChangeTrackPath => 'Obično se ovo dešava kada izbrišete/premjestite/preimenujete datoteku izvan Namide. Želite li ažurirati trenutnu putanju?';

  @override
  String get public => 'Javno';

  @override
  String get queue => 'Red čekanja';

  @override
  String get queues => 'Redovi čekanja';

  @override
  String get random => 'Nasumično';

  @override
  String get randomPicks => 'Nasumični odabir';

  @override
  String get rating => 'Ocjena';

  @override
  String get reIndex => 'Ponovo indeksiraj';

  @override
  String get reIndexSubtitle => 'Izgradite svoju muzičku biblioteku ispočetka';

  @override
  String get reIndexWarning => 'Ovaj proces može potrajati, ovisno o veličini vaše biblioteke.\n\nOmoti neće biti ponovo indeksirani dok god postoje';

  @override
  String get recentAlbums => 'Nedavni albumi';

  @override
  String get recentArtists => 'Nedavni izvođači';

  @override
  String get recentListens => 'Nedavna slušanja';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Nedavno dodano';

  @override
  String get recordLabel => 'Izdavačka kuća';

  @override
  String get refresh => 'Osvježi';

  @override
  String get refreshLibrary => 'Osvježi biblioteku';

  @override
  String get refreshLibrarySubtitle => 'Provjeri novo dodanu ili izbrisanu muziku';

  @override
  String get refreshOnStartup => 'Osvježi pri pokretanju';

  @override
  String get relatedVideos => 'Povezani videi';

  @override
  String get rememberAudioOnlyMode => 'Zapamti režim samo zvuk';

  @override
  String get remixer => 'Remikser';

  @override
  String get remove => 'Ukloni';

  @override
  String get removeDuplicates => 'Ukloni duplikate';

  @override
  String get removeFromFavourites => 'Ukloni iz omiljenih';

  @override
  String get removeFromLibrary => 'Ukloni iz biblioteke';

  @override
  String get removeFromPlaylist => 'Ukloni s liste numera';

  @override
  String get removeQueue => 'Ukloni red čekanja';

  @override
  String get removeSourceFromHistory => 'Ukloni izvor iz historije';

  @override
  String get removeWhitespaces => 'Ukloni praznine';

  @override
  String get removed => 'Uklonjeno';

  @override
  String get rename => 'Preimenuj';

  @override
  String get renamePlaylist => 'Preimenuj listu numera';

  @override
  String get reorderable => 'Promjenjiv redoslijed';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ponovi još $number puta',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Režim ponavljanja';

  @override
  String get repeatModeAll => 'Ponovi cijeli red';

  @override
  String get repeatModeNone => 'Stani na zadnjoj numeri';

  @override
  String get repeatModeOne => 'Ponovi trenutnu numeru';

  @override
  String get replaceAllListensWithAnotherTrack => 'Zamijeni sva slušanja drugom numerom';

  @override
  String get replies => 'Odgovori';

  @override
  String get reply => 'Odgovori';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Zahtijeva brisanje predmemorije slika i ponovno indeksiranje';

  @override
  String get rescanVideos => 'Ponovo skeniraj videe';

  @override
  String get resetBrightness => 'Resetuj svjetlinu';

  @override
  String get resetToDefault => 'Postavi na';

  @override
  String get respectNoMedia => 'Poštuj .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Ne uključuj direktorije koji imaju .nomedia';

  @override
  String get restart => 'Ponovo pokreni';

  @override
  String get restoreBackup => 'Vrati rezervnu kopiju';

  @override
  String get restoreDefaults => 'Vrati zadane postavke';

  @override
  String get restoredBackupSuccessfully => 'Rezervna kopija vraćena';

  @override
  String get restoredBackupSuccessfullySub => 'Datoteka rezervne kopije je uspješno vraćena';

  @override
  String get resume => 'Nastavi';

  @override
  String get resumeIfWasInterrupted => 'Nastavi ako je pauzirano zbog prekida';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Nastavi ako je pauzirano zbog glasnoće';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Nastavi ako je pauzirano manje od $numberString minuta',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Vrati Youtube Dislike prikaz';

  @override
  String get reverseOrder => 'Obrnuti redoslijed';

  @override
  String get rightAction => 'Desna radnja';

  @override
  String get ringtone => 'Melodija zvona';

  @override
  String get sameDirectoryOnly => 'Samo isti direktorij';

  @override
  String get sample => 'Uzorak';

  @override
  String get sampleRate => 'Stopa uzorkovanja';

  @override
  String get save => 'Sačuvaj';

  @override
  String get saveToLibrary => 'Sačuvaj u biblioteku';

  @override
  String get savedIn => 'Sačuvano u';

  @override
  String get scaleMultiplier => 'Množitelj skale';

  @override
  String get search => 'Traži';

  @override
  String get searchYoutube => 'Traži YouTube';

  @override
  String get seconds => 'sekundi';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Pogledaj kôd projekta na $site';
  }

  @override
  String get seekDuration => 'Trajanje traženja';

  @override
  String get seekDurationInfo => 'Možete dodirnuti trenutno trajanje za traženje unazad i ukupno trajanje za traženje unaprijed';

  @override
  String get seekbar => 'Traka za traženje';

  @override
  String get selectAll => 'Odaberi sve';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Odaberi datoteke već u lokalnoj biblioteci';

  @override
  String get selectedTracks => 'Odabrane numere';

  @override
  String get selfPromotion => 'Samopromocija';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Ove riječi neće biti podijeljene';

  @override
  String get separatorsMessage => 'Nema potrebe za umetanjem razmaka, osim ako želite koristiti slovo/simbol koji se može naći u cijeloj riječi (poput x i ft.)';

  @override
  String get serverAddress => 'Adresa servera';

  @override
  String get setAs => 'Postavi kao';

  @override
  String get setAsDefault => 'Postavi kao zadano';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Postavi zadnju izmjenu datoteke kao datum uploada videa';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Postavi raspoloženja';

  @override
  String get setMoodsSubtitle => 'Koristite zareze (,) za odvajanje';

  @override
  String get setRating => 'Postavi ocjenu';

  @override
  String get setTags => 'Postavi oznake';

  @override
  String get setYoutubeLink => 'Postavi YouTube link';

  @override
  String get settings => 'Postavke';

  @override
  String get setupFirstStartup => 'Postavljanje prvog pokretanja';

  @override
  String get share => 'Dijeli';

  @override
  String get shareLogs => 'Podijeli zapise';

  @override
  String get shortcuts => 'Prečice';

  @override
  String get shouldDuck => 'Treba utišati';

  @override
  String get shouldDuckNote => 'Označava da bi glasnoća trebala biti smanjena. npr. obavijest';

  @override
  String get shouldPause => 'Treba pauzirati';

  @override
  String get shouldPauseNote => 'Označava da bi reprodukcija trebala biti pauzirana. npr. pozivi';

  @override
  String get showAll => 'Prikaži sve';

  @override
  String get showChannelWatermarkInFullscreen => 'Prikaži vodeni žig kanala u cijelom ekranu';

  @override
  String get showFailedOnly => 'Prikaži samo neuspjele';

  @override
  String get showHideUnknownFields => 'Prikaži/sakrij nepoznata polja';

  @override
  String get showInSeekbar => 'Prikaži u traci za traženje';

  @override
  String get showMixPlaylistsIn => 'Prikaži mikseve u';

  @override
  String get showMore => 'Prikaži više';

  @override
  String get showShortVideosIn => 'Prikaži Shorts u';

  @override
  String get showSkipButton => 'Prikaži dugme za preskakanje';

  @override
  String get showVideoEndcards => 'Prikaži završne kartice videa';

  @override
  String get showWebm => 'Prikaži webm';

  @override
  String get shuffle => 'Izmiješaj';

  @override
  String get shuffleAll => 'Nasumično sve';

  @override
  String get shuffleNext => 'Nasumično sljedeće';

  @override
  String get signIn => 'Prijavi se';

  @override
  String get signInCanceled => 'Prijava otkazana';

  @override
  String get signInFailed => 'Prijava neuspjela';

  @override
  String get signInToYourAccount => 'Prijavite se na svoj račun';

  @override
  String get signInYouDontHaveAccount => 'Nemate prijavljen račun';

  @override
  String get signInYouNeedAccountToViewPage => 'Trebate račun za pregled ove stranice';

  @override
  String get signOut => 'Odjavi se';

  @override
  String signOutFromName({required String name}) {
    return 'Odjavi se sa $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Prijava omogućava osnovno korištenje';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Dobijte rani pristup putem Patreona ili korištenjem kupona';

  @override
  String get similarDiscoverDate => 'Sličan datum otkrivanja';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generiši numere koje su otkrivene otprilike u isto vrijeme kao $currentTrack';
  }

  @override
  String get similarTimeRange => 'Sličan vremenski raspon';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generiši numere koje ste slušali otprilike u isto vrijeme kao $currentTrack';
  }

  @override
  String get singles => 'Singlovi';

  @override
  String get size => 'Veličina';

  @override
  String get skip => 'Preskoči';

  @override
  String get skipCountTracking => 'Praćenje broja preskakanja';

  @override
  String get skipSilence => 'Preskoči tišinu';

  @override
  String get skipSponsorSegmentsInVideos => 'Preskoči sponzorske segmente u videima';

  @override
  String get sleepAfter => 'Spavaj nakon';

  @override
  String get sleepTimer => 'Tajmer za spavanje';

  @override
  String get socials => 'Društvene mreže';

  @override
  String get socialsSubtitle => 'Pratite nas na našim platformama za ažuriranja, savjete i razmjenu ideja';

  @override
  String get someWebServersRequireAuthentication => 'Neki serveri zahtijevaju prijavu. Ažurirajte podatke za prijavu kako bi zadržali pristup svojoj biblioteci.';

  @override
  String get sortBy => 'Sortiraj po';

  @override
  String get source => 'Izvor';

  @override
  String get speed => 'Brzina';

  @override
  String get sponsor => 'Sponzor';

  @override
  String get sponsorblock => 'Ukloni sponzorisane dijelove';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock ljestvica';

  @override
  String get staggeredAlbumGridView => 'Rešetkasti prikaz albuma';

  @override
  String get start => 'Početak';

  @override
  String get stats => 'Statistika';

  @override
  String get statsSubtitle => 'Evo nekoliko informacija o vašoj biblioteci';

  @override
  String get stop => 'Stop';

  @override
  String get stopAfterThisTrack => 'Zaustavi nakon ove numere';

  @override
  String get stopAfterThisVideo => 'Zaustavi nakon ovog videa';

  @override
  String get storagePermissionDenied => 'Dozvola odbijena';

  @override
  String get storagePermissionDeniedSubtitle => 'Molim dozvolite pristup da biste mogli izvršiti ovu radnju';

  @override
  String get stretchLyricsDuration => 'Razvuci trajanje teksta';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Pretplati se';

  @override
  String get subscribed => 'Pretplaćeno';

  @override
  String get subscriber => 'Pretplatnik';

  @override
  String get subscribers => 'Pretplatnici';

  @override
  String get succeeded => 'Uspjelo';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Imate problem ili prijedlog? Otvorite prijavu na $site';
  }

  @override
  String get support => 'Podrška';

  @override
  String get supremacy => 'Nadmoć';

  @override
  String get sussyBaka => 'Bruh nema numera';

  @override
  String get swipeActions => 'Radnje prevlačenja';

  @override
  String get swipeToOpenDrawer => 'Prevuci za otvaranje ladice';

  @override
  String get synced => 'Sinhronizirano';

  @override
  String get synopsis => 'Sinopsis';

  @override
  String get tagFields => 'Polja oznaka';

  @override
  String get tags => 'Oznake';

  @override
  String get tapAction => 'Radnja dodirom';

  @override
  String get tapToSeek => 'Dodirni za traženje';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Režim teme';

  @override
  String get themeModeDark => 'Tamna';

  @override
  String get themeModeLight => 'Svijetla';

  @override
  String get themeModeSystem => 'Sistemska';

  @override
  String get themeSettings => 'Tema';

  @override
  String get themeSettingsSubtitle => 'Ukupna atmosfera vašeg plejera';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Ova lista ima aktivne filtere, onemogućite ih prije promjene redoslijeda.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Ovaj video je vjerovatno izbrisan ili postavljen na privatno.';

  @override
  String get thumbnails => 'Sličice';

  @override
  String get title => 'Naslov';

  @override
  String get top => 'Vrh';

  @override
  String get topComments => 'Najbolji komentari';

  @override
  String get topCommentsSubtitle => 'Prikaži komentare na vrhu umjesto na dnu';

  @override
  String get topRecentAlbums => 'Najnoviji albumi';

  @override
  String get topRecentArtists => 'Najnoviji izvođači';

  @override
  String get topRecents => 'Najnovije';

  @override
  String get totalListenTime => 'Ukupno vrijeme slušanja';

  @override
  String get totalListens => 'Ukupno slušanja';

  @override
  String get totalTracks => 'Ukupno numera';

  @override
  String get totalTracksDuration => 'Ukupno trajanje numera';

  @override
  String get track => 'Numera';

  @override
  String get trackArtistsSeparator => 'Razdjelnik izvođača';

  @override
  String get trackGenresSeparator => 'Razdjelnik žanrova';

  @override
  String get trackInfo => 'Informacije o numeri';

  @override
  String get trackNotFound => 'Numera nije pronađena';

  @override
  String get trackNumber => 'Broj numere';

  @override
  String get trackNumberTotal => 'Ukupno numera';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Staro ime: \"$oldName\"\n\nNovo ime: \"$newName\"\n\nJeste li sigurni?';
  }

  @override
  String get trackPlayMode => 'Režim reprodukcije';

  @override
  String get trackPlayModeSearchResults => 'Rezultati pretrage';

  @override
  String get trackPlayModeSelectedOnly => 'Samo odabrana numera';

  @override
  String get trackPlayModeTrackAlbum => 'Album numere';

  @override
  String get trackPlayModeTrackArtist => 'Glavni izvođač numere';

  @override
  String get trackPlayModeTrackGenre => 'Žanr numere';

  @override
  String get trackThumbnailSizeInList => 'Veličina sličice numere';

  @override
  String get trackTileCustomization => 'Prilagođavanje pločice numere';

  @override
  String get trackTileItemsSeparator => 'Razdjelnik stavki';

  @override
  String get tracks => 'Numere';

  @override
  String get tracksExcludedByNomedia => 'Numere isključene zbog .nomedia';

  @override
  String get tracksInfo => 'Informacije o numerama';

  @override
  String get underrated => 'Podcijenjeno';

  @override
  String get undo => 'Poništi';

  @override
  String get undoChanges => 'Poništi promjene?';

  @override
  String get undoChangesDeletedPlaylist => 'Poništi izbrisanu listu numera';

  @override
  String get undoChangesDeletedQueue => 'Poništi izbrisani red čekanja';

  @override
  String get undoChangesDeletedTrack => 'Poništi izbrisanu numeru';

  @override
  String get uniqueArtworkHash => 'Jedinstveni hash omota';

  @override
  String get unlimited => 'Neograničeno';

  @override
  String get unlisted => 'Nelistano';

  @override
  String get unlock => 'Otključaj';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Ažuriraj';

  @override
  String get updateDirectoryPath => 'Ažuriraj putanju direktorija';

  @override
  String get updateMissingTracksOnly => 'Ažuriraj samo nedostajuće numere';

  @override
  String get updating => 'Ažuriranje';

  @override
  String get useCollapsedSettingTiles => 'Koristi sažete pločice postavki';

  @override
  String get useMediaStore => 'Koristi Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ trenutno indeksiranje\nx poštivanje .nomedia će biti prisilno omogućeno\nx neke oznake metapodataka će nedostajati\nx YouTube integracija za lokalnu biblioteku neće raditi';

  @override
  String get usePitchBlack => 'Koristi potpuno crnu';

  @override
  String get usePitchBlackSubtitle => 'Korisno za AMOLED ekrane.. i izgleda kul';

  @override
  String get used => 'Iskorišteno';

  @override
  String get value => 'Vrijednost';

  @override
  String get valueBetween50200 => 'Vrijednost treba biti između 50% i 200%';

  @override
  String get vibration => 'Vibracija';

  @override
  String get vibrationType => 'Tip vibracije';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Predmemorija videa';

  @override
  String get videoCacheFile => 'Keširana video datoteka';

  @override
  String get videoCacheFiles => 'Keširane video datoteke';

  @override
  String get videoOnly => 'Samo video';

  @override
  String get videoPlaybackSource => 'Izvor videa';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Ovo će dati prioritet lokalnim videima, ako se ne nađu, dohvatit će s YouTube-a';

  @override
  String get videoPlaybackSourceLocal => 'Lokalni videi';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a­­­­\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle =>
      'Provjerava ima li bilo koja video datoteka (pronađena unutar odabranih direktorija) naziv datoteke koji sadrži naziv datoteke numere';

  @override
  String get videoPlaybackSourceYoutube => 'Sa YouTube-a';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Provjerava u nazivu datoteke i komentaru numere bilo koji odgovarajući YouTube link, videi se keširaju za kasniju upotrebu.';

  @override
  String get videoQuality => 'Kvaliteta videa';

  @override
  String get videoQualitySubtitle => 'Bit će odabrana najviša dostupna kvaliteta.';

  @override
  String get videoQualitySubtitleNote => 'Uvijek je dobro zadržati više alternativa u slučaju da kvaliteta nije pronađena, inače će se vratiti na najlošiju kvalitetu';

  @override
  String get videos => 'Videi';

  @override
  String get view => 'prikaz';

  @override
  String get viewAll => 'Prikaži sve';

  @override
  String get views => 'pregleda';

  @override
  String get volume => 'Glasnoća';

  @override
  String get warning => 'Upozorenje';

  @override
  String get waveformBarsCount => 'Broj traka valnog oblika';

  @override
  String get webmNoEditTagsSupport => 'WEBM format ne podržava uređivanje oznaka';

  @override
  String get week => 'Sedmica';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Godina';

  @override
  String get yes => 'Da';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Vaše trenutno članstvo je $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Vaš prilagođeni redoslijed će biti izgubljen. Jeste li sigurni?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'Prilagodite YouTube iskustvo';

  @override
  String get youtubeStyleMiniplayer => 'Mini-plejer u YouTube stilu';

  @override
  String get ytPreferNewComments => 'Preferiraj nove komentare kada je moguće';

  @override
  String get ytPreferNewCommentsSubtitle => 'Keširana verzija će se koristiti samo kada nema veze';
}
