// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Indonesian (`id`).
class AppLocalizationsId extends AppLocalizations {
  AppLocalizationsId([String locale = 'id']) : super(locale);

  @override
  String get about => 'Tentang';

  @override
  String get active => 'Aktif';

  @override
  String get add => 'Tambahkan';

  @override
  String get addAccount => 'Tambahkan akun';

  @override
  String get addAll => 'Tambahkan Semua';

  @override
  String get addAllAndRemoveOldOnes => 'Tambahkan semua dan hapus yang lama';

  @override
  String get addAsANewPlaylist => 'Tambahkan sebagai Daftar Putar baru';

  @override
  String get addAudioToLocalLibrary => 'Tambahkan audio ke Pustaka lokal';

  @override
  String get addFolder => 'Tambah Folder';

  @override
  String get addLanguage => 'Tambahkan Bahasa';

  @override
  String get addLanguageSubtitle => 'Bantu terjemahkan Namida ke bahasa Anda sendiri';

  @override
  String get addLrcFile => 'Tambahkan File LRC';

  @override
  String get addMoreFromThisAlbum => 'Tambahkan lebih banyak dari Album ini ke antrean';

  @override
  String get addMoreFromThisArtist => 'Tambahkan lebih banyak dari Artis ini ke antrean';

  @override
  String get addMoreFromThisFolder => 'Tambahkan lebih banyak dari Folder ini ke antrean';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Tambahkan lebih bamyak dari $media ke antrean';
  }

  @override
  String get addOnlyMissing => 'Hanya menambahkan yang hilang';

  @override
  String get addToFavourites => 'Tambahkan ke favorit';

  @override
  String get addToPlaylist => 'Tambahkan ke Daftar Putar';

  @override
  String get addTracksAtTheBeginning => 'Add tracks at the beginning';

  @override
  String get added => 'Ditambahkan';

  @override
  String get advanced => 'Lanjutan';

  @override
  String get advancedSettings => 'Lanjutan';

  @override
  String get advancedSettingsSubtitle => 'Pengaturan Lanjutan, jangan sentuh';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Album Artis';

  @override
  String get albumArtists => 'Album Artis';

  @override
  String get albumIdentifiers => 'Indentifikasi Album';

  @override
  String get albumThumbnailSizeInList => 'Ukuran Thumbnail Album';

  @override
  String get albumTileCustomization => 'Kustomisasi Ubin Album';

  @override
  String get albums => 'Album';

  @override
  String get albumsCount => 'Jumlah Album';

  @override
  String get all => 'Semua';

  @override
  String get allTime => 'Semua waktu';

  @override
  String get alreadyExists => 'Sudah tersedia';

  @override
  String get always => 'Selalu';

  @override
  String get alwaysAsk => 'Selalu tanya';

  @override
  String get alwaysDim => 'Selalu Dim';

  @override
  String get alwaysExpandedSearchbar => 'Selalu Perluas Kolom Pencari';

  @override
  String get alwaysRestore => 'Selalu pulihkan';

  @override
  String get animatingThumbnailIntensity => 'Intensitas Animasi Thumbnail';

  @override
  String get animatingThumbnailInversed => 'Animasi Inverse';

  @override
  String get animatingThumbnailInversedSubtitle => 'Nilai yang tinggi akan menyebabkan Thumbnail menjadi lebih kecil';

  @override
  String get anotherProcessIsRunning => 'Proses lain sedang berjalan.';

  @override
  String get appIcon => 'Ikon aplikasi';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Artis';

  @override
  String get artists => 'Artis';

  @override
  String get artwork => 'Gambar';

  @override
  String get artworkGestures => 'Gestur Gambar';

  @override
  String get artworks => 'Gambar';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Cache Audio';

  @override
  String get audioOnly => 'Hanya Audio';

  @override
  String get auto => 'Otomatis';

  @override
  String get autoBackupInterval => 'Interval pencadangan otomatis';

  @override
  String get autoColoring => 'Warna dinamis';

  @override
  String get autoColoringSubtitle => 'Secara otomatis memilih warna pemutar dari Gambar saat ini';

  @override
  String get autoExtractTagsFromFilename => 'Ekstrak otomatis dari nama file';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Ekstrak otomatis Judul & Artis dari judul video';

  @override
  String get autoGenerated => 'Buat otomatis';

  @override
  String get autoSkip => 'Lewati otomatis';

  @override
  String get autoSkipOnce => 'Lewati otomatis sekali';

  @override
  String get autoStartRadio => 'Mulai otomatis radio';

  @override
  String get autoStartRadioSubtitle => 'Otomatis menambahkan daftar putar mix saat memutar trek tunggal';

  @override
  String get automaticBackup => 'Otomatis';

  @override
  String get automaticBackupSubtitle => 'Secara otomatis menerapkan file cadangan terbaru yang ditemukan di dalam lokasi cadangan';

  @override
  String get backupAndRestore => 'Pencandangan dan Pemulihan';

  @override
  String get backupAndRestoreSubtitle => 'Cadangkan database dan pengaturanmu';

  @override
  String get balanced => 'Seimbang';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Di Antara Tanggal';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Daftar Hitam';

  @override
  String get borderRadiusMultiplier => 'Radius Batas';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Membatalkan';

  @override
  String get canceled => 'Dibatalkan';

  @override
  String get changed => 'Berubah';

  @override
  String get changelog => 'Catatan perubahan';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Saluran';

  @override
  String get channels => 'Saluran';

  @override
  String get check => 'Periksa';

  @override
  String get checkForMore => 'Periksa lebih lanjut';

  @override
  String get checkList => 'Periksa daftar';

  @override
  String get choose => 'Pilih';

  @override
  String get chooseWhatToClear => 'Pilih apa yang akan dibersihkan';

  @override
  String get claim => 'Mengklaim';

  @override
  String get clear => 'Bersihkan';

  @override
  String get clearAudioCache => 'Bersihkan cache Audio';

  @override
  String get clearImageCache => 'Bersihkan cache Gambar';

  @override
  String get clearImageCacheWarning => 'Peringatan: akan membuat pustaka tanpa gambar, Gunakan hanya untuk membangun kembali cache gambar.';

  @override
  String get clearTrackItem => 'Hapus Trek';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Hapus Trek $numberString',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Bersihkan cache Video';

  @override
  String get clearVideoCacheNote => 'Anda dapat memilih apa yang akan dihapus.';

  @override
  String get clock => 'Waktu';

  @override
  String get colorPalette => 'Palet Warna';

  @override
  String get colorPaletteNote1 => 'Tekan lama warna untuk menghapusnya';

  @override
  String get colorPaletteNote2 => 'Ketuk pada mix untuk digunakan sebagai warna default';

  @override
  String get colorPalettes => 'Palet Warna';

  @override
  String get comment => 'Komentar';

  @override
  String get comments => 'Komentar';

  @override
  String get composer => 'Komposer';

  @override
  String get compress => 'Kompres';

  @override
  String get compressImages => 'Kompres Gambar';

  @override
  String get compressionPercentage => 'Persentase Kompresi';

  @override
  String get configure => 'Konfigurasi';

  @override
  String get confirm => 'Konfirmasi';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Menyalin Gambar';

  @override
  String get copiedToClipboard => 'Disalin ke Papan Klip';

  @override
  String get copy => 'Salin';

  @override
  String get corruptedFile => 'Tidak dapat mengurai file, mungkin rusak';

  @override
  String get couldntOpen => 'Tidak dapat dibuka :(';

  @override
  String get couldntOpenYtLink => 'Tidak ada tautan Youtube yang tersedia untuk lagu ini';

  @override
  String get couldntPlayFile => 'Tidak dapat memutar file';

  @override
  String get couldntRenamePlaylist => 'Tidak dapat mengganti nama daftar putar';

  @override
  String get couldntSaveImage => 'Tidak dapat menyimpan gambar';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Negara';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Membuat';

  @override
  String get createBackup => 'Membuat cadangan';

  @override
  String get createNewPlaylist => 'Membuat Daftar Putar baru';

  @override
  String get createdBackupSuccessfully => 'Membuat Cadangan';

  @override
  String get createdBackupSuccessfullySub => 'File cadangan berhasil dibuat';

  @override
  String get crossPlatformSync => 'Sinkronisasi lintas platform';

  @override
  String get crossfadeDuration => 'Durasi crossfade';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Memicu Crossfade secara otomatis dalam $secondsString detik terakhir',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Jangan memicu crossfade secara otomatis';

  @override
  String get custom => 'Kustom';

  @override
  String get customizations => 'Kustomisasi';

  @override
  String get customizationsSubtitle => 'Sesuaikan tampilan pemutar Anda, sesuaikan seleramu';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Penghemat data';

  @override
  String get dataSaverMode => 'Mode hemat data';

  @override
  String get database => 'Database';

  @override
  String get date => 'Tanggal';

  @override
  String get dateAdded => 'Tanggal Ditambahkan';

  @override
  String get dateCreated => 'Tanggal Dibuat';

  @override
  String get dateModified => 'Tanggal Diubah';

  @override
  String get dateTimeFormat => 'Format Tanggal';

  @override
  String get day => 'Day';

  @override
  String get days => 'Hari';

  @override
  String get defaultBackupLocation => 'Lokasi Cadangan Default';

  @override
  String get defaultColor => 'Warna Default';

  @override
  String get defaultColorSubtitle => 'Tetapkan warna yang akan digunakan oleh pemutar';

  @override
  String get defaultDownloadLocation => 'Lokasi Unduhan Default';

  @override
  String get defaultLabel => 'Default';

  @override
  String get defaultLibraryTab => 'Tab Pustaka Default';

  @override
  String get delete => 'Hapus';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Hapus $countString dari total $totalSizeText file?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Hapus $numberText secara permanen dari penyimpanan Anda';
  }

  @override
  String get deletePlaylist => 'Hapus Daftar Putar';

  @override
  String get deleteTempFiles => 'Hapus file sementara';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Deskripsi';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Apa maksud anda';

  @override
  String get dimIntensity => 'Intensitas Redup';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Redupkan miniplayer setelah $secondsString detik tidak ada aktivitas',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Direktori tidak ditemukan';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Nonaktifkan Semua';

  @override
  String get disableReordering => 'Nonaktifkan Penyusunan Ulang';

  @override
  String get disableSearchCleanup => 'Nonaktifkan Pembersihan Pencarian';

  @override
  String get discNumber => 'Nomor Disk';

  @override
  String get discNumberTotal => 'Total Disk';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Tidak Suka';

  @override
  String get dismissibleMiniplayer => 'Miniplayer Dapat Ditutup';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Tanggal kanan atas Kartu Album';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Menampilkan tanggal Album di Kartu Album kanan atas';

  @override
  String get displayArtistBeforeTitle => 'Tampilkan nama artis sebelum judul';

  @override
  String get displayArtworkOnLockscreen => 'Tampilkan gambar di layar kunci';

  @override
  String get displayAudioInfoInMiniplayer => 'Tampilkan Info Audio';

  @override
  String get displayFavButtonInNotification => 'Tampilkan Tombol Sukai di Notifikasi';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Thumbnail mungkin akan tergeser.';

  @override
  String get displayFavouriteIconInTrackTile => 'Tampilkan Tombol Sukai';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Tampilkan durasi yang tersisa, bukan total';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Tampilkan Item Ketiga di setiap Baris';

  @override
  String get displayThirdRowInTrackTile => 'Tampilkan Baris Ketiga';

  @override
  String get displayTrackNumberInAlbumPage => 'Tampilkan nomor Trek di Halaman Album';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Menampilkan kotak kecil berisi nomor trek di halaman album';

  @override
  String get doNothing => 'Tidak melakukan apapun';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Selesai';

  @override
  String get dontAskAgain => 'Jangan tanya lagi';

  @override
  String get dontDim => 'Jangan Dim';

  @override
  String get dontRestorePosition => 'Jangan pulihkan';

  @override
  String get dontResume => 'Jangan lanjutkan';

  @override
  String get doubleTapToToggleLyrics => 'Ketuk dua kali untuk menampilkan lirik';

  @override
  String get download => 'Unduh';

  @override
  String get downloadingWillOverrideIt => 'Pengunduhan akan ditimpa';

  @override
  String get downloads => 'Unduhan';

  @override
  String get downloadsMetadataTags => 'Mengunduh Label Metadata';

  @override
  String get downloadsMetadataTagsSubtitle => 'Ekstrak artis, judul dan album dari info video secara default';

  @override
  String get dragToSeek => 'Seret untuk mencari';

  @override
  String get duckAudio => 'Audio bebek';

  @override
  String get duplicatedItemsAdding => 'Anda mencoba menambahkan beberapa item yang sudah ada di Daftar Putar ini';

  @override
  String get duplicatedTracks => 'Trek Digandakan';

  @override
  String get duration => 'Durasi';

  @override
  String get edgeColorsSwitching => 'Peralihan Warna Tepi';

  @override
  String get edit => 'Sunting';

  @override
  String get editArtwork => 'Edit Gambar';

  @override
  String get editTags => 'Edit Label';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'Anda memiliki bidang dengan nilai kosong, pastikan Anda benar-benar mengeditnya';

  @override
  String get emptyValue => 'Nilai Kosong';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Aktifkan Efek Buram';

  @override
  String get enableBottomNavBar => 'Aktifkan Bilah Navigasi Bawah';

  @override
  String get enableBottomNavBarSubtitle => 'Item ada di dalam laci';

  @override
  String get enableClipboardMonitoring => 'Aktifkan Pemantauan Papan Klip';

  @override
  String get enableClipboardMonitoringSubtitle => 'Memungkinkan menempelkan tautan dan teks di dalam bilah pencarian';

  @override
  String get enableCrossfadeEffect => 'Aktifkan Efek Crossfade';

  @override
  String get enableFadeEffectOnPlayPause => 'Aktifkan Efek Pudar saat Putar/Jeda';

  @override
  String get enableFoldersHierarchy => 'Aktifkan Hierarki Folder';

  @override
  String get enableGlowEffect => 'Aktifkan Efek Cahaya';

  @override
  String get enableM3uSync => 'Aktifkan Sinkronisasi M3U';

  @override
  String get enableM3uSyncNote1 => 'Sinkronisasi M3U memungkinkan menyimpan perubahan daftar putar ke file M3U asli';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Jika terjadi kesalahan, cadangan daftar putar ini akan ditemukan di $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Jika Ditolak, semua perubahan yang dilakukan pada daftar putar ini akan hilang saat dimulai ulang';

  @override
  String get enableMiniplayerParticles => 'Aktifkan partikel bergerak';

  @override
  String get enableParallaxEffect => 'Aktifkan Efek Paralaks';

  @override
  String get enablePartyMode => 'Aktifkan Mode Pesta';

  @override
  String get enablePartyModeSubtitle => 'Terapkan efek pernapasan tepi yang mewah';

  @override
  String get enablePictureInPicture => 'Aktifkan Picture-in-Picture';

  @override
  String get enableReordering => 'Aktifkan Pengurutan Ulang';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Aktifkan Pembersihan Pencarian';

  @override
  String get enableSearchCleanupSubtitle => 'Semua Simbol dan Spasi akan diabaikan';

  @override
  String get enableSponsorblock => 'Aktifkan pemblokir iklan';

  @override
  String get enableVideoPlayback => 'Aktifkan Pemutaran Video';

  @override
  String get enterSymbol => 'Silakan Masukkan Simbol';

  @override
  String get equalizer => 'Ekualiser';

  @override
  String get error => 'Galat';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Terjadi kesalahan saat memutar trek';

  @override
  String get excludedFodlers => 'Folder yang Dikecualikan';

  @override
  String get exit => 'Keluar';

  @override
  String get exitAppSubtitle => 'Ketuk lagi untuk keluar';

  @override
  String get expandedMiniplayer => 'Miniplayer yang Diperluas';

  @override
  String get exportAsM3u => 'Ekspor sebagai M3U';

  @override
  String get extension => 'Ekstensi';

  @override
  String get externalFiles => 'File Eksternal';

  @override
  String get extract => 'Ekstrak';

  @override
  String get extractAllColorPalettes => 'Ekstrak Semua Palet Warna';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ekstrak Sisa $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Ekstrak prestasi. artis dari judul';

  @override
  String get extractFeatArtistSubtitle => 'Ekstrak artis (feat. X) dan (ft. X), sebagai entri artis baru.';

  @override
  String get extractingInfo => 'Mengekstrak Info';

  @override
  String get extras => 'Ekstra';

  @override
  String get extrasSubtitle => 'Pengaturan Ekstra untuk menyempurnakan pengalaman Anda';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Gagal';

  @override
  String get failedEdits => 'Pengeditan Gagal';

  @override
  String get favourites => 'Lagu yang Disukai';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Mengambil';

  @override
  String get fetchingOfAllVideos => 'Mengambil semua video';

  @override
  String get file => 'File';

  @override
  String get fileAlreadyExists => 'Berkas sudah ada';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Nama file';

  @override
  String get fileNameWoExt => 'Nama file tanpa ekstensi';

  @override
  String get filenameShouldntStartWith => 'Nama file tidak boleh diawali dengan';

  @override
  String get files => 'File';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Filter Album';

  @override
  String get filterArtists => 'Filter Artist';

  @override
  String get filterGenres => 'Filter Genre';

  @override
  String get filterPlaylists => 'Filter Daftar Putar';

  @override
  String get filterTracks => 'Filter Trek';

  @override
  String get filterTracksBy => 'Filter Lagu di Daftar Pencarian Berdasarkan';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Lagu Difilter berdasarkan ukuran dan durasi';

  @override
  String get finished => 'Selesai';

  @override
  String get finishedUpdatingLibrary => 'Selesai Memperbarui Perpustakaan';

  @override
  String get firstListen => 'Pertama kali didengarkan';

  @override
  String get fixYtdlpBigThumbnailSize => 'Perbaiki ukuran thumbnail yt-dlp yang besar';

  @override
  String get floatingActionButton => 'Tombol Aksi Mengambang';

  @override
  String get folder => 'Berkas';

  @override
  String get folderName => 'Nama Folder';

  @override
  String get folders => 'Folder';

  @override
  String get fontScale => 'Skala Font';

  @override
  String get forceMiniplayerFollowTrackColors => 'Paksa miniplayer untuk mengikuti warna trek';

  @override
  String get forceSquaredAlbumThumbnail => 'Paksa Thumbnail album Persegi';

  @override
  String get forceSquaredThumbnailNote => 'Ukuran Thumbnail & Tinggi Ubin TIDAK sama, Tampilan persegi tidak akan seperti yang diharapkan, Apakah Anda ingin membuatnya sama?';

  @override
  String get forceSquaredTrackThumbnail => 'Paksa Thumbnail trek Persegi';

  @override
  String get forceStopColorPaletteGeneration => 'Paksa berhenti mengekstraksi palet warna? kamu masih bisa melanjutkannya nanti';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Layar Penuh';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Menghasilkan';

  @override
  String get generateFromDates => 'Rentang waktu';

  @override
  String get generateFromDatesSubtitle => 'Hasilkan lagu yang Anda dengarkan dalam rentang waktu tertentu';

  @override
  String get generateRandomPlaylist => 'Hasilkan Daftar Putar acak';

  @override
  String get genre => 'Genre';

  @override
  String get genres => 'Genre';

  @override
  String get goToAlbum => 'Pergi ke Album';

  @override
  String get goToArtist => 'Pergi ke Artis';

  @override
  String get goToChannel => 'Pergi ke Channel';

  @override
  String get goToFolder => 'Pergi ke Folder';

  @override
  String get goodLooking => 'Tampan';

  @override
  String get grantStoragePermission => 'Berikan Izin Penyimpanan';

  @override
  String get group => 'Grup';

  @override
  String get groupArtworksByAlbum => 'Kelompokkan Gambar berdasarkan Album';

  @override
  String get guide => 'Panduan';

  @override
  String get hapticFeedback => 'Getar sentuhan';

  @override
  String get heightOfAlbumTile => 'Ketinggian Ubin Album';

  @override
  String get heightOfTrackTile => 'Ketinggian Ubin Trek';

  @override
  String get hideSkipButtonAfter => 'Sembunyikan tombol lewati setelah';

  @override
  String get highMatches => 'Kecocokan tinggi';

  @override
  String get highPerformance => 'Kinerja tinggi';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Riwayat';

  @override
  String get historyImportMissingEntriesNote =>
      'Entri ini tidak dapat ditemukan di dalam pustaka, jika Anda yakin entri tersebut ada, harap pertimbangkan untuk menambahkannya secara manual';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString mendengarkan $oldTrackInfo akan diganti dengan $newTrackInfo, konfirmasi?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Beranda';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'Format 12 Jam';

  @override
  String get hours => 'Jam';

  @override
  String get iReadAndAgree => 'Saya baca dan setujui';

  @override
  String get ifNotPlaying => 'Jika tidak memutar';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Pengunduhan dapat dibatasi ketika penghemat baterai aplikasi dihidupkan';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignore common prefixes while sorting';

  @override
  String get ignores => 'Abaikan';

  @override
  String get imageSource => 'Sumber gambar';

  @override
  String get immersiveMode => 'Layar Penuh';

  @override
  String get immersiveModeSubtitle => 'Sembunyikan bilah Status dan Navigasi saat Miniplayer diperluas';

  @override
  String get import => 'Impor';

  @override
  String get importAll => 'Impor semua';

  @override
  String get importLastFmHistory => 'Impor Riwayat LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Buka $lastfmCsvLink\n\n2. Ketik nama pengguna Anda, ambil dan unduh file csv.\n\n3. Pilih file dari layar berikutnya.';
  }

  @override
  String get importTimeRange => 'Impor rentang waktu';

  @override
  String get importYoutubeHistory => 'Impor Riwayat Youtube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Buka $takeoutLink\n\n2. Tekan \"Beberapa Format\" dan di samping \"Riwayat\" pilih \"JSON\".\n\n3. Tekan \"Semua data Youtube disertakan\", Batalkan pilihan Semua dan pilih hanya riwayat.\n\n4. Buat Ekspor, Unduh & Buka zip.\n\n5. Pilih \"watch-history.json\" dari layar berikutnya.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString channel berhasil diimpor',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText daftar putar berhasil diimpor',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Termasuk video';

  @override
  String get indexRefreshRequired => 'Lakukan Refresh setelah mengubah ini';

  @override
  String get indexer => 'Pengindeks';

  @override
  String get indexerNote => 'Catatan: Jumlah Gambar yang Tidak Lengkap mengacu pada Gambar yang diduplikasi & tidak ditemukan';

  @override
  String get indexerSubtitle => 'Kelola Pustaka musik Anda';

  @override
  String get infinityQueueOnNextPrev => 'Antrean Tak Terhingga di Berikutnya/Sebelumnya';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'menekan berikutnya sambil memainkan item terakhir akan melompat ke item pertama, dan sebaliknya';

  @override
  String get info => 'Informasi';

  @override
  String get inserted => 'dimasukkan';

  @override
  String get instantlyApplies => 'Langsung Berlaku';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Balik pilihan';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Item';

  @override
  String get jump => 'Lompat';

  @override
  String get jumpToDay => 'Lompat ke Hari';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Lompat ke trek pertama setelah menyelesaikan antrian';

  @override
  String get keepCachedVersions => 'Simpan versi cache';

  @override
  String get keepFileDates => 'Simpan tanggal file';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniplayer Diperluas';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniplayer Diperluas dan Video Diputar';

  @override
  String get keepScreenAwakeNone => 'Jangan biarkan layar tetap menyala';

  @override
  String get keepScreenAwakeWhen => 'Jaga agar kapan layar tetap menyala';

  @override
  String get killPlayerAfterDismissingApp => 'Bunuh pemutar setelah menutup aplikasi';

  @override
  String get language => 'Bahasa';

  @override
  String get learnMore => 'Pelajari selengkapnya';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Tab Pustaka';

  @override
  String get libraryTabsReorder => 'Anda dapat menyusun ulang tab yang diaktifkan.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Sukai';

  @override
  String get liked => 'Disukai';

  @override
  String get link => 'Tautan';

  @override
  String get listOfFolders => 'Daftar Folder';

  @override
  String get loadAll => 'Muat semua';

  @override
  String get loadingFile => 'Memuat Berkas';

  @override
  String get local => 'Lokal';

  @override
  String get localVideoMatching => 'Pencocokan Video Lokal';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Tekan lama lirik untuk masuk layar penuh';

  @override
  String get lostMemories => 'Kenangan masa Lampau';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'sekitar waktu ini, $numberString tahun yang lalu',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Penambah Kenyaringan';

  @override
  String get lyricist => 'Penulis lirik';

  @override
  String get lyrics => 'Lirik';

  @override
  String get lyricsSource => 'Sumber lirik';

  @override
  String get m3uPlaylist => 'Daftar Putar M3U';

  @override
  String get makeYourFirstListen => 'Dengarkan untuk pertama kalinya!';

  @override
  String get manage => 'Kelola';

  @override
  String get manageYourAccounts => 'Kelola akun anda';

  @override
  String get manualBackup => 'Manual';

  @override
  String get manualBackupSubtitle => 'mengambil file tertentu';

  @override
  String get markAsRead => 'Tandai sebagai sudah dibaca';

  @override
  String get matchAllTracks => 'Cocokkan Semua Lagu';

  @override
  String get matchAllTracksNote => 'ini dapat berdampak pada kecepatan pencocokan, karena ini akan memeriksa semua trek di pustaka Anda';

  @override
  String get matchingType => 'Tipe yang cocok';

  @override
  String get maxAudioCacheSize => 'Ukuran cache maksimal Audio';

  @override
  String get maxImageCacheSize => 'Ukuran cache maksimal Gambar';

  @override
  String get maxVideoCacheSize => 'Ukuran cache maksimal Video';

  @override
  String get maximum => 'Maksimum';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store diaktifkan, ini tidak akan berpengaruh';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Kode';

  @override
  String get membershipCodeSentToEmail => 'Kode dikirim ke email anda';

  @override
  String get membershipDidntChange => 'Keanggotaan tidak berubah';

  @override
  String get membershipEnjoyNew => 'Nikmati keanggotaan baru Anda';

  @override
  String get membershipFreeCoupon => 'Kupon Gratis';

  @override
  String get membershipManage => 'Kelola keanggotaan Anda';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Tidak ada langganan yang ditemukan untuk pengguna ini';

  @override
  String get membershipSignInToPatreonAccount => 'Masuk ke akun patreon Anda';

  @override
  String get membershipUnknown => 'Keanggotaan Tidak Diketahui';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Anda memerlukan keanggotaan $name1 atau $name2 untuk menambahkan beberapa akun';
  }

  @override
  String get merge => 'Gabungkan';

  @override
  String get metadataCache => 'Cache Metadata';

  @override
  String get metadataEditFailed => 'Gagal mengedit metadata';

  @override
  String get metadataReadFailed => 'Gagal membaca metadata';

  @override
  String get minFileDuration => 'Durasi Trek Minimum';

  @override
  String get minFileSize => 'Ukuran File Minimum';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Durasi trek minimum untuk mengembalikan posisi pemutaran terakhir';

  @override
  String get minValueCantBeMoreThanMax => 'Nilai minimum tidak boleh lebih dari nilai maksimum';

  @override
  String get minValueToCountTrackListen => 'Hitung dengarkan setelah: ';

  @override
  String get minimizedMiniplayer => 'Miniplayer yang Diminimalkan';

  @override
  String get minimum => 'Minimum';

  @override
  String get minimumOneFolderSubtitle => 'Minimal harus ada 1 folder, tambahkan folder lain jika Anda ingin menghapus folder ini';

  @override
  String get minimumOneItem => 'Tidak dapat menghapus item';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Setidaknya tersisa $numberString item',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Kustomisasi Miniplayer';

  @override
  String get minutes => 'menit';

  @override
  String get missingEntries => 'Entri Hilang';

  @override
  String get missingTracks => 'Trek yang hilang';

  @override
  String get mix => 'Mix';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Daftar putar campuran yang dibuat oleh youtube';

  @override
  String get mixes => 'Mix teratasmu';

  @override
  String get mobile => 'Perangkat mobile';

  @override
  String get month => 'Bulan';

  @override
  String get months => 'Bulan';

  @override
  String get mood => 'Atmosfer';

  @override
  String get moods => 'Atmosfer';

  @override
  String get more => 'Lagi';

  @override
  String get mostPlayed => 'Paling banyak dimainkan';

  @override
  String get multipleTracksTagsEditNote => 'Anda akan mengedit trek ini,\nBidang yang tidak diubah tetap tidak disentuh.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Nama';

  @override
  String get nameContainsBadCharacter => 'Nama mengandung karakter buruk';

  @override
  String get never => 'Tidak pernah';

  @override
  String get newDirectory => 'Direktori baru';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Tambahkan Trek';

  @override
  String get newTracksMoods => 'Atmosfer';

  @override
  String get newTracksMoodsSubtitle => 'Hasilkan trek berdasarkan atmosfer yang tersedia';

  @override
  String get newTracksRandom => 'Acak';

  @override
  String get newTracksRandomSubtitle => 'Ambil trek acak dari pustaka Anda';

  @override
  String get newTracksRatings => 'Peringkat';

  @override
  String get newTracksRatingsSubtitle => 'Hasilkan trek yang memiliki peringkat spesifik';

  @override
  String get newTracksRecommended => 'Direkomendasikan';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Tampilkan lagu yang biasa Anda dengarkan dengan $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Tanggal Rilis Serupa';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Tampilkan lagu yang dirilis sekitar waktu yang sama dengan $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Lagu memiliki tahun yang tidak diketahui';

  @override
  String get newest => 'Terbaru';

  @override
  String get next => 'Berikutnya';

  @override
  String get no => 'Tidak';

  @override
  String get noChangesFound => 'Tidak ada perubahan yang ditemukan.';

  @override
  String get noEnoughTracks => 'Anda tidak memiliki banyak trek..';

  @override
  String get noExcludedFolders => 'Anda tidak memiliki folder yang dikecualikan';

  @override
  String get noFolderChosen => 'Anda belum memilih folder apa pun';

  @override
  String get noMoodsAvailable => 'Tidak ada atmosfer yang tersedia';

  @override
  String get noNetworkAvailableToFetchData => 'Tidak ada jaringan yang tersedia untuk mengambil data';

  @override
  String get noTracksFound => 'Tidak ada trek yang ditemukan';

  @override
  String get noTracksFoundBetweenDates => 'Rentang waktu ini tidak memiliki trek apa pun.';

  @override
  String get noTracksFoundInDirectory => 'Tidak ada trek yang ditemukan di direktori ini';

  @override
  String get noTracksInHistory => 'Anda tidak memiliki cukup trek dalam riwayat';

  @override
  String get nonActive => 'Tidak aktif';

  @override
  String get nonFavourites => 'Bukan yang Disukai';

  @override
  String get none => 'Tidak ada';

  @override
  String get normalizeAudio => 'Normalisasikan audio';

  @override
  String get normalizeAudioSubtitle => 'Normalisasi volume dengan membaca tag perolehan replay atau info yang disediakan oleh youtube';

  @override
  String get notAvailableForYourDevice => 'Tidak tersedia untuk perangkat kamu';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Catatan';

  @override
  String get notification => 'Pemberitahuan';

  @override
  String get notifications => 'Pemberitahuan';

  @override
  String get numberOfTracks => 'Jumlah Trek';

  @override
  String get ofLabel => 'dari';

  @override
  String get offlineSearch => 'Pencarian Offline';

  @override
  String get offset => 'Mengimbangi';

  @override
  String get oldDirectory => 'Direktori lama';

  @override
  String get oldDirectoryStillHasTracks => 'Direktori Lama masih memiliki beberapa trek, konfirmasi?';

  @override
  String get oldestWatch => 'Terlama Ditonton';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Dalam Gangguan';

  @override
  String get onNotificationTap => 'Ketuk pada Notifikasi';

  @override
  String get onOpeningYoutubeLink => 'Saat membuka tautan youtube';

  @override
  String get onSwiping => 'Saat Menggeser';

  @override
  String get onVolumeZero => 'Pada volume 0';

  @override
  String get ongoing => 'Sedang berlangsung';

  @override
  String get open => 'Membuka';

  @override
  String get openApp => 'Buka Aplikasi';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Buka dalam tampilan Youtube';

  @override
  String get openMiniplayer => 'Buka Miniplayer';

  @override
  String get openQueue => 'Buka Antrian';

  @override
  String get openYoutubeLink => 'Buka Tautan Youtube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operasi $name memerlukan akun, Masuk untuk melanjutkan';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operasi $operation memerlukan setidaknya keanggotaan $name';
  }

  @override
  String get or => 'atau';

  @override
  String get others => 'Yang lain';

  @override
  String get output => 'Output';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Ganti file lama di folder yang sama';

  @override
  String get palette => 'Palet';

  @override
  String get paletteMix => 'Mencampur';

  @override
  String get paletteNewMix => 'Campuran Baru';

  @override
  String get paletteSelectedMix => 'Campuran Terpilih';

  @override
  String get parallelDownloads => 'Unduhan Paralel';

  @override
  String get parsed => 'diuraikan';

  @override
  String get password => 'Password';

  @override
  String get path => 'File Jalur Lengkap';

  @override
  String get pause => 'Jeda';

  @override
  String get pauseFadeDuration => 'Jeda Durasi Pudar';

  @override
  String get pausePlayback => 'Jeda pemutaran';

  @override
  String get percentage => 'Persentase';

  @override
  String get performanceMode => 'Mode performa';

  @override
  String get performanceNote => 'Mungkin mempengaruhi kinerja';

  @override
  String get personalized => 'Dipersonalisasi';

  @override
  String get personalizedRelatedVideos => 'Personalisasikan Video yang Terkait';

  @override
  String get personalizedRelatedVideosSubtitle => 'Menonaktifkan ini akan meningkatkan penggunaan data';

  @override
  String get pickColorsFromDeviceWallpaper => 'Pilih Warna dari Wallpaper Perangkat';

  @override
  String get pickFromStorage => 'Pilih dari penyimpanan';

  @override
  String get pinned => 'Disematkan';

  @override
  String get pitch => 'Nada';

  @override
  String get plain => 'Polos';

  @override
  String get play => 'Putar';

  @override
  String get playAfter => 'Mainkan Setelah';

  @override
  String get playAfterNextPrev => 'Putar Otomatis pada Berikutnya/Sebelumnya';

  @override
  String get playAll => 'Mainkan Semua';

  @override
  String get playFadeDuration => 'Putar Durasi Pudar';

  @override
  String get playLast => 'Mainkan Terakhir';

  @override
  String get playNext => 'Mainkan Berikutnya';

  @override
  String get playbackSetting => 'Pemutaran';

  @override
  String get playbackSettingSubtitle => 'Dapat diakses langsung di player dengan menekan lama tombol audio';

  @override
  String get playlist => 'Daftar Putar';

  @override
  String get playlists => 'Daftar Putar';

  @override
  String get playlistsImportM3uNative => 'Ini akan mengimpor daftar putar M3U untuk digunakan hanya oleh namida, gunakan jika Anda bermigrasi';

  @override
  String get playlistsImportM3uSynced =>
      'Ini akan secara otomatis mengimpor daftar putar M3U dari folder pengindeks dan menjaganya tetap sinkron dengan file M3U asli. aktifkan jika Anda mengakses/memodifikasi daftar putar dari aplikasi lain';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Impor otomatis Daftar Putar M3U';

  @override
  String get pleaseEnterADifferentName => 'Nama ini sudah ada :(\nsilahkan coba nama lain yang menarik';

  @override
  String get pleaseEnterALink => 'Silakan masukkan tautan';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. apakah ini tautan youtubenya?';

  @override
  String get pleaseEnterAName => 'Silakan masukkan nama';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Cegah trek Duplikasi';

  @override
  String get preventDuplicatedTracksSubtitle => 'Menggunakan nama file untuk mengidentifikasi trek secara unik';

  @override
  String get preview => 'Pratinjau';

  @override
  String get previous => 'Sebelumnya';

  @override
  String get previousButtonReplays => 'Tombol sebelumnya diputar ulang';

  @override
  String get previousButtonReplaysSubtitle => 'jika ditekan saat posisi ini melebihi durasi pencarian';

  @override
  String get prioritizeEmbeddedLyrics => 'Prioritaskan lirik yang disematkan';

  @override
  String get priority => 'Prioritas';

  @override
  String get private => 'Pribadi';

  @override
  String get progress => 'Kemajuan';

  @override
  String get promptToChangeTrackPath => 'Biasanya ini terjadi ketika Anda menghapus/memindahkan/mengganti nama file di luar namida, Apakah Anda ingin memperbarui jalur saat ini?';

  @override
  String get public => 'Publik';

  @override
  String get queue => 'Antrean';

  @override
  String get queues => 'Antrian';

  @override
  String get random => 'Acak';

  @override
  String get randomPicks => 'Pilihan Acak';

  @override
  String get rating => 'Peringkat';

  @override
  String get reIndex => 'Indeks ulang';

  @override
  String get reIndexSubtitle => 'Bangun kembali pustaka musik Anda dari awal';

  @override
  String get reIndexWarning => 'Proses ini mungkin memakan waktu cukup lama, bergantung pada ukuran pustaka Anda.\n\nGambar tidak akan diindeks ulang selama masih ada';

  @override
  String get recentAlbums => 'Album Terbaru';

  @override
  String get recentArtists => 'Artis Terbaru';

  @override
  String get recentListens => 'Baru diputar';

  @override
  String get recentlyAdded => 'Baru-baru ini ditambahkan';

  @override
  String get recordLabel => 'Label Rekaman';

  @override
  String get refresh => 'Menyegarkan';

  @override
  String get refreshLibrary => 'Segarkan Pustaka';

  @override
  String get refreshLibrarySubtitle => 'Periksa musik yang baru ditambahkan atau dihapus';

  @override
  String get refreshOnStartup => 'Segarkan saat memulai';

  @override
  String get relatedVideos => 'Video terkait';

  @override
  String get rememberAudioOnlyMode => 'Ingat mode audio saja';

  @override
  String get remixer => 'Pembuat remix';

  @override
  String get remove => 'Menghapus';

  @override
  String get removeDuplicates => 'Hapus Duplikat';

  @override
  String get removeFromFavourites => 'Hapus dari favorit';

  @override
  String get removeFromLibrary => 'Hapus dari pustaka';

  @override
  String get removeFromPlaylist => 'Hapus Dari Daftar Putar';

  @override
  String get removeQueue => 'Hapus Antrean';

  @override
  String get removeSourceFromHistory => 'Hapus sumber dari riwayat';

  @override
  String get removeWhitespaces => 'Hapus Spasi Putih';

  @override
  String get removed => 'Dihapus';

  @override
  String get rename => 'Ganti nama';

  @override
  String get renamePlaylist => 'Ganti nama Daftar Putar';

  @override
  String get reorderable => 'Dapat direkam';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ulangi sebanyak $number kali lagi',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Mode ulangi';

  @override
  String get repeatModeAll => 'Ulangi Semua Antrian';

  @override
  String get repeatModeNone => 'Berhenti di Trek Terakhir';

  @override
  String get repeatModeOne => 'Ulangi Lagu Saat Ini';

  @override
  String get replaceAllListensWithAnotherTrack => 'Ganti semua lagu yang didengarkan dengan lagu lain';

  @override
  String get replies => 'Balasan';

  @override
  String get reply => 'Balas';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Memerlukan pembersihan cache gambar dan pengindeksan ulang';

  @override
  String get rescanVideos => 'Pindai ulang video';

  @override
  String get resetBrightness => 'Atur ulang kecerahan';

  @override
  String get resetToDefault => 'Mulai dari';

  @override
  String get respectNoMedia => 'Kecualikan .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Jangan sertakan folder yang memiliki .nomedia';

  @override
  String get restart => 'Mulai ulang';

  @override
  String get restoreBackup => 'Pulihkan Cadangan';

  @override
  String get restoreDefaults => 'Kembalikan Default';

  @override
  String get restoredBackupSuccessfully => 'Cadangan yang Dipulihkan';

  @override
  String get restoredBackupSuccessfullySub => 'File cadangan telah berhasil dipulihkan';

  @override
  String get resume => 'Lanjutkan';

  @override
  String get resumeIfWasInterrupted => 'Lanjutkan jika dijeda karena gangguan';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Lanjutkan jika dijeda berdasarkan volume';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Lanjutkan jika dijeda kurang dari $numberString menit',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Balik Urutan';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Nada dering';

  @override
  String get sameDirectoryOnly => 'Hanya direktori yang sama';

  @override
  String get sample => 'Contoh';

  @override
  String get sampleRate => 'Tingkat Sampel';

  @override
  String get save => 'Simpan';

  @override
  String get saveToLibrary => 'Simpan ke pustaka';

  @override
  String get savedIn => 'Disimpan di';

  @override
  String get scaleMultiplier => 'Skala Ganda';

  @override
  String get search => 'Pencarian';

  @override
  String get searchYoutube => 'Cari di YouTube';

  @override
  String get seconds => 'detik';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Durasi Pencarian';

  @override
  String get seekDurationInfo => 'Anda dapat mengetuk durasi saat ini untuk mencari mundur & total durasi untuk mencari maju';

  @override
  String get seekbar => 'Bilah Pencarian';

  @override
  String get selectAll => 'Pilih Semua';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'File yang dipilih sudah siap di pustaka lokal';

  @override
  String get selectedTracks => 'Trek yang Dipilih';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Kata-kata ini tidak akan terpecah';

  @override
  String get separatorsMessage => 'Tidak perlu menyisipkan spasi, kecuali jika ingin menggunakan huruf/simbol yang terdapat pada keseluruhan kata (seperti x dan ft.)';

  @override
  String get serverAddress => 'Alamat server';

  @override
  String get setAs => 'Ditetapkan sebagai';

  @override
  String get setAsDefault => 'Ditetapkan sebagai default';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Tetapkan file yang terakhir diubah sebagai tanggal pengunggahan video';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Tetapkan Atmosfer';

  @override
  String get setMoodsSubtitle => 'Gunakan koma (,) untuk memisahkannya';

  @override
  String get setRating => 'Tetapkan Peringkat';

  @override
  String get setTags => 'Tetapkan Label';

  @override
  String get setYoutubeLink => 'Setel Tautan Youtube';

  @override
  String get settings => 'Pengaturan';

  @override
  String get setupFirstStartup => 'Siapkan penyetelan awal';

  @override
  String get share => 'Bagikan';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Pintasan';

  @override
  String get shouldDuck => 'Harus menunduk';

  @override
  String get shouldDuckNote => 'Menunjukkan bahwa volumenya harus diturunkan. contoh: pemberitahuan';

  @override
  String get shouldPause => 'Harus dijeda';

  @override
  String get shouldPauseNote => 'Menunjukkan bahwa pemutaran harus dijeda. contoh: panggilan';

  @override
  String get showAll => 'Tampilkan Semua';

  @override
  String get showChannelWatermarkInFullscreen => 'Tampilkan tanda air saluran dalam layar penuh';

  @override
  String get showFailedOnly => 'Hanya Tampilkan yang Gagal';

  @override
  String get showHideUnknownFields => 'Tampilkan/sembunyikan Bidang Tidak Dikenal';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Tampilkan Mix di';

  @override
  String get showMore => 'Tampilkan lebih banyak';

  @override
  String get showShortVideosIn => 'Tampilkan Shorts di';

  @override
  String get showSkipButton => 'Tampilkan tombol lewati';

  @override
  String get showVideoEndcards => 'Tampilkan kartu akhir video';

  @override
  String get showWebm => 'Tampilkan webm';

  @override
  String get shuffle => 'Acak';

  @override
  String get shuffleAll => 'Acak Semua';

  @override
  String get shuffleNext => 'Acak Berikutnya';

  @override
  String get signIn => 'Masuk';

  @override
  String get signInCanceled => 'Proses masuk dibatalkan';

  @override
  String get signInFailed => 'Gagal masuk';

  @override
  String get signInToYourAccount => 'Masuk ke akun Anda';

  @override
  String get signInYouDontHaveAccount => 'Anda tidak memiliki akun yang masuk';

  @override
  String get signInYouNeedAccountToViewPage => 'Anda memerlukan akun untuk melihat halaman ini';

  @override
  String get signOut => 'Keluar';

  @override
  String signOutFromName({required String name}) {
    return 'Keluar dari $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Masuk memungkinkan penggunaan dasar';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Dapatkan akses awal melalui patreon atau dengan menggunakan kupon';

  @override
  String get similarDiscoverDate => 'Tanggal ditemukan serupa';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Rentang waktu serupa';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Buat lagu yang kamu dengarkan di waktu yang sama dengan $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'Ukuran';

  @override
  String get skip => 'Lewati';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Lewati Keheningan';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Tidur Setelah';

  @override
  String get sleepTimer => 'Pengatur waktu tidur';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Sortir dengan';

  @override
  String get source => 'Sumber';

  @override
  String get speed => 'Kecepatan';

  @override
  String get sponsor => 'Iklan';

  @override
  String get sponsorblock => 'Blokir iklan';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Tampilkan kisi Terhuyung';

  @override
  String get start => 'Mulai';

  @override
  String get stats => 'Statistik';

  @override
  String get statsSubtitle => 'Berikut ini beberapa info tentang pustaka Anda';

  @override
  String get stop => 'Henti';

  @override
  String get stopAfterThisTrack => 'Berhenti setelah trek ini';

  @override
  String get stopAfterThisVideo => 'Berhenti setelah video ini';

  @override
  String get storagePermissionDenied => 'Izin ditolak';

  @override
  String get storagePermissionDeniedSubtitle => 'Harap beri izin akses untuk dapat melakukan tindakan ini';

  @override
  String get stretchLyricsDuration => 'Stretch Lyrics Duration';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Subscribe';

  @override
  String get subscribed => 'Berlangganan';

  @override
  String get subscriber => 'Pelanggan';

  @override
  String get subscribers => 'Pelanggan';

  @override
  String get succeeded => 'Berhasil';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Mendukung';

  @override
  String get supremacy => 'Supremasi';

  @override
  String get sussyBaka => 'Bruh tidak trek';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Geser untuk membuka laci';

  @override
  String get synced => 'Disinkronkan';

  @override
  String get synopsis => 'Ringkasan';

  @override
  String get tagFields => 'Bidang Label';

  @override
  String get tags => 'Label';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Ketuk untuk mencari';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Mode Tema';

  @override
  String get themeModeDark => 'Gelap';

  @override
  String get themeModeLight => 'Terang';

  @override
  String get themeModeSystem => 'Sistem';

  @override
  String get themeSettings => 'Tema';

  @override
  String get themeSettingsSubtitle => 'Sesuaikan suasana tema keseluruhan pemutar Anda';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Playlist ini memiliki pengurutan yang masih aktif, silahkan matikan ini sebelum mengurutkan ulang.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Video ini sepertinya telah dihapus atau diatur ke privat.';

  @override
  String get thumbnails => 'Thumbnail';

  @override
  String get title => 'Judul';

  @override
  String get top => 'Teratas';

  @override
  String get topComments => 'Komentar teratas';

  @override
  String get topCommentsSubtitle => 'Tampilkan komentar di teratas, bukan paling bawah';

  @override
  String get topRecentAlbums => 'Album Terbaru Teratas';

  @override
  String get topRecentArtists => 'Artis Terkini Teratas';

  @override
  String get topRecents => 'Terbaru dan Teratas';

  @override
  String get totalListenTime => 'Total Waktu Mendengarkan';

  @override
  String get totalListens => 'Total Mendengarkan';

  @override
  String get totalTracks => 'Jumlah Lagu';

  @override
  String get totalTracksDuration => 'Total Durasi Lagu';

  @override
  String get track => 'Trek';

  @override
  String get trackArtistsSeparator => 'Pemisah Artis';

  @override
  String get trackGenresSeparator => 'Pemisah Genre';

  @override
  String get trackInfo => 'Informasi Trek';

  @override
  String get trackNotFound => 'Lagu tidak ditemukan';

  @override
  String get trackNumber => 'Nomor Trek';

  @override
  String get trackNumberTotal => 'Total Trek';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Nama lama: \"$oldName\"\n\nNama baru: \"$newName\"\n\nApakah Anda yakin?';
  }

  @override
  String get trackPlayMode => 'Mode Putar';

  @override
  String get trackPlayModeSearchResults => 'Hasil Pencarian';

  @override
  String get trackPlayModeSelectedOnly => 'Hanya trek yang dipilih';

  @override
  String get trackPlayModeTrackAlbum => 'Album Lagu';

  @override
  String get trackPlayModeTrackArtist => 'Artis Utama Lagu';

  @override
  String get trackPlayModeTrackGenre => 'Genre Lagu';

  @override
  String get trackThumbnailSizeInList => 'Ukuran Thumbnail Lagu';

  @override
  String get trackTileCustomization => 'Kustomisasi Ubin Trek';

  @override
  String get trackTileItemsSeparator => 'Pemisah Item';

  @override
  String get tracks => 'Trek';

  @override
  String get tracksExcludedByNomedia => 'Lagu yang Dikecualikan oleh .nomedia';

  @override
  String get tracksInfo => 'Info Trek';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Membuka';

  @override
  String get undoChanges => 'Batalkan perubahan?';

  @override
  String get undoChangesDeletedPlaylist => 'Batalkan Daftar Putar yang dihapus';

  @override
  String get undoChangesDeletedQueue => 'Batalkan Antrean yang dihapus';

  @override
  String get undoChangesDeletedTrack => 'Batalkan Trek yang dihapus';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Tak terbatas';

  @override
  String get unlisted => 'Tidak terdaftar';

  @override
  String get unlock => 'Membuka kunci';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Memperbarui';

  @override
  String get updateDirectoryPath => 'Perbarui jalur direktori';

  @override
  String get updateMissingTracksOnly => 'Perbarui trek yang hilang saja';

  @override
  String get updating => 'Memperbarui';

  @override
  String get useCollapsedSettingTiles => 'Gunakan Ubin Pengaturan yang Diciutkan';

  @override
  String get useMediaStore => 'Gunakan Penyimpanan Media';

  @override
  String get useMediaStoreSubtitle =>
      '✓ waktu pengindeksan instan\nx pengecualian .nomedia akan diaktifkan secara paksa\nx beberapa label metadata akan hilang\nx integrasi youtube untuk pustaka lokal tidak akan berfungsi';

  @override
  String get usePitchBlack => 'Gunakan Pitch Black';

  @override
  String get usePitchBlackSubtitle => 'Berguna untuk layar AMOLED.. dan terlihat lebih keren';

  @override
  String get used => 'Digunakan';

  @override
  String get value => 'Nilai (Value)';

  @override
  String get valueBetween50200 => 'Nilainya harus antara 50% dan 200%';

  @override
  String get vibration => 'Getaran';

  @override
  String get vibrationType => 'Jenis getaran';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Cache Video';

  @override
  String get videoCacheFile => 'File Cache Video';

  @override
  String get videoCacheFiles => 'File Cache Video';

  @override
  String get videoOnly => 'Hanya Video';

  @override
  String get videoPlaybackSource => 'Sumber Video';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Ini akan mengutamakan video lokal, jika tidak ditemukan maka akan diambil dari youtube';

  @override
  String get videoPlaybackSourceLocal => 'Video Lokal';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Memeriksa apakah ada file video (ditemukan di dalam daftar folder yang dipilih) memiliki nama file yang berisi nama file trek';

  @override
  String get videoPlaybackSourceYoutube => 'Dari Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Periksa nama file trek & komentar untuk tautan youtube yang cocok, video di-cache untuk digunakan nanti.';

  @override
  String get videoQuality => 'Kualitas Video';

  @override
  String get videoQualitySubtitle => 'Kualitas tertinggi yang tersedia akan dipilih.';

  @override
  String get videoQualitySubtitleNote => 'Sebaiknya simpan lebih banyak alternatif jika kualitas tidak ditemukan, jika tidak maka kualitas akan kembali ke kualitas terburuk';

  @override
  String get videos => 'Video';

  @override
  String get view => 'Lihat';

  @override
  String get viewAll => 'Lihat semua';

  @override
  String get views => 'Tampilan';

  @override
  String get volume => 'Volume';

  @override
  String get warning => 'Peringatan';

  @override
  String get waveformBarsCount => 'Jumlah Bar Bergelombang';

  @override
  String get webmNoEditTagsSupport => 'Format WEBM tidak mendukung pengeditan label';

  @override
  String get week => 'Pekan';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Tahun';

  @override
  String get yes => 'Ya';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Keanggotaan Anda saat ini adalah $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Pengurutan kustommu akan hilang, Yakin?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Musik';

  @override
  String get youtubeSettingsSubtitle => 'Sesuaikan pengalaman Youtube';

  @override
  String get youtubeStyleMiniplayer => 'Miniplayer ala Youtube';

  @override
  String get ytPreferNewComments => 'Tampilkan komentar terbaru jika memungkinkan';

  @override
  String get ytPreferNewCommentsSubtitle => 'Versi cache hanya akan digunakan ketika tidak ada koneksi';
}
