// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Russian (`ru`).
class AppLocalizationsRu extends AppLocalizations {
  AppLocalizationsRu([String locale = 'ru']) : super(locale);

  @override
  String get about => 'О приложении';

  @override
  String get active => 'Активный';

  @override
  String get add => 'Добавить';

  @override
  String get addAccount => 'Добавить аккаунт';

  @override
  String get addAll => 'Добавить всё';

  @override
  String get addAllAndRemoveOldOnes => 'Добавить всё и удалить устаревшее';

  @override
  String get addAsANewPlaylist => 'Добавить как новый Плейлист';

  @override
  String get addAudioToLocalLibrary => 'Добавить аудио в локальную библиотеку';

  @override
  String get addFolder => 'Добавить Папку';

  @override
  String get addLanguage => 'Добавить Язык';

  @override
  String get addLanguageSubtitle => 'Помоги перевести Namida на твой язык';

  @override
  String get addLrcFile => 'Добавить LRC-файл';

  @override
  String get addMoreFromThisAlbum => 'Добавить ещё из этого Альбома в очередь';

  @override
  String get addMoreFromThisArtist => 'Добавить ещё от этого Исполнителя в очередь';

  @override
  String get addMoreFromThisFolder => 'Добавить ещё из этой Папки в очередь';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Добавить ещё из $media в очередь';
  }

  @override
  String get addOnlyMissing => 'Добавить только отсутствующие';

  @override
  String get addToFavourites => 'Добавить в избранное';

  @override
  String get addToPlaylist => 'Добавить в Плейлист';

  @override
  String get addTracksAtTheBeginning => 'Добавить треки в начало';

  @override
  String get added => 'добавлено';

  @override
  String get advanced => 'Продвинутое';

  @override
  String get advancedSettings => 'Продвинутые';

  @override
  String get advancedSettingsSubtitle => 'Продвинутые настройки, не трогай';

  @override
  String get alarm => 'Будильник';

  @override
  String get album => 'Альбом';

  @override
  String get albumArtist => 'Исполнитель Альбома';

  @override
  String get albumArtists => 'Исполнители Альбома';

  @override
  String get albumIdentifiers => 'Идентификаторы Альбомов';

  @override
  String get albumThumbnailSizeInList => 'Размер Миниатюры Альбома';

  @override
  String get albumTileCustomization => 'Настройка Плитки Альбома';

  @override
  String get albums => 'Альбомы';

  @override
  String get albumsCount => 'Количество Альбомов';

  @override
  String get all => 'Всё';

  @override
  String get allTime => 'За всё время';

  @override
  String get alreadyExists => 'Уже существует';

  @override
  String get always => 'Всегда';

  @override
  String get alwaysAsk => 'Всегда спрашивать';

  @override
  String get alwaysDim => 'Всегда Затемнять';

  @override
  String get alwaysExpandedSearchbar => 'Всегда Раскрытая Панель поиска';

  @override
  String get alwaysRestore => 'Всегда восстанавливать';

  @override
  String get animatingThumbnailIntensity => 'Интенсивность Анимации Миниатюр';

  @override
  String get animatingThumbnailInversed => 'Инверсия Анимации';

  @override
  String get animatingThumbnailInversedSubtitle => 'Высокие пики громкости приведут к уменьшению размера миниатюры';

  @override
  String get anotherProcessIsRunning => 'Другой процесс уже запущен.';

  @override
  String get appIcon => 'Иконка Приложения';

  @override
  String get appVersion => 'Версия приложения';

  @override
  String get artist => 'Исполнитель';

  @override
  String get artists => 'Исполнители';

  @override
  String get artwork => 'Обложка';

  @override
  String get artworkGestures => 'Жесты Обложек';

  @override
  String get artworks => 'Обложки';

  @override
  String get audio => 'Аудио';

  @override
  String get audioCache => 'Кэш Аудио';

  @override
  String get audioOnly => 'Только Аудио';

  @override
  String get auto => 'Автоматически';

  @override
  String get autoBackupInterval => 'Интервал автоматических резервных копий';

  @override
  String get autoColoring => 'Автораскраска';

  @override
  String get autoColoringSubtitle => 'Автовыбор цветов плеера на основе обложек';

  @override
  String get autoExtractTagsFromFilename => 'Автоматически извлечь из имени файла';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Автоматически извлекать Название и Исполнителя из названия видео';

  @override
  String get autoGenerated => 'Автоматически Сгенерированный';

  @override
  String get autoSkip => 'Автоматически пропустить';

  @override
  String get autoSkipOnce => 'Автоматически пропустить единожды';

  @override
  String get autoStartRadio => 'Автозапуск радио';

  @override
  String get autoStartRadioSubtitle => 'Автоматически добавляет смешанный плейлист при воспроизведении одного трека';

  @override
  String get automaticBackup => 'Автоматическое';

  @override
  String get automaticBackupSubtitle => 'Автоматически применяется последний файл резервной копии, найденный в хранилище';

  @override
  String get backupAndRestore => 'Резервное копирование и Восстановление';

  @override
  String get backupAndRestoreSubtitle => 'Резервное копирование базы данных и настроек';

  @override
  String get balanced => 'Сбалансированный';

  @override
  String get beta => 'Бета';

  @override
  String get betweenDates => 'Между Датами';

  @override
  String get bitrate => 'Битрейт';

  @override
  String get blacklist => 'Чёрный список';

  @override
  String get borderRadiusMultiplier => 'Множитель Радиуса Границ';

  @override
  String get cache => 'Кэш';

  @override
  String get cancel => 'Отмена';

  @override
  String get canceled => 'Отменено';

  @override
  String get changed => 'Изменено';

  @override
  String get changelog => 'Список изменений';

  @override
  String get changelogSubtitle => 'Посмотри, что нового добавили и исправили в Namida';

  @override
  String get channel => 'Канал';

  @override
  String get channels => 'Каналы';

  @override
  String get check => 'Проверить';

  @override
  String get checkForMore => 'Подробнее';

  @override
  String get checkList => 'Контрольный Список';

  @override
  String get choose => 'Выбрать';

  @override
  String get chooseWhatToClear => 'Выбери, что очистить';

  @override
  String get claim => 'Запросить';

  @override
  String get clear => 'Очистить';

  @override
  String get clearAudioCache => 'Очистить Кэш Аудио';

  @override
  String get clearImageCache => 'Очистить Кэш изображений';

  @override
  String get clearImageCacheWarning => 'Предупреждение: будет создана библиотека без изображений. Используй только для перестройки кэша изображений.';

  @override
  String get clearTrackItem => 'Удаление у Трека';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString треков',
      few: '$numberString трека',
      one: '$numberString трек',
    );
    return 'Очистить $_temp0';
  }

  @override
  String get clearVideoCache => 'Очистить Кэш Видео';

  @override
  String get clearVideoCacheNote => 'Ты можешь выбрать, что удалить.';

  @override
  String get clock => 'Часы';

  @override
  String get colorPalette => 'Цветовая Палитра';

  @override
  String get colorPaletteNote1 => 'Удерживайте по цвету, чтобы убрать его';

  @override
  String get colorPaletteNote2 => 'Нажми на микс, чтобы использовать его в качестве цвета по умолчанию';

  @override
  String get colorPalettes => 'Цветовые Палитры';

  @override
  String get comment => 'Комментарий';

  @override
  String get comments => 'Комментарии';

  @override
  String get composer => 'Композитор';

  @override
  String get compress => 'Сжать';

  @override
  String get compressImages => 'Сжать Изображения';

  @override
  String get compressionPercentage => 'Процент сжатия';

  @override
  String get configure => 'Настроить';

  @override
  String get confirm => 'ОК';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Обложка скопирована';

  @override
  String get copiedToClipboard => 'Скопировано в Буфер обмена';

  @override
  String get copy => 'Скопировать';

  @override
  String get corruptedFile => 'Не удалось прочесть файл. Возможно, он повреждён';

  @override
  String get couldntOpen => 'Не удалось открыть :(';

  @override
  String get couldntOpenYtLink => 'Для данного трека не установлена YouTube-ссылка';

  @override
  String get couldntPlayFile => 'Не удалось воспроизвести файл';

  @override
  String get couldntRenamePlaylist => 'Не удалось переименовать плейлист';

  @override
  String get couldntSaveImage => 'Не удалось сохранить изображение';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Исполнителей',
      few: '$countString Исполнителя',
      one: '$countString Исполнитель',
    );
    return '$_temp0 Альбома';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Альбомов',
      few: '$countString Альбома',
      one: '$countString Альбом',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Исполнителей',
      few: '$countString Исполнителя',
      one: '$countString Исполнитель',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Композиторов',
      few: '$countString Композитора',
      one: '$countString Композитор',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString дня',
      many: '$countString дней',
      few: '$countString дня',
      one: '$countString день',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString файлов',
      few: '$countString файла',
      one: '$countString файл',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString папок',
      few: '$countString папки',
      one: '$countString папка',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString жанров',
      few: '$countString жанра',
      one: '$countString жанр',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString месяца',
      many: '$countString месяцев',
      few: '$countString месяца',
      one: '$countString месяц',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString плейлистов',
      few: '$countString плейлиста',
      one: '$countString плейлист',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString подписчиков',
      few: '$countString подписчика',
      one: '$countString подписчик',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString подписчиков',
      few: '$countString подписчика',
      one: '$countString подписчик',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString треков',
      few: '$countString трека',
      one: '$countString трек',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString видео',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString просмотров',
      few: '$countString просмотра',
      one: '$countString просмотр',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString просмотров',
      few: '$countString просмотра',
      one: '$countString просмотр',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Страна';

  @override
  String get coupon => 'Купон';

  @override
  String get create => 'Создать';

  @override
  String get createBackup => 'Создать Резервную копию';

  @override
  String get createNewPlaylist => 'Создать новый Плейлист';

  @override
  String get createdBackupSuccessfully => 'Резервная копия создана';

  @override
  String get createdBackupSuccessfullySub => 'Резервная копия была создана успешно';

  @override
  String get crossPlatformSync => 'Кроссплатформенная синхронизация';

  @override
  String get crossfadeDuration => 'Длительность Затухающего перехода';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'последние $secondsString секунд',
      few: 'последние $secondsString секунды',
      one: 'последнюю $secondsString секунду',
    );
    return 'Автоматическое включение Затухающего перехода за $_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Не запускать затухающий переход автоматически';

  @override
  String get custom => 'Пользовательский';

  @override
  String get customizations => 'Персонализация';

  @override
  String get customizationsSubtitle => 'Настройте внешний вид своего плеера под себя';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Данные от: $name';
  }

  @override
  String get dataSaver => 'Оптимизатор Трафика';

  @override
  String get dataSaverMode => 'Режим Оптимизации Трафика';

  @override
  String get database => 'База данных';

  @override
  String get date => 'Дата';

  @override
  String get dateAdded => 'Дата Добавления';

  @override
  String get dateCreated => 'Дата Создания';

  @override
  String get dateModified => 'Дата Изменения';

  @override
  String get dateTimeFormat => 'Формат даты и времени';

  @override
  String get day => 'День';

  @override
  String get days => 'Дня';

  @override
  String get defaultBackupLocation => 'Расположение Резервных копий по Умолчанию';

  @override
  String get defaultColor => 'Тема по Умолчанию';

  @override
  String get defaultColorSubtitle => 'Установка цвета, который будет использоваться плеером';

  @override
  String get defaultDownloadLocation => 'Папка для Скачивания по Умолчанию';

  @override
  String get defaultLabel => 'По умолчанию';

  @override
  String get defaultLibraryTab => 'Категория по умолчанию';

  @override
  String get delete => 'Удалить';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString файлов, которые занимают',
      few: '$countString файла, которые занимают',
      one: '$countString файл, который занимает',
    );
    return 'Удалить $_temp0 $totalSizeText?';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Навсегда удалить $numberText из твоего хранилища';
  }

  @override
  String get deletePlaylist => 'Удалить Плейлист';

  @override
  String get deleteTempFiles => 'Удалить временные файлы';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Описание';

  @override
  String get developer => 'Разработчик';

  @override
  String get development => 'Разработка';

  @override
  String get didYouMean => 'Может, ты имел ввиду';

  @override
  String get dimIntensity => 'Интенсивность Затемнения';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString секунд',
      one: '$secondsString секунды',
    );
    return 'Затемнять миниплеер после $_temp0 бездействия';
  }

  @override
  String get directoryDoesntExist => 'Каталог не существует';

  @override
  String get disable => 'Отключить';

  @override
  String get disableAll => 'Отключить все';

  @override
  String get disableReordering => 'Отключить Переупорядочивание';

  @override
  String get disableSearchCleanup => 'Отключить Очистку Поиска';

  @override
  String get discNumber => 'Номер Диска';

  @override
  String get discNumberTotal => 'Всего дисков';

  @override
  String get discover => 'Найти';

  @override
  String get dislike => 'Не нравится';

  @override
  String get dismissibleMiniplayer => 'Закрываемый миниплеер';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Отображать текущую позицию при прокрутке вместо разницы';

  @override
  String get displayAlbumCardTopRightDate => 'Дата Карточки Альбома в правом верхнем углу';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Отображать дату Альбома в правом верхнем углу Карточки Альбома';

  @override
  String get displayArtistBeforeTitle => 'Отображать исполнителя перед названием';

  @override
  String get displayArtworkOnLockscreen => 'Отображать обложку на экране блокировки';

  @override
  String get displayAudioInfoInMiniplayer => 'Отображать Информацию об Аудио';

  @override
  String get displayFavButtonInNotification => 'Отображать кнопку \"Избранное\" в Уведомлениях';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Миниатюра может быть смещена.';

  @override
  String get displayFavouriteIconInTrackTile => 'Отображать Кнопку \"Избранное\"';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Отображать оставшуюся продолжительности вместо общей';

  @override
  String get displayStopButtonInNotification => 'Показывать Кнопку \"Стоп\" в Уведомлениях';

  @override
  String get displayThirdItemInRowInTrackTile => 'Отображать Третий Элемент в каждом Ряду';

  @override
  String get displayThirdRowInTrackTile => 'Отображать Третий Ряд';

  @override
  String get displayTrackNumberInAlbumPage => 'Отображать номер Трека на странице Альбома';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Отображать небольшое поле с номером трека на странице альбома';

  @override
  String get doNothing => 'Ничего не делать';

  @override
  String get donate => 'Пожертвовать';

  @override
  String get donateSubtitle => 'Если считаешь, что это того стоит';

  @override
  String get done => 'Готово';

  @override
  String get dontAskAgain => 'Больше не спрашивать';

  @override
  String get dontDim => 'Не Затемнять';

  @override
  String get dontRestorePosition => 'Не восстанавливать';

  @override
  String get dontResume => 'Не продолжать воспроизведение';

  @override
  String get doubleTapToToggleLyrics => 'Двойной тап для отображения текста песни';

  @override
  String get download => 'Скачать';

  @override
  String get downloadingWillOverrideIt => 'Загрузка перезапишет его';

  @override
  String get downloads => 'Загрузки';

  @override
  String get downloadsMetadataTags => 'Скачивать теги Метаданных';

  @override
  String get downloadsMetadataTagsSubtitle => 'Извлекать исполнителя, название и альбом из информации о видео по умолчанию';

  @override
  String get dragToSeek => 'Переместить для перемотки';

  @override
  String get duckAudio => 'Приглушать аудио';

  @override
  String get duplicatedItemsAdding => 'Ты пытаешься добавить элементы, что уже есть в плейлисте';

  @override
  String get duplicatedTracks => 'Дублированные Треки';

  @override
  String get duration => 'Продолжительность';

  @override
  String get edgeColorsSwitching => 'Переключение Цветов по Краям';

  @override
  String get edit => 'Редактировать';

  @override
  String get editArtwork => 'Редактировать Обложку';

  @override
  String get editTags => 'Редактировать Теги';

  @override
  String get email => 'Почта';

  @override
  String get emptyNonMeaningfulTagFields => 'у тебя есть поля с пустыми/незначительными значениями, убедись, что ты действительно хочешь их редактировать';

  @override
  String get emptyValue => 'Пустое Значение';

  @override
  String get enableArtworkCache => 'Включить кэш обложек';

  @override
  String get enableArtworkCacheSubtitle => 'Загрузка становится быстрее и улучшается производительность, однако используется больше места на хранилище';

  @override
  String get enableBlurEffect => 'Включить Эффект Размытия';

  @override
  String get enableBottomNavBar => 'Включить Нижнюю Панель Навигации';

  @override
  String get enableBottomNavBarSubtitle => 'Элементы в обоих диалоговых окнах';

  @override
  String get enableClipboardMonitoring => 'Включить Мониторинг Буфера обмена';

  @override
  String get enableClipboardMonitoringSubtitle => 'Позволяет вставлять ссылки и текст в строку поиска на лету';

  @override
  String get enableCrossfadeEffect => 'Включить эффект перехода с затуханием';

  @override
  String get enableFadeEffectOnPlayPause => 'Включение эффекта затухания при воспроизведении/паузе';

  @override
  String get enableFoldersHierarchy => 'Включить иерархию папок';

  @override
  String get enableGlowEffect => 'Включить эффект свечения';

  @override
  String get enableM3uSync => 'Включить синхронизацию M3U';

  @override
  String get enableM3uSyncNote1 => 'Синхронизация M3U позволяет сохранять изменения плейлиста в оригинальном M3U-файле';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Если что-то пошло не так, резервную копию этого плейлиста можно будет найти в $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'В случае отказа все изменения, сделанные в этом плейлисте, будут потеряны при перезапуске';

  @override
  String get enableMiniplayerParticles => 'Включить движущиеся частицы';

  @override
  String get enableParallaxEffect => 'Включить Эффект Параллакса';

  @override
  String get enablePartyMode => 'Включить режим вечеринки';

  @override
  String get enablePartyModeSubtitle => 'Включить прикольный эффект дыхания граней';

  @override
  String get enablePictureInPicture => 'Включить \"Картинку в картинке\"';

  @override
  String get enableReordering => 'Разрешить Переупорядочивание';

  @override
  String get enableReturnYoutubeDislike => 'Включить Дизлайки';

  @override
  String get enableSearchCleanup => 'Включить Очистку Поиска';

  @override
  String get enableSearchCleanupSubtitle => 'Все Символы и Пробелы будут проигнорированы';

  @override
  String get enableSponsorblock => 'Включить SponsorBlock';

  @override
  String get enableVideoPlayback => 'Включить Воспроизведение Видео';

  @override
  String get enterSymbol => 'Пожалуйста, Введите Символ';

  @override
  String get equalizer => 'Эквалайзер';

  @override
  String get error => 'Ошибка';

  @override
  String get errorFetchingVideoList => 'Ошибка анализа списка видео';

  @override
  String get errorPlayingTrack => 'Ошибка воспроизведении трека';

  @override
  String get excludedFodlers => 'Исключённые Папки';

  @override
  String get exit => 'Выход';

  @override
  String get exitAppSubtitle => 'Нажми ещё раз, чтобы выйти';

  @override
  String get expandedMiniplayer => 'Раскрытый Миниплеер';

  @override
  String get exportAsM3u => 'Экспорт в формате M3U';

  @override
  String get extension => 'Расширение';

  @override
  String get externalFiles => 'Внешние Файлы';

  @override
  String get extract => 'Извлечь';

  @override
  String get extractAllColorPalettes => 'Извлечь все цветовые палитры';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'оставшиеся $numberString',
      one: 'оставшийся $numberString',
    );
    return 'Извлечь $_temp0?';
  }

  @override
  String get extractFeatArtist => 'Извлечь исполнителей из названия';

  @override
  String get extractFeatArtistSubtitle => 'Извлечь (feat. X) и (ft. X) исполнителей в виде записи нового исполнителя.';

  @override
  String get extractingInfo => 'Извлечение информации';

  @override
  String get extras => 'Дополнительно';

  @override
  String get extrasSubtitle => 'Дополнительные Настройки для улучшения твоего опыта';

  @override
  String get extreme => 'Экстримальный';

  @override
  String get failed => 'Не удалось';

  @override
  String get failedEdits => 'Неудачные изменения';

  @override
  String get favourites => 'Избранные';

  @override
  String get features => 'Особенности';

  @override
  String get fetching => 'Извлечение';

  @override
  String get fetchingOfAllVideos => 'Извлечь из всех видео';

  @override
  String get file => 'Файл';

  @override
  String get fileAlreadyExists => 'Файл уже существует';

  @override
  String get fileBasedServerWarning =>
      'Файлы будут временно загружены на индексацию. Убедись, что соединение стабильно.\nРекомендуется использовать WiFi, чтобы избежать большого трафика.';

  @override
  String get fileName => 'Имя Файла';

  @override
  String get fileNameWoExt => 'Имя файла без расширения';

  @override
  String get filenameShouldntStartWith => 'Имя файла не должно начинаться с';

  @override
  String get files => 'Файлы';

  @override
  String get filler => 'Филер';

  @override
  String get filterAlbums => 'Отфильтровать Альбомы';

  @override
  String get filterArtists => 'Отфильтровать Исполнителей';

  @override
  String get filterGenres => 'Отфильтровать Жанры';

  @override
  String get filterPlaylists => 'Отфильтровать Плейлисты';

  @override
  String get filterTracks => 'Отфильтровать Треки';

  @override
  String get filterTracksBy => 'Отфильтровать Треки в Списках Поиска По';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Треки, Отфильтрованные по размеру и продолжительности';

  @override
  String get finished => 'Завершённые';

  @override
  String get finishedUpdatingLibrary => 'Обновление Библиотеки Завершено';

  @override
  String get firstListen => 'Первое прослушивание';

  @override
  String get fixYtdlpBigThumbnailSize => 'Исправить большой размер миниатюры yt-dlp';

  @override
  String get floatingActionButton => 'Плавающая Кнопка Действия';

  @override
  String get folder => 'Папка';

  @override
  String get folderName => 'Имя Папки';

  @override
  String get folders => 'Папки';

  @override
  String get fontScale => 'Размер Шрифта';

  @override
  String get forceMiniplayerFollowTrackColors => 'Заставить миниплеер использовать цвета трека';

  @override
  String get forceSquaredAlbumThumbnail => 'Принудительно сделать Миниатюру Альбома Квадратной';

  @override
  String get forceSquaredThumbnailNote => 'Размер Миниатюры и Высота Плитки НЕ совпадают, квадратный вид может не соответствовать ожиданиям. Ты точно хочешь уравнять их?';

  @override
  String get forceSquaredTrackThumbnail => 'Принудительно сделать Миниатюру Трека Квадратной';

  @override
  String get forceStopColorPaletteGeneration => 'Принудительно прекратить извлечение цветовых палитр? Ты можешь продолжить это позже';

  @override
  String get format => 'Формат';

  @override
  String get fullscreen => 'На весь экран';

  @override
  String get gaplessPlayback => 'Проигрывание Без пауз';

  @override
  String get generate => 'Подобрать';

  @override
  String get generateFromDates => 'Диапазон Времени';

  @override
  String get generateFromDatesSubtitle => 'Подобрать треки, прослушанные в определённом временном диапазоне';

  @override
  String get generateRandomPlaylist => 'Создать случайный Плейлист';

  @override
  String get genre => 'Жанр';

  @override
  String get genres => 'Жанры';

  @override
  String get goToAlbum => 'Перейти к Альбому';

  @override
  String get goToArtist => 'Перейти к Исполнителю';

  @override
  String get goToChannel => 'Перейти на Канал';

  @override
  String get goToFolder => 'Перейти к Папке';

  @override
  String get goodLooking => 'Выглядит хорошо';

  @override
  String get grantStoragePermission => 'Предоставить разрешение использование хранилища';

  @override
  String get group => 'Группа';

  @override
  String get groupArtworksByAlbum => 'Группировать обложки по альбому';

  @override
  String get guide => 'Руководство';

  @override
  String get hapticFeedback => 'Тактильный отклик';

  @override
  String get heightOfAlbumTile => 'Высота альбомной плитки';

  @override
  String get heightOfTrackTile => 'Высота плитки для треков';

  @override
  String get hideSkipButtonAfter => 'Убирать кнопку пропуска через';

  @override
  String get highMatches => 'Высокие показатели соответствия';

  @override
  String get highPerformance => 'Высокая производительность';

  @override
  String get highlight => 'Ключевой момент';

  @override
  String get history => 'История';

  @override
  String get historyImportMissingEntriesNote => 'Эти записи не удалось найти в библиотеке. Если ты считаешь, что они существуют, пожалуйста, добавь их вручную';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString прослушиваний',
      few: '$listensCountString прослушивания',
      one: '$listensCountString прослушивание',
    );
    return 'Заменить $_temp0 ($oldTrackInfo) на $newTrackInfo?';
  }

  @override
  String get home => 'Главная';

  @override
  String get hook => 'Крюк';

  @override
  String get host => 'Хост';

  @override
  String get hourFormat12 => '12-часовой формат';

  @override
  String get hours => 'Часов';

  @override
  String get iReadAndAgree => 'Я прочитал и согласен';

  @override
  String get ifNotPlaying => 'Если не проигрывает';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Загрузки могут быть ограничены, если приложение работает от аккумулятора';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Игнорировать общие префиксы при сортировке';

  @override
  String get ignores => 'Игнорирует';

  @override
  String get imageSource => 'Источник изображения';

  @override
  String get immersiveMode => 'Режим погружения';

  @override
  String get immersiveModeSubtitle => 'Скрывает статусную и навигационную панели при развёрнутом миниплеере';

  @override
  String get import => 'Импорт';

  @override
  String get importAll => 'Импортировать всё';

  @override
  String get importLastFmHistory => 'Импорт истории LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Перейди на $lastfmCsvLink\n\n2. Введи своё имя пользователя, получи и загрузи CSV-файл.\n\n3. Выбери файл на следующем экране.';
  }

  @override
  String get importTimeRange => 'Импортировать диапазон времени';

  @override
  String get importYoutubeHistory => 'Импорт истории YouTube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Перейди по $takeoutLink\n\n2. Нажми \"Несколько форматов\" и напротив \"Истории\" выбери \"JSON\".\n\n3. Нажми \"Выбраны все данные YouTube\", нажми на \"Отменить выбор\" и выбери только \"историю\".\n\n4. \"Создай Экспорт\", загрузи и разархивируй.\n\n5. На следующем экране выбери \"история-просмотров.json\".';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString каналов импортировано успешно',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText плейлистов импортировано успешно',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Включать видео';

  @override
  String get indexRefreshRequired => 'Выполните обновление после изменения этого параметра';

  @override
  String get indexer => 'Индексатор';

  @override
  String get indexerNote => 'Примечание: неполное количество обложек относится к дублированным и не найденным обложкам';

  @override
  String get indexerSubtitle => 'Управление музыкальной библиотекой';

  @override
  String get infinityQueueOnNextPrev => 'Бесконечная очередь на следующий/предыдущий';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'При нажатии кнопки \"Следующий\" во время воспроизведения последнего элемента происходит переход к первому, и наоборот';

  @override
  String get info => 'Информация';

  @override
  String get inserted => 'Введено';

  @override
  String get instantlyApplies => 'Мгновенно применяется';

  @override
  String get interactionReminder => 'Напоминание Взаимодействия';

  @override
  String get intro => 'Вступление';

  @override
  String get invertSelection => 'Инвертировать Выделение';

  @override
  String get issues => 'Проблемы';

  @override
  String get item => 'Элемент';

  @override
  String get jump => 'Перейти';

  @override
  String get jumpToDay => 'Перейти к дню';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Перейти к первому треку после завершения очереди';

  @override
  String get keepCachedVersions => 'Хранить кэшированные версии';

  @override
  String get keepFileDates => 'Хранить даты файлов';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Миниплеер развёрнут';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Миниплеер развёрнут, и видео воспроизводится';

  @override
  String get keepScreenAwakeNone => 'Не держать экран включённым';

  @override
  String get keepScreenAwakeWhen => 'Держать экран включённым, когда';

  @override
  String get killPlayerAfterDismissingApp => 'Закрыть плеер после выхода из приложения';

  @override
  String get language => 'Язык';

  @override
  String get learnMore => 'Узнать больше';

  @override
  String get leftAction => 'Действие при свайпе влево';

  @override
  String get legacyAuthentication => 'Устаревшая система авторизации';

  @override
  String get libraryTabs => 'Вкладки Категорий';

  @override
  String get libraryTabsReorder => 'Можно изменить порядок активированных категорий.';

  @override
  String get license => 'Лицензия';

  @override
  String get licenseSubtitle => 'Лицензии и Соглашения, используемые в Namida';

  @override
  String get like => 'Нравится';

  @override
  String get liked => 'Понравившиеся';

  @override
  String get link => 'Ссылка';

  @override
  String get listOfFolders => 'Список папок';

  @override
  String get loadAll => 'Загрузить всё';

  @override
  String get loadingFile => 'Файл загружается';

  @override
  String get local => 'Локально';

  @override
  String get localVideoMatching => 'Локальное Сопоставление Видео';

  @override
  String get login => 'Логин';

  @override
  String get longPressAction => 'Действие при Зажатии';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Долгое нажатие на текст песни активирует полноэкранный режим';

  @override
  String get lostMemories => 'Давно Прослушанное';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString лет',
      few: '$numberString года',
      one: '$numberString год',
    );
    return 'примерно в это время, $_temp0 назад';
  }

  @override
  String get lostPartners => 'Архивный Микс';

  @override
  String get loudnessEnhancer => 'Усиление громкости';

  @override
  String get lyricist => 'Лирик';

  @override
  String get lyrics => 'Текст песни';

  @override
  String get lyricsSource => 'Источник текста';

  @override
  String get m3uPlaylist => 'M3U-плейлист';

  @override
  String get makeYourFirstListen => 'Послушай впервые!';

  @override
  String get manage => 'Управлять';

  @override
  String get manageYourAccounts => 'Управлять своими аккаунтами';

  @override
  String get manualBackup => 'Ручной';

  @override
  String get manualBackupSubtitle => 'выбрать конкретный файл';

  @override
  String get markAsRead => 'Пометить как прочитанное';

  @override
  String get matchAllTracks => 'Сопоставить все треки';

  @override
  String get matchAllTracksNote => 'Это может повлиять на скорость сопоставления, так как при этом будут проверяться все треки в твоей библиотеке';

  @override
  String get matchingType => 'Тип соответствия';

  @override
  String get maxAudioCacheSize => 'Максимальный размер кэша аудио';

  @override
  String get maxImageCacheSize => 'Максимальный размер кэша изображений';

  @override
  String get maxVideoCacheSize => 'Максимальный размер кэша видео';

  @override
  String get maximum => 'Максимум';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Недоступно из-за включенного хранилища медиафайлов';

  @override
  String get medium => 'Средний';

  @override
  String get membershipCode => 'Код';

  @override
  String get membershipCodeSentToEmail => 'Код, отправленный на твою почту';

  @override
  String get membershipDidntChange => 'Членство не изменилось';

  @override
  String get membershipEnjoyNew => 'Наслаждайся своим новым членством';

  @override
  String get membershipFreeCoupon => 'Бесплатный Купон';

  @override
  String get membershipManage => 'Управляй своим членством';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'У этого пользователя не найдены подписки';

  @override
  String get membershipSignInToPatreonAccount => 'Войди в свой аккаунт Patreon';

  @override
  String get membershipUnknown => 'Неизвестное Членство';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Тебе нужно членство $name1 или $name2, чтобы добавить несколько аккаунтов';
  }

  @override
  String get merge => 'Объединить';

  @override
  String get metadataCache => 'Кэш метаданных';

  @override
  String get metadataEditFailed => 'Не удалось отредактировать метаданные';

  @override
  String get metadataReadFailed => 'Не удалось прочитать метаданные';

  @override
  String get minFileDuration => 'Минимальная продолжительность трека';

  @override
  String get minFileSize => 'Минимальный размер файла';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Минимальная продолжительность трека для продолжения воспроизведения с предыдущего момента';

  @override
  String get minValueCantBeMoreThanMax => 'Минимальное значение не может быть больше максимального';

  @override
  String get minValueToCountTrackListen => 'Считать, что трек прослушан после: ';

  @override
  String get minimizedMiniplayer => 'Минимизированный Миниплеер';

  @override
  String get minimum => 'Минимум';

  @override
  String get minimumOneFolderSubtitle => 'Должна быть как минимум одна папка, добавьте ещё папки, если хотите удалить эту';

  @override
  String get minimumOneItem => 'Не удалось удалить элемент';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString элементов',
      one: '$numberString элемента',
    );
    return 'Должно остаться не менее $_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Минимальная Длительность Сегмента';

  @override
  String get miniplayerCustomization => 'Кастомизация миниплеера';

  @override
  String get minutes => 'минут';

  @override
  String get missingEntries => 'Недостающие записи';

  @override
  String get missingTracks => 'Отсутствующие треки';

  @override
  String get mix => 'Микс';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Плейлист \"Микс\" сгенерированный YouTube';

  @override
  String get mixes => 'Миксы';

  @override
  String get mobile => 'Мобильный';

  @override
  String get month => 'Месяц';

  @override
  String get months => 'Месяца';

  @override
  String get mood => 'Настроение';

  @override
  String get moods => 'Настроения';

  @override
  String get more => 'Подробнее';

  @override
  String get mostPlayed => 'Проигрываемые чаще всего';

  @override
  String get multipleTracksTagsEditNote => 'Ты собираешься редактировать эти треки,\nНеизменённые поля останутся нетронутыми.';

  @override
  String get musicOfftopic => 'Музыкальный Оффтоп';

  @override
  String get name => 'Название';

  @override
  String get nameContainsBadCharacter => 'Название содержит плохой символ';

  @override
  String get never => 'Никогда';

  @override
  String get newDirectory => 'Новый каталог';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Добавить треки';

  @override
  String get newTracksMoods => 'Настроение';

  @override
  String get newTracksMoodsSubtitle => 'Подобрать треки по настроению';

  @override
  String get newTracksRandom => 'Случайно';

  @override
  String get newTracksRandomSubtitle => 'Выбор случайных треков из библиотеки';

  @override
  String get newTracksRatings => 'Оценки';

  @override
  String get newTracksRatingsSubtitle => 'Подобрать треки по рейтингу';

  @override
  String get newTracksRecommended => 'Рекомендуемые';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Подобрать треки, которые ты обычно слушал с $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Похожая дата выхода';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Подобрать треки, выпущенные примерно в то же время, что и $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Год выпуска трека неизвестен';

  @override
  String get newest => 'Новые';

  @override
  String get next => 'Дальше';

  @override
  String get no => 'нет';

  @override
  String get noChangesFound => 'Изменений не обнаружено.';

  @override
  String get noEnoughTracks => 'У вас не так много треков...';

  @override
  String get noExcludedFolders => 'У вас нет исключённых папок';

  @override
  String get noFolderChosen => 'Ты не выбрал ни одной папки';

  @override
  String get noMoodsAvailable => 'Настроения отсутствуют';

  @override
  String get noNetworkAvailableToFetchData => 'Нет подключения к сети для получения данных';

  @override
  String get noTracksFound => 'Треки не найдены';

  @override
  String get noTracksFoundBetweenDates => 'В этом временном промежутке нет треков.';

  @override
  String get noTracksFoundInDirectory => 'В этом каталоге не найдено ни одного трека';

  @override
  String get noTracksInHistory => 'У тебя недостаточно треков в истории';

  @override
  String get nonActive => 'Неактивный';

  @override
  String get nonFavourites => 'Неизбранные';

  @override
  String get none => 'Ничего';

  @override
  String get normalizeAudio => 'Нормализация звука';

  @override
  String get normalizeAudioSubtitle => 'Нормализует громкость, считывая тег \"ReplayGain\" или информацию, предоставленную YouTube';

  @override
  String get notAvailableForYourDevice => 'Недоступно на твоём Устройстве';

  @override
  String get notSupportedForNetworkFiles => 'Не поддерживается для Сетевых Файлов';

  @override
  String get note => 'Примечание';

  @override
  String get notification => 'Уведомление';

  @override
  String get notifications => 'Уведомления';

  @override
  String get numberOfTracks => 'Количество треков';

  @override
  String get ofLabel => 'из';

  @override
  String get offlineSearch => 'Оффлайн Поиск';

  @override
  String get offset => 'Смещение звука';

  @override
  String get oldDirectory => 'Старый каталог';

  @override
  String get oldDirectoryStillHasTracks => 'В Старом Каталоге ещё остались треки, подтвердить?';

  @override
  String get oldestWatch => 'Смотреть самые старые';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'При Прерывании';

  @override
  String get onNotificationTap => 'При Нажатии на Уведомление';

  @override
  String get onOpeningYoutubeLink => 'При открытии YouTube-ссылки';

  @override
  String get onSwiping => 'Действие по свайпу';

  @override
  String get onVolumeZero => 'При громкости 0';

  @override
  String get ongoing => 'В процессе';

  @override
  String get open => 'Открыть';

  @override
  String get openApp => 'Открыть Приложение';

  @override
  String get openInFileExplorer => 'Открыть в Проводнике';

  @override
  String get openInYoutubeView => 'Открыть в режиме просмотра YouTube';

  @override
  String get openMiniplayer => 'Открыть миниплеер';

  @override
  String get openQueue => 'Открыть очередь';

  @override
  String get openYoutubeLink => 'Открыть ссылку YouTube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Войдите в аккаунт для совершения операции $name';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Операция $operation требует как минимум членство $name';
  }

  @override
  String get or => 'или';

  @override
  String get others => 'Другие';

  @override
  String get output => 'Вывод';

  @override
  String get outro => 'Завершение';

  @override
  String get overrideOldFilesInTheSameFolder => 'Перезаписать старые файлы в той же папке';

  @override
  String get palette => 'Палитра';

  @override
  String get paletteMix => 'Микс';

  @override
  String get paletteNewMix => 'Новый Микс';

  @override
  String get paletteSelectedMix => 'Выбранный Микс';

  @override
  String get parallelDownloads => 'Параллельные загрузки';

  @override
  String get parsed => 'разобранный';

  @override
  String get password => 'Пароль';

  @override
  String get path => 'Полный Путь к Файлу';

  @override
  String get pause => 'Приостановить';

  @override
  String get pauseFadeDuration => 'Продолжительность Затухания при Паузе';

  @override
  String get pausePlayback => 'Приостановить воспроизведение';

  @override
  String get percentage => 'Процент';

  @override
  String get performanceMode => 'Производительный режим';

  @override
  String get performanceNote => 'Может повлиять на производительность';

  @override
  String get personalized => 'Персонализированный';

  @override
  String get personalizedRelatedVideos => 'Персонализированные похожие видео';

  @override
  String get personalizedRelatedVideosSubtitle => 'Отключение этого параметра увеличит расход данных';

  @override
  String get pickColorsFromDeviceWallpaper => 'Выбирать цвета из обоев на устройстве';

  @override
  String get pickFromStorage => 'Выбрать из хранилища';

  @override
  String get pinned => 'Закреплено';

  @override
  String get pitch => 'Высота';

  @override
  String get plain => 'Обычный';

  @override
  String get play => 'Воспроизвести';

  @override
  String get playAfter => 'Воспроизвести после';

  @override
  String get playAfterNextPrev => 'Автовоспроизведение при следующем/предыдущем';

  @override
  String get playAll => 'Воспроизвести всё';

  @override
  String get playFadeDuration => 'Продолжительность затухания воспроизведения';

  @override
  String get playLast => 'Воспроизвести Последним';

  @override
  String get playNext => 'Воспроизвести Следующим';

  @override
  String get playbackSetting => 'Воспроизведение';

  @override
  String get playbackSettingSubtitle => 'Доступ к ним возможен непосредственно в плеере путём длительного нажатия на кнопку воспроизведения звука';

  @override
  String get playlist => 'Плейлист';

  @override
  String get playlists => 'Плейлисты';

  @override
  String get playlistsImportM3uNative => 'Это импортирует M3U-плейлисты для использования в Namida. Используй, если мигрируешь';

  @override
  String get playlistsImportM3uSynced =>
      'Это будет автоматически импортировать M3U-плейлисты из индексирующих папок и продолжать синхронизировать с оригинальным M3U-файлом. Включи, если редактируешь этот файл из других приложений';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Автоимпорт M3U Плейлистов';

  @override
  String get pleaseEnterADifferentName => 'Это название уже существует :(\nпожалуйста, попробуйте другое необычное название';

  @override
  String get pleaseEnterALink => 'Пожалуйста, введите ссылку';

  @override
  String get pleaseEnterALinkSubtitle => 'эмм... это точно ссылка на YouTube?';

  @override
  String get pleaseEnterAName => 'Пожалуйста, введите название';

  @override
  String get port => 'Порт';

  @override
  String get preventDuplicatedTracks => 'Предотвращать дублирование треков';

  @override
  String get preventDuplicatedTracksSubtitle => 'Использует имя файла для однозначной идентификации треков';

  @override
  String get preview => 'Предпросмотр';

  @override
  String get previous => 'Предыдущий';

  @override
  String get previousButtonReplays => 'Перезапускать трек при выборе предыдущего трека';

  @override
  String get previousButtonReplaysSubtitle => 'если нажато, когда текущая позиция больше длины перемотки';

  @override
  String get prioritizeEmbeddedLyrics => 'Приоритет встроенному тексту песни';

  @override
  String get priority => 'Приоритет';

  @override
  String get private => 'Ограниченный доступ';

  @override
  String get progress => 'Прогресс';

  @override
  String get promptToChangeTrackPath => 'Обычно это происходит, когда ты удаляешь/перемещаешь/переименовываешь файл вне Namida. Хочешь обновить текущий путь?';

  @override
  String get public => 'Открытый доступ';

  @override
  String get queue => 'Очередь';

  @override
  String get queues => 'Очереди';

  @override
  String get random => 'Случайно';

  @override
  String get randomPicks => 'Микс';

  @override
  String get rating => 'Оценка';

  @override
  String get reIndex => 'Переиндексировать';

  @override
  String get reIndexSubtitle => 'Пересобирает музыкальную библиотеку с нуля';

  @override
  String get reIndexWarning =>
      'Этот процесс может занять некоторое время в зависимости от размера твоей библиотеки.\n\nПереиндексация обложек не будет производиться до тех пор, пока они существуют';

  @override
  String get recentAlbums => 'Недавние Альбомы';

  @override
  String get recentArtists => 'Недавние Исполнители';

  @override
  String get recentListens => 'Недавно Прослушанное';

  @override
  String get recentlyAdded => 'Недавно Добавленные';

  @override
  String get recordLabel => 'Студия Звукозаписи';

  @override
  String get refresh => 'Обновить';

  @override
  String get refreshLibrary => 'Обновить Библиотеку';

  @override
  String get refreshLibrarySubtitle => 'Проверить наличие новых добавленных или удалённых треков';

  @override
  String get refreshOnStartup => 'Обновить при запуске';

  @override
  String get relatedVideos => 'Похожие видео';

  @override
  String get rememberAudioOnlyMode => 'Запоминать \"Только Аудио\" режим';

  @override
  String get remixer => 'Ремиксер';

  @override
  String get remove => 'Удалить';

  @override
  String get removeDuplicates => 'Удалить Дубликаты';

  @override
  String get removeFromFavourites => 'Удалить из избранного';

  @override
  String get removeFromLibrary => 'Удалить из библиотеки';

  @override
  String get removeFromPlaylist => 'Удалить из Плейлиста';

  @override
  String get removeQueue => 'Удалить Очередь';

  @override
  String get removeSourceFromHistory => 'Удалить источник из истории';

  @override
  String get removeWhitespaces => 'Удалять Пробельные Символы';

  @override
  String get removed => 'Удалено';

  @override
  String get rename => 'Переименовать';

  @override
  String get renamePlaylist => 'Переименовать Плейлист';

  @override
  String get reorderable => 'Переупорядочиваемые';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number раз',
      few: '$number раза',
    );
    return 'Повторить ещё $_temp0';
  }

  @override
  String get repeatMode => 'Режим повторения';

  @override
  String get repeatModeAll => 'Повторять Всю Очередь';

  @override
  String get repeatModeNone => 'Остановить на Последнем Треке';

  @override
  String get repeatModeOne => 'Повторить Текущий Трек';

  @override
  String get replaceAllListensWithAnotherTrack => 'Заменить все прослушанные другим треком';

  @override
  String get replies => 'Ответы';

  @override
  String get reply => 'Ответ';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Требует очистки кэша изображений и повторное переиндексирование';

  @override
  String get rescanVideos => 'Повторное сканирование видео';

  @override
  String get resetBrightness => 'Сброс яркости';

  @override
  String get resetToDefault => 'Установить на';

  @override
  String get respectNoMedia => 'Соблюдать .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Исключает папки, содержащие .nomedia';

  @override
  String get restart => 'Перезапустить';

  @override
  String get restoreBackup => 'Восстановить резервную копию';

  @override
  String get restoreDefaults => 'Восстановить значения по умолчанию';

  @override
  String get restoredBackupSuccessfully => 'Резервная копия восстановлена';

  @override
  String get restoredBackupSuccessfullySub => 'Файл резервной копии успешно восстановлен';

  @override
  String get resume => 'Продолжить';

  @override
  String get resumeIfWasInterrupted => 'Продолжить воспроизведение, если было приостановлено из-за прерывания';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Продолжить воспроизведение, если было приостановлено из-за громкости';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString минут',
      few: '$numberString минуты',
      one: '$numberString минута',
    );
    return 'Продолжить воспроизведение, если был на паузе меньше, чем $_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Вернуть Дизлайки';

  @override
  String get reverseOrder => 'Обратный порядок';

  @override
  String get rightAction => 'Действие при свайпе вправо';

  @override
  String get ringtone => 'Рингтон';

  @override
  String get sameDirectoryOnly => 'Только в том же каталоге';

  @override
  String get sample => 'Сэмпл';

  @override
  String get sampleRate => 'Частота дискретизации';

  @override
  String get save => 'Сохранить';

  @override
  String get saveToLibrary => 'Сохранить в библиотеку';

  @override
  String get savedIn => 'Сохранено в';

  @override
  String get scaleMultiplier => 'Множитель Размера';

  @override
  String get search => 'Поиск';

  @override
  String get searchYoutube => 'Поиск на YouTube';

  @override
  String get seconds => 'секунд';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Посмотреть код Проекта на $site';
  }

  @override
  String get seekDuration => 'Продолжительность поиска';

  @override
  String get seekDurationInfo => 'Ты можешь нажать на текущую продолжительность для перемотки назад и общую продолжительность для перемотки вперёд';

  @override
  String get seekbar => 'Полоса прокрутки';

  @override
  String get selectAll => 'Выбрать всё';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Выбранные файлы уже в локальной библиотеке';

  @override
  String get selectedTracks => 'Выбранные треки';

  @override
  String get selfPromotion => 'Самопиар';

  @override
  String get semitones => 'Полутоны';

  @override
  String get separatorsBlacklistSubtitle => 'Эти слова не будут разделены';

  @override
  String get separatorsMessage => 'Пробелы вставлять не нужно, если только ты не хочешь использовать букву/символ, который встречается в целом слове (например, x и ft.)';

  @override
  String get serverAddress => 'Адрес Сервера';

  @override
  String get setAs => 'Установить как';

  @override
  String get setAsDefault => 'Установить как значение по умолчанию';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Установка даты последнего изменения файла в качестве даты загрузки видео';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Установить настроения';

  @override
  String get setMoodsSubtitle => 'Для разделения используй запятые (,)';

  @override
  String get setRating => 'Поставить оценку';

  @override
  String get setTags => 'Установить теги';

  @override
  String get setYoutubeLink => 'Задать Ссылку на YouTube';

  @override
  String get settings => 'Настройки';

  @override
  String get setupFirstStartup => 'Настройка первого запуска';

  @override
  String get share => 'Поделиться';

  @override
  String get shareLogs => 'Поделиться логами';

  @override
  String get shortcuts => 'Горячие клавиши';

  @override
  String get shouldDuck => 'Должен приглушиться';

  @override
  String get shouldDuckNote => 'Указывает на то, что громкость должна быть снижена. Пример: уведомление';

  @override
  String get shouldPause => 'Следует поставить на паузу';

  @override
  String get shouldPauseNote => 'Указывает, что воспроизведение должно быть приостановлено. Пример: при звонке';

  @override
  String get showAll => 'Показывать все';

  @override
  String get showChannelWatermarkInFullscreen => 'Показывать водяной знак канала в полноэкранном режиме';

  @override
  String get showFailedOnly => 'Показывать только неудачные';

  @override
  String get showHideUnknownFields => 'Показать/скрыть Неизвестные Поля';

  @override
  String get showInSeekbar => 'Показывать в Полосе Перемотки';

  @override
  String get showMixPlaylistsIn => 'Показывать миксы в';

  @override
  String get showMore => 'Подробнее';

  @override
  String get showShortVideosIn => 'Показывать Shorts в';

  @override
  String get showSkipButton => 'Показывать Кнопку Пропуска';

  @override
  String get showVideoEndcards => 'Показывать конечные заставки видео';

  @override
  String get showWebm => 'Показать webm';

  @override
  String get shuffle => 'Перемешать';

  @override
  String get shuffleAll => 'Перемешать всё';

  @override
  String get shuffleNext => 'Перемешать следующие';

  @override
  String get signIn => 'Зарегистрироваться';

  @override
  String get signInCanceled => 'Вход был отменён';

  @override
  String get signInFailed => 'Не удалось войти в аккаунт';

  @override
  String get signInToYourAccount => 'Войди в свой аккаунт';

  @override
  String get signInYouDontHaveAccount => 'Нет доступных для входа аккаунтов';

  @override
  String get signInYouNeedAccountToViewPage => 'Тебе нужен аккаунт, чтобы смотреть эту страницу';

  @override
  String get signOut => 'Выйти';

  @override
  String signOutFromName({required String name}) {
    return 'Выйти из $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Вход в систему позволяет использовать базовые функции';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Получи ранний доступ через Patreon или используя купон';

  @override
  String get similarDiscoverDate => 'Схожая Дата Обнаружения';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Сгенерировать треки, которые были обнаружены в то же время, что и $currentTrack';
  }

  @override
  String get similarTimeRange => 'Схожий Временной Диапазон';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Сгенерировать треки, которые ты слушал примерно в то же время, что и $currentTrack';
  }

  @override
  String get singles => 'Синглы';

  @override
  String get size => 'Размер';

  @override
  String get skip => 'Пропустить';

  @override
  String get skipCountTracking => 'Считать Количество Пропусков';

  @override
  String get skipSilence => 'Пропустить Тишину';

  @override
  String get skipSponsorSegmentsInVideos => 'Пропускать Спонсорские Вставки в Видео';

  @override
  String get sleepAfter => 'Заснуть после';

  @override
  String get sleepTimer => 'Таймер сна';

  @override
  String get socials => 'Соцсети';

  @override
  String get socialsSubtitle => 'Следи за обновлениями, советами, обсуждениями и идеями';

  @override
  String get someWebServersRequireAuthentication => 'Некоторые веб-сервисы требуют авторизации. Пожалуйста, обнови учётные данные, чтобы получить доступ к своей библиотеке.';

  @override
  String get sortBy => 'Сортировать по';

  @override
  String get source => 'Источник';

  @override
  String get speed => 'Скорость';

  @override
  String get sponsor => 'Спонсор';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'Рейтинг SponsorBlock';

  @override
  String get staggeredAlbumGridView => 'Поэтапное отображение сетки альбомов';

  @override
  String get start => 'Начало';

  @override
  String get stats => 'Статистика';

  @override
  String get statsSubtitle => 'Вот некоторые сведения о твоей библиотеке';

  @override
  String get stop => 'Стоп';

  @override
  String get stopAfterThisTrack => 'Остановить после этого трека';

  @override
  String get stopAfterThisVideo => 'Остановить после этого видео';

  @override
  String get storagePermissionDenied => 'Разрешение Отклонено';

  @override
  String get storagePermissionDeniedSubtitle => 'Пожалуйста, разреши доступ для выполнения этого действия';

  @override
  String get stretchLyricsDuration => 'Растянуть Продолжительность Слов песни';

  @override
  String get subdirectory => 'Подкаталог';

  @override
  String get subscribe => 'Подписаться';

  @override
  String get subscribed => 'Подписан';

  @override
  String get subscriber => 'Подписчик';

  @override
  String get subscribers => 'Подписчики';

  @override
  String get succeeded => 'Успешно';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Есть предложение или столкнулся с проблемой? Открой задачу на $site';
  }

  @override
  String get support => 'Поддержать';

  @override
  String get supremacy => 'Микс';

  @override
  String get sussyBaka => 'Блин, нет треков';

  @override
  String get swipeActions => 'Действия Жестов';

  @override
  String get swipeToOpenDrawer => 'Проведите пальцем, чтобы открыть панель';

  @override
  String get synced => 'Синхронизированный';

  @override
  String get synopsis => 'Синопсис';

  @override
  String get tagFields => 'Поля для Тегов';

  @override
  String get tags => 'Теги';

  @override
  String get tapAction => 'Действие при Нажатии';

  @override
  String get tapToSeek => 'Тапнуть для перемотки';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Тема';

  @override
  String get themeModeDark => 'Тёмная';

  @override
  String get themeModeLight => 'Светлая';

  @override
  String get themeModeSystem => 'Как в системе';

  @override
  String get themeSettings => 'Тема';

  @override
  String get themeSettingsSubtitle => 'Общая атмосфера твоего плеера';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'В плейлисте есть активные сортировщики. Отключи их перед упорядочением.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Вероятно, видео удалено или доступ к нему ограничен.';

  @override
  String get thumbnails => 'Миниатюры';

  @override
  String get title => 'Название';

  @override
  String get top => 'Топ';

  @override
  String get topComments => 'Комментарии сверху';

  @override
  String get topCommentsSubtitle => 'Отображать комментарии сверху, а не снизу';

  @override
  String get topRecentAlbums => 'Топ Недавних Альбомов';

  @override
  String get topRecentArtists => 'Топ Недавних Исполнителей';

  @override
  String get topRecents => 'Топ Недавних';

  @override
  String get totalListenTime => 'Общее Время Прослушивания';

  @override
  String get totalListens => 'Всего Прослушиваний';

  @override
  String get totalTracks => 'Всего Треков';

  @override
  String get totalTracksDuration => 'Общая Длительность Треков';

  @override
  String get track => 'Трек';

  @override
  String get trackArtistsSeparator => 'Разделители Исполнителей';

  @override
  String get trackGenresSeparator => 'Разделители Жанров';

  @override
  String get trackInfo => 'Информация о треке';

  @override
  String get trackNotFound => 'Трек не найден';

  @override
  String get trackNumber => 'Номер трека';

  @override
  String get trackNumberTotal => 'Всего Треков';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Старое название: \"$oldName\"\n\nНовое название: \"$newName\"\n\nТы уверен?';
  }

  @override
  String get trackPlayMode => 'Режим Воспроизведения';

  @override
  String get trackPlayModeSearchResults => 'Результаты Поиска';

  @override
  String get trackPlayModeSelectedOnly => 'Только выбранные дорожки';

  @override
  String get trackPlayModeTrackAlbum => 'Альбом Треков';

  @override
  String get trackPlayModeTrackArtist => 'Основной Исполнитель Трека';

  @override
  String get trackPlayModeTrackGenre => 'Жанр Трека';

  @override
  String get trackThumbnailSizeInList => 'Размер Миниатюры Трека';

  @override
  String get trackTileCustomization => 'Настройка Плитки Треков';

  @override
  String get trackTileItemsSeparator => 'Разделитель Элементов';

  @override
  String get tracks => 'Треки';

  @override
  String get tracksExcludedByNomedia => 'Треки, Исключённые из-за .nomedia';

  @override
  String get tracksInfo => 'Информация о треках';

  @override
  String get underrated => 'Недооценённое';

  @override
  String get undo => 'Отменить';

  @override
  String get undoChanges => 'Отменить изменения?';

  @override
  String get undoChangesDeletedPlaylist => 'Отменить удаление плейлиста';

  @override
  String get undoChangesDeletedQueue => 'Отменить удаление Очереди';

  @override
  String get undoChangesDeletedTrack => 'Отменить удаление трека';

  @override
  String get uniqueArtworkHash => 'Уникальный Хеш Обложки';

  @override
  String get unlimited => 'Неограниченный';

  @override
  String get unlisted => 'Доступ по ссылке';

  @override
  String get unlock => 'Разблокировать';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Обновить';

  @override
  String get updateDirectoryPath => 'Обновить пути к каталогу';

  @override
  String get updateMissingTracksOnly => 'Обновить только отсутствующих треков';

  @override
  String get updating => 'Обновление';

  @override
  String get useCollapsedSettingTiles => 'Использовать Свёрнутые Плитки Настроек';

  @override
  String get useMediaStore => 'Использовать Хранилище Медиафайлов';

  @override
  String get useMediaStoreSubtitle =>
      '✓ моментальная индексация\nx соблюдение .nomedia будет принудительно включено\nx некоторые теги метаданных будут отсутствовать\nx интеграция YouTube для локальной библиотеки не будет работать';

  @override
  String get usePitchBlack => 'Использовать угольно-чёрный цвет';

  @override
  String get usePitchBlackSubtitle => 'Полезно для AMOLED-экранов... и выглядит круче';

  @override
  String get used => 'Используется';

  @override
  String get value => 'Значение';

  @override
  String get valueBetween50200 => 'Значение должно быть от 50% до 200%';

  @override
  String get vibration => 'Вибрация';

  @override
  String get vibrationType => 'Тип вибрации';

  @override
  String get video => 'Видео';

  @override
  String get videoCache => 'Кэш видео';

  @override
  String get videoCacheFile => 'Кэшированный Видеофайл';

  @override
  String get videoCacheFiles => 'Кэшированные Видеофайлы';

  @override
  String get videoOnly => 'Только Видео';

  @override
  String get videoPlaybackSource => 'Источник Видео';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Даст приоритет видео на устройстве. Если оно не найдено, то будет получено с YouTube';

  @override
  String get videoPlaybackSourceLocal => 'Видео на Устройстве';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Алан Уолкер - Faded.m4a\nВидео Алан Уолкер - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Проверяет, не имеет ли какой-либо видеофайл (найденный в списке выбранных папок) имя файла, содержащее название трека';

  @override
  String get videoPlaybackSourceYoutube => 'Из YouTube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Проверяет имя файла и комментарий к треку на наличие подходящей ссылки на YouTube, видео кэшируются для дальнейшего использования.';

  @override
  String get videoQuality => 'Качество Видео';

  @override
  String get videoQualitySubtitle => 'Будет выбрано лучшее доступное качество.';

  @override
  String get videoQualitySubtitleNote => 'Всегда полезно иметь больше альтернатив на случай, если качество не будет найдено, иначе произойдёт откат к худшему качеству';

  @override
  String get videos => 'Видео';

  @override
  String get view => 'просмотр';

  @override
  String get viewAll => 'Посмотреть Всё';

  @override
  String get views => 'просмотра(ов)';

  @override
  String get volume => 'Громкость';

  @override
  String get warning => 'Предупреждение';

  @override
  String get waveformBarsCount => 'Количество полос волны громкости';

  @override
  String get webmNoEditTagsSupport => 'Формат WEBM не поддерживает редактирование тегов';

  @override
  String get week => 'Неделя';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Год';

  @override
  String get yes => 'да';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Твоё текущее членство: $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Текущая сортировка будет изменена. Продолжить?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'Настройка YouTube';

  @override
  String get youtubeStyleMiniplayer => 'Миниплеер в Youtube-стиле';

  @override
  String get ytPreferNewComments => 'Загрузка новых комментариев по возможности';

  @override
  String get ytPreferNewCommentsSubtitle => 'Кэшированная версия будет использована только при отсутствии подключения к интернету';
}
