// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Portuguese (`pt`).
class AppLocalizationsPt extends AppLocalizations {
  AppLocalizationsPt([String locale = 'pt']) : super(locale);

  @override
  String get about => 'Sobre';

  @override
  String get active => 'Ativo';

  @override
  String get add => 'Adicionar';

  @override
  String get addAccount => 'Adicionar conta';

  @override
  String get addAll => 'Adicionar tudo';

  @override
  String get addAllAndRemoveOldOnes => 'Adicionar tudo e remover os antigos';

  @override
  String get addAsANewPlaylist => 'Criar uma nova playlist';

  @override
  String get addAudioToLocalLibrary => 'Adicionar áudio à biblioteca local';

  @override
  String get addFolder => 'Criar pasta';

  @override
  String get addLanguage => 'Adicionar idioma';

  @override
  String get addLanguageSubtitle => 'Ajude traduzindo o Namida para seu próprio idioma';

  @override
  String get addLrcFile => 'Adicionar arquivo LRC';

  @override
  String get addMoreFromThisAlbum => 'Adicionar mais deste álbum à fila de reprodução';

  @override
  String get addMoreFromThisArtist => 'Adicionar mais deste artista à fila de reprodução';

  @override
  String get addMoreFromThisFolder => 'Adicionar mais desta pasta à fila de reprodução';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Adicionar mais de $media à fila de reprodução';
  }

  @override
  String get addOnlyMissing => 'Adicionar apenas o que falta';

  @override
  String get addToFavourites => 'Adicionar aos favoritos';

  @override
  String get addToPlaylist => 'Adicionar à playlist';

  @override
  String get addTracksAtTheBeginning => 'Adicionar faixas no início';

  @override
  String get added => 'Adicionada';

  @override
  String get advanced => 'Avançado';

  @override
  String get advancedSettings => 'Configurações Avançadas';

  @override
  String get advancedSettingsSubtitle => 'Configurações Avançadas, não mexer';

  @override
  String get alarm => 'Alarme';

  @override
  String get album => 'Álbum';

  @override
  String get albumArtist => 'Artista do Álbum';

  @override
  String get albumArtists => 'Artistas do Álbum';

  @override
  String get albumIdentifiers => 'Identificadores álbum';

  @override
  String get albumThumbnailSizeInList => 'Tamanho da Thumbnail do Álbum';

  @override
  String get albumTileCustomization => 'Personalização de Imagem do Álbum';

  @override
  String get albums => 'Álbuns';

  @override
  String get albumsCount => 'Quantidade de Álbuns';

  @override
  String get all => 'Tudo';

  @override
  String get allTime => 'Todos os tempos';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Sempre';

  @override
  String get alwaysAsk => 'Perguntar o que fazer';

  @override
  String get alwaysDim => 'Sempre com escurecimento';

  @override
  String get alwaysExpandedSearchbar => 'Barra de pesquisa sempre expandida';

  @override
  String get alwaysRestore => 'Sempre restaurar';

  @override
  String get animatingThumbnailIntensity => 'Intensidade da animação da Thumbnail';

  @override
  String get animatingThumbnailInversed => 'Animações Inversas';

  @override
  String get animatingThumbnailInversedSubtitle => 'Picos altos farão com que a Thumbnail fique menor';

  @override
  String get anotherProcessIsRunning => 'Outro processo já está em execução.';

  @override
  String get appIcon => 'Ícone do app';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Artista';

  @override
  String get artists => 'Artistas';

  @override
  String get artwork => 'Ilustração';

  @override
  String get artworkGestures => 'Gestos de Ilustração';

  @override
  String get artworks => 'Ilustrações';

  @override
  String get audio => 'Áudio';

  @override
  String get audioCache => 'Cache do áudio';

  @override
  String get audioOnly => 'Apenas Áudio';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Intervalo de backup automático';

  @override
  String get autoColoring => 'Coloração automática';

  @override
  String get autoColoringSubtitle => 'Escolher cores do player automaticamente a partir da ilustração atual';

  @override
  String get autoExtractTagsFromFilename => 'Extrair tags automaticamente do nome do arquivo';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Extrair automaticamente Título e Artista do título do vídeo';

  @override
  String get autoGenerated => 'Gerado automaticamente';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Iniciar áudio automaticamente';

  @override
  String get autoStartRadioSubtitle => 'Adicionar automaticamente uma playlist mixada quando tocando apenas uma musica';

  @override
  String get automaticBackup => 'Automático';

  @override
  String get automaticBackupSubtitle => 'Automaticamente utiliza arquivo de backup mais recente encontrado na localização de backup selecionada';

  @override
  String get backupAndRestore => 'Backup & Restauração';

  @override
  String get backupAndRestoreSubtitle => 'Fazer backup dos seus dados e configurações';

  @override
  String get balanced => 'Equilibrado';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Entre datas';

  @override
  String get bitrate => 'Bitrate';

  @override
  String get blacklist => 'Lista de exclusão';

  @override
  String get borderRadiusMultiplier => 'Multiplicador de Raio de Borda';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Cancelar';

  @override
  String get canceled => 'Cancelado';

  @override
  String get changed => 'Alterado';

  @override
  String get changelog => 'Histórico de atualizações';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Canal';

  @override
  String get channels => 'Canais';

  @override
  String get check => 'Verificar';

  @override
  String get checkForMore => 'Conferir mais';

  @override
  String get checkList => 'Conferir lista';

  @override
  String get choose => 'escolher';

  @override
  String get chooseWhatToClear => 'Escolher o que limpar';

  @override
  String get claim => 'Reivindicar';

  @override
  String get clear => 'Limpar';

  @override
  String get clearAudioCache => 'Limpar Cache de Áudio';

  @override
  String get clearImageCache => 'Limpar cache de imagens';

  @override
  String get clearImageCacheWarning => 'Aviso: isto irá resultar em uma biblioteca sem imagens, usar apenas para reconstruir o cache de imagens.';

  @override
  String get clearTrackItem => 'Limpar de uma música';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Limpar de $numberString músicas',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Limpar cache de vídeos';

  @override
  String get clearVideoCacheNote => 'Você pode escolher o quê eliminar.';

  @override
  String get clock => 'Relógio';

  @override
  String get colorPalette => 'Paleta de cores';

  @override
  String get colorPaletteNote1 => 'Mantenha uma cor pressionada para removê-la';

  @override
  String get colorPaletteNote2 => 'Pressione um mix para usar como cor padrão';

  @override
  String get colorPalettes => 'Paletas de cores';

  @override
  String get comment => 'Comentário';

  @override
  String get comments => 'Comentários';

  @override
  String get composer => 'Compositor';

  @override
  String get compress => 'Comprimir';

  @override
  String get compressImages => 'Comprimir imagens';

  @override
  String get compressionPercentage => 'Porcentagem de compressão';

  @override
  String get configure => 'Configurar';

  @override
  String get confirm => 'Confirmar';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Ilustração copiada';

  @override
  String get copiedToClipboard => 'Copiando para a Área de Transferência';

  @override
  String get copy => 'Copiar';

  @override
  String get corruptedFile => 'Não foi possível processar arquivo. Ele pode estar corrompido';

  @override
  String get couldntOpen => 'Não foi possível abrir :(';

  @override
  String get couldntOpenYtLink => 'Nenhum link do Youtube disponível para esta música';

  @override
  String get couldntPlayFile => 'Não foi possível reproduzir arquivo';

  @override
  String get couldntRenamePlaylist => 'Não foi possível renomear playlist';

  @override
  String get couldntSaveImage => 'Não foi possível salvar imagem';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'País';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Criar';

  @override
  String get createBackup => 'Criar Backup';

  @override
  String get createNewPlaylist => 'Criar nova Playlist';

  @override
  String get createdBackupSuccessfully => 'Backup criado';

  @override
  String get createdBackupSuccessfullySub => 'Arquivo de backup criado com sucesso';

  @override
  String get crossPlatformSync => 'Sincronização entre plataformas';

  @override
  String get crossfadeDuration => 'Duração da Transição Gradual';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Ativar transição gradual automaticamente nos últimos $secondsString segundos',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Não ativar transição gradual automaticamente';

  @override
  String get custom => 'Customizado';

  @override
  String get customizations => 'Customizações';

  @override
  String get customizationsSubtitle => 'Personalize a aparência do seu player, torne-o único';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'Banco de dados';

  @override
  String get date => 'Data';

  @override
  String get dateAdded => 'Adicionadas recentemente';

  @override
  String get dateCreated => 'Data Criada';

  @override
  String get dateModified => 'Data Modificada';

  @override
  String get dateTimeFormat => 'Formato Data/Tempo';

  @override
  String get day => 'Dia';

  @override
  String get days => 'Dias';

  @override
  String get defaultBackupLocation => 'Localização Padrão de Backup';

  @override
  String get defaultColor => 'Cor Padrão';

  @override
  String get defaultColorSubtitle => 'Escolher a cor usada pelo player';

  @override
  String get defaultDownloadLocation => 'Local de Download Padrão';

  @override
  String get defaultLabel => 'Padrão';

  @override
  String get defaultLibraryTab => 'Aba padrão da biblioteca';

  @override
  String get delete => 'Remover';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Deletar $countString arquivos (representando $totalSizeText)?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Permanente deletar $numberText do seu armazenamento';
  }

  @override
  String get deletePlaylist => 'Remover Playlist';

  @override
  String get deleteTempFiles => 'Deletar arquivos temporários';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Descrição';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Você quis dizer';

  @override
  String get dimIntensity => 'Intensidade do escurecimento da tela';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Escurecer miniplayer após $secondsString segundos de inatividade',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Localização não existe';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Desativar Tudo';

  @override
  String get disableReordering => 'Desabilitar Reordenamento';

  @override
  String get disableSearchCleanup => 'Desabilitar Limpeza de Busca';

  @override
  String get discNumber => 'Número do Disco';

  @override
  String get discNumberTotal => 'Total de Discos';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Não curti';

  @override
  String get dismissibleMiniplayer => 'Miniplayer Removível';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Data do Álbum na ficha do canto superior direito';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Exibir data do Álbum na ficha do canto superior direito';

  @override
  String get displayArtistBeforeTitle => 'Exibir artista antes do título';

  @override
  String get displayArtworkOnLockscreen => 'Exibir arte na tela de bloqueio';

  @override
  String get displayAudioInfoInMiniplayer => 'Exibir informações de Áudio';

  @override
  String get displayFavButtonInNotification => 'Exbir Botão de Favoritar na Notificação';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Thumbnail pode ser deslocada.';

  @override
  String get displayFavouriteIconInTrackTile => 'Exbir Botão de Favoritar';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Exibir duração restante ao invés de total';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Exibir terceiro ítem em cada linha';

  @override
  String get displayThirdRowInTrackTile => 'Exibir terceira linha';

  @override
  String get displayTrackNumberInAlbumPage => 'Exibir número da música na Página do Álbum';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Exibir um pequeno quadro contendo o número da música na página do álbum';

  @override
  String get doNothing => 'Fazer nada';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Pronto';

  @override
  String get dontAskAgain => 'Não perguntar novamente';

  @override
  String get dontDim => 'Não escureça';

  @override
  String get dontRestorePosition => 'Não restaurar';

  @override
  String get dontResume => 'Não retome';

  @override
  String get doubleTapToToggleLyrics => 'Duplo toque para ativar letra da música';

  @override
  String get download => 'Baixar';

  @override
  String get downloadingWillOverrideIt => 'Baixar irá sobrescrever';

  @override
  String get downloads => 'Downloads';

  @override
  String get downloadsMetadataTags => 'Tags Metadata dos Downloads';

  @override
  String get downloadsMetadataTagsSubtitle => 'Extrair artista, título e álbum das informações do vídeo por padrão';

  @override
  String get dragToSeek => 'Arraste para procurar';

  @override
  String get duckAudio => 'Reduzir Volume';

  @override
  String get duplicatedItemsAdding => 'Você está tentando adicionar alguns itens que já existem nesta playlist';

  @override
  String get duplicatedTracks => 'Músicas duplicadas';

  @override
  String get duration => 'Duração';

  @override
  String get edgeColorsSwitching => 'Cores dinâmicas nos cantos';

  @override
  String get edit => 'Editar';

  @override
  String get editArtwork => 'Editar Ilustração';

  @override
  String get editTags => 'Editar Tags';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'você deixou campos com valores vazios ou insignificantes, tenha certeza de que você realmente deseja editá-los';

  @override
  String get emptyValue => 'Valor Vazio';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Ativar Efeito de Borrado';

  @override
  String get enableBottomNavBar => 'Ativar Barra de Navegação Inferior';

  @override
  String get enableBottomNavBarSubtitle => 'Ítens do menu estarão no menu principal e em barra inferior';

  @override
  String get enableClipboardMonitoring => 'Permitir monitoramento de Área de Transferência';

  @override
  String get enableClipboardMonitoringSubtitle => 'Permite colar links e textos dentro da área de busca rapidamente';

  @override
  String get enableCrossfadeEffect => 'Ativar Efeito Crossfade';

  @override
  String get enableFadeEffectOnPlayPause => 'Permitir Efeito Fade ao Tocar/Pausar';

  @override
  String get enableFoldersHierarchy => 'Ativar Hierarquia de Diretórios';

  @override
  String get enableGlowEffect => 'Ativar Efeito de Brilho';

  @override
  String get enableM3uSync => 'Permitir Sincronização M3U';

  @override
  String get enableM3uSyncNote1 => 'Sincronização M3U permite salvar mudanças de playlist ao arquivo M3U original';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Se algo deu arrado, um backup desta palylist pode ser encontrado em $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Se negado, todas as mudanças feitas nesta playlist serão perdidas ao reiniciar';

  @override
  String get enableMiniplayerParticles => 'Ativar Partículas em Movimento';

  @override
  String get enableParallaxEffect => 'Ativar Efeito Parallax';

  @override
  String get enablePartyMode => 'Ativar Modo Festa';

  @override
  String get enablePartyModeSubtitle => 'Aplicar efeito edge breathing';

  @override
  String get enablePictureInPicture => 'Ativar modo Picture-in-Picture';

  @override
  String get enableReordering => 'Ativar Reordenamento';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Ativar Limpeza de Busca';

  @override
  String get enableSearchCleanupSubtitle => 'Todos os Símbolos e Espaços serão ignorados';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'Permitir Reprodução de Vídeo';

  @override
  String get enterSymbol => 'Por favor digite um Símbolo';

  @override
  String get equalizer => 'Equalizador';

  @override
  String get error => 'Erro';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Erro ao reproduzir música';

  @override
  String get excludedFodlers => 'Diretórios ignorados';

  @override
  String get exit => 'Sair';

  @override
  String get exitAppSubtitle => 'Pressione novamente para sair';

  @override
  String get expandedMiniplayer => 'Miniplayer expandido';

  @override
  String get exportAsM3u => 'Exportar como M3U';

  @override
  String get extension => 'Extensão';

  @override
  String get externalFiles => 'Arquivos externos';

  @override
  String get extract => 'Extrair';

  @override
  String get extractAllColorPalettes => 'Extrair Todas as Paletas de Cores';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Extrair $numberString Restantes?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Extrair artistas em destaque do título';

  @override
  String get extractFeatArtistSubtitle => 'Exair artistas (feat. X) e (ft. X) como entidades separadas.';

  @override
  String get extractingInfo => 'Extraindo Informações';

  @override
  String get extras => 'Extras';

  @override
  String get extrasSubtitle => 'Opções extras para refinar sua experiência';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Falhou';

  @override
  String get failedEdits => 'Edições falhadas';

  @override
  String get favourites => 'Favoritos';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Recuperando';

  @override
  String get fetchingOfAllVideos => 'Busca de todos os vídeos';

  @override
  String get file => 'Arquivo';

  @override
  String get fileAlreadyExists => 'Arquivo já existe';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Nome do arquivo';

  @override
  String get fileNameWoExt => 'Arquivo sem extensão';

  @override
  String get filenameShouldntStartWith => 'Arquivo não deve começar com';

  @override
  String get files => 'Arquivos';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Filtrar Álbuns';

  @override
  String get filterArtists => 'Filtrar Artistas';

  @override
  String get filterGenres => 'Filtrar Gêneros';

  @override
  String get filterPlaylists => 'Filtrar Playlists';

  @override
  String get filterTracks => 'Filtrar Músicas';

  @override
  String get filterTracksBy => 'Filtrar Músicas em Resultados de Busca Por';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Músicas filtradas pelo tamanho e duração';

  @override
  String get finished => 'Finalizado';

  @override
  String get finishedUpdatingLibrary => 'Biblioteca Atualizada com Sucesso';

  @override
  String get firstListen => 'Primeira escuta';

  @override
  String get fixYtdlpBigThumbnailSize => 'Consertar tamanhos grandes de thumbnail do yt-dlp';

  @override
  String get floatingActionButton => 'Botão de Ações Rápidas';

  @override
  String get folder => 'Pasta';

  @override
  String get folderName => 'Nome da Pasta';

  @override
  String get folders => 'Pastas';

  @override
  String get fontScale => 'Escala da Fonte';

  @override
  String get forceMiniplayerFollowTrackColors => 'Forçar miniplayer a seguir cores da música';

  @override
  String get forceSquaredAlbumThumbnail => 'Forçar Thumbnail de Álbum Quadrada';

  @override
  String get forceSquaredThumbnailNote => 'Tamanho e Quadro da Thumbnail NÃO são iguais, aparência não será como esparada. Deseja torná-las iguais?';

  @override
  String get forceSquaredTrackThumbnail => 'Forçar Thumbnail de Música Quadrada';

  @override
  String get forceStopColorPaletteGeneration => 'Terminar a extração de paletas de cores abruptamente? Você pode continuar depois';

  @override
  String get format => 'Formato';

  @override
  String get fullscreen => 'Tela cheia';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Gerar';

  @override
  String get generateFromDates => 'Intervalo de Tempo';

  @override
  String get generateFromDatesSubtitle => 'Gerar lista de músicas que você ouviu em determinado intervalo de tempo';

  @override
  String get generateRandomPlaylist => 'Gerar playlist aleatória';

  @override
  String get genre => 'Gênero';

  @override
  String get genres => 'Gêneros';

  @override
  String get goToAlbum => 'Ir ao Álbum';

  @override
  String get goToArtist => 'Ir ao Artista';

  @override
  String get goToChannel => 'Ir ao Canal';

  @override
  String get goToFolder => 'Ir à Pasta';

  @override
  String get goodLooking => 'Melhor aparência';

  @override
  String get grantStoragePermission => 'Conceder Permissão de Armazenamento';

  @override
  String get group => 'Grupo';

  @override
  String get groupArtworksByAlbum => 'Agrupar Ilustrações por Álbum';

  @override
  String get guide => 'Guia';

  @override
  String get hapticFeedback => 'Feedback tátil';

  @override
  String get heightOfAlbumTile => 'Altura do Título do Álbum';

  @override
  String get heightOfTrackTile => 'Altura do Título da Música';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Correspondências elevadas';

  @override
  String get highPerformance => 'Alta performance';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Histórico';

  @override
  String get historyImportMissingEntriesNote => 'Estas informações não puderam ser encontradas na biblioteca. Se você acredita que elas existem, acrescente-as manualmente';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString reproduções de $oldTrackInfo serão sustituidas por $newTrackInfo, confirmar?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Início';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'Relógio de 12 horas';

  @override
  String get hours => 'Horas';

  @override
  String get iReadAndAgree => 'Eu li e concordo';

  @override
  String get ifNotPlaying => 'Se não estiver reproduzindo';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Downloads podem ficar mais lentos quando o aplicativo tem restrições de consumo de bateria';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignorar prefixos comuns enquanto ordena';

  @override
  String get ignores => 'Ignora';

  @override
  String get imageSource => 'Fonte da imagem';

  @override
  String get immersiveMode => 'Modo Imersivo';

  @override
  String get immersiveModeSubtitle => 'Esconder barras de Status e Navegação quando o Miniplayer é expandido';

  @override
  String get import => 'Importar';

  @override
  String get importAll => 'Importar tudo';

  @override
  String get importLastFmHistory => 'Importar histórico do LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Vá em $lastfmCsvLink\n\n2. Digite seu nome de usuário, recupere e baixe o arquivo csv.\n\n3. Escolha o arquivo na próxima tela.';
  }

  @override
  String get importTimeRange => 'Importar intervalo de tempo';

  @override
  String get importYoutubeHistory => 'Importar histórico do Youtube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Vá em $takeoutLink\n\n2. Pressione \"Vários formatos\" e ao lado de \"Histórico\" escolha \"JSON\".\n\n3. Pressione \"Todos os dados Youtube\", Desselecione Tudo e selecione histórico apenas.\n\n4. Criar export, Baixar e Extrair.\n\n5. Escolha \"histórico.json\" na próxima tela.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString canais importados com sucesso',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText playlists importadas com sucesso',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Incluir vídeos';

  @override
  String get indexRefreshRequired => 'Reinicie após alterar isto';

  @override
  String get indexer => 'Indexador';

  @override
  String get indexerNote => 'Aviso: Número Incompleto de Ilustrações se refere às Ilustrações duplicadas e faltantes';

  @override
  String get indexerSubtitle => 'Gerenciar sua Biblioteca';

  @override
  String get infinityQueueOnNextPrev => 'Fila de reprodução infinita ao pressionar Próximo/Anterior';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'pressionar próximo enquanto reproduz último ítem na lista voltará ao primeiro e vice-versa';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'inserido';

  @override
  String get instantlyApplies => 'Aplicação Instantânea';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Seleção Inversa';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Ítem';

  @override
  String get jump => 'Pular';

  @override
  String get jumpToDay => 'Ir ao Dia';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Pular para a primeira música ao terminar fila de reprodução';

  @override
  String get keepCachedVersions => 'Manter versões no cache';

  @override
  String get keepFileDates => 'Manter data dos arquivos';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Miniplayer foi expandido';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Miniplayer foi expandido e um Vídeo está em Reprodução';

  @override
  String get keepScreenAwakeNone => 'Não manter tela ativa';

  @override
  String get keepScreenAwakeWhen => 'Manter tela ativa quando';

  @override
  String get killPlayerAfterDismissingApp => 'Parar player após fechar o app';

  @override
  String get language => 'Idioma';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Abas da Biblioteca';

  @override
  String get libraryTabsReorder => 'Você pode reorganizar as abas ativas.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Curtir';

  @override
  String get liked => 'Curtidos';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Lista de Diretórios';

  @override
  String get loadAll => 'Carregar tudo';

  @override
  String get loadingFile => 'Carregando Arquivo';

  @override
  String get local => 'Local';

  @override
  String get localVideoMatching => 'Correspondência de Vídeo Local';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Pressione a letra por um tempo longo para entrar no modo de tela cheia';

  @override
  String get lostMemories => 'Faz Tempo Que Não Ouve';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'nesta época, faz $numberString anos',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Intensificador de volume';

  @override
  String get lyricist => 'Letrista';

  @override
  String get lyrics => 'Letras';

  @override
  String get lyricsSource => 'Fontes das Letras';

  @override
  String get m3uPlaylist => 'Playlist M3U';

  @override
  String get makeYourFirstListen => 'Faça sua primeira reprodução!';

  @override
  String get manage => 'Gerenciar';

  @override
  String get manageYourAccounts => 'Gerenciar suas contas';

  @override
  String get manualBackup => 'Manual';

  @override
  String get manualBackupSubtitle => 'escolha um arquivo específico';

  @override
  String get markAsRead => 'Marcar como lido';

  @override
  String get matchAllTracks => 'Corresponder Toda as Músicas';

  @override
  String get matchAllTracksNote => 'isto pode impactar a velocidade de correspondência, pois irá conferir todas as músicas na sua biblioteca';

  @override
  String get matchingType => 'Tipo de Correspondência';

  @override
  String get maxAudioCacheSize => 'Tamanho máximo do cache de áudio';

  @override
  String get maxImageCacheSize => 'Tamanho máximo do cache de imagens';

  @override
  String get maxVideoCacheSize => 'Tamanho máximo do cache de vídeo';

  @override
  String get maximum => 'Máximo';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'A loja de mídia está ativada, isto não terá nenhum efeito';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Código';

  @override
  String get membershipCodeSentToEmail => 'Código enviando para o seu email';

  @override
  String get membershipDidntChange => 'A associação não mudou';

  @override
  String get membershipEnjoyNew => 'Aproveite sua nova assinatura';

  @override
  String get membershipFreeCoupon => 'Cupom Gratuito';

  @override
  String get membershipManage => 'Gerencie sua assinatura';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Nenhuma assinatura encontrada para este usuário';

  @override
  String get membershipSignInToPatreonAccount => 'Entre na sua conta do Patreon';

  @override
  String get membershipUnknown => 'Assinatura Desconhecida';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Você precisa da assinatura $name1 ou da $name2 para adicionar múltiplas contas';
  }

  @override
  String get merge => 'Mesclar';

  @override
  String get metadataCache => 'Cache de Metadata';

  @override
  String get metadataEditFailed => 'Edição de metadata falhou';

  @override
  String get metadataReadFailed => 'Leitura de metadata falhou';

  @override
  String get minFileDuration => 'Duração Mínima de Música';

  @override
  String get minFileSize => 'Tamanho Mínimo de Arquivo';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Duração mínima de música para restaurar última posição tocada';

  @override
  String get minValueCantBeMoreThanMax => 'Valor mínimo não pode ser maior que o máximo';

  @override
  String get minValueToCountTrackListen => 'Contar uma escuta após: ';

  @override
  String get minimizedMiniplayer => 'Miniplayer Minimizado';

  @override
  String get minimum => 'Mínimo';

  @override
  String get minimumOneFolderSubtitle => 'Deveria existir pelo menos 1 pasta, adicione mais pastas se deseja remover esta';

  @override
  String get minimumOneItem => 'Não foi possível remover ítem';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Pelo menos $numberString ítens devem permanecer',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Personalização do Miniplayer';

  @override
  String get minutes => 'minutos';

  @override
  String get missingEntries => 'Informações Faltantes';

  @override
  String get missingTracks => 'Músicas Perdidas';

  @override
  String get mix => 'Mixagem';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Mix playlist gerada pelo youtube';

  @override
  String get mixes => 'Mixagens';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Mês';

  @override
  String get months => 'Meses';

  @override
  String get mood => 'Humor';

  @override
  String get moods => 'Humores';

  @override
  String get more => 'Mais';

  @override
  String get mostPlayed => 'Mais Tocadas';

  @override
  String get multipleTracksTagsEditNote => 'Você está prestes a editar estas músicas,\nCampos não alterados permanecem intactos.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Nome';

  @override
  String get nameContainsBadCharacter => 'Nome contêm carater inválido';

  @override
  String get never => 'Nunca';

  @override
  String get newDirectory => 'Novo Diretório';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Adicionar Música';

  @override
  String get newTracksMoods => 'Humor';

  @override
  String get newTracksMoodsSubtitle => 'Gerar músicas baseadas nos humores disponíveis';

  @override
  String get newTracksRandom => 'Aleatório';

  @override
  String get newTracksRandomSubtitle => 'Escolher músicas aleatórias da sua biblioteca';

  @override
  String get newTracksRatings => 'Avaliações';

  @override
  String get newTracksRatingsSubtitle => 'Gerar músicas que têm avaliação específica';

  @override
  String get newTracksRecommended => 'Recomendadas';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Gerar músicas que você geralmente escuta junto com $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Data de Lançamento Semelhante';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Gerar músicas que foram lançadas na mesma época que $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Música tem ano desconhecido';

  @override
  String get newest => 'Mais novo';

  @override
  String get next => 'Next';

  @override
  String get no => 'Não';

  @override
  String get noChangesFound => 'Nenhuma mudança encontrada.';

  @override
  String get noEnoughTracks => 'Você não tem músicas suficientes..';

  @override
  String get noExcludedFolders => 'Você não tem nenhuma pasta ignorada';

  @override
  String get noFolderChosen => 'Você não selecionou nenhuma pasta';

  @override
  String get noMoodsAvailable => 'Nenhum humor disponível';

  @override
  String get noNetworkAvailableToFetchData => 'Nenhuma rede disponível para buscar dados';

  @override
  String get noTracksFound => 'Nenhuma música encontrada';

  @override
  String get noTracksFoundBetweenDates => 'Este intervalo de tempo não tem nenhuma música.';

  @override
  String get noTracksFoundInDirectory => 'Nenuma música encontrada neste diretório';

  @override
  String get noTracksInHistory => 'Você não tem músicas suficientes no seu histórico';

  @override
  String get nonActive => 'Não ativo/a';

  @override
  String get nonFavourites => 'Não Favoritos';

  @override
  String get none => 'Nenhum';

  @override
  String get normalizeAudio => 'Normalizar áudio';

  @override
  String get normalizeAudioSubtitle => 'Normaliza o volume lendo a etiqueta de ganho de repetição ou as informações fornecidas pelo Youtube';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Nota';

  @override
  String get notification => 'Notificação';

  @override
  String get notifications => 'Notificações';

  @override
  String get numberOfTracks => 'Número de músicas';

  @override
  String get ofLabel => 'de';

  @override
  String get offlineSearch => 'Busca Offline';

  @override
  String get offset => 'Offset';

  @override
  String get oldDirectory => 'Diretório Antigo';

  @override
  String get oldDirectoryStillHasTracks => 'Diretório Antigo ainda tem algumas músicas, confirmar?';

  @override
  String get oldestWatch => 'Reprodução Mais Antiga';

  @override
  String get onInterruption => 'Em interrupção';

  @override
  String get onNotificationTap => 'Ao pressionar notificação';

  @override
  String get onOpeningYoutubeLink => 'Ao abrir link do youtube';

  @override
  String get onSwiping => 'Ao Deslizar';

  @override
  String get onVolumeZero => 'Quando volume é 0';

  @override
  String get ongoing => 'Em andamento';

  @override
  String get open => 'Abrir';

  @override
  String get openApp => 'Abrir aplicativo';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Abrir em Youtube';

  @override
  String get openMiniplayer => 'Abrir Miniplayer';

  @override
  String get openQueue => 'Abrir Fila de Reprodução';

  @override
  String get openYoutubeLink => 'Abrir Link Youtube';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operação $name requer conta, faça login para prosseguir';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operação $operation necessita pelo menos da assinatura $name';
  }

  @override
  String get or => 'ou';

  @override
  String get others => 'Outros';

  @override
  String get output => 'Output';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Sobrescrever arqivos antigos na mesma pasta';

  @override
  String get palette => 'Paleta';

  @override
  String get paletteMix => 'Mixagem';

  @override
  String get paletteNewMix => 'Novo Mix';

  @override
  String get paletteSelectedMix => 'Mix Selecionado';

  @override
  String get parallelDownloads => 'Downloads Paralelos';

  @override
  String get parsed => 'analisado';

  @override
  String get password => 'Password';

  @override
  String get path => 'Caminho Completo do Arquivo';

  @override
  String get pause => 'Pausar';

  @override
  String get pauseFadeDuration => 'Duração do Fade de Pausa';

  @override
  String get pausePlayback => 'Pausar reprodução';

  @override
  String get percentage => 'Porcentagem';

  @override
  String get performanceMode => 'Modo de performance';

  @override
  String get performanceNote => 'Pode afetar performance';

  @override
  String get personalized => 'Personalizado';

  @override
  String get personalizedRelatedVideos => 'Vídeos Relacionados Personalizados';

  @override
  String get personalizedRelatedVideosSubtitle => 'Desativar isto irá aumentar o uso de dados';

  @override
  String get pickColorsFromDeviceWallpaper => 'Escolher Cores do Papel de Parede do Dispositivo';

  @override
  String get pickFromStorage => 'Escolher do armazenamento';

  @override
  String get pinned => 'Destacado';

  @override
  String get pitch => 'Tom';

  @override
  String get plain => 'Plano';

  @override
  String get play => 'Tocar';

  @override
  String get playAfter => 'Tocar depois de';

  @override
  String get playAfterNextPrev => 'Reprodução Automática no Próximo/Anterior';

  @override
  String get playAll => 'Tocar Tudo';

  @override
  String get playFadeDuration => 'Duração do Fade Durante Reprodução';

  @override
  String get playLast => 'Tocar Anterior';

  @override
  String get playNext => 'Tocar Próxima';

  @override
  String get playbackSetting => 'Reprodução';

  @override
  String get playbackSettingSubtitle => 'Pode ser acessado diretamente no player ao manter botão de áudio pressionado';

  @override
  String get playlist => 'Playlist';

  @override
  String get playlists => 'Listas de reprodução';

  @override
  String get playlistsImportM3uNative => 'Isso importará as playlists M3U para serem usadas apenas pelo namida, use se estiver migrando';

  @override
  String get playlistsImportM3uSynced =>
      'Isso importará automaticamente as playlists M3U das pastas do indexador e as manterá sincronizadas com o arquivo M3U original. habilite se você acessar/modificar as playlists de outros aplicativos';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Importar automática mente M3U playlists';

  @override
  String get pleaseEnterADifferentName => 'Este nome já existe :(\nfavor escolher outro nome';

  @override
  String get pleaseEnterALink => 'Por favor digite um link';

  @override
  String get pleaseEnterALinkSubtitle => 'Hmm.. isto é um link de youtube?';

  @override
  String get pleaseEnterAName => 'Por favor digite um nome';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Prevenir músicas duplicadas';

  @override
  String get preventDuplicatedTracksSubtitle => 'Usa nome do arquivo para identificar músicas como únicas';

  @override
  String get preview => 'Vista prévia';

  @override
  String get previous => 'Anterior';

  @override
  String get previousButtonReplays => 'Repetições de botões anteriores';

  @override
  String get previousButtonReplaysSubtitle => 'se pressionado enquanto a posição atual for maior que a duração da busca';

  @override
  String get prioritizeEmbeddedLyrics => 'Priorizar letras incorporadas';

  @override
  String get priority => 'Prioridade';

  @override
  String get private => 'Privado';

  @override
  String get progress => 'Progresso';

  @override
  String get promptToChangeTrackPath => 'Geralmente isto acontece quando você remove/move/renomeia o arquivo fora do Namida, você gostaria de atualizar caminho atual?';

  @override
  String get public => 'Público';

  @override
  String get queue => 'Fila';

  @override
  String get queues => 'Filas de Reprodução';

  @override
  String get random => 'Aleatório';

  @override
  String get randomPicks => 'Escolhas Aleatórias';

  @override
  String get rating => 'Avaliações';

  @override
  String get reIndex => 'Reindexar';

  @override
  String get reIndexSubtitle => 'Reconstruir biblioteca do zero';

  @override
  String get reIndexWarning => 'Este processo pode demorar dependendo do tamanho da biblioteca.\n\nIlustrações não serão reindexadas se ainda existirem';

  @override
  String get recentAlbums => 'Álbuns Recentes';

  @override
  String get recentArtists => 'Artistas Recentes';

  @override
  String get recentListens => 'Tocados Recentemente';

  @override
  String get recentlyAdded => 'Adicionado Recentemente';

  @override
  String get recordLabel => 'Gravadora';

  @override
  String get refresh => 'Atualizar';

  @override
  String get refreshLibrary => 'Atualizar Biblioteca';

  @override
  String get refreshLibrarySubtitle => 'Buscar músicas novas ou deletadas';

  @override
  String get refreshOnStartup => 'Atualizar na inicialização';

  @override
  String get relatedVideos => 'Vídeos relacionados';

  @override
  String get rememberAudioOnlyMode => 'Lemrar do modo somente áudio';

  @override
  String get remixer => 'Remixador';

  @override
  String get remove => 'Remover';

  @override
  String get removeDuplicates => 'Remover Duplicados';

  @override
  String get removeFromFavourites => 'Remover dos favoritos';

  @override
  String get removeFromLibrary => 'Remover da biblioteca';

  @override
  String get removeFromPlaylist => 'Remover da Playlist';

  @override
  String get removeQueue => 'Remover Fila';

  @override
  String get removeSourceFromHistory => 'Remover fontes do histórico';

  @override
  String get removeWhitespaces => 'Remover Espaços em Branco';

  @override
  String get removed => 'Removido';

  @override
  String get rename => 'Renomear';

  @override
  String get renamePlaylist => 'Renomear Playlist';

  @override
  String get reorderable => 'Reordenável';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Repetir mais $number vezes',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Modo de repetição';

  @override
  String get repeatModeAll => 'Repetir Toda a Fila';

  @override
  String get repeatModeNone => 'Parar na Última Música';

  @override
  String get repeatModeOne => 'Repetir Música Atual';

  @override
  String get replaceAllListensWithAnotherTrack => 'Sustituir todas as escutadas por uma música nova';

  @override
  String get replies => 'Respostas';

  @override
  String get reply => 'Resposta';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Requer limpeza do cache de imagens e reindexação';

  @override
  String get rescanVideos => 'Reescanear vídeos';

  @override
  String get resetBrightness => 'Restaurar brilho';

  @override
  String get resetToDefault => 'Estabelecer';

  @override
  String get respectNoMedia => 'Respeitar .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Não incluir pastas que incluem .nomedia';

  @override
  String get restart => 'Reiniciar';

  @override
  String get restoreBackup => 'Restaurar Backup';

  @override
  String get restoreDefaults => 'Restaurar Padrões';

  @override
  String get restoredBackupSuccessfully => 'Backup Restaurado';

  @override
  String get restoredBackupSuccessfullySub => 'Arquivo de Backup restaurado com sucesso';

  @override
  String get resume => 'Continuar';

  @override
  String get resumeIfWasInterrupted => 'Continuar caso pausado por uma interrupção';

  @override
  String get resumeIfWasPausedByVolume => 'Continuar caso pausado pelo volume';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Resumir se estiver pausado por menos de $numberString minutos',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Ordem Inversa';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Toque';

  @override
  String get sameDirectoryOnly => 'Mesmo diretório apenas';

  @override
  String get sample => 'Amostra';

  @override
  String get sampleRate => 'Taxa de Amostra';

  @override
  String get save => 'Salvar';

  @override
  String get saveToLibrary => 'Salvar na biblioteca';

  @override
  String get savedIn => 'Salvo em';

  @override
  String get scaleMultiplier => 'Multiplicador de Escala';

  @override
  String get search => 'Buscar';

  @override
  String get searchYoutube => 'Procurar no YouTube';

  @override
  String get seconds => 'segundos';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Duração de Busca';

  @override
  String get seekDurationInfo => 'Você pode pressionar a duração atual para buscar para trás e duração total para buscar para frente';

  @override
  String get seekbar => 'Barra de busca';

  @override
  String get selectAll => 'Selecionar Tudo';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Selecione os arquivos já existentes na biblioteca local';

  @override
  String get selectedTracks => 'Músicas Selecionadas';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Estas palavras não serão divididas';

  @override
  String get separatorsMessage => 'Não é necessário inserir espaços, a não ser que queria usar uma letra ou símbolo que pode ser encontrado numa palavra completa (como x e ft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Set as';

  @override
  String get setAsDefault => 'Estabelecer como Padrão';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Arqivo selecionado modificado como data de upload do vídeo';

  @override
  String get setMoods => 'Estabelecer humores';

  @override
  String get setMoodsSubtitle => 'Usar vírgulas (,) para separar um elemento do outro';

  @override
  String get setRating => 'Avaliar';

  @override
  String get setTags => 'Criar Tags';

  @override
  String get setYoutubeLink => 'Associar a um Vídeo do Youtube';

  @override
  String get settings => 'Configurações';

  @override
  String get setupFirstStartup => 'Configurações primeira vez';

  @override
  String get share => 'Compartilhar';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Atalhos';

  @override
  String get shouldDuck => 'Deveria Diminuir Volume';

  @override
  String get shouldDuckNote => 'Indica se o volume deveria ser abaixado. ex: notificação';

  @override
  String get shouldPause => 'Deveria Pausar';

  @override
  String get shouldPauseNote => 'Indica se a reprodução deveria ser pausada. ex: ligações';

  @override
  String get showAll => 'Mostrar Tudo';

  @override
  String get showChannelWatermarkInFullscreen => 'Mostrar marca d\'água do canal em tela cheia';

  @override
  String get showFailedOnly => 'Mostrar apenas falhas';

  @override
  String get showHideUnknownFields => 'Exibir/ocultar Campos Desconhecidos';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Mostrar mixagens em';

  @override
  String get showMore => 'Mostrar mais';

  @override
  String get showShortVideosIn => 'Mostrar Shorts em';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'Mostrar cartões finais do vídeo';

  @override
  String get showWebm => 'Mostrar webm';

  @override
  String get shuffle => 'Embaralhar';

  @override
  String get shuffleAll => 'Embaralhar Tudo';

  @override
  String get shuffleNext => 'Embaralhar Próxima';

  @override
  String get signIn => 'Login';

  @override
  String get signInCanceled => 'O login foi cancelado';

  @override
  String get signInFailed => 'O login falhou';

  @override
  String get signInToYourAccount => 'Faça login na sua conta';

  @override
  String get signInYouDontHaveAccount => 'Você não está logado em nenhuma conta';

  @override
  String get signInYouNeedAccountToViewPage => 'Você precisa de uma conta para ver essa página';

  @override
  String get signOut => 'Deslogar';

  @override
  String signOutFromName({required String name}) {
    return 'Deslogar de $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'O login permite o uso básico';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Obtenha acesso antecipado através do Patreon ou usando um cupom';

  @override
  String get similarDiscoverDate => 'Data de descoberta semelhante';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Gera faixas que você descobriu por volta do mesmo tempo que $currentTrack';
  }

  @override
  String get similarTimeRange => 'Intervalo de tempo semelhante';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Gera faixas que você ouviu por volta do mesmo tempo que $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'Tamanho';

  @override
  String get skip => 'Pular';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Pular Silêncio';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Modo de repouso após';

  @override
  String get sleepTimer => 'Tempo de Repouso';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Ordenar Por';

  @override
  String get source => 'Fonte';

  @override
  String get speed => 'Velocidade';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Visualização de Grade de Álbuns Deslocada';

  @override
  String get start => 'Começar';

  @override
  String get stats => 'Estatísticas';

  @override
  String get statsSubtitle => 'Aqui estão algumas informações sore sua biblioteca';

  @override
  String get stop => 'Parar';

  @override
  String get stopAfterThisTrack => 'Parar depois desta música';

  @override
  String get stopAfterThisVideo => 'Pausar depois deste vídeo';

  @override
  String get storagePermissionDenied => 'Permissão negada';

  @override
  String get storagePermissionDeniedSubtitle => 'Favor permitir acesso para poder realizar esta ação';

  @override
  String get stretchLyricsDuration => 'Extender duração das letras';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Inscrever-se';

  @override
  String get subscribed => 'Inscrito';

  @override
  String get subscriber => 'Inscrito';

  @override
  String get subscribers => 'Inscritos';

  @override
  String get succeeded => 'Sucesso';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Suporte';

  @override
  String get supremacy => 'Supremacia';

  @override
  String get sussyBaka => 'Bruh sem música';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Deslizar para abrir menu';

  @override
  String get synced => 'Sincronizado';

  @override
  String get synopsis => 'Sinopse';

  @override
  String get tagFields => 'Campo de Tag';

  @override
  String get tags => 'Tags';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Toque para buscar';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Modo do Tema';

  @override
  String get themeModeDark => 'Escuro';

  @override
  String get themeModeLight => 'Claro';

  @override
  String get themeModeSystem => 'Sistema';

  @override
  String get themeSettings => 'Tema';

  @override
  String get themeSettingsSubtitle => 'O vibe geral do seu player';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Esta lista de reprodução tem ordenadores ativos, por favor os desative antes de reordenar.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'É possível que este vídeo tenha sido deletado ou definido como privado.';

  @override
  String get thumbnails => 'Miniaturas';

  @override
  String get title => 'Título';

  @override
  String get top => 'Topo';

  @override
  String get topComments => 'Melhores comentários';

  @override
  String get topCommentsSubtitle => 'Mostrar comentários no todo ao invés do fundo';

  @override
  String get topRecentAlbums => 'Melhores Álbuns Recentes';

  @override
  String get topRecentArtists => 'Melhores Artistas Recentes';

  @override
  String get topRecents => 'Melhores Recentes';

  @override
  String get totalListenTime => 'Tempo Total de Escuta';

  @override
  String get totalListens => 'Escutas totais';

  @override
  String get totalTracks => 'Músicas Totais';

  @override
  String get totalTracksDuration => 'Duração Total de Músicas';

  @override
  String get track => 'Música';

  @override
  String get trackArtistsSeparator => 'Separador de Artistas';

  @override
  String get trackGenresSeparator => 'Separador de Gêneros';

  @override
  String get trackInfo => 'Informação da Música';

  @override
  String get trackNotFound => 'Música não encontrada';

  @override
  String get trackNumber => 'Número da Música';

  @override
  String get trackNumberTotal => 'Músicas Totais';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Nome antigo: \"$oldName\"\n\nNome novo: \"$newName\"\n\nTem certeza?';
  }

  @override
  String get trackPlayMode => 'Modo de Reprodução';

  @override
  String get trackPlayModeSearchResults => 'Resultados da Busca';

  @override
  String get trackPlayModeSelectedOnly => 'Música Selecionada Apenas';

  @override
  String get trackPlayModeTrackAlbum => 'Álbum da Música';

  @override
  String get trackPlayModeTrackArtist => 'Artista Principal';

  @override
  String get trackPlayModeTrackGenre => 'Gênero da Música';

  @override
  String get trackThumbnailSizeInList => 'Tamanho da Thumbnail';

  @override
  String get trackTileCustomization => 'Personalização da Imagem da Música';

  @override
  String get trackTileItemsSeparator => 'Separador';

  @override
  String get tracks => 'Músicas';

  @override
  String get tracksExcludedByNomedia => 'Músicas ignoradas por .nomedia';

  @override
  String get tracksInfo => 'Informação das Músicas';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Desfazer';

  @override
  String get undoChanges => 'Desfazer alterações?';

  @override
  String get undoChangesDeletedPlaylist => 'Restaurar playlist removida';

  @override
  String get undoChangesDeletedQueue => 'Restaurar Fila de Reprodução removida';

  @override
  String get undoChangesDeletedTrack => 'Restaurar Música removida';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Ilimitado';

  @override
  String get unlisted => 'Não listado';

  @override
  String get unlock => 'Desbloquear';

  @override
  String get update => 'Atualizar';

  @override
  String get updateDirectoryPath => 'Atualizar caminho do diretório';

  @override
  String get updateMissingTracksOnly => 'Atualizar múscas faltantes apenas';

  @override
  String get updating => 'Atualizando';

  @override
  String get useCollapsedSettingTiles => 'Menus de Configuração em Páginas Separadas';

  @override
  String get useMediaStore => 'Usar Loja de Mídia';

  @override
  String get useMediaStoreSubtitle =>
      '✓ indexação instantânea\nx respeitar .nomedia será obrigatoriamente habilitado\nx certas metadata tags não serão obtidas\nx integração do youtube com biblioteca local não irá funcionar';

  @override
  String get usePitchBlack => 'Usar Preto Puro';

  @override
  String get usePitchBlackSubtitle => 'Útil para telas AMOLED... e é mais bonito';

  @override
  String get used => 'Usado';

  @override
  String get value => 'Valor';

  @override
  String get valueBetween50200 => 'O valor deve estar entre 50% e 200%';

  @override
  String get vibration => 'Vibração';

  @override
  String get vibrationType => 'Tipo de vibração';

  @override
  String get video => 'Vídeo';

  @override
  String get videoCache => 'Cache de Vídeo';

  @override
  String get videoCacheFile => 'Arquivo do Cache de Vídeo';

  @override
  String get videoCacheFiles => 'Arquivos do Cache de Vídeo';

  @override
  String get videoOnly => 'Vídeo Apenas';

  @override
  String get videoPlaybackSource => 'Fonte do Vídeo';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Isto irá priorizar vídeos locais, caso não encontrados irá procurá-los no Youtube';

  @override
  String get videoPlaybackSourceLocal => 'Víeos Locais';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVídeo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Confere se algum arquivo de vídeo (encontrado na lista de pastas selecionada) tem um nome de arquivo que contem o nome da música';

  @override
  String get videoPlaybackSourceYoutube => 'Do Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Registra o nome de arquivo e comentário para qualquer link de youtube correspondente, vídeos serão guardados no cache para uso futuro.';

  @override
  String get videoQuality => 'Qualidade do Vídeo';

  @override
  String get videoQualitySubtitle => 'A quallidade mais alta disponível será escolhida.';

  @override
  String get videoQualitySubtitleNote => 'É sempre bom ter mais opções no caso de uma qualidade não ser encontrada, caso contrário irá reverter para a qualidade mais baixa';

  @override
  String get videos => 'Vídeos';

  @override
  String get view => 'visualização';

  @override
  String get viewAll => 'Visualizar Tudo';

  @override
  String get views => 'visualizações';

  @override
  String get volume => 'Volume';

  @override
  String get warning => 'Cuidado';

  @override
  String get waveformBarsCount => 'Quantidade de Barras Waveform';

  @override
  String get webmNoEditTagsSupport => 'Formato WEBM não suporta edição de tags';

  @override
  String get week => 'Semana';

  @override
  String get year => 'Ano';

  @override
  String get yes => 'sim';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Sua assinatura atual é $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Seu pedido personalizado será perdido, tem certeza?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Música';

  @override
  String get youtubeSettingsSubtitle => 'Personalizar experiência Youtube';

  @override
  String get youtubeStyleMiniplayer => 'Miniplayer estilo Youtube';

  @override
  String get ytPreferNewComments => 'Dar preferência a comentários novos quando possível';

  @override
  String get ytPreferNewCommentsSubtitle => 'Versão guardada no cache será usada apenas quando não há conexão';
}
