// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Finnish (`fi`).
class AppLocalizationsFi extends AppLocalizations {
  AppLocalizationsFi([String locale = 'fi']) : super(locale);

  @override
  String get about => 'Tietoja';

  @override
  String get active => 'Aktiivi';

  @override
  String get add => 'Lisätä';

  @override
  String get addAccount => 'Lisätä tili';

  @override
  String get addAll => 'Lisätä kaikki';

  @override
  String get addAllAndRemoveOldOnes => 'Lisätä kaikki ja poista vanhat';

  @override
  String get addAsANewPlaylist => 'Lisätä uudeksi soittolistaksi';

  @override
  String get addAudioToLocalLibrary => 'Lisää ääni paikalliseen kirjastoon';

  @override
  String get addFolder => 'Lisätä Kansio';

  @override
  String get addLanguage => 'Lisätä kieli';

  @override
  String get addLanguageSubtitle => 'Auta kääntää Namida sinun oma kieleksi';

  @override
  String get addLrcFile => 'Lisätä LRC tiedosto';

  @override
  String get addMoreFromThisAlbum => 'Lisätä lisää tästä albumista jonoon';

  @override
  String get addMoreFromThisArtist => 'Lisätä lisää tästä artistilta jonoon';

  @override
  String get addMoreFromThisFolder => 'Lisätä lisää tästä kansiosta jonoon';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Lisätä jonoon ${media}sta';
  }

  @override
  String get addOnlyMissing => 'Lisätä vain puuttuvat';

  @override
  String get addToFavourites => 'Lisätä suosikkeihin';

  @override
  String get addToPlaylist => 'Lisätä soittiolistaan';

  @override
  String get addTracksAtTheBeginning => 'Lisää kappaleita alkuun';

  @override
  String get added => 'Lisätty';

  @override
  String get advanced => 'Kehittynyt';

  @override
  String get advancedSettings => 'Lisäasetukset';

  @override
  String get advancedSettingsSubtitle => 'Lisäasetukset, Älä koske';

  @override
  String get alarm => 'Herätyskello';

  @override
  String get album => 'Albumi';

  @override
  String get albumArtist => 'Albumien Muusikko';

  @override
  String get albumArtists => 'Albumi muusikot';

  @override
  String get albumIdentifiers => 'Albumin Tunnisteet';

  @override
  String get albumThumbnailSizeInList => 'Albumin valokuvan koko';

  @override
  String get albumTileCustomization => 'Albumin kannen mukauttaminen';

  @override
  String get albums => 'Albumit';

  @override
  String get albumsCount => 'Albumien määrä';

  @override
  String get all => 'Kaikki';

  @override
  String get allTime => 'Kaikki aikaa';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Aina';

  @override
  String get alwaysAsk => 'Aina kysy';

  @override
  String get alwaysDim => 'Himmennä Aina';

  @override
  String get alwaysExpandedSearchbar => 'Aina laajentaa hakualue';

  @override
  String get alwaysRestore => 'Aina entisöidä';

  @override
  String get animatingThumbnailIntensity => 'Kannen Animaation Intensiteetti';

  @override
  String get animatingThumbnailInversed => 'Päinvastoin animaatiot';

  @override
  String get animatingThumbnailInversedSubtitle => 'Korkea piikit pienentävät kantta';

  @override
  String get anotherProcessIsRunning => 'Toinen prosessi on jo käytössä.';

  @override
  String get appIcon => 'Sovelluksen kuvake';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Muusikko';

  @override
  String get artists => 'Muusikot';

  @override
  String get artwork => 'Kuvamateriaali';

  @override
  String get artworkGestures => 'Kuvamateriaali Elkeet';

  @override
  String get artworks => 'Kuvamateriaalia';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Audio Välimuisti';

  @override
  String get audioOnly => 'Vain Audio';

  @override
  String get auto => 'Auto';

  @override
  String get autoBackupInterval => 'Automaattinen varmuuskopiointiväli';

  @override
  String get autoColoring => 'Auto väritys';

  @override
  String get autoColoringSubtitle => 'Valitse automaattisesti soittimen värit nykyisestä taideteoksesta';

  @override
  String get autoExtractTagsFromFilename => 'Automaattisesti ota tiedostosta';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Automaattinen ota otsikosta ja esittäjä videon nimestä';

  @override
  String get autoGenerated => 'Luotu automaattisesti';

  @override
  String get autoSkip => 'Automaattinen ohitus';

  @override
  String get autoSkipOnce => 'Automaattinen ohitus kerran';

  @override
  String get autoStartRadio => 'Automaattisesti aloita radio';

  @override
  String get autoStartRadioSubtitle => 'Lisätä automaattisesti sekoitussoittolistan kappaletta toistettaessa';

  @override
  String get automaticBackup => 'Automaattinen';

  @override
  String get automaticBackupSubtitle => 'Käyttää automaattisesti viimeisintä varmuuskopiotiedostoa, joka löytyy varmuuskopion sijainnista';

  @override
  String get backupAndRestore => 'varmuuskopiointi ja palautus';

  @override
  String get backupAndRestoreSubtitle => 'Varmuuskopioi tietokanta ja asetukset';

  @override
  String get balanced => 'Tasapainoinen';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Päivämäärien välillä';

  @override
  String get bitrate => 'Bittinopeus';

  @override
  String get blacklist => 'Blacklisti';

  @override
  String get borderRadiusMultiplier => 'Reunuksen Säteen Kerroin';

  @override
  String get cache => 'Välimuisti';

  @override
  String get cancel => 'Peruuttaa';

  @override
  String get canceled => 'Peruuttettu';

  @override
  String get changed => 'Vaihtaatu';

  @override
  String get changelog => 'Muutusloki';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Kanava';

  @override
  String get channels => 'Kanavat';

  @override
  String get check => 'Varmistaa';

  @override
  String get checkForMore => 'Tarkistaa lisääle';

  @override
  String get checkList => 'Tarkistuslista';

  @override
  String get choose => 'Valita';

  @override
  String get chooseWhatToClear => 'Valita mitä sinä halut tyhjä';

  @override
  String get claim => 'Väittää';

  @override
  String get clear => 'Tyhjä';

  @override
  String get clearAudioCache => 'Tyhjä Audio Välimuisti';

  @override
  String get clearImageCache => 'Tyhjä kuva välimuisti';

  @override
  String get clearImageCacheWarning => 'Varoitus: lähte kirjastoon ilman kuvia. Käytä vain rakenta uusi kuvavälimuisti.';

  @override
  String get clearTrackItem => 'Tyhjä kappaleita';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Tyhjä $numberString kappaletta',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Tyhjä video Välimuisti';

  @override
  String get clearVideoCacheNote => 'Voit valita mitä haluat poistaa.';

  @override
  String get clock => 'Kello';

  @override
  String get colorPalette => 'Väripaletti';

  @override
  String get colorPaletteNote1 => 'Poista väri painamalla pitkään';

  @override
  String get colorPaletteNote2 => 'Napauta sekoitusta käytettäväksi oletuksena väri';

  @override
  String get colorPalettes => 'Väripaletteja';

  @override
  String get comment => 'Kommenti';

  @override
  String get comments => 'Kommentit';

  @override
  String get composer => 'Säveltäjä';

  @override
  String get compress => 'Pakkaa';

  @override
  String get compressImages => 'Pakkaa valokuvat';

  @override
  String get compressionPercentage => 'Pakkaa prosenttia';

  @override
  String get configure => 'Konfiguroida';

  @override
  String get confirm => 'Vahvista';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'Kopioida Taideteos';

  @override
  String get copiedToClipboard => 'Kopioitu Leikepöydälle';

  @override
  String get copy => 'Kopioida';

  @override
  String get corruptedFile => 'Tiedostoa ei voitu jäsentää, se saattaa olla korruptoitunut';

  @override
  String get couldntOpen => 'Ei voinut avata :(';

  @override
  String get couldntOpenYtLink => 'Tälle kappaleelle ei ole Youtube-linkkiä';

  @override
  String get couldntPlayFile => 'Ei voinut pelata tiedosto';

  @override
  String get couldntRenamePlaylist => 'Ei voinut antaa soittiolista uusi nimi';

  @override
  String get couldntSaveImage => 'Ei voinut tallentaa';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Maa';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Luoda';

  @override
  String get createBackup => 'Luoda Varmuuskopio';

  @override
  String get createNewPlaylist => 'Luoda uusi Soittolista';

  @override
  String get createdBackupSuccessfully => 'Luotu Varmuuskopio';

  @override
  String get createdBackupSuccessfullySub => 'Varmuuskopiotiedosto on luotu onnistuneesti';

  @override
  String get crossPlatformSync => 'Alustojen välinen Sync';

  @override
  String get crossfadeDuration => 'Ristihäivytyksen kesto';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Käynnistä Crossfade automaattisesti viimeisen $secondsString sekunnin aikana',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Älä käynnistä ristihäivytystä automaattisesti';

  @override
  String get custom => 'Mukautettu';

  @override
  String get customizations => 'Mukautuksia';

  @override
  String get customizationsSubtitle => 'Mukauta kuinka soittimesi näyttää, tee siitä omasi! :)';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Datan säästin';

  @override
  String get dataSaverMode => 'Datan säästötila';

  @override
  String get database => 'Tietokanta';

  @override
  String get date => 'Päivämäärä';

  @override
  String get dateAdded => 'Päivämäärä Lisätty';

  @override
  String get dateCreated => 'Päivämäärä Luotu';

  @override
  String get dateModified => 'Päivämäärä Muokattu';

  @override
  String get dateTimeFormat => 'päivämäärän ja aika';

  @override
  String get day => 'Päivää';

  @override
  String get days => 'Päivät';

  @override
  String get defaultBackupLocation => 'Oletus varmuuskopio sijainti';

  @override
  String get defaultColor => 'Oletusväri';

  @override
  String get defaultColorSubtitle => 'Aseta soittimen käyttämä väri';

  @override
  String get defaultDownloadLocation => 'Oletuslataussijainti';

  @override
  String get defaultLabel => 'Oletus';

  @override
  String get defaultLibraryTab => 'Oletuskirjasto välilehti';

  @override
  String get delete => 'Poista';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Poistetaanko $countString tiedostoa, jotka edustavat kokoa $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Poista pysyvästi $numberText tallennustilastasi';
  }

  @override
  String get deletePlaylist => 'Poista soittolista';

  @override
  String get deleteTempFiles => 'Poista väliaikaiset tiedostot';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Kuvaus';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Tarkoititko';

  @override
  String get dimIntensity => 'Himmeä intensiteetti';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Himmentää minisoitinta $secondsString sekunnin käyttämättömyyden jälkeen',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Hakemistoa ei ole olemassa';

  @override
  String get disable => 'Poista käytöstä';

  @override
  String get disableAll => 'Poista kaikki käytöstä';

  @override
  String get disableReordering => 'Poista uudelleenjärjestely käytöstä';

  @override
  String get disableSearchCleanup => 'Poista Haku Puhdistus käytöstä';

  @override
  String get discNumber => 'Disc Numero';

  @override
  String get discNumberTotal => 'Disc totaali';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'En tykkää';

  @override
  String get dismissibleMiniplayer => 'Ohitettava minisoitin';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Albumikortin päivämäärä oikealla ylhäällä';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Näytä albumin päivämäärä albumikortin oikeassa yläkulmassa';

  @override
  String get displayArtistBeforeTitle => 'Näytä artisti ennen nimi';

  @override
  String get displayArtworkOnLockscreen => 'Näytä kuvitus lukitusnäytöllä';

  @override
  String get displayAudioInfoInMiniplayer => 'Näytä äänitiedot';

  @override
  String get displayFavButtonInNotification => 'Näytä suosikkipainike ilmoituksessa';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Pikkukuva saattaa siirtyä vaarin paikkaan.';

  @override
  String get displayFavouriteIconInTrackTile => 'Näytä suosikkipainike';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Näytä jäljellä oleva kesto kokonaismäärän sijaan';

  @override
  String get displayStopButtonInNotification => 'Näytä pysäytys nappi ilmoituksessa';

  @override
  String get displayThirdItemInRowInTrackTile => 'Näytä kolmas kohde jokaisella rivillä';

  @override
  String get displayThirdRowInTrackTile => 'Näytä kolmas rivi';

  @override
  String get displayTrackNumberInAlbumPage => 'Näytä kappaleen numero albumisivulla';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Näytä albumisivulla pieni laatikko, joka sisältää kappaleen numeron';

  @override
  String get doNothing => 'Ei tee mitään';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Tehty';

  @override
  String get dontAskAgain => 'Älä kysy uudestaan';

  @override
  String get dontDim => 'Älä Himmennä';

  @override
  String get dontRestorePosition => 'Älä palauttaa';

  @override
  String get dontResume => 'Älä jatkaa';

  @override
  String get doubleTapToToggleLyrics => 'Vaihda sanoituksia kaksoisnapauttamalla';

  @override
  String get download => 'Lataa';

  @override
  String get downloadingWillOverrideIt => 'Lataaminen ohittaa sen';

  @override
  String get downloads => 'Lataukset';

  @override
  String get downloadsMetadataTags => 'Lataa Metatietotunnisteita';

  @override
  String get downloadsMetadataTagsSubtitle => 'Pura esittäjä, nimi ja albumi videon tiedoista oletuksena';

  @override
  String get dragToSeek => 'Vedä etsiäksesi';

  @override
  String get duckAudio => 'Alentaa audio';

  @override
  String get duplicatedItemsAdding => 'Yrität lisätä joitain kohteita, jotka ovat jo olemassa tässä soittolistassa';

  @override
  String get duplicatedTracks => 'Kopioidut kappaleet';

  @override
  String get duration => 'Kesto';

  @override
  String get edgeColorsSwitching => 'Reunojen värin vaihto';

  @override
  String get edit => 'Muokata';

  @override
  String get editArtwork => 'Muokkaa kuvitusta';

  @override
  String get editTags => 'Muokkaa tunnisteita';

  @override
  String get email => 'Email';

  @override
  String get emptyNonMeaningfulTagFields => 'sinulla on kenttiä, joissa on tyhjiä vai merkityksettömiä arvoja, varmista, että haluat todella muokata niitä';

  @override
  String get emptyValue => 'Tyhjä arvo';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Käyttää suomennus';

  @override
  String get enableBottomNavBar => 'Käyttää pohja navigointipalkki';

  @override
  String get enableBottomNavBarSubtitle => 'Tavarat ovat laatikon sisällä molempiin suuntiin';

  @override
  String get enableClipboardMonitoring => 'Käyttää Leikepöydän valvonta';

  @override
  String get enableClipboardMonitoringSubtitle => 'Anna linkkien ja tekstin liittäminen hakupalkkiin liikkeellä ollessasi';

  @override
  String get enableCrossfadeEffect => 'Käyttää Ristihäivytys';

  @override
  String get enableFadeEffectOnPlayPause => 'Käyttää Sammui kun musiikki toisto/tauko';

  @override
  String get enableFoldersHierarchy => 'Käyttää kansiohierarkia';

  @override
  String get enableGlowEffect => 'Käyttää hehkuefekti';

  @override
  String get enableM3uSync => 'Käyttää M3U Sync';

  @override
  String get enableM3uSyncNote1 => 'M3U Sync antaa soitolista tallenna muutokset alkuperäinen M3U tiedostolle';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Jos jokin meni väärin, tämän soittolistan varmuuskopio löytyy osoitteesta $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Jos ei antaa, kaikki muutokset tehty tämä soitolistalle menetetään uudelleenkäynnistyksen yhteydessä';

  @override
  String get enableMiniplayerParticles => 'Salli liikkuvat hiukkaset';

  @override
  String get enableParallaxEffect => 'Käyttää parallaksiefekti';

  @override
  String get enablePartyMode => 'Käyttää juhlatila';

  @override
  String get enablePartyModeSubtitle => 'Käytä hienoa reunahengitystehoa';

  @override
  String get enablePictureInPicture => 'Ota kuva kuvassa käyttöön';

  @override
  String get enableReordering => 'Käyttää uudelleenjärjestely';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Käyttää Haku Puhdistus';

  @override
  String get enableSearchCleanupSubtitle => 'Kaikki symbolit ja välilyönnit ohitetaan';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'Ota käyttöön videotoisto';

  @override
  String get enterSymbol => 'Syötä symboli';

  @override
  String get equalizer => 'Taajuuskorjain';

  @override
  String get error => 'Virhe';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Virhe pelaamassa kappale';

  @override
  String get excludedFodlers => 'Poissuljetut kansiot';

  @override
  String get exit => 'Poistu';

  @override
  String get exitAppSubtitle => 'Poistu napauttamalla uudelleen';

  @override
  String get expandedMiniplayer => 'Laajennettu minisoitin';

  @override
  String get exportAsM3u => 'Viedä kun M3U';

  @override
  String get extension => 'Laajennus';

  @override
  String get externalFiles => 'Ulkoiset Tiedostot';

  @override
  String get extract => 'Purkaa';

  @override
  String get extractAllColorPalettes => 'Pura Kaikki Väripaletit';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Pura kaikki jäljellä $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Pura feat. muusikot nimestä';

  @override
  String get extractFeatArtistSubtitle => 'Pura (feat. X) ja (ft. X) muusikot, uutena muusikkona.';

  @override
  String get extractingInfo => 'Tietojen Poimiminen';

  @override
  String get extras => 'Ekstrat';

  @override
  String get extrasSubtitle => 'Lisäasetukset parantaaksesi käyttökokemustasi';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Ei toiminut';

  @override
  String get failedEdits => 'Muokkauksia ei toiminut';

  @override
  String get favourites => 'Lempparit';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Haetaan';

  @override
  String get fetchingOfAllVideos => 'Kaikkien videoiden hakeminen';

  @override
  String get file => 'Tiedosto';

  @override
  String get fileAlreadyExists => 'Tiedosto on jo olemassa';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Teidosto nimi';

  @override
  String get fileNameWoExt => 'Tiedostonimi ilman päätettä';

  @override
  String get filenameShouldntStartWith => 'Tiedostonimen ei pitäisi alkaa tan kanssa =';

  @override
  String get files => 'Tiedostot';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Suodata albumit';

  @override
  String get filterArtists => 'Suodata Muusikot';

  @override
  String get filterGenres => 'Suodata Genres';

  @override
  String get filterPlaylists => 'Suodata Soittolistat';

  @override
  String get filterTracks => 'Suodata kappaleita';

  @override
  String get filterTracksBy => 'Suodattaa kappaleita hakulistasa kautta';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Kappaleet suodatettu koko ja keston kanssa';

  @override
  String get finished => 'Valmis';

  @override
  String get finishedUpdatingLibrary => 'Kirjaston Päivitys Valmis';

  @override
  String get firstListen => 'Ensin kuuntele';

  @override
  String get fixYtdlpBigThumbnailSize => 'Korjaa yt-dlp:n iso kuvituskoko';

  @override
  String get floatingActionButton => 'Kelluva Painike';

  @override
  String get folder => 'Kansio';

  @override
  String get folderName => 'Kansio Nimi';

  @override
  String get folders => 'Kansiot';

  @override
  String get fontScale => 'Fonttikoko';

  @override
  String get forceMiniplayerFollowTrackColors => 'Pakota minisoitin seuraamaan kappaleiden värejä';

  @override
  String get forceSquaredAlbumThumbnail => 'Pakottaa Neliöity Albumi Kuva';

  @override
  String get forceSquaredThumbnailNote => 'Kuvan koko ja laatan korkeus EIVÄT ole sama, neliömäinen ulkoasu ei ole odotetusti, Haluatko tehdä se oka tapauksessa?';

  @override
  String get forceSquaredTrackThumbnail => 'Pakottaa Neliöity Musiikkikappale Kuva';

  @override
  String get forceStopColorPaletteGeneration => 'Pakotetaanko väripalettien poimiminen lopettamaan? voit silti jatkaa sitä myöhemmin';

  @override
  String get format => 'Muoto';

  @override
  String get fullscreen => 'Kokoruutu';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Luo';

  @override
  String get generateFromDates => 'Aikaväli';

  @override
  String get generateFromDatesSubtitle => 'Luo kappaleita, joita olet kuunnellut tietyllä aikavälillä';

  @override
  String get generateRandomPlaylist => 'Luo satunnainen soittolista';

  @override
  String get genre => 'Genre';

  @override
  String get genres => 'Genres';

  @override
  String get goToAlbum => 'Mennä Albumiin';

  @override
  String get goToArtist => 'Mene Muusikon';

  @override
  String get goToChannel => 'Mene kanavalle';

  @override
  String get goToFolder => 'Mene Kansoille';

  @override
  String get goodLooking => 'Hyvän näköinen';

  @override
  String get grantStoragePermission => 'Anna Tallennuslupa';

  @override
  String get group => 'Ryhmä';

  @override
  String get groupArtworksByAlbum => 'Ryhmittele teoksia albumin mukaan';

  @override
  String get guide => 'Ohje';

  @override
  String get hapticFeedback => 'Haptinen palaute';

  @override
  String get heightOfAlbumTile => 'Albumin kuva korkeus';

  @override
  String get heightOfTrackTile => 'Radan kuva korkeus';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Korkeus Vastaavat';

  @override
  String get highPerformance => 'Korkea Suorituskyky';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Historia';

  @override
  String get historyImportMissingEntriesNote => 'Näitä merkintöjä ei löydy kirjastosta. Jos uskot niiden olevan olemassa, harkitse niiden lisäämistä manuaalisesti';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$oldTrackInfo ( $listensCountString ) kuuntelumääräsi korvataan $newTrackInfo :lla, Oletko varma?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Koti';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12 Tunni kello';

  @override
  String get hours => 'Tunnit';

  @override
  String get iReadAndAgree => 'Luin ja Soustan';

  @override
  String get ifNotPlaying => 'Jos ei pelaa';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Latauksia voidaan rajoittaa, kun sovelluksen akku on rajoitettu';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignore common prefixes while sorting';

  @override
  String get ignores => 'Ohittaa';

  @override
  String get imageSource => 'Kuvan lähde';

  @override
  String get immersiveMode => 'Mukaansatempaavatila';

  @override
  String get immersiveModeSubtitle => 'Piilota tila ja navigointipalkit, kun minisoitin laajenee';

  @override
  String get import => 'Tuoda';

  @override
  String get importAll => 'Tuo kaikki';

  @override
  String get importLastFmHistory => 'Tuo LastFm-historia';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Siirry osoitteeseen $lastfmCsvLink\n\n 2. Kirjoita käyttäjänimesi, hae ja lataa csv-tiedosto.\n\n 3. Valitse tiedosto seuraavasta näytöstä.';
  }

  @override
  String get importTimeRange => 'Tuo aikaväli';

  @override
  String get importYoutubeHistory => 'Tuo Youtube-historia';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Siirry osoitteeseen $takeoutLink\n\n 2. Paina \"Multiple Formats\" ja valitse \"Historia\"-kohdan vierestä \"JSON\". \n\n3. Paina \"Kaikki Youtube-tiedot sisältyvät\", poista kaikkien valinta ja valitse vain historia. \n\n4. Luo Vie, lataa ja pura. \n\n5. Valitse seuraavasta näytöstä \"watch-history.json\".';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString kanavat tuotu onnistuneesti',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText soittolistan tuonti onnistuneesti',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Sisällytä videot';

  @override
  String get indexRefreshRequired => 'Tee Refresh tämän muuttamisen jälkeen';

  @override
  String get indexer => 'Indeksoija';

  @override
  String get indexerNote => 'Huomautus: Taideteosten epätäydellinen määrä viittaa monistettuihin ja ei löytyneisiin taideteoksiin';

  @override
  String get indexerSubtitle => 'Hallinnoi musiikkikirjastoasi';

  @override
  String get infinityQueueOnNextPrev => 'Infinity-jono kohdassa Seuraava/Edellinen';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'Seuraavan painaminen toistaessasi viimeistä kohdetta hyppää ensimmäiseen ja päinvastoin';

  @override
  String get info => 'Tiedot';

  @override
  String get inserted => 'lisätty';

  @override
  String get instantlyApplies => 'Sovelletaan välittömästi';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Käänteinen Valinta';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Esine';

  @override
  String get jump => 'Hyppää';

  @override
  String get jumpToDay => 'Hyppää päivään';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Hyppää ensimmäiseen kappaleeseen jonon päätyttyä';

  @override
  String get keepCachedVersions => 'Säilytä välimuistissa olevat versiot';

  @override
  String get keepFileDates => 'Säilytä tiedostojen päivämäärät';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Minisoitin on laajennettu';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Minisoitin on laajennettu ja videota toistetaan';

  @override
  String get keepScreenAwakeNone => 'Älä pidä näyttöä hereillä';

  @override
  String get keepScreenAwakeWhen => 'Pidä näyttö hereillä kun';

  @override
  String get killPlayerAfterDismissingApp => 'Tappaa pelaajan toiminta sovelluksen hylkäämisen jälkeen';

  @override
  String get language => 'Kieli';

  @override
  String get learnMore => 'Lisää tietoa';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Kirjaston välilehdet';

  @override
  String get libraryTabsReorder => 'Sinä voit järjestää aktivoitu välilehdet.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Kun';

  @override
  String get liked => 'Tykätu';

  @override
  String get link => 'Linkki';

  @override
  String get listOfFolders => 'Luettelo Kansioista';

  @override
  String get loadAll => 'Lataa kaikki';

  @override
  String get loadingFile => 'Ladataan tiedostoa';

  @override
  String get local => 'Paikallinen';

  @override
  String get localVideoMatching => 'Paikallinen videovastaavuus';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Paina sanoitusta pitkään siirtyäksesi koko näytön tilaan';

  @override
  String get lostMemories => 'Kadonneita muistoja';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'noin tähän aikaan, $numberString vuotta sitten',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Kuuluvuus Tehostaja';

  @override
  String get lyricist => 'Sanoittaja';

  @override
  String get lyrics => 'Sanat';

  @override
  String get lyricsSource => 'Sanan alkuperä';

  @override
  String get m3uPlaylist => 'M3U Soitolista';

  @override
  String get makeYourFirstListen => 'Kuuntele ensimmäistä kertaa!';

  @override
  String get manage => 'Hallitse';

  @override
  String get manageYourAccounts => 'Hallitse sun tilit';

  @override
  String get manualBackup => 'Manuaalinen';

  @override
  String get manualBackupSubtitle => 'Poimi tietty tiedosto';

  @override
  String get markAsRead => 'Merkitse lukenut';

  @override
  String get matchAllTracks => 'Vastaa Kaikki Musiikkikappaleet';

  @override
  String get matchAllTracksNote => 'tämä voi vaikuttaa hakunopeuteen, koska se tarkistaa kaikki kokoelmasi kappaleet';

  @override
  String get matchingType => 'Vastaava tyyppi';

  @override
  String get maxAudioCacheSize => 'Äänivälimuistin Enimmäiskoko';

  @override
  String get maxImageCacheSize => 'Kuvavälimuistin Enimmäiskoko';

  @override
  String get maxVideoCacheSize => 'Videovälimuistin Enimmäiskoko';

  @override
  String get maximum => 'Maksimi';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media säilytys on päällä, tällä ei tule olemaan vaikutusta';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Koodi';

  @override
  String get membershipCodeSentToEmail => 'Koodi lähetetty sun sähköpostiin';

  @override
  String get membershipDidntChange => 'Jäsenyys ei vaihtonut';

  @override
  String get membershipEnjoyNew => 'Toivottavasti pidät uudesta jäsenyydestäsi :)';

  @override
  String get membershipFreeCoupon => 'Ilmainen kuponki';

  @override
  String get membershipManage => 'Hallinnoi Jäsenyyttäsi';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Tilauksia ei löytynyt tama käyttäjälle';

  @override
  String get membershipSignInToPatreonAccount => 'Kirjaudu sisään patreon-tilillesi';

  @override
  String get membershipUnknown => 'Jäsentaso Epävarma';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Tarvitset jäsenyyden $name1 tai $name2 Etta voit käyttää moninkertainen tilliä';
  }

  @override
  String get merge => 'Yhdistä';

  @override
  String get metadataCache => 'Metadata Välimuisti';

  @override
  String get metadataEditFailed => 'Metatietojen välimuistin muokkaaminen epäonnistui';

  @override
  String get metadataReadFailed => 'Metatietojen lukeminen epäonnistui';

  @override
  String get minFileDuration => 'Raidan vähimmäiskesto';

  @override
  String get minFileSize => 'Minimi tiedostokoko';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Raidan vähimmäiskesto viimeksi toistetun sijainnin palauttamiseksi';

  @override
  String get minValueCantBeMoreThanMax => 'Minimiarvo ei voi olla suurempi kuin enimmäisarvo';

  @override
  String get minValueToCountTrackListen => 'Laske kuuntelu jälkeen: ';

  @override
  String get minimizedMiniplayer => 'Minimoitu minisoitin';

  @override
  String get minimum => 'Minimum';

  @override
  String get minimumOneFolderSubtitle => 'Pitäisi olla vähintään yksi. Lisää kansioita, jos haluat poistaa tämän';

  @override
  String get minimumOneItem => 'Ei voinut poista kohde';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Vähintään $numberString kohdetta pitäisi olla jäljellä',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Minisoittimen mukauttaminen';

  @override
  String get minutes => 'minuuttia';

  @override
  String get missingEntries => 'Puuttuvat merkinnät';

  @override
  String get missingTracks => 'Puuttuvat kappaleet';

  @override
  String get mix => 'sekoita';

  @override
  String get mixPlaylistGeneratedByYoutube => 'YouTuben tuottama sekoitussoittolista';

  @override
  String get mixes => 'sekoitus';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Kuukausi';

  @override
  String get months => 'Kuukausia';

  @override
  String get mood => 'Tunne';

  @override
  String get moods => 'Tunnelmat';

  @override
  String get more => 'Lisaa';

  @override
  String get mostPlayed => 'Eniten pelatut';

  @override
  String get multipleTracksTagsEditNote => 'Olet muokkaamassa näitä kappaleita,\n Muuttumattomat kentät säilyvät ennallaan.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Nimi';

  @override
  String get nameContainsBadCharacter => 'Nimissä on paha Merkki';

  @override
  String get never => 'Ei koskaan';

  @override
  String get newDirectory => 'Uusi hakemisto';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Lisää kappaleita';

  @override
  String get newTracksMoods => 'Tunne';

  @override
  String get newTracksMoodsSubtitle => 'Luo kappaleita käytettävissä olevien tunteiden perusteella';

  @override
  String get newTracksRandom => 'Satunnainen';

  @override
  String get newTracksRandomSubtitle => 'Poimi satunnaisia kappaleita kirjastostasi';

  @override
  String get newTracksRatings => 'Suosio';

  @override
  String get newTracksRatingsSubtitle => 'Luo kappaleita, joilla on tietty luokitus';

  @override
  String get newTracksRecommended => 'Suositella';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Luo kappaleita, joita kuuntelit tavallisesti kappaleella $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Samanlainen julkaisupäivä';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Luo kappaleita, jotka julkaistiin suunnilleen samaan aikaan kuin $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Kappaleen vuosiluku on tuntematon';

  @override
  String get newest => 'Uusin';

  @override
  String get next => 'Ensin';

  @override
  String get no => 'Ei';

  @override
  String get noChangesFound => 'Muutoksia ei löytynyt.';

  @override
  String get noEnoughTracks => 'Sinulla ei ole paljon säikeitä...';

  @override
  String get noExcludedFolders => 'Sinulla ei ole poissuljettuja kansioita';

  @override
  String get noFolderChosen => 'Et ole valinnut yhtään kansiota';

  @override
  String get noMoodsAvailable => 'Tunnelmia ei ole saatavilla';

  @override
  String get noNetworkAvailableToFetchData => 'Tietojen noutamiseen ei ole käytettävissä verkkoa';

  @override
  String get noTracksFound => 'Säikeitä ei löytynyt';

  @override
  String get noTracksFoundBetweenDates => 'Tällä aikavälillä ei ole yhtään säiettä.';

  @override
  String get noTracksFoundInDirectory => 'Tästä hakemistosta ei löytynyt säikeitä';

  @override
  String get noTracksInHistory => 'Sinulla ei ole tarpeeksi säikeitä historiassa';

  @override
  String get nonActive => 'Ei-aktiivinen';

  @override
  String get nonFavourites => 'Ei-suosikit';

  @override
  String get none => 'Ei mitään';

  @override
  String get normalizeAudio => 'Normalisoi ääni';

  @override
  String get normalizeAudioSubtitle => 'Normalisoi äänenvoimakkuuden lukemalla toiston vahvistustunnisteen tai youtuben antaman infon mukaan';

  @override
  String get notAvailableForYourDevice => 'Ei saatavilla laitteellasi';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'Huomautus';

  @override
  String get notification => 'Tiedote';

  @override
  String get notifications => 'Tiedotteet';

  @override
  String get numberOfTracks => 'Säikeiden lukumäärä';

  @override
  String get ofLabel => 'josta';

  @override
  String get offlineSearch => 'Ei-verkkohaku';

  @override
  String get offset => 'Ylityksen määrä';

  @override
  String get oldDirectory => 'Vanha hakemisto';

  @override
  String get oldDirectoryStillHasTracks => 'Vanhassa hakemistossa on vielä joitain säikeitä; vahvistetaanko?';

  @override
  String get oldestWatch => 'Vanhin Kello';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Keskeytyksestä';

  @override
  String get onNotificationTap => 'Ilmoitusta Painaessa';

  @override
  String get onOpeningYoutubeLink => 'Youtube linkin avaamisen yhteydessä';

  @override
  String get onSwiping => 'Pyyhkäistessä';

  @override
  String get onVolumeZero => 'Äänenvoimakkuuden ollessa 0';

  @override
  String get ongoing => 'Meneillään';

  @override
  String get open => 'Avaa';

  @override
  String get openApp => 'Avaa sovellus';

  @override
  String get openInFileExplorer => 'Avaa tiedostoissa';

  @override
  String get openInYoutubeView => 'Avaa Youtube-näkymässä';

  @override
  String get openMiniplayer => 'Avaa Miniplayer';

  @override
  String get openQueue => 'Avaa jono';

  @override
  String get openYoutubeLink => 'Avaa Youtube-linkki';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Toiminto $name vaatii tilin. Jatka kirjautumalla sisään';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Toiminto $operation edellyttää vähintään jäsenyyttä $name';
  }

  @override
  String get or => 'tai';

  @override
  String get others => 'Muut';

  @override
  String get output => 'Lähtö';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Korvaa vanhat tiedostot samassa kansiossa';

  @override
  String get palette => 'Paletti';

  @override
  String get paletteMix => 'Seos';

  @override
  String get paletteNewMix => 'Uusi seos';

  @override
  String get paletteSelectedMix => 'Valittu seos';

  @override
  String get parallelDownloads => 'Rinnakkaiset lataukset';

  @override
  String get parsed => 'jäsennetty';

  @override
  String get password => 'Password';

  @override
  String get path => 'Tiedoston koko polku';

  @override
  String get pause => 'Keskeytä';

  @override
  String get pauseFadeDuration => 'Keskeytyksen häivytyksen kesto';

  @override
  String get pausePlayback => 'Keskeytä toisto';

  @override
  String get percentage => 'Prosenttiosuus';

  @override
  String get performanceMode => 'Suorituskykytila';

  @override
  String get performanceNote => 'Saattaa vaikuttaa suorituskykyyn';

  @override
  String get personalized => 'Henkilökohtaiseksi saatu';

  @override
  String get personalizedRelatedVideos => 'Personalisoidut samankaltaiset videot';

  @override
  String get personalizedRelatedVideosSubtitle => 'Tämän poistaminen käytöstä lisää tiedonsiirtoa';

  @override
  String get pickColorsFromDeviceWallpaper => 'Valitse värit laitteen taustakuvasta';

  @override
  String get pickFromStorage => 'Valitse tallennustilasta';

  @override
  String get pinned => 'Kiinnitetty';

  @override
  String get pitch => 'Piki';

  @override
  String get plain => 'Pelkkä';

  @override
  String get play => 'Toista';

  @override
  String get playAfter => 'Toista sen jälkeen';

  @override
  String get playAfterNextPrev => 'Automaattinen toisto Seuraavasta/Edellisestä';

  @override
  String get playAll => 'Toista kaikki';

  @override
  String get playFadeDuration => 'Toiston häivytyksen kesto';

  @override
  String get playLast => 'Toista viimeinen';

  @override
  String get playNext => 'Toista seuraava';

  @override
  String get playbackSetting => 'Toisto';

  @override
  String get playbackSettingSubtitle => 'Pääsee suoraan soittimesta painamalla audiopainiketta pitkään';

  @override
  String get playlist => 'Soittolista';

  @override
  String get playlists => 'Soittolistat';

  @override
  String get playlistsImportM3uNative => 'Tämä tuo M3U-soittolistoja vain namidan käyttöön. käytä, jos olet siirtymässä';

  @override
  String get playlistsImportM3uSynced =>
      'Tämä tuo automaattisesti M3U-soittolistat indeksointikansioista ja pitää ne synkronoituna alkuperäisen M3U-tiedoston kanssa. ota käyttöön, jos käytät tai muokkaat soittolistoja muista sovelluksista';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Tuo M3U-soittolistat automaattisesti';

  @override
  String get pleaseEnterADifferentName => 'Tämä nimi on jo olemassa :(\nkokeile toista mielikuvituksellista nimeä';

  @override
  String get pleaseEnterALink => 'Syötä linkki';

  @override
  String get pleaseEnterALinkSubtitle => 'hmm,. onko tämä youtube-linkki?';

  @override
  String get pleaseEnterAName => 'Syötä nimi';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Estä päällekkäiset säikeet';

  @override
  String get preventDuplicatedTracksSubtitle => 'Käyttää tiedoston nimeä säikeiden yksilölliseen tunnistamiseen';

  @override
  String get preview => 'Esikatselu';

  @override
  String get previous => 'Edellinen';

  @override
  String get previousButtonReplays => 'Edellisten painikkeiden toistot';

  @override
  String get previousButtonReplaysSubtitle => 'jos painetaan, kun nykyinen sijainti oli pidempi kuin haun kesto';

  @override
  String get prioritizeEmbeddedLyrics => 'Aseta upotetut sanoitukset ensisijaisiksi';

  @override
  String get priority => 'Ensisijaisuus';

  @override
  String get private => 'Yksityinen';

  @override
  String get progress => 'Edistyminen';

  @override
  String get promptToChangeTrackPath => 'Yleensä näin tapahtuu, kun poistat/siirrät/nimeät uudelleen tiedoston namidan ulkopuolelle. Haluatko päivittää nykyisen polun?';

  @override
  String get public => 'Julkinen';

  @override
  String get queue => 'Jono';

  @override
  String get queues => 'Jonot';

  @override
  String get random => 'Satunnainen';

  @override
  String get randomPicks => 'Satunnaiset valinnat';

  @override
  String get rating => 'Luokitus';

  @override
  String get reIndex => 'Uudelleen indexoi';

  @override
  String get reIndexSubtitle => 'Uudelleen rakenna musiikki kirjastosi alusta asti';

  @override
  String get reIndexWarning => 'Tämä prosessi voi viedä hetken, riippuen kirjastosi koosta\n\nTeoksia ei uudelleen indexoida niin kauan kuin ne ovat vielä olemassa';

  @override
  String get recentAlbums => 'Viimeaikaiset albumit';

  @override
  String get recentArtists => 'Viimeaikaiset taiteilijat';

  @override
  String get recentListens => 'Viimeaikaiset kuuntelut';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Äskettäin lisätty';

  @override
  String get recordLabel => 'Levy-yhtiö';

  @override
  String get refresh => 'Virkistä';

  @override
  String get refreshLibrary => 'Virkistä kirjasto';

  @override
  String get refreshLibrarySubtitle => 'Tarkista äskettäin lisätyn tai poistetun musiikin varalta';

  @override
  String get refreshOnStartup => 'Virkistä käynnistyksen yhteydessä';

  @override
  String get relatedVideos => 'Aiheeseen liittyvät videot';

  @override
  String get rememberAudioOnlyMode => 'Muista vain ääni -tila';

  @override
  String get remixer => 'Uudelleensekoitin';

  @override
  String get remove => 'Poista';

  @override
  String get removeDuplicates => 'Poista kaksoiskappaleet';

  @override
  String get removeFromFavourites => 'Poista suosikeista';

  @override
  String get removeFromLibrary => 'Poista kirjastosta';

  @override
  String get removeFromPlaylist => 'Poista soittolistasta';

  @override
  String get removeQueue => 'Poista jono';

  @override
  String get removeSourceFromHistory => 'Poista lähde historiasta';

  @override
  String get removeWhitespaces => 'Poista välilyönnit';

  @override
  String get removed => 'Poistettu';

  @override
  String get rename => 'Nimeä uudelleen';

  @override
  String get renamePlaylist => 'Nimeä soittolista uudelleen';

  @override
  String get reorderable => 'Uudelleen järjestettävissä';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Toista vielä $number kertaa',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Uudelleentoisto moodi';

  @override
  String get repeatModeAll => 'Toista kaikki jonossa';

  @override
  String get repeatModeNone => 'Pysähdy viimeisellä kappaleella';

  @override
  String get repeatModeOne => 'Toista nykyinen kappale';

  @override
  String get replaceAllListensWithAnotherTrack => 'Korvaa kaikki kuuntelut toisella kappaleella';

  @override
  String get replies => 'Vastaukset';

  @override
  String get reply => 'Vastaa';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Edellyttää kuvavälimuistin tyhjentämistä ja uudelleen indeksointia';

  @override
  String get rescanVideos => 'Skannaa videot uudelleen';

  @override
  String get resetBrightness => 'Palauta kirkkaus';

  @override
  String get resetToDefault => 'Aseta';

  @override
  String get respectNoMedia => 'Kunnioita .nomediaa';

  @override
  String get respectNoMediaSubtitle => 'Älä sisällytä kansioita, joissa on .nomedia';

  @override
  String get restart => 'Käynnistä uudelleen';

  @override
  String get restoreBackup => 'Palauta varmuuskopio';

  @override
  String get restoreDefaults => 'Palauta oletukset';

  @override
  String get restoredBackupSuccessfully => 'Palautettu varmuuskopio';

  @override
  String get restoredBackupSuccessfullySub => 'Varmuuskopiotiedosto palautettiin onnistuneesti';

  @override
  String get resume => 'Jatka';

  @override
  String get resumeIfWasInterrupted => 'Jatka, jos se keskeytettiin keskeytyksen vuoksi';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Jatka toistoa jos toisto pysäytettiin äänenvoimakkuudella';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Jatka toistoa, jos toisto pysäytettiin alle $numberString minuutiksi',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Käänteinen Järjestys';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Soittoääni';

  @override
  String get sameDirectoryOnly => 'Vain samassa tiedosto osoitteessa';

  @override
  String get sample => 'Esimerkki';

  @override
  String get sampleRate => 'Näyteiden määrä';

  @override
  String get save => 'Tallenna';

  @override
  String get saveToLibrary => 'Tallenna kirjastoon';

  @override
  String get savedIn => 'Tallennettu';

  @override
  String get scaleMultiplier => 'Skaalauksen kerroin';

  @override
  String get search => 'Haku';

  @override
  String get searchYoutube => 'Hae YouTubesta';

  @override
  String get seconds => 'Sekunteja';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Seek Duration';

  @override
  String get seekDurationInfo => 'Voit painaa nykyisestä kestosta kelataksesi taaksepäin & kokonaiskestosta kelataksesi eteenpäin';

  @override
  String get seekbar => 'Aikajana';

  @override
  String get selectAll => 'Valitse Kaikki';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Valtise jo paikallisesti olemassa olevat tiedostot';

  @override
  String get selectedTracks => 'Valitut Kappaleet';

  @override
  String get selfPromotion => 'Itse-promootio';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Näitä sanoja ei tulla halkaisemaan';

  @override
  String get separatorsMessage => 'Ei tarvetta käyttää välilyöntiä, ellet halua käyttää kirjainta/symbolia joka voidaan löytää koko sanassa (kuten x ja ft.)';

  @override
  String get serverAddress => 'Palvelimen osoite';

  @override
  String get setAs => 'Asetettuna';

  @override
  String get setAsDefault => 'Asetettuna oletusarvoon';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Aseta tiedoston viimeisin muokkauspäivä videon latauspäiväksi';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Aseta tunnelmat';

  @override
  String get setMoodsSubtitle => 'Käytä pilkkuja (,) erottaaksesi niiden välillä';

  @override
  String get setRating => 'Aseta arvostelu';

  @override
  String get setTags => 'Aseta tunnisteet';

  @override
  String get setYoutubeLink => 'Aseta Youtube linkki';

  @override
  String get settings => 'Asetukset';

  @override
  String get setupFirstStartup => 'Ensikerran aloitus asetukset';

  @override
  String get share => 'Jaa';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Lyhenteet';

  @override
  String get shouldDuck => 'Should duck';

  @override
  String get shouldDuckNote => 'Ilmaisee että äänenvoimakkuutta pitäisi alentaa. Esim. Ilmoitus';

  @override
  String get shouldPause => 'Pitäisi pysäyttää';

  @override
  String get shouldPauseNote => 'Ilmaisee että toisto pitäisi pysäyttää. Esim. Puhelut';

  @override
  String get showAll => 'Näytä Kaikki';

  @override
  String get showChannelWatermarkInFullscreen => 'Näytä kanavan vesileima kokonäytön tilassa';

  @override
  String get showFailedOnly => 'Näytä vain epäonnistuneet';

  @override
  String get showHideUnknownFields => 'Näytä/piilota tietämätömät tiedot/kentät';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Näytä sekoitukset';

  @override
  String get showMore => 'Näytä lisää';

  @override
  String get showShortVideosIn => 'Näytä lyhytvideoita';

  @override
  String get showSkipButton => 'Näytä ohitus nappi';

  @override
  String get showVideoEndcards => 'Näytä videon loppukortit/lopetusnäyttö';

  @override
  String get showWebm => 'Näytä webm';

  @override
  String get shuffle => 'Sekoitus';

  @override
  String get shuffleAll => 'Sekoita kaikki';

  @override
  String get shuffleNext => 'Sekoita seuraava';

  @override
  String get signIn => 'Kirjaudu sisään';

  @override
  String get signInCanceled => 'Kirjautuminen peruutettiin';

  @override
  String get signInFailed => 'Kirjautuminen on epäonnistunut';

  @override
  String get signInToYourAccount => 'Kirjaudu sisään käyttäjätilillesi';

  @override
  String get signInYouDontHaveAccount => 'Sinulla ei ole yhtään kirjautunutta käyttäjää';

  @override
  String get signInYouNeedAccountToViewPage => 'Tarvitset käyttäjätilin nähdäksesi tämän sivun';

  @override
  String get signOut => 'Kirjaudu ulos';

  @override
  String signOutFromName({required String name}) {
    return 'Kirjaudu ulos käyttäjältä $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Sisään kirjautumalla saat perustason käytön';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Hanki aikainen pääsy patreonin kautta tai käyttämällä kuponki';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Similar Time Range';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generate tracks you listened to around the same time as $currentTrack';
  }

  @override
  String get singles => 'Singlet';

  @override
  String get size => 'Koko';

  @override
  String get skip => 'Ohita';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Ohita hiljaisuus';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Mene unitilaan tämän jälkeen';

  @override
  String get sleepTimer => 'Unitilan ajastin';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Järjestä... Mukaan';

  @override
  String get source => 'Lähde';

  @override
  String get speed => 'Nopeus';

  @override
  String get sponsor => 'Sponsori';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Staggered Album Gridview';

  @override
  String get start => 'Aloita';

  @override
  String get stats => 'Tilastot';

  @override
  String get statsSubtitle => 'Tässä on tietoa kirjastostasi';

  @override
  String get stop => 'Pysäytä';

  @override
  String get stopAfterThisTrack => 'Pysäytä tämän kappaleen jälkeen';

  @override
  String get stopAfterThisVideo => 'Pysäytä tämän videon jälkeen';

  @override
  String get storagePermissionDenied => 'Lupa kielletty';

  @override
  String get storagePermissionDeniedSubtitle => 'Ole hyvä ja anna lupa tähän toimintaan';

  @override
  String get stretchLyricsDuration => 'Venytä sanoituksien kestoa';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Tilaa';

  @override
  String get subscribed => 'Tilattu';

  @override
  String get subscriber => 'Tilaaja';

  @override
  String get subscribers => 'Tilaajat';

  @override
  String get succeeded => 'Onnistua';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Tuki';

  @override
  String get supremacy => 'Supremacy';

  @override
  String get sussyBaka => 'Bro ei kappaleita';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Kelaa avataksesi vetolaatikko';

  @override
  String get synced => 'Synkattu';

  @override
  String get synopsis => 'Yleiskatsaus';

  @override
  String get tagFields => 'Tunniste kentät';

  @override
  String get tags => 'Tunnisteet';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Paina kelataksesi';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Teema moodi';

  @override
  String get themeModeDark => 'Tumma';

  @override
  String get themeModeLight => 'Vaalea';

  @override
  String get themeModeSystem => 'Systeemi';

  @override
  String get themeSettings => 'Teema';

  @override
  String get themeSettingsSubtitle => 'Soittimesi tunnelma';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering =>
      'Tässä soittolistassa on aktiivisia järjestäjiä, ole hyvä ja poista ne käytöstä ennen uudelleen järjestelyä';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Tämä video on todennäköisesti poistettu tai muokattu yksityiseksi';

  @override
  String get thumbnails => 'Thumbnails';

  @override
  String get title => 'Otsikko';

  @override
  String get top => 'Ylä';

  @override
  String get topComments => 'Ylä kommenttit';

  @override
  String get topCommentsSubtitle => 'Näytä kommentit ylhäällä, alhaan sijasta';

  @override
  String get topRecentAlbums => 'Top Recent Albums';

  @override
  String get topRecentArtists => 'Top Recent Artists';

  @override
  String get topRecents => 'Top Recents';

  @override
  String get totalListenTime => 'Kokonaiskuuntelu aika';

  @override
  String get totalListens => 'Kokonaiskuuntelut';

  @override
  String get totalTracks => 'Total Tracks';

  @override
  String get totalTracksDuration => 'Total Tracks Duration';

  @override
  String get track => 'Kappale';

  @override
  String get trackArtistsSeparator => 'Artistien erittäjä';

  @override
  String get trackGenresSeparator => 'Genrejen erittäjä';

  @override
  String get trackInfo => 'Kappale Info';

  @override
  String get trackNotFound => 'Kappaletta ei löytynyt';

  @override
  String get trackNumber => 'Kappale numero';

  @override
  String get trackNumberTotal => 'Track Total';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Old name: \"$oldName\"\n\nNew name: \"$newName\"\n\nAre you sure?';
  }

  @override
  String get trackPlayMode => 'Toiston moodi';

  @override
  String get trackPlayModeSearchResults => 'Hakutulokset';

  @override
  String get trackPlayModeSelectedOnly => 'Vain valittua kappaletta';

  @override
  String get trackPlayModeTrackAlbum => 'Kappaleen albumi';

  @override
  String get trackPlayModeTrackArtist => 'Kappaleen pääartisti';

  @override
  String get trackPlayModeTrackGenre => 'Kappaleen genre';

  @override
  String get trackThumbnailSizeInList => 'Size of Track Thumbnail';

  @override
  String get trackTileCustomization => 'Track Tile Customization';

  @override
  String get trackTileItemsSeparator => 'Items Separator';

  @override
  String get tracks => 'Kappaleet';

  @override
  String get tracksExcludedByNomedia => 'Tracks Excluded by .nomedia';

  @override
  String get tracksInfo => 'Kappaleiden Info';

  @override
  String get underrated => 'Aliarvostettu';

  @override
  String get undo => 'Peru';

  @override
  String get undoChanges => 'Peru muutokset?';

  @override
  String get undoChangesDeletedPlaylist => 'Peru soittolistan poisto';

  @override
  String get undoChangesDeletedQueue => 'Peru poistettu jono';

  @override
  String get undoChangesDeletedTrack => 'Peru poistettu kappale';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Rajoittamaton';

  @override
  String get unlisted => 'Listaamaton';

  @override
  String get unlock => 'Avata';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Päivittää';

  @override
  String get updateDirectoryPath => 'Päivitä tiedosto sijantia';

  @override
  String get updateMissingTracksOnly => 'Päivitä vain puuttuvat kappaleet';

  @override
  String get updating => 'Päivitetään';

  @override
  String get useCollapsedSettingTiles => 'Use Collapsed Setting Tiles';

  @override
  String get useMediaStore => 'Käytä median varastointia';

  @override
  String get useMediaStoreSubtitle =>
      '✓ instant indexing time\nx respect .nomedia will be forcely enabled\nx some metadata tags will be missing\nx youtube integration for local library will not work';

  @override
  String get usePitchBlack => 'Käytä piki mustaa';

  @override
  String get usePitchBlackSubtitle => 'Hyödynnöllinen AMOLED näytöille.. ja näytää Hienomalle';

  @override
  String get used => 'Käytetty';

  @override
  String get value => 'Arvo';

  @override
  String get valueBetween50200 => 'Arvon pitäisi olla 50% ja 200% välillä';

  @override
  String get vibration => 'Tärinä';

  @override
  String get vibrationType => 'Tärinän tyyppi';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Video Cache';

  @override
  String get videoCacheFile => 'Cached Video File';

  @override
  String get videoCacheFiles => 'Cached Video Files';

  @override
  String get videoOnly => 'Vain video';

  @override
  String get videoPlaybackSource => 'Video lähde';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Antaa prioriteetin paikallisille videoille, jos ei löydy, hakee youtubesta';

  @override
  String get videoPlaybackSourceLocal => 'Paikalliset videot';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Checks if any video file (found inside the chosen folders list) has a filename that contains the filename of the track';

  @override
  String get videoPlaybackSourceYoutube => 'Youtubesta';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Checks in track\'s filename & comment for any matching youtube link, videos are cached for later use.';

  @override
  String get videoQuality => 'Video laatu';

  @override
  String get videoQualitySubtitle => 'Ottaa parhaan saatavilla olevan laadun';

  @override
  String get videoQualitySubtitleNote => 'It\'s always good to keep more alternatives in case a quality isn\'t found, otherwise it will fallback to the worst quality';

  @override
  String get videos => 'Videoita';

  @override
  String get view => 'Näytä';

  @override
  String get viewAll => 'Näytä Kaikki';

  @override
  String get views => 'Näyttökerrat';

  @override
  String get volume => 'Äänenvoimakkuus';

  @override
  String get warning => 'Varoitus';

  @override
  String get waveformBarsCount => 'Aallonmuodon palkkien määrä';

  @override
  String get webmNoEditTagsSupport => 'WEBM formaatti ei tue nimikkeiden muokkausta';

  @override
  String get week => 'Viikko';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Vuosi';

  @override
  String get yes => 'Kyllä';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Tämänhetkinen jäsenyytesi on $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Your custom order will be lost, Are you sure?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube musiikki';

  @override
  String get youtubeSettingsSubtitle => 'Kustomisoi Youtube käyttökokemusta';

  @override
  String get youtubeStyleMiniplayer => 'Youtube tyylinen Mini-soitin';

  @override
  String get ytPreferNewComments => 'Suosi uusia kommentteja kun mahdollista';

  @override
  String get ytPreferNewCommentsSubtitle => 'Cached version will only be used when there is no connection';
}
