// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Arabic (`ar`).
class AppLocalizationsAr extends AppLocalizations {
  AppLocalizationsAr([String locale = 'ar']) : super(locale);

  @override
  String get about => 'عن';

  @override
  String get active => 'نشط';

  @override
  String get add => 'اضافة';

  @override
  String get addAccount => 'إضافة حساب';

  @override
  String get addAll => 'أضف الكل';

  @override
  String get addAllAndRemoveOldOnes => 'أضف الكل وأحذف القديم';

  @override
  String get addAsANewPlaylist => 'أضف كقائمة تشغيل جديدة';

  @override
  String get addAudioToLocalLibrary => 'إضافة الصوت إلى المكتبة المحلية';

  @override
  String get addFolder => 'إضافة مجلد';

  @override
  String get addLanguage => 'إضافة لغة';

  @override
  String get addLanguageSubtitle => 'ساعد في ترجمة ناميدا إلى لغتك';

  @override
  String get addLrcFile => 'إضافة ملف LRC';

  @override
  String get addMoreFromThisAlbum => 'أضف المزيد من هذا الألبوم إلى قائمة الانتظار';

  @override
  String get addMoreFromThisArtist => 'أضف المزيد من هذا الفنان إلى قائمة الانتظار';

  @override
  String get addMoreFromThisFolder => 'أضف المزيد من هذا المجلد إلى قائمة الانتظار';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'أضف المزيد من $media إلى قائمة الانتظار';
  }

  @override
  String get addOnlyMissing => 'أضف المفقودة فقط';

  @override
  String get addToFavourites => 'أضف إلى المفضلة';

  @override
  String get addToPlaylist => 'أضف إلى قائمة التشغيل';

  @override
  String get addTracksAtTheBeginning => 'إضافة مسارات في البداية';

  @override
  String get added => 'مضاف';

  @override
  String get advanced => 'متقدم';

  @override
  String get advancedSettings => 'متقدمة';

  @override
  String get advancedSettingsSubtitle => 'الإعدادات المتقدمة، لا تلمس';

  @override
  String get alarm => 'منبه';

  @override
  String get album => 'الألبوم';

  @override
  String get albumArtist => 'ألبوم الفنان';

  @override
  String get albumArtists => 'ألبوم الفنانين';

  @override
  String get albumIdentifiers => 'معرفات الألبوم';

  @override
  String get albumThumbnailSizeInList => 'حجم الصورة المصغرة للألبوم';

  @override
  String get albumTileCustomization => 'تخصيص بلاط الألبوم';

  @override
  String get albums => 'الألبومات';

  @override
  String get albumsCount => 'عدد الألبومات';

  @override
  String get all => 'الكل';

  @override
  String get allTime => 'كل الأوقات';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'دائمًا';

  @override
  String get alwaysAsk => 'اسأل دائمًا';

  @override
  String get alwaysDim => 'خافت دائما';

  @override
  String get alwaysExpandedSearchbar => 'توسيع شريط البحث دائما';

  @override
  String get alwaysRestore => 'استعادة دائما';

  @override
  String get animatingThumbnailIntensity => 'قوة حركة الصورة المصغرة';

  @override
  String get animatingThumbnailInversed => 'عكس التأثيرات الحركية';

  @override
  String get animatingThumbnailInversedSubtitle => 'ستؤدي القمم العالية إلى تصغير حجم الصورة المصغرة';

  @override
  String get anotherProcessIsRunning => 'هناك عملية أخرى قيد التشغيل بالفعل.';

  @override
  String get appIcon => 'ايقونة التطبيق';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'الفنان';

  @override
  String get artists => 'الفنانون';

  @override
  String get artwork => 'العمل الفني';

  @override
  String get artworkGestures => 'إيماءات العمل الفني';

  @override
  String get artworks => 'الأعمال الفنية';

  @override
  String get audio => 'الصوت';

  @override
  String get audioCache => 'ذاكرة التخزين المؤقت الصوتية';

  @override
  String get audioOnly => 'الصوت فقط';

  @override
  String get auto => 'تلقائي';

  @override
  String get autoBackupInterval => 'الفاصل الزمني للنسخ الاحتياطي التلقائي';

  @override
  String get autoColoring => 'التلوين التلقائي';

  @override
  String get autoColoringSubtitle => 'اختيار ألوان المشغل تلقائيًا من العمل الفني الحالي';

  @override
  String get autoExtractTagsFromFilename => 'استخراج تلقائي من اسم الملف';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'استخراج العنوان والفنان تلقائيًا من عنوان الفيديو';

  @override
  String get autoGenerated => 'إنشاء تلقائي';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'تشغيل تلقائي لليوتيوب';

  @override
  String get autoStartRadioSubtitle => 'يضيف قائمة تشغيل مختلطة تلقائيًا عند تشغيل مقطع واحد';

  @override
  String get automaticBackup => 'تلقائي';

  @override
  String get automaticBackupSubtitle => 'يُطبِّق تلقائيًا أحدث ملف نسخ احتياطي موجود داخل موقع النسخ الاحتياطي.';

  @override
  String get backupAndRestore => 'النسخ الاحتياطي والاستعادة';

  @override
  String get backupAndRestoreSubtitle => 'النسخ الاحتياطي لقاعدة البيانات والإعدادات الخاصة بك';

  @override
  String get balanced => 'متوازن';

  @override
  String get beta => 'تجريبي';

  @override
  String get betweenDates => 'بين التواريخ';

  @override
  String get bitrate => 'معدل البتّ';

  @override
  String get blacklist => 'القائمة السوداء';

  @override
  String get borderRadiusMultiplier => 'مضاعف نصف قطر الحدود';

  @override
  String get cache => 'التخزين المؤقت';

  @override
  String get cancel => 'إلغاﺀ';

  @override
  String get canceled => 'ملغي';

  @override
  String get changed => 'تم تغييره';

  @override
  String get changelog => 'سجل التغيير';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'القناة';

  @override
  String get channels => 'القنوات';

  @override
  String get check => 'تحقق';

  @override
  String get checkForMore => 'تحقق من المزيد';

  @override
  String get checkList => 'قائمة التحقق';

  @override
  String get choose => 'أختر';

  @override
  String get chooseWhatToClear => 'اختر ما تريد مسحه';

  @override
  String get claim => 'مطالبة';

  @override
  String get clear => 'مسح';

  @override
  String get clearAudioCache => 'امسح ذاكرة التخزين المؤقت الصوتية';

  @override
  String get clearImageCache => 'مسح ذاكرة التخزين المؤقت للصور';

  @override
  String get clearImageCacheWarning => 'تحذير: سيؤدي إلى مكتبة بدون صور، استخدمها فقط لإعادة بناء ذاكرة التخزين المؤقت للصور.';

  @override
  String get clearTrackItem => 'مسح المقاطع';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'مسح $numberString من المقاطع',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'مسح ذاكرة التخزين المؤقت للفيديو';

  @override
  String get clearVideoCacheNote => 'يمكنك اختيار ما تريد حذفه.';

  @override
  String get clock => 'الساعة';

  @override
  String get colorPalette => 'لوحة الألوان';

  @override
  String get colorPaletteNote1 => 'اضغط ضغطة مطولة على اللون لإزالته';

  @override
  String get colorPaletteNote2 => 'اضغط على مزيج لاستخدامه كلون افتراضي';

  @override
  String get colorPalettes => 'لوحات الألوان';

  @override
  String get comment => 'تعليق';

  @override
  String get comments => 'تعليقات';

  @override
  String get composer => 'ملحن';

  @override
  String get compress => 'الضغط';

  @override
  String get compressImages => 'ضغط الصور';

  @override
  String get compressionPercentage => 'نسبة الضغط';

  @override
  String get configure => 'تكوين';

  @override
  String get confirm => 'تأكيد';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'العمل الفني الذي تم نسخه';

  @override
  String get copiedToClipboard => 'تم النسخ إلى الحافظة';

  @override
  String get copy => 'نسخ';

  @override
  String get corruptedFile => 'تعذر تحليل الملف، ربما يكون تالفًا';

  @override
  String get couldntOpen => 'لا يمكن فتح :(';

  @override
  String get couldntOpenYtLink => 'لا يوجد رابط يوتيوب متاح لهذا المقطع';

  @override
  String get couldntPlayFile => 'تعذر تشغيل الملف';

  @override
  String get couldntRenamePlaylist => 'تعذرت إعادة تسمية قائمة التشغيل';

  @override
  String get couldntSaveImage => 'تعذر حفظ الصورة';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'البلد';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'إنشاﺀ';

  @override
  String get createBackup => 'إنشاء نسخة احتياطية';

  @override
  String get createNewPlaylist => 'إنشاء قائمة تشغيل جديدة';

  @override
  String get createdBackupSuccessfully => 'تم إنشاء نسخة احتياطية';

  @override
  String get createdBackupSuccessfullySub => 'تم إنشاء ملف النسخ الاحتياطي بنجاح';

  @override
  String get crossPlatformSync => 'مزامنة بين المنصات';

  @override
  String get crossfadeDuration => 'مدة التلاشي';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'قم بتشغيل تأثير التلاشي المتقاطع تلقائيًا خلال $secondsString ثانية',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'لا تقم بتشغيل التلاشي المتقاطع تلقائيًا';

  @override
  String get custom => 'مخصّص';

  @override
  String get customizations => 'تخصيصات';

  @override
  String get customizationsSubtitle => 'قم بتخصيص الشكل الذي يبدو عليه المشغل، اجعله خاصًا بك';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'قاعدة البيانات';

  @override
  String get date => 'التاريخ';

  @override
  String get dateAdded => 'تاريخ الاضافة';

  @override
  String get dateCreated => 'تاريخ الإنشاء';

  @override
  String get dateModified => 'تاريخ التعديل';

  @override
  String get dateTimeFormat => 'تنسيق التاريخ والوقت';

  @override
  String get day => 'يوم';

  @override
  String get days => 'ايام';

  @override
  String get defaultBackupLocation => 'موقع النسخ الاحتياطي الافتراضي';

  @override
  String get defaultColor => 'اللون الافتراضي';

  @override
  String get defaultColorSubtitle => 'قم بتعيين اللون الذي سيستخدمه المشغل';

  @override
  String get defaultDownloadLocation => 'موقع التنزيل الافتراضي';

  @override
  String get defaultLabel => 'الإفتراضي';

  @override
  String get defaultLibraryTab => 'تبويب المكتبة الافتراضي';

  @override
  String get delete => 'حذف';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'هل تريد حذف $countString ملف يمثل $totalSizeText؟',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'احذف $numberTextنهائيًا من ذاكرة التخزين';
  }

  @override
  String get deletePlaylist => 'حذف قائمة التشغيل';

  @override
  String get deleteTempFiles => 'حذف الملفات المؤقتة';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'الوصف';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'هل تقصد';

  @override
  String get dimIntensity => 'شدة التعتيم';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'يتم تعتيم المشغل الصغير بعد $secondsString ثانية من عدم النشاط',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'الدليل غير موجود';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'تعطيل الكل';

  @override
  String get disableReordering => 'تعطيل إعادة الترتيب';

  @override
  String get disableSearchCleanup => 'تعطيل تنظيف البحث';

  @override
  String get discNumber => 'رقم القرص';

  @override
  String get discNumberTotal => 'اجمالي الأقراص';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'لم يعجبني';

  @override
  String get dismissibleMiniplayer => 'مشغل صغير قابل للرفض';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'عرض الزمن الحالي بدلا من عرض الفرق الزمني';

  @override
  String get displayAlbumCardTopRightDate => 'التاريخ الأيمن أعلى بطاقة الألبوم';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'عرض تاريخ الألبوم في أعلى يمين بطاقة الألبوم';

  @override
  String get displayArtistBeforeTitle => 'عرض الفنان قبل العنوان';

  @override
  String get displayArtworkOnLockscreen => 'عرض العمل الفني على شاشة القفل';

  @override
  String get displayAudioInfoInMiniplayer => 'عرض معلومات الصوت';

  @override
  String get displayFavButtonInNotification => 'عرض زر المفضلة في شريط الإشعارات';

  @override
  String get displayFavButtonInNotificationSubtitle => 'قد يتم ازاحة الصورة المصغرة';

  @override
  String get displayFavouriteIconInTrackTile => 'عرض زر المفضلة';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'عرض المدة المتبقية بدلاً من الإجمالي';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'عرض العنصر الثالث في كل صف';

  @override
  String get displayThirdRowInTrackTile => 'عرض الصف الثالث';

  @override
  String get displayTrackNumberInAlbumPage => 'عرض رقم المقطع في صفحة الألبوم';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'قم بعرض مربع صغير يحتوي على رقم المقطع في صفحة الألبوم';

  @override
  String get doNothing => 'لا تفعل شيئا';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'تم';

  @override
  String get dontAskAgain => 'لا تسأل مرة اخرى';

  @override
  String get dontDim => 'لا تقم بالتعتيم';

  @override
  String get dontRestorePosition => 'لا تسترجع';

  @override
  String get dontResume => 'لا تستأنف';

  @override
  String get doubleTapToToggleLyrics => 'انقر نقرًا مزدوجًا لإظهار كلمات الأغنية';

  @override
  String get download => 'تنزيل';

  @override
  String get downloadingWillOverrideIt => 'التنزيل سوف يحل محلها';

  @override
  String get downloads => 'التنزيلات';

  @override
  String get downloadsMetadataTags => 'تنزيل علامات البيانات الوصفية';

  @override
  String get downloadsMetadataTagsSubtitle => 'قم باستخراج الفنان والعنوان والألبوم من معلومات الفيديو بشكل افتراضي';

  @override
  String get dragToSeek => 'اسحب للبحث';

  @override
  String get duckAudio => 'صوت البطة';

  @override
  String get duplicatedItemsAdding => 'أنت تحاول إضافة بعض العناصر الموجودة بالفعل في قائمة التشغيل هذه';

  @override
  String get duplicatedTracks => 'المقاطع المكررة';

  @override
  String get duration => 'المدة';

  @override
  String get edgeColorsSwitching => 'تبديل ألوان الحواف';

  @override
  String get edit => 'تعديل';

  @override
  String get editArtwork => 'تعديل العمل الفني';

  @override
  String get editTags => 'تعديل الوسوم';

  @override
  String get email => 'الإيميل';

  @override
  String get emptyNonMeaningfulTagFields => 'لديك حقول ذات قيم فارغة/ليست ذات معنى، تأكد من أنك تريد حقًا تعديلها';

  @override
  String get emptyValue => 'قيمة فارغة';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'تفعيل تأثير الضبابية';

  @override
  String get enableBottomNavBar => 'تمكين شريط التنقل السفلي';

  @override
  String get enableBottomNavBarSubtitle => 'العناصر موجودة داخل الدرج في كلا الاتجاهين';

  @override
  String get enableClipboardMonitoring => 'تفعيل مراقبة الحافظة';

  @override
  String get enableClipboardMonitoringSubtitle => 'يسمح بلصق الروابط والنص داخل شريط البحث أثناء التنقل';

  @override
  String get enableCrossfadeEffect => 'تمكين تأثير التلاشي';

  @override
  String get enableFadeEffectOnPlayPause => 'تمكين تأثير التلاشي عند التشغيل/الإيقاف المؤقت';

  @override
  String get enableFoldersHierarchy => 'تمكين التسلسل الهرمي للمجلدات';

  @override
  String get enableGlowEffect => 'تمكين تأثير التوهج';

  @override
  String get enableM3uSync => 'تمكين مزامنة M3U';

  @override
  String get enableM3uSyncNote1 => 'تسمح مزامنة M3U بحفظ تغييرات قائمة التشغيل في ملف M3U الأصلي';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'إذا حدث أي خطأ، فسيتم العثور على نسخة احتياطية لقائمة التشغيل هذه في $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'في حالة الرفض، سيتم فقدان جميع التغييرات التي تم إجراؤها في قائمة التشغيل هذه عند إعادة التشغيل';

  @override
  String get enableMiniplayerParticles => 'تمكين الجسيمات المتحركة';

  @override
  String get enableParallaxEffect => 'تمكين تأثير المنظر';

  @override
  String get enablePartyMode => 'تفعيل وضع الحفلة';

  @override
  String get enablePartyModeSubtitle => 'تطبيق تأثير التنفس للحافة';

  @override
  String get enablePictureInPicture => 'تمكين صورة داخل صورة';

  @override
  String get enableReordering => 'تمكين اعادة الترتيب';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'تمكين تنظيف البحث';

  @override
  String get enableSearchCleanupSubtitle => 'سيتم تجاهل كافة الرموز والمسافات';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'تمكين تشغيل الفيديو';

  @override
  String get enterSymbol => 'الرجاء إدخال رمز';

  @override
  String get equalizer => 'معادل الصوت';

  @override
  String get error => 'خطأ';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'خطأ أثناء تشغيل المسار';

  @override
  String get excludedFodlers => 'المجلدات المستبعدة';

  @override
  String get exit => 'خروج';

  @override
  String get exitAppSubtitle => 'اضغط مرة أخرى للخروج';

  @override
  String get expandedMiniplayer => 'مشغل صغير موسع';

  @override
  String get exportAsM3u => 'تصدير كـ M3U';

  @override
  String get extension => 'ملحق';

  @override
  String get externalFiles => 'ملفات خارجية';

  @override
  String get extract => 'استخراج';

  @override
  String get extractAllColorPalettes => 'استخراج كافة لوحات الألوان';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'هل تريد استخراج $numberString المتبقي؟',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'استخراج الفنانين المشاركين من العنوان';

  @override
  String get extractFeatArtistSubtitle => 'مقتطفات من الفنانين (fet.X) و(ft.X)، كمدخل فنان جديد.';

  @override
  String get extractingInfo => 'استخراج المعلومات';

  @override
  String get extras => 'إضافات';

  @override
  String get extrasSubtitle => 'إعدادات إضافية لتحسين تجربتك';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'فشل';

  @override
  String get failedEdits => 'تعديلات فاشلة';

  @override
  String get favourites => 'المفضلات';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'جلب';

  @override
  String get fetchingOfAllVideos => 'جلب جميع مقاطع الفيديو';

  @override
  String get file => 'ملف';

  @override
  String get fileAlreadyExists => 'الملف موجود بالفعل';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'اسم الملف';

  @override
  String get fileNameWoExt => 'اسم الملف بدون امتداد';

  @override
  String get filenameShouldntStartWith => 'لا ينبغي أن يبدأ اسم الملف بـ';

  @override
  String get files => 'ملفات';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'تصفية الألبومات';

  @override
  String get filterArtists => 'تصفية الفنانون';

  @override
  String get filterGenres => 'تصفية الأنواع';

  @override
  String get filterPlaylists => 'تصفية قوائم التشغيل';

  @override
  String get filterTracks => 'تصفية المقاطع';

  @override
  String get filterTracksBy => 'تصفية المقاطع في قوائم البحث حسب';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'المسارات التي تمت تصفيتها حسب الحجم والمدة';

  @override
  String get finished => 'منتهي';

  @override
  String get finishedUpdatingLibrary => 'تم الانتهاء من تحديث المكتبة';

  @override
  String get firstListen => 'أول استماع';

  @override
  String get fixYtdlpBigThumbnailSize => 'إصلاح حجم الصورة المصغرة الكبيرة لـ yt-dlp';

  @override
  String get floatingActionButton => 'زر الإجراء العائم';

  @override
  String get folder => 'مجلد';

  @override
  String get folderName => 'اسم المجلد';

  @override
  String get folders => 'المجلدات';

  @override
  String get fontScale => 'حجم الخط';

  @override
  String get forceMiniplayerFollowTrackColors => 'إجبار المشغل الصغير على اتباع ألوان المقطع';

  @override
  String get forceSquaredAlbumThumbnail => 'فرض الصورة المصغرة المربعة للألبوم';

  @override
  String get forceSquaredThumbnailNote => 'حجم الصورة المصغرة وارتفاع البلاط ليسا متساويين، ولن يكون المظهر المربع كما هو متوقع، هل ترغب في جعلهما متساويين؟';

  @override
  String get forceSquaredTrackThumbnail => 'فرض صورة مصغرة مربعة';

  @override
  String get forceStopColorPaletteGeneration => 'فرض إيقاف استخراج لوحات الألوان؟ لا يزال بإمكانك الاستمرار في ذلك لاحقًا';

  @override
  String get format => 'الصيغة';

  @override
  String get fullscreen => 'ملء الشاشة';

  @override
  String get gaplessPlayback => 'التشغيل بلا فصل';

  @override
  String get generate => 'إنشاء';

  @override
  String get generateFromDates => 'مدى زمني';

  @override
  String get generateFromDatesSubtitle => 'قم بإنشاء المقاطع التي استمعت إليها في نطاق زمني';

  @override
  String get generateRandomPlaylist => 'إنشاء قائمة تشغيل عشوائية';

  @override
  String get genre => 'النوع';

  @override
  String get genres => 'الانواع';

  @override
  String get goToAlbum => 'اذهب الى الألبوم';

  @override
  String get goToArtist => 'اذهب الى الفنان';

  @override
  String get goToChannel => 'اذهب الى القناة';

  @override
  String get goToFolder => 'اذهب الى المجلد';

  @override
  String get goodLooking => 'جميل المظهر';

  @override
  String get grantStoragePermission => 'السماح بأذن التخزين';

  @override
  String get group => 'المجموعة';

  @override
  String get groupArtworksByAlbum => 'تجميع الأعمال الفنية حسب الألبوم';

  @override
  String get guide => 'دليل';

  @override
  String get hapticFeedback => 'رد الفعل بالأهتزاز';

  @override
  String get heightOfAlbumTile => 'ارتفاع بلاط الألبوم';

  @override
  String get heightOfTrackTile => 'ارتفاع بلاط المقطع';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'مطابقات عالية';

  @override
  String get highPerformance => 'اداء عال';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'السجل';

  @override
  String get historyImportMissingEntriesNote => 'لا يمكن العثور على هذه الإدخالات داخل المكتبة، إذا كنت تعتقد أنها موجودة، فيرجى التفكير في إضافتها يدويًا';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: 'سيتم استبدال $listensCountString من عمليات الاستماع لـ $oldTrackInfo بـ $newTrackInfo، هل تؤكد ذلك؟',
    );
    return '$_temp0';
  }

  @override
  String get home => 'الرئيسية';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => 'صيغة ١٢ ساعة';

  @override
  String get hours => 'ساعات';

  @override
  String get iReadAndAgree => 'قرأت و أوافق';

  @override
  String get ifNotPlaying => 'إذا لم يتم تشغيله';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'يمكن تبطيء التنزيلات عندما يكون التطبيق مقيدًا بالبطارية';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'تجاهل الجمل البادئة الشائعة';

  @override
  String get ignores => 'تجاهل';

  @override
  String get imageSource => 'مصدر الصور';

  @override
  String get immersiveMode => 'وضع الغمر';

  @override
  String get immersiveModeSubtitle => 'إخفاء شريط الحالة والتنقل أثناء توسيع المشغل الصغير';

  @override
  String get import => 'استيراد';

  @override
  String get importAll => 'استيراد الكل';

  @override
  String get importLastFmHistory => 'استيراد سجل LastFm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. انتقل إلى $lastfmCsvLink\n\n2. اكتب اسم المستخدم الخاص بك، وقم بإحضار ملف CSV وتنزيله.\n\n3. اختر الملف من الشاشة التالية.';
  }

  @override
  String get importTimeRange => 'استيراد النطاق الزمني';

  @override
  String get importYoutubeHistory => 'استيراد سجل اليوتيوب';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. انتقل إلى $takeoutLink\n\n2. اضغط على \"تنسيقات متعددة\" وبجانب \"السجل\" اختر \"JSON\".\n\n3. اضغط على \"جميع بيانات يوتيوب متضمنة\"، وقم بإلغاء تحديد الكل واختر السجل فقط.\n\n4. إنشاء التصدير والتنزيل وفك الضغط.\n\n5. اختر \"watch-history.json\" من الشاشة التالية.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'تم استيراد $numberString من القنوات بنجاح',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'تم استيراد $numberText من قوائم التشغيل بنجاح',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'تضمين مقاطع الفيديو';

  @override
  String get indexRefreshRequired => 'قم بالتحديث بعد تغيير هذا';

  @override
  String get indexer => 'المفهرس';

  @override
  String get indexerNote => 'ملاحظة: يشير العدد غير الكامل من الأعمال الفنية إلى الأعمال الفنية المكررة وغير الموجودة';

  @override
  String get indexerSubtitle => 'إدارة مكتبة الموسيقى الخاصة بك';

  @override
  String get infinityQueueOnNextPrev => 'قائمة الانتظار اللانهائية على التالي/السابق';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'سيؤدي الضغط على التالي أثناء تشغيل العنصر الأخير إلى الانتقال إلى العنصر الأول، والعكس صحيح';

  @override
  String get info => 'معلومات';

  @override
  String get inserted => 'تم إدراجها';

  @override
  String get instantlyApplies => 'تطبق على الفور';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'عكس التحديد';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'عنصر';

  @override
  String get jump => 'قفز';

  @override
  String get jumpToDay => 'اقفز الى اليوم';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'انتقل إلى المقطع الأول بعد الانتهاء من قائمة الانتظار';

  @override
  String get keepCachedVersions => 'احتفظ بالإصدارات المخزنة مؤقتًا';

  @override
  String get keepFileDates => 'احتفظ بتواريخ الملفات';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'تم توسيع المشغل الصغير';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'يتم توسيع المشغل الصغير ويتم تشغيل الفيديو';

  @override
  String get keepScreenAwakeNone => 'لا تبقي الشاشة مستيقظة';

  @override
  String get keepScreenAwakeWhen => 'إبقاء الشاشة مستيقظة عندما';

  @override
  String get killPlayerAfterDismissingApp => 'إغلاق المشغل بعد رفض التطبيق';

  @override
  String get language => 'اللغة';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'تبويبات المكتبة';

  @override
  String get libraryTabsReorder => 'يمكنك إعادة ترتيب علامات التبويب النشطة.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'إعجاب';

  @override
  String get liked => 'معجب';

  @override
  String get link => 'رابط';

  @override
  String get listOfFolders => 'قائمة المجلدات';

  @override
  String get loadAll => 'تجهيز الكل';

  @override
  String get loadingFile => 'تجهيز الملف';

  @override
  String get local => 'محلي';

  @override
  String get localVideoMatching => 'مطابقة الفيديو المحلية';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'اضغط مطولا على كلمات الاغنية للدخول على عرض الشاشة الكامل';

  @override
  String get lostMemories => 'ذكريات ضائعة';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'في مثل هذا الوقت تقريبًا، منذ $numberString سنة',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'محسن جهارة الصوت';

  @override
  String get lyricist => 'شاعر غنائي';

  @override
  String get lyrics => 'كلمات الاغنية';

  @override
  String get lyricsSource => 'مصدر كلمات الأغنية';

  @override
  String get m3uPlaylist => 'قائمة تشغيل M3U';

  @override
  String get makeYourFirstListen => 'استمع لأول مرة!';

  @override
  String get manage => 'إدارة';

  @override
  String get manageYourAccounts => 'إدارة حساباتك';

  @override
  String get manualBackup => 'يدوي';

  @override
  String get manualBackupSubtitle => 'اختر ملف محدد';

  @override
  String get markAsRead => 'وضع علامة مقروء';

  @override
  String get matchAllTracks => 'مطابقة كل المقاطع';

  @override
  String get matchAllTracksNote => 'يمكن أن يكون لهذا تأثير على سرعة المطابقة، لأنه سيفحص جميع المقاطع الموجودة في مكتبتك';

  @override
  String get matchingType => 'نوع المطابقة';

  @override
  String get maxAudioCacheSize => 'الحد الأقصى لحجم ذاكرة التخزين المؤقت للصوت';

  @override
  String get maxImageCacheSize => 'الحد الأقصى لحجم ذاكرة التخزين المؤقت للصورة';

  @override
  String get maxVideoCacheSize => 'الحد الأقصى لحجم ذاكرة التخزين المؤقت للفيديو';

  @override
  String get maximum => 'الأقصى';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'متجر الوسائط مفعل لن يكون له اي تاثير';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'الرمز';

  @override
  String get membershipCodeSentToEmail => 'تم إرسال الرمز إلى بريدك الإلكتروني';

  @override
  String get membershipDidntChange => 'العضوية لم تتغير';

  @override
  String get membershipEnjoyNew => 'استمتع بعضويتك الجديدة';

  @override
  String get membershipFreeCoupon => 'قسيمة مجانية';

  @override
  String get membershipManage => 'إدارة عضويتك';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'لم يتم العثور على اشتراكات لهذا المستخدم';

  @override
  String get membershipSignInToPatreonAccount => 'قم بتسجيل الدخول إلى حساب باتريون الخاص بك';

  @override
  String get membershipUnknown => 'عضوية غير معروفة';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'تحتاج إلى عضوية $name1 أو $name2 لإضافة حسابات متعددة';
  }

  @override
  String get merge => 'دمج';

  @override
  String get metadataCache => 'السجل المؤقت للبيانات الوصفية';

  @override
  String get metadataEditFailed => 'فشل في تحرير بيانات التعريف';

  @override
  String get metadataReadFailed => 'فشل في قراءة بيانات التعريف';

  @override
  String get minFileDuration => 'الحد الأدنى لمدة المقطع';

  @override
  String get minFileSize => 'الحد الأدنى لحجم الملف';

  @override
  String get minTrackDurationToRestoreLastPosition => 'الحد الأدنى لمدة المقطع لاستعادة آخر موضع تم تشغيله';

  @override
  String get minValueCantBeMoreThanMax => 'لا يمكن أن تكون القيمة الدنيا أكثر من الحد الأقصى';

  @override
  String get minValueToCountTrackListen => 'عد الاستماع بعد: . ';

  @override
  String get minimizedMiniplayer => 'تصغير المشغل الصغير';

  @override
  String get minimum => 'الأدنى';

  @override
  String get minimumOneFolderSubtitle => 'يجب أن يكون هناك مجلد واحد على الأقل، أضف المزيد من المجلدات إذا كنت تريد إزالة هذا المجلد';

  @override
  String get minimumOneItem => 'تعذرت إزالة العنصر';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'يجب أن يبقى على الأقل $numberString من العناصر',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'تخصيص المشغل الصغير';

  @override
  String get minutes => 'دقائق';

  @override
  String get missingEntries => 'مدخلات مفقودة';

  @override
  String get missingTracks => 'مقاطع مفقودة';

  @override
  String get mix => 'خلط';

  @override
  String get mixPlaylistGeneratedByYoutube => 'خلط قائمة التشغيل التي تم إنشاؤها بواسطة يوتيوب';

  @override
  String get mixes => 'المخلوطة';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'شهر';

  @override
  String get months => 'شهور';

  @override
  String get mood => 'مزاج';

  @override
  String get moods => 'الحالة المزاجية';

  @override
  String get more => 'المزيد';

  @override
  String get mostPlayed => 'الأكثر تشغيلا';

  @override
  String get multipleTracksTagsEditNote => 'أنت على وشك تعديل هذه المقاطع،\nالمعطيات التي لم تتغير ستبقى دون تغيير.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'الاسم';

  @override
  String get nameContainsBadCharacter => 'الاسم يحتوي على حرف غير صالح';

  @override
  String get never => 'ابداً';

  @override
  String get newDirectory => 'دليل جديد';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'إضافة المقاطع';

  @override
  String get newTracksMoods => 'مزاج';

  @override
  String get newTracksMoodsSubtitle => 'إنشاء المقاطع على أساس الحالة المزاجية المتاحة';

  @override
  String get newTracksRandom => 'عشوائي';

  @override
  String get newTracksRandomSubtitle => 'اختر مقاطع عشوائية من مكتبتك';

  @override
  String get newTracksRatings => 'التقييمات';

  @override
  String get newTracksRatingsSubtitle => 'إنشاء مقاطع ذات تصنيف محدد';

  @override
  String get newTracksRecommended => 'موصى به';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'قم بإنشاء المقاطع التي تستمع إليها عادةً باستخدام $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'تاريخ الإصدار مشابه';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'قم بإنشاء المقاطع التي تم إصدارها في نفس الوقت تقريبًا مثل $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'المقطع له سنة غير معروفة';

  @override
  String get newest => 'الأحدث';

  @override
  String get next => 'التالي';

  @override
  String get no => 'لا';

  @override
  String get noChangesFound => 'لم يتم العثور على أي تغييرات.';

  @override
  String get noEnoughTracks => 'ليس لديك الكثير من المقاطع..';

  @override
  String get noExcludedFolders => 'ليس لديك أي مجلدات مستبعدة';

  @override
  String get noFolderChosen => 'لم تقم باختيار أي مجلد';

  @override
  String get noMoodsAvailable => 'لا يوجد مزاج متاح';

  @override
  String get noNetworkAvailableToFetchData => 'لا توجد شبكة متاحة لجلب البيانات';

  @override
  String get noTracksFound => 'لم يتم العثور على مقاطع';

  @override
  String get noTracksFoundBetweenDates => 'لا يحتوي هذا النطاق الزمني على أية مقاطع.';

  @override
  String get noTracksFoundInDirectory => 'لم يتم العثور على مقاطع في هذا المجلد';

  @override
  String get noTracksInHistory => 'ليس لديك ما يكفي من المقاطع في السجل';

  @override
  String get nonActive => 'غير نشط';

  @override
  String get nonFavourites => 'غير المفضلة';

  @override
  String get none => 'لاشيء';

  @override
  String get normalizeAudio => 'موازنة الصوت';

  @override
  String get normalizeAudioSubtitle => 'موازنة مستوى الصوت من خلال قراءة علامة كسب الإعادة أو المعلومات المقدمة من يوتيوب';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'ملاحظة';

  @override
  String get notification => 'الإشعارات';

  @override
  String get notifications => 'الإشعارات';

  @override
  String get numberOfTracks => 'عدد المقاطع';

  @override
  String get ofLabel => 'من';

  @override
  String get offlineSearch => 'بحث دون اتصال';

  @override
  String get offset => 'الإزاحة';

  @override
  String get oldDirectory => 'الدليل القديم';

  @override
  String get oldDirectoryStillHasTracks => 'المجلد القديم لا يزال يحتوي على بعض المقاطع، هل تؤكد ذلك؟';

  @override
  String get oldestWatch => 'الأقدم مشاهدة';

  @override
  String get onInterruption => 'عند المقاطعة';

  @override
  String get onNotificationTap => 'عند الضغط على الإشعار';

  @override
  String get onOpeningYoutubeLink => 'عند فتح رابط اليوتيوب';

  @override
  String get onSwiping => 'عند السحب';

  @override
  String get onVolumeZero => 'عند مستوى الصوت ٠';

  @override
  String get ongoing => 'جاري التنفيذ';

  @override
  String get open => 'فتح';

  @override
  String get openApp => 'فتح التطبيق';

  @override
  String get openInFileExplorer => 'فتح في متصفح الملفات';

  @override
  String get openInYoutubeView => 'فتح في عرض يوتيوب';

  @override
  String get openMiniplayer => 'فتح المشغل الصغير';

  @override
  String get openQueue => 'فتح قائمة الانتظار';

  @override
  String get openYoutubeLink => 'فتح رابط يوتيوب';

  @override
  String operationRequiresAccount({required String name}) {
    return 'تتطلب عملية $name حسابًا، قم بتسجيل الدخول للمتابعة';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'تتطلب العملية $operation عضوية $name على الأقل';
  }

  @override
  String get or => 'او';

  @override
  String get others => 'أخرى';

  @override
  String get output => 'المخرجات';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'تجاوز الملفات القديمة في نفس المجلد';

  @override
  String get palette => 'مجموعة الألوان';

  @override
  String get paletteMix => 'مزج';

  @override
  String get paletteNewMix => 'مزيج جديد';

  @override
  String get paletteSelectedMix => 'المزيج المختار';

  @override
  String get parallelDownloads => 'التنزيلات الموازية';

  @override
  String get parsed => 'تحليل';

  @override
  String get password => 'Password';

  @override
  String get path => 'المسار الكامل للملف';

  @override
  String get pause => 'إيقاف مؤقت';

  @override
  String get pauseFadeDuration => 'مدة الإيقاف المؤقت للتلاشي';

  @override
  String get pausePlayback => 'إيقاف مؤقت للتشغيل';

  @override
  String get percentage => 'النسبة';

  @override
  String get performanceMode => 'وضع الاداء';

  @override
  String get performanceNote => 'قد يؤثر على الأداء';

  @override
  String get personalized => 'مخصص';

  @override
  String get personalizedRelatedVideos => 'مقاطع فيديو مخصصة ذات صلة';

  @override
  String get personalizedRelatedVideosSubtitle => 'سيؤدي تعطيل هذا إلى زيادة استخدام البيانات';

  @override
  String get pickColorsFromDeviceWallpaper => 'اختر الألوان من خلفية الجهاز';

  @override
  String get pickFromStorage => 'اختر من وحدة التخزين';

  @override
  String get pinned => 'مُثَبَّتَة';

  @override
  String get pitch => 'الحدة';

  @override
  String get plain => 'مستو';

  @override
  String get play => 'تشغيل';

  @override
  String get playAfter => 'تشغيل بعد';

  @override
  String get playAfterNextPrev => 'التشغيل التلقائي على التالي/السابق';

  @override
  String get playAll => 'تشغيل الكل';

  @override
  String get playFadeDuration => 'تشغيل مدة التلاشي';

  @override
  String get playLast => 'تشغيل الأخير';

  @override
  String get playNext => 'تشغيل التالي';

  @override
  String get playbackSetting => 'التشغيل';

  @override
  String get playbackSettingSubtitle => 'يمكن الوصول إليها مباشرة في المشغل عن طريق الضغط لفترة طويلة على زر الصوت';

  @override
  String get playlist => 'قائمة التشغيل';

  @override
  String get playlists => 'قوائم التشغيل';

  @override
  String get playlistsImportM3uNative => 'سيؤدي هذا إلى استيراد قوائم تشغيل M3U لاستخدامها فقط من قبل namida، واستخدامها إذا كنت تقوم بالترحيل';

  @override
  String get playlistsImportM3uSynced =>
      'سيؤدي هذا تلقائيًا إلى استيراد قوائم تشغيل M3U من مجلدات المفهرس والحفاظ على مزامنتها مع ملف M3U الأصلي. قم بتمكينها إذا قمت بالوصول إلى/تعديل قوائم التشغيل من تطبيقات أخرى';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'الاستيراد التلقائي لقوائم تشغيل M3U';

  @override
  String get pleaseEnterADifferentName => 'هذا الاسم مستخدم بالفعل مسبقا :(\nيرجى تجربة اسم فاخر آخر';

  @override
  String get pleaseEnterALink => 'الرجاء إدخال الرابط';

  @override
  String get pleaseEnterALinkSubtitle => 'تخمين.. هل هذا رابط اليوتيوب؟';

  @override
  String get pleaseEnterAName => 'الرجاء إدخال اسم';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'منع المقاطع المكررة';

  @override
  String get preventDuplicatedTracksSubtitle => 'يستخدم اسم الملف لتحديد المقاطع بشكل فريد';

  @override
  String get preview => 'معاينة';

  @override
  String get previous => 'سابق';

  @override
  String get previousButtonReplays => 'إعادة تشغيل الزر السابق';

  @override
  String get previousButtonReplaysSubtitle => 'إذا تم الضغط عليه بينما كان الوضع الحالي أكثر من مدة البحث';

  @override
  String get prioritizeEmbeddedLyrics => 'إعطاء الأولوية للكلمات المضمنة';

  @override
  String get priority => 'أولوية';

  @override
  String get private => 'خاص';

  @override
  String get progress => 'التقدم';

  @override
  String get promptToChangeTrackPath => 'يحدث هذا عادةً عند حذف/نقل/إعادة تسمية الملف خارج namida، هل ترغب في انعاش المسار الحالي؟';

  @override
  String get public => 'عام';

  @override
  String get queue => 'الانتظار';

  @override
  String get queues => 'قوائم الانتظار';

  @override
  String get random => 'عشوائي';

  @override
  String get randomPicks => 'اختيار عشوائي';

  @override
  String get rating => 'تقييم';

  @override
  String get reIndex => 'إعادة الفهرسة';

  @override
  String get reIndexSubtitle => 'أعد بناء مكتبة الموسيقى الخاصة بك من الصفر';

  @override
  String get reIndexWarning => 'قد تستغرق هذه العملية بعض الوقت، حسب حجم مكتبتك.\n\nلن تتم إعادة فهرسة الأعمال الفنية طالما أنها لا تزال موجودة';

  @override
  String get recentAlbums => 'الالبومات الحديثة';

  @override
  String get recentArtists => 'أحدث الفنانين';

  @override
  String get recentListens => 'المستمع لها حديثا';

  @override
  String get recentlyAdded => 'مضافة حديثا';

  @override
  String get recordLabel => 'تسمية التسجيل';

  @override
  String get refresh => 'انعاش';

  @override
  String get refreshLibrary => 'تحديث المكتبة';

  @override
  String get refreshLibrarySubtitle => 'تحقق من الموسيقى المضافة أو المحذوفة حديثًا';

  @override
  String get refreshOnStartup => 'تحديث عند التشغيل';

  @override
  String get relatedVideos => 'مقاطع ذات صلة';

  @override
  String get rememberAudioOnlyMode => 'تذكر وضع الصوت فقط';

  @override
  String get remixer => 'الخالط';

  @override
  String get remove => 'احذف';

  @override
  String get removeDuplicates => 'حذف المكررة';

  @override
  String get removeFromFavourites => 'إزالة من المفضلة';

  @override
  String get removeFromLibrary => 'حذف من المكتبة';

  @override
  String get removeFromPlaylist => 'حذف من قائمة التشغيل';

  @override
  String get removeQueue => 'إزالة قائمة الانتظار';

  @override
  String get removeSourceFromHistory => 'إزالة المصدر من السجل';

  @override
  String get removeWhitespaces => 'إزالة المسافات البيضاء';

  @override
  String get removed => 'تم حذفه';

  @override
  String get rename => 'إعادة تسمية';

  @override
  String get renamePlaylist => 'إعادة تسمية قائمة التشغيل';

  @override
  String get reorderable => 'قابل لإعادة الترتيب';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'كرر ذلك لمدة $number مرات أخرى',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'وضع التكرار';

  @override
  String get repeatModeAll => 'كرر كل قائمة الانتظار';

  @override
  String get repeatModeNone => 'توقف عند المقطع الأخير';

  @override
  String get repeatModeOne => 'كرر المقطع الحالي';

  @override
  String get replaceAllListensWithAnotherTrack => 'استبدل جميع عمليات الاستماع بمقطع آخر';

  @override
  String get replies => 'الردود';

  @override
  String get reply => 'رد';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'يتطلب مسح ذاكرة التخزين المؤقت للصورة وإعادة فهرستها';

  @override
  String get rescanVideos => 'إعادة فحص مقاطع الفيديو';

  @override
  String get resetBrightness => 'إعادة ضبط السطوع';

  @override
  String get resetToDefault => 'ضبط لـ';

  @override
  String get respectNoMedia => 'احترام .nomedia';

  @override
  String get respectNoMediaSubtitle => 'لا تقم بتضمين المجلدات التي تحتوي على .nomedia';

  @override
  String get restart => 'إعادة التشغيل';

  @override
  String get restoreBackup => 'استرجاع النسخة الاحتياطية';

  @override
  String get restoreDefaults => 'استرجاع الافتراضية';

  @override
  String get restoredBackupSuccessfully => 'تمت استعادة النسخة الاحتياطية';

  @override
  String get restoredBackupSuccessfullySub => 'تمت استعادة ملف النسخ الاحتياطي بنجاح';

  @override
  String get resume => 'استكمال';

  @override
  String get resumeIfWasInterrupted => 'استئناف إذا تم إيقافه مؤقتًا بسبب المقاطعة';

  @override
  String get resumeIfWasPausedByVolume => 'استئناف إذا تم إيقافه مؤقتًا حسب مستوى الصوت';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'استئناف إذا تم إيقافه مؤقتًا لمدة تقل عن $numberString دقيقة',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'عكس الترتيب';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'نغمة الرنين';

  @override
  String get sameDirectoryOnly => 'نفس الدليل فقط';

  @override
  String get sample => 'نموذج';

  @override
  String get sampleRate => 'معدل العينة';

  @override
  String get save => 'حفظ';

  @override
  String get saveToLibrary => 'حفظ في المكتبة';

  @override
  String get savedIn => 'حفظ في';

  @override
  String get scaleMultiplier => 'مضاعف النطاق';

  @override
  String get search => 'بحث';

  @override
  String get searchYoutube => 'ابحث في يوتيوب';

  @override
  String get seconds => 'ثواني';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'البحث عن المدة';

  @override
  String get seekDurationInfo => 'يمكنك النقر على المدة الحالية للبحث إلى الوراء والمدة الإجمالية للبحث إلى الأمام';

  @override
  String get seekbar => 'شريط التقدم';

  @override
  String get selectAll => 'تحديد الكل';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'حدد الملفات الموجودة بالفعل في المكتبة المحلية';

  @override
  String get selectedTracks => 'المقاطع المختارة';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'لن يتم تقسيم هذه الكلمات';

  @override
  String get separatorsMessage => 'لا داعي لإدراج مسافات، إلا إذا كنت تريد استخدام حرف/رمز يمكن العثور عليه في كلمة كاملة (مثل x وft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'تعيين كـ';

  @override
  String get setAsDefault => 'تعيين كافتراضي';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'قم بتعيين الملف الذي تم تعديله مؤخرًا كتاريخ تحميل الفيديو';

  @override
  String get setMoods => 'تعيين المزاج';

  @override
  String get setMoodsSubtitle => 'استخدم الفواصل (،) للفصل بينهما';

  @override
  String get setRating => 'تعيين التقييم';

  @override
  String get setTags => 'تعيين العلامات';

  @override
  String get setYoutubeLink => 'تعيين رابط يوتيوب';

  @override
  String get settings => 'الإعدادات';

  @override
  String get setupFirstStartup => 'إعداد أول بدء التشغيل';

  @override
  String get share => 'مشاركة';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'اختصارات';

  @override
  String get shouldDuck => 'ينبغي بطة';

  @override
  String get shouldDuckNote => 'يشير إلى أنه ينبغي خفض مستوى الصوت. على سبيل المثال: الإشعار';

  @override
  String get shouldPause => 'يجب أن يتوقف';

  @override
  String get shouldPauseNote => 'يشير إلى أنه يجب إيقاف التشغيل مؤقتًا. على سبيل المثال: المكالمات';

  @override
  String get showAll => 'اظهر الكل';

  @override
  String get showChannelWatermarkInFullscreen => 'عرض العلامة المائية للقناة في وضع ملء الشاشة';

  @override
  String get showFailedOnly => 'اظهار المعطل فقط';

  @override
  String get showHideUnknownFields => 'إظهار/إخفاء الحقول غير المعروفة';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'عرض الخلط في';

  @override
  String get showMore => 'إظهار المزيد';

  @override
  String get showShortVideosIn => 'عرض الفيديوهات القصيرة في';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'عرض بطاقات نهاية الفيديو';

  @override
  String get showWebm => 'عرض webm';

  @override
  String get shuffle => 'خلط';

  @override
  String get shuffleAll => 'خلط الكل';

  @override
  String get shuffleNext => 'خلط التالي';

  @override
  String get signIn => 'تسجيل الدخول';

  @override
  String get signInCanceled => 'تسجيل الدخول تم إلغائه';

  @override
  String get signInFailed => 'فشل تسجيل الدخول';

  @override
  String get signInToYourAccount => 'تسجيل الدخول الى حسابك';

  @override
  String get signInYouDontHaveAccount => 'ليس لديك أي حساب مسجل الدخول اليه';

  @override
  String get signInYouNeedAccountToViewPage => 'تحتاج إلى حساب لعرض هذه الصفحة';

  @override
  String get signOut => 'تسجيل الخروج';

  @override
  String signOutFromName({required String name}) {
    return 'تسجيل الخروج من $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'تسجيل الدخول يسمح بالاستخدام الأساسي';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'احصل على الوصول المبكر من خلال باتريون أو باستخدام القسيمة';

  @override
  String get similarDiscoverDate => 'تاريخ أكتشاف مشابه';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'إنشاء مسارات صوتية أكتشفت في نفس وقت_المسار_الحالي';
  }

  @override
  String get similarTimeRange => 'مدة زمنية متشابهة';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'إنشاء مسارات أستمعت إليها في نفس وقت_المسار_الحالي_';
  }

  @override
  String get singles => 'اغانٍ فردية';

  @override
  String get size => 'الحجم';

  @override
  String get skip => 'تخط';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'تخط الصمت';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'النوم بعد';

  @override
  String get sleepTimer => 'مؤقت النوم';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'فرز حسب';

  @override
  String get source => 'المصدر';

  @override
  String get speed => 'السرعة';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'عرض الشبكة للألبوم المتداخل';

  @override
  String get start => 'بدء';

  @override
  String get stats => 'الإحصائيات';

  @override
  String get statsSubtitle => 'إليك بعض المعلومات عن مكتبتك';

  @override
  String get stop => 'إيقاف';

  @override
  String get stopAfterThisTrack => 'توقف بعد هذا المقطع';

  @override
  String get stopAfterThisVideo => 'توقف بعد هذا الفيديو';

  @override
  String get storagePermissionDenied => 'تم رفض الإذن';

  @override
  String get storagePermissionDeniedSubtitle => 'يرجى السماح بالوصول لتتمكن من تنفيذ هذا الإجراء';

  @override
  String get stretchLyricsDuration => 'تمديد مدة كلمات الأغنية';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'اشتراك';

  @override
  String get subscribed => 'تم الإشتراك';

  @override
  String get subscriber => 'مُشترك';

  @override
  String get subscribers => 'مشتركون';

  @override
  String get succeeded => 'نجح';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'الدعم';

  @override
  String get supremacy => 'سيادة';

  @override
  String get sussyBaka => 'لا توجد مقاطع';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'اسحب لفتح الدرج';

  @override
  String get synced => 'متزامن';

  @override
  String get synopsis => 'ملخص';

  @override
  String get tagFields => 'حقول العلامات';

  @override
  String get tags => 'العلامات';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'انقر للبحث';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'وضع السمة';

  @override
  String get themeModeDark => 'غامق';

  @override
  String get themeModeLight => 'مضيء';

  @override
  String get themeModeSystem => 'النظام';

  @override
  String get themeSettings => 'السمة';

  @override
  String get themeSettingsSubtitle => 'الشكل العام لمشغلك';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'تحتوي قائمة التشغيل هذه على مصنفات نشطة، يرجى تعطيلها قبل إعادة الترتيب.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'من المحتمل أن يتم حذف هذا الفيديو أو تعيينه على خاص.';

  @override
  String get thumbnails => 'الصور المصغرة';

  @override
  String get title => 'العنوان';

  @override
  String get top => 'الأعلى';

  @override
  String get topComments => 'الأعلى تعليقات';

  @override
  String get topCommentsSubtitle => 'عرض التعليقات في الأعلى بدلاً من الأسفل';

  @override
  String get topRecentAlbums => 'أفضل الألبومات الأخيرة';

  @override
  String get topRecentArtists => 'أهم الفنانين الحديثين';

  @override
  String get topRecents => 'الحديثة';

  @override
  String get totalListenTime => 'إجمالي وقت الاستماع';

  @override
  String get totalListens => 'إجمالي الاستماع';

  @override
  String get totalTracks => 'إجمالي المقاطع';

  @override
  String get totalTracksDuration => 'إجمالي مدة المقاطع';

  @override
  String get track => 'مقطع';

  @override
  String get trackArtistsSeparator => 'فواصل الفنانين';

  @override
  String get trackGenresSeparator => 'فواصل الانواع';

  @override
  String get trackInfo => 'معلومات المقطع';

  @override
  String get trackNotFound => 'لم يتم العثور على المقطع';

  @override
  String get trackNumber => 'رقم المقطع';

  @override
  String get trackNumberTotal => 'إجمالي المقطع';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'الاسم القديم: \"$oldName\"\n\nالاسم الجديد: \"$newName\"\n\nهل أنت متأكد؟';
  }

  @override
  String get trackPlayMode => 'وضع التشغيل';

  @override
  String get trackPlayModeSearchResults => 'نتائج البحث';

  @override
  String get trackPlayModeSelectedOnly => 'المقاطع المحددة فقط';

  @override
  String get trackPlayModeTrackAlbum => 'البوم المقطع';

  @override
  String get trackPlayModeTrackArtist => 'الفنان الرئيسي للمقطع';

  @override
  String get trackPlayModeTrackGenre => 'نوع المقطع';

  @override
  String get trackThumbnailSizeInList => 'حجم الصورة المصغرة للمقطع';

  @override
  String get trackTileCustomization => 'تخصيص بلاط المقطع';

  @override
  String get trackTileItemsSeparator => 'فاصل العناصر';

  @override
  String get tracks => 'مقاطع';

  @override
  String get tracksExcludedByNomedia => 'المقاطع المستبعدة بواسطة .nomedia';

  @override
  String get tracksInfo => 'معلومات المقاطع';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'تراجع';

  @override
  String get undoChanges => 'تراجع عن التغييرات؟';

  @override
  String get undoChangesDeletedPlaylist => 'تراجع عن حذف قائمة التشغيل';

  @override
  String get undoChangesDeletedQueue => 'تراجع عن حذف قائمة الانتظار';

  @override
  String get undoChangesDeletedTrack => 'تراجع عن حذف المقطع';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'غير محدود';

  @override
  String get unlisted => 'غير مدرج';

  @override
  String get unlock => 'فتح القفل';

  @override
  String get update => 'تَحدِيث';

  @override
  String get updateDirectoryPath => 'تحديث مسار الدليل';

  @override
  String get updateMissingTracksOnly => 'تحديث المقاطع المفقودة فقط';

  @override
  String get updating => 'التحديث جارٍ';

  @override
  String get useCollapsedSettingTiles => 'استخدم مربعات الإعداد المطوية';

  @override
  String get useMediaStore => 'استخدم سجل الوسائط';

  @override
  String get useMediaStoreSubtitle =>
      '✓ وقت فوري للفهرسة\nx احترام .nomedia سيتم تمكينه بالقوة\nx ستكون بعض علامات البيانات التعريفية مفقودة\nxلن يعمل تكامل يوتيوب للمكتبة المحلية';

  @override
  String get usePitchBlack => 'استخدم الأسود الداكن';

  @override
  String get usePitchBlackSubtitle => 'مفيد لشاشات اموليد.. وذو مظهر رائع';

  @override
  String get used => 'مستخدم';

  @override
  String get value => 'القيمة';

  @override
  String get valueBetween50200 => 'يجب أن تكون القيمة بين 50% و200%';

  @override
  String get vibration => 'الإهتزاز';

  @override
  String get vibrationType => 'نوع الإهتزاز';

  @override
  String get video => 'فيديو';

  @override
  String get videoCache => 'ذاكرة التخزين المؤقت للفيديو';

  @override
  String get videoCacheFile => 'ملف الفيديو المخزن مؤقتا';

  @override
  String get videoCacheFiles => 'ملفات التخزين المؤقت للفيديو';

  @override
  String get videoOnly => 'الفيديوهات فقط';

  @override
  String get videoPlaybackSource => 'مصدر الفيديو';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'سيؤدي هذا إلى إعطاء الأولوية لمقاطع الفيديو المحلية، وإذا لم يتم العثور عليها، فسيتم جلبها من يوتيوب';

  @override
  String get videoPlaybackSourceLocal => 'الفيديوهات المحلية';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'آلان ووكر - باهت.m4a\nفيديو آلان ووكر - باهت (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'يتحقق مما إذا كان أي ملف فيديو (موجود داخل قائمة المجلدات المختارة) له اسم ملف يحتوي على اسم ملف المقطع';

  @override
  String get videoPlaybackSourceYoutube => 'من اليوتيوب';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'التحقق من اسم ملف المقطع والتعليق على أي رابط يوتيوب مطابق، ويتم تخزين مقاطع الفيديو مؤقتًا لاستخدامها لاحقًا.';

  @override
  String get videoQuality => 'جودة الفيديو';

  @override
  String get videoQualitySubtitle => 'سيتم اختيار أعلى جودة متاحة.';

  @override
  String get videoQualitySubtitleNote => 'من الجيد دائمًا الاحتفاظ بمزيد من البدائل في حالة عدم العثور على الجودة، وإلا فسيتم الرجوع إلى الجودة الأسوأ';

  @override
  String get videos => 'فيديوهات';

  @override
  String get view => 'شاهد';

  @override
  String get viewAll => 'عرض الكل';

  @override
  String get views => 'مشاهدات';

  @override
  String get volume => 'مستوى الصوت';

  @override
  String get warning => 'تحذير';

  @override
  String get waveformBarsCount => 'عدد أشرطة الشكل الموجي';

  @override
  String get webmNoEditTagsSupport => 'لا يدعم تنسيق WEBM تحرير العلامات';

  @override
  String get week => 'اسبوع';

  @override
  String get year => 'سنة';

  @override
  String get yes => 'نعم';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'عضويتك الحالية هي $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'سيتم فقدان طلبك المخصص، هل أنت متأكد؟';

  @override
  String get youtube => 'يوتيوب';

  @override
  String get youtubeMusic => 'موسيقى اليوتيوب';

  @override
  String get youtubeSettingsSubtitle => 'تخصيص تجربة يوتيوب';

  @override
  String get youtubeStyleMiniplayer => 'المشغل الصغير على طريقة اليوتيوب';

  @override
  String get ytPreferNewComments => 'تفضيل التعليقات الجديدة عندما يكون ذلك ممكنا';

  @override
  String get ytPreferNewCommentsSubtitle => 'سيتم استخدام النسخة المخزنة مؤقتًا فقط في حالة عدم وجود اتصال';
}
