// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Bengali Bangla (`bn`).
class AppLocalizationsBn extends AppLocalizations {
  AppLocalizationsBn([String locale = 'bn']) : super(locale);

  @override
  String get about => 'পরিচিতি';

  @override
  String get active => 'সক্রিয়';

  @override
  String get add => 'যোগ করুন';

  @override
  String get addAccount => 'অ্যাকাউন্ট যোগ করুন';

  @override
  String get addAll => 'সব যোগ করুন';

  @override
  String get addAllAndRemoveOldOnes => 'সব যোগ করুন এবং পুরনোগুলো সরিয়ে দিন';

  @override
  String get addAsANewPlaylist => 'একটি নতুন প্লেলিস্ট হিসেবে যোগ করুন';

  @override
  String get addAudioToLocalLibrary => 'লোকাল লাইব্রেরিতে অডিও যোগ করুন';

  @override
  String get addFolder => 'ফোল্ডার যোগ করুন';

  @override
  String get addLanguage => 'ভাষা যোগ করুন';

  @override
  String get addLanguageSubtitle => 'Namida-কে আপনার নিজের ভাষায় অনুবাদ করতে সাহায্য করুন';

  @override
  String get addLrcFile => 'LRC ফাইল যোগ করুন';

  @override
  String get addMoreFromThisAlbum => 'এই অ্যালবাম থেকে কিউতে আরও যোগ করুন';

  @override
  String get addMoreFromThisArtist => 'এই শিল্পী থেকে কিউতে আরও যোগ করুন';

  @override
  String get addMoreFromThisFolder => 'এই ফোল্ডার থেকে কিউতে আরও যোগ করুন';

  @override
  String addMoreFromToQueue({required String media}) {
    return '$media থেকে কিউতে আরও ট্র্যাক যোগ করুন';
  }

  @override
  String get addOnlyMissing => 'শুধু অনুপস্থিতগুলো যোগ করুন';

  @override
  String get addToFavourites => 'পছন্দের তালিকায় যোগ করুন';

  @override
  String get addToPlaylist => 'প্লেলিস্টে যোগ করুন';

  @override
  String get addTracksAtTheBeginning => 'ট্র্যাকের শুরুতে যোগ করুন';

  @override
  String get added => 'যোগ করা হয়েছে';

  @override
  String get advanced => 'উন্নত';

  @override
  String get advancedSettings => 'উন্নত সেটিংস';

  @override
  String get advancedSettingsSubtitle => 'উন্নত সেটিংস, পরিবর্তন না করাই শ্রেয়';

  @override
  String get alarm => 'অ্যালার্ম';

  @override
  String get album => 'অ্যালবাম';

  @override
  String get albumArtist => 'অ্যালবাম শিল্পী';

  @override
  String get albumArtists => 'অ্যালবাম শিল্পী';

  @override
  String get albumIdentifiers => 'অ্যালবাম সনাক্তকারী';

  @override
  String get albumThumbnailSizeInList => 'অ্যালবাম থাম্বনেইলের আকার';

  @override
  String get albumTileCustomization => 'অ্যালবাম টাইল কাস্টমাইজেশন';

  @override
  String get albums => 'অ্যালবাম';

  @override
  String get albumsCount => 'অ্যালবামের সংখ্যা';

  @override
  String get all => 'সব';

  @override
  String get allTime => 'সবসময়';

  @override
  String get alreadyExists => 'ইতিমধ্যেই বিদ্যমান';

  @override
  String get always => 'সর্বদা';

  @override
  String get alwaysAsk => 'সর্বদা জিজ্ঞাসা করুন';

  @override
  String get alwaysDim => 'সর্বদা ম্লান করুন';

  @override
  String get alwaysExpandedSearchbar => 'সর্বদা প্রসারিত সার্চবার';

  @override
  String get alwaysRestore => 'সর্বদা পুনরুদ্ধার করুন';

  @override
  String get animatingThumbnailIntensity => 'থাম্বনেইল অ্যানিমেশন তীব্রতা';

  @override
  String get animatingThumbnailInversed => 'বিপরীত অ্যানিমেশন';

  @override
  String get animatingThumbnailInversedSubtitle => 'উচ্চ বিটের সময় থাম্বনেইল ছোট হয়ে যাবে';

  @override
  String get anotherProcessIsRunning => 'অন্য একটি প্রক্রিয়া ইতিমধ্যে চলছে।';

  @override
  String get appIcon => 'অ্যাপ আইকন';

  @override
  String get appVersion => 'অ্যাপ সংস্করণ';

  @override
  String get artist => 'শিল্পী';

  @override
  String get artists => 'শিল্পী';

  @override
  String get artwork => 'আর্টওয়ার্ক';

  @override
  String get artworkGestures => 'আর্টওয়ার্ক জেসচার';

  @override
  String get artworks => 'আর্টওয়ার্ক';

  @override
  String get audio => 'অডিও';

  @override
  String get audioCache => 'অডিও ক্যাশ';

  @override
  String get audioOnly => 'শুধুমাত্র অডিও';

  @override
  String get auto => 'স্বয়ংক্রিয়';

  @override
  String get autoBackupInterval => 'স্বয়ংক্রিয় ব্যাকআপ ব্যবধান';

  @override
  String get autoColoring => 'স্বয়ংক্রিয় রঙ নির্ধারণ';

  @override
  String get autoColoringSubtitle => 'বর্তমান আর্টওয়ার্ক দ্বারা স্বয়ংক্রিয়ভাবে প্লেয়ারের রঙ নির্ধারণ করুন';

  @override
  String get autoExtractTagsFromFilename => 'ফাইলের নাম থেকে স্বয়ংক্রিয়ভাবে ট্যাগ বের করুন';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'ভিডিওর শিরোনাম থেকে স্বয়ংক্রিয়ভাবে শিরোনাম ও শিল্পী বের করুন';

  @override
  String get autoGenerated => 'স্বয়ংক্রিয়ভাবে তৈরি';

  @override
  String get autoSkip => 'স্বয়ংক্রিয়ভাবে এড়িয়ে যান';

  @override
  String get autoSkipOnce => 'স্বয়ংক্রিয়ভাবে একবার এড়িয়ে যান';

  @override
  String get autoStartRadio => 'অটো-রেডিও চালু করুন';

  @override
  String get autoStartRadioSubtitle => 'একটি একক ট্র্যাক চালানোর সময় স্বয়ংক্রিয়ভাবে একটি মিক্স প্লেলিস্ট যোগ করে';

  @override
  String get automaticBackup => 'স্বয়ংক্রিয় ব্যাকআপ';

  @override
  String get automaticBackupSubtitle => 'এটি ব্যাকআপ ফোল্ডারে থাকা সর্বশেষ ব্যাকআপ ফাইলটি স্বয়ংক্রিয়ভাবে রিস্টোর (Restore) করে';

  @override
  String get backupAndRestore => 'ব্যাকআপ ও পুনরুদ্ধার';

  @override
  String get backupAndRestoreSubtitle => 'আপনার ডাটাবেস এবং সেটিংস ব্যাকআপ করুন';

  @override
  String get balanced => 'ভারসাম্যপূর্ণ';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'তারিখের মধ্যে';

  @override
  String get bitrate => 'বিটরেট';

  @override
  String get blacklist => 'ব্ল্যাকলিস্ট';

  @override
  String get borderRadiusMultiplier => 'বর্ডার রেডিয়াস';

  @override
  String get cache => 'ক্যাশ';

  @override
  String get cancel => 'বাতিল করুন';

  @override
  String get canceled => 'বাতিল করা হয়েছে';

  @override
  String get changed => 'পরিবর্তিত';

  @override
  String get changelog => 'পরিবর্তনলিপি';

  @override
  String get changelogSubtitle => 'Namida-তে নতুন কী যোগ বা ঠিক করা হয়েছে তা দেখুন';

  @override
  String get channel => 'চ্যানেল';

  @override
  String get channels => 'চ্যানেল';

  @override
  String get check => 'চেক করুন';

  @override
  String get checkForMore => 'আরও চেক করুন';

  @override
  String get checkList => 'চেকলিস্ট';

  @override
  String get choose => 'বেছে নিন';

  @override
  String get chooseWhatToClear => 'কি সাফ করবেন তা বেছে নিন';

  @override
  String get claim => 'ক্লেইম করুন';

  @override
  String get clear => 'সাফ করুন';

  @override
  String get clearAudioCache => 'অডিওর ক্যাশ সাফ করুন';

  @override
  String get clearImageCache => 'ছবির ক্যাশ সাফ করুন';

  @override
  String get clearImageCacheWarning => 'সতর্কতা: লাইব্রেরি ট্র্যাকে কোনো আর্টওয়ার্ক থাকবে না! শুধুমাত্র ইমেজ ক্যাশ পুনরায় তৈরি করার জন্য এটি ব্যবহার করুন।';

  @override
  String get clearTrackItem => 'ট্র্যাকের বিষয়বস্তু সাফ করুন';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberStringটি ট্র্যাকের বিষয়বস্তু সাফ করুন',
      one: 'ট্র্যাকের বিষয়বস্তু সাফ করুন',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'ভিডিওর ক্যাশ সাফ করুন';

  @override
  String get clearVideoCacheNote => 'আপনি চাইলে নির্দিষ্ট ফাইল বেছে নিতে পারেন।';

  @override
  String get clock => 'ঘড়ি';

  @override
  String get colorPalette => 'কালার প্যালেট';

  @override
  String get colorPaletteNote1 => 'চাইলে লং-প্রেস করে রঙ সরিয়ে ফেলতে পারেন';

  @override
  String get colorPaletteNote2 => 'ডিফল্ট রঙ হিসেবে ব্যবহার করতে মিক্সে ট্যাপ করুন';

  @override
  String get colorPalettes => 'কালার প্যালেট';

  @override
  String get comment => 'কমেন্ট';

  @override
  String get comments => 'কমেন্ট';

  @override
  String get composer => 'সুরকার';

  @override
  String get compress => 'কমপ্রেস করুন';

  @override
  String get compressImages => 'ছবি কমপ্রেস করুন';

  @override
  String get compressionPercentage => 'কমপ্রেশন শতাংশ';

  @override
  String get configure => 'কনফিগার';

  @override
  String get confirm => 'নিশ্চিত করুন';

  @override
  String get confirmRefresh => 'আপনি কি রিফ্রেশ করতে চান?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'আর্টওয়ার্ক সংরক্ষণ করা হয়েছে';

  @override
  String get copiedToClipboard => 'ক্লিপবোর্ডে কপি করা হয়েছে';

  @override
  String get copy => 'কপি করুন';

  @override
  String get corruptedFile => 'ফাইল পার্স করা যায়নি, এটি নষ্ট হতে পারে';

  @override
  String get couldntOpen => 'খোলা যায়নি :(';

  @override
  String get couldntOpenYtLink => 'এই ট্র্যাকের জন্য কোন ইউটিউব লিঙ্ক পাওয়া যায়নি';

  @override
  String get couldntPlayFile => 'ফাইল চালানো যায়নি';

  @override
  String get couldntRenamePlaylist => 'প্লেলিস্টের নাম পরিবর্তন করা যায়নি';

  @override
  String get couldntSaveImage => 'ছবি সংরক্ষণ করা যায়নি';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি অ্যালবাম শিল্পী',
      one: '$countStringটি অ্যালবাম শিল্পী',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি অ্যালবাম',
      one: '$countStringটি অ্যালবাম',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString জন শিল্পী',
      one: '$countString জন শিল্পী',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString জন সুরকার',
      one: '$countString জন সুরকার',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString দিন',
      one: '$countString দিন',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি ফাইল',
      one: '$countStringটি ফাইল',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি ফোল্ডার',
      one: '$countStringটি ফোল্ডার',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি জনরা',
      one: '$countStringটি জনরা',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString মাস',
      one: '$countString মাস',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি প্লেলিস্ট',
      one: '$countStringটি প্লেলিস্ট',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString সাবস্ক্রাইবার',
      one: '$countString সাবস্ক্রাইবার',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString সাবস্ক্রাইবার',
      one: '$countString সাবস্ক্রাইবার',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি ট্র্যাক',
      one: '$countStringটি ট্র্যাক',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি ভিডিও',
      one: '$countStringটি ভিডিও',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString ভিউ',
      one: '$countStringটি ভিউ',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString ভিউ',
      one: '$countStringটি ভিউ',
    );
    return '$_temp0';
  }

  @override
  String get country => 'দেশ';

  @override
  String get coupon => 'কুপন';

  @override
  String get create => 'তৈরি করুন';

  @override
  String get createBackup => 'ব্যাকআপ তৈরি করুন';

  @override
  String get createNewPlaylist => 'নতুন প্লেলিস্ট তৈরি করুন';

  @override
  String get createdBackupSuccessfully => 'ব্যাকআপ তৈরি করা হয়েছে';

  @override
  String get createdBackupSuccessfullySub => 'ব্যাকআপ ফাইল সফলভাবে তৈরি করা হয়েছে';

  @override
  String get crossPlatformSync => 'ক্রস-প্ল্যাটফর্ম সিঙ্ক';

  @override
  String get crossfadeDuration => 'ক্রসফেড সময়কাল';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'শেষ $secondsString সেকেন্ডে স্বয়ংক্রিয়ভাবে ক্রসফেড ট্রিগার করুন',
      one: 'শেষ $secondsString সেকেন্ডে স্বয়ংক্রিয়ভাবে ক্রসফেড ট্রিগার করুন',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'স্বয়ংক্রিয়ভাবে ক্রসফেড ট্রিগার করবেন না';

  @override
  String get custom => 'কাস্টম';

  @override
  String get customizations => 'কাস্টমাইজেশন';

  @override
  String get customizationsSubtitle => 'Namida-কে আপনার নিজের মতো করে কাস্টমাইজ করুন';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'ডেটা সরবরাহকারী: $name';
  }

  @override
  String get dataSaver => 'ডেটা সেভার';

  @override
  String get dataSaverMode => 'ডেটা সেভার মোড';

  @override
  String get database => 'ডাটাবেস';

  @override
  String get date => 'তারিখ';

  @override
  String get dateAdded => 'যোগ করার তারিখ';

  @override
  String get dateCreated => 'তৈরির তারিখ';

  @override
  String get dateModified => 'পরিবর্তনের তারিখ';

  @override
  String get dateTimeFormat => 'তারিখ ও সময়ের ফরম্যাট';

  @override
  String get day => 'দিন';

  @override
  String get days => 'দিন';

  @override
  String get defaultBackupLocation => 'ডিফল্ট ব্যাকআপ অবস্থান';

  @override
  String get defaultColor => 'ডিফল্ট রঙ';

  @override
  String get defaultColorSubtitle => 'প্লেয়ারে ব্যবহৃত হওয়ার জন্য একটি রঙ নির্ধারণ করুন';

  @override
  String get defaultDownloadLocation => 'ডিফল্ট ডাউনলোড এর অবস্থান';

  @override
  String get defaultLabel => 'ডিফল্ট';

  @override
  String get defaultLibraryTab => 'ডিফল্ট লাইব্রেরি ট্যাব';

  @override
  String get delete => 'ডিলিট করুন';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countStringটি ফাইল, যার মোট সাইজ $totalSizeText, ডিলিট করবেন?',
      one: '$countStringটি ফাইল, যার মোট সাইজ $totalSizeText, ডিলিট করবেন?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'নিশ্চিত করুন, আপনি কি স্থায়ীভাবে $numberText ডিলিট করতে চান';
  }

  @override
  String get deletePlaylist => 'প্লেলিস্ট ডিলিট করুন';

  @override
  String get deleteTempFiles => 'অস্থায়ী ফাইল ডিলিট করুন';

  @override
  String get deleted => 'ডিলিট করা হয়েছে';

  @override
  String get description => 'বর্ণনা';

  @override
  String get developer => 'ডেভেলপার';

  @override
  String get development => 'ডেভেলপমেন্ট';

  @override
  String get didYouMean => 'আপনি কি বোঝাতে চেয়েছেন';

  @override
  String get dimIntensity => 'ম্লান করার তীব্রতা';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString সেকেন্ড নিষ্ক্রিয় থাকার পর মিনিপ্লেয়ার ম্লান করুন',
      one: '$secondsString সেকেন্ড নিষ্ক্রিয় থাকার পর মিনিপ্লেয়ার ম্লান করুন',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'ডিরেক্টরির অস্তিত্ব নেই';

  @override
  String get disable => 'নিষ্ক্রিয় করুন';

  @override
  String get disableAll => 'সব নিষ্ক্রিয় করুন';

  @override
  String get disableReordering => 'পুনর্বিন্যাস নিষ্ক্রিয় করুন';

  @override
  String get disableSearchCleanup => 'সার্চ ক্লিনআপ নিষ্ক্রিয় করুন';

  @override
  String get discNumber => 'ডিস্ক নম্বর';

  @override
  String get discNumberTotal => 'মোট ডিস্ক সংখ্যা';

  @override
  String get discover => 'ডিসকভার';

  @override
  String get dislike => 'ডিসলাইক';

  @override
  String get dismissibleMiniplayer => 'খারিজযোগ্য মিনিপ্লেয়ার';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'সিক করার সময় পার্থক্যের পরিবর্তে প্রকৃত অবস্থান প্রদর্শন করুন';

  @override
  String get displayAlbumCardTopRightDate => 'অ্যালবাম কার্ডের উপরের ডানদিকের তারিখ';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'অ্যালবাম কার্ডের উপরে ডানদিকে অ্যালবামের তারিখ প্রদর্শন করুন';

  @override
  String get displayArtistBeforeTitle => 'শিরোনামের উপরে শিল্পী প্রদর্শন করুন';

  @override
  String get displayArtworkOnLockscreen => 'লকস্ক্রিনে আর্টওয়ার্ক প্রদর্শন করুন';

  @override
  String get displayAudioInfoInMiniplayer => 'অডিওর তথ্য প্রদর্শন করুন';

  @override
  String get displayFavButtonInNotification => 'নোটিফিকেশনে \'লাইক\' বাটন দেখান';

  @override
  String get displayFavButtonInNotificationSubtitle => 'থাম্বনেইল স্থানচ্যুত হতে পারে।';

  @override
  String get displayFavouriteIconInTrackTile => '\'লাইক\' বাটন দেখান';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'মোট সময়ের পরিবর্তে অবশিষ্ট সময় প্রদর্শন করুন';

  @override
  String get displayStopButtonInNotification => 'নোটিফিকেশনে \'স্টপ\' বাটন দেখান';

  @override
  String get displayThirdItemInRowInTrackTile => 'প্রতিটি সারিতে তৃতীয় আইটেম প্রদর্শন করুন';

  @override
  String get displayThirdRowInTrackTile => 'ট্র্যাক বক্সে তৃতীয় সারি প্রদর্শন করুন';

  @override
  String get displayTrackNumberInAlbumPage => 'অ্যালবাম পেজে ট্র্যাক নম্বর প্রদর্শন করুন';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'অ্যালবাম পেজে ট্র্যাক নম্বর সম্বলিত একটি ছোট বাক্স প্রদর্শন করুন';

  @override
  String get doNothing => 'কিছুই করবে না';

  @override
  String get donate => 'অনুদান দিন';

  @override
  String get donateSubtitle => 'অ্যাপটি আরও উন্নত করতে অনুদান দিতে পারেন';

  @override
  String get done => 'সম্পন্ন';

  @override
  String get dontAskAgain => 'আর জিজ্ঞাসা করবেন না';

  @override
  String get dontDim => 'ম্লান করবেন না';

  @override
  String get dontRestorePosition => 'পুনরুদ্ধার করবেন না';

  @override
  String get dontResume => 'পুনরায় শুরু করবেন না';

  @override
  String get doubleTapToToggleLyrics => 'আর্টওয়ার্কে ডাবল ট্যাপ করে লিরিক্স দেখুন';

  @override
  String get download => 'ডাউনলোড';

  @override
  String get downloadingWillOverrideIt => 'ডাউনলোড করলে এটি ওভাররাইড করবে';

  @override
  String get downloads => 'ডাউনলোড';

  @override
  String get downloadsMetadataTags => 'মেটাডেটা ট্যাগ ডাউনলোড করুন';

  @override
  String get downloadsMetadataTagsSubtitle => 'ডিফল্টভাবে ভিডিও তথ্য থেকে শিল্পী, শিরোনাম ও অ্যালবাম বের করুন';

  @override
  String get dragToSeek => 'সিক করতে টেনে আনুন';

  @override
  String get duckAudio => 'অডিও ধীর করুন';

  @override
  String get duplicatedItemsAdding => 'আপনি এমন কিছু আইটেম যোগ করার চেষ্টা করছেন যা ইতিমধ্যে এই প্লেলিস্টে বিদ্যমান';

  @override
  String get duplicatedTracks => 'ডুপ্লিকেট ট্র্যাক';

  @override
  String get duration => 'সময়কাল';

  @override
  String get edgeColorsSwitching => 'এজ কালার সুইচিং';

  @override
  String get edit => 'সম্পাদনা';

  @override
  String get editArtwork => 'আর্টওয়ার্ক সম্পাদনা করুন';

  @override
  String get editTags => 'ট্যাগ সম্পাদনা করুন';

  @override
  String get email => 'ইমেইল';

  @override
  String get emptyNonMeaningfulTagFields => 'আপনার কাছে খালি মানসহ ফিল্ড রয়েছে, নিশ্চিত করুন যে আপনি সত্যিই সেগুলো সম্পাদনা করতে চান';

  @override
  String get emptyValue => 'খালি মান';

  @override
  String get enableArtworkCache => 'আর্টওয়ার্ক ক্যাশ সক্রিয় করুন';

  @override
  String get enableArtworkCacheSubtitle => 'দ্রুত লোডিং এবং উন্নত পারফরম্যান্স, তবে বেশি স্টোরেজ ব্যবহার করে';

  @override
  String get enableBlurEffect => 'ব্লার ইফেক্ট সক্রিয় করুন';

  @override
  String get enableBottomNavBar => 'নিচের নেভিগেশন বার সক্রিয় করুন';

  @override
  String get enableBottomNavBarSubtitle => 'আইটেমগুলো উভয় উপায়ে ড্রয়ারের ভিতরে রয়েছে';

  @override
  String get enableClipboardMonitoring => 'ক্লিপবোর্ড মনিটরিং সক্রিয় করুন';

  @override
  String get enableClipboardMonitoringSubtitle => 'সার্চবারে লিঙ্ক এবং টেক্সট পেস্ট করতে দেয়';

  @override
  String get enableCrossfadeEffect => 'ক্রসফেড ইফেক্ট সক্রিয় করুন';

  @override
  String get enableFadeEffectOnPlayPause => 'ফেড ইফেক্ট সক্রিয় করুন';

  @override
  String get enableFoldersHierarchy => 'ফোল্ডার হায়ারার্কি';

  @override
  String get enableGlowEffect => 'গ্লো ইফেক্ট সক্রিয় করুন';

  @override
  String get enableM3uSync => 'M3U সিঙ্ক সক্রিয় করুন';

  @override
  String get enableM3uSyncNote1 => 'M3U সিঙ্ক প্লেলিস্টের পরিবর্তন মূল M3U ফাইলে সংরক্ষণ করতে দেয়';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'কিছু ভুল হলে, এই প্লেলিস্টের একটি ব্যাকআপ ফাইল $playlistsBackupPath এ পাওয়া যাবে';
  }

  @override
  String get enableM3uSyncSubtitle => 'যদি অস্বীকার করা হয়, এই প্লেলিস্টে করা সমস্ত পরিবর্তন পুনরায় চালু করার সময় হারিয়ে যাবে';

  @override
  String get enableMiniplayerParticles => 'উড়ন্ত কণা সক্রিয় করুন';

  @override
  String get enableParallaxEffect => 'প্যারালাক্স ইফেক্ট সক্রিয় করুন';

  @override
  String get enablePartyMode => 'পার্টি মোড সক্রিয় করুন';

  @override
  String get enablePartyModeSubtitle => 'অলঙ্কৃত এজ ব্রিদিং ইফেক্ট প্রয়োগ করুন';

  @override
  String get enablePictureInPicture => 'পিকচার-ইন-পিকচার সক্রিয় করুন';

  @override
  String get enableReordering => 'পুনর্বিন্যাস সক্রিয় করুন';

  @override
  String get enableReturnYoutubeDislike => 'রিটার্ন ইউটিউব ডিসলাইক সক্রিয় করুন';

  @override
  String get enableSearchCleanup => 'সার্চ ক্লিনআপ সক্রিয় করুন';

  @override
  String get enableSearchCleanupSubtitle => 'সমস্ত চিহ্ন এবং স্পেস উপেক্ষা করা হবে';

  @override
  String get enableSponsorblock => 'স্পন্সরব্লক সক্রিয় করুন';

  @override
  String get enableVideoPlayback => 'ভিডিও প্লেব্যাক সক্রিয় করুন';

  @override
  String get enterSymbol => 'দয়া করে একটি চিহ্ন দিন';

  @override
  String get equalizer => 'ইকুয়ালাইজার';

  @override
  String get error => 'ত্রুটি';

  @override
  String get errorFetchingVideoList => 'ভিডিও তালিকা আনতে সমস্যা হচ্ছে';

  @override
  String get errorPlayingTrack => 'ট্র্যাক চালাতে ত্রুটি';

  @override
  String get excludedFodlers => 'বর্জিত ফোল্ডার';

  @override
  String get exit => 'প্রস্থান';

  @override
  String get exitAppSubtitle => 'প্রস্থান করতে আবার ট্যাপ করুন';

  @override
  String get expandedMiniplayer => 'প্রসারিত মিনিপ্লেয়ার';

  @override
  String get exportAsM3u => 'M3U হিসাবে এক্সপোর্ট করুন';

  @override
  String get extension => 'এক্সটেনশন';

  @override
  String get externalFiles => 'বাহ্যিক ফাইল';

  @override
  String get extract => 'এক্সট্র্যাক্ট করুন';

  @override
  String get extractAllColorPalettes => 'সব কালার প্যালেট এক্সট্র্যাক্ট করুন';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberStringটি প্যালেট বাকি আছে, এক্সট্র্যাক্ট করবেন?',
      one: '$numberStringটি প্যালেট বাকি আছে, এক্সট্র্যাক্ট করবেন?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'শিরোনাম থেকে শিল্পী বের করুন';

  @override
  String get extractFeatArtistSubtitle => '(feat. X) এবং (ft. X) শিল্পীগুলোকে একটি নতুন শিল্পী এন্ট্রি হিসেবে বের করে।';

  @override
  String get extractingInfo => 'তথ্য এক্সট্র্যাক্ট করা হচ্ছে';

  @override
  String get extras => 'অতিরিক্ত';

  @override
  String get extrasSubtitle => 'আপনার অভিজ্ঞতা ঠিক করতে অতিরিক্ত সেটিংস';

  @override
  String get extreme => 'উচ্চ';

  @override
  String get failed => 'ব্যর্থ হয়েছে';

  @override
  String get failedEdits => 'ব্যর্থ সম্পাদনাগুলো';

  @override
  String get favourites => 'পছন্দের তালিকা';

  @override
  String get features => 'ফিচার';

  @override
  String get fetching => 'লোড হচ্ছে';

  @override
  String get fetchingOfAllVideos => 'সব ভিডিও লোড করা হচ্ছে';

  @override
  String get file => 'ফাইল';

  @override
  String get fileAlreadyExists => 'ফাইল ইতিমধ্যে বিদ্যমান';

  @override
  String get fileBasedServerWarning =>
      'ইনডেক্সিং (Indexing) করার জন্য ফাইলগুলো সাময়িকভাবে ডাউনলোড করা হবে।\nনিশ্চিত করুন আপনার ইন্টারনেট সংযোগ স্থিতিশীল আছে। অতিরিক্ত ডেটা খরচ এড়াতে ওয়াই-ফাই (Wi-Fi) ব্যবহার করুন।';

  @override
  String get fileName => 'ফাইলের নাম';

  @override
  String get fileNameWoExt => 'এক্সটেনশন ছাড়া ফাইলের নাম';

  @override
  String get filenameShouldntStartWith => 'ফাইলের নাম এটা দিয়ে শুরু হওয়া উচিত নয়';

  @override
  String get files => 'ফাইল';

  @override
  String get filler => 'ফিলার';

  @override
  String get filterAlbums => 'অ্যালবাম ফিল্টার করুন';

  @override
  String get filterArtists => 'শিল্পী ফিল্টার করুন';

  @override
  String get filterGenres => 'জনরা ফিল্টার করুন';

  @override
  String get filterPlaylists => 'প্লেলিস্ট ফিল্টার করুন';

  @override
  String get filterTracks => 'ট্র্যাক ফিল্টার করুন';

  @override
  String get filterTracksBy => 'অনুসন্ধান তালিকায় ট্র্যাক ফিল্টার করুন';

  @override
  String get filtered => 'ফিল্টার করা হয়েছে';

  @override
  String get filteredBySizeAndDuration => 'সাইজ এবং সময়কাল দ্বারা ফিল্টার করা ট্র্যাক';

  @override
  String get finished => 'সম্পন্ন হয়েছে';

  @override
  String get finishedUpdatingLibrary => 'লাইব্রেরি আপডেট সম্পন্ন হয়েছে';

  @override
  String get firstListen => 'প্রথম শ্রবণ';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp বড় থাম্বনেইল সাইজ ঠিক করুন';

  @override
  String get floatingActionButton => 'ভাসমান অ্যাকশন বাটন';

  @override
  String get folder => 'ফোল্ডার';

  @override
  String get folderName => 'ফোল্ডারের নাম';

  @override
  String get folders => 'ফোল্ডার';

  @override
  String get fontScale => 'ফন্ট স্কেল';

  @override
  String get forceMiniplayerFollowTrackColors => 'মিনিপ্লেয়ারকে ট্র্যাকের রঙ অনুসরণ করতে বাধ্য করুন';

  @override
  String get forceSquaredAlbumThumbnail => 'সকল অ্যালবাম থাম্বনেইল বর্গাকার করুন';

  @override
  String get forceSquaredThumbnailNote => 'থাম্বনেইল ও টাইলের মাপ সমান নয়, তাই এটি বর্গাকার দেখাবে না। আপনি কি এগুলো সমান করতে চান?';

  @override
  String get forceSquaredTrackThumbnail => 'সকল ট্র্যাক থাম্বনেইল বর্গাকার করুন';

  @override
  String get forceStopColorPaletteGeneration => 'কালার প্যালেট এক্সট্র্যাক্ট করা বন্ধ করবেন? আপনি পরে এটি আবার চালিয়ে যেতে পারবেন';

  @override
  String get format => 'ফরম্যাট';

  @override
  String get fullscreen => 'ফুলস্ক্রিন';

  @override
  String get gaplessPlayback => 'বিরতিহীন প্লেব্যাক';

  @override
  String get generate => 'তৈরি করুন';

  @override
  String get generateFromDates => 'সময় অনুযায়ী';

  @override
  String get generateFromDatesSubtitle => 'আপনার একটি সময় পরিসীমায় শোনা ট্র্যাকগুলো যোগ করুন';

  @override
  String get generateRandomPlaylist => 'এলোমেলো প্লেলিস্ট তৈরি করুন';

  @override
  String get genre => 'জনরা';

  @override
  String get genres => 'জনরা';

  @override
  String get goToAlbum => 'অ্যালবামে যান';

  @override
  String get goToArtist => 'শিল্পীতে যান';

  @override
  String get goToChannel => 'চ্যানেলে যান';

  @override
  String get goToFolder => 'ফোল্ডারে যান';

  @override
  String get goodLooking => 'আকর্ষণীয়';

  @override
  String get grantStoragePermission => 'স্টোরেজ পারমিশন দিন';

  @override
  String get group => 'গ্রুপ';

  @override
  String get groupArtworksByAlbum => 'অ্যালবাম দ্বারা আর্টওয়ার্ক গ্রুপ করুন';

  @override
  String get guide => 'গাইড';

  @override
  String get hapticFeedback => 'হ্যাপটিক ফিডব্যাক';

  @override
  String get heightOfAlbumTile => 'অ্যালবাম টাইলের উচ্চতা';

  @override
  String get heightOfTrackTile => 'ট্র্যাক টাইলের উচ্চতা';

  @override
  String get hideSkipButtonAfter => 'এরপর \'স্কিপ\' বাটন লুকান';

  @override
  String get highMatches => 'সর্বোচ্চ মিল';

  @override
  String get highPerformance => 'সর্বোচ্চ কার্যক্ষমতা';

  @override
  String get highlight => 'হাইলাইট';

  @override
  String get history => 'ইতিহাস';

  @override
  String get historyImportMissingEntriesNote => 'এই এন্ট্রিগুলো লাইব্রেরিতে খুঁজে পাওয়া যায়নি। যদি নিশ্চিত হন যে এগুলো বিদ্যমান, তবে দয়া করে ম্যানুয়ালি যোগ করুন';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString বার শ্রবণ $oldTrackInfo এর সাথে প্রতিস্থাপিত হবে $newTrackInfo, নিশ্চিত?',
      one: '$listensCountString বার শ্রবণ $oldTrackInfo এর সাথে প্রতিস্থাপিত হবে $newTrackInfo, নিশ্চিত?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'হোম';

  @override
  String get hook => 'আকর্ষণ';

  @override
  String get host => 'হোস্ট';

  @override
  String get hourFormat12 => '১২ ঘণ্টার ফরম্যাট';

  @override
  String get hours => 'ঘণ্টা';

  @override
  String get iReadAndAgree => 'আমি পড়েছি এবং সম্মত';

  @override
  String get ifNotPlaying => 'যদি চালানো না হয়';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'অ্যাপ ব্যাটারি সীমাবদ্ধ থাকলে ডাউনলোড গতি কমে যেতে পারে';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'সাধারণ উপসর্গগুলো উপেক্ষা করুন';

  @override
  String get ignores => 'উপেক্ষা';

  @override
  String get imageSource => 'ছবির উৎস';

  @override
  String get immersiveMode => 'ইমারসিভ মোড';

  @override
  String get immersiveModeSubtitle => 'মিনিপ্লেয়ার প্রসারিত থাকাকালীন স্ট্যাটাস এবং নেভিগেশন বার লুকান';

  @override
  String get import => 'ইম্পোর্ট';

  @override
  String get importAll => 'সব ইম্পোর্ট করুন';

  @override
  String get importLastFmHistory => 'LastFm ইতিহাস ইম্পোর্ট করুন';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. $lastfmCsvLink -এ যান।\n\n2. আপনার ইউজারনেম লিখুন, তথ্যগুলো সংগ্রহ করুন এবং সিএসভি (csv) ফাইলটি ডাউনলোড করুন।\n\n3. পরবর্তী স্ক্রিন থেকে ফাইলটি নির্বাচন করুন।';
  }

  @override
  String get importTimeRange => 'সময়সীমা ইমপোর্ট করুন';

  @override
  String get importYoutubeHistory => 'ইউটিউব ইতিহাস ইম্পোর্ট করুন';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. $takeoutLink -এ যান।\n\n2. \"Multiple Formats\" -এ ক্লিক করুন এবং \"History\"-এর পাশে \"JSON\" অপশনটি বেছে নিন।\n\n3. \"All Youtube data included\" -এ ক্লিক করে সব ডি-সিলেক্ট (Deselect) করুন এবং শুধু \"history\" সিলেক্ট করুন।\n\n4. এক্সপোর্ট তৈরি করে ফাইলটি ডাউনলোড এবং আনজিপ (Unzip) করুন।\n\n5. পরবর্তী স্ক্রিন থেকে \"watch-history.json\" ফাইলটি বেছে নিন।';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberStringটি চ্যানেল সফলভাবে ইম্পোর্ট করা হয়েছে',
      one: '$numberStringটি চ্যানেল সফলভাবে ইম্পোর্ট করা হয়েছে',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'সফলভাবে $numberTextটি প্লেলিস্ট ইম্পোর্ট করা হয়েছে',
      one: 'সফলভাবে $numberTextটি প্লেলিস্ট ইম্পোর্ট করা হয়েছে',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'ভিডিও অন্তর্ভুক্ত করুন';

  @override
  String get indexRefreshRequired => 'পরিবর্তনের পর একবার রিফ্রেশ করুন';

  @override
  String get indexer => 'ইনডেক্সার';

  @override
  String get indexerNote => 'দ্রষ্টব্য: ‘অসম্পূর্ণ সংখ্যক আর্টওয়ার্ক’ বলতে ডুপ্লিকেট এবং খুঁজে না পাওয়া আর্টওয়ার্কগুলোকে বোঝায়';

  @override
  String get indexerSubtitle => 'আপনার সঙ্গীত লাইব্রেরি নিয়ন্ত্রন করুন';

  @override
  String get infinityQueueOnNextPrev => 'পরবর্তী/পূর্ববর্তীতে ইনফিনিটি কিউ';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'শেষ ট্র্যাক চালানোর সময় \'পরবর্তী\' বাটন চাপলে প্রথম ট্র্যাকে চলে যাবে, এবং তদ্বিপরীত';

  @override
  String get info => 'তথ্য';

  @override
  String get inserted => 'যোগ করা হয়েছে';

  @override
  String get instantlyApplies => 'তাৎক্ষণিকভাবে প্রযোজ্য';

  @override
  String get interactionReminder => 'ইন্টারঅ্যাকশন রিমাইন্ডার';

  @override
  String get intro => 'সূচনা';

  @override
  String get invertSelection => 'নির্বাচন বিপরীত করুন';

  @override
  String get issues => 'সমস্যা';

  @override
  String get item => 'আইটেম';

  @override
  String get jump => 'যান';

  @override
  String get jumpToDay => 'দিনে যান';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'কিউ শেষ হওয়ার পর প্রথম ট্র্যাকে চলে যান';

  @override
  String get keepCachedVersions => 'ক্যাশ সংস্করণ রাখুন';

  @override
  String get keepFileDates => 'ফাইলের তারিখ রাখুন';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'যখন মিনিপ্লেয়ার প্রসারিত থাকবে';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'যখন মিনিপ্লেয়ার প্রসারিত থাকবে এবং ভিডিও চালাবে';

  @override
  String get keepScreenAwakeNone => 'স্ক্রিন চালু রাখবেন না';

  @override
  String get keepScreenAwakeWhen => 'স্ক্রিন চালু রাখুন';

  @override
  String get killPlayerAfterDismissingApp => 'অ্যাপ খারিজ করার পর প্লেয়ার বন্ধ করুন';

  @override
  String get language => 'ভাষা';

  @override
  String get learnMore => 'আরও জানুন';

  @override
  String get leftAction => 'বাম দিকের অ্যাকশন';

  @override
  String get legacyAuthentication => 'লিগ্যাসি অথেন্টিকেশন';

  @override
  String get libraryTabs => 'লাইব্রেরি ট্যাব';

  @override
  String get libraryTabsReorder => 'আপনি সক্রিয় ট্যাবগুলো পুনর্বিন্যাস করতে পারেন।';

  @override
  String get license => 'লাইসেন্স';

  @override
  String get licenseSubtitle => 'Namida-তে ব্যবহৃত লাইসেন্স এবং চুক্তিসমূহ দেখুন';

  @override
  String get like => 'লাইক';

  @override
  String get liked => 'লাইক করা হয়েছে';

  @override
  String get link => 'লিঙ্ক';

  @override
  String get listOfFolders => 'নির্বাচিত ফোল্ডার';

  @override
  String get loadAll => 'সব লোড করুন';

  @override
  String get loadingFile => 'ফাইল লোড হচ্ছে';

  @override
  String get local => 'স্থানীয়';

  @override
  String get localVideoMatching => 'স্থানীয় ভিডিও ম্যাচিং';

  @override
  String get login => 'লগইন';

  @override
  String get longPressAction => 'লং-প্রেস অ্যাকশন';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'ফুলস্ক্রিনে লিরিক্স দেখতে লং-প্রেস করুন';

  @override
  String get lostMemories => 'হারানো স্মৃতি';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString বছর আগে, প্রায় এই সময়ে শোনা হয়েছে ',
      one: '$numberString বছর আগে, প্রায় এই সময়ে শোনা হয়েছে ',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'পুরনো সাথী';

  @override
  String get loudnessEnhancer => 'লাউডনেস এনহ্যান্সার';

  @override
  String get lyricist => 'গীতিকার';

  @override
  String get lyrics => 'লিরিক্স';

  @override
  String get lyricsSource => 'লিরিক্সের উৎস';

  @override
  String get m3uPlaylist => 'M3U প্লেলিস্ট';

  @override
  String get makeYourFirstListen => 'আপনার প্রথম শ্রবণ এ পরিণত করুন!';

  @override
  String get manage => 'পরিচালনা করুন';

  @override
  String get manageYourAccounts => 'আপনার অ্যাকাউন্ট পরিচালনা করুন';

  @override
  String get manualBackup => 'ম্যানুয়াল';

  @override
  String get manualBackupSubtitle => 'একটি নির্দিষ্ট ফাইল নির্বাচন করুন';

  @override
  String get markAsRead => 'পড়া হয়েছে হিসাবে চিহ্নিত করুন';

  @override
  String get matchAllTracks => 'সমস্ত ট্র্যাক ম্যাচ করুন';

  @override
  String get matchAllTracksNote => 'এটি ম্যাচিং গতিতে প্রভাব ফেলতে পারে, কারণ এটি আপনার লাইব্রেরির সমস্ত ট্র্যাক চেক করবে';

  @override
  String get matchingType => 'ম্যাচিং এর ধরন';

  @override
  String get maxAudioCacheSize => 'সর্বোচ্চ অডিওর ক্যাশ';

  @override
  String get maxImageCacheSize => 'সর্বোচ্চ ছবির ক্যাশ';

  @override
  String get maxVideoCacheSize => 'সর্বোচ্চ ভিডিওর ক্যাশ';

  @override
  String get maximum => 'সর্বোচ্চ';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'মিডিয়া স্টোর সক্রিয়, এর কোন প্রভাব থাকবে না';

  @override
  String get medium => 'মধ্যম';

  @override
  String get membershipCode => 'কোড';

  @override
  String get membershipCodeSentToEmail => 'আপনার ইমেইলে কোড পাঠানো হয়েছে';

  @override
  String get membershipDidntChange => 'সদস্যপদ পরিবর্তন হয়নি';

  @override
  String get membershipEnjoyNew => 'আপনার নতুন সদস্যপদ উপভোগ করুন';

  @override
  String get membershipFreeCoupon => 'ফ্রি কুপন';

  @override
  String get membershipManage => 'আপনার সদস্যপদ পরিচালনা করুন';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'এই ব্যবহারকারীর জন্য কোন সাবস্ক্রিপশন পাওয়া যায়নি';

  @override
  String get membershipSignInToPatreonAccount => 'আপনার প্যাট্রিয়ন অ্যাকাউন্টে সাইন ইন করুন';

  @override
  String get membershipUnknown => 'অজানা সদস্যপদ';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'একাধিক অ্যাকাউন্ট যোগ করতে আপনার $name1 বা $name2 এর সদস্যপদ প্রয়োজন';
  }

  @override
  String get merge => 'একত্রিত করুন';

  @override
  String get metadataCache => 'মেটাডেটা ক্যাশ';

  @override
  String get metadataEditFailed => 'মেটাডেটা সম্পাদনা ব্যর্থ হয়েছে';

  @override
  String get metadataReadFailed => 'মেটাডেটা পড়া ব্যর্থ হয়েছে';

  @override
  String get minFileDuration => 'সর্বনিম্ন ট্র্যাক সময়কাল';

  @override
  String get minFileSize => 'সর্বনিম্ন ফাইল সাইজ';

  @override
  String get minTrackDurationToRestoreLastPosition => 'শেষবার শ্রবণের অবস্থান পুনরুদ্ধার করতে সর্বনিম্ন ট্র্যাক সময়কাল';

  @override
  String get minValueCantBeMoreThanMax => 'সর্বনিম্ন মান সর্বোচ্চ মানের চেয়ে বেশি হতে পারে না';

  @override
  String get minValueToCountTrackListen => 'কতটুকু শোনা হলে শ্রবণ হিসেবে গণনা করা হবে ';

  @override
  String get minimizedMiniplayer => 'সঙ্কুচিত মিনিপ্লেয়ার';

  @override
  String get minimum => 'সর্বনিম্ন';

  @override
  String get minimumOneFolderSubtitle => 'কমপক্ষে একটি ফোল্ডার থাকা উচিত, আপনি যদি এটি সরাতে চান তবে আরও ফোল্ডার যোগ করুন';

  @override
  String get minimumOneItem => 'আইটেম সরানো যায়নি';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'কমপক্ষে $numberStringটি আইটেম অবশিষ্ট থাকা উচিত',
      one: 'কমপক্ষে $numberStringটি আইটেম অবশিষ্ট থাকা উচিত',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'সর্বনিম্ন সেগমেন্ট সময়কাল';

  @override
  String get miniplayerCustomization => 'মিনিপ্লেয়ার কাস্টমাইজেশন';

  @override
  String get minutes => 'মিনিট';

  @override
  String get missingEntries => 'অনুপস্থিত এন্ট্রি';

  @override
  String get missingTracks => 'অনুপস্থিত ট্র্যাক';

  @override
  String get mix => 'মিক্স';

  @override
  String get mixPlaylistGeneratedByYoutube => 'ইউটিউব দ্বারা তৈরি মিক্স প্লেলিস্ট';

  @override
  String get mixes => 'মিক্স';

  @override
  String get mobile => 'মোবাইল';

  @override
  String get month => 'মাস';

  @override
  String get months => 'মাস';

  @override
  String get mood => 'মুড';

  @override
  String get moods => 'মুড';

  @override
  String get more => 'আরও';

  @override
  String get mostPlayed => 'সবচেয়ে বেশি শোনা';

  @override
  String get multipleTracksTagsEditNote => 'আপনি এই ট্র্যাকগুলো সম্পাদনা করতে চলেছেন, \nঅপরিবর্তিত ক্ষেত্রগুলো একই থাকবে।';

  @override
  String get musicOfftopic => 'মিউজিক অফটপিক';

  @override
  String get name => 'নাম';

  @override
  String get nameContainsBadCharacter => 'নামে অগ্রহণযোগ্য অক্ষর রয়েছে';

  @override
  String get never => 'কখনো না';

  @override
  String get newDirectory => 'নতুন ডিরেক্টরি';

  @override
  String get newLabel => 'নতুন';

  @override
  String get newTracksAdd => 'ট্র্যাক যোগ করুন';

  @override
  String get newTracksMoods => 'মুড অনুযায়ী';

  @override
  String get newTracksMoodsSubtitle => 'নির্দিষ্ট মুডের ট্র্যাক যোগ করুন';

  @override
  String get newTracksRandom => 'এলোমেলো';

  @override
  String get newTracksRandomSubtitle => 'লাইব্রেরি থেকে এলোমেলোভাবে ট্র্যাক যোগ করুন';

  @override
  String get newTracksRatings => 'রেটিং অনুযায়ী';

  @override
  String get newTracksRatingsSubtitle => 'নির্দিষ্ট রেটিংয়ের ট্র্যাক যোগ করুন';

  @override
  String get newTracksRecommended => 'সুপারিশকৃত';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return '$currentTrack এর সাথে সম্পর্কিত ট্র্যাকগুলো যোগ করুন';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'সমসাময়িক';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return '$currentTrack এর কাছাকাছি সময়ে মুক্তিপ্রাপ্ত ট্র্যাকগুলো যোগ করুন';
  }

  @override
  String get newTracksUnknownYear => 'ট্র্যাকের বছর অজানা';

  @override
  String get newest => 'নতুন';

  @override
  String get next => 'পরবর্তী';

  @override
  String get no => 'না';

  @override
  String get noChangesFound => 'কোনো পরিবর্তন পাওয়া যায়নি।';

  @override
  String get noEnoughTracks => 'আপনার কাছে যথেষ্ট ট্র্যাক নেই..';

  @override
  String get noExcludedFolders => 'আপনার কাছে কোন বর্জিত ফোল্ডার নেই';

  @override
  String get noFolderChosen => 'আপনি কোনো ফোল্ডার নির্বাচন করেননি';

  @override
  String get noMoodsAvailable => 'কোনো মুড উপলভ্য নেই';

  @override
  String get noNetworkAvailableToFetchData => 'কোন নেটওয়ার্ক কানেকশন উপলভ্য নেই';

  @override
  String get noTracksFound => 'কোনো ট্র্যাক পাওয়া যায়নি';

  @override
  String get noTracksFoundBetweenDates => 'এই সময় পরিসীমায় কোন ট্র্যাক নেই।';

  @override
  String get noTracksFoundInDirectory => 'এই ডিরেক্টরিতে কোন ট্র্যাক পাওয়া যায়নি';

  @override
  String get noTracksInHistory => 'আপনার ইতিহাসে পর্যাপ্ত ট্র্যাক নেই';

  @override
  String get nonActive => 'নিষ্ক্রিয়';

  @override
  String get nonFavourites => 'পছন্দের তালিকাভুক্ত নয়';

  @override
  String get none => 'কোনোটিই নয়';

  @override
  String get normalizeAudio => 'অডিও স্বাভাবিক করুন';

  @override
  String get normalizeAudioSubtitle => 'রিপ্লে গেইন ট্যাগ (Replay Gain) বা ইউটিউবের তথ্য অনুযায়ী ভলিউম স্বাভাবিক করে';

  @override
  String get notAvailableForYourDevice => 'আপনার ডিভাইসের জন্য উপলভ্য নয়';

  @override
  String get notSupportedForNetworkFiles => 'নেটওয়ার্ক ফাইলের জন্য সমর্থিত নয়';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'দ্রষ্টব্য';

  @override
  String get notification => 'নোটিফিকেশন';

  @override
  String get notifications => 'নোটিফিকেশন';

  @override
  String get numberOfTracks => 'ট্র্যাকের সংখ্যা';

  @override
  String get ofLabel => 'এর';

  @override
  String get offlineSearch => 'অফলাইন অনুসন্ধান';

  @override
  String get offset => 'অফসেট';

  @override
  String get oldDirectory => 'পুরনো ডিরেক্টরি';

  @override
  String get oldDirectoryStillHasTracks => 'পুরনো ডিরেক্টরিতে এখনও কিছু ট্র্যাক রয়েছে, নিশ্চিত?';

  @override
  String get oldestWatch => 'অনেক আগের দেখা';

  @override
  String get onDeviceConnect => 'ডিভাইস সংযোগ করলে';

  @override
  String get onInterruption => 'প্লেব্যাক বিঘ্নিত হলে করণীয়';

  @override
  String get onNotificationTap => 'নোটিফিকেশনে ট্যাপ করালে';

  @override
  String get onOpeningYoutubeLink => 'ইউটিউব লিঙ্ক খোলার সময়';

  @override
  String get onSwiping => 'সোয়াইপ করার সময়';

  @override
  String get onVolumeZero => 'ভলিউম ০ হওয়ার সময়';

  @override
  String get ongoing => 'চলমান';

  @override
  String get open => 'খুলুন';

  @override
  String get openApp => 'অ্যাপ খুলুন';

  @override
  String get openInFileExplorer => 'ফাইল এক্সপ্লোরারে খুলুন';

  @override
  String get openInYoutubeView => 'ইউটিউব ভিউতে খুলুন';

  @override
  String get openMiniplayer => 'মিনিপ্লেয়ার খুলুন';

  @override
  String get openQueue => 'কিউ খুলুন';

  @override
  String get openYoutubeLink => 'ইউটিউব লিঙ্ক খুলুন';

  @override
  String operationRequiresAccount({required String name}) {
    return 'অপারেশন $name এর জন্য অ্যাকাউন্ট প্রয়োজন, অগ্রসর হতে সাইন ইন করুন';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'অপারেশন $operation এর জন্য কমপক্ষে $name সদস্যপদ প্রয়োজন';
  }

  @override
  String get or => 'বা';

  @override
  String get others => 'অন্যান্য';

  @override
  String get output => 'আউটপুট';

  @override
  String get outro => 'সমাপ্তি';

  @override
  String get overrideOldFilesInTheSameFolder => 'একই ফোল্ডারে পুরনো ফাইলগুলিকে ওভাররাইড করুন';

  @override
  String get palette => 'প্যালেট';

  @override
  String get paletteMix => 'মিক্স';

  @override
  String get paletteNewMix => 'নতুন মিক্স';

  @override
  String get paletteSelectedMix => 'নির্বাচিত মিক্স';

  @override
  String get parallelDownloads => 'একযোগে ডাউনলোড';

  @override
  String get parsed => 'পার্স করা হয়েছে';

  @override
  String get password => 'পাসওয়ার্ড';

  @override
  String get path => 'ফাইলের সম্পূর্ণ পাথ (Path)';

  @override
  String get pause => 'বিরতি';

  @override
  String get pauseFadeDuration => 'পজ ফেড এর সময়কাল';

  @override
  String get pausePlayback => 'প্লেব্যাক বিরতি দিন';

  @override
  String get percentage => 'শতাংশ';

  @override
  String get performanceMode => 'কার্যক্ষমতা মোড';

  @override
  String get performanceNote => 'কার্যক্ষমতায় প্রভাব ফেলতে পারে';

  @override
  String get personalized => 'ব্যক্তিগতকৃত';

  @override
  String get personalizedRelatedVideos => 'ব্যক্তিগতকৃত সম্পর্কিত ভিডিও';

  @override
  String get personalizedRelatedVideosSubtitle => 'এটি নিষ্ক্রিয় করলে ডেটা ব্যবহার বৃদ্ধি পাবে';

  @override
  String get pickColorsFromDeviceWallpaper => 'ডিভাইস ওয়ালপেপারের রঙ ব্যবহার করুন';

  @override
  String get pickFromStorage => 'স্টোরেজ থেকে বাছাই করুন';

  @override
  String get pinned => 'পিন করা';

  @override
  String get pitch => 'পিচ';

  @override
  String get plain => 'সাধারণ';

  @override
  String get play => 'চালান';

  @override
  String get playAfter => 'এর পরে চালান';

  @override
  String get playAfterNextPrev => 'পরবর্তী/পূর্ববর্তীতে স্বয়ংক্রিয় চালান';

  @override
  String get playAll => 'সব চালান';

  @override
  String get playFadeDuration => 'প্লে ফেড এর সময়কাল';

  @override
  String get playLast => 'শেষটি চালান';

  @override
  String get playNext => 'পরবর্তীটি চালান';

  @override
  String get playbackSetting => 'প্লেব্যাক';

  @override
  String get playbackSettingSubtitle => '\'অডিও\' বাটনে লং-প্রেস করে সরাসরি এই সেটিংস অ্যাক্সেস করুন';

  @override
  String get playlist => 'প্লেলিস্ট';

  @override
  String get playlists => 'প্লেলিস্ট';

  @override
  String get playlistsImportM3uNative => 'এটি শুধুমাত্র Namida-তে ব্যবহারের জন্য M3U প্লেলিস্ট ইম্পোর্ট করবে। মাইগ্রেট করলে এটি ব্যবহার করুন';

  @override
  String get playlistsImportM3uSynced =>
      'এটি স্বয়ংক্রিয়ভাবে ইনডেক্সার ফোল্ডার থেকে M3U প্লেলিস্ট ইম্পোর্ট করবে এবং মূল M3U ফাইলের সাথে সিঙ্ক রাখবে। আপনি যদি অন্যান্য অ্যাপ থেকে প্লেলিস্ট অ্যাক্সেস/পরিবর্তন করেন তবে সক্রিয় করুন';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'স্বয়ংক্রিয়ভাবে M3U প্লেলিস্ট ইম্পোর্ট করুন';

  @override
  String get pleaseEnterADifferentName => 'এই নামটি ইতিমধ্যে বিদ্যমান :(\nদয়া করে অন্য একটি নাম চেষ্টা করুন';

  @override
  String get pleaseEnterALink => 'দয়া করে একটি লিঙ্ক দিন';

  @override
  String get pleaseEnterALinkSubtitle => 'উম্ম.. এটি কি একটি ইউটিউব লিঙ্ক?';

  @override
  String get pleaseEnterAName => 'দয়া করে একটি নাম দিন';

  @override
  String get port => 'পোর্ট';

  @override
  String get preventDuplicatedTracks => 'ডুপ্লিকেট ট্র্যাক প্রতিরোধ করুন';

  @override
  String get preventDuplicatedTracksSubtitle => 'ট্র্যাক স্বতন্ত্রভাবে সনাক্ত করতে ফাইলের নাম ব্যবহার করে';

  @override
  String get preview => 'প্রিভিউ';

  @override
  String get previous => 'পূর্ববর্তী';

  @override
  String get previousButtonReplays => '\'পূর্ববর্তী\' বাটন দ্বারা পুনঃচালনা করুন';

  @override
  String get previousButtonReplaysSubtitle => 'যখন বর্তমান অবস্থান সিক সময়কালের চেয়ে বেশি থাকবে';

  @override
  String get prioritizeEmbeddedLyrics => 'এম্বেড করা লিরিক্সকে অগ্রাধিকার দিন';

  @override
  String get priority => 'অগ্রাধিকার';

  @override
  String get private => 'ব্যক্তিগত';

  @override
  String get progress => 'অগ্রগতি';

  @override
  String get promptToChangeTrackPath => 'সাধারণত এটি ঘটে যখন আপনি এই অ্যাপের বাইরে ফাইলটি ডিলিট, স্থানান্তর বা নাম পরিবর্তন করেন। আপনি কি বর্তমান পাথ (Path) আপডেট করতে চান?';

  @override
  String get public => 'সাধারণ';

  @override
  String get queue => 'কিউ';

  @override
  String get queues => 'কিউ';

  @override
  String get random => 'র‍্যান্ডম';

  @override
  String get randomPicks => 'এলোমেলো বাছাই';

  @override
  String get rating => 'রেটিং';

  @override
  String get reIndex => 'রি-ইনডেক্স';

  @override
  String get reIndexSubtitle => 'আপনার মিউজিক লাইব্রেরি শুরু থেকে নতুন করে সাজান';

  @override
  String get reIndexWarning =>
      'এই প্রক্রিয়াটি সম্পন্ন হতে কিছুটা সময় নিতে পারে, যা আপনার লাইব্রেরির আকারের ওপর নির্ভর করবে।\n\nযতক্ষণ আর্টওয়ার্ক বিদ্যমান ততক্ষণ সেগুলো পুনঃইনডেক্স করা হবে না';

  @override
  String get recentAlbums => 'সাম্প্রতিক অ্যালবাম';

  @override
  String get recentArtists => 'সাম্প্রতিক শিল্পী';

  @override
  String get recentListens => 'সাম্প্রতিক শোনা';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'সাম্প্রতিক সংযোজন';

  @override
  String get recordLabel => 'রেকর্ড লেবেল';

  @override
  String get refresh => 'রিফ্রেশ';

  @override
  String get refreshLibrary => 'লাইব্রেরি রিফ্রেশ করুন';

  @override
  String get refreshLibrarySubtitle => 'নতুন যোগকৃত বা ডিলিট করা সঙ্গীতের জন্য চেক করুন';

  @override
  String get refreshOnStartup => 'অ্যাপ চালু করার সময় রিফ্রেশ করুন';

  @override
  String get relatedVideos => 'সম্পর্কিত ভিডিও';

  @override
  String get rememberAudioOnlyMode => 'শুধুমাত্র অডিও মোড মনে রাখুন';

  @override
  String get remixer => 'রিমিক্সার';

  @override
  String get remove => 'সরান';

  @override
  String get removeDuplicates => 'ডুপ্লিকেটগুলো সরান';

  @override
  String get removeFromFavourites => 'পছন্দের তালিকা থেকে সরান';

  @override
  String get removeFromLibrary => 'লাইব্রেরি থেকে সরান';

  @override
  String get removeFromPlaylist => 'প্লেলিস্ট থেকে সরান';

  @override
  String get removeQueue => 'কিউ সরান';

  @override
  String get removeSourceFromHistory => 'ইতিহাস থেকে উৎস সরান';

  @override
  String get removeWhitespaces => 'হোয়াইটস্পেস সরান';

  @override
  String get removed => 'সরানো হয়েছে';

  @override
  String get rename => 'নাম পরিবর্তন করুন';

  @override
  String get renamePlaylist => 'প্লেলিস্টের নাম পরিবর্তন করুন';

  @override
  String get reorderable => 'পুনর্বিন্যাসযোগ্য';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'আরও $number বার পুনরাবৃত্তি করুন',
      one: 'আরও $number বার পুনরাবৃত্তি করুন',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'পুনরাবৃত্তি মোড';

  @override
  String get repeatModeAll => 'সম্পূর্ণ কিউ পুনরাবৃত্তি করুন';

  @override
  String get repeatModeNone => 'শেষ ট্র্যাকে থামুন';

  @override
  String get repeatModeOne => 'বর্তমান ট্র্যাক পুনরাবৃত্তি করুন';

  @override
  String get replaceAllListensWithAnotherTrack => 'সমস্ত শ্রবণ অন্য ট্র্যাক দিয়ে প্রতিস্থাপন করুন';

  @override
  String get replies => 'রিপ্লাই';

  @override
  String get reply => 'রিপ্লাই';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'ছবির ক্যাশ সাফ করা এবং পুনরায় ইনডেক্সিং করা প্রয়োজন';

  @override
  String get rescanVideos => 'ভিডিও স্ক্যান করুন';

  @override
  String get resetBrightness => 'উজ্জ্বলতা রিসেট করুন';

  @override
  String get resetToDefault => 'ডিফল্ট মান পুনরুদ্ধার করা হয়েছে';

  @override
  String get respectNoMedia => '.nomedia মেনে চলুন';

  @override
  String get respectNoMediaSubtitle => '.nomedia আছে এমন ফোল্ডার অন্তর্ভুক্ত করবে না';

  @override
  String get restart => 'পুনরায় শুরু করুন';

  @override
  String get restoreBackup => 'ব্যাকআপ পুনরুদ্ধার করুন';

  @override
  String get restoreDefaults => 'ডিফল্ট পুনরুদ্ধার করুন';

  @override
  String get restoredBackupSuccessfully => 'ব্যাকআপ পুনরুদ্ধার করা হয়েছে';

  @override
  String get restoredBackupSuccessfullySub => 'ব্যাকআপ ফাইল সফলভাবে পুনরুদ্ধার করা হয়েছে';

  @override
  String get resume => 'পুনরায় শুরু';

  @override
  String get resumeIfWasInterrupted => 'পুনরায় শুরু করুন যদি কোনো বাধা দ্বারা থামানো হয়ে থাকে';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'ডিভাইস বিচ্ছিন্ন হওয়ার কারণে বন্ধ হলে পুনরায় চালু করুন';

  @override
  String get resumeIfWasPausedByVolume => 'পুনরায় শুরু করুন যদি ভলিউম দ্বারা থামানো হয়ে থাকে';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'পুনরায় শুরু করুন যদি $numberString মিনিটের কম সময়ের জন্য থামানো হয়ে থাকে',
      one: 'পুনরায় শুরু করুন যদি $numberString মিনিটের কম সময়ের জন্য থামানো হয়ে থাকে',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'রিটার্ন ইউটিউব ডিসলাইক';

  @override
  String get reverseOrder => 'উল্টো ক্রম';

  @override
  String get rightAction => 'ডান দিকের অ্যাকশন';

  @override
  String get ringtone => 'রিংটোন';

  @override
  String get sameDirectoryOnly => 'শুধুমাত্র একই ডিরেক্টরি';

  @override
  String get sample => 'নমুনা';

  @override
  String get sampleRate => 'নমুনা হার';

  @override
  String get save => 'সংরক্ষণ করুন';

  @override
  String get saveToLibrary => 'লাইব্রেরিতে সংরক্ষণ করুন';

  @override
  String get savedIn => 'সংরক্ষিত হয়েছে';

  @override
  String get scaleMultiplier => 'আর্টওয়ার্ক সাইজ';

  @override
  String get search => 'অনুসন্ধান করুন';

  @override
  String get searchYoutube => 'ইউটিউবে অনুসন্ধান করুন';

  @override
  String get seconds => 'সেকেন্ড';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return '$site-এ প্রজেক্ট কোড দেখুন';
  }

  @override
  String get seekDuration => 'সিক সময়কাল';

  @override
  String get seekDurationInfo => 'পিছনে সিক করতে বর্তমান সময়কাল এবং সামনে সিক করতে মোট সময়কালের উপর ট্যাপ করুন';

  @override
  String get seekbar => 'সিকবার';

  @override
  String get selectAll => 'সব নির্বাচন করুন';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'স্থানীয় লাইব্রেরিতে থাকা ফাইল নির্বাচন করুন';

  @override
  String get selectedTracks => 'নির্বাচিত ট্র্যাক';

  @override
  String get selfPromotion => 'স্ব-প্রচার';

  @override
  String get semitones => 'সেমিটোন';

  @override
  String get separatorsBlacklistSubtitle => 'এই শব্দগুলো বিভক্ত হবে না';

  @override
  String get separatorsMessage => 'স্পেস দেওয়ার প্রয়োজন নেই, যদি না চিহ্নটি কোনো শব্দের অংশ হয় (যেমন: x এবং ft.)';

  @override
  String get serverAddress => 'সার্ভার ঠিকানা';

  @override
  String get setAs => 'হিসাবে সেট করুন';

  @override
  String get setAsDefault => 'ডিফল্ট হিসাবে সেট করুন';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'ফাইলের সর্বশেষ পরিবর্তনকে ভিডিও আপলোডের তারিখ হিসাবে সেট করুন';

  @override
  String get setMonoAudio => 'মোনো অডিও সেট করুন';

  @override
  String get setMoods => 'মুড সেট করুন';

  @override
  String get setMoodsSubtitle => 'আলাদা করতে কমা (,) ব্যবহার করুন';

  @override
  String get setRating => 'রেটিং সেট করুন';

  @override
  String get setTags => 'ট্যাগ সেট করুন';

  @override
  String get setYoutubeLink => 'ইউটিউব লিঙ্ক সেট করুন';

  @override
  String get settings => 'সেটিংস';

  @override
  String get setupFirstStartup => 'প্রাথমিক সেটআপ সম্পন্ন করুন';

  @override
  String get share => 'শেয়ার';

  @override
  String get shareLogs => 'লগ শেয়ার করুন';

  @override
  String get shortcuts => 'শর্টকাট';

  @override
  String get shouldDuck => 'ধীর করা উচিত';

  @override
  String get shouldDuckNote => 'এখানে ভলিউম কমানো উচিত। যেমন: নোটিফিকেশন';

  @override
  String get shouldPause => 'বিরতি দেওয়া উচিত';

  @override
  String get shouldPauseNote => 'এখানে প্লেব্যাক থামানো উচিত। যেমন: কল';

  @override
  String get showAll => 'সব দেখান';

  @override
  String get showChannelWatermarkInFullscreen => 'ফুলস্ক্রিনে চ্যানেল ওয়াটারমার্ক দেখান';

  @override
  String get showFailedOnly => 'শুধুমাত্র ব্যর্থগুলো দেখান';

  @override
  String get showHideUnknownFields => 'অজানা ক্ষেত্রগুলো দেখুন/লুকান';

  @override
  String get showInSeekbar => 'সিকবারে দেখান';

  @override
  String get showMixPlaylistsIn => 'মিক্সগুলোতে দেখান';

  @override
  String get showMore => 'আরও দেখান';

  @override
  String get showShortVideosIn => 'শর্টগুলোতে দেখান';

  @override
  String get showSkipButton => '\'স্কিপ\' বাটন দেখান';

  @override
  String get showVideoEndcards => 'ভিডিও এন্ডকার্ড দেখান';

  @override
  String get showWebm => 'WEBM দেখান';

  @override
  String get shuffle => 'এলোমেলো';

  @override
  String get shuffleAll => 'সব এলোমেলো করুন';

  @override
  String get shuffleNext => 'শুধু পরবর্তিগুলো';

  @override
  String get signIn => 'সাইন ইন';

  @override
  String get signInCanceled => 'সাইন ইন বাতিল করা হয়েছে';

  @override
  String get signInFailed => 'সাইন ইন ব্যর্থ হয়েছে';

  @override
  String get signInToYourAccount => 'আপনার অ্যাকাউন্টে সাইন ইন করুন';

  @override
  String get signInYouDontHaveAccount => 'আপনার কোনো অ্যাকাউন্টে সাইন ইন করা নেই';

  @override
  String get signInYouNeedAccountToViewPage => 'এই পৃষ্ঠা দেখতে আপনার একটি অ্যাকাউন্ট প্রয়োজন';

  @override
  String get signOut => 'সাইন আউট';

  @override
  String signOutFromName({required String name}) {
    return '$name থেকে সাইন আউট করবেন';
  }

  @override
  String get signingInAllowsBasicUsage => 'সাইন ইন করলে মৌলিক সুবিধাগুলো পাবেন';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'প্যাট্রিয়ন বা কুপন ব্যবহার করে প্রাথমিক অ্যাক্সেস পান';

  @override
  String get similarDiscoverDate => 'আবিষ্কারের সময়কাল';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return '$currentTrack এর কাছাকাছি সময়ে আবিষ্কৃত ট্র্যাকগুলো যোগ করুন';
  }

  @override
  String get similarTimeRange => 'একই সময়সীমা';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return '$currentTrack এর কাছাকাছি সময়ে শোনা ট্র্যাকগুলো যোগ করুন';
  }

  @override
  String get singles => 'একক গান';

  @override
  String get size => 'সাইজ';

  @override
  String get skip => 'স্কিপ';

  @override
  String get skipCountTracking => 'স্কিপ কাউন্ট ট্র্যাকিং';

  @override
  String get skipSilence => 'নীরবতা এড়িয়ে যান';

  @override
  String get skipSponsorSegmentsInVideos => 'ভিডিওর স্পন্সর অংশগুলো বাদ দিন';

  @override
  String get sleepAfter => 'সময় বা ট্র্যাক সেট করুন';

  @override
  String get sleepTimer => 'স্লিপ টাইমার';

  @override
  String get socials => 'সোশ্যাল মিডিয়া';

  @override
  String get socialsSubtitle => 'আপডেট, টিপস এবং আলোচনার জন্য আমাদের সাথে যুক্ত হন';

  @override
  String get someWebServersRequireAuthentication => 'কিছু ওয়েব সার্ভারের জন্য যাচাইকরণ প্রয়োজন। আপনার লাইব্রেরিতে অ্যাক্সেস বজায় রাখতে দয়া করে লগইন তথ্য (Credentials) আপডেট করুন।';

  @override
  String get sortBy => 'দ্বারা সাজান';

  @override
  String get source => 'উৎস';

  @override
  String get speed => 'গতি';

  @override
  String get sponsor => 'বিজ্ঞাপন';

  @override
  String get sponsorblock => 'স্পন্সরব্লক';

  @override
  String get sponsorblockLeaderboard => 'স্পন্সরব্লক লিডারবোর্ড';

  @override
  String get staggeredAlbumGridView => 'স্ট্যাগার্ড অ্যালবাম গ্রিডভিউ';

  @override
  String get start => 'শুরু করুন';

  @override
  String get stats => 'পরিসংখ্যান';

  @override
  String get statsSubtitle => 'এখানে আপনার লাইব্রেরি সম্পর্কে কিছু তথ্য রয়েছে';

  @override
  String get stop => 'থামান';

  @override
  String get stopAfterThisTrack => 'এই ট্র্যাকের পরে থামান';

  @override
  String get stopAfterThisVideo => 'এই ভিডিওর পরে থামান';

  @override
  String get storagePermissionDenied => 'অনুমতি অস্বীকৃত';

  @override
  String get storagePermissionDeniedSubtitle => 'এই ক্রিয়া সম্পাদন করতে দয়া করে অ্যাক্সেস অনুমতি দিন';

  @override
  String get stretchLyricsDuration => 'লিরিক্স এর সময়কাল প্রসারিত করুন';

  @override
  String get subdirectory => 'সাবডিরেক্টরি';

  @override
  String get subscribe => 'সাবস্ক্রাইব';

  @override
  String get subscribed => 'সাবস্ক্রাইবকৃত';

  @override
  String get subscriber => 'সাবস্ক্রাইবার';

  @override
  String get subscribers => 'সাবস্ক্রাইবার';

  @override
  String get succeeded => 'সফল হয়েছে';

  @override
  String suggestionSubtitle({required String site}) {
    return 'কোনো সমস্যা বা পরামর্শ থাকলে $site-এ আমাদের জানানতে পারেন';
  }

  @override
  String get support => 'সহায়তা';

  @override
  String get supremacy => 'সর্বোচ্চতা';

  @override
  String get sussyBaka => 'কিছুই পাওয়া যায়নি';

  @override
  String get swipeActions => 'সোয়াইপ অ্যাকশন';

  @override
  String get swipeToOpenDrawer => 'ড্রয়ার খুলতে সোয়াইপ করুন';

  @override
  String get synced => 'সিঙ্ক করা হয়েছে';

  @override
  String get synopsis => 'সারসংক্ষেপ';

  @override
  String get tagFields => 'ট্যাগ ক্ষেত্রসমূহ';

  @override
  String get tags => 'ট্যাগ';

  @override
  String get tapAction => 'ট্যাপ অ্যাকশন';

  @override
  String get tapToSeek => 'সিক করতে ট্যাপ করুন';

  @override
  String get theFollowingChangesWereDetected => 'এই পরিবর্তনগুলো শনাক্ত করা হয়েছে';

  @override
  String get themeMode => 'থিম মোড';

  @override
  String get themeModeDark => 'ডার্ক মোড';

  @override
  String get themeModeLight => 'লাইট মোড';

  @override
  String get themeModeSystem => 'সিস্টেম';

  @override
  String get themeSettings => 'থিম';

  @override
  String get themeSettingsSubtitle => 'আপনার প্লেয়ারের সামগ্রিক আবহ';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'এই প্লেলিস্টে সক্রিয় সর্টার রয়েছে, পুনর্বিন্যাস করার আগে দয়া করে সেগুলো নিষ্ক্রিয় করুন।';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'এই ভিডিওটি সম্ভবত ডিলিট করা হয়েছে বা ব্যক্তিগত হিসাবে সেট করা হয়েছে।';

  @override
  String get thumbnails => 'থাম্বনেইল';

  @override
  String get title => 'শিরোনাম';

  @override
  String get top => 'শীর্ষ';

  @override
  String get topComments => 'শীর্ষ কমেন্ট';

  @override
  String get topCommentsSubtitle => 'নিচের পরিবর্তে উপরে কমেন্ট প্রদর্শন করুন';

  @override
  String get topRecentAlbums => 'সাম্প্রতিক শীর্ষ অ্যালবাম';

  @override
  String get topRecentArtists => 'সাম্প্রতিক শীর্ষ শিল্পী';

  @override
  String get topRecents => 'সাম্প্রতিক শীর্ষ তালিকা';

  @override
  String get totalListenTime => 'মোট শ্রবণের সময়';

  @override
  String get totalListens => 'মোট শ্রবণ';

  @override
  String get totalTracks => 'মোট ট্র্যাক';

  @override
  String get totalTracksDuration => 'মোট ট্র্যাকের সময়কাল';

  @override
  String get track => 'ট্র্যাক';

  @override
  String get trackArtistsSeparator => 'শিল্পী বিভাজক';

  @override
  String get trackGenresSeparator => 'জনরা বিভাজক';

  @override
  String get trackInfo => 'ট্র্যাকের তথ্য';

  @override
  String get trackNotFound => 'ট্র্যাক পাওয়া যায়নি';

  @override
  String get trackNumber => 'ট্র্যাক নম্বর';

  @override
  String get trackNumberTotal => 'ট্র্যাক মোট';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'পুরনো নাম: \"$oldName\"\n\nনতুন নাম: \"$newName\"\n\nআপনি কি নিশ্চিত?';
  }

  @override
  String get trackPlayMode => 'চালানোর মোড';

  @override
  String get trackPlayModeSearchResults => 'অনুসন্ধানকৃত ফলাফল';

  @override
  String get trackPlayModeSelectedOnly => 'শুধুমাত্র নির্বাচিত ট্র্যাক';

  @override
  String get trackPlayModeTrackAlbum => 'ট্র্যাকের অ্যালবাম';

  @override
  String get trackPlayModeTrackArtist => 'ট্র্যাকের প্রধান শিল্পী';

  @override
  String get trackPlayModeTrackGenre => 'ট্র্যাকের জনরা';

  @override
  String get trackThumbnailSizeInList => 'ট্র্যাক থাম্বনেইলের আকার';

  @override
  String get trackTileCustomization => 'ট্র্যাক টাইল কাস্টমাইজেশন';

  @override
  String get trackTileItemsSeparator => 'আইটেম বিভাজক';

  @override
  String get tracks => 'ট্র্যাক';

  @override
  String get tracksExcludedByNomedia => '.nomedia দ্বারা বর্জিত ট্র্যাক';

  @override
  String get tracksInfo => 'ট্র্যাকের তথ্য';

  @override
  String get underrated => 'অবমূল্যায়িত';

  @override
  String get undo => 'পূর্বাবস্থায় আনুন';

  @override
  String get undoChanges => 'পরিবর্তন পূর্বাবস্থায় আনবেন?';

  @override
  String get undoChangesDeletedPlaylist => 'ডিলিট করা প্লেলিস্ট পূর্বাবস্থায় আনুন';

  @override
  String get undoChangesDeletedQueue => 'ডিলিট করা কিউ পূর্বাবস্থায় আনুন';

  @override
  String get undoChangesDeletedTrack => 'ডিলিট করা ট্র্যাক পূর্বাবস্থায় আনুন';

  @override
  String get uniqueArtworkHash => 'অনন্য আর্টওয়ার্ক হ্যাশ';

  @override
  String get unlimited => 'সীমাহীন';

  @override
  String get unlisted => 'তালিকাভুক্ত নয়';

  @override
  String get unlock => 'আনলক';

  @override
  String get unsubscribe => 'আনসাবস্ক্রাইব';

  @override
  String get update => 'আপডেট';

  @override
  String get updateDirectoryPath => 'ডিরেক্টরি পাথ (Path) আপডেট করুন';

  @override
  String get updateMissingTracksOnly => 'শুধুমাত্র অনুপস্থিত ট্র্যাক আপডেট করুন';

  @override
  String get updating => 'আপডেট করা হচ্ছে';

  @override
  String get useCollapsedSettingTiles => 'সঙ্কুচিত সেটিংস টাইল ব্যবহার করুন';

  @override
  String get useMediaStore => 'মিডিয়া স্টোর ব্যবহার করুন';

  @override
  String get useMediaStoreSubtitle =>
      '✓ তাত্ক্ষণিক ইনডেক্সিং\nx .nomedia মানা হবে\nx কিছু মেটাডেটা ট্যাগ অনুপস্থিত থাকবে\nx স্থানীয় লাইব্রেরির জন্য ইউটিউব ইন্টিগ্রেশন কাজ করবে না';

  @override
  String get usePitchBlack => 'পিচ ব্ল্যাক মোড';

  @override
  String get usePitchBlackSubtitle => 'AMOLED স্ক্রিনের জন্য উপযোগী.. এবং দেখতে আরও আকর্ষণীয়';

  @override
  String get used => 'ব্যবহৃত';

  @override
  String get value => 'মান';

  @override
  String get valueBetween50200 => 'মান অবশ্যই ৫০% থেকে ২০০% এর মধ্যে হতে হবে';

  @override
  String get vibration => 'কম্পন';

  @override
  String get vibrationType => 'কম্পনের ধরন';

  @override
  String get video => 'ভিডিও';

  @override
  String get videoCache => 'ভিডিও ক্যাশ';

  @override
  String get videoCacheFile => 'ক্যাশ করা ভিডিও ফাইল';

  @override
  String get videoCacheFiles => 'ক্যাশ করা ভিডিও ফাইল';

  @override
  String get videoOnly => 'শুধুমাত্র ভিডিও';

  @override
  String get videoPlaybackSource => 'ভিডিওর উৎস';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'এটি স্থানীয় ভিডিওকে অগ্রাধিকার দেবে, না পাওয়া গেলে ইউটিউব থেকে আনা হবে';

  @override
  String get videoPlaybackSourceLocal => 'স্থানীয় ভিডিও';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'এটি চেক করে যে নির্বাচিত ফোল্ডারের মধ্যে কোন ভিডিও ফাইলের নামে ট্র্যাক ফাইলের নাম রয়েছে কিনা';

  @override
  String get videoPlaybackSourceYoutube => 'ইউটিউব থেকে';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'এটি ট্রাকের নাম এবং কমেন্টের মাঝে মিল আছে এমন ইউটিউব লিঙ্ক চেক করে, ভিডিওগুলো পরবর্তী ব্যবহারের জন্য সংরক্ষণ করা হয়।';

  @override
  String get videoQuality => 'ভিডিও কোয়ালিটি';

  @override
  String get videoQualitySubtitle => 'সর্বোচ্চ উপলভ্য কোয়ালিটি নির্বাচন করা হবে।';

  @override
  String get videoQualitySubtitleNote => 'একটি কোয়ালিটি না পাওয়া গেলে বিকল্পের জন্য একাধিক কোয়ালিটি রাখা ভালো, অন্যথায় এটি সর্বনিম্ন কোয়ালিটিতে ফিরে যাবে';

  @override
  String get videos => 'ভিডিও';

  @override
  String get view => 'দেখুন';

  @override
  String get viewAll => 'সব দেখুন';

  @override
  String get views => 'ভিউ';

  @override
  String get volume => 'ভলিউম';

  @override
  String get warning => 'সতর্কতা';

  @override
  String get waveformBarsCount => 'ওয়েভফর্ম বার সংখ্যা';

  @override
  String get webmNoEditTagsSupport => 'WEBM ফরম্যাট ট্যাগ সম্পাদনা সমর্থন করে না';

  @override
  String get week => 'সপ্তাহ';

  @override
  String get wiredDevice => 'তারযুক্ত ডিভাইস';

  @override
  String get wirelessDevice => 'তারবিহীন ডিভাইস';

  @override
  String get year => 'বছর';

  @override
  String get yes => 'হ্যাঁ';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'আপনার বর্তমান সদস্যপদ $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'আপনার কাস্টম ক্রম হারিয়ে যাবে, আপনি কি নিশ্চিত?';

  @override
  String get youtube => 'ইউটিউব';

  @override
  String get youtubeMusic => 'ইউটিউব মিউজিক';

  @override
  String get youtubeSettingsSubtitle => 'আপনার ইউটিউব অভিজ্ঞতা কাস্টমাইজ করুন';

  @override
  String get youtubeStyleMiniplayer => 'ইউটিউব-স্টাইল মিনিপ্লেয়ার';

  @override
  String get ytPreferNewComments => 'নতুন কমেন্ট অগ্রাধিকার দিন';

  @override
  String get ytPreferNewCommentsSubtitle => 'ক্যাশ সংস্করণ শুধুমাত্র তখনই ব্যবহৃত হবে যখন কোন সংযোগ থাকবে না';
}
