// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Afrikaans (`af`).
class AppLocalizationsAf extends AppLocalizations {
  AppLocalizationsAf([String locale = 'af']) : super(locale);

  @override
  String get about => 'Oor';

  @override
  String get active => 'Aktief';

  @override
  String get add => 'Voeg by';

  @override
  String get addAccount => 'Voeg rekening by';

  @override
  String get addAll => 'Voeg alles by';

  @override
  String get addAllAndRemoveOldOnes => 'Voeg alles by en verwyder ou items';

  @override
  String get addAsANewPlaylist => 'Voeg by as \'n nuwe snitlys';

  @override
  String get addAudioToLocalLibrary => 'Voeg klank by plaaslike biblioteek';

  @override
  String get addFolder => 'Voeg vouer by';

  @override
  String get addLanguage => 'Voeg taal by';

  @override
  String get addLanguageSubtitle => 'Help om Namida in jou eie taal te vertaal';

  @override
  String get addLrcFile => 'Voeg LRC-lêer by';

  @override
  String get addMoreFromThisAlbum => 'Voeg meer van hierdie album by die tou';

  @override
  String get addMoreFromThisArtist => 'Voeg meer van hierdie kunstenaar by die tou';

  @override
  String get addMoreFromThisFolder => 'Voeg meer van hierdie vouer by die tou';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Voeg meer van $media by die tou';
  }

  @override
  String get addOnlyMissing => 'Voeg slegs ontbrekende by';

  @override
  String get addToFavourites => 'Voeg by gunstelinge';

  @override
  String get addToPlaylist => 'Voeg by snitlys';

  @override
  String get addTracksAtTheBeginning => 'Voeg snitte aan die begin by';

  @override
  String get added => 'bygevoeg';

  @override
  String get advanced => 'Gevorderd';

  @override
  String get advancedSettings => 'Gevorderd';

  @override
  String get advancedSettingsSubtitle => 'Gevorderde instellings, moenie raak nie';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Albumkunstenaar';

  @override
  String get albumArtists => 'Albumkunstenaars';

  @override
  String get albumIdentifiers => 'Albumidentifiseerders';

  @override
  String get albumThumbnailSizeInList => 'Grootte van albumduimnael';

  @override
  String get albumTileCustomization => 'Albumteël-aanpassing';

  @override
  String get albums => 'Musiekalbums';

  @override
  String get albumsCount => 'Albumtelling';

  @override
  String get all => 'Alles';

  @override
  String get allTime => 'Alle tye';

  @override
  String get alreadyExists => 'Bestaat alreeds';

  @override
  String get always => 'Altyd';

  @override
  String get alwaysAsk => 'Vra altyd';

  @override
  String get alwaysDim => 'Verdoof altyd';

  @override
  String get alwaysExpandedSearchbar => 'Altyd uitgebreide soekbalk';

  @override
  String get alwaysRestore => 'Herstel altyd';

  @override
  String get animatingThumbnailIntensity => 'Duimnael-animasie-intensiteit';

  @override
  String get animatingThumbnailInversed => 'Omgekeerde animasies';

  @override
  String get animatingThumbnailInversedSubtitle => 'Hoë pieke sal veroorsaak dat die duimnael kleiner word';

  @override
  String get anotherProcessIsRunning => '\'n Ander proses loop reeds.';

  @override
  String get appIcon => 'Toep-ikoon';

  @override
  String get appVersion => 'App Weergawe';

  @override
  String get artist => 'Kunstenaar';

  @override
  String get artists => 'Kunstenaars';

  @override
  String get artwork => 'Kunswerk';

  @override
  String get artworkGestures => 'Kunswerkgebare';

  @override
  String get artworks => 'Kunswerke';

  @override
  String get audio => 'Klank';

  @override
  String get audioCache => 'Klankkas';

  @override
  String get audioOnly => 'Slegs klank';

  @override
  String get auto => 'Outo';

  @override
  String get autoBackupInterval => 'Outo-rugsteuninterval';

  @override
  String get autoColoring => 'Outokleuring';

  @override
  String get autoColoringSubtitle => 'Kies outomaties spelerskleure uit die huidige kunswerk';

  @override
  String get autoExtractTagsFromFilename => 'Trek outomaties uit lêernaam';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Trek titel en kunstenaar outomaties uit videotitel';

  @override
  String get autoGenerated => 'Outo-gegenereer';

  @override
  String get autoSkip => 'Outo-oorslaan';

  @override
  String get autoSkipOnce => 'Slaan een keer outomaties oor';

  @override
  String get autoStartRadio => 'Begin radio outomaties';

  @override
  String get autoStartRadioSubtitle => 'Voeg outomaties \'n mengselsnitlys by wanneer \'n enkele snit gespeel word';

  @override
  String get automaticBackup => 'Outomaties';

  @override
  String get automaticBackupSubtitle => 'Pas outomaties die mees onlangse rugsteunlêer toe wat in die rugsteunligging gevind is';

  @override
  String get backupAndRestore => 'Rugsteun en herstel';

  @override
  String get backupAndRestoreSubtitle => 'Rugsteun jou databasis en instellings';

  @override
  String get balanced => 'Gebalanseerd';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Tussen datums';

  @override
  String get bitrate => 'Bissnelheid';

  @override
  String get blacklist => 'Swartlys';

  @override
  String get borderRadiusMultiplier => 'Randradiusvermenigvuldiger';

  @override
  String get cache => 'Kas';

  @override
  String get cancel => 'Kanselleer';

  @override
  String get canceled => 'Gekanselleer';

  @override
  String get changed => 'Verander';

  @override
  String get changelog => 'Veranderingslog';

  @override
  String get changelogSubtitle => 'Kyk wat nuut bygevoeg/reggestel is binne Namida';

  @override
  String get channel => 'Kanaal';

  @override
  String get channels => 'Kanale';

  @override
  String get check => 'Kontroleer';

  @override
  String get checkForMore => 'Kyk vir meer';

  @override
  String get checkList => 'Kontrolelys';

  @override
  String get choose => 'Kies';

  @override
  String get chooseWhatToClear => 'Kies wat om skoon te maak';

  @override
  String get claim => 'Eis';

  @override
  String get clear => 'Maak skoon';

  @override
  String get clearAudioCache => 'Maak klankkas skoon';

  @override
  String get clearImageCache => 'Maak beeldkas skoon';

  @override
  String get clearImageCacheWarning => 'Waarskuwing: sal lei tot \'n biblioteek sonder beelde. Gebruik slegs om die beeldkas te herbou.';

  @override
  String get clearTrackItem => 'Maak snit s\'n skoon';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Maak $numberString snitte s\'n skoon',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Maak videokas skoon';

  @override
  String get clearVideoCacheNote => 'Jy kan kies wat om te verwyder.';

  @override
  String get clock => 'Horlosie';

  @override
  String get colorPalette => 'Kleurpalet';

  @override
  String get colorPaletteNote1 => 'Druk lank op \'n kleur om dit te verwyder';

  @override
  String get colorPaletteNote2 => 'Tik op \'n mengsel om as \'n verstekkleur te gebruik';

  @override
  String get colorPalettes => 'Kleurpalette';

  @override
  String get comment => 'Kommentaar';

  @override
  String get comments => 'Kommentare';

  @override
  String get composer => 'Komponis';

  @override
  String get compress => 'Pers saam';

  @override
  String get compressImages => 'Pers beelde saam';

  @override
  String get compressionPercentage => 'Saampersingspersentasie';

  @override
  String get configure => 'Konfigureer';

  @override
  String get confirm => 'Bevestig';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => 'Kunswerk gekopieer';

  @override
  String get copiedToClipboard => 'Na knipbord gekopieer';

  @override
  String get copy => 'Kopieer';

  @override
  String get corruptedFile => 'Kon nie lêer ontleed nie, dit mag korrup wees';

  @override
  String get couldntOpen => 'Kon nie oopmaak nie :(';

  @override
  String get couldntOpenYtLink => 'Geen Youtube-skakel beskikbaar vir hierdie snit nie';

  @override
  String get couldntPlayFile => 'Kon nie lêer speel nie';

  @override
  String get couldntRenamePlaylist => 'Kon nie snitlys hernoem nie';

  @override
  String get couldntSaveImage => 'Kon nie beeld stoor nie';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Land';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Skep';

  @override
  String get createBackup => 'Skep rugsteun';

  @override
  String get createNewPlaylist => 'Skep nuwe snitlys';

  @override
  String get createdBackupSuccessfully => 'Rugsteun geskep';

  @override
  String get createdBackupSuccessfullySub => 'Rugsteunlêer is suksesvol geskep';

  @override
  String get crossPlatformSync => 'Kruisplatform-sinchronisasie';

  @override
  String get crossfadeDuration => 'Kruisfadeduur';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Aktiveer kruisfade outomaties in die laaste $secondsString sekondes',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Moenie kruisfade outomaties aktiveer nie';

  @override
  String get custom => 'Pasgemaak';

  @override
  String get customizations => 'Aanpassings';

  @override
  String get customizationsSubtitle => 'Pas aan hoe jou speler lyk, maak dit joune';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data word verskaf deur: $name';
  }

  @override
  String get dataSaver => 'Databespaarder';

  @override
  String get dataSaverMode => 'Databespaardermodus';

  @override
  String get database => 'Databasis';

  @override
  String get date => 'Datum';

  @override
  String get dateAdded => 'Datum bygevoeg';

  @override
  String get dateCreated => 'Datum geskep';

  @override
  String get dateModified => 'Datum gewysig';

  @override
  String get dateTimeFormat => 'Datum-tyd-formaat';

  @override
  String get day => 'Dag';

  @override
  String get days => 'Dae';

  @override
  String get defaultBackupLocation => 'Verstek rugsteunligging';

  @override
  String get defaultColor => 'Verstekkleur';

  @override
  String get defaultColorSubtitle => 'Stel \'n kleur in om deur die speler gebruik te word';

  @override
  String get defaultDownloadLocation => 'Verstek aflaailigging';

  @override
  String get defaultLabel => 'Verstek';

  @override
  String get defaultLibraryTab => 'Verstek biblioteektab';

  @override
  String get delete => 'Verwyder';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Verwyder $countString lêer wat $totalSizeText verteenwoordig?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Verwyder $numberText permanent van jou stoor';
  }

  @override
  String get deletePlaylist => 'Verwyder snitlys';

  @override
  String get deleteTempFiles => 'Verwyder tydelike lêers';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Beskrywing';

  @override
  String get developer => 'Ontwikkelaar';

  @override
  String get development => 'Ontwikkeling';

  @override
  String get didYouMean => 'Het jy bedoel';

  @override
  String get dimIntensity => 'Verdoofintensiteit';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Verdoof minispeler na $secondsString sekondes van onaktiwiteit',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Gids bestaan nie';

  @override
  String get disable => 'Deaktiveer';

  @override
  String get disableAll => 'Deaktiveer alles';

  @override
  String get disableReordering => 'Deaktiveer herrangskikking';

  @override
  String get disableSearchCleanup => 'Deaktiveer soekopruiming';

  @override
  String get discNumber => 'Skyfnommer';

  @override
  String get discNumberTotal => 'Skyftotaal';

  @override
  String get discover => 'Ontdek';

  @override
  String get dislike => 'Hou nie van nie';

  @override
  String get dismissibleMiniplayer => 'Verwerpbaare minispeler';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Vertoon werklike posisie in plaas van verskil tydens soek';

  @override
  String get displayAlbumCardTopRightDate => 'Albumkaart bo-regs datum';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Vertoon albumdatum bo-regs op die albumkaart';

  @override
  String get displayArtistBeforeTitle => 'Vertoon kunstenaar voor titel';

  @override
  String get displayArtworkOnLockscreen => 'Vertoon kunswerk op sluitskerm';

  @override
  String get displayAudioInfoInMiniplayer => 'Vertoon klankinligting';

  @override
  String get displayFavButtonInNotification => 'Vertoon gunsteling-knoppie in kennisgewing';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Duimnael mag dalk verskuif word.';

  @override
  String get displayFavouriteIconInTrackTile => 'Vertoon gunsteling-knoppie';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Vertoon oorblywende duur in plaas van totaal';

  @override
  String get displayStopButtonInNotification => 'Vertoon stopknoppie in kennisgewing';

  @override
  String get displayThirdItemInRowInTrackTile => 'Vertoon derde item in elke ry';

  @override
  String get displayThirdRowInTrackTile => 'Vertoon derde ry';

  @override
  String get displayTrackNumberInAlbumPage => 'Vertoon snitnommer op albumpadsy';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Vertoon \'n klein blokkie met die snitnommer op die albumpadsy';

  @override
  String get doNothing => 'Doen niks';

  @override
  String get donate => 'Skenk';

  @override
  String get donateSubtitle => 'As jy dink dit verdien';

  @override
  String get done => 'Klaar';

  @override
  String get dontAskAgain => 'Moenie weer vra nie';

  @override
  String get dontDim => 'Moenie verdoof nie';

  @override
  String get dontRestorePosition => 'Moenie herstel nie';

  @override
  String get dontResume => 'Moenie hervat nie';

  @override
  String get doubleTapToToggleLyrics => 'Dubbeltik om lirieke te wissel';

  @override
  String get download => 'Laai af';

  @override
  String get downloadingWillOverrideIt => 'Aflaai sal dit oorskryf';

  @override
  String get downloads => 'Aflaaie';

  @override
  String get downloadsMetadataTags => 'Aflaai metadata-etikette';

  @override
  String get downloadsMetadataTagsSubtitle => 'Trek kunstenaar, titel & album by verstek uit video-inligting';

  @override
  String get dragToSeek => 'Sleep om te soek';

  @override
  String get duckAudio => 'Duck oudio';

  @override
  String get duplicatedItemsAdding => 'Jy probeer items byvoeg wat reeds in hierdie snitlys bestaan';

  @override
  String get duplicatedTracks => 'Gedupliseerde snitte';

  @override
  String get duration => 'Duur';

  @override
  String get edgeColorsSwitching => 'Randkleure wissel';

  @override
  String get edit => 'Redigeer';

  @override
  String get editArtwork => 'Redigeer kunswerk';

  @override
  String get editTags => 'Redigeer etikette';

  @override
  String get email => 'E-pos';

  @override
  String get emptyNonMeaningfulTagFields => 'jy het velde met leë/nie-betekenisvolle waardes, maak seker jy wil hulle werklik redigeer';

  @override
  String get emptyValue => 'Leë waarde';

  @override
  String get enableArtworkCache => 'Aktiveer Kunswerk Kas';

  @override
  String get enableArtworkCacheSubtitle => 'Vinniger laai en verbeterde werkverrigting, maar gebruik meer stoorspasie';

  @override
  String get enableBlurEffect => 'Aktiveer vervaag-effek';

  @override
  String get enableBottomNavBar => 'Aktiveer onderste navigasiebalk';

  @override
  String get enableBottomNavBarSubtitle => 'Items is binne die laai in albei rigtings';

  @override
  String get enableClipboardMonitoring => 'Aktiveer knipbordmonitering';

  @override
  String get enableClipboardMonitoringSubtitle => 'Laat toe om skakels en teks binne soekbalk te plak terwyl jy besig is';

  @override
  String get enableCrossfadeEffect => 'Aktiveer kruisfade-effek';

  @override
  String get enableFadeEffectOnPlayPause => 'Aktiveer vervaag-effek by speel/pouse';

  @override
  String get enableFoldersHierarchy => 'Aktiveer gidshiërargie';

  @override
  String get enableGlowEffect => 'Aktiveer gloei-effek';

  @override
  String get enableM3uSync => 'Aktiveer M3U-sinchronisasie';

  @override
  String get enableM3uSyncNote1 => 'M3U-sinchronisasie laat toe om snitlysveranderinge in die oorspronklike M3U-lêer te stoor';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'As iets verkeerd gegaan het, sal \'n rugsteun van hierdie snitlys gevind word in $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Indien geweier, sal alle veranderinge wat in hierdie snitlys gemaak is, verlore gaan by herbegin';

  @override
  String get enableMiniplayerParticles => 'Aktiveer bewegende deeltjies';

  @override
  String get enableParallaxEffect => 'Aktiveer parallaks-effek';

  @override
  String get enablePartyMode => 'Aktiveer partytjiemodus';

  @override
  String get enablePartyModeSubtitle => 'Pas spoggerige randasemhalingseffek toe';

  @override
  String get enablePictureInPicture => 'Aktiveer prentjie-in-prentjie';

  @override
  String get enableReordering => 'Aktiveer herrangskikking';

  @override
  String get enableReturnYoutubeDislike => 'Aktiveer Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Aktiveer soekopruiming';

  @override
  String get enableSearchCleanupSubtitle => 'Alle simbole en spasies sal geïgnoreer word';

  @override
  String get enableSponsorblock => 'Aktiveer SponsorBlock';

  @override
  String get enableVideoPlayback => 'Aktiveer videoterugspeel';

  @override
  String get enterSymbol => 'Voer asseblief \'n simbool in';

  @override
  String get equalizer => 'Gelykmaker';

  @override
  String get error => 'Fout';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Fout met speel van snit';

  @override
  String get excludedFodlers => 'Uitgeslote vouers';

  @override
  String get exit => 'Gaan uit';

  @override
  String get exitAppSubtitle => 'Tik weer om uit te gaan';

  @override
  String get expandedMiniplayer => 'Uitgebreide minispeler';

  @override
  String get exportAsM3u => 'Voer uit as M3U';

  @override
  String get extension => 'Uitbreiding';

  @override
  String get externalFiles => 'Eksterne lêers';

  @override
  String get extract => 'Trek uit';

  @override
  String get extractAllColorPalettes => 'Trek alle kleurpalette uit';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Trek oorblywende $numberString uit?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Trek feat. kunstenaars uit titel uit';

  @override
  String get extractFeatArtistSubtitle => 'Trek (feat. X) en (ft. X) kunstenaars uit as \'n nuwe kunstenaarsinskrywing.';

  @override
  String get extractingInfo => 'Trek inligting uit';

  @override
  String get extras => 'Ekstras';

  @override
  String get extrasSubtitle => 'Ekstra instellings om jou ervaring te verfyn';

  @override
  String get extreme => 'Ekstreem';

  @override
  String get failed => 'Misluk';

  @override
  String get failedEdits => 'Mislukte redigerings';

  @override
  String get favourites => 'Gunstelinge';

  @override
  String get features => 'Funksies';

  @override
  String get fetching => 'Haal';

  @override
  String get fetchingOfAllVideos => 'Haal alle video\'s';

  @override
  String get file => 'Lêer';

  @override
  String get fileAlreadyExists => 'Lêer bestaan reeds';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Lêernaam';

  @override
  String get fileNameWoExt => 'Lêernaam sonder uitbreiding';

  @override
  String get filenameShouldntStartWith => 'Lêernaam moet nie begin met';

  @override
  String get files => 'Lêers';

  @override
  String get filler => 'Vuller';

  @override
  String get filterAlbums => 'Filtreer albums';

  @override
  String get filterArtists => 'Filtreer kunstenaars';

  @override
  String get filterGenres => 'Filtreer genres';

  @override
  String get filterPlaylists => 'Filtreer snitlyste';

  @override
  String get filterTracks => 'Filtreer snitte';

  @override
  String get filterTracksBy => 'Filtreer snitte in soeklyste volgens';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Snitte gefiltreer volgens grootte en duur';

  @override
  String get finished => 'Klaar';

  @override
  String get finishedUpdatingLibrary => 'Klaar met bywerking van biblioteek';

  @override
  String get firstListen => 'Eerste luister';

  @override
  String get fixYtdlpBigThumbnailSize => 'Maak yt-dlp groot duimnaelgrootte reg';

  @override
  String get floatingActionButton => 'Swerwende aksieknoppie';

  @override
  String get folder => 'Vouer';

  @override
  String get folderName => 'Vouernaam';

  @override
  String get folders => 'Vouers';

  @override
  String get fontScale => 'Fontskaal';

  @override
  String get forceMiniplayerFollowTrackColors => 'Dwing minispeler om snitkleure te volg';

  @override
  String get forceSquaredAlbumThumbnail => 'Dwing vierkantige albumduimnael';

  @override
  String get forceSquaredThumbnailNote => 'Duimnaelgrootte & Teëlhoogte is NIE gelyk nie, vierkantige voorkoms sal nie soos verwag wees nie. Wil jy hulle gelyk maak?';

  @override
  String get forceSquaredTrackThumbnail => 'Dwing vierkantige snitduimnael';

  @override
  String get forceStopColorPaletteGeneration => 'Dwing stop van kleurpalet-onttrekking? Jy kan dit later voortsit';

  @override
  String get format => 'Formaat';

  @override
  String get fullscreen => 'Volskerm';

  @override
  String get gaplessPlayback => 'Gapinglose terugspeel';

  @override
  String get generate => 'Genereer';

  @override
  String get generateFromDates => 'Tydsbestek';

  @override
  String get generateFromDatesSubtitle => 'Genereer snitte wat jy in \'n tydsbestek geluister het';

  @override
  String get generateRandomPlaylist => 'Genereer ewekansige snitlys';

  @override
  String get genre => 'Genre';

  @override
  String get genres => 'Styl';

  @override
  String get goToAlbum => 'Gaan na album';

  @override
  String get goToArtist => 'Gaan na kunstenaar';

  @override
  String get goToChannel => 'Gaan na kanaal';

  @override
  String get goToFolder => 'Gaan na vouer';

  @override
  String get goodLooking => 'Lyk goed';

  @override
  String get grantStoragePermission => 'Gee stoortoestemming';

  @override
  String get group => 'Groep';

  @override
  String get groupArtworksByAlbum => 'Groepeer kunswerke volgens album';

  @override
  String get guide => 'Gids';

  @override
  String get hapticFeedback => 'Haptiese terugvoer';

  @override
  String get heightOfAlbumTile => 'Hoogte van albumteël';

  @override
  String get heightOfTrackTile => 'Hoogte van snitteël';

  @override
  String get hideSkipButtonAfter => 'Versteek slaan-oor-knoppie na';

  @override
  String get highMatches => 'Hoë ooreenkomste';

  @override
  String get highPerformance => 'Hoë werkverrigting';

  @override
  String get highlight => 'Hoogtepunt';

  @override
  String get history => 'Geskiedenis';

  @override
  String get historyImportMissingEntriesNote => 'Hierdie inskrywings kon nie in die biblioteek gevind word nie, as jy glo hulle bestaan, oorweeg dit om hulle handmatig by te voeg';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString luisters vir $oldTrackInfo sal vervang word met $newTrackInfo, bevestig?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Tuis';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12-uur formaat';

  @override
  String get hours => 'Ure';

  @override
  String get iReadAndAgree => 'Ek het gelees & stem saam';

  @override
  String get ifNotPlaying => 'Indien nie speel nie';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Aflaaie kan beperk word wanneer die toepassing batterybeperk is';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignoreer algemene voorvoegsels tydens sortering';

  @override
  String get ignores => 'Ignoreer';

  @override
  String get imageSource => 'Beeldbron';

  @override
  String get immersiveMode => 'Meeslepende modus';

  @override
  String get immersiveModeSubtitle => 'Versteek status- & navigasiebalke terwyl minispeler uitgebrei is';

  @override
  String get import => 'Voer in';

  @override
  String get importAll => 'Voer alles in';

  @override
  String get importLastFmHistory => 'Voer LastFm-geskiedenis in';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Gaan na $lastfmCsvLink\n\n2. Tik jou gebruikersnaam, haal en laai csv-lêer af.\n\n3. Kies die lêer op die volgende skerm.';
  }

  @override
  String get importTimeRange => 'Voer tydsbestek in';

  @override
  String get importYoutubeHistory => 'Voer Youtube-geskiedenis in';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Gaan na $takeoutLink\n\n2. Druk \"Multiple Formats\" en kies \"JSON\" langs \"History\".\n\n3. Druk \"All Youtube data included\", Ontkies Alles en kies slegs geskiedenis.\n\n4. Skep Uitvoer, Laai af & Pak uit.\n\n5. Kies \"watch-history.json\" op die volgende skerm.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString kanale suksesvol ingevoer',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText snitlyste suksesvol ingevoer',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Sluit video\'s in';

  @override
  String get indexRefreshRequired => 'Doen \'n verfris na verandering hiervan';

  @override
  String get indexer => 'Indekseerder';

  @override
  String get indexerNote => 'Nota: Onvolledige aantal kunswerke verwys na die gedupliseerde & nie-gevonde kunswerke';

  @override
  String get indexerSubtitle => 'Bestuur jou musiekbiblioteek';

  @override
  String get infinityQueueOnNextPrev => 'Oneindige tou op Volgende/Vorige';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'om volgende te druk terwyl die laaste item speel, sal na die eerste spring, en omgekeerd';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'ingevoeg';

  @override
  String get instantlyApplies => 'Pas onmiddellik toe';

  @override
  String get interactionReminder => 'Interaksieherinnering';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Keer seleksie om';

  @override
  String get issues => 'Kwessies';

  @override
  String get item => 'Item';

  @override
  String get jump => 'Spring';

  @override
  String get jumpToDay => 'Spring na Dag';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Spring na eerste snit nadat tou klaar is';

  @override
  String get keepCachedVersions => 'Hou gekaste weergawes';

  @override
  String get keepFileDates => 'Hou lêerdatums';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Minispeler is uitgebrei';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Minispeler is uitgebrei en \'n video speel';

  @override
  String get keepScreenAwakeNone => 'Moenie skerm wakker hou nie';

  @override
  String get keepScreenAwakeWhen => 'Hou skerm wakker wanneer';

  @override
  String get killPlayerAfterDismissingApp => 'Maak speler dood na die toepassing verwerp is';

  @override
  String get language => 'Taal';

  @override
  String get learnMore => 'Leer meer';

  @override
  String get leftAction => 'Linkeraksie';

  @override
  String get legacyAuthentication => 'Nalatenskap Verifikasie';

  @override
  String get libraryTabs => 'Biblioteektabs';

  @override
  String get libraryTabsReorder => 'Jy kan die geaktiveerde tabs herrangskik.';

  @override
  String get license => 'Lisensie';

  @override
  String get licenseSubtitle => 'Lisensies en Ooreenkomste Gebruik deur Namida';

  @override
  String get like => 'Hou van';

  @override
  String get liked => 'Gehou van';

  @override
  String get link => 'Skakel';

  @override
  String get listOfFolders => 'Lys van vouers';

  @override
  String get loadAll => 'Laai alles';

  @override
  String get loadingFile => 'Laai lêer';

  @override
  String get local => 'Plaaslik';

  @override
  String get localVideoMatching => 'Plaaslike video-ooreenstemming';

  @override
  String get login => 'Meld aan';

  @override
  String get longPressAction => 'Langdrukaksie';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Druk lank op die lirieke om volskerm te gaan';

  @override
  String get lostMemories => 'Verlore Herinneringe';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'rondom hierdie tyd, $numberString jaar gelede',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Verlore vennote';

  @override
  String get loudnessEnhancer => 'Hardheidsverbeteraar';

  @override
  String get lyricist => 'Liriekskrywer';

  @override
  String get lyrics => 'Lirieke';

  @override
  String get lyricsSource => 'Liriekebron';

  @override
  String get m3uPlaylist => 'M3U Snitlys';

  @override
  String get makeYourFirstListen => 'Maak jou eerste luister!';

  @override
  String get manage => 'Bestuur';

  @override
  String get manageYourAccounts => 'Bestuur jou rekeninge';

  @override
  String get manualBackup => 'Handmatig';

  @override
  String get manualBackupSubtitle => 'kies \'n spesifieke lêer';

  @override
  String get markAsRead => 'Merk as gelees';

  @override
  String get matchAllTracks => 'Pas by alle snitte';

  @override
  String get matchAllTracksNote => 'dit kan \'n impak op die ooreenstemmingspoed hê, aangesien dit alle snitte in jou biblioteek sal nagaan';

  @override
  String get matchingType => 'Ooreenstemmingstipe';

  @override
  String get maxAudioCacheSize => 'Maks oudiokasgrootte';

  @override
  String get maxImageCacheSize => 'Maks beeldkasgrootte';

  @override
  String get maxVideoCacheSize => 'Maks videokasgrootte';

  @override
  String get maximum => 'Maksimum';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store is geaktiveer, dit sal geen effek hê nie';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Kode';

  @override
  String get membershipCodeSentToEmail => 'Kode gestuur na jou e-pos';

  @override
  String get membershipDidntChange => 'Lidmaatskap het nie verander nie';

  @override
  String get membershipEnjoyNew => 'Geniet jou nuwe lidmaatskap';

  @override
  String get membershipFreeCoupon => 'Gratis koepon';

  @override
  String get membershipManage => 'Bestuur jou lidmaatskap';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Geen intekeninge gevind vir hierdie gebruiker nie';

  @override
  String get membershipSignInToPatreonAccount => 'Teken in op jou patreon-rekening';

  @override
  String get membershipUnknown => 'Onbekende Lidmaatskap';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Jy benodig lidmaatskap van $name1 of $name2 om veelvuldige rekeninge by te voeg';
  }

  @override
  String get merge => 'Voeg saam';

  @override
  String get metadataCache => 'Metadata-kas';

  @override
  String get metadataEditFailed => 'Kon nie metadata redigeer nie';

  @override
  String get metadataReadFailed => 'Kon nie metadata lees nie';

  @override
  String get minFileDuration => 'Minimum Snitduur';

  @override
  String get minFileSize => 'Minimum Lêergrootte';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimum snitduur om laaste gespeelde posisie te herstel';

  @override
  String get minValueCantBeMoreThanMax => 'Minimum waarde kan nie meer as die maksimum wees nie';

  @override
  String get minValueToCountTrackListen => 'Tel \'n luister na: ';

  @override
  String get minimizedMiniplayer => 'Geminimeerde minispeler';

  @override
  String get minimum => 'Minimum';

  @override
  String get minimumOneFolderSubtitle => 'Daar moet ten minste 1 vouer wees, voeg meer vouers by as jy hierdie een wil verwyder';

  @override
  String get minimumOneItem => 'Kon nie item verwyder nie';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ten minste $numberString items moet oorbly',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segmentduur';

  @override
  String get miniplayerCustomization => 'Minispeler-aanpassing';

  @override
  String get minutes => 'minute';

  @override
  String get missingEntries => 'Ontbrekende Inskrywings';

  @override
  String get missingTracks => 'Ontbrekende Snitte';

  @override
  String get mix => 'Mengsel';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Mengselsnitlys gegenereer deur youtube';

  @override
  String get mixes => 'Mengsels';

  @override
  String get mobile => 'Mobiel';

  @override
  String get month => 'Maand';

  @override
  String get months => 'Maande';

  @override
  String get mood => 'Luim';

  @override
  String get moods => 'Luime';

  @override
  String get more => 'Meer';

  @override
  String get mostPlayed => 'Mees Gespeel';

  @override
  String get multipleTracksTagsEditNote => 'Jy staan op die punt om hierdie snitte te redigeer,\nOnveranderde velde bly onaangeraak.';

  @override
  String get musicOfftopic => 'Musiek Van Die Onderwerp Af';

  @override
  String get name => 'Naam';

  @override
  String get nameContainsBadCharacter => 'Naam bevat slegte karakter';

  @override
  String get never => 'Nooit';

  @override
  String get newDirectory => 'Nuwe vouer';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Voeg Snitte By';

  @override
  String get newTracksMoods => 'Luim';

  @override
  String get newTracksMoodsSubtitle => 'Genereer snitte gebaseer op beskikbare luime';

  @override
  String get newTracksRandom => 'Ewekansig';

  @override
  String get newTracksRandomSubtitle => 'Kies ewekansige snitte uit jou biblioteek';

  @override
  String get newTracksRatings => 'Graderings';

  @override
  String get newTracksRatingsSubtitle => 'Genereer snitte wat spesifieke gradering het';

  @override
  String get newTracksRecommended => 'Aanbeveel';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Genereer snitte wat jy gewoonlik saam met $currentTrack geluister het';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Soortgelyke Vrystellingsdatum';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Genereer snitte wat rondom dieselfde tyd as $currentTrack vrygestel is';
  }

  @override
  String get newTracksUnknownYear => 'Snit het onbekende jaar';

  @override
  String get newest => 'Nuutste';

  @override
  String get next => 'Volgende';

  @override
  String get no => 'nee';

  @override
  String get noChangesFound => 'Geen veranderinge is gevind nie.';

  @override
  String get noEnoughTracks => 'Jy het nie veel snitte nie..';

  @override
  String get noExcludedFolders => 'Jy het geen uitgeslote vouers nie';

  @override
  String get noFolderChosen => 'Jy het geen vouer gekies nie';

  @override
  String get noMoodsAvailable => 'Geen luime beskikbaar nie';

  @override
  String get noNetworkAvailableToFetchData => 'Geen netwerk beskikbaar om data te haal nie';

  @override
  String get noTracksFound => 'Geen snitte is gevind nie';

  @override
  String get noTracksFoundBetweenDates => 'Hierdie tydsbestek het geen snitte nie.';

  @override
  String get noTracksFoundInDirectory => 'Geen snitte gevind in hierdie vouer nie';

  @override
  String get noTracksInHistory => 'Jy het nie genoeg snitte in geskiedenis nie';

  @override
  String get nonActive => 'Nie-Aktief';

  @override
  String get nonFavourites => 'Nie-Gunstelinge';

  @override
  String get none => 'Geen';

  @override
  String get normalizeAudio => 'Normaliseer oudio';

  @override
  String get normalizeAudioSubtitle => 'Normaliseer volume deur die herhalingswins-etiket of die inligting verskaf deur youtube te lees';

  @override
  String get notAvailableForYourDevice => 'Nie beskikbaar vir jou toestel nie';

  @override
  String get notSupportedForNetworkFiles => 'Nie ondersteun vir netwerklêers';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => 'Nota';

  @override
  String get notification => 'Kennisgewing';

  @override
  String get notifications => 'Kennisgewings';

  @override
  String get numberOfTracks => 'Aantal Snitte';

  @override
  String get ofLabel => 'van';

  @override
  String get offlineSearch => 'Vanlyn Soektog';

  @override
  String get offset => 'Afset';

  @override
  String get oldDirectory => 'Ou vouer';

  @override
  String get oldDirectoryStillHasTracks => 'Ou Vouer het steeds snitte, bevestig?';

  @override
  String get oldestWatch => 'Oudste Kyk';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'By Onderbreking';

  @override
  String get onNotificationTap => 'By Kennisgewing Tik';

  @override
  String get onOpeningYoutubeLink => 'By oopmaak van youtube-skakel';

  @override
  String get onSwiping => 'By Veeg';

  @override
  String get onVolumeZero => 'By volume 0';

  @override
  String get ongoing => 'Deurlopend';

  @override
  String get open => 'Maak oop';

  @override
  String get openApp => 'Maak Toep Oop';

  @override
  String get openInFileExplorer => 'Maak oop in Lêerverkenner';

  @override
  String get openInYoutubeView => 'Maak oop in Youtube-aansig';

  @override
  String get openMiniplayer => 'Maak Minispeler Oop';

  @override
  String get openQueue => 'Maak Tou Oop';

  @override
  String get openYoutubeLink => 'Maak Youtube-skakel Oop';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operasie $name vereis rekening, Teken in om voort te gaan';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operasie $operation vereis ten minste lidmaatskap $name';
  }

  @override
  String get or => 'of';

  @override
  String get others => 'Ander';

  @override
  String get output => 'Uitset';

  @override
  String get outro => 'Slot';

  @override
  String get overrideOldFilesInTheSameFolder => 'Oorskryf ou lêers in dieselfde vouer';

  @override
  String get palette => 'Palet';

  @override
  String get paletteMix => 'Mengsel';

  @override
  String get paletteNewMix => 'Nuwe Mengsel';

  @override
  String get paletteSelectedMix => 'Gekose Mengsel';

  @override
  String get parallelDownloads => 'Parallelle Aflaaie';

  @override
  String get parsed => 'ontleed';

  @override
  String get password => 'Wagwoord';

  @override
  String get path => 'Lêer Volle Pad';

  @override
  String get pause => 'Pouse';

  @override
  String get pauseFadeDuration => 'Pouse Vervaagduur';

  @override
  String get pausePlayback => 'Pouse terugspeel';

  @override
  String get percentage => 'Persentasie';

  @override
  String get performanceMode => 'Prestasie-modus';

  @override
  String get performanceNote => 'Mag prestasie beïnvloed';

  @override
  String get personalized => 'Gepersonaliseerd';

  @override
  String get personalizedRelatedVideos => 'Gepersonaliseerde Verwante Video\'s';

  @override
  String get personalizedRelatedVideosSubtitle => 'Deaktivering hiervan sal datagebruik verhoog';

  @override
  String get pickColorsFromDeviceWallpaper => 'Kies Kleure uit Toestelmuurpapier';

  @override
  String get pickFromStorage => 'Kies uit stoor';

  @override
  String get pinned => 'Vasgepen';

  @override
  String get pitch => 'Toonhoogte';

  @override
  String get plain => 'Gewoon';

  @override
  String get play => 'Speel';

  @override
  String get playAfter => 'Speel Na';

  @override
  String get playAfterNextPrev => 'Outospeel op Volgende/Vorige';

  @override
  String get playAll => 'Speel Alles';

  @override
  String get playFadeDuration => 'Speel Vervaagduur';

  @override
  String get playLast => 'Speel Laaste';

  @override
  String get playNext => 'Speel Volgende';

  @override
  String get playbackSetting => 'Terugspeel';

  @override
  String get playbackSettingSubtitle => 'Kan direk in die speler verkry word deur die oudioknoppie lank te druk';

  @override
  String get playlist => 'Snitlys';

  @override
  String get playlists => 'Snitlyste';

  @override
  String get playlistsImportM3uNative => 'Hierdie sal M3U-snitlyste invoer om slegs deur namida gebruik te word, gebruik as jy migreer';

  @override
  String get playlistsImportM3uSynced =>
      'Hierdie sal outomaties M3U-snitlyste vanaf indekseerdergouers invoer en hulle gesinchroniseer hou met die oorspronklike M3U-lêer. aktiveer as jy die snitlyste vanaf ander toepassings gebruik/wysig';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Voer M3U Snitlyste outomaties in';

  @override
  String get pleaseEnterADifferentName => 'Hierdie naam bestaan reeds :(\nprobeer asseblief \'n ander spoggerige naam';

  @override
  String get pleaseEnterALink => 'Voer asseblief \'n skakel in';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. is hierdie \'n youtube-skakel?';

  @override
  String get pleaseEnterAName => 'Voer asseblief \'n naam in';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Voorkom Gedupliseerde snitte';

  @override
  String get preventDuplicatedTracksSubtitle => 'Gebruik lêernaam om snitte uniek te identifiseer';

  @override
  String get preview => 'Voorskou';

  @override
  String get previous => 'Vorige';

  @override
  String get previousButtonReplays => 'Vorige knoppie speel weer';

  @override
  String get previousButtonReplaysSubtitle => 'indien gedruk terwyl huidige posisie meer as soekduur was';

  @override
  String get prioritizeEmbeddedLyrics => 'Prioritiseer ingebedde lirieke';

  @override
  String get priority => 'Prioriteit';

  @override
  String get private => 'Privaat';

  @override
  String get progress => 'Vordering';

  @override
  String get promptToChangeTrackPath => 'Gewoonlik gebeur dit wanneer jy die lêer buite namida verwyder/skuif/hernoem, Wil jy die huidige pad opdateer?';

  @override
  String get public => 'Publiek';

  @override
  String get queue => 'Tou';

  @override
  String get queues => 'Toue';

  @override
  String get random => 'Ewekansig';

  @override
  String get randomPicks => 'Ewekansige Keuses';

  @override
  String get rating => 'Gradering';

  @override
  String get reIndex => 'Her-indekseer';

  @override
  String get reIndexSubtitle => 'Herbou jou musiekbiblioteek van nuuts af';

  @override
  String get reIndexWarning => 'Hierdie proses mag \'n rukkie neem, afhangende van jou biblioteekgrootte.\n\nKunswerke sal nie her-indekseer word solank hulle nog bestaan nie';

  @override
  String get recentAlbums => 'Onlangse Albums';

  @override
  String get recentArtists => 'Onlangse Kunstenaars';

  @override
  String get recentListens => 'Onlangse Luisters';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Onlangs Bygevoeg';

  @override
  String get recordLabel => 'Platemaatskappy';

  @override
  String get refresh => 'Verfris';

  @override
  String get refreshLibrary => 'Verfris Biblioteek';

  @override
  String get refreshLibrarySubtitle => 'Kyk vir nuut bygevoegde of verwyderde musiek';

  @override
  String get refreshOnStartup => 'Verfris by begin';

  @override
  String get relatedVideos => 'Verwante video\'s';

  @override
  String get rememberAudioOnlyMode => 'Onthou slegs-klank-modus';

  @override
  String get remixer => 'Remikser';

  @override
  String get remove => 'Verwyder';

  @override
  String get removeDuplicates => 'Verwyder Duplikate';

  @override
  String get removeFromFavourites => 'Verwyder uit gunstelinge';

  @override
  String get removeFromLibrary => 'Verwyder uit biblioteek';

  @override
  String get removeFromPlaylist => 'Verwyder Uit Snitlys';

  @override
  String get removeQueue => 'Verwyder Tou';

  @override
  String get removeSourceFromHistory => 'Verwyder bron uit geskiedenis';

  @override
  String get removeWhitespaces => 'Verwyder Witspasies';

  @override
  String get removed => 'Verwyder';

  @override
  String get rename => 'Hernoem';

  @override
  String get renamePlaylist => 'Hernoem Snitlys';

  @override
  String get reorderable => 'Herrangskikbaar';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Herhaal vir nog $number keer',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Herhaalmodus';

  @override
  String get repeatModeAll => 'Herhaal Alle Tou';

  @override
  String get repeatModeNone => 'Stop op Laaste Snit';

  @override
  String get repeatModeOne => 'Herhaal Huidige Snit';

  @override
  String get replaceAllListensWithAnotherTrack => 'Vervang alle luisters met \'n ander snit';

  @override
  String get replies => 'Antwoorde';

  @override
  String get reply => 'Antwoord';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Vereis skoonmaak van beeldkas en her-indeksering';

  @override
  String get rescanVideos => 'Herskandeer video\'s';

  @override
  String get resetBrightness => 'Herstel helderheid';

  @override
  String get resetToDefault => 'Stel na';

  @override
  String get respectNoMedia => 'Respekteer .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Moenie vouers insluit wat .nomedia het nie';

  @override
  String get restart => 'Herbegin';

  @override
  String get restoreBackup => 'Herstel Rugsteun';

  @override
  String get restoreDefaults => 'Herstel Verstekwaardes';

  @override
  String get restoredBackupSuccessfully => 'Rugsteun Herstel';

  @override
  String get restoredBackupSuccessfullySub => 'Rugsteunlêer is suksesvol herstel';

  @override
  String get resume => 'Hervat';

  @override
  String get resumeIfWasInterrupted => 'Hervat indien gepouseer deur onderbreking';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Hervat indien gepouseer deur volume';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Hervat indien gepouseer vir minder as $numberString minute',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Keer YouTube terug';

  @override
  String get reverseOrder => 'Omgekeerde Volgorde';

  @override
  String get rightAction => 'Regteraksie';

  @override
  String get ringtone => 'Luitoon';

  @override
  String get sameDirectoryOnly => 'Slegs selfde vouer';

  @override
  String get sample => 'Monster';

  @override
  String get sampleRate => 'Monstertempo';

  @override
  String get save => 'Stoor';

  @override
  String get saveToLibrary => 'Stoor na biblioteek';

  @override
  String get savedIn => 'Gestoor in';

  @override
  String get scaleMultiplier => 'Skaalvermenigvuldiger';

  @override
  String get search => 'Soek';

  @override
  String get searchYoutube => 'Soek YouTube';

  @override
  String get seconds => 'sekondes';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Sien Projekkode op $site';
  }

  @override
  String get seekDuration => 'Soekduur';

  @override
  String get seekDurationInfo => 'Jy kan op huidige duur tik om terug te soek & totale duur om vorentoe te soek';

  @override
  String get seekbar => 'Soekbalk';

  @override
  String get selectAll => 'Kies Alles';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Kies lêers reeds in plaaslike biblioteek';

  @override
  String get selectedTracks => 'Gekose Snitte';

  @override
  String get selfPromotion => 'Selfpromosie';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Hierdie woorde sal nie geskei word nie';

  @override
  String get separatorsMessage => 'Nie nodig om spasies in te voeg nie, tensy jy \'n letter/simbool wil gebruik wat in \'n hele woord gevind kan word (soos x en ft.)';

  @override
  String get serverAddress => 'Bedieneradres';

  @override
  String get setAs => 'Stel as';

  @override
  String get setAsDefault => 'Stel as Verstek';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Stel lêer laas gewysig as video-oplaaidatum';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Stel luime';

  @override
  String get setMoodsSubtitle => 'Gebruik kommas (,) om tussen hulle te skei';

  @override
  String get setRating => 'Stel Gradering';

  @override
  String get setTags => 'Stel etikette';

  @override
  String get setYoutubeLink => 'Stel Youtube-skakel';

  @override
  String get settings => 'Instellings';

  @override
  String get setupFirstStartup => 'Stel eerste begin op';

  @override
  String get share => 'Deel';

  @override
  String get shareLogs => 'Deel logs';

  @override
  String get shortcuts => 'Kortpaaie';

  @override
  String get shouldDuck => 'Moet duck';

  @override
  String get shouldDuckNote => 'Dui aan dat die volume verlaag moet word. bv: kennisgewing';

  @override
  String get shouldPause => 'Moet pouseer';

  @override
  String get shouldPauseNote => 'Dui aan dat die terugspeel gepouseer moet word. bv: oproepe';

  @override
  String get showAll => 'Wys Alles';

  @override
  String get showChannelWatermarkInFullscreen => 'Wys kanaalwatermerk in volskerm';

  @override
  String get showFailedOnly => 'Wys slegs Mislukte';

  @override
  String get showHideUnknownFields => 'Wys/versteek Onbekende Velde';

  @override
  String get showInSeekbar => 'Wys in Soekbalk';

  @override
  String get showMixPlaylistsIn => 'Wys Mengsels in';

  @override
  String get showMore => 'Wys meer';

  @override
  String get showShortVideosIn => 'Wys Shorts in';

  @override
  String get showSkipButton => 'Wys Slaan-oor-knoppie';

  @override
  String get showVideoEndcards => 'Wys video-eindkaarte';

  @override
  String get showWebm => 'Wys webm';

  @override
  String get shuffle => 'Skommel';

  @override
  String get shuffleAll => 'Skommel Alles';

  @override
  String get shuffleNext => 'Skommel Volgende';

  @override
  String get signIn => 'Teken in';

  @override
  String get signInCanceled => 'Intekning is gekanselleer';

  @override
  String get signInFailed => 'Intekning het misluk';

  @override
  String get signInToYourAccount => 'Teken in op jou rekening';

  @override
  String get signInYouDontHaveAccount => 'Jy het nie enige rekening ingeteken nie';

  @override
  String get signInYouNeedAccountToViewPage => 'Jy benodig \'n rekening om hierdie bladsy te sien';

  @override
  String get signOut => 'Teken uit';

  @override
  String signOutFromName({required String name}) {
    return 'Teken uit van $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Intekning laat basiese gebruik toe';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Kry vroeë toegang deur patreon of deur koepon te gebruik';

  @override
  String get similarDiscoverDate => 'Soortgelyke Ontdekkingsdatum';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Genereer snitte wat rondom dieselfde tyd as $currentTrack ontdek is';
  }

  @override
  String get similarTimeRange => 'Soortgelyke Tydsbestek';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Genereer snitte wat jy rondom dieselfde tyd as $currentTrack geluister het';
  }

  @override
  String get singles => 'Enkelsnitte';

  @override
  String get size => 'Grootte';

  @override
  String get skip => 'Slaan oor';

  @override
  String get skipCountTracking => 'Slaan-oor-tellingopsporing';

  @override
  String get skipSilence => 'Slaan Stilte Oor';

  @override
  String get skipSponsorSegmentsInVideos => 'Slaan Borgsegmente in Video\'s Oor';

  @override
  String get sleepAfter => 'Slaap Na';

  @override
  String get sleepTimer => 'Slaaptydhouer';

  @override
  String get socials => 'Sosiale Netwerke';

  @override
  String get socialsSubtitle => 'Sluit us aan op ons platforms vir opdaterings, wenke, besprekings en idees';

  @override
  String get someWebServersRequireAuthentication => '\'n Paar webbedieners vereis stawing. Dateer asseblief credentials om toegang tot jou biblioteek te behou.';

  @override
  String get sortBy => 'Sorteer volgens';

  @override
  String get source => 'Bron';

  @override
  String get speed => 'Spoed';

  @override
  String get sponsor => 'Borg';

  @override
  String get sponsorblock => 'SponsorBlokkeer';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Ranglys';

  @override
  String get staggeredAlbumGridView => 'Verspringende Albumroosteraansig';

  @override
  String get start => 'Begin';

  @override
  String get stats => 'Statistieke';

  @override
  String get statsSubtitle => 'Hier is bietjie inligting oor jou biblioteek';

  @override
  String get stop => 'Stop';

  @override
  String get stopAfterThisTrack => 'Stop na hierdie snit';

  @override
  String get stopAfterThisVideo => 'Stop na hierdie video';

  @override
  String get storagePermissionDenied => 'Toestemming Geweier';

  @override
  String get storagePermissionDeniedSubtitle => 'Laat asseblief toegang toe om hierdie aksie uit te voer';

  @override
  String get stretchLyricsDuration => 'Rek Lirieke Duur';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Skryf in';

  @override
  String get subscribed => 'Ingeteken';

  @override
  String get subscriber => 'Intekenaar';

  @override
  String get subscribers => 'Intekenare';

  @override
  String get succeeded => 'Geslaag';

  @override
  String suggestionSubtitle({required String site}) {
    return '\'n Kwessie of Voorstel? Maak \'n kwessie oop op $site';
  }

  @override
  String get support => 'Ondersteuning';

  @override
  String get supremacy => 'Oppergesag';

  @override
  String get sussyBaka => 'Bruh geen snitte';

  @override
  String get swipeActions => 'Veegaksies';

  @override
  String get swipeToOpenDrawer => 'Veeg om laai oop te maak';

  @override
  String get synced => 'Gesinchroniseer';

  @override
  String get synopsis => 'Sinopsis';

  @override
  String get tagFields => 'Etiketvelde';

  @override
  String get tags => 'Etikette';

  @override
  String get tapAction => 'Tikaksie';

  @override
  String get tapToSeek => 'Tik om te soek';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Temamodus';

  @override
  String get themeModeDark => 'Donker';

  @override
  String get themeModeLight => 'Lig';

  @override
  String get themeModeSystem => 'Stelsel';

  @override
  String get themeSettings => 'Tema';

  @override
  String get themeSettingsSubtitle => 'Die algehele atmosfeer van jou speler';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Hierdie snitlys het aktiewe sorteerders, deaktiveer hulle asseblief voor herrangskikking.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Hierdie video is waarskynlik verwyder of op privaat gestel.';

  @override
  String get thumbnails => 'Duimnaels';

  @override
  String get title => 'Titel';

  @override
  String get top => 'Bo';

  @override
  String get topComments => 'Top kommentaar';

  @override
  String get topCommentsSubtitle => 'Vertoon kommentaar bo in plaas van onder';

  @override
  String get topRecentAlbums => 'Top Onlangse Albums';

  @override
  String get topRecentArtists => 'Top Onlangse Kunstenaars';

  @override
  String get topRecents => 'Top Onlangse';

  @override
  String get totalListenTime => 'Totale Luistertyd';

  @override
  String get totalListens => 'Totale Luisters';

  @override
  String get totalTracks => 'Totale Snitte';

  @override
  String get totalTracksDuration => 'Totale Snitte Duur';

  @override
  String get track => 'Snit';

  @override
  String get trackArtistsSeparator => 'Kunstenaarskeiers';

  @override
  String get trackGenresSeparator => 'Genreskeiers';

  @override
  String get trackInfo => 'Snitinligting';

  @override
  String get trackNotFound => 'Snit nie gevind nie';

  @override
  String get trackNumber => 'Snitnommer';

  @override
  String get trackNumberTotal => 'Snit Totaal';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Ou naam: \"$oldName\"\n\nNuwe naam: \"$newName\"\n\nIs jy seker?';
  }

  @override
  String get trackPlayMode => 'Speelmodus';

  @override
  String get trackPlayModeSearchResults => 'Soekresultate';

  @override
  String get trackPlayModeSelectedOnly => 'Slegs gekose snit';

  @override
  String get trackPlayModeTrackAlbum => 'Snit se Album';

  @override
  String get trackPlayModeTrackArtist => 'Snit se Hoofkunstenaar';

  @override
  String get trackPlayModeTrackGenre => 'Snit se Genre';

  @override
  String get trackThumbnailSizeInList => 'Grootte van Snitduimnael';

  @override
  String get trackTileCustomization => 'Snitteël-aanpassing';

  @override
  String get trackTileItemsSeparator => 'Itemsskeier';

  @override
  String get tracks => 'Snitte';

  @override
  String get tracksExcludedByNomedia => 'Snitte Uitgesluit deur .nomedia';

  @override
  String get tracksInfo => 'Snitinfo';

  @override
  String get underrated => 'Onderwaardeer';

  @override
  String get undo => 'Maak ongedaan';

  @override
  String get undoChanges => 'Maak Veranderinge Ongedaan?';

  @override
  String get undoChangesDeletedPlaylist => 'Maak verwyderde snitlys ongedaan';

  @override
  String get undoChangesDeletedQueue => 'Maak verwyderde Tou ongedaan';

  @override
  String get undoChangesDeletedTrack => 'Maak verwyderde snit ongedaan';

  @override
  String get uniqueArtworkHash => 'Unieke Kunswerk-hash';

  @override
  String get unlimited => 'Onbeperk';

  @override
  String get unlisted => 'Ongelys';

  @override
  String get unlock => 'Ontsluit';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Dateer op';

  @override
  String get updateDirectoryPath => 'Dateer vouerpad op';

  @override
  String get updateMissingTracksOnly => 'Dateer slegs ontbrekende snitte op';

  @override
  String get updating => 'Besig om op te dateer';

  @override
  String get useCollapsedSettingTiles => 'Gebruik Ingeplofte Instellingsteëls';

  @override
  String get useMediaStore => 'Gebruik Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ onmiddellike indekseringstyd\nx respekteer .nomedia sal gedwing word\nx sommige metadata-etikette sal ontbreek\nx youtube-integrasie vir plaaslike biblioteek sal nie werk nie';

  @override
  String get usePitchBlack => 'Gebruik Pikswart';

  @override
  String get usePitchBlackSubtitle => 'Nuttig vir AMOLED-skerms.. en lyk koeler';

  @override
  String get used => 'Gebruik';

  @override
  String get value => 'Waarde';

  @override
  String get valueBetween50200 => 'Waarde moet tussen 50% en 200% wees';

  @override
  String get vibration => 'Vibrasie';

  @override
  String get vibrationType => 'Vibrasietipe';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Videokas';

  @override
  String get videoCacheFile => 'Gekaste Videolêer';

  @override
  String get videoCacheFiles => 'Gekaste Videolêers';

  @override
  String get videoOnly => 'Slegs Video';

  @override
  String get videoPlaybackSource => 'Videobron';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Hierdie sal prioriteit gee aan plaaslike video\'s, indien nie gevind nie sal dit van youtube haal';

  @override
  String get videoPlaybackSourceLocal => 'Plaaslike Video\'s';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Kyk of enige videolêer (gevind binne die gekose vouerelys) \'n lêernaam het wat die lêernaam van die snit bevat';

  @override
  String get videoPlaybackSourceYoutube => 'Van Youtube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Kyk in snit se lêernaam & kommentaar vir enige ooreenstemmende youtube-skakel, video\'s word gekas vir latere gebruik.';

  @override
  String get videoQuality => 'Videokwaliteit';

  @override
  String get videoQualitySubtitle => 'Hoogste kwaliteit beskikbaar sal gekies word.';

  @override
  String get videoQualitySubtitleNote =>
      'Dis altyd goed om meer alternatiewe te hou vir ingeval \'n kwaliteit nie gevind word nie, andersins sal dit terugval na die swakste kwaliteit';

  @override
  String get videos => 'Video\'s';

  @override
  String get view => 'kyk';

  @override
  String get viewAll => 'Wys Alles';

  @override
  String get views => 'kyke';

  @override
  String get volume => 'Volume';

  @override
  String get warning => 'Waarskuwing';

  @override
  String get waveformBarsCount => 'Golfvormstawe Telling';

  @override
  String get webmNoEditTagsSupport => 'WEBM-formaat ondersteun nie etiketredigering nie';

  @override
  String get week => 'Week';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Jaar';

  @override
  String get yes => 'ja';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Jou huidige lidmaatskap is $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Jou pasgemaakte volgorde sal verlore gaan, Is jy seker?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Musiek';

  @override
  String get youtubeSettingsSubtitle => 'Pas Youtube-ervaring aan';

  @override
  String get youtubeStyleMiniplayer => 'Youtube-styl Minispeler';

  @override
  String get ytPreferNewComments => 'Verkies nuwe kommentaar wanneer moontlik';

  @override
  String get ytPreferNewCommentsSubtitle => 'Gekaste weergawe sal slegs gebruik word wanneer daar geen verbinding is nie';
}
