// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Serbian (`sr`).
class AppLocalizationsSr extends AppLocalizations {
  AppLocalizationsSr([String locale = 'sr']) : super(locale);

  @override
  String get about => 'О апликацији';

  @override
  String get active => 'Активно';

  @override
  String get add => 'Додај';

  @override
  String get addAccount => 'Додај налог';

  @override
  String get addAll => 'Додај све';

  @override
  String get addAllAndRemoveOldOnes => 'Додај све и уклони старе';

  @override
  String get addAsANewPlaylist => 'Додај као нову плејлисту';

  @override
  String get addAudioToLocalLibrary => 'Додај аудио снимак у локалну збирку';

  @override
  String get addFolder => 'Додај фолдер';

  @override
  String get addLanguage => 'Додај језик';

  @override
  String get addLanguageSubtitle => 'Помозите у превођењу апликације Namida на ваш језик';

  @override
  String get addLrcFile => 'Додај LRC фајл';

  @override
  String get addMoreFromThisAlbum => 'Додај још из овог албума у редослед';

  @override
  String get addMoreFromThisArtist => 'Додај још од овог извођача у редослед';

  @override
  String get addMoreFromThisFolder => 'Додај још из овог фолдера у редослед';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Додај још из $media у редослед';
  }

  @override
  String get addOnlyMissing => 'Додај само недостајуће';

  @override
  String get addToFavourites => 'Додај у омиљене';

  @override
  String get addToPlaylist => 'Додај на плејлисту';

  @override
  String get addTracksAtTheBeginning => 'Add tracks at the beginning';

  @override
  String get added => 'додато';

  @override
  String get advanced => 'Напредно';

  @override
  String get advancedSettings => 'Напредно';

  @override
  String get advancedSettingsSubtitle => 'Напредна подешавања, не дирајте';

  @override
  String get alarm => 'Аларм';

  @override
  String get album => 'Албум';

  @override
  String get albumArtist => 'Извођач албума';

  @override
  String get albumArtists => 'Извођачи албума';

  @override
  String get albumIdentifiers => 'Идентификатори албума';

  @override
  String get albumThumbnailSizeInList => 'Величина сличице албума';

  @override
  String get albumTileCustomization => 'Прилагођавање плочице албума';

  @override
  String get albums => 'Албуми';

  @override
  String get albumsCount => 'Број албума';

  @override
  String get all => 'Све';

  @override
  String get allTime => 'Све време';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Увек';

  @override
  String get alwaysAsk => 'Увек питај';

  @override
  String get alwaysDim => 'Увек затамњуј';

  @override
  String get alwaysExpandedSearchbar => 'Увек проширена трака за претрагу';

  @override
  String get alwaysRestore => 'Увек врати';

  @override
  String get animatingThumbnailIntensity => 'Интензитет анимације сличице';

  @override
  String get animatingThumbnailInversed => 'Инверзне анимације';

  @override
  String get animatingThumbnailInversedSubtitle => 'Високи врхунци ће узроковати да се сличица смањи';

  @override
  String get anotherProcessIsRunning => 'Други процес је већ покренут.';

  @override
  String get appIcon => 'App Icon';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Извођач';

  @override
  String get artists => 'Извођачи';

  @override
  String get artwork => 'Уметничко дело';

  @override
  String get artworkGestures => 'Покрети уметничког дела';

  @override
  String get artworks => 'Уметничка дела';

  @override
  String get audio => 'Аудио снимак';

  @override
  String get audioCache => 'Кеш аудио снимка';

  @override
  String get audioOnly => 'Само аудио снимак';

  @override
  String get auto => 'Аутоматски';

  @override
  String get autoBackupInterval => 'Интервал аутоматског прављења резервне копије';

  @override
  String get autoColoring => 'Аутоматско бојење';

  @override
  String get autoColoringSubtitle => 'Аутоматско бирање боје плејера из тренутних уметничких дела';

  @override
  String get autoExtractTagsFromFilename => 'Аутоматско издвајање из назива фајла';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Аутоматско издвајање наслова и извођача из наслова видео снимка';

  @override
  String get autoGenerated => 'Аутоматски генерисано';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => 'Аутоматски започни радио';

  @override
  String get autoStartRadioSubtitle => 'Аутоматски додаје микс плејлисту када пуштате једну нумеру';

  @override
  String get automaticBackup => 'Аутоматски';

  @override
  String get automaticBackupSubtitle => 'Аутоматски примењује најновији фајл резервне копије који се налази на локацији резервне копије';

  @override
  String get backupAndRestore => 'Резервна копија и враћање података';

  @override
  String get backupAndRestoreSubtitle => 'Направите резервну копију базе података и подешавања';

  @override
  String get balanced => 'Балансирано';

  @override
  String get beta => 'Бета';

  @override
  String get betweenDates => 'Између датума';

  @override
  String get bitrate => 'Брзина преноса';

  @override
  String get blacklist => 'Црна листа';

  @override
  String get borderRadiusMultiplier => 'Множилац радијуса границе';

  @override
  String get cache => 'Кеш';

  @override
  String get cancel => 'Откажи';

  @override
  String get canceled => 'Отказано';

  @override
  String get changed => 'Промењено';

  @override
  String get changelog => 'Евиденција промена';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Канал';

  @override
  String get channels => 'Канали';

  @override
  String get check => 'Провери';

  @override
  String get checkForMore => 'Провери за још';

  @override
  String get checkList => 'Листа провера';

  @override
  String get choose => 'Изабери';

  @override
  String get chooseWhatToClear => 'Изаберите шта ћете избрисати';

  @override
  String get claim => 'Узми';

  @override
  String get clear => 'Очисти';

  @override
  String get clearAudioCache => 'Очисти кеш аудио снимака';

  @override
  String get clearImageCache => 'Очисти кеш слика';

  @override
  String get clearImageCacheWarning => 'Упозорење: Резултираће збирком без слика. Користити само за обнављање кеша слика.';

  @override
  String get clearTrackItem => 'Очисти нумере';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Очисти $numberString нумера',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Очисти кеш видео снимака';

  @override
  String get clearVideoCacheNote => 'Можете изабрати шта ћете избрисати.';

  @override
  String get clock => 'Сат';

  @override
  String get colorPalette => 'Палета боја';

  @override
  String get colorPaletteNote1 => 'Дуго притисните боју да бисте је уклонили';

  @override
  String get colorPaletteNote2 => 'Додирните микс да бисте га користили као подразумевану боју';

  @override
  String get colorPalettes => 'Палете боја';

  @override
  String get comment => 'Коментар';

  @override
  String get comments => 'Коментари';

  @override
  String get composer => 'Композитор';

  @override
  String get compress => 'Компресуј';

  @override
  String get compressImages => 'Компресуј слике';

  @override
  String get compressionPercentage => 'Проценат компресије';

  @override
  String get configure => 'Подесите';

  @override
  String get confirm => 'Потврди';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Копирано уметничко дело';

  @override
  String get copiedToClipboard => 'Копирано у привремену меморију';

  @override
  String get copy => 'Копирај';

  @override
  String get corruptedFile => 'Није могуће рашчланити фајл, можда је оштећен';

  @override
  String get couldntOpen => 'Није могуће отворити :(';

  @override
  String get couldntOpenYtLink => 'Нема доступног YouTube линка за ову нумеру';

  @override
  String get couldntPlayFile => 'Није могуће пустити фајл';

  @override
  String get couldntRenamePlaylist => 'Није могуће преименовати плејлисту';

  @override
  String get couldntSaveImage => 'Није могуће сачувати слику';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Земља';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Направи';

  @override
  String get createBackup => 'Направи резервну копију';

  @override
  String get createNewPlaylist => 'Направи нову плејлисту';

  @override
  String get createdBackupSuccessfully => 'Резервна копија је направљена';

  @override
  String get createdBackupSuccessfullySub => 'Фајл резервне копије је успешно направљен';

  @override
  String get crossPlatformSync => 'Cross-Platform Sync';

  @override
  String get crossfadeDuration => 'Трајање претапања';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Аутоматска активација претапања у последњих $secondsString секунди',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Не активирај претапање аутоматски';

  @override
  String get custom => 'Прилагођено';

  @override
  String get customizations => 'Прилагођавања';

  @override
  String get customizationsSubtitle => 'Прилагодите изглед вашег плејера, учините га својим';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => 'База података';

  @override
  String get date => 'Датум';

  @override
  String get dateAdded => 'Датум додавања';

  @override
  String get dateCreated => 'Датум прављења';

  @override
  String get dateModified => 'Датум измене';

  @override
  String get dateTimeFormat => 'Формат датума и времена';

  @override
  String get day => 'Дан';

  @override
  String get days => 'Дана';

  @override
  String get defaultBackupLocation => 'Подразумевана локација резервне копије';

  @override
  String get defaultColor => 'Подразумевана боја';

  @override
  String get defaultColorSubtitle => 'Подесите боју коју ће користити плејер';

  @override
  String get defaultDownloadLocation => 'Подразумевана локација преузимања';

  @override
  String get defaultLabel => 'Подразумевано';

  @override
  String get defaultLibraryTab => 'Подразумевана картица збирке';

  @override
  String get delete => 'Избриши';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Избрисати $countString фајлова који представљају $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Трајно брисање $numberText из своје меморије';
  }

  @override
  String get deletePlaylist => 'Брисање плејлисте';

  @override
  String get deleteTempFiles => 'Избриши привремене фајлове';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Опис';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Да ли сте мислили';

  @override
  String get dimIntensity => 'Интензитет затамњења';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Затамњење мини-плејера након $secondsString секунди неактивности',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Директоријум не постоји';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'Онемогући све';

  @override
  String get disableReordering => 'Онемогући преуређивање';

  @override
  String get disableSearchCleanup => 'Онемогући чишћење претраге';

  @override
  String get discNumber => 'Број диска';

  @override
  String get discNumberTotal => 'Укупно диска';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Не свиђа ми се';

  @override
  String get dismissibleMiniplayer => 'Одбацивајући мини-плејер';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => 'Датум у горњем десном углу картице албума';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Приказ датума албума на картици албума у горњем десном углу';

  @override
  String get displayArtistBeforeTitle => 'Прикажи извођача пре наслова';

  @override
  String get displayArtworkOnLockscreen => 'Прикажи уметничко дело на закључаном екрану';

  @override
  String get displayAudioInfoInMiniplayer => 'Прикажи информације о аудио снимку';

  @override
  String get displayFavButtonInNotification => 'Прикажи дугме „Омиљено“ у обавештењу';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Сличица ће се можда померити.';

  @override
  String get displayFavouriteIconInTrackTile => 'Прикажи дугме „Омиљено“';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Прикажи преостало трајање уместо укупног';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => 'Прикажи трећу ставку у сваком реду';

  @override
  String get displayThirdRowInTrackTile => 'Прикажи трећи ред';

  @override
  String get displayTrackNumberInAlbumPage => 'Прикажи број нумере на страници албума';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Приказ мале кутије која садржи број нумере на страници албума';

  @override
  String get doNothing => 'Не ради ништа';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Готово';

  @override
  String get dontAskAgain => 'Не питај поново';

  @override
  String get dontDim => 'Не затамњуј';

  @override
  String get dontRestorePosition => 'Не враћај';

  @override
  String get dontResume => 'Не настављај';

  @override
  String get doubleTapToToggleLyrics => 'Двапут додирните да бисте укључили/искључили текст';

  @override
  String get download => 'Преузми';

  @override
  String get downloadingWillOverrideIt => 'Преузимање ће га преписати';

  @override
  String get downloads => 'Преузимања';

  @override
  String get downloadsMetadataTags => 'Ознаке метаподатака преузимања';

  @override
  String get downloadsMetadataTagsSubtitle => 'Подразумевано издвојите извођача, наслов и албум из информација о видео снимку';

  @override
  String get dragToSeek => 'Превуците за тражење';

  @override
  String get duckAudio => 'Пригуши аудио снимак';

  @override
  String get duplicatedItemsAdding => 'Покушавате да додате неке ставке које већ постоје на овој плејлисти';

  @override
  String get duplicatedTracks => 'Дуплиране нумере';

  @override
  String get duration => 'Трајање';

  @override
  String get edgeColorsSwitching => 'Промена боја ивица';

  @override
  String get edit => 'Измени';

  @override
  String get editArtwork => 'Измени уметничко дело';

  @override
  String get editTags => 'Измени ознаке';

  @override
  String get email => 'Имејл';

  @override
  String get emptyNonMeaningfulTagFields => 'имате поља с празним/бесмисленим вредностима, уверите се да заиста желите да их измените';

  @override
  String get emptyValue => 'Празна вредност';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Омогући ефекат замагљивања';

  @override
  String get enableBottomNavBar => 'Омогући доњу траку за навигацију';

  @override
  String get enableBottomNavBarSubtitle => 'Ставке се налазе унутар фиоке за оба начина';

  @override
  String get enableClipboardMonitoring => 'Омогући праћење привремене меморије';

  @override
  String get enableClipboardMonitoringSubtitle => 'Омогућава налепљивање линкова и текстова унутар траке за претрагу у покрету';

  @override
  String get enableCrossfadeEffect => 'Омогући ефекат претапања';

  @override
  String get enableFadeEffectOnPlayPause => 'Омогућите ефекат тамњења при пуштању/паузи';

  @override
  String get enableFoldersHierarchy => 'Омогући хијерархију фолдера';

  @override
  String get enableGlowEffect => 'Омогући ефекат сјаја';

  @override
  String get enableM3uSync => 'Омогући M3U синхронизацију';

  @override
  String get enableM3uSyncNote1 => 'M3U синхронизација омогућава чување промена плејлиста у оригиналном M3U фајлу';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Ако нешто пође по злу, резервна копија ове плејлисте ће се наћи на $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Ако је одбијено, све промене урађене на овој плејлисти ће бити изгубљене при поновном покретању';

  @override
  String get enableMiniplayerParticles => 'Омогући покретне честице';

  @override
  String get enableParallaxEffect => 'Омогући ефекат паралаксе';

  @override
  String get enablePartyMode => 'Омогући режим журке';

  @override
  String get enablePartyModeSubtitle => 'Примените фенси ефекат дисања ивица';

  @override
  String get enablePictureInPicture => 'Омогући слику-у-слици';

  @override
  String get enableReordering => 'Омогући преуређивање';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Омогући чишћење претраге';

  @override
  String get enableSearchCleanupSubtitle => 'Сви симболи и размаци ће бити игнорисани';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => 'Омогући репродукцију видео снимка';

  @override
  String get enterSymbol => 'Унесите симбол';

  @override
  String get equalizer => 'Еквилајзер';

  @override
  String get error => 'Грешка';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Грешка при пуштању нумере';

  @override
  String get excludedFodlers => 'Изузети фолдери';

  @override
  String get exit => 'Изађи';

  @override
  String get exitAppSubtitle => 'Додирните поново да бисте изашли';

  @override
  String get expandedMiniplayer => 'Проширени мини-плејер';

  @override
  String get exportAsM3u => 'Извези као M3U';

  @override
  String get extension => 'Додатак';

  @override
  String get externalFiles => 'Спољни фајлови';

  @override
  String get extract => 'Издвој';

  @override
  String get extractAllColorPalettes => 'Издвој све палете боја';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Издвојити преосталих $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Издвој „feat.“ извођаче из наслова';

  @override
  String get extractFeatArtistSubtitle => 'Издвајање (feat. X) и (ft. X) извођаче, као нови унос извођача.';

  @override
  String get extractingInfo => 'Информације о издвајању';

  @override
  String get extras => 'Додатно';

  @override
  String get extrasSubtitle => 'Додатна подешавања за побољшање вашег искуства';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => 'Неуспешно';

  @override
  String get failedEdits => 'Неуспешне измене';

  @override
  String get favourites => 'Омиљени';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Прикупљање';

  @override
  String get fetchingOfAllVideos => 'Прикупљање свих видео снимака';

  @override
  String get file => 'Фајл';

  @override
  String get fileAlreadyExists => 'Фајл већ постоји';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Назив фајла';

  @override
  String get fileNameWoExt => 'Назив фајла без додатка';

  @override
  String get filenameShouldntStartWith => 'Назив фајла не треба почињати са';

  @override
  String get files => 'Фајлови';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => 'Филтрирање албума';

  @override
  String get filterArtists => 'Филтрирање извођача';

  @override
  String get filterGenres => 'Филтрирање жанрова';

  @override
  String get filterPlaylists => 'Филтрирање плејлиста';

  @override
  String get filterTracks => 'Филтриране нумера';

  @override
  String get filterTracksBy => 'Филтрирање нумера на листама претраге према';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Нумере филтриране по величини и трајању';

  @override
  String get finished => 'Завршено';

  @override
  String get finishedUpdatingLibrary => 'Завршено ажурирање збирке';

  @override
  String get firstListen => 'Прво слушање';

  @override
  String get fixYtdlpBigThumbnailSize => 'Поправи yt-dlp велику величину сличице';

  @override
  String get floatingActionButton => 'Плутајуће дугме радње';

  @override
  String get folder => 'Фолдер';

  @override
  String get folderName => 'Назив фолдера';

  @override
  String get folders => 'Фолдера';

  @override
  String get fontScale => 'Скала фонта';

  @override
  String get forceMiniplayerFollowTrackColors => 'Присили мини-плејер да прати боје нумера';

  @override
  String get forceSquaredAlbumThumbnail => 'Присили квадратне сличице албума';

  @override
  String get forceSquaredThumbnailNote => 'Величина сличице и висина плочице НИСУ једнаке, квадратни изглед неће бити како се очекивало. Желите ли да их учините једнаким?';

  @override
  String get forceSquaredTrackThumbnail => 'Присили квадратну сличицу нумере';

  @override
  String get forceStopColorPaletteGeneration => 'Присилно зауставити издвајање палета боја? Можете наставити касније';

  @override
  String get format => 'Формат';

  @override
  String get fullscreen => 'Цео екран';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => 'Генериши';

  @override
  String get generateFromDates => 'Временски опсег';

  @override
  String get generateFromDatesSubtitle => 'Генеришите нумере које сте слушали у временском опсегу';

  @override
  String get generateRandomPlaylist => 'Генериши насумичну плејлисту';

  @override
  String get genre => 'Жанр';

  @override
  String get genres => 'Жанрови';

  @override
  String get goToAlbum => 'Иди на албум';

  @override
  String get goToArtist => 'Иди на извођача';

  @override
  String get goToChannel => 'Иди на канал';

  @override
  String get goToFolder => 'Иди у фолдер';

  @override
  String get goodLooking => 'Доброг изгледа';

  @override
  String get grantStoragePermission => 'Додели дозволу за меморију';

  @override
  String get group => 'Група';

  @override
  String get groupArtworksByAlbum => 'Групиши уметничка дела према албуму';

  @override
  String get guide => 'Водич';

  @override
  String get hapticFeedback => 'Haptic Feedback';

  @override
  String get heightOfAlbumTile => 'Висина плочице албума';

  @override
  String get heightOfTrackTile => 'Висина плочице нумере';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => 'Високa подударања';

  @override
  String get highPerformance => 'Високе перформансе';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => 'Историја';

  @override
  String get historyImportMissingEntriesNote => 'Ови уноси се не могу пронаћи у збирци, ако верујете да постоје, размислите о томе да их додате ручно';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString слушања нумере $oldTrackInfo ће бити замењена са нумером $newTrackInfo, потврдити?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Почетна';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12-часовни формат';

  @override
  String get hours => 'Сати';

  @override
  String get iReadAndAgree => 'Читам и прихватам';

  @override
  String get ifNotPlaying => 'Ако није пуштено';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Преузимања се могу ограничити када је батерија ограничена';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignore common prefixes while sorting';

  @override
  String get ignores => 'Игнорише';

  @override
  String get imageSource => 'Image source';

  @override
  String get immersiveMode => 'Имерзивни режим';

  @override
  String get immersiveModeSubtitle => 'Сакриј статусну траку и траку за навигацију док је мини-плејер проширен';

  @override
  String get import => 'Увоз';

  @override
  String get importAll => 'Увези све';

  @override
  String get importLastFmHistory => 'Увези LastFM историју';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Идите на $lastfmCsvLink\n\n2. Унесите своје корисничко име, преузмите и преузмите csv фајл.\n\n3. Изаберите фајл са следећег екрана.';
  }

  @override
  String get importTimeRange => 'Увези временски опсег';

  @override
  String get importYoutubeHistory => 'Увези YouTube историју';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Идите на $takeoutLink\n\n2. Притисните „Више формата“ и поред „Историја“ изаберите „JSON“.\n\n3. Притисните „Сви подаци са YouTube-а укључени“, опозовите избор свих и изаберите само историју.\n\n4. Направите извоз, преузмите и распакујте.\n\n5. Изаберите „watch-history.json“ са следећег екрана.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Увезено $numberString канала успешно',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Увезено $numberText плејлиста успешно',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Укључи видео снимке';

  @override
  String get indexRefreshRequired => 'Обавите освежавање након промене овога';

  @override
  String get indexer => 'Индексер';

  @override
  String get indexerNote => 'Напомена: Непотпун број уметничких дела се односи на дуплирана и непронађена уметничка дела';

  @override
  String get indexerSubtitle => 'Управљајте вашом музичком збирком';

  @override
  String get infinityQueueOnNextPrev => 'Бесконачан редослед на следећем/претходном';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'притиском на следеће док пуштате последњу ставку скочићете на прву, и обрнуто';

  @override
  String get info => 'Информације';

  @override
  String get inserted => 'убачено';

  @override
  String get instantlyApplies => 'Одмах примењује';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => 'Обрни избор';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Ставка';

  @override
  String get jump => 'Скочи';

  @override
  String get jumpToDay => 'Скочи на дан';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Скочи на прву нумеру након завршетка редоследа';

  @override
  String get keepCachedVersions => 'Чувај кеширану верзију';

  @override
  String get keepFileDates => 'Задржи датуме фајлова';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Мини-плејер је проширен';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Мини-плејер је проширен и видео снимак је пуштен';

  @override
  String get keepScreenAwakeNone => 'Немој држати екран будним';

  @override
  String get keepScreenAwakeWhen => 'Држи екран будним када';

  @override
  String get killPlayerAfterDismissingApp => 'Убиј плејер након одбацивања апликације';

  @override
  String get language => 'Језик';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Картице збирке';

  @override
  String get libraryTabsReorder => 'Можете преуредити активиране картице.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Свиђа ми се';

  @override
  String get liked => 'Свиђа ми се';

  @override
  String get link => 'Линк';

  @override
  String get listOfFolders => 'Листа фолдера';

  @override
  String get loadAll => 'Учитај све';

  @override
  String get loadingFile => 'Учитавање фајла';

  @override
  String get local => 'Локално';

  @override
  String get localVideoMatching => 'Подударање локалног видео снимка';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Дуго притисните текст песме да бисте ушли у режим целог екрана';

  @override
  String get lostMemories => 'Изгубљена сећања';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'отприлике у ово време, пре $numberString година',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Побољшавач гласноће';

  @override
  String get lyricist => 'Текстописац';

  @override
  String get lyrics => 'Текст';

  @override
  String get lyricsSource => 'Извор текста';

  @override
  String get m3uPlaylist => 'M3U плејлиста';

  @override
  String get makeYourFirstListen => 'Направите своје прво слушање!';

  @override
  String get manage => 'Управљај';

  @override
  String get manageYourAccounts => 'Управљајте вашим налозима';

  @override
  String get manualBackup => 'Ручно';

  @override
  String get manualBackupSubtitle => 'одаберите одређени фајл';

  @override
  String get markAsRead => 'Означи као прочитано';

  @override
  String get matchAllTracks => 'Подударај све нумере';

  @override
  String get matchAllTracksNote => 'ово може да утиче на брзину подударања, јер ће проверити све нумере у вашој збирци';

  @override
  String get matchingType => 'Тип подударања';

  @override
  String get maxAudioCacheSize => 'Максимална величина кеша аудио снимка';

  @override
  String get maxImageCacheSize => 'Максимална величина кеша слике';

  @override
  String get maxVideoCacheSize => 'Максимална величина кеша видео снимка';

  @override
  String get maximum => 'Максимум';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Продавница медија је омогућена, ово неће имати ефекта';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'Кôд';

  @override
  String get membershipCodeSentToEmail => 'Кôд је послат на ваш имејл';

  @override
  String get membershipDidntChange => 'Чланство се није променило';

  @override
  String get membershipEnjoyNew => 'Уживајте у свом новом чланству';

  @override
  String get membershipFreeCoupon => 'Бесплатан купон';

  @override
  String get membershipManage => 'Управљај својим чланством';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Није пронађена ниједна претплата за овог корисника';

  @override
  String get membershipSignInToPatreonAccount => 'Пријава на ваш patreon налог';

  @override
  String get membershipUnknown => 'Непознато чланство';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Потребно вам је чланство $name1 или $name2 да бисте додали више налога';
  }

  @override
  String get merge => 'Споји';

  @override
  String get metadataCache => 'Кеш метаподатака';

  @override
  String get metadataEditFailed => 'Уређивање метаподатака није успело';

  @override
  String get metadataReadFailed => 'Читање метаподатака није успело';

  @override
  String get minFileDuration => 'Минимално трајање нумере';

  @override
  String get minFileSize => 'Минимална величина фајла';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Минимално трајање нумере за враћање позиције последњег пуштања';

  @override
  String get minValueCantBeMoreThanMax => 'Минимална вредност не може бити већа од максималне';

  @override
  String get minValueToCountTrackListen => 'Бројање слушања после: ';

  @override
  String get minimizedMiniplayer => 'Минимизирани мини-плејер';

  @override
  String get minimum => 'Минимум';

  @override
  String get minimumOneFolderSubtitle => 'Требало би да постоји најмање 1 фолдер, додајте још фолдера ако желите да уклоните овај';

  @override
  String get minimumOneItem => 'Није могуће уклонити ставку';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Требало би да остане најмање $numberString ставки',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => 'Прилагођавање мини-плејера';

  @override
  String get minutes => 'минута';

  @override
  String get missingEntries => 'Недостајући уноси';

  @override
  String get missingTracks => 'Недостајуће нумере';

  @override
  String get mix => 'Микс';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Микс плејлиста које генерише YouTube';

  @override
  String get mixes => 'Миксеви';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => 'Месец';

  @override
  String get months => 'Месеци';

  @override
  String get mood => 'Расположење';

  @override
  String get moods => 'Расположења';

  @override
  String get more => 'Више';

  @override
  String get mostPlayed => 'Највише пуштано';

  @override
  String get multipleTracksTagsEditNote => 'Управо ћете изменити ове нумере,\nНепромењена поља остају нетакнута.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => 'Назив';

  @override
  String get nameContainsBadCharacter => 'Назив садржи лоше знакове';

  @override
  String get never => 'Никада';

  @override
  String get newDirectory => 'Нови фолдер';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Додај нумере';

  @override
  String get newTracksMoods => 'Расположење';

  @override
  String get newTracksMoodsSubtitle => 'Генеришите нумере на основу доступних расположења';

  @override
  String get newTracksRandom => 'Насумично';

  @override
  String get newTracksRandomSubtitle => 'Покупите насумичне нумере из своје збирке';

  @override
  String get newTracksRatings => 'Оцене';

  @override
  String get newTracksRatingsSubtitle => 'Генеришите нумере које имају одређену оцену';

  @override
  String get newTracksRecommended => 'Препоручено';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Генеришите песме које сте обично слушали помоћу $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Сличан датум објављивања';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Генеришите песме које су објављене отприлике у исто време када и $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Нумера има непознату годину';

  @override
  String get newest => 'Најновије';

  @override
  String get next => 'Следеће';

  @override
  String get no => 'не';

  @override
  String get noChangesFound => 'Промене нису пронађене.';

  @override
  String get noEnoughTracks => 'Немате много нумера.';

  @override
  String get noExcludedFolders => 'Немате ниједан изузет фолдер';

  @override
  String get noFolderChosen => 'Нисте изабрали ниједан фолдер';

  @override
  String get noMoodsAvailable => 'Расположења нису доступна';

  @override
  String get noNetworkAvailableToFetchData => 'Нема доступне мреже за прикупљање података';

  @override
  String get noTracksFound => 'Није пронађена ниједна нумера';

  @override
  String get noTracksFoundBetweenDates => 'Овај временски опсег нема ниједну нумеру.';

  @override
  String get noTracksFoundInDirectory => 'Нема пронађених нумера у овом фолдеру';

  @override
  String get noTracksInHistory => 'Немате довољно нумера у историји';

  @override
  String get nonActive => 'Неактивно';

  @override
  String get nonFavourites => 'Неомиљено';

  @override
  String get none => 'Ниједно';

  @override
  String get normalizeAudio => 'Нормализуј звук';

  @override
  String get normalizeAudioSubtitle => 'Нормализује јачину звука читајући ознаку за добијање поновног пуштања или информације које пружа YouTube';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Напомена';

  @override
  String get notification => 'Обавештење';

  @override
  String get notifications => 'Обавештења';

  @override
  String get numberOfTracks => 'Број нумера';

  @override
  String get ofLabel => 'од';

  @override
  String get offlineSearch => 'Офлајн претрага';

  @override
  String get offset => 'Офсет';

  @override
  String get oldDirectory => 'Стари фолдер';

  @override
  String get oldDirectoryStillHasTracks => 'Стари фолдер још увек има неке нумере, потврдити?';

  @override
  String get oldestWatch => 'Најстарије гледање';

  @override
  String get onInterruption => 'При прекиду';

  @override
  String get onNotificationTap => 'При додиру обавештења';

  @override
  String get onOpeningYoutubeLink => 'При отварању YouTube линка';

  @override
  String get onSwiping => 'При превлачењу';

  @override
  String get onVolumeZero => 'При јачини звука 0';

  @override
  String get ongoing => 'У току';

  @override
  String get open => 'Отвори';

  @override
  String get openApp => 'Отвори апликацију';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'Отвори у YouTube приказу';

  @override
  String get openMiniplayer => 'Отвори мини-плејер';

  @override
  String get openQueue => 'Отвори редослед';

  @override
  String get openYoutubeLink => 'Отвори YouTube линк';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Операција $name захтева налог. Пријавите се да бисте наставили';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Операција $operation захтева најмање чланство $name';
  }

  @override
  String get or => 'или';

  @override
  String get others => 'Остало';

  @override
  String get output => 'Излаз';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => 'Препиши старе фајлове у истом фолдеру';

  @override
  String get palette => 'Палета';

  @override
  String get paletteMix => 'Микс';

  @override
  String get paletteNewMix => 'Нови микс';

  @override
  String get paletteSelectedMix => 'Изабрани микс';

  @override
  String get parallelDownloads => 'Паралелна преузимања';

  @override
  String get parsed => 'рашчлањено';

  @override
  String get password => 'Password';

  @override
  String get path => 'Пуна путања фајла';

  @override
  String get pause => 'Пауза';

  @override
  String get pauseFadeDuration => 'Трајање затамњења паузе';

  @override
  String get pausePlayback => 'Пауза репродукције';

  @override
  String get percentage => 'Проценат';

  @override
  String get performanceMode => 'Режим перформанси';

  @override
  String get performanceNote => 'Може утицати на перформансе';

  @override
  String get personalized => 'Персонализовано';

  @override
  String get personalizedRelatedVideos => 'Персонализовани сродни видео снимци';

  @override
  String get personalizedRelatedVideosSubtitle => 'Ако ово онемогућите, повећаће се потрошња података';

  @override
  String get pickColorsFromDeviceWallpaper => 'Изабери боје са позадине уређаја';

  @override
  String get pickFromStorage => 'Изабери из меморије';

  @override
  String get pinned => 'Закачено';

  @override
  String get pitch => 'Висина тона';

  @override
  String get plain => 'Обично';

  @override
  String get play => 'Пусти';

  @override
  String get playAfter => 'Пусти после';

  @override
  String get playAfterNextPrev => 'Аутоплеј на следеће/претходно';

  @override
  String get playAll => 'Пусти све';

  @override
  String get playFadeDuration => 'Трајање затамњења пуштања';

  @override
  String get playLast => 'Пусти последње';

  @override
  String get playNext => 'Пусти следеће';

  @override
  String get playbackSetting => 'Репродукција';

  @override
  String get playbackSettingSubtitle => 'Може се приступити директно у плејеру дугим притиском на аудио дугме';

  @override
  String get playlist => 'Плејлиста';

  @override
  String get playlists => 'Плејлисте';

  @override
  String get playlistsImportM3uNative => 'Ово ће увести M3U плејлисте које ће користити само namida, користите ако мигрирате';

  @override
  String get playlistsImportM3uSynced =>
      'Ово ће аутоматски увести M3U плејлисте из фолдера за индексирање и задржати их синхронизованим с оригиналним M3U фајлом. Омогућите ако приступате/мењате плејлисте из других апликација';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Аутоматски увоз M3U плејлисте';

  @override
  String get pleaseEnterADifferentName => 'Ово име већ постоји :(\nпокушајте са другим отменим називом';

  @override
  String get pleaseEnterALink => 'Унесите линк';

  @override
  String get pleaseEnterALinkSubtitle => 'хм.. да ли је YouTube линк?';

  @override
  String get pleaseEnterAName => 'Унесите назив';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Спречи дуплиране нумере';

  @override
  String get preventDuplicatedTracksSubtitle => 'Користи назив фајла за јединствену идентификацију нумера';

  @override
  String get preview => 'Преглед';

  @override
  String get previous => 'Претходно';

  @override
  String get previousButtonReplays => 'Претходно дугме понавља';

  @override
  String get previousButtonReplaysSubtitle => 'ако се притисне док је тренутна позиција била дуже од трајања тражења';

  @override
  String get prioritizeEmbeddedLyrics => 'Дај приоритет уграђеним текстовима';

  @override
  String get priority => 'Приоритет';

  @override
  String get private => 'Приватно';

  @override
  String get progress => 'Напредак';

  @override
  String get promptToChangeTrackPath => 'Обично се ово дешава када избришете/преместите/преименујете фајл ван апликације namida. Желите ли да ажурирате тренутну путању?';

  @override
  String get public => 'Јавно';

  @override
  String get queue => 'Редослед';

  @override
  String get queues => 'Редоследи';

  @override
  String get random => 'Насумично';

  @override
  String get randomPicks => 'Насумични избори';

  @override
  String get rating => 'Оцена';

  @override
  String get reIndex => 'Поново индексирај';

  @override
  String get reIndexSubtitle => 'Поново направите своју музичку збирку од нуле';

  @override
  String get reIndexWarning => 'Овај процес може потрајати, у зависности од величине ваше збирке.\n\nУметничка дела неће бити поново индексирана све док још постоје';

  @override
  String get recentAlbums => 'Недавни албуми';

  @override
  String get recentArtists => 'Недавни извођачи';

  @override
  String get recentListens => 'Недавна слушања';

  @override
  String get recentlyAdded => 'Недавно додато';

  @override
  String get recordLabel => 'Издавачка кућа';

  @override
  String get refresh => 'Освежи';

  @override
  String get refreshLibrary => 'Освежи збирку';

  @override
  String get refreshLibrarySubtitle => 'Проверите постоји ли новододата или избрисана музика';

  @override
  String get refreshOnStartup => 'Освежи при покретању';

  @override
  String get relatedVideos => 'Сродни видео снимци';

  @override
  String get rememberAudioOnlyMode => 'Запамти режим само аудио снимак';

  @override
  String get remixer => 'Ремиксер';

  @override
  String get remove => 'Уклони';

  @override
  String get removeDuplicates => 'Уклони дупликате';

  @override
  String get removeFromFavourites => 'Уклони из омиљених';

  @override
  String get removeFromLibrary => 'Уклони из збирке';

  @override
  String get removeFromPlaylist => 'Уклони са плејлисте';

  @override
  String get removeQueue => 'Уклони редослед';

  @override
  String get removeSourceFromHistory => 'Уклони извор из историје';

  @override
  String get removeWhitespaces => 'Уклони размаке';

  @override
  String get removed => 'Уклоњено';

  @override
  String get rename => 'Преименуј';

  @override
  String get renamePlaylist => 'Преименуј плејлисту';

  @override
  String get reorderable => 'Могуће преуредити';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Понови још $number пута',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Режим понављања';

  @override
  String get repeatModeAll => 'Понови све редоследе';

  @override
  String get repeatModeNone => 'Заустави на последњој нумери';

  @override
  String get repeatModeOne => 'Понови тренутну нумеру';

  @override
  String get replaceAllListensWithAnotherTrack => 'Замени сва слушања другом нумером';

  @override
  String get replies => 'Одговори';

  @override
  String get reply => 'Одговор';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Захтева чишћење кеша слике и поновно индексирање';

  @override
  String get rescanVideos => 'Поново скенирај видео снимке';

  @override
  String get resetBrightness => 'Ресетуј осветљеност';

  @override
  String get resetToDefault => 'Подеси на';

  @override
  String get respectNoMedia => 'Подржи .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Немојте укључивати фолдере који имају .nomedia';

  @override
  String get restart => 'Рестартуј';

  @override
  String get restoreBackup => 'Врати резервну копију';

  @override
  String get restoreDefaults => 'Врати подразумевано';

  @override
  String get restoredBackupSuccessfully => 'Враћене резервне копије';

  @override
  String get restoredBackupSuccessfullySub => 'Фајл резервне копије је успешно враћен';

  @override
  String get resume => 'Настави';

  @override
  String get resumeIfWasInterrupted => 'Настави ако је паузирано при прекиду';

  @override
  String get resumeIfWasPausedByVolume => 'Настави ако је паузирано по јачини звука';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Настави ако је паузирано мање од $numberString минута',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Обрнути распоред';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => 'Мелодија звона';

  @override
  String get sameDirectoryOnly => 'Само исти фолдер';

  @override
  String get sample => 'Sample';

  @override
  String get sampleRate => 'Стопа узорковања';

  @override
  String get save => 'Сачувај';

  @override
  String get saveToLibrary => 'Сачувај у збирку';

  @override
  String get savedIn => 'Сачувано у';

  @override
  String get scaleMultiplier => 'Скалирај множиоца';

  @override
  String get search => 'Претрага';

  @override
  String get searchYoutube => 'Претрага YouTube';

  @override
  String get seconds => 'секунди';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Трајање тражења';

  @override
  String get seekDurationInfo => 'Можете да додирнете тренутно трајање да тражите уназад и укупно трајање да тражите унапред';

  @override
  String get seekbar => 'Трака за тражење';

  @override
  String get selectAll => 'Изабери све';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Select files already in local library';

  @override
  String get selectedTracks => 'Изабране нумере';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Ове речи се неће поделити';

  @override
  String get separatorsMessage => 'Нема потребе за уношењем размака, осим ако не желите да користите слово/симбол који се може наћи у целој речи (као што су x и ft.)';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => 'Подеси као';

  @override
  String get setAsDefault => 'Подеси као подразумевано';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Подесите последњи измењени фајл као датум отпремања видео снимка';

  @override
  String get setMoods => 'Подеси расположења';

  @override
  String get setMoodsSubtitle => 'Користите зарезе (,) да их одвојите';

  @override
  String get setRating => 'Подеси оцену';

  @override
  String get setTags => 'Подеси ознаке';

  @override
  String get setYoutubeLink => 'Подеси YouTube линк';

  @override
  String get settings => 'Подешавања';

  @override
  String get setupFirstStartup => 'Подесите прво покретање';

  @override
  String get share => 'Дели';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Пречице';

  @override
  String get shouldDuck => 'Треба пригушити';

  @override
  String get shouldDuckNote => 'Означава да треба смањити јачину звука. нпр: обавештење';

  @override
  String get shouldPause => 'Треба паузирати';

  @override
  String get shouldPauseNote => 'Означава да репродукцију треба паузирати. нпр: позиви';

  @override
  String get showAll => 'Прикажи све';

  @override
  String get showChannelWatermarkInFullscreen => 'Прикажи водени жиг канала у режиму целог екрана';

  @override
  String get showFailedOnly => 'Прикажи само неуспешно';

  @override
  String get showHideUnknownFields => 'Прикажи/сакриј непозната поља';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => 'Прикажи миксеве у';

  @override
  String get showMore => 'Прикажи више';

  @override
  String get showShortVideosIn => 'Прикажи Shorts у';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => 'Прикажи завршне картице видео снимка';

  @override
  String get showWebm => 'Прикажи webm';

  @override
  String get shuffle => 'Мешај';

  @override
  String get shuffleAll => 'Мешај све';

  @override
  String get shuffleNext => 'Мешај следеће';

  @override
  String get signIn => 'Пријава';

  @override
  String get signInCanceled => 'Пријава је отказана';

  @override
  String get signInFailed => 'Пријава је неуспешна';

  @override
  String get signInToYourAccount => 'Пријава на ваш налог';

  @override
  String get signInYouDontHaveAccount => 'Немате пријављен ниједан налог';

  @override
  String get signInYouNeedAccountToViewPage => 'Потребан вам је налог да бисте видели ову страницу';

  @override
  String get signOut => 'Одјава';

  @override
  String signOutFromName({required String name}) {
    return 'Одјава из $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Пријављивање омогућава основну употребу';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Добијте рани приступ користећи patreon или купон';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Similar Time Range';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generate tracks you listened to around the same time as $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'Величина';

  @override
  String get skip => 'Прескочи';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => 'Прескочи тишину';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => 'Спавати након';

  @override
  String get sleepTimer => 'Тајмер спавања';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Сортирање по';

  @override
  String get source => 'Извор';

  @override
  String get speed => 'Брзина';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => 'Попречни албум мрежастог приказа';

  @override
  String get start => 'Започни';

  @override
  String get stats => 'Статистика';

  @override
  String get statsSubtitle => 'Ево неких информација о вашој збирци';

  @override
  String get stop => 'Заустави';

  @override
  String get stopAfterThisTrack => 'Заустави након ове нумере';

  @override
  String get stopAfterThisVideo => 'Заустави након овог видео снимка';

  @override
  String get storagePermissionDenied => 'Дозвола одбијена';

  @override
  String get storagePermissionDeniedSubtitle => 'Дозволите приступ да бисте могли да извршите ову радњу';

  @override
  String get stretchLyricsDuration => 'Stretch Lyrics Duration';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Претплата';

  @override
  String get subscribed => 'Претплаћено';

  @override
  String get subscriber => 'Претплатник';

  @override
  String get subscribers => 'Претплатници';

  @override
  String get succeeded => 'Успешно';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Подршка';

  @override
  String get supremacy => 'Надмоћ';

  @override
  String get sussyBaka => 'Нема нумера';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => 'Превуци за отварање фиоке';

  @override
  String get synced => 'Синхронизовано';

  @override
  String get synopsis => 'Сажетак';

  @override
  String get tagFields => 'Поља ознака';

  @override
  String get tags => 'Ознаке';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => 'Додирните за тражење';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Тема';

  @override
  String get themeModeDark => 'Тамна';

  @override
  String get themeModeLight => 'Светла';

  @override
  String get themeModeSystem => 'Системска';

  @override
  String get themeSettings => 'Тема';

  @override
  String get themeSettingsSubtitle => 'Свеопшти изглед вашег плејера';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Ова плејлиста има активне сортере, онемогућите их пре преуређивања.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Овај видео снимак је вероватно избрисан или постављен као приватан.';

  @override
  String get thumbnails => 'Сличице';

  @override
  String get title => 'Наслов';

  @override
  String get top => 'Топ';

  @override
  String get topComments => 'Коментари на врху';

  @override
  String get topCommentsSubtitle => 'Приказ коментара на врху уместо на дну';

  @override
  String get topRecentAlbums => 'Топ недавни албуми';

  @override
  String get topRecentArtists => 'Топ недавни извођачи';

  @override
  String get topRecents => 'Топ недавно';

  @override
  String get totalListenTime => 'Укупно време слушања';

  @override
  String get totalListens => 'Укупно слушања';

  @override
  String get totalTracks => 'Укупно нумера';

  @override
  String get totalTracksDuration => 'Укупно трајање нумера';

  @override
  String get track => 'Нумера';

  @override
  String get trackArtistsSeparator => 'Раздвајачи извођача';

  @override
  String get trackGenresSeparator => 'Раздвајачи жанрова';

  @override
  String get trackInfo => 'Информације о нумери';

  @override
  String get trackNotFound => 'Нумера није пронађена';

  @override
  String get trackNumber => 'Број нумере';

  @override
  String get trackNumberTotal => 'Укупно нумера';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Стари назив „$oldName“\n\nНови назив „$newName“\n\nЈесте ли сигурни?';
  }

  @override
  String get trackPlayMode => 'Режим пуштања';

  @override
  String get trackPlayModeSearchResults => 'Резултати претраге';

  @override
  String get trackPlayModeSelectedOnly => 'Само изабрана нумера';

  @override
  String get trackPlayModeTrackAlbum => 'Албум нумере';

  @override
  String get trackPlayModeTrackArtist => 'Главни извођач нумере';

  @override
  String get trackPlayModeTrackGenre => 'Жанр нумере';

  @override
  String get trackThumbnailSizeInList => 'Величина сличице нумере';

  @override
  String get trackTileCustomization => 'Прилагођавање плочице нумере';

  @override
  String get trackTileItemsSeparator => 'Раздвајач ставки';

  @override
  String get tracks => 'Нумере';

  @override
  String get tracksExcludedByNomedia => 'Нумере изузете од .nomedia';

  @override
  String get tracksInfo => 'Информације о нумерама';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => 'Опозови';

  @override
  String get undoChanges => 'Опозвати промене?';

  @override
  String get undoChangesDeletedPlaylist => 'Опозови избрисане плејлисте';

  @override
  String get undoChangesDeletedQueue => 'Опозови избрисани редослед';

  @override
  String get undoChangesDeletedTrack => 'Опозови избрисану нумеру';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => 'Неограничено';

  @override
  String get unlisted => 'По позиву';

  @override
  String get unlock => 'Откључај';

  @override
  String get update => 'Ажурирај';

  @override
  String get updateDirectoryPath => 'Ажурирај путању фолдера';

  @override
  String get updateMissingTracksOnly => 'Ажурирај само недостајуће нумере';

  @override
  String get updating => 'Ажурирање';

  @override
  String get useCollapsedSettingTiles => 'Користи скупљене плочице подешавања';

  @override
  String get useMediaStore => 'Користи продавницу медија';

  @override
  String get useMediaStoreSubtitle =>
      '✓ инстантно време индексирања\nx поштовање .nomedia ће бити принудно омогућено\nx неке ознаке метаподатака ће недостајати\nx YouTube интеграција за локалну збирку неће радити';

  @override
  String get usePitchBlack => 'Користи потпуно црну';

  @override
  String get usePitchBlackSubtitle => 'Корисно за AMOLED екране.. и изгледа боље';

  @override
  String get used => 'Коришћено';

  @override
  String get value => 'Вредност';

  @override
  String get valueBetween50200 => 'Вредност треба бити између 50% и 200%';

  @override
  String get vibration => 'Vibration';

  @override
  String get vibrationType => 'Vibration type';

  @override
  String get video => 'Видео снимак';

  @override
  String get videoCache => 'Кеш видео снимака';

  @override
  String get videoCacheFile => 'Кеширани фајл видео снимка';

  @override
  String get videoCacheFiles => 'Кеширани фајлови видео снимака';

  @override
  String get videoOnly => 'Само видео снимак';

  @override
  String get videoPlaybackSource => 'Извор видео снимка';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Ово ће дати приоритет локалним видео снимцима, ако се не пронађу, онда ће се преузети с YouTube-а';

  @override
  String get videoPlaybackSourceLocal => 'Локални видео снимци';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nВидео Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Проверава да ли било који фајл видео снимка (који се налази на листи изабраних фолдера) има назив који садржи назив фајла';

  @override
  String get videoPlaybackSourceYoutube => 'С YouTube-а';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Проверава назив фајла и коментар нумере за било који подударни YouTube линк, видео снимци се кеширају за каснију употребу.';

  @override
  String get videoQuality => 'Квалитет видео снимка';

  @override
  String get videoQualitySubtitle => 'Биће изабран највећи доступни квалитет.';

  @override
  String get videoQualitySubtitleNote => 'Увек је добро задржати више алтернатива у случају да се квалитет не пронађе, иначе ће се вратити на најгори квалитет';

  @override
  String get videos => 'Видео снимци';

  @override
  String get view => 'преглед';

  @override
  String get viewAll => 'Види све';

  @override
  String get views => 'прегледа';

  @override
  String get volume => 'Јачина звука';

  @override
  String get warning => 'Упозорење';

  @override
  String get waveformBarsCount => 'Број таласних барова';

  @override
  String get webmNoEditTagsSupport => 'WEBM формат не подржава уређивање ознака';

  @override
  String get week => 'Недеља';

  @override
  String get year => 'Година';

  @override
  String get yes => 'да';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Ваше тренутно чланство је $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Ваш прилагођени распоред ће бити изгубљен, јесте ли сигурни?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'Прилагодите YouTube искуство';

  @override
  String get youtubeStyleMiniplayer => 'Мини-плејер у YouTube стилу';

  @override
  String get ytPreferNewComments => 'Преферирај нове коментаре када је то могуће';

  @override
  String get ytPreferNewCommentsSubtitle => 'Кеширана верзија ће се користити само када нема везе';
}
