// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Dutch Flemish (`nl`).
class AppLocalizationsNl extends AppLocalizations {
  AppLocalizationsNl([String locale = 'nl']) : super(locale);

  @override
  String get about => 'Over';

  @override
  String get active => 'Actief';

  @override
  String get add => 'Toevoegen';

  @override
  String get addAccount => 'Account toevoegen';

  @override
  String get addAll => 'Alles toevoegen';

  @override
  String get addAllAndRemoveOldOnes => 'Alles toevoegen en oude verwijderen';

  @override
  String get addAsANewPlaylist => 'Toevoegen als nieuwe afspeellijst';

  @override
  String get addAudioToLocalLibrary => 'Audio toevoegen aan lokale verzameling';

  @override
  String get addFolder => 'Nieuwe map';

  @override
  String get addLanguage => 'Taal toevoegen';

  @override
  String get addLanguageSubtitle => 'Helpen met vertalen van Namida';

  @override
  String get addLrcFile => 'Lrc-bestand toevoegen';

  @override
  String get addMoreFromThisAlbum => 'Meer van dit album toevoegen aan wachtrij';

  @override
  String get addMoreFromThisArtist => 'Meer van deze artiest toevoegen aan wachtrij';

  @override
  String get addMoreFromThisFolder => 'Meer uit deze map toevoegen aan wachtrij';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Meer van $media toevoegen aan wachtrij';
  }

  @override
  String get addOnlyMissing => 'Alleen ontbrekende toevoegen';

  @override
  String get addToFavourites => 'Toevoegen aan favorieten';

  @override
  String get addToPlaylist => 'Toevoegen aan afspeellijst';

  @override
  String get addTracksAtTheBeginning => 'Nummers toevoegen aan begin';

  @override
  String get added => 'toegevoegd';

  @override
  String get advanced => 'Geavanceerd';

  @override
  String get advancedSettings => 'Geavanceerd';

  @override
  String get advancedSettingsSubtitle => 'Geavanceerde instellingen - niet mee spelen';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Albumartiest';

  @override
  String get albumArtists => 'Albumartiesten';

  @override
  String get albumIdentifiers => 'Albumidentificaties';

  @override
  String get albumThumbnailSizeInList => 'Omvang van albumhoes';

  @override
  String get albumTileCustomization => 'Albumhoesweergave aanpassen';

  @override
  String get albums => 'Albums';

  @override
  String get albumsCount => 'Aantal albums';

  @override
  String get all => 'Alles';

  @override
  String get allTime => 'Aller tijden';

  @override
  String get alreadyExists => 'Bestaat al';

  @override
  String get always => 'Altijd';

  @override
  String get alwaysAsk => 'Altijd vragen';

  @override
  String get alwaysDim => 'Altijd dimmen';

  @override
  String get alwaysExpandedSearchbar => 'Altijd uitgebreide zoekmogelijkheden tonen';

  @override
  String get alwaysRestore => 'Altijd herstellen';

  @override
  String get animatingThumbnailIntensity => 'Animatiesnelheid van miniatuur';

  @override
  String get animatingThumbnailInversed => 'Animaties andersom afspelen';

  @override
  String get animatingThumbnailInversedSubtitle => 'Let op: hoger = kleinere miniatuur';

  @override
  String get anotherProcessIsRunning => 'Er is al een proces actief.';

  @override
  String get appIcon => 'App-pictogram';

  @override
  String get appVersion => 'Appversie';

  @override
  String get artist => 'Artiest';

  @override
  String get artists => 'Artiesten';

  @override
  String get artwork => 'Albumhoes';

  @override
  String get artworkGestures => 'Albumhoesgebaren';

  @override
  String get artworks => 'Albumhoezen';

  @override
  String get audio => 'Audio';

  @override
  String get audioCache => 'Audiocache';

  @override
  String get audioOnly => 'Alleen audio';

  @override
  String get auto => 'Automatisch';

  @override
  String get autoBackupInterval => 'Automatisch reservekopieën maken';

  @override
  String get autoColoring => 'Automatisch inkleuren';

  @override
  String get autoColoringSubtitle => 'Stel de spelerkleuren in op basis van die van de huidige albumhoes';

  @override
  String get autoExtractTagsFromFilename => 'Automatisch op basis van bestandsnaam';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Automatisch op basis van titel en artiest uit videotitel';

  @override
  String get autoGenerated => 'Automatisch gegenereerd';

  @override
  String get autoSkip => 'Automatisch overslaan';

  @override
  String get autoSkipOnce => 'Eenmalig automatisch overslaan';

  @override
  String get autoStartRadio => 'Radio automatisch starten';

  @override
  String get autoStartRadioSubtitle => 'Voeg automatisch een mixafspeellijst toe tijdens het afspelen van een los nummer';

  @override
  String get automaticBackup => 'Automatisch';

  @override
  String get automaticBackupSubtitle => 'Herstelt automatisch het recentste reservekopiebestand vanuit de opgegeven locatie';

  @override
  String get backupAndRestore => 'Reservekopieën en herstellen';

  @override
  String get backupAndRestoreSubtitle => 'Maak een reservekopie van de databank en instellingen';

  @override
  String get balanced => 'Gebalanceerd';

  @override
  String get beta => 'Bèta';

  @override
  String get betweenDates => 'Tussen data';

  @override
  String get bitrate => 'Bitsnelheid';

  @override
  String get blacklist => 'Zwarte lijst';

  @override
  String get borderRadiusMultiplier => 'Hoekstraalvermenigvuldiging';

  @override
  String get cache => 'Cache';

  @override
  String get cancel => 'Annuleren';

  @override
  String get canceled => 'Afgebroken';

  @override
  String get changed => 'Gewijzigd';

  @override
  String get changelog => 'Wijzigingslog';

  @override
  String get changelogSubtitle => 'Bekijk het wijzigingslog van Namida';

  @override
  String get channel => 'Kanaal';

  @override
  String get channels => 'Kanalen';

  @override
  String get check => 'Controleren';

  @override
  String get checkForMore => 'Meer bekijken';

  @override
  String get checkList => 'Controlelijst';

  @override
  String get choose => 'Kiezen';

  @override
  String get chooseWhatToClear => 'Kies de te wissen items';

  @override
  String get claim => 'Verzilveren';

  @override
  String get clear => 'Wissen';

  @override
  String get clearAudioCache => 'Audiocache wissen';

  @override
  String get clearImageCache => 'Afbeeldingscache wissen';

  @override
  String get clearImageCacheWarning => 'Waarschuwing: hierdoor zal de verzameling geen afbeeldingen meer bevatten. Doe dit alleen om ze opnieuw in te laden.';

  @override
  String get clearTrackItem => 'Nummers wissen';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString nummers wissen',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Videocache wissen';

  @override
  String get clearVideoCacheNote => 'Geef aan wat je wilt wissen.';

  @override
  String get clock => 'Klok';

  @override
  String get colorPalette => 'Kleurenschema';

  @override
  String get colorPaletteNote1 => 'Houd een kleur lang ingedrukt om te verwijderen';

  @override
  String get colorPaletteNote2 => 'Druk op een combinatie om in te stellen als standaardkleur';

  @override
  String get colorPalettes => 'Kleurenschema\'s';

  @override
  String get comment => 'Reactie';

  @override
  String get comments => 'Reacties';

  @override
  String get composer => 'Componist';

  @override
  String get compress => 'Comprimeren';

  @override
  String get compressImages => 'Afbeeldingen comprimeren';

  @override
  String get compressionPercentage => 'Compressiepercentage';

  @override
  String get configure => 'Instellen';

  @override
  String get confirm => 'Oké';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'De albumhoes is gekopieerd';

  @override
  String get copiedToClipboard => 'Gekopieerd naar het klembord';

  @override
  String get copy => 'Kopiëren';

  @override
  String get corruptedFile => 'Het bestand kan niet worden verwerkt - is het beschadigd?';

  @override
  String get couldntOpen => 'Het openen is mislukt. :(';

  @override
  String get couldntOpenYtLink => 'Er is van dit nummer geen youtubelink beschikbaar';

  @override
  String get couldntPlayFile => 'Het bestand kan niet worden afgespeeld';

  @override
  String get couldntRenamePlaylist => 'De afspeellijstnaam kan niet worden gewijzigd';

  @override
  String get couldntSaveImage => 'De afbeelding kan niet worden opgeslagen';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Land';

  @override
  String get coupon => 'Waardebon';

  @override
  String get create => 'Maken';

  @override
  String get createBackup => 'Reservekopie maken';

  @override
  String get createNewPlaylist => 'Nieuwe afspeellijst';

  @override
  String get createdBackupSuccessfully => 'Reservekopie gemaakt';

  @override
  String get createdBackupSuccessfullySub => 'Er is een reservekopie gemaakt';

  @override
  String get crossPlatformSync => 'Synchronisatie tussen platformen';

  @override
  String get crossfadeDuration => 'Overgangsduur';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Automatisch een vloeiende overgang verzorgen in de laatste $secondsString seconden',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Geen automatische vloeiende overgang';

  @override
  String get custom => 'Aangepast';

  @override
  String get customizations => 'Aanpassingen';

  @override
  String get customizationsSubtitle => 'Zet de speler naar eigen hand';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'De gegevens zijn afkomstig van $name';
  }

  @override
  String get dataSaver => 'Gegevensbesparing';

  @override
  String get dataSaverMode => 'Gegevensbesparingsmodus';

  @override
  String get database => 'Databank';

  @override
  String get date => 'Datum';

  @override
  String get dateAdded => 'Toevoegdatum';

  @override
  String get dateCreated => 'Aanmaakdatum';

  @override
  String get dateModified => 'Bewerkdatum';

  @override
  String get dateTimeFormat => 'Datum- en tijdopmaak';

  @override
  String get day => 'Dag';

  @override
  String get days => 'Dagen';

  @override
  String get defaultBackupLocation => 'Standaard reservekopielocatie';

  @override
  String get defaultColor => 'Standaardkleur';

  @override
  String get defaultColorSubtitle => 'Geef aan van welke kleur de speler moet worden voorzien';

  @override
  String get defaultDownloadLocation => 'Standaard downloadlocatie instellen';

  @override
  String get defaultLabel => 'Standaard';

  @override
  String get defaultLibraryTab => 'Standaard verzamelingstabblad';

  @override
  String get delete => 'Verwijderen';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Weet je zeker dat je $countString bestand(en) van $totalSizeText wilt verwijderen?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return '$numberText permanent uit de opslag verwijderen';
  }

  @override
  String get deletePlaylist => 'Afspeellijst verwijderen';

  @override
  String get deleteTempFiles => 'Tijdelijke bestanden verwijderen';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Beschrijving';

  @override
  String get developer => 'Ontwikkelaar';

  @override
  String get development => 'Ontwikkeling';

  @override
  String get didYouMean => 'Bedoelde je';

  @override
  String get dimIntensity => 'Dimintensiteit';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Minispeler dimmen na $secondsString seconden inactiviteit',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'De map bestaat niet';

  @override
  String get disable => 'Uitschakelen';

  @override
  String get disableAll => 'Alles uitschakelen';

  @override
  String get disableReordering => 'Herordenen uitschakelen';

  @override
  String get disableSearchCleanup => 'Zoekopruiming uitschakelen';

  @override
  String get discNumber => 'Schijfnummer';

  @override
  String get discNumberTotal => 'Aantal schijven';

  @override
  String get discover => 'Ontdekken';

  @override
  String get dislike => 'Vind ik niet leuk';

  @override
  String get dismissibleMiniplayer => 'Minispeler minimaliseerbaar maken';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Huidige positie tonen tijdens doorspoelen in plaats van verschil';

  @override
  String get displayAlbumCardTopRightDate => 'Datum rechtsboven op albumhoezen tonen';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Toon de datum van uitgave rechtsboven op albumhoezen';

  @override
  String get displayArtistBeforeTitle => 'Artiesten vóór titels sorteren';

  @override
  String get displayArtworkOnLockscreen => 'Albumhoes tonen op vergrendelscherm';

  @override
  String get displayAudioInfoInMiniplayer => 'Audio-informatie tonen';

  @override
  String get displayFavButtonInNotification => 'Favorietknop op melding tonen';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Hierdoor wordt de miniatuur mogelijk verschoven.';

  @override
  String get displayFavouriteIconInTrackTile => 'Favorietknop tonen';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Resterende duur in plaats van totaalduur tonen';

  @override
  String get displayStopButtonInNotification => 'Stopknop tonen op melding';

  @override
  String get displayThirdItemInRowInTrackTile => 'Derde item van elke rij tonen';

  @override
  String get displayThirdRowInTrackTile => 'Derde rij tonen';

  @override
  String get displayTrackNumberInAlbumPage => 'Volgnummer op albumpagina tonen';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Toon een klein vak op de albumpagina met daarin het volgnummer';

  @override
  String get doNothing => 'Niets doen';

  @override
  String get donate => 'Doneren';

  @override
  String get donateSubtitle => 'Als je vindt dat het wat waard is';

  @override
  String get done => 'Klaar';

  @override
  String get dontAskAgain => 'Niet meer vragen';

  @override
  String get dontDim => 'Nooit dimmen';

  @override
  String get dontRestorePosition => 'Niet herstellen';

  @override
  String get dontResume => 'Niet hervatten';

  @override
  String get doubleTapToToggleLyrics => 'Dubbeltikken om songtekst te tonen';

  @override
  String get download => 'Downloaden';

  @override
  String get downloadingWillOverrideIt => 'Downloaden zal dit overschrijven';

  @override
  String get downloads => 'Downloads';

  @override
  String get downloadsMetadataTags => 'Bestandstags downloaden';

  @override
  String get downloadsMetadataTagsSubtitle => 'Extraheer artiest, titel en album uit de videoinformatie';

  @override
  String get dragToSeek => 'Slepen om te spoelen';

  @override
  String get duckAudio => 'Audioniveau verlagen';

  @override
  String get duplicatedItemsAdding => 'Je probeert items toe te voegen die al op de afspeellijst staan';

  @override
  String get duplicatedTracks => 'Duplicaten';

  @override
  String get duration => 'Duur';

  @override
  String get edgeColorsSwitching => 'Veranderen van randkleur';

  @override
  String get edit => 'Bewerken';

  @override
  String get editArtwork => 'Albumhoes bewerken';

  @override
  String get editTags => 'Tags bewerken';

  @override
  String get email => 'E-mailadres';

  @override
  String get emptyNonMeaningfulTagFields => 'Let op: er zijn velden met blanco of ongeschikte waarden - denk goed na of je ze wilt bewerken';

  @override
  String get emptyValue => 'Blanco waarde';

  @override
  String get enableArtworkCache => 'Hoezen bewaren in cache';

  @override
  String get enableArtworkCacheSubtitle => 'Versnelt het laden en verbetert de prestaties, maar verbruikt meer opslagruimte';

  @override
  String get enableBlurEffect => 'Vervagingseffect gebruiken';

  @override
  String get enableBottomNavBar => 'Navigatiebalk aan onderkant van scherm tonen';

  @override
  String get enableBottomNavBarSubtitle => 'Items bevinden zich tevens in het zijpaneel';

  @override
  String get enableClipboardMonitoring => 'Klembord monitoren';

  @override
  String get enableClipboardMonitoringSubtitle => 'Plak links en tekst in het zoekvak';

  @override
  String get enableCrossfadeEffect => 'Overgangseffect gebruiken';

  @override
  String get enableFadeEffectOnPlayPause => 'Overgangseffect gebruiken bij afspelen/pauzeren';

  @override
  String get enableFoldersHierarchy => 'Mappenstructuur gebruiken';

  @override
  String get enableGlowEffect => 'Gloeieffect gebruiken';

  @override
  String get enableM3uSync => 'M3u-synchronisatie inschakelen';

  @override
  String get enableM3uSyncNote1 => 'Met behulp van m3u-synchronisatie kun je afspeellijstwijzigingen bewaren in het oorspronkelijke m3u-bestand';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Als er iets misgaat, dan is er een reservekopie beschikbaar in $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Schakel uit om alle wijzigingen na een herstart te wissen';

  @override
  String get enableMiniplayerParticles => 'Bewegende deeltjes tonen';

  @override
  String get enableParallaxEffect => 'Parallaxeffect gebruiken';

  @override
  String get enablePartyMode => 'Feestmodus inschakelen';

  @override
  String get enablePartyModeSubtitle => 'Toon een mooi effect langs de randen';

  @override
  String get enablePictureInPicture => 'Beeld-in-beeld (PIP) inschakelen';

  @override
  String get enableReordering => 'Herordenen inschakelen';

  @override
  String get enableReturnYoutubeDislike => 'Toon de vind-ik-niet-leukknop';

  @override
  String get enableSearchCleanup => 'Zoekresultaten opruimen inschakelen';

  @override
  String get enableSearchCleanupSubtitle => 'Alle speciale tekens en spaties worden genegeerd';

  @override
  String get enableSponsorblock => 'SponsorBlock inschakelen';

  @override
  String get enableVideoPlayback => 'Video\'s afspelen';

  @override
  String get enterSymbol => 'Voer een speciaal teken in';

  @override
  String get equalizer => 'Equalizer';

  @override
  String get error => 'Foutmelding';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Het nummer kan niet worden afgespeeld';

  @override
  String get excludedFodlers => 'Genegeerde mappen';

  @override
  String get exit => 'Afsluiten';

  @override
  String get exitAppSubtitle => 'Druk nogmaals om af te sluiten';

  @override
  String get expandedMiniplayer => 'Uitgebreide minispeler';

  @override
  String get exportAsM3u => 'Exporteren als m3u-bestand';

  @override
  String get extension => 'Extensie';

  @override
  String get externalFiles => 'Externe bestanden';

  @override
  String get extract => 'Extraheren';

  @override
  String get extractAllColorPalettes => 'Alle kleurenschema\'s extraheren';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Wil je de resterende $numberString extraheren?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Nummers met ‘feat.‘ apart noteren';

  @override
  String get extractFeatArtistSubtitle => 'Voegt artiesten met ‘feat. X’ en ‘ft. X’ toe als losse items.';

  @override
  String get extractingInfo => 'Bezig met extraheren van informatie…';

  @override
  String get extras => 'Extra\'s';

  @override
  String get extrasSubtitle => 'Extra instellingen om alles naar eigen hand te zetten';

  @override
  String get extreme => 'Extreem';

  @override
  String get failed => 'Mislukt';

  @override
  String get failedEdits => 'De bewerkingen zijn mislukt';

  @override
  String get favourites => 'Favorieten';

  @override
  String get features => 'Functies';

  @override
  String get fetching => 'Bezig met ophalen…';

  @override
  String get fetchingOfAllVideos => 'Bezig met ophalen van alle video\'s…';

  @override
  String get file => 'Bestand';

  @override
  String get fileAlreadyExists => 'Het bestand bestaat al';

  @override
  String get fileBasedServerWarning =>
      'Bestanden worden tijdelijk opgehaald, zodat ze kunnen worden geïndexeerd. Zorg voor een stabiele internetverbinding.\nWifi wordt aanbevolen om een hoog dataverbruik te voorkomen.';

  @override
  String get fileName => 'Bestandsnaam';

  @override
  String get fileNameWoExt => 'Bestandsnaam zonder extensie';

  @override
  String get filenameShouldntStartWith => 'De bestandsnaam mag niet beginnen met';

  @override
  String get files => 'Bestanden';

  @override
  String get filler => 'Opvulling';

  @override
  String get filterAlbums => 'Albums filteren';

  @override
  String get filterArtists => 'Artiesten filteren';

  @override
  String get filterGenres => 'Genres filteren';

  @override
  String get filterPlaylists => 'Afspeellijsten filteren';

  @override
  String get filterTracks => 'Nummers filteren';

  @override
  String get filterTracksBy => 'Nummers op lijsten filteren op';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Nummers gefilterd op bestandsgrootte en duur';

  @override
  String get finished => 'Afgerond';

  @override
  String get finishedUpdatingLibrary => 'De verzameling is bijgewerkt';

  @override
  String get firstListen => 'Eerste keer beluisterd op';

  @override
  String get fixYtdlpBigThumbnailSize => 'Grote miniaturen van yt-dlp repareren';

  @override
  String get floatingActionButton => 'Zwevende actieknop';

  @override
  String get folder => 'Map';

  @override
  String get folderName => 'Mapnaam';

  @override
  String get folders => 'Mappen';

  @override
  String get fontScale => 'Tekstgrootte';

  @override
  String get forceMiniplayerFollowTrackColors => 'Kleuren van huidig nummer gebruiken in minispeler';

  @override
  String get forceSquaredAlbumThumbnail => 'Albumhoezen vierkant maken';

  @override
  String get forceSquaredThumbnailNote =>
      'Let op: de miniatuurgrootte en -hoogte zijn niet altijd gelijk, waardoor een vierkant niet altijd mogelijk is. Weet je zeker dat je ze allemaal vierkant wilt maken?';

  @override
  String get forceSquaredTrackThumbnail => 'Miniaturen van nummers vierkant maken';

  @override
  String get forceStopColorPaletteGeneration => 'Weet je zeker dat je het extraheren wilt afbreken? Je kunt op een ander moment verdergaan.';

  @override
  String get format => 'Formaat';

  @override
  String get fullscreen => 'Schermvullende weergave';

  @override
  String get gaplessPlayback => 'Ononderbroken afspelen';

  @override
  String get generate => 'Genereren';

  @override
  String get generateFromDates => 'Tijdspanne';

  @override
  String get generateFromDatesSubtitle => 'Genereer beluisterde nummers binnen een bepaalde tijdspanne';

  @override
  String get generateRandomPlaylist => 'Willekeurige afspeellijst genereren';

  @override
  String get genre => 'Genre';

  @override
  String get genres => 'Genres';

  @override
  String get goToAlbum => 'Ga naar album';

  @override
  String get goToArtist => 'Ga naar artiest';

  @override
  String get goToChannel => 'Ga naar kanaal';

  @override
  String get goToFolder => 'Ga naar map';

  @override
  String get goodLooking => 'Ziet er goed uit';

  @override
  String get grantStoragePermission => 'Opslagrecht toestaan';

  @override
  String get group => 'Groep';

  @override
  String get groupArtworksByAlbum => 'Hoezen groeperen op album';

  @override
  String get guide => 'Zelfstudie';

  @override
  String get hapticFeedback => 'Haptische feedback';

  @override
  String get heightOfAlbumTile => 'Hoogte van albumminiatuur';

  @override
  String get heightOfTrackTile => 'Hoogte van nummerminiatuur';

  @override
  String get hideSkipButtonAfter => 'Overslaanknop verbergen na';

  @override
  String get highMatches => 'Groot aantal overeenkomsten';

  @override
  String get highPerformance => 'Hoge prestaties';

  @override
  String get highlight => 'Uitgelichte scène';

  @override
  String get history => 'Geschiedenis';

  @override
  String get historyImportMissingEntriesNote => 'Deze nummers zijn niet aangetroffen in de verzameling. Als je zeker weet dat ze bestaan, voeg ze dan handmatig toe.';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString zoekt naar $oldTrackInfo en vervangt deze door $newTrackInfo. Weet je het zeker?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Overzicht';

  @override
  String get hook => 'Pakkende opening';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12-uursnotatie';

  @override
  String get hours => 'Tijdnotatie';

  @override
  String get iReadAndAgree => 'Ik heb gelezen en ga akkoord met';

  @override
  String get ifNotPlaying => 'Indien niet wordt afgespeeld';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Let op: als het accugebruik wordt beperkt, kunnen downloadsnelheden eveneens worden beperkt';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Gebruikelijke voorvoegsels negeren tijdens sorteren';

  @override
  String get ignores => 'Negeert';

  @override
  String get imageSource => 'Afbeeldingsbron';

  @override
  String get immersiveMode => 'Schermvullende weergave';

  @override
  String get immersiveModeSubtitle => 'Verberg status- en navigatiebalken na het vergroten van de minispeler';

  @override
  String get import => 'Importeren';

  @override
  String get importAll => 'Alles importeren';

  @override
  String get importLastFmHistory => 'Last.fm-geschiedenis importeren';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Ga naar $lastfmCsvLink;\n\n2. Voer je gebruikersnaam in en download het csv-bestand;\n\n3. Kies het bestand op het volgende scherm.';
  }

  @override
  String get importTimeRange => 'Tijdspanne importeren';

  @override
  String get importYoutubeHistory => 'YouTube-geschiedenis importeren';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Ga naar $takeoutLink\n\n2. Druk op ‘Meerdere indelingen’ en klik naast ‘Geschiedenis’ op ‘JSON’.\n\n3. Druk op ‘Alle YouTube-gegevens inbegrepen’, deselecteer alles en kies alleen voor de geschiedenis.\n\n4. Stel een export samen, download deze en pak het archiefbestand uit.\n\n5. Kies op het volgende scherm het bestand ‘watch-history.json’.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Er zijn $numberString kanalen geïmporteerd',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Er zijn $numberText afspeellijsten geïmporteerd',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Inclusief video\'s';

  @override
  String get indexRefreshRequired => 'Herlaad na aanpassen';

  @override
  String get indexer => 'Indexering';

  @override
  String get indexerNote => 'Let op: een onvolledig aantal albumhoezen verwijst naar duplicaten en niet-aangetroffen hoezen';

  @override
  String get indexerSubtitle => 'Muziekverzameling beheren';

  @override
  String get infinityQueueOnNextPrev => 'Oneindige wachtrij van volgende/vorige';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'Druk tijdens het afspelen van het laatste item op volgende om naar het eerste te gaan en vice versa';

  @override
  String get info => 'Informatie';

  @override
  String get inserted => 'ingevoegd';

  @override
  String get instantlyApplies => 'Wordt meteen toegepast';

  @override
  String get interactionReminder => 'Interactieherinnering';

  @override
  String get intro => 'Introductie';

  @override
  String get invertSelection => 'Selectie omkeren';

  @override
  String get issues => 'Problemen';

  @override
  String get item => 'Item';

  @override
  String get jump => 'Ga naar';

  @override
  String get jumpToDay => 'Ga naar dag';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Ga naar eerste nummer na afronden van wachtrij';

  @override
  String get keepCachedVersions => 'Gecachete versies behouden';

  @override
  String get keepFileDates => 'Bestandsdatums behouden';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'minispeler is uitgeklapt';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'minispeler is uitgeklapt en er een video wordt afgespeeld';

  @override
  String get keepScreenAwakeNone => 'Scherm niet ingeschakeld houden';

  @override
  String get keepScreenAwakeWhen => 'Scherm ingeschakeld houden indien';

  @override
  String get killPlayerAfterDismissingApp => 'Stoppen met afspelen na afsluiten van app';

  @override
  String get language => 'Taal';

  @override
  String get learnMore => 'Meer informatie';

  @override
  String get leftAction => 'Linkeractie';

  @override
  String get legacyAuthentication => 'Veroudere verificatie';

  @override
  String get libraryTabs => 'Verzamelingstabbladen';

  @override
  String get libraryTabsReorder => 'Je kunt de volgorde van actieve tabbladen aanpassen.';

  @override
  String get license => 'Licentie';

  @override
  String get licenseSubtitle => 'Licenties en voorwaarden van Namida';

  @override
  String get like => 'Vind ik leuk';

  @override
  String get liked => 'Vind ik leuk';

  @override
  String get link => 'Link';

  @override
  String get listOfFolders => 'Lijst met mappen';

  @override
  String get loadAll => 'Alles laden';

  @override
  String get loadingFile => 'Bezig met laden van bestand…';

  @override
  String get local => 'Lokaal';

  @override
  String get localVideoMatching => 'Lokale video-overeenkomsten';

  @override
  String get login => 'E-mailadres';

  @override
  String get longPressAction => 'Actie na ingedrukt houden';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Houd de songtekst ingedrukt om schermvullend te tonen';

  @override
  String get lostMemories => 'Verloren herinneringen';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString jaar geleden rond deze tijd',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Oude bekenden';

  @override
  String get loudnessEnhancer => 'Volumeversterker';

  @override
  String get lyricist => 'Tekstschrijver';

  @override
  String get lyrics => 'Songtekst';

  @override
  String get lyricsSource => 'Songtekstbron';

  @override
  String get m3uPlaylist => 'M3u-afspeellijst';

  @override
  String get makeYourFirstListen => 'Speel iets af!';

  @override
  String get manage => 'Beheren';

  @override
  String get manageYourAccounts => 'Accounts beheren';

  @override
  String get manualBackup => 'Handmatig';

  @override
  String get manualBackupSubtitle => 'kies een specifiek bestand';

  @override
  String get markAsRead => 'Markeren als gelezen';

  @override
  String get matchAllTracks => 'Alle nummers overeen laten komen';

  @override
  String get matchAllTracksNote => 'Let op: dit kan van invloed zijn op de snelheid, daar alle nummers worden gecontroleerd';

  @override
  String get matchingType => 'Overeenkomstig type';

  @override
  String get maxAudioCacheSize => 'Max. omvang van audiocache';

  @override
  String get maxImageCacheSize => 'Max. omvang van afbeeldingscache';

  @override
  String get maxVideoCacheSize => 'Max. omvang van videocache';

  @override
  String get maximum => 'Maximaal';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Mediaopslag is ingeschakeld, dus dit is niet van toepassing';

  @override
  String get medium => 'Gemiddeld';

  @override
  String get membershipCode => 'Code';

  @override
  String get membershipCodeSentToEmail => 'De code is per e-mail verstuurd';

  @override
  String get membershipDidntChange => 'Het abonnement is onaangetast';

  @override
  String get membershipEnjoyNew => 'Geniet van je nieuwe abonnementsvorm';

  @override
  String get membershipFreeCoupon => 'Gratis kortingsbon';

  @override
  String get membershipManage => 'Abonnement beheren';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Deze gebruiker heeft geen abonnementen';

  @override
  String get membershipSignInToPatreonAccount => 'Inloggen op Patreonaccount';

  @override
  String get membershipUnknown => 'Onbekend abonnement';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Voor het gebruik van meerdere accounts dien je over een $name1- of $name2-abonnement te beschikken';
  }

  @override
  String get merge => 'Samenvoegen';

  @override
  String get metadataCache => 'Metagegevenscache';

  @override
  String get metadataEditFailed => 'De metagegevens kunnen niet worden bewerkt';

  @override
  String get metadataReadFailed => 'De metagegevens kunnen niet worden ingelezen';

  @override
  String get minFileDuration => 'Minimale duur van nummer';

  @override
  String get minFileSize => 'Minimale bestandsgrootte';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimale duur van nummer om vorige afspeelpositie te herstellen';

  @override
  String get minValueCantBeMoreThanMax => 'De minimumwaarde kan niet boven de maximumwaarde liggen';

  @override
  String get minValueToCountTrackListen => 'Tellen als beluisterd na ';

  @override
  String get minimizedMiniplayer => 'Geminimaliseerde minispeler';

  @override
  String get minimum => 'Minimaal';

  @override
  String get minimumOneFolderSubtitle => 'Er dient ten minste één map te zijn - voeg meer mappen toe om deze te kunnen verwijderen';

  @override
  String get minimumOneItem => 'Het item kan niet worden verwijderd';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Minimaal $numberString items dienen te worden behouden',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimale duur van segment';

  @override
  String get miniplayerCustomization => 'Vormgeving van minispeler';

  @override
  String get minutes => 'minuten';

  @override
  String get missingEntries => 'Ontbrekende items';

  @override
  String get missingTracks => 'Ontbrekende nummers';

  @override
  String get mix => 'Mix';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Een door YouTube gegenereerde afspeellijst';

  @override
  String get mixes => 'Gemixt';

  @override
  String get mobile => 'Mobiel';

  @override
  String get month => 'Maand';

  @override
  String get months => 'Maanden';

  @override
  String get mood => 'Stemming';

  @override
  String get moods => 'Stemmingen';

  @override
  String get more => 'Meer';

  @override
  String get mostPlayed => 'Vaakst beluisterd';

  @override
  String get multipleTracksTagsEditNote => 'Je staat op het punt om deze nummers te bewerken.\nOnaangetaste velden blijven zoals ze zijn.';

  @override
  String get musicOfftopic => 'Ongerelateerde muziek';

  @override
  String get name => 'Naam';

  @override
  String get nameContainsBadCharacter => 'De naam bevat een niet-toegestaan teken';

  @override
  String get never => 'Nooit';

  @override
  String get newDirectory => 'Nieuwe map';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Nummers toevoegen';

  @override
  String get newTracksMoods => 'Stemming';

  @override
  String get newTracksMoodsSubtitle => 'Stel nummers samen op basis van beschikbare stemmingen';

  @override
  String get newTracksRandom => 'Willekeurig';

  @override
  String get newTracksRandomSubtitle => 'Speel willekeurige nummers uit je verzameling af';

  @override
  String get newTracksRatings => 'Waarderingen';

  @override
  String get newTracksRatingsSubtitle => 'Stel nummers met een bepaalde waardering samen';

  @override
  String get newTracksRecommended => 'Aanbevolen';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Stel nummers samen die je meestal beluisterd naar aanleiding van $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Vergelijkbare verschijningsdatum';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Stel nummers samen die zijn uitgebracht rond dezelfde periode als $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Nummer bevat onbekend jaartal';

  @override
  String get newest => 'Nieuwste';

  @override
  String get next => 'Volgende';

  @override
  String get no => 'nee';

  @override
  String get noChangesFound => 'Er zijn geen wijzigingen aangebracht.';

  @override
  String get noEnoughTracks => 'Je hebt nog niet veel nummers…';

  @override
  String get noExcludedFolders => 'Je hebt geen genegeerde mappen';

  @override
  String get noFolderChosen => 'Je hebt geen map gekozen';

  @override
  String get noMoodsAvailable => 'Er zijn geen stemmingen beschikbaar';

  @override
  String get noNetworkAvailableToFetchData => 'Er is geen internetverbinding';

  @override
  String get noTracksFound => 'Er zijn geen nummers aangetroffen';

  @override
  String get noTracksFoundBetweenDates => 'Er zijn geen nummers binnen deze tijdspanne.';

  @override
  String get noTracksFoundInDirectory => 'Er zijn geen nummers aangetroffen in deze map';

  @override
  String get noTracksInHistory => 'Je hebt te weinig nummers in de geschiedenis';

  @override
  String get nonActive => 'Inactief';

  @override
  String get nonFavourites => 'Geen favorieten';

  @override
  String get none => 'Geen';

  @override
  String get normalizeAudio => 'Audio normaliseren';

  @override
  String get normalizeAudioSubtitle => 'Normaliseer het audiovolume door de replaygaintag of YouTube-informatie uit te lezen';

  @override
  String get notAvailableForYourDevice => 'Niet beschikbaar op je apparaat';

  @override
  String get notSupportedForNetworkFiles => 'Niet ondersteund op netwerkbestanden';

  @override
  String get note => 'Opmerking';

  @override
  String get notification => 'Melding';

  @override
  String get notifications => 'Meldingen';

  @override
  String get numberOfTracks => 'Aantal nummers';

  @override
  String get ofLabel => 'van';

  @override
  String get offlineSearch => 'Offline-zoeken';

  @override
  String get offset => 'Verschuiving';

  @override
  String get oldDirectory => 'Oude map';

  @override
  String get oldDirectoryStillHasTracks => 'De oude map bevat nog nummers. Weet je het zeker?';

  @override
  String get oldestWatch => 'Langst geleden bekeken';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Na onderbreking';

  @override
  String get onNotificationTap => 'Na drukken op melding';

  @override
  String get onOpeningYoutubeLink => 'Na openen van YouTubelink';

  @override
  String get onSwiping => 'Na vegen';

  @override
  String get onVolumeZero => 'Na bereiken van volumeniveau 0';

  @override
  String get ongoing => 'In uitvoering';

  @override
  String get open => 'Openen';

  @override
  String get openApp => 'App openen';

  @override
  String get openInFileExplorer => 'Openen in bestandsbeheerder';

  @override
  String get openInYoutubeView => 'Openen in YouTubeweergave';

  @override
  String get openMiniplayer => 'Minispeler openen';

  @override
  String get openQueue => 'Wachtrij tonen';

  @override
  String get openYoutubeLink => 'YouTubelink openen';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Voor het gebruik van ‘$name’ is een account vereist - log in om door te gaan';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Voor het gebruik van ‘$operation’ is minimaal het $name-abonnement vereist';
  }

  @override
  String get or => 'of';

  @override
  String get others => 'Overig';

  @override
  String get output => 'Uitvoer';

  @override
  String get outro => 'Aftiteling';

  @override
  String get overrideOldFilesInTheSameFolder => 'Oude bestand in dezelfde map overschrijven';

  @override
  String get palette => 'Palet';

  @override
  String get paletteMix => 'Mix';

  @override
  String get paletteNewMix => 'Nieuwe mix';

  @override
  String get paletteSelectedMix => 'Gekozen mix';

  @override
  String get parallelDownloads => 'Gelijktijdige downloads';

  @override
  String get parsed => 'verwerkt';

  @override
  String get password => 'Wachtwoord';

  @override
  String get path => 'Volledige bestandslocatie';

  @override
  String get pause => 'Pauzeren';

  @override
  String get pauseFadeDuration => 'Vervaagduur na pauzeren';

  @override
  String get pausePlayback => 'Afspelen pauzeren';

  @override
  String get percentage => 'Percentage';

  @override
  String get performanceMode => 'Prestatiemodus';

  @override
  String get performanceNote => 'Let op: dit kan van invloed zijn op de prestaties';

  @override
  String get personalized => 'Gepersonaliseerd';

  @override
  String get personalizedRelatedVideos => 'Gepersonaliseerde gerelateerde video\'s';

  @override
  String get personalizedRelatedVideosSubtitle => 'Let op: uitschakelen verhoogt het gegevensverbruik';

  @override
  String get pickColorsFromDeviceWallpaper => 'Kleuren van startschermachtergrond gebruiken';

  @override
  String get pickFromStorage => 'Kies uit interne opslag';

  @override
  String get pinned => 'Vastgemaakt';

  @override
  String get pitch => 'Toonhoogte';

  @override
  String get plain => 'Plat';

  @override
  String get play => 'Afpelen';

  @override
  String get playAfter => 'Afspelen na';

  @override
  String get playAfterNextPrev => 'Automatisch afspelen na volgende/vorige';

  @override
  String get playAll => 'Alles afspelen';

  @override
  String get playFadeDuration => 'Vervaagduur na afspelen';

  @override
  String get playLast => 'Als laatste afspelen';

  @override
  String get playNext => 'Als volgende afspelen';

  @override
  String get playbackSetting => 'Afspelen';

  @override
  String get playbackSettingSubtitle => 'Houd de audioknop op de speler lang ingedrukt om te openen';

  @override
  String get playlist => 'Afspeellijst';

  @override
  String get playlists => 'Afspeellijsten';

  @override
  String get playlistsImportM3uNative => 'Hiermee importeer je m3u-afspeellijsten naar Namida - gebruik alleen tijdens migratie';

  @override
  String get playlistsImportM3uSynced =>
      'Hiermee importeert je m3u-afspeellijsten uit geïndexeerde mappen en houd je ze gesynchroniseerd met het oorspronkelijke bestand. Schakel in als je wel eens afspeellijsten vanuit andere apps opent/bewerkt.';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'M3u-afspeellijsten automatisch importeren';

  @override
  String get pleaseEnterADifferentName => 'Deze naam is al in gebruik. :(\nKies een andere mooie naam';

  @override
  String get pleaseEnterALink => 'Voer een link in';

  @override
  String get pleaseEnterALinkSubtitle => 'Eh… is dit wel een YouTubelink?';

  @override
  String get pleaseEnterAName => 'Voer een naam in';

  @override
  String get port => 'Poort';

  @override
  String get preventDuplicatedTracks => 'Duplicaten voorkomen';

  @override
  String get preventDuplicatedTracksSubtitle => 'Maakt gebruik van bestandsnamen om nummers te identificeren';

  @override
  String get preview => 'Voorvertoning';

  @override
  String get previous => 'Vorige';

  @override
  String get previousButtonReplays => 'Herhalen na drukken op vorige';

  @override
  String get previousButtonReplaysSubtitle => 'Indien ingedrukt nadat de huidige positie verder dan de spoelduur lag';

  @override
  String get prioritizeEmbeddedLyrics => 'Voorkeur voor meegeleverde songtekst';

  @override
  String get priority => 'Prioriteit';

  @override
  String get private => 'Privé';

  @override
  String get progress => 'Voortgang';

  @override
  String get promptToChangeTrackPath => 'Dit gebeurt meestal zodra je een bestand buiten Namida verwijdert, verplaatst of van naam wijzigt. Wil je de locatie bijwerken?';

  @override
  String get public => 'Openbaar';

  @override
  String get queue => 'Wachtrij';

  @override
  String get queues => 'Wachtrijen';

  @override
  String get random => 'Willekeurig';

  @override
  String get randomPicks => 'Willekeurige keuzes';

  @override
  String get rating => 'Waardering';

  @override
  String get reIndex => 'Herindexeren';

  @override
  String get reIndexSubtitle => 'Stel je verzameling vanaf nul samen';

  @override
  String get reIndexWarning =>
      'Let op: dit kan – afhankelijk van de omvang van je verzameling – even duren.\n\nAlbumhoezen worden niet opnieuw geïndexeerd, tenzij het nieuwe hoezen betreft.';

  @override
  String get recentAlbums => 'Recente albums';

  @override
  String get recentArtists => 'Recente artiesten';

  @override
  String get recentListens => 'Recent beluisterd';

  @override
  String get recentlyAdded => 'Onlangs toegevoegd';

  @override
  String get recordLabel => 'Platenlabel';

  @override
  String get refresh => 'Herladen';

  @override
  String get refreshLibrary => 'Verzameling herladen';

  @override
  String get refreshLibrarySubtitle => 'Controleer op nieuwe of verwijderde muziek';

  @override
  String get refreshOnStartup => 'Herladen na opstarten';

  @override
  String get relatedVideos => 'Gerelateerde video\'s';

  @override
  String get rememberAudioOnlyMode => 'Audiomodus onthouden';

  @override
  String get remixer => 'Remixen';

  @override
  String get remove => 'Verwijderen';

  @override
  String get removeDuplicates => 'Duplicaten verwijderen';

  @override
  String get removeFromFavourites => 'Verwijderen uit favorieten';

  @override
  String get removeFromLibrary => 'Verwijderen uit verzameling';

  @override
  String get removeFromPlaylist => 'Verwijderen van afspeellijst';

  @override
  String get removeQueue => 'Wachtrij wissen';

  @override
  String get removeSourceFromHistory => 'Bron uit geschiedenis verwijderen';

  @override
  String get removeWhitespaces => 'Witruimtes wissen';

  @override
  String get removed => 'Verwijderd';

  @override
  String get rename => 'Naam wĳzigen';

  @override
  String get renamePlaylist => 'Afspeellijstnaam wĳzigen';

  @override
  String get reorderable => 'Hersorteerbaar';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number keer herhalen',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Herhaalmodus';

  @override
  String get repeatModeAll => 'Gehele wachtrij herhalen';

  @override
  String get repeatModeNone => 'Stoppen na laatste nummer';

  @override
  String get repeatModeOne => 'Huidig nummer herhalen';

  @override
  String get replaceAllListensWithAnotherTrack => 'Alle beluisteringen vervangen door ander nummer';

  @override
  String get replies => 'Antwoorden';

  @override
  String get reply => 'Beantwoorden';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Vereist wissen van de afbeeldingscache en opnieuw indexeren';

  @override
  String get rescanVideos => 'Video\'s opnieuw indexeren';

  @override
  String get resetBrightness => 'Standaard helderheid';

  @override
  String get resetToDefault => 'Instellen op';

  @override
  String get respectNoMedia => '.nomedia respecteren';

  @override
  String get respectNoMediaSubtitle => 'Neem geen mappen op die .nomedia bevatten';

  @override
  String get restart => 'Herstarten';

  @override
  String get restoreBackup => 'Reservekopie herstellen';

  @override
  String get restoreDefaults => 'Standaardwaarden herstellen';

  @override
  String get restoredBackupSuccessfully => 'Reservekopie hersteld';

  @override
  String get restoredBackupSuccessfullySub => 'Het reservekopiebestand is hersteld';

  @override
  String get resume => 'Hervatten';

  @override
  String get resumeIfWasInterrupted => 'Hervatten na onderbreking';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Hervatten na volumeonderbreking';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Hervatten na pauzering van minder dan $numberString minuten',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Vind-ik-niet-leukknop tonen';

  @override
  String get reverseOrder => 'Volgorde omdraaien';

  @override
  String get rightAction => 'Rechteractie';

  @override
  String get ringtone => 'Beltoon';

  @override
  String get sameDirectoryOnly => 'Alleen uit dezelfde map';

  @override
  String get sample => 'Voorbeeld';

  @override
  String get sampleRate => 'Samplesnelheid';

  @override
  String get save => 'Opslaan';

  @override
  String get saveToLibrary => 'Opslaan in verzameling';

  @override
  String get savedIn => 'Opgeslagen is';

  @override
  String get scaleMultiplier => 'Groottevermenigvuldiging';

  @override
  String get search => 'Zoeken';

  @override
  String get searchYoutube => 'YouTube doorzoeken';

  @override
  String get seconds => 'seconden';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'Bekijk de projectcode op $site';
  }

  @override
  String get seekDuration => 'Spoelduur';

  @override
  String get seekDurationInfo => 'Tip: druk op de huidige duur om terug te spoelen en op de totaalduur om vooruit te spoelen';

  @override
  String get seekbar => 'Spoelbalk';

  @override
  String get selectAll => 'Alles selecteren';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Kies bestanden uit lokale verzameling';

  @override
  String get selectedTracks => 'Gekozen nummers';

  @override
  String get selfPromotion => 'Zelfpromotie';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Deze woorden worden niet opgedeeld';

  @override
  String get separatorsMessage => 'Je hoeft geen spaties te gebruiken, tenzij je een letter of symbool uit een woord wilt opnemen, bijvoorbeeld ‘x’ of ‘ft.’';

  @override
  String get serverAddress => 'Serveradres';

  @override
  String get setAs => 'Instellen als';

  @override
  String get setAsDefault => 'Instellen als standaard';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Recentste bestandsbewerking gebruiken als uploaddatum';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Stemmingen instellen';

  @override
  String get setMoodsSubtitle => 'Gebruik een komma (,) als scheidingsteken';

  @override
  String get setRating => 'Waardering instellen';

  @override
  String get setTags => 'Tags instellen';

  @override
  String get setYoutubeLink => 'YouTubelink instellen';

  @override
  String get settings => 'Instellingen';

  @override
  String get setupFirstStartup => 'Instelhulp';

  @override
  String get share => 'Delen';

  @override
  String get shareLogs => 'Logboek delen';

  @override
  String get shortcuts => 'Sneltoetsen';

  @override
  String get shouldDuck => 'Verlagen';

  @override
  String get shouldDuckNote => 'Geeft aan dat het volume verlaagd moet worden, bijvoorbeeld door middel van een melding';

  @override
  String get shouldPause => 'Pauzeren';

  @override
  String get shouldPauseNote => 'Geeft aan dat het afspelen onderbroken moet worden, bijvoorbeeld tijdens een oproep';

  @override
  String get showAll => 'Alles inschakelen';

  @override
  String get showChannelWatermarkInFullscreen => 'Watermerk van kanaal schermvullend tonen';

  @override
  String get showFailedOnly => 'Alleen foutmeldingen';

  @override
  String get showHideUnknownFields => 'Onbekende velden tonen/verbergen';

  @override
  String get showInSeekbar => 'Tonen op spoelbalk';

  @override
  String get showMixPlaylistsIn => 'Mixen tonen in';

  @override
  String get showMore => 'Meer tonen';

  @override
  String get showShortVideosIn => 'Shorts tonen in';

  @override
  String get showSkipButton => 'Overslaanknop tonen';

  @override
  String get showVideoEndcards => 'Eindschermen van video\'s tonen';

  @override
  String get showWebm => 'Webm tonen';

  @override
  String get shuffle => 'Willekeurig afspelen';

  @override
  String get shuffleAll => 'Alles willekeurig afspelen';

  @override
  String get shuffleNext => 'Volgende willekeurig afspelen';

  @override
  String get signIn => 'Inloggen';

  @override
  String get signInCanceled => 'Het inloggen is afgebroken';

  @override
  String get signInFailed => 'Het inloggen is mislukt';

  @override
  String get signInToYourAccount => 'Log in op je account';

  @override
  String get signInYouDontHaveAccount => 'Je bent niet ingelogd';

  @override
  String get signInYouNeedAccountToViewPage => 'Voor het gebruik van deze pagina is een account vereist';

  @override
  String get signOut => 'Uitloggen';

  @override
  String signOutFromName({required String name}) {
    return 'Uitloggen op $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Log in om de basisfuncties te kunnen gebruiken';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Verkrijg vroegtijdige toegang door lid te worden op Patreon of door middel van een kortingsbon';

  @override
  String get similarDiscoverDate => 'Vergelijkbare ontdekkingsdatum';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Maak nummers die je ontdekt hebt rond dezelfde tijd als $currentTrack';
  }

  @override
  String get similarTimeRange => 'Vergelijkbare tijdspanne';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Maak nummers die je beluisterd hebt rond dezelfde tijd als $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => 'Grootte';

  @override
  String get skip => 'Overslaan';

  @override
  String get skipCountTracking => 'Geen aantallen bijhouden';

  @override
  String get skipSilence => 'Stilte onderdrukken';

  @override
  String get skipSponsorSegmentsInVideos => 'Sponsorsegmenten in video\'s overslaan';

  @override
  String get sleepAfter => 'Slaapstand na';

  @override
  String get sleepTimer => 'Tijdklok';

  @override
  String get socials => 'Sociale media';

  @override
  String get socialsSubtitle => 'Volg ons op de diverse platforms om updates, tips en discussies te ontvangen';

  @override
  String get someWebServersRequireAuthentication => 'Sommige webservers vereisen verificatie. Werk je inloggegevens bij om toegang tot je bibliotheek te verzekeren.';

  @override
  String get sortBy => 'Sorteren op';

  @override
  String get source => 'Bron';

  @override
  String get speed => 'Snelheid';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock-klassement';

  @override
  String get staggeredAlbumGridView => 'Gestapelde albumweergave';

  @override
  String get start => 'Starten';

  @override
  String get stats => 'Statistieken';

  @override
  String get statsSubtitle => 'Informatie over mijn verzameling';

  @override
  String get stop => 'Stoppen';

  @override
  String get stopAfterThisTrack => 'Stoppen na dit nummer';

  @override
  String get stopAfterThisVideo => 'Stoppen na deze video';

  @override
  String get storagePermissionDenied => 'Toegang geweigerd';

  @override
  String get storagePermissionDeniedSubtitle => 'Geef Namida toegang om deze actie uit te kunnen voeren';

  @override
  String get stretchLyricsDuration => 'Songteksttijd op scherm verlengen';

  @override
  String get subdirectory => 'Onderliggende map';

  @override
  String get subscribe => 'Abonneren';

  @override
  String get subscribed => 'Geabonneerd';

  @override
  String get subscriber => 'Abonnee';

  @override
  String get subscribers => 'Abonnees';

  @override
  String get succeeded => 'Voltooid';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Ervaar je een probleem of wil je een idee delen? Open dan een draadje op $site';
  }

  @override
  String get support => 'Ondersteuning';

  @override
  String get supremacy => 'Overheersing';

  @override
  String get sussyBaka => 'Ouwe, je hebt geen nummers';

  @override
  String get swipeActions => 'Veegacties';

  @override
  String get swipeToOpenDrawer => 'Veeg om het navigatiemenu te openen';

  @override
  String get synced => 'Gesynchroniseerd';

  @override
  String get synopsis => 'Samenvatting';

  @override
  String get tagFields => 'Tagvelden';

  @override
  String get tags => 'Tags';

  @override
  String get tapAction => 'Indrukactie';

  @override
  String get tapToSeek => 'Druk om te spoelen';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Thema';

  @override
  String get themeModeDark => 'Donker thema';

  @override
  String get themeModeLight => 'Licht thema';

  @override
  String get themeModeSystem => 'Systeemthema';

  @override
  String get themeSettings => 'Thema';

  @override
  String get themeSettingsSubtitle => 'De algemene vormgeving van de speler';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Deze afspeellijst bevat actieve sorteerfilters - schakel die eerst uit.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Deze video is verwijderd of ingesteld als privé.';

  @override
  String get thumbnails => 'Miniaturen';

  @override
  String get title => 'Titel';

  @override
  String get top => 'Bovenaan';

  @override
  String get topComments => 'Reacties bovenaan tonen';

  @override
  String get topCommentsSubtitle => 'Toon reacties bovenaan in plaats van onderaan';

  @override
  String get topRecentAlbums => 'Toplijst recente albums';

  @override
  String get topRecentArtists => 'Toplijst recente artiesten';

  @override
  String get topRecents => 'Toplijst';

  @override
  String get totalListenTime => 'Totale luistertijd';

  @override
  String get totalListens => 'Totaalaantal beluisteringen';

  @override
  String get totalTracks => 'Totaalaantal nummers';

  @override
  String get totalTracksDuration => 'Totale nummerduur';

  @override
  String get track => 'Nummer';

  @override
  String get trackArtistsSeparator => 'Artiestscheidingstekens';

  @override
  String get trackGenresSeparator => 'Genrescheidingstekens';

  @override
  String get trackInfo => 'Nummerinformatie';

  @override
  String get trackNotFound => 'Nummer niet aangetroffen';

  @override
  String get trackNumber => 'Volgnummer';

  @override
  String get trackNumberTotal => 'Totaal';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Oude naam: “$oldName”\n\nNieuwe naam: “$newName”\n\nWeet je het zeker?';
  }

  @override
  String get trackPlayMode => 'Afspeelmodus';

  @override
  String get trackPlayModeSearchResults => 'Zoekresultaten';

  @override
  String get trackPlayModeSelectedOnly => 'Alleen gekozen nummer';

  @override
  String get trackPlayModeTrackAlbum => 'Van album';

  @override
  String get trackPlayModeTrackArtist => 'Nummerartiest';

  @override
  String get trackPlayModeTrackGenre => 'Genre van nummer';

  @override
  String get trackThumbnailSizeInList => 'Afmetingen van minatuur';

  @override
  String get trackTileCustomization => 'Tegelaanpassing';

  @override
  String get trackTileItemsSeparator => 'Itemscheiding';

  @override
  String get tracks => 'Nummers';

  @override
  String get tracksExcludedByNomedia => 'Nummers met .nomedia negeren';

  @override
  String get tracksInfo => 'Nummerinformatie';

  @override
  String get underrated => 'Ondergewaardeerd';

  @override
  String get undo => 'Ongedaan maken';

  @override
  String get undoChanges => 'Weet je het zeker?';

  @override
  String get undoChangesDeletedPlaylist => 'Verwijderde afspeellijst herstellen';

  @override
  String get undoChangesDeletedQueue => 'Verwijderde wachtrij herstellen';

  @override
  String get undoChangesDeletedTrack => 'Verwijderd nummer herstellen';

  @override
  String get uniqueArtworkHash => 'Unieke controlesom van hoes';

  @override
  String get unlimited => 'Onbeperkt';

  @override
  String get unlisted => 'Niet-vermeld';

  @override
  String get unlock => 'Ontgrendelen';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Bijwerken';

  @override
  String get updateDirectoryPath => 'Locatie bijwerken';

  @override
  String get updateMissingTracksOnly => 'Alleen ontbrekende nummers bijwerken';

  @override
  String get updating => 'Bezig met bijwerken…';

  @override
  String get useCollapsedSettingTiles => 'Ingeklapte instellingstegels gebruiken';

  @override
  String get useMediaStore => 'Mediaopslag gebruiken';

  @override
  String get useMediaStoreSubtitle =>
      '✓ Onmiddellijke zoekresultaten;\nx ‘.nomedia respecteren’ wordt ingeschakeld;\nx Enkele metagegevenstags zullen ontbreken;\nx YouTubeintegratie met lokale verzameling zal niet werken.';

  @override
  String get usePitchBlack => 'Zwart thema';

  @override
  String get usePitchBlackSubtitle => 'Speciaal voor amoledschermen en ziet er bovendien toffer uit';

  @override
  String get used => 'Gebruikt';

  @override
  String get value => 'Waarde';

  @override
  String get valueBetween50200 => 'De waarde moet tussen de 50 en 200% liggen';

  @override
  String get vibration => 'Trillen';

  @override
  String get vibrationType => 'Soort trilling';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Videocache';

  @override
  String get videoCacheFile => 'Gecachet videobestand';

  @override
  String get videoCacheFiles => 'Gecachete videobestanden';

  @override
  String get videoOnly => 'Alleen video';

  @override
  String get videoPlaybackSource => 'Videobron';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'Hiermee wordt prioriteit gegeven aan lokale video\'s - pas bij geen resultaten wordt YouTube geraadpleegd';

  @override
  String get videoPlaybackSourceLocal => 'Lokale video\'s';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'André Hazes - Eenzame kerst.m4a\nVideo André Hazes - Eenzame kerst (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Controleert of videobestanden van de mappenlijst de bestandsnaam van het nummer in kwestie bevatten';

  @override
  String get videoPlaybackSourceYoutube => 'Van YouTube';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'Controleert of de bestandsnaam en -opmerking overeenkomen met een YouTubelink. Video\'s worden opgeslagen in de cache.';

  @override
  String get videoQuality => 'Videokwaliteit';

  @override
  String get videoQualitySubtitle => 'De hoogst ingestelde kwaliteit zal worden gekozen';

  @override
  String get videoQualitySubtitleNote => 'Het is goed om alternatieven te hebben voor als een kwaliteit niet beschikbaar is, anders wordt de slechtste kwaliteit gekozen';

  @override
  String get videos => 'Video\'s';

  @override
  String get view => 'weergave';

  @override
  String get viewAll => 'Alles bekijken';

  @override
  String get views => 'weergaven';

  @override
  String get volume => 'Volumeniveau';

  @override
  String get warning => 'Waarschuwing';

  @override
  String get waveformBarsCount => 'Aantal balken op golfvorm';

  @override
  String get webmNoEditTagsSupport => 'Webm heeft geen ondersteuning voor het aanpassen van tags';

  @override
  String get week => 'Week';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Jaar';

  @override
  String get yes => 'ja';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Je huidige abonnementsvorm is $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Je aangepaste volgorde wordt gewist. Weet je het zeker?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'Pas het gebruik van YouTube aan';

  @override
  String get youtubeStyleMiniplayer => 'YouTube-achtige minispeler';

  @override
  String get ytPreferNewComments => 'Voorkeur voor nieuwe reacties (indien mogelijk)';

  @override
  String get ytPreferNewCommentsSubtitle => 'De gecachete versie zal alleen worden gebruikt als er geen internetverbinding is';
}
