// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Japanese (`ja`).
class AppLocalizationsJa extends AppLocalizations {
  AppLocalizationsJa([String locale = 'ja']) : super(locale);

  @override
  String get about => 'アプリについて';

  @override
  String get active => '有効';

  @override
  String get add => '追加';

  @override
  String get addAccount => 'アカウントを追加';

  @override
  String get addAll => 'すべて追加';

  @override
  String get addAllAndRemoveOldOnes => '古いものを削除し、すべて追加';

  @override
  String get addAsANewPlaylist => '新しいプレイリストとして追加';

  @override
  String get addAudioToLocalLibrary => 'ローカルライブラリから音楽を追加';

  @override
  String get addFolder => 'フォルダを追加';

  @override
  String get addLanguage => '言語を追加';

  @override
  String get addLanguageSubtitle => 'あなたの言語でNamidaの翻訳を助ける';

  @override
  String get addLrcFile => 'LRCファイルを追加';

  @override
  String get addMoreFromThisAlbum => 'このアルバムからさらにキューに追加';

  @override
  String get addMoreFromThisArtist => 'このアーティストからさらにキューに追加';

  @override
  String get addMoreFromThisFolder => 'このフォルダからさらにキューに追加';

  @override
  String addMoreFromToQueue({required String media}) {
    return '$media からさらにキューに追加';
  }

  @override
  String get addOnlyMissing => '欠落しているものだけ追加';

  @override
  String get addToFavourites => 'お気に入りに追加';

  @override
  String get addToPlaylist => 'プレイリストに追加';

  @override
  String get addTracksAtTheBeginning => '先頭にトラックを追加';

  @override
  String get added => '追加済';

  @override
  String get advanced => '高度';

  @override
  String get advancedSettings => '高度';

  @override
  String get advancedSettingsSubtitle => '高度な設定、触らないことを推奨';

  @override
  String get alarm => 'アラーム';

  @override
  String get album => 'アルバム';

  @override
  String get albumArtist => 'アルバムアーティスト';

  @override
  String get albumArtists => 'アルバムアーティスト';

  @override
  String get albumIdentifiers => 'アルバムの識別方法';

  @override
  String get albumThumbnailSizeInList => 'アルバムのサムネイルの大きさ';

  @override
  String get albumTileCustomization => 'アルバムタイルのカスタマイズ';

  @override
  String get albums => 'アルバム';

  @override
  String get albumsCount => 'アルバム数';

  @override
  String get all => '全て';

  @override
  String get allTime => '全期間';

  @override
  String get alreadyExists => 'すでに存在';

  @override
  String get always => '常に';

  @override
  String get alwaysAsk => '常に尋ねる';

  @override
  String get alwaysDim => '常に暗転';

  @override
  String get alwaysExpandedSearchbar => '常に検索バーを拡張する';

  @override
  String get alwaysRestore => '常に復元';

  @override
  String get animatingThumbnailIntensity => 'サムネイルアニメーションの大きさ';

  @override
  String get animatingThumbnailInversed => 'アニメーションを逆転';

  @override
  String get animatingThumbnailInversedSubtitle => '高に設定するとサムネイルが小さくなります';

  @override
  String get anotherProcessIsRunning => '別のプロセスがすでに実行されています。';

  @override
  String get appIcon => 'アプリアイコン';

  @override
  String get appVersion => 'アプリのバージョン';

  @override
  String get artist => 'アーティスト';

  @override
  String get artists => 'アーティスト';

  @override
  String get artwork => 'アートワーク';

  @override
  String get artworkGestures => 'アートワークのジェスチャー';

  @override
  String get artworks => 'アートワーク';

  @override
  String get audio => '音声';

  @override
  String get audioCache => '音声キャッシュ';

  @override
  String get audioOnly => '音声のみ';

  @override
  String get auto => '自動';

  @override
  String get autoBackupInterval => '自動バックアップの間隔';

  @override
  String get autoColoring => '自動カラーリング';

  @override
  String get autoColoringSubtitle => '現在のアートワークからプレーヤーの色を自動的に選択';

  @override
  String get autoExtractTagsFromFilename => 'ファイル名から自動抽出';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => '動画タイトルからタイトルとアーティストを自動的に抽出';

  @override
  String get autoGenerated => '自動生成';

  @override
  String get autoSkip => '自動的にスキップ';

  @override
  String get autoSkipOnce => '1度だけ自動的にスキップ';

  @override
  String get autoStartRadio => 'ラジオを自動再生';

  @override
  String get autoStartRadioSubtitle => '1曲再生時にミックスプレイリストを自動的に追加';

  @override
  String get automaticBackup => '自動的';

  @override
  String get automaticBackupSubtitle => 'バックアップ場所内で見つかった最新のバックアップファイルを自動的に適用';

  @override
  String get backupAndRestore => 'バックアップ & 復元';

  @override
  String get backupAndRestoreSubtitle => 'データベースと設定をバックアップ';

  @override
  String get balanced => 'バランス';

  @override
  String get beta => 'ベータ';

  @override
  String get betweenDates => '日付の間';

  @override
  String get bitrate => 'ビットレート';

  @override
  String get blacklist => 'ブラックリスト';

  @override
  String get borderRadiusMultiplier => '縁の半径乗数';

  @override
  String get cache => 'キャッシュ';

  @override
  String get cancel => 'キャンセル';

  @override
  String get canceled => 'キャンセル';

  @override
  String get changed => '更新済';

  @override
  String get changelog => '更新履歴';

  @override
  String get changelogSubtitle => 'Namida内に新しく追加/修正されたものを見る';

  @override
  String get channel => 'チャンネル';

  @override
  String get channels => 'チャンネル';

  @override
  String get check => '確認';

  @override
  String get checkForMore => 'もっと見る';

  @override
  String get checkList => 'リストを見る';

  @override
  String get choose => '選択';

  @override
  String get chooseWhatToClear => 'クリアする項目を選択';

  @override
  String get claim => '請求';

  @override
  String get clear => 'クリア';

  @override
  String get clearAudioCache => '音声キャッシュをクリア';

  @override
  String get clearImageCache => '画像キャッシュをクリア';

  @override
  String get clearImageCacheWarning => '警告：画像のないライブラリが作成されます。画像キャッシュを再構築する場合にのみ使用してください。';

  @override
  String get clearTrackItem => 'トラックをクリア';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString 個のトラックをクリア',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => '映像キャッシュをクリア';

  @override
  String get clearVideoCacheNote => '削除するものを選択してください。';

  @override
  String get clock => '時計';

  @override
  String get colorPalette => 'カラーパレット';

  @override
  String get colorPaletteNote1 => '色を長押しすると削除できます';

  @override
  String get colorPaletteNote2 => '既定の色として利用するミックスをタップ';

  @override
  String get colorPalettes => 'カラーパレット';

  @override
  String get comment => 'コメント';

  @override
  String get comments => 'コメント';

  @override
  String get composer => '作曲者';

  @override
  String get compress => '圧縮';

  @override
  String get compressImages => '画像を圧縮';

  @override
  String get compressionPercentage => '圧縮率';

  @override
  String get configure => '構成';

  @override
  String get confirm => '承認';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'アートワークをコピー';

  @override
  String get copiedToClipboard => 'クリップボードからコピー';

  @override
  String get copy => 'コピー';

  @override
  String get corruptedFile => 'ファイルの解析に失敗しました。ファイルが破損している可能性があります';

  @override
  String get couldntOpen => '開けません :(';

  @override
  String get couldntOpenYtLink => 'このトラックには YouTubeリンクがありません';

  @override
  String get couldntPlayFile => '音声ファイルを再生できませんでした';

  @override
  String get couldntRenamePlaylist => 'プレイリスト名を変更できませんでした';

  @override
  String get couldntSaveImage => '画像を保存できませんでした';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => '国';

  @override
  String get coupon => 'クーポン';

  @override
  String get create => '作成';

  @override
  String get createBackup => 'バックアップを作成';

  @override
  String get createNewPlaylist => '新しいプレイリストを作成';

  @override
  String get createdBackupSuccessfully => '作成されたバックアップ';

  @override
  String get createdBackupSuccessfullySub => 'バックアップファイルの作成に成功しました';

  @override
  String get crossPlatformSync => 'クロスプラットフォーム間での同期';

  @override
  String get crossfadeDuration => 'クロスフェード時間';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '終わる $secondsString 秒前からクロスフェードを自動的に開始',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'クロスフェードを自動的に開始しない';

  @override
  String get custom => 'カスタム';

  @override
  String get customizations => 'カスタマイズ';

  @override
  String get customizationsSubtitle => 'プレーヤーをカスタマイズして、自分だけの見た目にしましょう';

  @override
  String dataIsProvidedByName({required String name}) {
    return '$name によるデータ';
  }

  @override
  String get dataSaver => 'データセーバー';

  @override
  String get dataSaverMode => 'データセーバーモード';

  @override
  String get database => 'データベース';

  @override
  String get date => '日付';

  @override
  String get dateAdded => '追加した日付';

  @override
  String get dateCreated => '作成した日付';

  @override
  String get dateModified => '変更日';

  @override
  String get dateTimeFormat => '日付時刻形式';

  @override
  String get day => '日';

  @override
  String get days => '日';

  @override
  String get defaultBackupLocation => '既定のバックアップ場所';

  @override
  String get defaultColor => '既定の色';

  @override
  String get defaultColorSubtitle => 'プレーヤーで使用する色を設定';

  @override
  String get defaultDownloadLocation => '既定のダウンロード場所';

  @override
  String get defaultLabel => '既定';

  @override
  String get defaultLibraryTab => '既定のライブラリタブ';

  @override
  String get delete => '削除';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$totalSizeText相当の、$countString個のファイルを削除しますか？',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'ストレージから $numberText を完全に削除';
  }

  @override
  String get deletePlaylist => 'プレイリストを削除';

  @override
  String get deleteTempFiles => 'tempファイルを削除';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => '説明';

  @override
  String get developer => 'デベロッパー';

  @override
  String get development => '開発';

  @override
  String get didYouMean => 'もしかして';

  @override
  String get dimIntensity => '濃淡';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString 秒間操作しないとミニプレーヤーが暗くなります',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'ディレクトリが存在しません';

  @override
  String get disable => '無効';

  @override
  String get disableAll => '全て無効';

  @override
  String get disableReordering => '並べ替えを無効にする';

  @override
  String get disableSearchCleanup => '検索クリーンアップを無効にする';

  @override
  String get discNumber => 'ディスク番号';

  @override
  String get discNumberTotal => 'ディスク総量';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => '嫌い';

  @override
  String get dismissibleMiniplayer => 'ミニプレーヤーを閉じられるようにする';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'シーク中にその位置の実際の再生時間を表示する';

  @override
  String get displayAlbumCardTopRightDate => 'アルバムカード右上に日付';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'アルバムカードの右上にアルバムの日付を表示する';

  @override
  String get displayArtistBeforeTitle => 'タイトルの前にアーティストを表示';

  @override
  String get displayArtworkOnLockscreen => 'ロック画面でアートワークを表示する';

  @override
  String get displayAudioInfoInMiniplayer => 'オーディオ情報を表示する';

  @override
  String get displayFavButtonInNotification => '通知にお気に入りボタンを表示する';

  @override
  String get displayFavButtonInNotificationSubtitle => 'サムネイルがずれる場合があります。';

  @override
  String get displayFavouriteIconInTrackTile => 'お気に入りボタンを表示する';

  @override
  String get displayRemainingDurationInsteadOfTotal => '合計時間ではなく残り時間を表示する';

  @override
  String get displayStopButtonInNotification => '通知に停止ボタンを表示する';

  @override
  String get displayThirdItemInRowInTrackTile => '各行に3番目の項目を表示する';

  @override
  String get displayThirdRowInTrackTile => '三番目の項目を表示する';

  @override
  String get displayTrackNumberInAlbumPage => 'アルバムでトラック番号を表示する';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'アルバムにトラック番号の小さなボックスを表示する';

  @override
  String get doNothing => 'なにもしない';

  @override
  String get donate => '寄付';

  @override
  String get donateSubtitle => 'このアプリが役に立ったなら寄付できます';

  @override
  String get done => '完了';

  @override
  String get dontAskAgain => '二度と表示しない';

  @override
  String get dontDim => '暗転しない';

  @override
  String get dontRestorePosition => '復元しない';

  @override
  String get dontResume => '再開しない';

  @override
  String get doubleTapToToggleLyrics => 'ダブルタップで歌詞が切り替わる';

  @override
  String get download => 'ダウンロード';

  @override
  String get downloadingWillOverrideIt => 'ダウンロードすると上書きされます';

  @override
  String get downloads => 'ダウンロード';

  @override
  String get downloadsMetadataTags => 'メタデータタグをダウンロード';

  @override
  String get downloadsMetadataTagsSubtitle => 'デフォルトで動画情報からアーティスト、タイトル、アルバムを抽出する';

  @override
  String get dragToSeek => 'ドラッグして探す';

  @override
  String get duckAudio => '音量を下げる';

  @override
  String get duplicatedItemsAdding => 'そのアイテムは既に追加されています';

  @override
  String get duplicatedTracks => '重複したトラック';

  @override
  String get duration => '間隔';

  @override
  String get edgeColorsSwitching => '縁色を切り替える';

  @override
  String get edit => '編集';

  @override
  String get editArtwork => 'アートワークを編集';

  @override
  String get editTags => 'タグを編集';

  @override
  String get email => 'E−メール';

  @override
  String get emptyNonMeaningfulTagFields => '空の値や意味のない値を持つフィールドがある場合に確認する';

  @override
  String get emptyValue => '空の値';

  @override
  String get enableArtworkCache => 'アートワークキャッシュの有効化';

  @override
  String get enableArtworkCacheSubtitle => '読み込みが速くなりパフォーマンスも向上しますが、ストレージの消費量が増加します';

  @override
  String get enableBlurEffect => 'ぼかしエフェクトを有効化';

  @override
  String get enableBottomNavBar => '下部ナビゲーションバーを有効化';

  @override
  String get enableBottomNavBarSubtitle => 'エントリは引き続きドロワーに表示されます';

  @override
  String get enableClipboardMonitoring => 'クリップボード監視を有効化';

  @override
  String get enableClipboardMonitoringSubtitle => '検索バーにその場でリンクやテキストを挿入できます';

  @override
  String get enableCrossfadeEffect => 'クロスフェードエフェクトを有効化';

  @override
  String get enableFadeEffectOnPlayPause => '再生/一時停止時のフェード効果を有効化';

  @override
  String get enableFoldersHierarchy => 'フォルダのヒエラルキーを有効化';

  @override
  String get enableGlowEffect => 'グローエフェクトを有効化';

  @override
  String get enableM3uSync => 'M3U Syncを有効化';

  @override
  String get enableM3uSyncNote1 => 'M3U Syncを使用すると、プレイリストの変更を元のM3Uファイルに反映できます';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return '何か問題があった場合、このプレイリストのバックアップは$playlistsBackupPath にあります';
  }

  @override
  String get enableM3uSyncSubtitle => '拒否した場合、このプレイリストで行われたすべての変更は再起動時に失われます';

  @override
  String get enableMiniplayerParticles => '動くパーティクルを有効化';

  @override
  String get enableParallaxEffect => '視差効果を有効化';

  @override
  String get enablePartyMode => 'パーティモードを有効化';

  @override
  String get enablePartyModeSubtitle => '派手なエッジブリージングエフェクトを適用';

  @override
  String get enablePictureInPicture => 'ピクチャーインピクチャーを有効化';

  @override
  String get enableReordering => '並べ替えを有効化';

  @override
  String get enableReturnYoutubeDislike => 'Return Youtube Dislikeを有効化';

  @override
  String get enableSearchCleanup => '検索クリーンアップを有効にする';

  @override
  String get enableSearchCleanupSubtitle => 'すべての記号とスペースは無視されます';

  @override
  String get enableSponsorblock => 'SponsorBlockを有効化';

  @override
  String get enableVideoPlayback => '動画再生を有効化';

  @override
  String get enterSymbol => '記号を入力してください';

  @override
  String get equalizer => 'イコライザー';

  @override
  String get error => 'エラー';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'トラックの再生中にエラーが発生しました';

  @override
  String get excludedFodlers => '除外するフォルダ';

  @override
  String get exit => '終了';

  @override
  String get exitAppSubtitle => 'もう一度タップすると終了します';

  @override
  String get expandedMiniplayer => '拡張ミニプレーヤー';

  @override
  String get exportAsM3u => 'M3Uとしてエクスポート';

  @override
  String get extension => '拡大';

  @override
  String get externalFiles => '外部ファイル';

  @override
  String get extract => '抽出';

  @override
  String get extractAllColorPalettes => 'すべてのカラーパレットを抽出';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '残りの$numberStringを抽出しますか?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'タイトルからfeat. アーティストを抽出';

  @override
  String get extractFeatArtistSubtitle => 'タイトル上の (feat. X) および (ft. X) を新しいアーティスト エントリとして抽出します。';

  @override
  String get extractingInfo => '情報の抽出';

  @override
  String get extras => '追加機能';

  @override
  String get extrasSubtitle => '体験を向上するための追加設定';

  @override
  String get extreme => 'エクストリーム';

  @override
  String get failed => '失敗';

  @override
  String get failedEdits => '編集失敗';

  @override
  String get favourites => 'お気に入り';

  @override
  String get features => '機能';

  @override
  String get fetching => '抽出中';

  @override
  String get fetchingOfAllVideos => 'すべての動画を取得';

  @override
  String get file => 'ファイル';

  @override
  String get fileAlreadyExists => 'ファイルが既に存在します';

  @override
  String get fileBasedServerWarning => 'インデックス作成のため、ファイルを一時的にダウンロードします。接続が安定していることを確認してください。\nデータ使用量の増大を避けるため、Wi-Fi の使用を推奨します。';

  @override
  String get fileName => 'ファイル名';

  @override
  String get fileNameWoExt => '拡張子なしのファイル名';

  @override
  String get filenameShouldntStartWith => 'ファイル名は以下で始まってはいけません';

  @override
  String get files => 'ファイル';

  @override
  String get filler => 'フィラー';

  @override
  String get filterAlbums => 'アルバムをフィルター';

  @override
  String get filterArtists => 'アーティストをフィルター';

  @override
  String get filterGenres => 'ジャンルをフィルター';

  @override
  String get filterPlaylists => 'プレイリストをフィルター';

  @override
  String get filterTracks => 'トラックをフィルター';

  @override
  String get filterTracksBy => '検索リストのトラックをフィルター';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'サイズと長さでフィルタリングされたトラック';

  @override
  String get finished => '完了しました';

  @override
  String get finishedUpdatingLibrary => 'ライブラリの更新が完了しました';

  @override
  String get firstListen => '初めて聞いた';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp の大きなサムネイルサイズを修正';

  @override
  String get floatingActionButton => 'フローティングアクションボタン';

  @override
  String get folder => 'フォルダ';

  @override
  String get folderName => 'フォルダ名';

  @override
  String get folders => 'フォルダ';

  @override
  String get fontScale => 'フォントの大きさ';

  @override
  String get forceMiniplayerFollowTrackColors => 'ミニプレーヤーをトラックの色に合わせる';

  @override
  String get forceSquaredAlbumThumbnail => 'アルバムのサムネイルを正方形に強制する';

  @override
  String get forceSquaredThumbnailNote => 'サムネイルのサイズはアルバムタイルの高さと等しくないため、強制的に正方形にすると、期待どおりの効果が得られない可能性があります。同じサイズにしますか?';

  @override
  String get forceSquaredTrackThumbnail => 'トラックのサムネイルを正方形に強制する';

  @override
  String get forceStopColorPaletteGeneration => 'カラーパレットの抽出を強制的に停止しますか? 後で続行できます';

  @override
  String get format => 'フォーマット';

  @override
  String get fullscreen => '全画面表示';

  @override
  String get gaplessPlayback => 'シームレス再生';

  @override
  String get generate => '生成';

  @override
  String get generateFromDates => '時間制限';

  @override
  String get generateFromDatesSubtitle => '特定の時間範囲内で聴いたトラックを生成する';

  @override
  String get generateRandomPlaylist => 'ランダムプレイリストを作成';

  @override
  String get genre => 'ジャンル';

  @override
  String get genres => 'ジャンル';

  @override
  String get goToAlbum => 'アルバムに移動';

  @override
  String get goToArtist => 'アーティストに移動';

  @override
  String get goToChannel => 'チャンネルに移動';

  @override
  String get goToFolder => 'フォルダに移動';

  @override
  String get goodLooking => 'いいね';

  @override
  String get grantStoragePermission => 'ストレージの権限を付与する';

  @override
  String get group => 'グループ';

  @override
  String get groupArtworksByAlbum => 'アルバム別にアートワークをグループ化';

  @override
  String get guide => 'ガイド';

  @override
  String get hapticFeedback => '触覚フィードバック';

  @override
  String get heightOfAlbumTile => 'アルバムタイルの高さ';

  @override
  String get heightOfTrackTile => 'トラックタイルの高さ';

  @override
  String get hideSkipButtonAfter => 'スキップボタンの表示時間';

  @override
  String get highMatches => '高い一致';

  @override
  String get highPerformance => '高パフォーマンス';

  @override
  String get highlight => 'ハイライト';

  @override
  String get history => '履歴';

  @override
  String get historyImportMissingEntriesNote => 'これらのアイテムはライブラリで見つかりませんでした。もし存在する場合は、手動で追加してみてください';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString 件聞いています。$oldTrackInfo は$newTrackInfo に置き換えられます。よろしいですか?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'ホーム';

  @override
  String get hook => 'フック';

  @override
  String get host => 'ホスト';

  @override
  String get hourFormat12 => '12時間表示';

  @override
  String get hours => '時間';

  @override
  String get iReadAndAgree => '読み、合意します';

  @override
  String get ifNotPlaying => '停止中なら';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'システムの省電力機能にアプリが制限されていると、ダウンロード速度が遅くなる場合があります';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'ソート時に基本的な接頭詞を無視する';

  @override
  String get ignores => '無視する';

  @override
  String get imageSource => '画像のソース';

  @override
  String get immersiveMode => '没入モード';

  @override
  String get immersiveModeSubtitle => 'ミニプレーヤーが展開されている間はステータスバーとナビゲーションバーを非表示にする';

  @override
  String get import => 'インポート';

  @override
  String get importAll => '全てインポート';

  @override
  String get importLastFmHistory => 'LastFmの履歴をインポート';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. $lastfmCsvLink に移動します\n\n2. ユーザー名を入力し、csv ファイルを取得してダウンロードします。\n\n3. 次の画面からファイルを選択します。';
  }

  @override
  String get importTimeRange => 'インポート時間範囲';

  @override
  String get importYoutubeHistory => 'YouTubeの履歴をインポート';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. $takeoutLink に移動します。\n\n2. 「複数の形式」を押して、「履歴」の横にある「JSON」を選択します。\n\n3. 「すべての YouTube データを含む」を押して、すべて選択を解除し、履歴のみを選択します。\n\n4. エクスポート、ダウンロード、解凍を作成します。\n\n5. 次の画面から「watch-history.json」を選択します。';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString 個のチャンネルを正常にインポートしました',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText 個のプレイリストを正常にインポートしました',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => '動画を含める';

  @override
  String get indexRefreshRequired => 'このオプションを変更した後に更新が必要です';

  @override
  String get indexer => '索引作成';

  @override
  String get indexerNote => '注: アートワークの数が不完全です。重複または欠落したアートワークが存在します';

  @override
  String get indexerSubtitle => '音楽ライブラリを管理';

  @override
  String get infinityQueueOnNextPrev => '次/前の無限キュー';

  @override
  String get infinityQueueOnNextPrevSubtitle => '最後の項目を再生中に次へを押すと、最初の項目にジャンプします。その逆も同様です';

  @override
  String get info => '情報';

  @override
  String get inserted => '挿入済';

  @override
  String get instantlyApplies => 'すぐに適用';

  @override
  String get interactionReminder => '視聴者への催促';

  @override
  String get intro => 'イントロ (OP)';

  @override
  String get invertSelection => '選択を反転';

  @override
  String get issues => '問題';

  @override
  String get item => 'アイテム';

  @override
  String get jump => 'ジャンプ';

  @override
  String get jumpToDay => '日付にジャンプ';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'キュー終了後に最初のトラックにジャンプ';

  @override
  String get keepCachedVersions => 'キャッシュされたバージョンを保持する';

  @override
  String get keepFileDates => 'ファイルの日付を保持する';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'ミニプレーヤーの展開時';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'ミニプレーヤーが展開され、動画が再生中の場合';

  @override
  String get keepScreenAwakeNone => '画面をオンにしたままにしない';

  @override
  String get keepScreenAwakeWhen => '画面をオンにしたままにする';

  @override
  String get killPlayerAfterDismissingApp => 'アプリを終了した後にプレーヤーを強制終了する';

  @override
  String get language => '言語';

  @override
  String get learnMore => '詳細を確認';

  @override
  String get leftAction => '左スワイプ';

  @override
  String get legacyAuthentication => '古い認証方式';

  @override
  String get libraryTabs => 'ライブラリタブ';

  @override
  String get libraryTabsReorder => 'アクティブ化されたタブを並べ替えられます。';

  @override
  String get license => 'ライセンス';

  @override
  String get licenseSubtitle => 'Namida が使用するライセンスと契約';

  @override
  String get like => '好き';

  @override
  String get liked => '好き';

  @override
  String get link => 'リンク';

  @override
  String get listOfFolders => 'フォルダのリスト';

  @override
  String get loadAll => 'すべて読み込む';

  @override
  String get loadingFile => 'ファイルを読み込み中';

  @override
  String get local => 'ローカル';

  @override
  String get localVideoMatching => 'ローカルの動画を検索';

  @override
  String get login => 'ログイン';

  @override
  String get longPressAction => '長押しアクション';

  @override
  String get longPressTheLyricsToEnterFullscreen => '歌詞を長押しすると全画面になります';

  @override
  String get lostMemories => 'しばらく聞いていない';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString年前の今頃',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'ボリュームブースター';

  @override
  String get lyricist => '作詞';

  @override
  String get lyrics => '歌詞';

  @override
  String get lyricsSource => '歌詞ソース';

  @override
  String get m3uPlaylist => 'M3U プレイリスト';

  @override
  String get makeYourFirstListen => 'まずは聞いてみてください！';

  @override
  String get manage => '管理';

  @override
  String get manageYourAccounts => 'アカウントを管理';

  @override
  String get manualBackup => 'マニュアル';

  @override
  String get manualBackupSubtitle => '特定のファイルを選択';

  @override
  String get markAsRead => '既読にする';

  @override
  String get matchAllTracks => '全てのトラックに一致';

  @override
  String get matchAllTracksNote => 'ライブラリ内のすべてのトラックをチェックするため、マッチ速度に影響を与える可能性があります';

  @override
  String get matchingType => 'マッチタイプ';

  @override
  String get maxAudioCacheSize => '最大音声キャッシュサイズ';

  @override
  String get maxImageCacheSize => '最大画像キャッシュサイズ';

  @override
  String get maxVideoCacheSize => '最大映像キャッシュサイズ';

  @override
  String get maximum => '最大';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'メディアストアが有効になっている場合、これは効果がありません';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => 'コード';

  @override
  String get membershipCodeSentToEmail => 'コードはあなたのメールに送信されました';

  @override
  String get membershipDidntChange => 'メンバーシップは変更されませんでした';

  @override
  String get membershipEnjoyNew => '新しいメンバーシップをお楽しみください';

  @override
  String get membershipFreeCoupon => '無料クーポン';

  @override
  String get membershipManage => 'メンバーシップを管理';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'このユーザーのサブスクリプションは見つかりませんでした';

  @override
  String get membershipSignInToPatreonAccount => 'パトロンアカウントにログイン';

  @override
  String get membershipUnknown => '不明なメンバーシップ';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return '複数のアカウントを追加するには、 $name1 または $name2 のメンバーシップが必要です';
  }

  @override
  String get merge => 'マージ';

  @override
  String get metadataCache => 'メタデータキャッシュ';

  @override
  String get metadataEditFailed => 'メタデータの編集に失敗しました';

  @override
  String get metadataReadFailed => 'メタデータの読み取りに失敗しました';

  @override
  String get minFileDuration => '最小トラック継続時間';

  @override
  String get minFileSize => '最小ファイルサイズ';

  @override
  String get minTrackDurationToRestoreLastPosition => '最後に再生した位置を復元するための最小トラック継続時間';

  @override
  String get minValueCantBeMoreThanMax => '最小値は最大値を超えることはできません';

  @override
  String get minValueToCountTrackListen => '再生回数にカウントされる長さ: ';

  @override
  String get minimizedMiniplayer => '最小化されたミニプレーヤー';

  @override
  String get minimum => '最小化';

  @override
  String get minimumOneFolderSubtitle => '少なくとも 1 つのフォルダが必要です。このフォルダを削除する場合は、新しいフォルダを追加してください';

  @override
  String get minimumOneItem => 'アイテムを削除できませんでした';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '少なくとも$numberString個のアイテムが残っている必要があります',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'スキップするセグメントの長さの最小時間';

  @override
  String get miniplayerCustomization => 'ミニプレーヤーのカスタマイズ';

  @override
  String get minutes => '分';

  @override
  String get missingEntries => '欠落したエントリ';

  @override
  String get missingTracks => '欠落したトラック';

  @override
  String get mix => 'ミックス';

  @override
  String get mixPlaylistGeneratedByYoutube => 'YouTubeによって生成されたミックスプレイリスト';

  @override
  String get mixes => 'ミックス';

  @override
  String get mobile => 'モバイル';

  @override
  String get month => '月';

  @override
  String get months => '月';

  @override
  String get mood => '雰囲気';

  @override
  String get moods => '雰囲気';

  @override
  String get more => 'もっと';

  @override
  String get mostPlayed => '最も再生された';

  @override
  String get multipleTracksTagsEditNote => 'これらのトラックを編集しようとしています。\n変更されていないフィールドはそのまま残ります。';

  @override
  String get musicOfftopic => '音楽ではない区間';

  @override
  String get name => '名前';

  @override
  String get nameContainsBadCharacter => '名前に不適切な文字が含まれています';

  @override
  String get never => 'しない';

  @override
  String get newDirectory => '新しいディレクトリ';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'トラックを追加';

  @override
  String get newTracksMoods => '雰囲気';

  @override
  String get newTracksMoodsSubtitle => '既存の雰囲気に基づいてトラックを生成する';

  @override
  String get newTracksRandom => 'ランダム';

  @override
  String get newTracksRandomSubtitle => 'ライブラリからランダムにトラックを選択する';

  @override
  String get newTracksRatings => '評価';

  @override
  String get newTracksRatingsSubtitle => '特定の評価のトラックを生成する';

  @override
  String get newTracksRecommended => 'おすすめされた';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return '$currentTrackで普段聴いているトラックを生成します';
  }

  @override
  String get newTracksSimilarrReleaseDate => '同様のリリース日';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return '$currentTrackと同時期にリリースされたトラックを生成します';
  }

  @override
  String get newTracksUnknownYear => 'トラックの年は不明です';

  @override
  String get newest => '最新';

  @override
  String get next => '次へ';

  @override
  String get no => 'いいえ';

  @override
  String get noChangesFound => '変更は見つかりませんでした。';

  @override
  String get noEnoughTracks => 'トラックがあまりありません。';

  @override
  String get noExcludedFolders => '除外フォルダはありません';

  @override
  String get noFolderChosen => 'フォルダが選択されていません';

  @override
  String get noMoodsAvailable => '利用可能な雰囲気はありません';

  @override
  String get noNetworkAvailableToFetchData => 'インターネット接続がありません';

  @override
  String get noTracksFound => 'トラックは見つかりませんでした';

  @override
  String get noTracksFoundBetweenDates => 'この時間範囲にはトラックがありません。';

  @override
  String get noTracksFoundInDirectory => 'このディレクトリにトラックが見つかりません';

  @override
  String get noTracksInHistory => '履歴に十分なトラックがありません';

  @override
  String get nonActive => '無効';

  @override
  String get nonFavourites => 'お気に入りではない';

  @override
  String get none => 'なし';

  @override
  String get normalizeAudio => 'オーディオを正規化';

  @override
  String get normalizeAudioSubtitle => 'ReplayGainタグまたは YouTube が提供する情報を読み取り、音量を正規化します';

  @override
  String get notAvailableForYourDevice => 'このデバイスでは利用できません';

  @override
  String get notSupportedForNetworkFiles => 'ネットワークファイルはサポートされていません';

  @override
  String get note => 'ノート';

  @override
  String get notification => '通知';

  @override
  String get notifications => '通知';

  @override
  String get numberOfTracks => 'トラック数';

  @override
  String get ofLabel => 'の';

  @override
  String get offlineSearch => 'オフライン検索';

  @override
  String get offset => 'オフセット';

  @override
  String get oldDirectory => '古いディレクトリ';

  @override
  String get oldDirectoryStillHasTracks => '古いフォルダにはまだいくつかのトラックが残っていますが、よろしいですか?';

  @override
  String get oldestWatch => '一番昔に見た';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => '中断時';

  @override
  String get onNotificationTap => '通知タップ時';

  @override
  String get onOpeningYoutubeLink => 'YouTubeのリンクを開いた時';

  @override
  String get onSwiping => 'スワイプ時';

  @override
  String get onVolumeZero => '音量0の時';

  @override
  String get ongoing => '進行中';

  @override
  String get open => '開く';

  @override
  String get openApp => 'アプリを開く';

  @override
  String get openInFileExplorer => 'ファイルエクスプローラーで開く';

  @override
  String get openInYoutubeView => 'YouTubeで開く';

  @override
  String get openMiniplayer => 'ミニプレーヤーを開く';

  @override
  String get openQueue => 'キューを開く';

  @override
  String get openYoutubeLink => 'YouTubeリンクを開く';

  @override
  String operationRequiresAccount({required String name}) {
    return '$name を実行するにはアカウントが必要です。続行するにはサインインしてください';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return '$operation には少なくともメンバーシップ $name への参加が必要です';
  }

  @override
  String get or => 'または';

  @override
  String get others => 'その他';

  @override
  String get output => 'アウトプット';

  @override
  String get outro => 'アウトロ (ED)';

  @override
  String get overrideOldFilesInTheSameFolder => '同じフォルダ内の古いファイルを上書きする';

  @override
  String get palette => 'パレット';

  @override
  String get paletteMix => 'ミックス';

  @override
  String get paletteNewMix => '新しいミックス';

  @override
  String get paletteSelectedMix => '選択されたミックス';

  @override
  String get parallelDownloads => '複数ダウンロード';

  @override
  String get parsed => '解析済';

  @override
  String get password => 'パスワード';

  @override
  String get path => 'ファイルのフルパス';

  @override
  String get pause => '一時停止';

  @override
  String get pauseFadeDuration => '一時停止時のフェードの長さ';

  @override
  String get pausePlayback => '再生を一時停止';

  @override
  String get percentage => 'パーセンテージ';

  @override
  String get performanceMode => 'パフォーマンスモード';

  @override
  String get performanceNote => 'パフォーマンスに影響する可能性があります';

  @override
  String get personalized => 'カスタム';

  @override
  String get personalizedRelatedVideos => 'あなた向けの関連動画';

  @override
  String get personalizedRelatedVideosSubtitle => 'これを無効にするとデータ使用量が増加します';

  @override
  String get pickColorsFromDeviceWallpaper => 'デバイスの壁紙から色を選択する';

  @override
  String get pickFromStorage => 'ストレージから選択';

  @override
  String get pinned => 'ピン留め';

  @override
  String get pitch => 'ピッチ';

  @override
  String get plain => 'プレーンテキスト';

  @override
  String get play => '再生';

  @override
  String get playAfter => '後で再生';

  @override
  String get playAfterNextPrev => '次/前の自動再生';

  @override
  String get playAll => '全て再生';

  @override
  String get playFadeDuration => '再生時のフェードの長さ';

  @override
  String get playLast => '最後に再生';

  @override
  String get playNext => '次に再生';

  @override
  String get playbackSetting => '再生';

  @override
  String get playbackSettingSubtitle => 'オーディオボタンを長押しすると、プレーヤーで直接アクセスできます';

  @override
  String get playlist => 'プレイリスト';

  @override
  String get playlists => 'プレイリスト';

  @override
  String get playlistsImportM3uNative => 'namida でのみ使用可能なM3Uプレイリストをインポートする。移行時に使用できます';

  @override
  String get playlistsImportM3uSynced => 'インデックスフォルダからM3Uプレイリストを自動的にインポートし、元のM3Uファイルと同期したままにします。他のアプリでプレイリストにアクセスまたは編集する場合は、有効にしてください';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'M3Uプレイリストを自動インポート';

  @override
  String get pleaseEnterADifferentName => 'この名前はすでに存在します :(\n別の素敵な名前を試してください';

  @override
  String get pleaseEnterALink => 'リンクを入力してください';

  @override
  String get pleaseEnterALinkSubtitle => 'ええっと…これはYouTubeのリンクですか？';

  @override
  String get pleaseEnterAName => '名前を入力してください';

  @override
  String get port => 'ポート';

  @override
  String get preventDuplicatedTracks => 'トラックの重複防止';

  @override
  String get preventDuplicatedTracksSubtitle => 'ファイル名を使用してトラックを一意に識別します';

  @override
  String get preview => 'プレビュー';

  @override
  String get previous => '前';

  @override
  String get previousButtonReplays => 'プレビューボタンでリプレイ';

  @override
  String get previousButtonReplaysSubtitle => '現在位置がシーク時間以上あるときに押された場合';

  @override
  String get prioritizeEmbeddedLyrics => '埋め込まれた歌詞を優先する';

  @override
  String get priority => '優先度';

  @override
  String get private => 'プライベート';

  @override
  String get progress => '進捗';

  @override
  String get promptToChangeTrackPath => '通常、これは namida の外部でファイルを削除/移動/名前変更したときに発生します。現在のパスを更新しますか?';

  @override
  String get public => '公開';

  @override
  String get queue => 'キュー';

  @override
  String get queues => 'キュー';

  @override
  String get random => 'ランダム';

  @override
  String get randomPicks => 'ランダム選択';

  @override
  String get rating => '評価';

  @override
  String get reIndex => '再インデックス';

  @override
  String get reIndexSubtitle => '音楽ライブラリを再構築する';

  @override
  String get reIndexWarning => 'このプロセスは、ライブラリのサイズに応じて、しばらく時間がかかる場合があります。\n\nアートワークは、存在する限り再インデックスされません';

  @override
  String get recentAlbums => '最近のアルバム';

  @override
  String get recentArtists => '最近のアーティスト';

  @override
  String get recentListens => '最近聞いた';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => '最近追加された';

  @override
  String get recordLabel => 'レコード会社';

  @override
  String get refresh => '更新';

  @override
  String get refreshLibrary => 'ライブラリを更新';

  @override
  String get refreshLibrarySubtitle => '新しく追加された音楽や削除された音楽を確認';

  @override
  String get refreshOnStartup => '開始時に更新';

  @override
  String get relatedVideos => '関連動画';

  @override
  String get rememberAudioOnlyMode => '音声のみモードを記憶';

  @override
  String get remixer => 'リミキサー';

  @override
  String get remove => '削除';

  @override
  String get removeDuplicates => '重複を削除';

  @override
  String get removeFromFavourites => 'お気に入りから削除';

  @override
  String get removeFromLibrary => 'ライブラリから削除';

  @override
  String get removeFromPlaylist => 'プレイリストから削除';

  @override
  String get removeQueue => 'キューを削除';

  @override
  String get removeSourceFromHistory => '履歴からソースを削除する';

  @override
  String get removeWhitespaces => '空白を削除';

  @override
  String get removed => '削除済み';

  @override
  String get rename => '名前を変更';

  @override
  String get renamePlaylist => 'プレイリスト名を変更';

  @override
  String get reorderable => '並び替え可能';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number 回繰り返す',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'ループ再生モード';

  @override
  String get repeatModeAll => 'すべてのキューを繰り返す';

  @override
  String get repeatModeNone => '最後のトラックで停止';

  @override
  String get repeatModeOne => '現在のトラックを繰り返す';

  @override
  String get replaceAllListensWithAnotherTrack => 'このトラックのすべての視聴履歴を別のトラックに置き換える';

  @override
  String get replies => '返信';

  @override
  String get reply => '返信';

  @override
  String get requiresClearingImageCacheAndReIndexing => '画像キャッシュのクリアと再インデックスが必要です';

  @override
  String get rescanVideos => '動画を再スキャン';

  @override
  String get resetBrightness => '明るさをリセット';

  @override
  String get resetToDefault => '設定';

  @override
  String get respectNoMedia => '.nomedia を無視する';

  @override
  String get respectNoMediaSubtitle => '.nomedia のあるフォルダを含めない';

  @override
  String get restart => '再起動';

  @override
  String get restoreBackup => 'バックアップを復元';

  @override
  String get restoreDefaults => 'デフォルトに戻す';

  @override
  String get restoredBackupSuccessfully => '復元されたバックアップ';

  @override
  String get restoredBackupSuccessfullySub => 'バックアップファイルが正常に復元されました';

  @override
  String get resume => '再開';

  @override
  String get resumeIfWasInterrupted => '中断により一時停止された場合は再開する';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => '音量によって一時停止された場合は再開する';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '一時停止が $numberString 分未満の場合、再開する',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => '逆順';

  @override
  String get rightAction => '右スワイプ';

  @override
  String get ringtone => '着信音';

  @override
  String get sameDirectoryOnly => '同じディレクトリのみ';

  @override
  String get sample => 'サンプル';

  @override
  String get sampleRate => 'サンプルレート';

  @override
  String get save => '保存';

  @override
  String get saveToLibrary => 'ライブラリに保存';

  @override
  String get savedIn => '保存場所';

  @override
  String get scaleMultiplier => 'スケール乗数';

  @override
  String get search => '検索';

  @override
  String get searchYoutube => 'YouTubeで検索';

  @override
  String get seconds => '秒';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return '$site でプロジェクトのコードを見る';
  }

  @override
  String get seekDuration => 'シーク間隔';

  @override
  String get seekDurationInfo => '現在の時間をタップすると巻き戻し、合計時間をタップすると早送りできます';

  @override
  String get seekbar => 'シークバー';

  @override
  String get selectAll => 'すべて選択';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'ローカルライブラリに既に存在するファイルを選択';

  @override
  String get selectedTracks => '選択されたトラック';

  @override
  String get selfPromotion => '自己宣伝';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'これらの単語は分割されません';

  @override
  String get separatorsMessage => '単語全体に含まれる文字/記号 (x や ft. など) を使用する場合を除き、スペースを挿入する必要はありません';

  @override
  String get serverAddress => 'サーバーアドレス';

  @override
  String get setAs => 'として設定';

  @override
  String get setAsDefault => 'デフォルトとして設定';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'ファイルの最終更新日を動画のアップロード日として設定する';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => '雰囲気を設定';

  @override
  String get setMoodsSubtitle => '区切りにはカンマ（,）を使用してください';

  @override
  String get setRating => '評価を設定';

  @override
  String get setTags => 'タグを設定';

  @override
  String get setYoutubeLink => 'YouTubeリンクを設定';

  @override
  String get settings => '設定';

  @override
  String get setupFirstStartup => '初回起動時のセットアップ';

  @override
  String get share => '共有';

  @override
  String get shareLogs => 'ログを共有';

  @override
  String get shortcuts => 'ショートカット';

  @override
  String get shouldDuck => '音量を下げるべきです';

  @override
  String get shouldDuckNote => '音量を下げる必要があることを示します。例: 通知';

  @override
  String get shouldPause => '一時停止すべき';

  @override
  String get shouldPauseNote => '再生を一時停止することを示します。例: 通話';

  @override
  String get showAll => 'すべて表示';

  @override
  String get showChannelWatermarkInFullscreen => '全画面時にチャンネルのウォーターマークを表示する';

  @override
  String get showFailedOnly => '失敗のみ表示';

  @override
  String get showHideUnknownFields => '不明なフィールドの表示/非表示';

  @override
  String get showInSeekbar => 'シークバーに表示';

  @override
  String get showMixPlaylistsIn => 'ミックスを表示する';

  @override
  String get showMore => 'もっと見る';

  @override
  String get showShortVideosIn => 'ショート動画を表示する';

  @override
  String get showSkipButton => 'スキップボタンを表示';

  @override
  String get showVideoEndcards => '動画のエンドカードを表示';

  @override
  String get showWebm => 'webm を見る';

  @override
  String get shuffle => 'シャッフル';

  @override
  String get shuffleAll => 'すべてシャッフル';

  @override
  String get shuffleNext => '次をシャッフル';

  @override
  String get signIn => 'サインイン';

  @override
  String get signInCanceled => 'サインインはキャンセルされました';

  @override
  String get signInFailed => 'サインイン失敗';

  @override
  String get signInToYourAccount => 'アカウントにサインイン';

  @override
  String get signInYouDontHaveAccount => 'サインインしているアカウントはありません';

  @override
  String get signInYouNeedAccountToViewPage => 'このページを表示するにはアカウントが必要です';

  @override
  String get signOut => 'ログアウト';

  @override
  String signOutFromName({required String name}) {
    return '$name からログアウト';
  }

  @override
  String get signingInAllowsBasicUsage => 'サインインすると基本的な機能が使用可能になります';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Patreon またはクーポンを使用し早期アクセスを入手';

  @override
  String get similarDiscoverDate => '類似の発見日';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return '$currentTrack とほぼ同時期に発見されたトラックを生成';
  }

  @override
  String get similarTimeRange => '類似の時間範囲';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return '$currentTrack と同時期に聴いたトラックを生成';
  }

  @override
  String get singles => 'シングル';

  @override
  String get size => 'サイズ';

  @override
  String get skip => 'スキップ';

  @override
  String get skipCountTracking => 'スキップ回数トラッキング';

  @override
  String get skipSilence => '無音をスキップ';

  @override
  String get skipSponsorSegmentsInVideos => '動画内のスポンサーセグメントをスキップする機能です';

  @override
  String get sleepAfter => '後で一時停止';

  @override
  String get sleepTimer => 'スリープタイマー';

  @override
  String get socials => 'ソーシャルリンク';

  @override
  String get socialsSubtitle => 'いずれかのプラットフォームに参加して最新情報、ヒント、アイデアなどについて議論できます';

  @override
  String get someWebServersRequireAuthentication => '一部のウェブサーバーでは認証が必要です。ライブラリへアクセスするには、認証情報を更新してください。';

  @override
  String get sortBy => '並べ替え';

  @override
  String get source => 'ソース';

  @override
  String get speed => '速度';

  @override
  String get sponsor => 'スポンサー (広告)';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock リーダーボード';

  @override
  String get staggeredAlbumGridView => 'アルバムグリッドビュー';

  @override
  String get start => '開始';

  @override
  String get stats => '統計';

  @override
  String get statsSubtitle => 'ライブラリに関する情報はこちら';

  @override
  String get stop => '停止';

  @override
  String get stopAfterThisTrack => 'このトラックの後に停止';

  @override
  String get stopAfterThisVideo => 'この動画の後に停止';

  @override
  String get storagePermissionDenied => '許可が拒否されました';

  @override
  String get storagePermissionDeniedSubtitle => 'この操作を実行するにはアクセスを許可してください';

  @override
  String get stretchLyricsDuration => '同期歌詞を長さに合わせて引き伸ばす';

  @override
  String get subdirectory => 'サブディレクトリ';

  @override
  String get subscribe => '登録';

  @override
  String get subscribed => '登録済み';

  @override
  String get subscriber => '登録者';

  @override
  String get subscribers => '登録者';

  @override
  String get succeeded => '成功しました';

  @override
  String suggestionSubtitle({required String site}) {
    return '問題や提案がありますか？ $site でIssueを開いてください';
  }

  @override
  String get support => 'サポート';

  @override
  String get supremacy => '覇権';

  @override
  String get sussyBaka => 'うーん、トラックがありません';

  @override
  String get swipeActions => 'スワイプアクション';

  @override
  String get swipeToOpenDrawer => 'ドロワーを開くにはスワイプします';

  @override
  String get synced => '同期済み';

  @override
  String get synopsis => '概要';

  @override
  String get tagFields => 'タグフィールド';

  @override
  String get tags => 'タグ';

  @override
  String get tapAction => 'タップアクション';

  @override
  String get tapToSeek => 'タップして巻き戻し';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'テーマモード';

  @override
  String get themeModeDark => 'ダーク';

  @override
  String get themeModeLight => 'ライト';

  @override
  String get themeModeSystem => 'システム';

  @override
  String get themeSettings => 'テーマ';

  @override
  String get themeSettingsSubtitle => 'プレーヤーの全体的な雰囲気';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'このプレイリストには有効になっているソートがあります。並べ替える前に無効にしてください。';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'このビデオは削除されたか、非公開に設定されている可能性があります。';

  @override
  String get thumbnails => 'サムネイル';

  @override
  String get title => 'タイトル';

  @override
  String get top => '上';

  @override
  String get topComments => '人気のコメント';

  @override
  String get topCommentsSubtitle => 'コメントを下ではなく上に表示する';

  @override
  String get topRecentAlbums => '最近のトップアルバム';

  @override
  String get topRecentArtists => '最近のトップアーティスト';

  @override
  String get topRecents => '最近のトップ';

  @override
  String get totalListenTime => '総再生時間';

  @override
  String get totalListens => '総再生数';

  @override
  String get totalTracks => '総トラック数';

  @override
  String get totalTracksDuration => '総トラック時間';

  @override
  String get track => 'トラック';

  @override
  String get trackArtistsSeparator => 'アーティストの区切り文字';

  @override
  String get trackGenresSeparator => 'ジャンルの区切り文字';

  @override
  String get trackInfo => 'トラックの情報';

  @override
  String get trackNotFound => 'トラックが見つかりません';

  @override
  String get trackNumber => 'トラック番号';

  @override
  String get trackNumberTotal => '総トラック数';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return '古い名前: 「$oldName」\n\n新しい名前: 「$newName」\n\nよろしいですか?';
  }

  @override
  String get trackPlayMode => '再生モード';

  @override
  String get trackPlayModeSearchResults => '検索結果';

  @override
  String get trackPlayModeSelectedOnly => '選択したトラックのみ';

  @override
  String get trackPlayModeTrackAlbum => 'トラックのアルバム';

  @override
  String get trackPlayModeTrackArtist => 'トラックのメインアーティスト';

  @override
  String get trackPlayModeTrackGenre => 'トラックのジャンル';

  @override
  String get trackThumbnailSizeInList => 'トラックのサムネイルサイズ';

  @override
  String get trackTileCustomization => 'トラックタイルのカスタマイズ';

  @override
  String get trackTileItemsSeparator => 'アイテムの区切り文字';

  @override
  String get tracks => 'トラック';

  @override
  String get tracksExcludedByNomedia => '.nomedia によって除外されたトラック';

  @override
  String get tracksInfo => 'トラックの情報';

  @override
  String get underrated => '過小評価された';

  @override
  String get undo => '元に戻す';

  @override
  String get undoChanges => '変更を元に戻しますか？';

  @override
  String get undoChangesDeletedPlaylist => 'プレイリストの削除を元に戻しました';

  @override
  String get undoChangesDeletedQueue => 'キューの削除を元に戻しました';

  @override
  String get undoChangesDeletedTrack => 'トラックの削除を元に戻しました';

  @override
  String get uniqueArtworkHash => 'ユニークアートワークハッシュ';

  @override
  String get unlimited => '無制限';

  @override
  String get unlisted => '非公開';

  @override
  String get unlock => 'アンロック';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'アップデート';

  @override
  String get updateDirectoryPath => 'ディレクトリパスをアップデート';

  @override
  String get updateMissingTracksOnly => '不足しているトラックのみ更新';

  @override
  String get updating => 'アップデート中';

  @override
  String get useCollapsedSettingTiles => '折りたたみ設定タイルを使用する';

  @override
  String get useMediaStore => 'メディアストアを使用する';

  @override
  String get useMediaStoreSubtitle => '✓ インデックス作成時間が即時に完了\nx .nomedia が強制的に有効化されます\nx 一部のメタデータ タグが欠落します\nx ローカル ライブラリの YouTube 統合は機能しません';

  @override
  String get usePitchBlack => '真っ黒にする';

  @override
  String get usePitchBlackSubtitle => 'AMOLED スクリーンで動作し、見た目もクールです';

  @override
  String get used => '使用済み';

  @override
  String get value => '値';

  @override
  String get valueBetween50200 => '値は50%から200%の間でなければなりません';

  @override
  String get vibration => '振動';

  @override
  String get vibrationType => '振動のタイプ';

  @override
  String get video => '動画';

  @override
  String get videoCache => '映像キャッシュ';

  @override
  String get videoCacheFile => 'キャッシュされた映像ファイル';

  @override
  String get videoCacheFiles => 'キャッシュされた映像ファイル';

  @override
  String get videoOnly => '動画のみ';

  @override
  String get videoPlaybackSource => '動画のソース';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'これにより、ローカル内の動画が優先され、見つからない場合は YouTube から取得されます';

  @override
  String get videoPlaybackSourceLocal => 'ローカルの動画';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nビデオ Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => '選択したフォルダリスト内にある動画ファイルの名前に、トラックのファイル名が含まれているかどうかを確認する';

  @override
  String get videoPlaybackSourceYoutube => 'YouTubeから';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => 'トラックのファイル名とコメントをチェックして、一致する YouTube リンクがないか確認します。動画は後で使用するためにキャッシュされます。';

  @override
  String get videoQuality => '動画の画質';

  @override
  String get videoQualitySubtitle => '最高品質のものが選択されます。';

  @override
  String get videoQualitySubtitleNote => '品質が見つからない場合に備えて、複数の代替案を用意しておくことをお勧めします。そうしないと、最悪の品質に戻ってしまいます';

  @override
  String get videos => '動画';

  @override
  String get view => '見る';

  @override
  String get viewAll => 'すべて見る';

  @override
  String get views => '回再生';

  @override
  String get volume => '音量';

  @override
  String get warning => '警告';

  @override
  String get waveformBarsCount => '波形バー数';

  @override
  String get webmNoEditTagsSupport => 'WEBM形式はタグ編集をサポートしていません';

  @override
  String get week => '週';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => '年';

  @override
  String get yes => 'はい';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return '現在のメンバーシップは$nameです';
  }

  @override
  String get yourCustomOrderWillBeLost => '変更点は失われます。よろしいですか?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'YouTubeの体験をカスタマイズする';

  @override
  String get youtubeStyleMiniplayer => 'YouTubeスタイルのミニプレーヤー';

  @override
  String get ytPreferNewComments => '可能な限り新しいコメントを優先する';

  @override
  String get ytPreferNewCommentsSubtitle => 'キャッシュバージョンは接続がない場合にのみ使用されます';
}
