// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Slovenian (`sl`).
class AppLocalizationsSl extends AppLocalizations {
  AppLocalizationsSl([String locale = 'sl']) : super(locale);

  @override
  String get about => 'O aplikaciji';

  @override
  String get active => 'Aktivno';

  @override
  String get add => 'Dodaj';

  @override
  String get addAccount => 'Dodaj račun';

  @override
  String get addAll => 'Dodaj vse';

  @override
  String get addAllAndRemoveOldOnes => 'Dodaj vse in odstrani stare';

  @override
  String get addAsANewPlaylist => 'Dodaj kot nov seznam predvajanja';

  @override
  String get addAudioToLocalLibrary => 'Dodaj zvok v lokalno knjižnico';

  @override
  String get addFolder => 'Dodaj mapo';

  @override
  String get addLanguage => 'Dodaj jezik';

  @override
  String get addLanguageSubtitle => 'Pomagajte prevesti Namido v vaš jezik';

  @override
  String get addLrcFile => 'Dodaj datoteko LRC';

  @override
  String get addMoreFromThisAlbum => 'Dodaj več s tega albuma v čakalno vrsto';

  @override
  String get addMoreFromThisArtist => 'Dodaj več od tega izvajalca v čakalno vrsto';

  @override
  String get addMoreFromThisFolder => 'Dodaj več iz te mape v čakalno vrsto';

  @override
  String addMoreFromToQueue({required String media}) {
    return 'Dodaj več iz $media v čakalno vrsto';
  }

  @override
  String get addOnlyMissing => 'Dodaj samo manjkajoče';

  @override
  String get addToFavourites => 'Dodaj med priljubljene';

  @override
  String get addToPlaylist => 'Dodaj na seznam predvajanja';

  @override
  String get addTracksAtTheBeginning => 'Dodaj skladbe na začetek';

  @override
  String get added => 'dodano';

  @override
  String get advanced => 'Napredno';

  @override
  String get advancedSettings => 'Napredno';

  @override
  String get advancedSettingsSubtitle => 'Napredne nastavitve, ne dotikajte se';

  @override
  String get alarm => 'Alarm';

  @override
  String get album => 'Album';

  @override
  String get albumArtist => 'Izvajalec albuma';

  @override
  String get albumArtists => 'Izvajalci albuma';

  @override
  String get albumIdentifiers => 'Identifikatorji albuma';

  @override
  String get albumThumbnailSizeInList => 'Velikost sličice albuma';

  @override
  String get albumTileCustomization => 'Prilagajanje ploščice albuma';

  @override
  String get albums => 'Albumi';

  @override
  String get albumsCount => 'Število albumov';

  @override
  String get all => 'Vse';

  @override
  String get allTime => 'Vse obdobje';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => 'Vedno';

  @override
  String get alwaysAsk => 'Vedno vprašaj';

  @override
  String get alwaysDim => 'Vedno zatemni';

  @override
  String get alwaysExpandedSearchbar => 'Vedno razširjena iskalna vrstica';

  @override
  String get alwaysRestore => 'Vedno obnovi';

  @override
  String get animatingThumbnailIntensity => 'Intenzivnost animacije sličice';

  @override
  String get animatingThumbnailInversed => 'Obrnjene animacije';

  @override
  String get animatingThumbnailInversedSubtitle => 'Visoki toni bodo pomanjšali sličico';

  @override
  String get anotherProcessIsRunning => 'Drug proces se že izvaja.';

  @override
  String get appIcon => 'Ikona aplikacije';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => 'Izvajalec';

  @override
  String get artists => 'Izvajalci';

  @override
  String get artwork => 'Slika albuma';

  @override
  String get artworkGestures => 'Geste na sliki albuma';

  @override
  String get artworks => 'Slike albumov';

  @override
  String get audio => 'Zvok';

  @override
  String get audioCache => 'Predpomnilnik zvoka';

  @override
  String get audioOnly => 'Samo zvok';

  @override
  String get auto => 'Samodejno';

  @override
  String get autoBackupInterval => 'Interval samodejnega varnostnega kopiranja';

  @override
  String get autoColoring => 'Samodejno barvanje';

  @override
  String get autoColoringSubtitle => 'Samodejno izberi barve predvajalnika iz trenutne slike albuma';

  @override
  String get autoExtractTagsFromFilename => 'Samodejno izlušči iz imena datoteke';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => 'Samodejno izlušči naslov in izvajalca iz naslova videa';

  @override
  String get autoGenerated => 'Samodejno ustvarjeno';

  @override
  String get autoSkip => 'Samodejni preskok';

  @override
  String get autoSkipOnce => 'Samodejno preskoči enkrat';

  @override
  String get autoStartRadio => 'Samodejni zagon radia';

  @override
  String get autoStartRadioSubtitle => 'Samodejno doda mešani seznam predvajanja pri predvajanju posamezne skladbe';

  @override
  String get automaticBackup => 'Samodejno';

  @override
  String get automaticBackupSubtitle => 'Samodejno uporabi najnovejšo varnostno kopijo, najdeno na lokaciji';

  @override
  String get backupAndRestore => 'Varnostno kopiranje in obnovitev';

  @override
  String get backupAndRestoreSubtitle => 'Varnostno kopirajte bazo podatkov in nastavitve';

  @override
  String get balanced => 'Uravnoteženo';

  @override
  String get beta => 'Beta';

  @override
  String get betweenDates => 'Med datumi';

  @override
  String get bitrate => 'Bitna hitrost';

  @override
  String get blacklist => 'Črni seznam';

  @override
  String get borderRadiusMultiplier => 'Množitelj zaobljenosti robov';

  @override
  String get cache => 'Predpomnilnik';

  @override
  String get cancel => 'Prekliči';

  @override
  String get canceled => 'Preklicano';

  @override
  String get changed => 'Spremenjeno';

  @override
  String get changelog => 'Dnevnik sprememb';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => 'Kanal';

  @override
  String get channels => 'Kanali';

  @override
  String get check => 'Preveri';

  @override
  String get checkForMore => 'Preveri za več';

  @override
  String get checkList => 'Kontrolni seznam';

  @override
  String get choose => 'Izberi';

  @override
  String get chooseWhatToClear => 'Izberite, kaj želite počistiti';

  @override
  String get claim => 'Zahtevaj';

  @override
  String get clear => 'Počisti';

  @override
  String get clearAudioCache => 'Počisti predpomnilnik zvoka';

  @override
  String get clearImageCache => 'Počisti predpomnilnik slik';

  @override
  String get clearImageCacheWarning => 'Opozorilo: knjižnica bo ostala brez slik. Uporabite le za ponovno izgradnjo predpomnilnika slik.';

  @override
  String get clearTrackItem => 'Počisti za skladbo';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Počisti za $numberString skladb',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => 'Počisti predpomnilnik videa';

  @override
  String get clearVideoCacheNote => 'Izberete lahko, kaj želite izbrisati.';

  @override
  String get clock => 'Ura';

  @override
  String get colorPalette => 'Barvna paleta';

  @override
  String get colorPaletteNote1 => 'Dolgo pritisnite barvo, da jo odstranite';

  @override
  String get colorPaletteNote2 => 'Tapnite na mešanico za uporabo kot privzeto barvo';

  @override
  String get colorPalettes => 'Barvne palete';

  @override
  String get comment => 'Komentar';

  @override
  String get comments => 'Komentarji';

  @override
  String get composer => 'Skladatelj';

  @override
  String get compress => 'Stisni';

  @override
  String get compressImages => 'Stisni slike';

  @override
  String get compressionPercentage => 'Odstotek stiskanja';

  @override
  String get configure => 'Konfiguriraj';

  @override
  String get confirm => 'Potrdi';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get copiedArtwork => 'Kopirana slika albuma';

  @override
  String get copiedToClipboard => 'Kopirano v odložišče';

  @override
  String get copy => 'Kopiraj';

  @override
  String get corruptedFile => 'Datoteke ni mogoče razčleniti, morda je poškodovana';

  @override
  String get couldntOpen => 'Ni bilo mogoče odpreti :(';

  @override
  String get couldntOpenYtLink => 'Za to skladbo ni na voljo Youtube povezave';

  @override
  String get couldntPlayFile => 'Datoteke ni bilo mogoče predvajati';

  @override
  String get couldntRenamePlaylist => 'Seznama predvajanja ni bilo mogoče preimenovati';

  @override
  String get couldntSaveImage => 'Slike ni bilo mogoče shraniti';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => 'Država';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => 'Ustvari';

  @override
  String get createBackup => 'Ustvari varnostno kopijo';

  @override
  String get createNewPlaylist => 'Ustvari nov seznam predvajanja';

  @override
  String get createdBackupSuccessfully => 'Varnostna kopija ustvarjena';

  @override
  String get createdBackupSuccessfullySub => 'Datoteka varnostne kopije je bila uspešno ustvarjena';

  @override
  String get crossPlatformSync => 'Medplatformska sinhronizacija';

  @override
  String get crossfadeDuration => 'Trajanje prelivanja';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Samodejno sproži prelivanje v zadnjih $secondsString sekundah',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => 'Ne sproži samodejnega prelivanja';

  @override
  String get custom => 'Po meri';

  @override
  String get customizations => 'Prilagoditve';

  @override
  String get customizationsSubtitle => 'Prilagodite videz predvajalnika po svojem okusu';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Podatke zagotavlja: $name';
  }

  @override
  String get dataSaver => 'Varčevanje s podatki';

  @override
  String get dataSaverMode => 'Način varčevanja s podatki';

  @override
  String get database => 'Baza podatkov';

  @override
  String get date => 'Datum';

  @override
  String get dateAdded => 'Datum dodajanja';

  @override
  String get dateCreated => 'Datum ustvarjanja';

  @override
  String get dateModified => 'Datum spremembe';

  @override
  String get dateTimeFormat => 'Format datuma in časa';

  @override
  String get day => 'Dan';

  @override
  String get days => 'Dni';

  @override
  String get defaultBackupLocation => 'Privzeta lokacija varnostne kopije';

  @override
  String get defaultColor => 'Privzeta barva';

  @override
  String get defaultColorSubtitle => 'Nastavite barvo, ki jo bo uporabljal predvajalnik';

  @override
  String get defaultDownloadLocation => 'Privzeta lokacija prenosov';

  @override
  String get defaultLabel => 'Privzeto';

  @override
  String get defaultLibraryTab => 'Privzeti zavihek knjižnice';

  @override
  String get delete => 'Izbriši';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Izbriši $countString datoteko/e v skupni velikosti $totalSizeText?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return 'Trajno izbriši $numberText iz shrambe';
  }

  @override
  String get deletePlaylist => 'Izbriši seznam predvajanja';

  @override
  String get deleteTempFiles => 'Izbriši začasne datoteke';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => 'Opis';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => 'Ali ste mislili';

  @override
  String get dimIntensity => 'Intenzivnost zatemnitve';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: 'Zatemni mini predvajalnik po $secondsString sekundah neaktivnosti',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => 'Imenik ne obstaja';

  @override
  String get disable => 'Onemogoči';

  @override
  String get disableAll => 'Onemogoči vse';

  @override
  String get disableReordering => 'Onemogoči spreminjanje vrstnega reda';

  @override
  String get disableSearchCleanup => 'Onemogoči čiščenje iskanja';

  @override
  String get discNumber => 'Številka diska';

  @override
  String get discNumberTotal => 'Skupno diskov';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => 'Ni mi všeč';

  @override
  String get dismissibleMiniplayer => 'Odstranljiv mini predvajalnik';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Prikaži dejanski položaj namesto razlike med iskanjem';

  @override
  String get displayAlbumCardTopRightDate => 'Datum desno zgoraj na kartici albuma';

  @override
  String get displayAlbumCardTopRightDateSubtitle => 'Prikaži datum albuma desno zgoraj na kartici albuma';

  @override
  String get displayArtistBeforeTitle => 'Prikaži izvajalca pred naslovom';

  @override
  String get displayArtworkOnLockscreen => 'Prikaži sliko albuma na zaklenjenem zaslonu';

  @override
  String get displayAudioInfoInMiniplayer => 'Prikaži informacije o zvoku';

  @override
  String get displayFavButtonInNotification => 'Prikaži gumb za priljubljene v obvestilu';

  @override
  String get displayFavButtonInNotificationSubtitle => 'Sličica se lahko premakne.';

  @override
  String get displayFavouriteIconInTrackTile => 'Prikaži gumb za priljubljene';

  @override
  String get displayRemainingDurationInsteadOfTotal => 'Prikaži preostali čas namesto celotnega';

  @override
  String get displayStopButtonInNotification => 'Prikaži gumb za ustavitev v obvestilu';

  @override
  String get displayThirdItemInRowInTrackTile => 'Prikaži tretji element v vsaki vrstici';

  @override
  String get displayThirdRowInTrackTile => 'Prikaži tretjo vrstico';

  @override
  String get displayTrackNumberInAlbumPage => 'Prikaži številko skladbe na strani albuma';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => 'Prikaži majhno polje s številko skladbe na strani albuma';

  @override
  String get doNothing => 'Ne naredi ničesar';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => 'Končano';

  @override
  String get dontAskAgain => 'Ne vprašaj ponovno';

  @override
  String get dontDim => 'Ne zatemni';

  @override
  String get dontRestorePosition => 'Ne obnovi';

  @override
  String get dontResume => 'Ne nadaljuj';

  @override
  String get doubleTapToToggleLyrics => 'Dvakrat tapnite za preklop besedila';

  @override
  String get download => 'Prenesi';

  @override
  String get downloadingWillOverrideIt => 'Prenos ga bo prepisal';

  @override
  String get downloads => 'Prenosi';

  @override
  String get downloadsMetadataTags => 'Oznake metapodatkov prenosov';

  @override
  String get downloadsMetadataTagsSubtitle => 'Privzeto izlušči izvajalca, naslov in album iz informacij o videu';

  @override
  String get dragToSeek => 'Povleci za iskanje';

  @override
  String get duckAudio => 'Znižaj glasnost zvoka (Duck)';

  @override
  String get duplicatedItemsAdding => 'Poskušate dodati elemente, ki že obstajajo na tem seznamu';

  @override
  String get duplicatedTracks => 'Podvojene skladbe';

  @override
  String get duration => 'Trajanje';

  @override
  String get edgeColorsSwitching => 'Preklapljanje barv robov';

  @override
  String get edit => 'Uredi';

  @override
  String get editArtwork => 'Uredi sliko albuma';

  @override
  String get editTags => 'Uredi oznake';

  @override
  String get email => 'E-pošta';

  @override
  String get emptyNonMeaningfulTagFields => 'imate polja s praznimi/nepomembnimi vrednostmi, prepričajte se, da jih res želite urediti';

  @override
  String get emptyValue => 'Prazna vrednost';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => 'Omogoči učinek zameglitve';

  @override
  String get enableBottomNavBar => 'Omogoči spodnjo navigacijsko vrstico';

  @override
  String get enableBottomNavBarSubtitle => 'Elementi so znotraj predala v obe smeri';

  @override
  String get enableClipboardMonitoring => 'Omogoči spremljanje odložišča';

  @override
  String get enableClipboardMonitoringSubtitle => 'Omogoča lepljenje povezav in besedila v iskalno vrstico sproti';

  @override
  String get enableCrossfadeEffect => 'Omogoči učinek prelivanja';

  @override
  String get enableFadeEffectOnPlayPause => 'Omogoči učinek bledenja pri predvajanju/pavzi';

  @override
  String get enableFoldersHierarchy => 'Omogoči hierarhijo map';

  @override
  String get enableGlowEffect => 'Omogoči učinek žarenja';

  @override
  String get enableM3uSync => 'Omogoči sinhronizacijo M3U';

  @override
  String get enableM3uSyncNote1 => 'Sinhronizacija M3U omogoča shranjevanje sprememb seznama predvajanja v izvirno datoteko M3U';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return 'Če gre kaj narobe, bo varnostna kopija tega seznama v $playlistsBackupPath';
  }

  @override
  String get enableM3uSyncSubtitle => 'Če zavrnete, bodo vse spremembe tega seznama ob ponovnem zagonu izgubljene';

  @override
  String get enableMiniplayerParticles => 'Omogoči premikajoče delce';

  @override
  String get enableParallaxEffect => 'Omogoči učinek paralakse';

  @override
  String get enablePartyMode => 'Omogoči način zabave';

  @override
  String get enablePartyModeSubtitle => 'Uporabi moderen učinek dihanja robov';

  @override
  String get enablePictureInPicture => 'Omogoči slika-v-sliki';

  @override
  String get enableReordering => 'Omogoči spreminjanje vrstnega reda';

  @override
  String get enableReturnYoutubeDislike => 'Omogoči Return Youtube Dislike';

  @override
  String get enableSearchCleanup => 'Omogoči čiščenje iskanja';

  @override
  String get enableSearchCleanupSubtitle => 'Vsi simboli in presledki bodo prezrti';

  @override
  String get enableSponsorblock => 'Omogoči SponsorBlock';

  @override
  String get enableVideoPlayback => 'Omogoči predvajanje videa';

  @override
  String get enterSymbol => 'Vnesite simbol';

  @override
  String get equalizer => 'Izenačevalnik';

  @override
  String get error => 'Napaka';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => 'Napaka pri predvajanju skladbe';

  @override
  String get excludedFodlers => 'Izključene mape';

  @override
  String get exit => 'Izhod';

  @override
  String get exitAppSubtitle => 'Tapnite znova za izhod';

  @override
  String get expandedMiniplayer => 'Razširjen mini predvajalnik';

  @override
  String get exportAsM3u => 'Izvozi kot M3U';

  @override
  String get extension => 'Končnica';

  @override
  String get externalFiles => 'Zunanje datoteke';

  @override
  String get extract => 'Izlušči';

  @override
  String get extractAllColorPalettes => 'Izlušči vse barvne palete';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Izlušči preostalih $numberString?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => 'Izlušči feat. izvajalce iz naslova';

  @override
  String get extractFeatArtistSubtitle => 'Izlušči (feat. X) in (ft. X) izvajalce kot nov vnos izvajalca.';

  @override
  String get extractingInfo => 'Pridobivanje informacij';

  @override
  String get extras => 'Dodatki';

  @override
  String get extrasSubtitle => 'Dodatne nastavitve za izboljšanje izkušnje';

  @override
  String get extreme => 'Ekstremno';

  @override
  String get failed => 'Ni uspelo';

  @override
  String get failedEdits => 'Neuspešna urejanja';

  @override
  String get favourites => 'Priljubljene';

  @override
  String get features => 'Features';

  @override
  String get fetching => 'Pridobivanje';

  @override
  String get fetchingOfAllVideos => 'Pridobivanje vseh videov';

  @override
  String get file => 'Datoteka';

  @override
  String get fileAlreadyExists => 'Datoteka že obstaja';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => 'Ime datoteke';

  @override
  String get fileNameWoExt => 'Ime datoteke brez končnice';

  @override
  String get filenameShouldntStartWith => 'Ime datoteke se ne sme začeti z';

  @override
  String get files => 'Datoteke';

  @override
  String get filler => 'Polnilo';

  @override
  String get filterAlbums => 'Filtriraj albume';

  @override
  String get filterArtists => 'Filtriraj izvajalce';

  @override
  String get filterGenres => 'Filtriraj žanre';

  @override
  String get filterPlaylists => 'Filtriraj sezname predvajanja';

  @override
  String get filterTracks => 'Filtriraj skladbe';

  @override
  String get filterTracksBy => 'Filtriraj skladbe v seznamih iskanja po';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => 'Skladbe filtrirane po velikosti in trajanju';

  @override
  String get finished => 'Končano';

  @override
  String get finishedUpdatingLibrary => 'Posodabljanje knjižnice končano';

  @override
  String get firstListen => 'Prvo poslušanje';

  @override
  String get fixYtdlpBigThumbnailSize => 'Popravi veliko velikost sličice yt-dlp';

  @override
  String get floatingActionButton => 'Plavajoči akcijski gumb';

  @override
  String get folder => 'Mapa';

  @override
  String get folderName => 'Ime mape';

  @override
  String get folders => 'Mape';

  @override
  String get fontScale => 'Velikost pisave';

  @override
  String get forceMiniplayerFollowTrackColors => 'Vsili mini predvajalniku barve skladbe';

  @override
  String get forceSquaredAlbumThumbnail => 'Vsili kvadratno sličico albuma';

  @override
  String get forceSquaredThumbnailNote => 'Velikost sličice in višina ploščice NISTA enaki, kvadratni videz ne bo pričakovan. ju želite izenačiti?';

  @override
  String get forceSquaredTrackThumbnail => 'Vsili kvadratno sličico skladbe';

  @override
  String get forceStopColorPaletteGeneration => 'Prisilno ustaviti ustvarjanje barvnih palet? Lahko nadaljujete kasneje';

  @override
  String get format => 'Format';

  @override
  String get fullscreen => 'Celozaslonsko';

  @override
  String get gaplessPlayback => 'Predvajanje brez presledkov';

  @override
  String get generate => 'Ustvari';

  @override
  String get generateFromDates => 'Časovni razpon';

  @override
  String get generateFromDatesSubtitle => 'Ustvari seznam skladb, ki ste jih poslušali v časovnem obdobju';

  @override
  String get generateRandomPlaylist => 'Ustvari naključni seznam predvajanja';

  @override
  String get genre => 'Žanr';

  @override
  String get genres => 'Žanri';

  @override
  String get goToAlbum => 'Pojdi na album';

  @override
  String get goToArtist => 'Pojdi na izvajalca';

  @override
  String get goToChannel => 'Pojdi na kanal';

  @override
  String get goToFolder => 'Pojdi v mapo';

  @override
  String get goodLooking => 'Izgleda dobro';

  @override
  String get grantStoragePermission => 'Dovoli dostop do shrambe';

  @override
  String get group => 'Skupina';

  @override
  String get groupArtworksByAlbum => 'Združi slike po albumih';

  @override
  String get guide => 'Vodnik';

  @override
  String get hapticFeedback => 'Haptični odziv';

  @override
  String get heightOfAlbumTile => 'Višina ploščice albuma';

  @override
  String get heightOfTrackTile => 'Višina ploščice skladbe';

  @override
  String get hideSkipButtonAfter => 'Skrij gumb za preskok po';

  @override
  String get highMatches => 'Visoko ujemanje';

  @override
  String get highPerformance => 'Visoka zmogljivost';

  @override
  String get highlight => 'Poudarek';

  @override
  String get history => 'Zgodovina';

  @override
  String get historyImportMissingEntriesNote => 'Teh vnosov ni bilo mogoče najti v knjižnici. Če menite, da obstajajo, razmislite o ročnem dodajanju';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString poslušanj za $oldTrackInfo bo zamenjanih z $newTrackInfo, potrdi?',
    );
    return '$_temp0';
  }

  @override
  String get home => 'Domov';

  @override
  String get hook => 'Refren';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12-urni format';

  @override
  String get hours => 'Ure';

  @override
  String get iReadAndAgree => 'Prebral sem in se strinjam';

  @override
  String get ifNotPlaying => 'Če se ne predvaja';

  @override
  String get ignoreBatteryOptimizationsSubtitle => 'Prenosi so lahko upočasnjeni, če je aplikacija baterijsko omejena';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Prezri pogoste predpone pri razvrščanju';

  @override
  String get ignores => 'Ignorira';

  @override
  String get imageSource => 'Vir slike';

  @override
  String get immersiveMode => 'Imersivni način';

  @override
  String get immersiveModeSubtitle => 'Skrij statusno in navigacijsko vrstico, ko je mini predvajalnik razširjen';

  @override
  String get import => 'Uvozi';

  @override
  String get importAll => 'Uvozi vse';

  @override
  String get importLastFmHistory => 'Uvozi zgodovino Last.fm';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. Pojdite na $lastfmCsvLink\n\n2. Vnesite uporabniško ime, pridobite in prenesite datoteko CSV.\n\n3. Izberite datoteko na naslednjem zaslonu.';
  }

  @override
  String get importTimeRange => 'Uvozi časovni razpon';

  @override
  String get importYoutubeHistory => 'Uvozi zgodovino YouTube';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. Pojdite na $takeoutLink\n\n2. Pritisnite \"Multiple Formats\" in poleg \"History\" izberite \"JSON\".\n\n3. Pritisnite \"All Youtube data included\", prekličite izbor vsega in izberite samo zgodovino.\n\n4. Ustvarite izvoz, prenesite in razširite.\n\n5. Izberite \"watch-history.json\" na naslednjem zaslonu.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Uspešno uvoženih $numberString kanalov',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Uspešno uvoženih $numberText seznamov predvajanja',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Vključi videe';

  @override
  String get indexRefreshRequired => 'Po spremembi osvežite knjižnico';

  @override
  String get indexer => 'Indeksirnik';

  @override
  String get indexerNote => 'Opomba: Nepopolno število slik albumov se nanaša na podvojene in nenajdene slike';

  @override
  String get indexerSubtitle => 'Upravljajte svojo glasbeno knjižnico';

  @override
  String get infinityQueueOnNextPrev => 'Neskončna vrsta pri Naprej/Nazaj';

  @override
  String get infinityQueueOnNextPrevSubtitle => 'pritisk na naprej med predvajanjem zadnjega elementa skoči na prvega in obratno';

  @override
  String get info => 'Info';

  @override
  String get inserted => 'vstavljeno';

  @override
  String get instantlyApplies => 'Takojšnja uporaba';

  @override
  String get interactionReminder => 'Opomnik za interakcijo';

  @override
  String get intro => 'Uvod';

  @override
  String get invertSelection => 'Obrni izbor';

  @override
  String get issues => 'Issues';

  @override
  String get item => 'Element';

  @override
  String get jump => 'Skoči';

  @override
  String get jumpToDay => 'Skoči na dan';

  @override
  String get jumpToFirstTrackAfterQueueFinish => 'Skoči na prvo skladbo po koncu vrste';

  @override
  String get keepCachedVersions => 'Obdrži predpomnjene različice';

  @override
  String get keepFileDates => 'Obdrži datume datotek';

  @override
  String get keepScreenAwakeMiniplayerExpanded => 'Mini predvajalnik je razširjen';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => 'Mini predvajalnik je razširjen in video se predvaja';

  @override
  String get keepScreenAwakeNone => 'Ne ohranjaj zaslona prižganega';

  @override
  String get keepScreenAwakeWhen => 'Ohrani zaslon prižgan, ko';

  @override
  String get killPlayerAfterDismissingApp => 'Ubij predvajalnik po zaprtju aplikacije';

  @override
  String get language => 'Jezik';

  @override
  String get learnMore => 'Več informacij';

  @override
  String get leftAction => 'Levo dejanje';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => 'Zavihki knjižnice';

  @override
  String get libraryTabsReorder => 'Vrstni red aktiviranih zavihkov lahko spremenite.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => 'Všeč mi je';

  @override
  String get liked => 'Všečkano';

  @override
  String get link => 'Povezava';

  @override
  String get listOfFolders => 'Seznam map';

  @override
  String get loadAll => 'Naloži vse';

  @override
  String get loadingFile => 'Nalaganje datoteke';

  @override
  String get local => 'Lokalno';

  @override
  String get localVideoMatching => 'Lokalno ujemanje videa';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Dejanje dolgega pritiska';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Dolgo pritisnite besedilo za celozaslonski način';

  @override
  String get lostMemories => 'Izgubljeni spomini';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'okoli tega časa, pred $numberString leti',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => 'Ojačevalec glasnosti';

  @override
  String get lyricist => 'Tekstopisec';

  @override
  String get lyrics => 'Besedilo';

  @override
  String get lyricsSource => 'Vir besedila';

  @override
  String get m3uPlaylist => 'Seznam predvajanja M3U';

  @override
  String get makeYourFirstListen => 'Opravite prvo poslušanje!';

  @override
  String get manage => 'Upravljaj';

  @override
  String get manageYourAccounts => 'Upravljajte svoje račune';

  @override
  String get manualBackup => 'Ročno';

  @override
  String get manualBackupSubtitle => 'izberite določeno datoteko';

  @override
  String get markAsRead => 'Označi kot prebrano';

  @override
  String get matchAllTracks => 'Ujemanje vseh skladb';

  @override
  String get matchAllTracksNote => 'to lahko vpliva na hitrost ujemanja, saj bo preverilo vse skladbe v knjižnici';

  @override
  String get matchingType => 'Vrsta ujemanja';

  @override
  String get maxAudioCacheSize => 'Maks. velikost predpomnilnika zvoka';

  @override
  String get maxImageCacheSize => 'Maks. velikost predpomnilnika slik';

  @override
  String get maxVideoCacheSize => 'Maks. velikost predpomnilnika videa';

  @override
  String get maximum => 'Maksimalno';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store je omogočen, to ne bo imelo učinka';

  @override
  String get medium => 'Srednje';

  @override
  String get membershipCode => 'Koda';

  @override
  String get membershipCodeSentToEmail => 'Koda poslana na vaš e-naslov';

  @override
  String get membershipDidntChange => 'Članstvo se ni spremenilo';

  @override
  String get membershipEnjoyNew => 'Uživajte v novem članstvu';

  @override
  String get membershipFreeCoupon => 'Brezplačen kupon';

  @override
  String get membershipManage => 'Upravljajte svoje članstvo';

  @override
  String get membershipNoSubscriptionsFoundForUser => 'Za tega uporabnika ni najdenih naročnin';

  @override
  String get membershipSignInToPatreonAccount => 'Prijavite se v svoj Patreon račun';

  @override
  String get membershipUnknown => 'Neznano članstvo';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return 'Za dodajanje več računov potrebujete članstvo $name1 ali $name2';
  }

  @override
  String get merge => 'Združi';

  @override
  String get metadataCache => 'Predpomnilnik metapodatkov';

  @override
  String get metadataEditFailed => 'Urejanje metapodatkov ni uspelo';

  @override
  String get metadataReadFailed => 'Branje metapodatkov ni uspelo';

  @override
  String get minFileDuration => 'Minimalno trajanje skladbe';

  @override
  String get minFileSize => 'Minimalna velikost datoteke';

  @override
  String get minTrackDurationToRestoreLastPosition => 'Minimalno trajanje skladbe za obnovitev zadnjega položaja';

  @override
  String get minValueCantBeMoreThanMax => 'Minimalna vrednost ne sme biti večja od maksimalne';

  @override
  String get minValueToCountTrackListen => 'Štej poslušanje po: ';

  @override
  String get minimizedMiniplayer => 'Pomanjšan mini predvajalnik';

  @override
  String get minimum => 'Minimalno';

  @override
  String get minimumOneFolderSubtitle => 'Obstajati mora vsaj 1 mapa, dodajte več map, če želite odstraniti to';

  @override
  String get minimumOneItem => 'Elementa ni bilo mogoče odstraniti';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Vsaj $numberString elementov mora ostati',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimalno trajanje segmenta';

  @override
  String get miniplayerCustomization => 'Prilagajanje mini predvajalnika';

  @override
  String get minutes => 'minut';

  @override
  String get missingEntries => 'Manjkajoči vnosi';

  @override
  String get missingTracks => 'Manjkajoče skladbe';

  @override
  String get mix => 'Mešanica';

  @override
  String get mixPlaylistGeneratedByYoutube => 'Mešani seznam predvajanja, ustvarjen z YouTubom';

  @override
  String get mixes => 'Mešanice';

  @override
  String get mobile => 'Mobilno';

  @override
  String get month => 'Mesec';

  @override
  String get months => 'Mesecev';

  @override
  String get mood => 'Razpoloženje';

  @override
  String get moods => 'Razpoloženja';

  @override
  String get more => 'Več';

  @override
  String get mostPlayed => 'Najbolj predvajano';

  @override
  String get multipleTracksTagsEditNote => 'Uredili boste te skladbe,\nNespremenjena polja ostanejo nedotaknjena.';

  @override
  String get musicOfftopic => 'Glasba izven teme';

  @override
  String get name => 'Ime';

  @override
  String get nameContainsBadCharacter => 'Ime vsebuje neveljaven znak';

  @override
  String get never => 'Nikoli';

  @override
  String get newDirectory => 'Nova mapa';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => 'Dodaj skladbe';

  @override
  String get newTracksMoods => 'Razpoloženje';

  @override
  String get newTracksMoodsSubtitle => 'Ustvari skladbe na podlagi razpoložljivih razpoloženj';

  @override
  String get newTracksRandom => 'Naključno';

  @override
  String get newTracksRandomSubtitle => 'Izberi naključne skladbe iz knjižnice';

  @override
  String get newTracksRatings => 'Ocene';

  @override
  String get newTracksRatingsSubtitle => 'Ustvari skladbe z določeno oceno';

  @override
  String get newTracksRecommended => 'Priporočeno';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return 'Ustvari skladbe, ki ste jih običajno poslušali z $currentTrack';
  }

  @override
  String get newTracksSimilarrReleaseDate => 'Podoben datum izdaje';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return 'Ustvari skladbe, izdane približno v istem času kot $currentTrack';
  }

  @override
  String get newTracksUnknownYear => 'Skladba ima neznano leto';

  @override
  String get newest => 'Najnovejše';

  @override
  String get next => 'Naslednja';

  @override
  String get no => 'ne';

  @override
  String get noChangesFound => 'Spremembe niso bile najdene.';

  @override
  String get noEnoughTracks => 'Imate premalo skladb..';

  @override
  String get noExcludedFolders => 'Imate prazne izključene mape';

  @override
  String get noFolderChosen => 'Niste izbrali nobene mape';

  @override
  String get noMoodsAvailable => 'Ni razpoložljivih razpoloženj';

  @override
  String get noNetworkAvailableToFetchData => 'Ni omrežja za pridobivanje podatkov';

  @override
  String get noTracksFound => 'Skladbe niso bile najdene';

  @override
  String get noTracksFoundBetweenDates => 'V tem časovnem obdobju ni skladb.';

  @override
  String get noTracksFoundInDirectory => 'V tej mapi ni najdenih skladb';

  @override
  String get noTracksInHistory => 'V zgodovini nimate dovolj skladb';

  @override
  String get nonActive => 'Neaktivno';

  @override
  String get nonFavourites => 'Ni med priljubljenimi';

  @override
  String get none => 'Brez';

  @override
  String get normalizeAudio => 'Normaliziraj zvok';

  @override
  String get normalizeAudioSubtitle => 'Normalizira glasnost z branjem oznake replay gain ali informacij z YouTuba';

  @override
  String get notAvailableForYourDevice => 'Ni na voljo za vašo napravo';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get note => 'Opomba';

  @override
  String get notification => 'Obvestilo';

  @override
  String get notifications => 'Obvestila';

  @override
  String get numberOfTracks => 'Število skladb';

  @override
  String get ofLabel => 'od';

  @override
  String get offlineSearch => 'Iskanje brez povezave';

  @override
  String get offset => 'Odmik';

  @override
  String get oldDirectory => 'Stara mapa';

  @override
  String get oldDirectoryStillHasTracks => 'Stara mapa še vedno vsebuje skladbe, potrdi?';

  @override
  String get oldestWatch => 'Najstarejši ogled';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => 'Ob prekinitvi';

  @override
  String get onNotificationTap => 'Ob tapu na obvestilo';

  @override
  String get onOpeningYoutubeLink => 'Ob odpiranju YouTube povezave';

  @override
  String get onSwiping => 'Ob potegu';

  @override
  String get onVolumeZero => 'Pri glasnosti 0';

  @override
  String get ongoing => 'V teku';

  @override
  String get open => 'Odpri';

  @override
  String get openApp => 'Odpri aplikacijo';

  @override
  String get openInFileExplorer => 'Odpri v Raziskovalcu';

  @override
  String get openInYoutubeView => 'Odpri v pogledu YouTube';

  @override
  String get openMiniplayer => 'Odpri mini predvajalnik';

  @override
  String get openQueue => 'Odpri čakalno vrsto';

  @override
  String get openYoutubeLink => 'Odpri YouTube povezavo';

  @override
  String operationRequiresAccount({required String name}) {
    return 'Operacija $name zahteva račun, prijavite se za nadaljevanje';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return 'Operacija $operation zahteva vsaj članstvo $name';
  }

  @override
  String get or => 'ali';

  @override
  String get others => 'Drugo';

  @override
  String get output => 'Izhod';

  @override
  String get outro => 'Odjava';

  @override
  String get overrideOldFilesInTheSameFolder => 'Prepiši stare datoteke v isti mapi';

  @override
  String get palette => 'Paleta';

  @override
  String get paletteMix => 'Mešanica';

  @override
  String get paletteNewMix => 'Nova mešanica';

  @override
  String get paletteSelectedMix => 'Izbrana mešanica';

  @override
  String get parallelDownloads => 'Vzporedni prenosi';

  @override
  String get parsed => 'razčlenjeno';

  @override
  String get password => 'Password';

  @override
  String get path => 'Celotna pot datoteke';

  @override
  String get pause => 'Pavza';

  @override
  String get pauseFadeDuration => 'Trajanje bledenja pri pavzi';

  @override
  String get pausePlayback => 'Pavza predvajanja';

  @override
  String get percentage => 'Odstotek';

  @override
  String get performanceMode => 'Način zmogljivosti';

  @override
  String get performanceNote => 'Lahko vpliva na zmogljivost';

  @override
  String get personalized => 'Prilagojeno';

  @override
  String get personalizedRelatedVideos => 'Prilagojeni povezani videi';

  @override
  String get personalizedRelatedVideosSubtitle => 'Onemogočanje tega bo povečalo porabo podatkov';

  @override
  String get pickColorsFromDeviceWallpaper => 'Izberi barve iz ozadja naprave';

  @override
  String get pickFromStorage => 'Izberi iz shrambe';

  @override
  String get pinned => 'Pripeto';

  @override
  String get pitch => 'Višina tona';

  @override
  String get plain => 'Navadno';

  @override
  String get play => 'Predvajaj';

  @override
  String get playAfter => 'Predvajaj za';

  @override
  String get playAfterNextPrev => 'Samodejno predvajanje pri Naprej/Nazaj';

  @override
  String get playAll => 'Predvajaj vse';

  @override
  String get playFadeDuration => 'Trajanje bledenja pri predvajanju';

  @override
  String get playLast => 'Predvajaj zadnje';

  @override
  String get playNext => 'Predvajaj naslednje';

  @override
  String get playbackSetting => 'Predvajanje';

  @override
  String get playbackSettingSubtitle => 'Dostopno neposredno v predvajalniku z dolgim pritiskom na gumb za zvok';

  @override
  String get playlist => 'Seznam predvajanja';

  @override
  String get playlists => 'Seznami predvajanja';

  @override
  String get playlistsImportM3uNative => 'To bo uvozilo sezname M3U samo za uporabo v Namidi, uporabite pri migraciji';

  @override
  String get playlistsImportM3uSynced =>
      'To bo samodejno uvozilo sezname M3U iz map indeksirnika in jih sinhroniziralo z izvirno datoteko M3U. omogočite, če dostopate/spreminjate sezname iz drugih aplikacij';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'Samodejno uvozi sezname predvajanja M3U';

  @override
  String get pleaseEnterADifferentName => 'To ime že obstaja :(\nprosimo poskusite drugo ime';

  @override
  String get pleaseEnterALink => 'Prosimo vnesite povezavo';

  @override
  String get pleaseEnterALinkSubtitle => 'umm.. je to youtube povezava?';

  @override
  String get pleaseEnterAName => 'Prosimo vnesite ime';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => 'Prepreči podvojene skladbe';

  @override
  String get preventDuplicatedTracksSubtitle => 'Uporabi ime datoteke za edinstveno identifikacijo skladb';

  @override
  String get preview => 'Predogled';

  @override
  String get previous => 'Prejšnja';

  @override
  String get previousButtonReplays => 'Gumb prejšnja ponovi';

  @override
  String get previousButtonReplaysSubtitle => 'če pritisnjen, ko je trenutni položaj večji od trajanja iskanja';

  @override
  String get prioritizeEmbeddedLyrics => 'Daj prednost vdelanemu besedilu';

  @override
  String get priority => 'Prioriteta';

  @override
  String get private => 'Zasebno';

  @override
  String get progress => 'Napredek';

  @override
  String get promptToChangeTrackPath => 'Običajno se to zgodi, ko izbrišete/premaknete/preimenujete datoteko zunaj Namide. Želite posodobiti trenutno pot?';

  @override
  String get public => 'Javno';

  @override
  String get queue => 'Čakalna vrsta';

  @override
  String get queues => 'Čakalne vrste';

  @override
  String get random => 'Naključno';

  @override
  String get randomPicks => 'Naključni izbori';

  @override
  String get rating => 'Ocena';

  @override
  String get reIndex => 'Ponovno indeksiraj';

  @override
  String get reIndexSubtitle => 'Ponovno zgradi glasbeno knjižnico iz nič';

  @override
  String get reIndexWarning => 'Ta proces lahko traja nekaj časa, odvisno od velikosti knjižnice.\n\nSlike albumov ne bodo ponovno indeksirane, dokler obstajajo';

  @override
  String get recentAlbums => 'Nedavni albumi';

  @override
  String get recentArtists => 'Nedavni izvajalci';

  @override
  String get recentListens => 'Nedavna poslušanja';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => 'Nedavno dodano';

  @override
  String get recordLabel => 'Založba';

  @override
  String get refresh => 'Osveži';

  @override
  String get refreshLibrary => 'Osveži knjižnico';

  @override
  String get refreshLibrarySubtitle => 'Preveri za novo dodano ali izbrisano glasbo';

  @override
  String get refreshOnStartup => 'Osveži ob zagonu';

  @override
  String get relatedVideos => 'Povezani videi';

  @override
  String get rememberAudioOnlyMode => 'Zapomni si način samo zvok';

  @override
  String get remixer => 'Remikser';

  @override
  String get remove => 'Odstrani';

  @override
  String get removeDuplicates => 'Odstrani podvojene';

  @override
  String get removeFromFavourites => 'Odstrani iz priljubljenih';

  @override
  String get removeFromLibrary => 'Odstrani iz knjižnice';

  @override
  String get removeFromPlaylist => 'Odstrani s seznama predvajanja';

  @override
  String get removeQueue => 'Odstrani čakalno vrsto';

  @override
  String get removeSourceFromHistory => 'Odstrani vir iz zgodovine';

  @override
  String get removeWhitespaces => 'Odstrani presledke';

  @override
  String get removed => 'Odstranjeno';

  @override
  String get rename => 'Preimenuj';

  @override
  String get renamePlaylist => 'Preimenuj seznam predvajanja';

  @override
  String get reorderable => 'Spremenljiv vrstni red';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Ponovi še $number-krat',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Način ponavljanja';

  @override
  String get repeatModeAll => 'Ponovi celotno vrsto';

  @override
  String get repeatModeNone => 'Ustavi na zadnji skladbi';

  @override
  String get repeatModeOne => 'Ponovi trenutno skladbo';

  @override
  String get replaceAllListensWithAnotherTrack => 'Zamenjaj vsa poslušanja z drugo skladbo';

  @override
  String get replies => 'Odgovori';

  @override
  String get reply => 'Odgovori';

  @override
  String get requiresClearingImageCacheAndReIndexing => 'Zahteva čiščenje predpomnilnika slik in ponovno indeksiranje';

  @override
  String get rescanVideos => 'Ponovno preišči videe';

  @override
  String get resetBrightness => 'Ponastavi svetlost';

  @override
  String get resetToDefault => 'Nastavi na';

  @override
  String get respectNoMedia => 'Spoštuj .nomedia';

  @override
  String get respectNoMediaSubtitle => 'Ne vključi map, ki imajo .nomedia';

  @override
  String get restart => 'Ponovni zagon';

  @override
  String get restoreBackup => 'Obnovi varnostno kopijo';

  @override
  String get restoreDefaults => 'Obnovi privzeto';

  @override
  String get restoredBackupSuccessfully => 'Varnostna kopija obnovljena';

  @override
  String get restoredBackupSuccessfullySub => 'Datoteka varnostne kopije je bila uspešno obnovljena';

  @override
  String get resume => 'Nadaljuj';

  @override
  String get resumeIfWasInterrupted => 'Nadaljuj, če je bilo prekinjeno';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => 'Nadaljuj, če je bilo pavzirano zaradi glasnosti';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: 'Nadaljuj, če je bilo pavzirano manj kot $numberString minut',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => 'Obrnjen vrstni red';

  @override
  String get rightAction => 'Desno dejanje';

  @override
  String get ringtone => 'Melodija zvonjenja';

  @override
  String get sameDirectoryOnly => 'Samo ista mapa';

  @override
  String get sample => 'Vzorec';

  @override
  String get sampleRate => 'Hitrost vzorčenja';

  @override
  String get save => 'Shrani';

  @override
  String get saveToLibrary => 'Shrani v knjižnico';

  @override
  String get savedIn => 'Shranjeno v';

  @override
  String get scaleMultiplier => 'Množitelj merila';

  @override
  String get search => 'Išči';

  @override
  String get searchYoutube => 'Išči YouTube';

  @override
  String get seconds => 'sekund';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => 'Trajanje iskanja';

  @override
  String get seekDurationInfo => 'Lahko tapnete trenutno trajanje za iskanje nazaj in celotno trajanje za iskanje naprej';

  @override
  String get seekbar => 'Drsnik za iskanje';

  @override
  String get selectAll => 'Izberi vse';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Izberi datoteke že v lokalni knjižnici';

  @override
  String get selectedTracks => 'Izbrane skladbe';

  @override
  String get selfPromotion => 'Samopromocija';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => 'Te besede ne bodo razdeljene';

  @override
  String get separatorsMessage => 'Ni treba vstavljati presledkov, razen če želite uporabiti črko/simbol, ki ga najdete v celotni besedi (kot x in ft.)';

  @override
  String get serverAddress => 'Naslov strežnika';

  @override
  String get setAs => 'Nastavi kot';

  @override
  String get setAsDefault => 'Nastavi kot privzeto';

  @override
  String get setFileLastModifiedAsVideoUploadDate => 'Nastavi datum zadnje spremembe datoteke kot datum nalaganja videa';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => 'Nastavi razpoloženja';

  @override
  String get setMoodsSubtitle => 'Uporabite vejice (,) za ločevanje';

  @override
  String get setRating => 'Nastavi oceno';

  @override
  String get setTags => 'Nastavi oznake';

  @override
  String get setYoutubeLink => 'Nastavi YouTube povezavo';

  @override
  String get settings => 'Nastavitve';

  @override
  String get setupFirstStartup => 'Nastavi prvi zagon';

  @override
  String get share => 'Deli';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Bližnjice';

  @override
  String get shouldDuck => 'Mora znižati glasnost';

  @override
  String get shouldDuckNote => 'Nakazuje, da se mora glasnost znižati. npr: obvestilo';

  @override
  String get shouldPause => 'Mora pavzirati';

  @override
  String get shouldPauseNote => 'Nakazuje, da se mora predvajanje pavzirati. npr: klici';

  @override
  String get showAll => 'Prikaži vse';

  @override
  String get showChannelWatermarkInFullscreen => 'Prikaži vodni žig kanala v celozaslonskem načinu';

  @override
  String get showFailedOnly => 'Prikaži samo neuspešne';

  @override
  String get showHideUnknownFields => 'Prikaži/skrij neznana polja';

  @override
  String get showInSeekbar => 'Prikaži v drsniku';

  @override
  String get showMixPlaylistsIn => 'Prikaži mešanice v';

  @override
  String get showMore => 'Prikaži več';

  @override
  String get showShortVideosIn => 'Prikaži Shorts v';

  @override
  String get showSkipButton => 'Prikaži gumb za preskok';

  @override
  String get showVideoEndcards => 'Prikaži končne kartice videa';

  @override
  String get showWebm => 'Prikaži webm';

  @override
  String get shuffle => 'Premešaj';

  @override
  String get shuffleAll => 'Premešaj vse';

  @override
  String get shuffleNext => 'Premešaj naslednjo';

  @override
  String get signIn => 'Prijava';

  @override
  String get signInCanceled => 'Prijava je bila preklicana';

  @override
  String get signInFailed => 'Prijava ni uspela';

  @override
  String get signInToYourAccount => 'Prijavite se v svoj račun';

  @override
  String get signInYouDontHaveAccount => 'Nimate prijavljenega računa';

  @override
  String get signInYouNeedAccountToViewPage => 'Za ogled te strani potrebujete račun';

  @override
  String get signOut => 'Odjava';

  @override
  String signOutFromName({required String name}) {
    return 'Odjava iz $name';
  }

  @override
  String get signingInAllowsBasicUsage => 'Prijava omogoča osnovno uporabo';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Pridobite zgodnji dostop prek Patreona ali z uporabo kupona';

  @override
  String get similarDiscoverDate => 'Podoben datum odkrivanja';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Ustvari skladbe, ki so bile odkrite približno v istem času kot $currentTrack';
  }

  @override
  String get similarTimeRange => 'Podoben časovni razpon';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Ustvari skladbe, ki ste jih poslušali približno v istem času kot $currentTrack';
  }

  @override
  String get singles => 'Singli';

  @override
  String get size => 'Velikost';

  @override
  String get skip => 'Preskoči';

  @override
  String get skipCountTracking => 'Sledenje številu preskokov';

  @override
  String get skipSilence => 'Preskoči tišino';

  @override
  String get skipSponsorSegmentsInVideos => 'Preskoči sponzorske segmente v videih';

  @override
  String get sleepAfter => 'Spanje po';

  @override
  String get sleepTimer => 'Časovnik za spanje';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => 'Razvrsti po';

  @override
  String get source => 'Vir';

  @override
  String get speed => 'Hitrost';

  @override
  String get sponsor => 'Sponzor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'Lestvica SponsorBlock';

  @override
  String get staggeredAlbumGridView => 'Zamaknjen mrežni pogled albumov';

  @override
  String get start => 'Začetek';

  @override
  String get stats => 'Statistika';

  @override
  String get statsSubtitle => 'Tukaj je nekaj informacij o vaši knjižnici';

  @override
  String get stop => 'Stop';

  @override
  String get stopAfterThisTrack => 'Ustavi po tej skladbi';

  @override
  String get stopAfterThisVideo => 'Ustavi po tem videu';

  @override
  String get storagePermissionDenied => 'Dovoljenje zavrnjeno';

  @override
  String get storagePermissionDeniedSubtitle => 'Prosimo dovolite dostop za izvedbo tega dejanja';

  @override
  String get stretchLyricsDuration => 'Raztegni trajanje besedila';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => 'Naroči se';

  @override
  String get subscribed => 'Naročen';

  @override
  String get subscriber => 'Naročnik';

  @override
  String get subscribers => 'Naročniki';

  @override
  String get succeeded => 'Uspelo';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => 'Podpora';

  @override
  String get supremacy => 'Prevlada';

  @override
  String get sussyBaka => 'Bruh ni skladb';

  @override
  String get swipeActions => 'Dejanja potega';

  @override
  String get swipeToOpenDrawer => 'Potegnite za odpiranje predala';

  @override
  String get synced => 'Sinhronizirano';

  @override
  String get synopsis => 'Povzetek';

  @override
  String get tagFields => 'Polja oznak';

  @override
  String get tags => 'Oznake';

  @override
  String get tapAction => 'Dejanje tapa';

  @override
  String get tapToSeek => 'Tapnite za iskanje';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => 'Način teme';

  @override
  String get themeModeDark => 'Temna';

  @override
  String get themeModeLight => 'Svetla';

  @override
  String get themeModeSystem => 'Sistemska';

  @override
  String get themeSettings => 'Tema';

  @override
  String get themeSettingsSubtitle => 'Splošno vzdušje vašega predvajalnika';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'Ta seznam ima aktivne razvrščevalnike, onemogočite jih pred spreminjanjem vrstnega reda.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'Ta video je verjetno izbrisan ali nastavljen na zasebno.';

  @override
  String get thumbnails => 'Sličice';

  @override
  String get title => 'Naslov';

  @override
  String get top => 'Vrh';

  @override
  String get topComments => 'Najboljši komentarji';

  @override
  String get topCommentsSubtitle => 'Prikaži komentarje na vrhu namesto na dnu';

  @override
  String get topRecentAlbums => 'Najboljši nedavni albumi';

  @override
  String get topRecentArtists => 'Najboljši nedavni izvajalci';

  @override
  String get topRecents => 'Najboljši nedavni';

  @override
  String get totalListenTime => 'Skupni čas poslušanja';

  @override
  String get totalListens => 'Skupno poslušanj';

  @override
  String get totalTracks => 'Skupno skladb';

  @override
  String get totalTracksDuration => 'Skupno trajanje skladb';

  @override
  String get track => 'Skladba';

  @override
  String get trackArtistsSeparator => 'Ločila izvajalcev';

  @override
  String get trackGenresSeparator => 'Ločila žanrov';

  @override
  String get trackInfo => 'Info o skladbi';

  @override
  String get trackNotFound => 'Skladba ni najdena';

  @override
  String get trackNumber => 'Številka skladbe';

  @override
  String get trackNumberTotal => 'Skupno skladb';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return 'Staro ime: \"$oldName\"\n\nNovo ime: \"$newName\"\n\nSte prepričani?';
  }

  @override
  String get trackPlayMode => 'Način predvajanja';

  @override
  String get trackPlayModeSearchResults => 'Rezultati iskanja';

  @override
  String get trackPlayModeSelectedOnly => 'Samo izbrana skladba';

  @override
  String get trackPlayModeTrackAlbum => 'Album skladbe';

  @override
  String get trackPlayModeTrackArtist => 'Glavni izvajalec skladbe';

  @override
  String get trackPlayModeTrackGenre => 'Žanr skladbe';

  @override
  String get trackThumbnailSizeInList => 'Velikost sličice skladbe';

  @override
  String get trackTileCustomization => 'Prilagajanje ploščice skladbe';

  @override
  String get trackTileItemsSeparator => 'Ločilo elementov';

  @override
  String get tracks => 'Skladbe';

  @override
  String get tracksExcludedByNomedia => 'Skladbe izključene zaradi .nomedia';

  @override
  String get tracksInfo => 'Info o skladbah';

  @override
  String get underrated => 'Podcenjeno';

  @override
  String get undo => 'Razveljavi';

  @override
  String get undoChanges => 'Razveljavi spremembe?';

  @override
  String get undoChangesDeletedPlaylist => 'Razveljavi izbrisan seznam predvajanja';

  @override
  String get undoChangesDeletedQueue => 'Razveljavi izbrisano čakalno vrsto';

  @override
  String get undoChangesDeletedTrack => 'Razveljavi izbrisano skladbo';

  @override
  String get uniqueArtworkHash => 'Edinstven hash slike';

  @override
  String get unlimited => 'Neomejeno';

  @override
  String get unlisted => 'Nenavedeno';

  @override
  String get unlock => 'Odkleni';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => 'Posodobi';

  @override
  String get updateDirectoryPath => 'Posodobi pot mape';

  @override
  String get updateMissingTracksOnly => 'Posodobi samo manjkajoče skladbe';

  @override
  String get updating => 'Posodabljanje';

  @override
  String get useCollapsedSettingTiles => 'Uporabi strnjene ploščice nastavitev';

  @override
  String get useMediaStore => 'Uporabi Media Store';

  @override
  String get useMediaStoreSubtitle =>
      '✓ takojšen čas indeksiranja\nx spoštovanje .nomedia bo prisilno vklopljeno\nx nekatere oznake metapodatkov bodo manjkale\nx youtube integracija za lokalno knjižnico ne bo delovala';

  @override
  String get usePitchBlack => 'Uporabi popolnoma črno';

  @override
  String get usePitchBlackSubtitle => 'Uporabno za zaslone AMOLED.. in izgleda bolj kul';

  @override
  String get used => 'Uporabljeno';

  @override
  String get value => 'Vrednost';

  @override
  String get valueBetween50200 => 'Vrednost mora biti med 50% in 200%';

  @override
  String get vibration => 'Vibracija';

  @override
  String get vibrationType => 'Vrsta vibracije';

  @override
  String get video => 'Video';

  @override
  String get videoCache => 'Predpomnilnik videa';

  @override
  String get videoCacheFile => 'Predpomnjena video datoteka';

  @override
  String get videoCacheFiles => 'Predpomnjene video datoteke';

  @override
  String get videoOnly => 'Samo video';

  @override
  String get videoPlaybackSource => 'Vir videa';

  @override
  String get videoPlaybackSourceAutoSubtitle => 'To bo dalo prednost lokalnim videom, če ne bodo najdeni, bo pridobilo z youtuba';

  @override
  String get videoPlaybackSourceLocal => 'Lokalni videi';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => 'Preveri, ali ima katera video datoteka (najdena znotraj izbranega seznama map) ime datoteke, ki vsebuje ime datoteke skladbe';

  @override
  String get videoPlaybackSourceYoutube => 'Z Youtuba';

  @override
  String get videoPlaybackSourceYoutubeSubtitle =>
      'Preveri v imenu datoteke skladbe in komentarju za kakršno koli ujemajočo youtube povezavo, videi so predpomnjeni za kasnejšo uporabo.';

  @override
  String get videoQuality => 'Kakovost videa';

  @override
  String get videoQualitySubtitle => 'Izbrana bo najvišja razpoložljiva kakovost.';

  @override
  String get videoQualitySubtitleNote => 'Vedno je dobro obdržati več alternativ, če kakovost ni najdena, sicer bo preklopilo na najslabšo kakovost';

  @override
  String get videos => 'Videi';

  @override
  String get view => 'ogled';

  @override
  String get viewAll => 'Prikaži vse';

  @override
  String get views => 'ogledov';

  @override
  String get volume => 'Glasnost';

  @override
  String get warning => 'Opozorilo';

  @override
  String get waveformBarsCount => 'Število stolpcev valovne oblike';

  @override
  String get webmNoEditTagsSupport => 'Format WEBM ne podpira urejanja oznak';

  @override
  String get week => 'Teden';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => 'Leto';

  @override
  String get yes => 'da';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return 'Vaše trenutno članstvo je $name';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Vaš vrstni red po meri bo izgubljen, ste prepričani?';

  @override
  String get youtube => 'Youtube';

  @override
  String get youtubeMusic => 'Youtube Music';

  @override
  String get youtubeSettingsSubtitle => 'Prilagodite izkušnjo Youtube';

  @override
  String get youtubeStyleMiniplayer => 'Mini predvajalnik v slogu Youtube';

  @override
  String get ytPreferNewComments => 'Raje nove komentarje, ko je mogoče';

  @override
  String get ytPreferNewCommentsSubtitle => 'Predpomnjena različica bo uporabljena le, ko ni povezave';
}
