// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Korean (`ko`).
class AppLocalizationsKo extends AppLocalizations {
  AppLocalizationsKo([String locale = 'ko']) : super(locale);

  @override
  String get about => '앱 정보';

  @override
  String get active => '활성화';

  @override
  String get add => '추가';

  @override
  String get addAccount => '계정 추가';

  @override
  String get addAll => '모두 추가';

  @override
  String get addAllAndRemoveOldOnes => '오래된 것 삭제하고 모두 추가';

  @override
  String get addAsANewPlaylist => '새 재생목록으로 추가';

  @override
  String get addAudioToLocalLibrary => '로컬 라이브러리에서 음악 추가';

  @override
  String get addFolder => '폴더 추가';

  @override
  String get addLanguage => '언어 추가';

  @override
  String get addLanguageSubtitle => '당신의 언어로 Namida 번역을 도와주세요';

  @override
  String get addLrcFile => 'LRC 파일 추가';

  @override
  String get addMoreFromThisAlbum => '이 앨범에서 대기열에 추가';

  @override
  String get addMoreFromThisArtist => '이 아티스트에서 대기열에 추가';

  @override
  String get addMoreFromThisFolder => '이 폴더에서 대기열에 추가';

  @override
  String addMoreFromToQueue({required String media}) {
    return '$media에서 추가 대기열에 추가';
  }

  @override
  String get addOnlyMissing => '누락된 것만 추가';

  @override
  String get addToFavourites => '즐겨찾기에 추가';

  @override
  String get addToPlaylist => '재생목록에 추가';

  @override
  String get addTracksAtTheBeginning => 'Add tracks at the beginning';

  @override
  String get added => '추가됨';

  @override
  String get advanced => '고급';

  @override
  String get advancedSettings => '고급 설정';

  @override
  String get advancedSettingsSubtitle => '고급 설정(건드리지 않는 것이 좋습니다)';

  @override
  String get alarm => '알람';

  @override
  String get album => '앨범';

  @override
  String get albumArtist => '앨범 아티스트';

  @override
  String get albumArtists => '앨범 아티스트';

  @override
  String get albumIdentifiers => '앨범 ID';

  @override
  String get albumThumbnailSizeInList => '앨범 썸네일 크기';

  @override
  String get albumTileCustomization => '앨범 타일 맞춤 설정';

  @override
  String get albums => '앨범';

  @override
  String get albumsCount => '앨범 수';

  @override
  String get all => '모두';

  @override
  String get allTime => '전체 기간';

  @override
  String get alreadyExists => 'Already Exists';

  @override
  String get always => '항상';

  @override
  String get alwaysAsk => '항상 물어보기';

  @override
  String get alwaysDim => 'Always Dim';

  @override
  String get alwaysExpandedSearchbar => '항상 확장된 검색창';

  @override
  String get alwaysRestore => '항상 복원';

  @override
  String get animatingThumbnailIntensity => '썸네일 애니메이션 크기';

  @override
  String get animatingThumbnailInversed => '애니메이션 반전';

  @override
  String get animatingThumbnailInversedSubtitle => '높음으로 설정하면 썸네일 크기가 작아짐';

  @override
  String get anotherProcessIsRunning => '다른 프로세스가 이미 실행 중입니다.';

  @override
  String get appIcon => 'App Icon';

  @override
  String get appVersion => 'App Version';

  @override
  String get artist => '아티스트';

  @override
  String get artists => '아티스트';

  @override
  String get artwork => '아트워크';

  @override
  String get artworkGestures => '아트웍 제스처';

  @override
  String get artworks => '아트워크';

  @override
  String get audio => '오디오';

  @override
  String get audioCache => '오디오 캐시';

  @override
  String get audioOnly => '오디오만';

  @override
  String get auto => '자동';

  @override
  String get autoBackupInterval => '자동 백업 간격';

  @override
  String get autoColoring => '자동 색상 지정';

  @override
  String get autoColoringSubtitle => '현재 아트웍에서 플레이어 색상 자동 선택';

  @override
  String get autoExtractTagsFromFilename => '파일명에서 자동 추출';

  @override
  String get autoExtractTitleAndArtistFromVideoTitle => '동영상 제목에서 제목과 아티스트 자동 추출';

  @override
  String get autoGenerated => '자동 생성';

  @override
  String get autoSkip => 'Auto Skip';

  @override
  String get autoSkipOnce => 'Auto Skip Once';

  @override
  String get autoStartRadio => '라디오 자동 시작';

  @override
  String get autoStartRadioSubtitle => '단일 트랙 재생 시 믹스 재생목록을 자동으로 추가합니다';

  @override
  String get automaticBackup => '자동 백업';

  @override
  String get automaticBackupSubtitle => '백업 위치에서 찾은 최신 백업 파일 자동 적용';

  @override
  String get backupAndRestore => '백업 & 복원';

  @override
  String get backupAndRestoreSubtitle => '데이터베이스 및 설정 백업';

  @override
  String get balanced => '균형';

  @override
  String get beta => '베타';

  @override
  String get betweenDates => '날짜 사이';

  @override
  String get bitrate => '비트 레이트';

  @override
  String get blacklist => '블랙리스트';

  @override
  String get borderRadiusMultiplier => '테두리 반경 배율';

  @override
  String get cache => '캐시';

  @override
  String get cancel => '취소';

  @override
  String get canceled => '취소됨';

  @override
  String get changed => '변경됨';

  @override
  String get changelog => '변경 내역';

  @override
  String get changelogSubtitle => 'See what\'s newly added/fixed inside Namida';

  @override
  String get channel => '채널';

  @override
  String get channels => '채널';

  @override
  String get check => '확인';

  @override
  String get checkForMore => '자세한 내용 확인';

  @override
  String get checkList => '목록 보기';

  @override
  String get choose => '선택';

  @override
  String get chooseWhatToClear => '지울 항목 선택';

  @override
  String get claim => '요청';

  @override
  String get clear => '지우기';

  @override
  String get clearAudioCache => '오디오 캐시 지우기';

  @override
  String get clearImageCache => '이미지 캐시 지우기';

  @override
  String get clearImageCacheWarning => '경고: 이미지가 없는 라이브러리가 생성되므로 이미지 캐시를 다시 생성할 때만 사용합니다.';

  @override
  String get clearTrackItem => '트랙 지우기';

  @override
  String clearTrackItemMultiple({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString개의 트랙 지우기',
    );
    return '$_temp0';
  }

  @override
  String get clearVideoCache => '동영상 캐시 지우기';

  @override
  String get clearVideoCacheNote => '삭제할 항목을 선택할 수 있습니다.';

  @override
  String get clock => '시계';

  @override
  String get colorPalette => '색상 팔레트';

  @override
  String get colorPaletteNote1 => '길게 눌러 색상 삭제';

  @override
  String get colorPaletteNote2 => '기본 색상으로 사용할 믹스를 누릅니다';

  @override
  String get colorPalettes => '색상 팔레트';

  @override
  String get comment => '댓글';

  @override
  String get comments => '댓글';

  @override
  String get composer => '작곡가';

  @override
  String get compress => '압축';

  @override
  String get compressImages => '이미지 압축';

  @override
  String get compressionPercentage => '압축률';

  @override
  String get configure => '구성';

  @override
  String get confirm => '승인';

  @override
  String get confirmRefresh => 'Confirm Refresh?';

  @override
  String get convertToM3UPlaylist => 'Convert to M3U Playlist';

  @override
  String get convertToNormalPlaylist => 'Convert to Normal Playlist';

  @override
  String get copiedArtwork => '아트웍 복사';

  @override
  String get copiedToClipboard => '클립보드에서 복사';

  @override
  String get copy => '복사';

  @override
  String get corruptedFile => '파일 분석 실패, 파일이 손상되었을 수 있음';

  @override
  String get couldntOpen => '열 수 없습니다 :(';

  @override
  String get couldntOpenYtLink => '이 트랙에 YouTube링크가 없습니다';

  @override
  String get couldntPlayFile => '재생할 수 없습니다';

  @override
  String get couldntRenamePlaylist => '재생목록의 이름을 변경할 수 없습니다';

  @override
  String get couldntSaveImage => '이미지를 저장할 수 없습니다';

  @override
  String countAlbumArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Album Artists',
      one: '$countString Album Artist',
    );
    return '$_temp0';
  }

  @override
  String countAlbums({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Albums',
      one: '$countString Album',
    );
    return '$_temp0';
  }

  @override
  String countArtists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Artists',
      one: '$countString Artist',
    );
    return '$_temp0';
  }

  @override
  String countComposers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Composers',
      one: '$countString Composer',
    );
    return '$_temp0';
  }

  @override
  String countDays({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Days',
      one: '$countString Day',
    );
    return '$_temp0';
  }

  @override
  String countFiles({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Files',
      one: '$countString File',
    );
    return '$_temp0';
  }

  @override
  String countFolders({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Folders',
      one: '$countString Folder',
    );
    return '$_temp0';
  }

  @override
  String countGenres({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Genres',
      one: '$countString Genre',
    );
    return '$_temp0';
  }

  @override
  String countMonths({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Months',
      one: '$countString Month',
    );
    return '$_temp0';
  }

  @override
  String countPlaylists({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Playlists',
      one: '$countString Playlist',
    );
    return '$_temp0';
  }

  @override
  String countSubscribers({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countSubscribersShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Subscribers',
      one: '$countString Subscriber',
    );
    return '$_temp0';
  }

  @override
  String countTracks({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Tracks',
      one: '$countString Track',
    );
    return '$_temp0';
  }

  @override
  String countVideos({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Videos',
      one: '$countString Video',
    );
    return '$_temp0';
  }

  @override
  String countViews({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String countViewsShort({required int count}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Views',
      one: '$countString View',
    );
    return '$_temp0';
  }

  @override
  String get country => '국가';

  @override
  String get coupon => 'Coupon';

  @override
  String get create => '생성';

  @override
  String get createBackup => '백업 생성';

  @override
  String get createNewPlaylist => '새 재생목록 만들기';

  @override
  String get createdBackupSuccessfully => '생성된 백업';

  @override
  String get createdBackupSuccessfullySub => '백업 파일 생성 성공';

  @override
  String get crossPlatformSync => 'Cross-Platform Sync';

  @override
  String get crossfadeDuration => '크로스페이드 시간';

  @override
  String crossfadeTriggerSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '종료 $secondsString초 전부터 자동으로 크로스페이드 시작',
    );
    return '$_temp0';
  }

  @override
  String get crossfadeTriggerSecondsDisabled => '크로스페이드를 자동으로 시작하지 않음';

  @override
  String get custom => '사용자 정의';

  @override
  String get customizations => '맞춤 설정';

  @override
  String get customizationsSubtitle => '플레이어를 커스터마이징하여 나만의 플레이어로 만들기';

  @override
  String dataIsProvidedByName({required String name}) {
    return 'Data is provided by: $name';
  }

  @override
  String get dataSaver => 'Data Saver';

  @override
  String get dataSaverMode => 'Data Saver Mode';

  @override
  String get database => '데이터베이스';

  @override
  String get date => '날짜';

  @override
  String get dateAdded => '추가된 날짜';

  @override
  String get dateCreated => '생성된 날짜';

  @override
  String get dateModified => '수정된 날짜';

  @override
  String get dateTimeFormat => '날짜 시간 형식';

  @override
  String get day => '일';

  @override
  String get days => '일';

  @override
  String get defaultBackupLocation => '기본 백업 위치';

  @override
  String get defaultColor => '기본 색상';

  @override
  String get defaultColorSubtitle => '플레이어에서 사용할 색상 설정';

  @override
  String get defaultDownloadLocation => '기본 다운로드 위치';

  @override
  String get defaultLabel => '기본';

  @override
  String get defaultLibraryTab => '기본 라이브러리 탭';

  @override
  String get delete => '삭제';

  @override
  String deleteFileCacheSubtitle({required int count, required String totalSizeText}) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$totalSizeText에 해당하는 $countString개의 파일을 삭제할까요?',
    );
    return '$_temp0';
  }

  @override
  String deleteNTracksFromStorage({required String numberText}) {
    return '저장소에서 $numberText개 영구 삭제';
  }

  @override
  String get deletePlaylist => '재생목록 삭제';

  @override
  String get deleteTempFiles => '임시파일 삭제';

  @override
  String get deleted => 'Deleted';

  @override
  String get description => '설명';

  @override
  String get developer => 'Developer';

  @override
  String get development => 'Development';

  @override
  String get didYouMean => '혹시';

  @override
  String get dimIntensity => '밝기';

  @override
  String dimMiniplayerAfterSeconds({required int seconds}) {
    final intl.NumberFormat secondsNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String secondsString = secondsNumberFormat.format(seconds);

    String _temp0 = intl.Intl.pluralLogic(
      seconds,
      locale: localeName,
      other: '$secondsString초 동안 조작하지 않으면 미니 플레이어가 어두워집니다',
    );
    return '$_temp0';
  }

  @override
  String get directoryDoesntExist => '디렉토리가 존재하지 않음';

  @override
  String get disable => 'Disable';

  @override
  String get disableAll => 'KO';

  @override
  String get disableReordering => '정렬 비활성화';

  @override
  String get disableSearchCleanup => '검색 정리 비활성화';

  @override
  String get discNumber => '디스크 번호';

  @override
  String get discNumberTotal => '디스크 총량';

  @override
  String get discover => 'Discover';

  @override
  String get dislike => '싫어요';

  @override
  String get dismissibleMiniplayer => '미니플레이어 해제 가능';

  @override
  String get displayActualPositionInsteadOfDifferenceWhileSeeking => 'Display actual position instead of difference while seeking';

  @override
  String get displayAlbumCardTopRightDate => '앨범 카드 우측 상단의 날짜';

  @override
  String get displayAlbumCardTopRightDateSubtitle => '앨범 카드 우측 상단에 앨범 날짜 표시';

  @override
  String get displayArtistBeforeTitle => '제목 앞에 아티스트 표시';

  @override
  String get displayArtworkOnLockscreen => '잠금화면에서 아트웍 표시';

  @override
  String get displayAudioInfoInMiniplayer => '오디오 정보 표시';

  @override
  String get displayFavButtonInNotification => '알림에 즐겨찾기 버튼 표시';

  @override
  String get displayFavButtonInNotificationSubtitle => '썸네일이 어긋날 수 있습니다.';

  @override
  String get displayFavouriteIconInTrackTile => '즐겨찾기 버튼 표시';

  @override
  String get displayRemainingDurationInsteadOfTotal => '총 시간이 아닌 남은 시간 표시';

  @override
  String get displayStopButtonInNotification => 'Display Stop Button in Notification';

  @override
  String get displayThirdItemInRowInTrackTile => '각 행에 세 번째 항목 표시';

  @override
  String get displayThirdRowInTrackTile => '세 번째 항목 표시';

  @override
  String get displayTrackNumberInAlbumPage => '앨범의 트랙 번호 표시';

  @override
  String get displayTrackNumberInAlbumPageSubtitle => '앨범에 트랙 번호 작은 박스 표시';

  @override
  String get doNothing => '아무것도 하지 않음';

  @override
  String get donate => 'Donate';

  @override
  String get donateSubtitle => 'If you think it deserves';

  @override
  String get done => '완료';

  @override
  String get dontAskAgain => '다시 묻지 않기';

  @override
  String get dontDim => 'Don\'t Dim';

  @override
  String get dontRestorePosition => '복원하지 않음';

  @override
  String get dontResume => '다시 시작하지 않음';

  @override
  String get doubleTapToToggleLyrics => '더블 탭으로 가사 전환';

  @override
  String get download => '다운로드';

  @override
  String get downloadingWillOverrideIt => '다운로드하면 덮어씁니다';

  @override
  String get downloads => '다운로드';

  @override
  String get downloadsMetadataTags => '메타데이터 태그 다운로드';

  @override
  String get downloadsMetadataTagsSubtitle => '기본적으로 동영상 정보에서 아티스트, 제목 및 앨범 추출';

  @override
  String get dragToSeek => '드래그해서 찾기';

  @override
  String get duckAudio => '볼륨 낮추기';

  @override
  String get duplicatedItemsAdding => '해당 항목은 이미 추가되어 있습니다';

  @override
  String get duplicatedTracks => '중복된 트랙';

  @override
  String get duration => '간격';

  @override
  String get edgeColorsSwitching => '가장자리 색상 전환';

  @override
  String get edit => '편집';

  @override
  String get editArtwork => '아트웍 편집';

  @override
  String get editTags => '태그 편집';

  @override
  String get email => '이메일';

  @override
  String get emptyNonMeaningfulTagFields => '비어있거나 의미 없는 값의 필드가 있는지 확인';

  @override
  String get emptyValue => '빈 값';

  @override
  String get enableArtworkCache => 'Enable Artwork Cache';

  @override
  String get enableArtworkCacheSubtitle => 'Faster loading and improved performance, but uses more storage';

  @override
  String get enableBlurEffect => '블러 효과 활성화';

  @override
  String get enableBottomNavBar => '하단 네비게이션 바 활성화';

  @override
  String get enableBottomNavBarSubtitle => '항목이 서랍에 계속 표시됨';

  @override
  String get enableClipboardMonitoring => '클립보드 모니터링 활성화';

  @override
  String get enableClipboardMonitoringSubtitle => '검색창에 링크나 텍스트를 바로 삽입할 수 있습니다';

  @override
  String get enableCrossfadeEffect => '크로스페이드 효과 사용';

  @override
  String get enableFadeEffectOnPlayPause => '재생/일시정지 시 페이드 효과 활성화';

  @override
  String get enableFoldersHierarchy => '폴더 계층구조 활성화';

  @override
  String get enableGlowEffect => '글로우 효과 활성화';

  @override
  String get enableM3uSync => 'M3U Sync 활성화';

  @override
  String get enableM3uSyncNote1 => 'M3U Sync를 사용하면 재생목록의 변경사항을 원본 M3U 파일에 반영할 수 있습니다';

  @override
  String enableM3uSyncNote2({required String playlistsBackupPath}) {
    return '문제가 발생하면 이 재생목록의 백업은 $playlistsBackupPath에 있습니다';
  }

  @override
  String get enableM3uSyncSubtitle => '거부하면, 재시작 시 이 재생 목록의 모든 변경사항이 손실됩니다';

  @override
  String get enableMiniplayerParticles => '움직이는 파티클 활성화';

  @override
  String get enableParallaxEffect => '시차 효과 활성화';

  @override
  String get enablePartyMode => '파티 모드 활성화';

  @override
  String get enablePartyModeSubtitle => '화려한 엣지 브리징 효과 적용';

  @override
  String get enablePictureInPicture => 'PIP 활성화';

  @override
  String get enableReordering => '정렬 활성화';

  @override
  String get enableReturnYoutubeDislike => 'Enable Return Youtube Dislike';

  @override
  String get enableSearchCleanup => '검색 정리 활성화';

  @override
  String get enableSearchCleanupSubtitle => '모든 기호와 공백은 무시됨';

  @override
  String get enableSponsorblock => 'Enable SponsorBlock';

  @override
  String get enableVideoPlayback => '동영상 재생 활성화';

  @override
  String get enterSymbol => '기호를 입력하세요';

  @override
  String get equalizer => '이퀄라이저';

  @override
  String get error => '오류';

  @override
  String get errorFetchingVideoList => 'Error fetching video list';

  @override
  String get errorPlayingTrack => '트랙 재생 중 오류가 발생했습니다';

  @override
  String get excludedFodlers => '제외할 폴더';

  @override
  String get exit => '종료';

  @override
  String get exitAppSubtitle => '다시 탭하면 종료';

  @override
  String get expandedMiniplayer => '확장된 미니 플레이어';

  @override
  String get exportAsM3u => 'M3U로 내보내기';

  @override
  String get extension => '확장';

  @override
  String get externalFiles => '외부 파일';

  @override
  String get extract => '추출';

  @override
  String get extractAllColorPalettes => '모든 색상 팔레트 추출';

  @override
  String extractAllColorPalettesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '나머지 $numberString를 추출할까요?',
    );
    return '$_temp0';
  }

  @override
  String get extractFeatArtist => '제목에서 feat. 아티스트 추출';

  @override
  String get extractFeatArtistSubtitle => '(feat. X) 및 (ft. X) 아티스트를 새로운 아티스트 항목으로 추출합니다.';

  @override
  String get extractingInfo => '정보 추출';

  @override
  String get extras => '추가 기능';

  @override
  String get extrasSubtitle => '경험을 향상시키기 위한 추가 설정';

  @override
  String get extreme => 'Extreme';

  @override
  String get failed => '실패';

  @override
  String get failedEdits => '편집 실패';

  @override
  String get favourites => '즐겨찾기';

  @override
  String get features => 'Features';

  @override
  String get fetching => '추출 중';

  @override
  String get fetchingOfAllVideos => '모든 동영상 가져오기';

  @override
  String get file => '파일';

  @override
  String get fileAlreadyExists => '파일이 이미 존재함';

  @override
  String get fileBasedServerWarning => 'Files will be temporarily downloaded for indexing, Make sure your connection is stable.\nWi-Fi is recommended to avoid high data usage.';

  @override
  String get fileName => '파일명';

  @override
  String get fileNameWoExt => '확장자 없는 파일명';

  @override
  String get filenameShouldntStartWith => '파일명은 다음과 같이 시작하면 안 됨';

  @override
  String get files => '파일';

  @override
  String get filler => 'Filler';

  @override
  String get filterAlbums => '앨범 필터링';

  @override
  String get filterArtists => '아티스트 필터링';

  @override
  String get filterGenres => '장르 필터링';

  @override
  String get filterPlaylists => '재생목록 필터링';

  @override
  String get filterTracks => '트랙 필터링';

  @override
  String get filterTracksBy => '검색 목록의 트랙을 필터링';

  @override
  String get filtered => 'Filtered';

  @override
  String get filteredBySizeAndDuration => '크기와 길이로 필터링된 트랙';

  @override
  String get finished => '완료되었습니다';

  @override
  String get finishedUpdatingLibrary => '라이브러리 업데이트가 완료되었습니다';

  @override
  String get firstListen => '먼저 듣기';

  @override
  String get fixYtdlpBigThumbnailSize => 'yt-dlp의 큰 썸네일 크기 수정';

  @override
  String get floatingActionButton => '플로팅 액션 버튼';

  @override
  String get folder => '폴더';

  @override
  String get folderName => '폴더명';

  @override
  String get folders => '폴더';

  @override
  String get fontScale => '폰트 크기';

  @override
  String get forceMiniplayerFollowTrackColors => '미니 플레이어를 트랙 색상에 맞추기';

  @override
  String get forceSquaredAlbumThumbnail => '앨범 썸네일을 정사각형으로 강제 설정';

  @override
  String get forceSquaredThumbnailNote => '썸네일의 크기가 앨범 타일의 높이와 같지 않기 때문에 강제로 정사각형으로 만들면 기대한 효과를 얻지 못할 수 있습니다. 같은 크기로 설정하시겠습니까?';

  @override
  String get forceSquaredTrackThumbnail => '트랙의 썸네일을 강제로 정사각형으로 만들기';

  @override
  String get forceStopColorPaletteGeneration => '색상 팔레트 추출을 강제로 중지하시겠습니까? 나중에 계속할 수 있습니다';

  @override
  String get format => '형식';

  @override
  String get fullscreen => 'Fullscreen';

  @override
  String get gaplessPlayback => 'Gapless Playback';

  @override
  String get generate => '생성';

  @override
  String get generateFromDates => '시간 제한';

  @override
  String get generateFromDatesSubtitle => '특정 시간대에 들은 트랙을 생성';

  @override
  String get generateRandomPlaylist => '랜덤 재생목록 생성';

  @override
  String get genre => '장르';

  @override
  String get genres => '장르';

  @override
  String get goToAlbum => '앨범으로 이동';

  @override
  String get goToArtist => '아티스트로 이동';

  @override
  String get goToChannel => '채널로 이동';

  @override
  String get goToFolder => '폴더로 이동';

  @override
  String get goodLooking => '좋아요';

  @override
  String get grantStoragePermission => '저장소 권한 부여';

  @override
  String get group => '그룹';

  @override
  String get groupArtworksByAlbum => '앨범별로 아트웍을 그룹화';

  @override
  String get guide => '가이드';

  @override
  String get hapticFeedback => 'Haptic Feedback';

  @override
  String get heightOfAlbumTile => '앨범 타일 높이';

  @override
  String get heightOfTrackTile => '트랙 타일 높이';

  @override
  String get hideSkipButtonAfter => 'Hide skip button after';

  @override
  String get highMatches => '높은 일치도';

  @override
  String get highPerformance => '고성능';

  @override
  String get highlight => 'Highlight';

  @override
  String get history => '히스토리';

  @override
  String get historyImportMissingEntriesNote => '이 항목들은 라이브러리에서 찾을 수 없습니다. 만약 존재한다면 수동으로 추가해 보세요';

  @override
  String historyListensReplaceWarning({required int listensCount, required String newTrackInfo, required String oldTrackInfo}) {
    final intl.NumberFormat listensCountNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String listensCountString = listensCountNumberFormat.format(listensCount);

    String _temp0 = intl.Intl.pluralLogic(
      listensCount,
      locale: localeName,
      other: '$listensCountString 건을 들었습니다. $oldTrackInfo는 $newTrackInfo로 대체됩니다. 대체할까요?',
    );
    return '$_temp0';
  }

  @override
  String get home => '홈';

  @override
  String get hook => 'Hook';

  @override
  String get host => 'Host';

  @override
  String get hourFormat12 => '12시간 표기';

  @override
  String get hours => '시간';

  @override
  String get iReadAndAgree => '읽고 동의 합니다';

  @override
  String get ifNotPlaying => '중지 중일 경우';

  @override
  String get ignoreBatteryOptimizationsSubtitle => '시스템의 절전 기능에 앱이 등록되어 있을 경우 다운로드 속도가 느려질 수 있습니다';

  @override
  String get ignoreCommonPrefixesWhileSorting => 'Ignore common prefixes while sorting';

  @override
  String get ignores => '무시';

  @override
  String get imageSource => 'Image source';

  @override
  String get immersiveMode => '몰입형 모드';

  @override
  String get immersiveModeSubtitle => '미니플레이어가 펼쳐져 있는 동안 상태 표시줄과 내비게이션 바를 숨김';

  @override
  String get import => '가져오기';

  @override
  String get importAll => '모두 가져오기';

  @override
  String get importLastFmHistory => 'LastFm 시청 기록 가져오기';

  @override
  String importLastFmHistoryGuide({required String lastfmCsvLink}) {
    return '1. $lastfmCsvLink로 이동합니다\n\n2. 사용자 이름을 입력하고 csv 파일을 가져와 다운로드합니다.\n\n3. 다음 화면에서 파일을 선택합니다.';
  }

  @override
  String get importTimeRange => '져오기 시간 범위';

  @override
  String get importYoutubeHistory => 'Youtube 시청 기록 가져오기';

  @override
  String importYoutubeHistoryGuide({required String takeoutLink}) {
    return '1. $takeoutLink로 이동합니다.\n\n2. 「여러 형식」을 누르고 「기록」옆에 있는 「JSON」을 선택합니다.\n\n3. 「모든 Youtube 데이터 포함됨」을 눌러 모두 선택을 해제하고 시청 기록만 선택합니다.\n\n4. 내보내기, 다운로드, 압축 해제를 생성합니다.\n\n5. 다음 화면에서 「시청 기록.json」을 선택합니다.';
  }

  @override
  String importedNChannelsSuccessfully({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString개의 채널을 성공적으로 가져왔습니다',
    );
    return '$_temp0';
  }

  @override
  String importedNPlaylistsSuccessfully({required int number, required String numberText}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberText개의 재생목록을 성공적으로 가져왔습니다',
    );
    return '$_temp0';
  }

  @override
  String get includeVideos => 'Include videos';

  @override
  String get indexRefreshRequired => '이 옵션을 변경한 후 새로고침';

  @override
  String get indexer => '인덱싱';

  @override
  String get indexerNote => '참고: 작품 수가 불완전합니다. 중복되거나 누락된 작품이 있습니다';

  @override
  String get indexerSubtitle => '음악 라이브러리 관리';

  @override
  String get infinityQueueOnNextPrev => '다음/이전 무한 대기열';

  @override
  String get infinityQueueOnNextPrevSubtitle => '마지막 항목 재생 중 다음을 누르면 첫 번째 항목으로 이동합니다. 그 반대의 경우도 마찬가지입니다';

  @override
  String get info => '정보';

  @override
  String get inserted => '삽입됨';

  @override
  String get instantlyApplies => '즉시 적용';

  @override
  String get interactionReminder => 'Interaction Reminder';

  @override
  String get intro => 'Intro';

  @override
  String get invertSelection => '선택 반전';

  @override
  String get issues => 'Issues';

  @override
  String get item => '항목';

  @override
  String get jump => '점프';

  @override
  String get jumpToDay => '날짜로 점프';

  @override
  String get jumpToFirstTrackAfterQueueFinish => '대기열 종료 후 첫 번째 트랙으로 점프';

  @override
  String get keepCachedVersions => '캐시된 버전 유지';

  @override
  String get keepFileDates => '파일 날짜 유지';

  @override
  String get keepScreenAwakeMiniplayerExpanded => '미니 플레이어가 확장되었습니다';

  @override
  String get keepScreenAwakeMiniplayerExpandedAndVideo => '미니 플레이어가 확장되고 동영상 재생 중';

  @override
  String get keepScreenAwakeNone => '화면이 켜진 상태로 유지되지 않음';

  @override
  String get keepScreenAwakeWhen => '화면이 켜진 상태로 유지';

  @override
  String get killPlayerAfterDismissingApp => '앱 종료 후 플레이어 강제 종료';

  @override
  String get language => '언어';

  @override
  String get learnMore => 'Learn more';

  @override
  String get leftAction => 'Left Action';

  @override
  String get legacyAuthentication => 'Legacy Authentication';

  @override
  String get libraryTabs => '라이브러리 탭';

  @override
  String get libraryTabsReorder => '활성화된 탭을 정렬할 수 있습니다.';

  @override
  String get license => 'License';

  @override
  String get licenseSubtitle => 'Licenses & Agreements Used by Namida';

  @override
  String get like => '좋아요';

  @override
  String get liked => '좋아요';

  @override
  String get link => '링크';

  @override
  String get listOfFolders => '폴더 목록';

  @override
  String get loadAll => '모두 불러오기';

  @override
  String get loadingFile => '파일 불러오기';

  @override
  String get local => '로컬';

  @override
  String get localVideoMatching => '로컬 영상 검색';

  @override
  String get login => 'Login';

  @override
  String get longPressAction => 'Long-Press Action';

  @override
  String get longPressTheLyricsToEnterFullscreen => 'Long press the lyrics to enter fullscreen';

  @override
  String get lostMemories => '한동안 듣지 않음';

  @override
  String lostMemoriesSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$numberString년 전 이맘때',
    );
    return '$_temp0';
  }

  @override
  String get lostPartners => 'Lost Partners';

  @override
  String get loudnessEnhancer => '볼륨 부스터';

  @override
  String get lyricist => '작사';

  @override
  String get lyrics => '가사';

  @override
  String get lyricsSource => '가사 소스';

  @override
  String get m3uPlaylist => 'M3U 재생목록';

  @override
  String get makeYourFirstListen => '먼저 들어보세요!';

  @override
  String get manage => '관리';

  @override
  String get manageYourAccounts => '계정 관리';

  @override
  String get manualBackup => '설명서';

  @override
  String get manualBackupSubtitle => '특정 파일 선택';

  @override
  String get markAsRead => '읽은 것으로 표시';

  @override
  String get matchAllTracks => '모든 트랙과 일치';

  @override
  String get matchAllTracksNote => '라이브러리의 모든 트랙을 검사하기 때문에 매칭 속도에 영향을 줄 수 있음';

  @override
  String get matchingType => '일치 유형';

  @override
  String get maxAudioCacheSize => '최대 오디오 캐시 크기';

  @override
  String get maxImageCacheSize => '최대 이미지 캐시 크기';

  @override
  String get maxVideoCacheSize => '최대 동영상 캐시 크기';

  @override
  String get maximum => '최대';

  @override
  String get mediaStoreIsEnabledThisWillHaveNoEffect => 'Media Store is enabled, this will have no effect';

  @override
  String get medium => 'Medium';

  @override
  String get membershipCode => '멤버십 코드';

  @override
  String get membershipCodeSentToEmail => '코드가 메일로 전송되었습니다';

  @override
  String get membershipDidntChange => '멤버십이 변경되지 않았습니다';

  @override
  String get membershipEnjoyNew => '새로운 멤버십을 즐기세요';

  @override
  String get membershipFreeCoupon => '무료 쿠폰';

  @override
  String get membershipManage => '멤버십 관리';

  @override
  String get membershipNoSubscriptionsFoundForUser => '이 사용자의 구독을 찾을 수 없습니다';

  @override
  String get membershipSignInToPatreonAccount => '후원자 계정 로그인';

  @override
  String get membershipUnknown => '알 수 없는 멤버십';

  @override
  String membershipYouNeedMembershipOfToAddMultipleAccounts({required String name1, required String name2}) {
    return '여러 계정을 추가하려면 $name1 또는 $name2 멤버십이 필요합니다';
  }

  @override
  String get merge => '병합';

  @override
  String get metadataCache => '메타데이터 캐시';

  @override
  String get metadataEditFailed => '메타데이터 편집 실패';

  @override
  String get metadataReadFailed => '메타데이터 읽기 실패';

  @override
  String get minFileDuration => '최소 트랙 지속시간';

  @override
  String get minFileSize => '최소 파일 크기';

  @override
  String get minTrackDurationToRestoreLastPosition => '마지막 재생 위치를 복원하기 위한 최소 트랙 지속시간';

  @override
  String get minValueCantBeMoreThanMax => '최솟값은 최댓값을 초과할 수 없습니다';

  @override
  String get minValueToCountTrackListen => '다음 길이까지 재생하면 1회 카운트됩니다: ';

  @override
  String get minimizedMiniplayer => '최소화된 미니플레이어';

  @override
  String get minimum => '최소화';

  @override
  String get minimumOneFolderSubtitle => '최소 1개의 폴더가 필요합니다. 이 폴더를 삭제하려면 새 폴더를 추가하세요';

  @override
  String get minimumOneItem => '항목을 삭제할 수 없습니다';

  @override
  String minimumOneItemSubtitle({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '최소 $numberString개의 항목이 남아 있어야 합니다',
    );
    return '$_temp0';
  }

  @override
  String get minimumSegmentDuration => 'Minimum Segment Duration';

  @override
  String get miniplayerCustomization => '미니플레이어 맞춤 설정';

  @override
  String get minutes => '분';

  @override
  String get missingEntries => '누락된 항목';

  @override
  String get missingTracks => '누락된 트랙';

  @override
  String get mix => '믹스';

  @override
  String get mixPlaylistGeneratedByYoutube => 'YouTube에서 생성한 믹스 재생 목록';

  @override
  String get mixes => '믹스';

  @override
  String get mobile => 'Mobile';

  @override
  String get month => '월';

  @override
  String get months => '월';

  @override
  String get mood => '분위기';

  @override
  String get moods => '분위기';

  @override
  String get more => '더';

  @override
  String get mostPlayed => '가장 많이 재생된';

  @override
  String get multipleTracksTagsEditNote => '이 트랙들을 편집하려고 합니다.\n변경되지 않은 필드는 그대로 유지됩니다.';

  @override
  String get musicOfftopic => 'Music Offtopic';

  @override
  String get name => '이름';

  @override
  String get nameContainsBadCharacter => '이름에 부적절한 문자가 포함되어 있습니다';

  @override
  String get never => '한 번도';

  @override
  String get newDirectory => '새 디렉토리';

  @override
  String get newLabel => 'New';

  @override
  String get newTracksAdd => '트랙 추가';

  @override
  String get newTracksMoods => '분위기';

  @override
  String get newTracksMoodsSubtitle => '기존 분위기에 따라 트랙 생성';

  @override
  String get newTracksRandom => '랜덤';

  @override
  String get newTracksRandomSubtitle => '라이브러리에서 무작위로 트랙을 선택';

  @override
  String get newTracksRatings => '평가';

  @override
  String get newTracksRatingsSubtitle => '특정 등급의 트랙을 생성';

  @override
  String get newTracksRecommended => '추천';

  @override
  String newTracksRecommendedSubtitle({required String currentTrack}) {
    return '$currentTrack에서 자주 듣는 트랙을 생성합니다';
  }

  @override
  String get newTracksSimilarrReleaseDate => '비슷한 발매일';

  @override
  String newTracksSimilarrReleaseDateSubtitle({required String currentTrack}) {
    return '$currentTrack과 비슷한 시기에 발매된 트랙을 생성합니다';
  }

  @override
  String get newTracksUnknownYear => '트랙의 연도를 알 수 없음';

  @override
  String get newest => '최신';

  @override
  String get next => '다음';

  @override
  String get no => '아니오';

  @override
  String get noChangesFound => '변경사항을 찾지 못했습니다.';

  @override
  String get noEnoughTracks => '트랙이 충분하지 않습니다..';

  @override
  String get noExcludedFolders => '제외된 폴더가 없습니다';

  @override
  String get noFolderChosen => '폴더가 선택되지 않았습니다';

  @override
  String get noMoodsAvailable => '사용 가능한 분위기가 없습니다';

  @override
  String get noNetworkAvailableToFetchData => '연결 가능한 네트워크가 없습니다';

  @override
  String get noTracksFound => '트랙을 찾지 못했습니다';

  @override
  String get noTracksFoundBetweenDates => '이 시간대에 트랙이 없습니다.';

  @override
  String get noTracksFoundInDirectory => '이 디렉토리에 트랙이 없습니다';

  @override
  String get noTracksInHistory => '기록에 충분한 트랙이 없습니다';

  @override
  String get nonActive => '비활성화';

  @override
  String get nonFavourites => '즐겨찾기가 아님';

  @override
  String get none => '없음';

  @override
  String get normalizeAudio => '오디오 정규화';

  @override
  String get normalizeAudioSubtitle => '재생 게인 태그 또는 YouTube에서 제공한 정보를 읽어 볼륨을 정규화합니다';

  @override
  String get notAvailableForYourDevice => 'Not Available for your Device';

  @override
  String get notSupportedForNetworkFiles => 'Not Supported for Network Files';

  @override
  String get notSupportedForVideoFiles => 'Not Supported for Video Files';

  @override
  String get note => '노트';

  @override
  String get notification => '알림';

  @override
  String get notifications => '알림';

  @override
  String get numberOfTracks => '트랙 수';

  @override
  String get ofLabel => '의';

  @override
  String get offlineSearch => '오프라인 검색';

  @override
  String get offset => '오프셋';

  @override
  String get oldDirectory => '오래된 디렉토리';

  @override
  String get oldDirectoryStillHasTracks => '오래된 디렉토리에 아직 트랙이 몇 개 남아있는데 괜찮습니까?';

  @override
  String get oldestWatch => '가장 예전에 본';

  @override
  String get onDeviceConnect => 'On Device Connect';

  @override
  String get onInterruption => '중단 시';

  @override
  String get onNotificationTap => '알림 탭 시';

  @override
  String get onOpeningYoutubeLink => 'YouTube 링크 열 때';

  @override
  String get onSwiping => '스와이프 중일 때';

  @override
  String get onVolumeZero => '볼륨 0일 때';

  @override
  String get ongoing => '진행 중';

  @override
  String get open => '열기';

  @override
  String get openApp => '앱 열기';

  @override
  String get openInFileExplorer => 'Open in File Explorer';

  @override
  String get openInYoutubeView => 'YouTube에서 열기';

  @override
  String get openMiniplayer => '미니플레이어에서 열기';

  @override
  String get openQueue => '대기열 열기';

  @override
  String get openYoutubeLink => 'YouTube 링크 열기';

  @override
  String operationRequiresAccount({required String name}) {
    return '$name을 실행하려면 계정이 필요합니다. 계속하려면 로그인하세요';
  }

  @override
  String operationRequiresMembership({required String name, required String operation}) {
    return '$operation은 최소한 $name 멤버십 가입이 필요합니다';
  }

  @override
  String get or => '또는';

  @override
  String get others => '기타';

  @override
  String get output => '출력';

  @override
  String get outro => 'Outro';

  @override
  String get overrideOldFilesInTheSameFolder => '같은 폴더에 있는 오래된 파일 덮어쓰기';

  @override
  String get palette => '팔레트';

  @override
  String get paletteMix => '믹스';

  @override
  String get paletteNewMix => '새로운 믹스';

  @override
  String get paletteSelectedMix => '선택된 믹스';

  @override
  String get parallelDownloads => '다중 다운로드';

  @override
  String get parsed => '구문 분석 완료';

  @override
  String get password => 'Password';

  @override
  String get path => '파일 전체 경로';

  @override
  String get pause => '일시정지';

  @override
  String get pauseFadeDuration => '일시정지시 페이드 길이';

  @override
  String get pausePlayback => '재생 일시정지';

  @override
  String get percentage => '퍼센트';

  @override
  String get performanceMode => '성능 모드';

  @override
  String get performanceNote => '성능에 영향을 줄 수 있음';

  @override
  String get personalized => '개인화';

  @override
  String get personalizedRelatedVideos => '개인화된 관련 동영상';

  @override
  String get personalizedRelatedVideosSubtitle => '이 기능을 비활성화하면 데이터 사용량이 증가합니다';

  @override
  String get pickColorsFromDeviceWallpaper => '기기의 배경화면에서 색상 선택';

  @override
  String get pickFromStorage => '저장소에서 선택';

  @override
  String get pinned => '핀 고정';

  @override
  String get pitch => '피치';

  @override
  String get plain => '일반 텍스트';

  @override
  String get play => '재생';

  @override
  String get playAfter => '나중에 재생';

  @override
  String get playAfterNextPrev => '다음/이전 자동재생';

  @override
  String get playAll => '모두 재생';

  @override
  String get playFadeDuration => '재생 시 페이드 길이';

  @override
  String get playLast => '마지막 재생';

  @override
  String get playNext => '다음 재생';

  @override
  String get playbackSetting => '재생';

  @override
  String get playbackSettingSubtitle => '오디오 버튼을 길게 누르면 플레이어에서 바로 접근 가능';

  @override
  String get playlist => '재생목록';

  @override
  String get playlists => '재생목록';

  @override
  String get playlistsImportM3uNative => '이것은 Namida에서만 사용할 M3U 플레이리스트를 가져옵니다. 마이그레이션 중인 경우에만 사용하세요';

  @override
  String get playlistsImportM3uSynced => '인덱서 폴더에서 M3U 플레이리스트를 자동으로 가져오고, 원본 M3U 파일과 동기화 상태를 유지합니다. 다른 앱에서 플레이리스트에 접근하거나 수정하는 경우 활성화하세요';

  @override
  String get playlistsImportM3uSyncedAutoImport => 'M3U 재생목록 자동 가져오기';

  @override
  String get pleaseEnterADifferentName => '이 이름은 이미 존재합니다 :(\n다른 멋진 이름을 시도해 보세요';

  @override
  String get pleaseEnterALink => '링크를 입력하세요';

  @override
  String get pleaseEnterALinkSubtitle => '어...이거 YouTube 링크인가요?';

  @override
  String get pleaseEnterAName => '이름을 입력하세요';

  @override
  String get port => 'Port';

  @override
  String get preventDuplicatedTracks => '트랙 중복 방지';

  @override
  String get preventDuplicatedTracksSubtitle => '파일명을 사용하여 트랙을 고유하게 식별';

  @override
  String get preview => '미리보기';

  @override
  String get previous => 'Previous';

  @override
  String get previousButtonReplays => '미리보기 버튼으로 재생';

  @override
  String get previousButtonReplaysSubtitle => '현재 위치가 검색 시간 이상일 때 눌려진 경우';

  @override
  String get prioritizeEmbeddedLyrics => '내장된 가사 우선';

  @override
  String get priority => 'Priority';

  @override
  String get private => '비공개';

  @override
  String get progress => '진행';

  @override
  String get promptToChangeTrackPath => '일반적으로 이것은 namida 외부에서 파일을 삭제/이동/이름을 변경했을 때 발생합니다. 현재 경로를 업데이트 하시겠습니까?';

  @override
  String get public => '공개';

  @override
  String get queue => '대기열';

  @override
  String get queues => '대기열';

  @override
  String get random => '랜덤';

  @override
  String get randomPicks => '랜덤 선택';

  @override
  String get rating => '평가';

  @override
  String get reIndex => '재인덱스';

  @override
  String get reIndexSubtitle => '음악 라이브러리 재구성';

  @override
  String get reIndexWarning => '이 프로세스는 라이브러리의 크기에 따라 다소 시간이 걸릴 수 있습니다.\n\n아트웍은 존재하는 한 재인덱싱되지 않습니다';

  @override
  String get recentAlbums => '최근 앨범';

  @override
  String get recentArtists => '최근 아티스트';

  @override
  String get recentListens => '최근 청취';

  @override
  String get recentQueues => 'Recent Queues';

  @override
  String get recentlyAdded => '최근 추가됨';

  @override
  String get recordLabel => '음반사';

  @override
  String get refresh => '새로 고침';

  @override
  String get refreshLibrary => '라이브러리 새로 고침';

  @override
  String get refreshLibrarySubtitle => '새로 추가되거나 삭제된 음악 확인';

  @override
  String get refreshOnStartup => '시작 시 새로 고침';

  @override
  String get relatedVideos => '관련 동영상';

  @override
  String get rememberAudioOnlyMode => '오디오 전용 모드 저장';

  @override
  String get remixer => '리믹서';

  @override
  String get remove => '삭제';

  @override
  String get removeDuplicates => '중복 삭제';

  @override
  String get removeFromFavourites => '즐겨찾기에서 삭제';

  @override
  String get removeFromLibrary => '라이브러리에서 삭제';

  @override
  String get removeFromPlaylist => '재생목록에서 삭제';

  @override
  String get removeQueue => '대기열에서 삭제';

  @override
  String get removeSourceFromHistory => '기록에서 소스 삭제';

  @override
  String get removeWhitespaces => '공백 제거';

  @override
  String get removed => '삭제 완료';

  @override
  String get rename => '이름 변경';

  @override
  String get renamePlaylist => '재생목록 이름 변경';

  @override
  String get reorderable => '정렬 가능';

  @override
  String repeatForNTimes({required int number}) {
    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '$number회 반복',
    );
    return '$_temp0';
  }

  @override
  String get repeatMode => 'Repeat mode';

  @override
  String get repeatModeAll => '모든 대기열 반복';

  @override
  String get repeatModeNone => '마지막 트랙에서 정지';

  @override
  String get repeatModeOne => '현재 트랙 반복';

  @override
  String get replaceAllListensWithAnotherTrack => '이 트랙의 모든 청취 기록을 다른 트랙으로 대체';

  @override
  String get replies => '답장';

  @override
  String get reply => '답장';

  @override
  String get requiresClearingImageCacheAndReIndexing => '이미지 캐시 지우기 및 재인덱싱이 필요합니다';

  @override
  String get rescanVideos => '동영상 다시 스캔';

  @override
  String get resetBrightness => '밝기 재설정';

  @override
  String get resetToDefault => '기본값';

  @override
  String get respectNoMedia => '.nomedia 무시';

  @override
  String get respectNoMediaSubtitle => '.nomedia 폴더를 포함하지 않음';

  @override
  String get restart => '재시작';

  @override
  String get restoreBackup => '백업 복원';

  @override
  String get restoreDefaults => '기본값으로 복원';

  @override
  String get restoredBackupSuccessfully => '복원된 백업';

  @override
  String get restoredBackupSuccessfullySub => '백업 파일이 성공적으로 복원되었습니다';

  @override
  String get resume => '다시 시작';

  @override
  String get resumeIfWasInterrupted => '중단으로 인해 일시 정지된 경우 다시 시작';

  @override
  String get resumeIfWasPausedByDeviceDisconnect => 'Resume if was paused by device disconnect';

  @override
  String get resumeIfWasPausedByVolume => '볼륨에 의해 일시 정지된 경우 다시 시작';

  @override
  String resumeIfWasPausedForLessThanNMin({required int number}) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.decimalPattern(localeName);
    final String numberString = numberNumberFormat.format(number);

    String _temp0 = intl.Intl.pluralLogic(
      number,
      locale: localeName,
      other: '일시정지가 $numberString분 미만인 경우 다시 시작',
    );
    return '$_temp0';
  }

  @override
  String get returnYoutubeDislike => 'Return Youtube Dislike';

  @override
  String get reverseOrder => '역순';

  @override
  String get rightAction => 'Right Action';

  @override
  String get ringtone => '벨소리';

  @override
  String get sameDirectoryOnly => '같은 디렉토리만';

  @override
  String get sample => 'Sample';

  @override
  String get sampleRate => '샘플 속도';

  @override
  String get save => '저장';

  @override
  String get saveToLibrary => '라이브러리에 저장';

  @override
  String get savedIn => '저장 위치';

  @override
  String get scaleMultiplier => '스케일 배율';

  @override
  String get search => '검색';

  @override
  String get searchYoutube => 'YouTube에서 검색';

  @override
  String get seconds => '초';

  @override
  String seeProjectCodeOnSite({required String site}) {
    return 'See Project Code on $site';
  }

  @override
  String get seekDuration => '탐색 간격';

  @override
  String get seekDurationInfo => '현재 시간을 누르면 되감기, 총 시간을 누르면 빨리 감기';

  @override
  String get seekbar => '탐색바';

  @override
  String get selectAll => '모두 선택';

  @override
  String get selectFilesAlreadyInLocalLibrary => 'Select files already in local library';

  @override
  String get selectedTracks => '선택된 트랙';

  @override
  String get selfPromotion => 'Self Promotion';

  @override
  String get semitones => 'Semitones';

  @override
  String get separatorsBlacklistSubtitle => '이러한 단어는 분할되지 않습니다';

  @override
  String get separatorsMessage => '단어 전체에 포함되는 문자/기호(예: x 또는 ft.)를 사용하는 경우를 제외하고는 공백을 삽입할 필요가 없습니다';

  @override
  String get serverAddress => 'Server Address';

  @override
  String get setAs => '로 설정';

  @override
  String get setAsDefault => '기본값으로 설정';

  @override
  String get setFileLastModifiedAsVideoUploadDate => '파일의 마지막 업데이트 날짜를 동영상 업로드 날짜로 설정';

  @override
  String get setMonoAudio => 'Set Mono Audio';

  @override
  String get setMoods => '분위기 설정';

  @override
  String get setMoodsSubtitle => '구분은 쉼표(,)를 사용하세요';

  @override
  String get setRating => '평점 설정';

  @override
  String get setTags => '태그 설정';

  @override
  String get setYoutubeLink => 'YouTube링크 설정';

  @override
  String get settings => '설정';

  @override
  String get setupFirstStartup => '초기 시작시 설정';

  @override
  String get share => '공유';

  @override
  String get shareLogs => 'Share Logs';

  @override
  String get shortcuts => 'Shortcuts';

  @override
  String get shouldDuck => '볼륨을 낮춰야 함';

  @override
  String get shouldDuckNote => '볼륨을 낮춰야 함을 나타냅니다. 예: 알림';

  @override
  String get shouldPause => '일시정지 해야 함';

  @override
  String get shouldPauseNote => '재생이 일시 정지되었음을 나타냅니다. 예: 통화';

  @override
  String get showAll => 'Show All';

  @override
  String get showChannelWatermarkInFullscreen => '전체화면에서 채널의 워터마크 표시';

  @override
  String get showFailedOnly => 'Show Failed only';

  @override
  String get showHideUnknownFields => '알 수 없는 필드 표시/숨기기';

  @override
  String get showInSeekbar => 'Show in Seekbar';

  @override
  String get showMixPlaylistsIn => '믹스 목록 표시';

  @override
  String get showMore => '더 보기';

  @override
  String get showShortVideosIn => '짧은 동영상 보기';

  @override
  String get showSkipButton => 'Show Skip Button';

  @override
  String get showVideoEndcards => '동영상의 엔드카드 표시';

  @override
  String get showWebm => 'WemM 보기';

  @override
  String get shuffle => '섞기';

  @override
  String get shuffleAll => '모두 섞기';

  @override
  String get shuffleNext => '다음 섞기';

  @override
  String get signIn => '로그인';

  @override
  String get signInCanceled => '로그인이 취소되었습니다';

  @override
  String get signInFailed => '로그인 실패';

  @override
  String get signInToYourAccount => '계정에 로그인';

  @override
  String get signInYouDontHaveAccount => '로그인한 계정이 없습니다';

  @override
  String get signInYouNeedAccountToViewPage => '이 페이지를 보려면 계정이 필요합니다';

  @override
  String get signOut => '로그아웃';

  @override
  String signOutFromName({required String name}) {
    return '$name에서 로그아웃';
  }

  @override
  String get signingInAllowsBasicUsage => '로그인하면 기본 기능을 사용할 수 있습니다';

  @override
  String get signingInAllowsBasicUsageSubtitle => 'Patreon 또는 쿠폰을 사용하여 얼리 액세스 받기';

  @override
  String get similarDiscoverDate => 'Similar Discover Date';

  @override
  String similarDiscoverDateSubtitle({required String currentTrack}) {
    return 'Generate tracks that were discovered around the same time as $currentTrack';
  }

  @override
  String get similarTimeRange => 'Similar Time Range';

  @override
  String similarTimeRangeSubtitle({required String currentTrack}) {
    return 'Generate tracks you listened to around the same time as $currentTrack';
  }

  @override
  String get singles => 'Singles';

  @override
  String get size => '크기';

  @override
  String get skip => '건너띄기';

  @override
  String get skipCountTracking => 'Skip Count Tracking';

  @override
  String get skipSilence => '무음 건너띄기';

  @override
  String get skipSponsorSegmentsInVideos => 'Skip Sponsor Segments in Videos';

  @override
  String get sleepAfter => '나중에 일시 정지';

  @override
  String get sleepTimer => '취침 타이머';

  @override
  String get socials => 'Socials';

  @override
  String get socialsSubtitle => 'Join us on our platforms for Updates, Tips, Discussion & Ideas';

  @override
  String get someWebServersRequireAuthentication => 'Some web servers require authentication. Please update credentials to maintain access to your library.';

  @override
  String get sortBy => '정렬';

  @override
  String get source => '소스';

  @override
  String get speed => '속도';

  @override
  String get sponsor => 'Sponsor';

  @override
  String get sponsorblock => 'SponsorBlock';

  @override
  String get sponsorblockLeaderboard => 'SponsorBlock Leaderboard';

  @override
  String get staggeredAlbumGridView => '앨범 그리드 보기';

  @override
  String get start => '시작';

  @override
  String get stats => '통계';

  @override
  String get statsSubtitle => '라이브러리 정보';

  @override
  String get stop => '중지';

  @override
  String get stopAfterThisTrack => '이 트랙 이후 중지';

  @override
  String get stopAfterThisVideo => '이 동영상 이후 중지';

  @override
  String get storagePermissionDenied => '권한이 거부되었습니다';

  @override
  String get storagePermissionDeniedSubtitle => '이 작업을 수행하려면 접근 권한을 허용해야 합니다';

  @override
  String get stretchLyricsDuration => 'Stretch Lyrics Duration';

  @override
  String get subdirectory => 'Subdirectory';

  @override
  String get subscribe => '구독';

  @override
  String get subscribed => '등록됨';

  @override
  String get subscriber => '구독자';

  @override
  String get subscribers => '구독자';

  @override
  String get succeeded => '성공했습니다';

  @override
  String suggestionSubtitle({required String site}) {
    return 'Have an Issue or Suggestion? Open an issue on $site';
  }

  @override
  String get support => '지원';

  @override
  String get supremacy => '최상';

  @override
  String get sussyBaka => '음, 트랙이 없어요';

  @override
  String get swipeActions => 'Swipe Actions';

  @override
  String get swipeToOpenDrawer => '스와이프하여 서랍을 엽니다';

  @override
  String get synced => '동기화됨';

  @override
  String get synopsis => '개요';

  @override
  String get tagFields => '태그 필드';

  @override
  String get tags => '태그';

  @override
  String get tapAction => 'Tap Action';

  @override
  String get tapToSeek => '탭하여 되감기';

  @override
  String get theFollowingChangesWereDetected => 'The following changes were detected';

  @override
  String get themeMode => '테마 선택';

  @override
  String get themeModeDark => '다크';

  @override
  String get themeModeLight => '라이트';

  @override
  String get themeModeSystem => '시스템 설정에 따라';

  @override
  String get themeSettings => '테마';

  @override
  String get themeSettingsSubtitle => '플레이어의 전체적인 분위기';

  @override
  String get thisPlaylistHasActiveSortersDisableThemBeforeReordering => 'This playlist has active sorters, please disable them before reordering.';

  @override
  String get thisVideoIsLikelyDeletedOrSetToPrivate => 'This video is likely deleted or set to private.';

  @override
  String get thumbnails => '썸네일';

  @override
  String get title => '제목';

  @override
  String get top => '상단';

  @override
  String get topComments => '인기 댓글';

  @override
  String get topCommentsSubtitle => '댓글을 아래가 아닌 위에 표시';

  @override
  String get topRecentAlbums => '최근 인기 앨범';

  @override
  String get topRecentArtists => '최근 인기 아티스트';

  @override
  String get topRecents => '최근 인기 게시물';

  @override
  String get totalListenTime => '총 재생 시간';

  @override
  String get totalListens => '총 재생 횟수';

  @override
  String get totalTracks => '총 트랙 수';

  @override
  String get totalTracksDuration => '총 트랙 시간';

  @override
  String get track => '트랙';

  @override
  String get trackArtistsSeparator => '아티스트 구분자';

  @override
  String get trackGenresSeparator => '장르 구분자';

  @override
  String get trackInfo => '트랙 정보';

  @override
  String get trackNotFound => '트랙을 찾을 수 없음';

  @override
  String get trackNumber => '트랙 번호';

  @override
  String get trackNumberTotal => '총 트랙 수';

  @override
  String trackPathOldNew({required String newName, required String oldName}) {
    return '이전 이름: 「$oldName」\n\n새 이름: 「$newName」\n\n괜찮으시겠습니까?';
  }

  @override
  String get trackPlayMode => '재생 모드';

  @override
  String get trackPlayModeSearchResults => '검색 결과';

  @override
  String get trackPlayModeSelectedOnly => '선택된 트랙만';

  @override
  String get trackPlayModeTrackAlbum => '트랙 앨범';

  @override
  String get trackPlayModeTrackArtist => '트랙의 메인 아티스트';

  @override
  String get trackPlayModeTrackGenre => '트랙 장르';

  @override
  String get trackThumbnailSizeInList => '트랙 썸네일 크기';

  @override
  String get trackTileCustomization => '트랙 타일 맞춤 설정';

  @override
  String get trackTileItemsSeparator => '아이템 구분자';

  @override
  String get tracks => '트랙';

  @override
  String get tracksExcludedByNomedia => '.nomedia에 의해 제외된 트랙';

  @override
  String get tracksInfo => '트랙 정보';

  @override
  String get underrated => 'Underrated';

  @override
  String get undo => '실행 취소';

  @override
  String get undoChanges => '변경사항을 취소하시겠습니까?';

  @override
  String get undoChangesDeletedPlaylist => '재생목록 삭제를 취소했습니다';

  @override
  String get undoChangesDeletedQueue => '대기열 삭제 취소';

  @override
  String get undoChangesDeletedTrack => '트랙 삭제 취소';

  @override
  String get uniqueArtworkHash => 'Unique Artwork Hash';

  @override
  String get unlimited => '무제한';

  @override
  String get unlisted => '비공개';

  @override
  String get unlock => '잠금 해제';

  @override
  String get unsubscribe => 'Unsubscribe';

  @override
  String get update => '업데이트';

  @override
  String get updateDirectoryPath => '디렉토리 경로 업데이트';

  @override
  String get updateMissingTracksOnly => '누락된 트랙만 업데이트';

  @override
  String get updating => '업데이트 중';

  @override
  String get useCollapsedSettingTiles => '접힌 설정 타일 사용';

  @override
  String get useMediaStore => '미디어 저장소 사용';

  @override
  String get useMediaStoreSubtitle => '✓ 인덱싱 시간이 즉시 완료됨\nx .nomedia가 강제로 활성화됨\nx 일부 메타데이터 태그가 누락됨\nx 로컬 라이브러리의 YouTube 통합이 작동하지 않음';

  @override
  String get usePitchBlack => '검은색으로 설정';

  @override
  String get usePitchBlackSubtitle => 'AMOLED 화면에서 작동하고, 멋지게 보입니다';

  @override
  String get used => '사용됨';

  @override
  String get value => '값';

  @override
  String get valueBetween50200 => '값은 50%에서 200% 사이여야 함';

  @override
  String get vibration => 'Vibration';

  @override
  String get vibrationType => 'Vibration type';

  @override
  String get video => '동영상';

  @override
  String get videoCache => '영상 캐시';

  @override
  String get videoCacheFile => '캐시된 영상 파일';

  @override
  String get videoCacheFiles => '캐시된 영상 파일';

  @override
  String get videoOnly => '동영상만';

  @override
  String get videoPlaybackSource => '동영상 소스';

  @override
  String get videoPlaybackSourceAutoSubtitle => '로컬 동영상을 우선적으로 재생하고, 찾을 수 없는 경우 YouTube에서 가져옵니다';

  @override
  String get videoPlaybackSourceLocal => '로컬 동영상';

  @override
  String get videoPlaybackSourceLocalExampleSubtitle => 'Alan Walker - Faded.m4a\n동영상 Alan Walker - Faded (480p).mp4';

  @override
  String get videoPlaybackSourceLocalSubtitle => '선택된 폴더 목록의 비디오 파일 이름에 트랙의 파일명이 포함되어 있는지 확인';

  @override
  String get videoPlaybackSourceYoutube => 'YouTube에서';

  @override
  String get videoPlaybackSourceYoutubeSubtitle => '트랙의 파일 이름과 댓글을 확인하여 일치하는 YouTube 링크가 있는지 확인합니다. 동영상은 나중에 사용할 수 있도록 캐시됩니다.';

  @override
  String get videoQuality => '동영상 품질';

  @override
  String get videoQualitySubtitle => '최고 품질이 선택됩니다.';

  @override
  String get videoQualitySubtitleNote => '원하는 품질을 찾지 못할 경우를 대비하여 여러 가지 대안을 준비하는 것이 좋습니다. 그렇지 않으면 최악의 품질로 돌아갈 수 있습니다';

  @override
  String get videos => '동영상';

  @override
  String get view => '보기';

  @override
  String get viewAll => '모두 보기';

  @override
  String get views => '재생회수';

  @override
  String get volume => '볼륨';

  @override
  String get warning => '경고';

  @override
  String get waveformBarsCount => '파형 막대 개수';

  @override
  String get webmNoEditTagsSupport => 'WEBM 형식은 태그 편집을 지원하지 않습니다';

  @override
  String get week => '주';

  @override
  String get wiredDevice => 'Wired Device';

  @override
  String get wirelessDevice => 'Wireless Device';

  @override
  String get year => '년';

  @override
  String get yes => '예';

  @override
  String yourCurrentMembershipIs({required String name}) {
    return '현재 멤버십은 $name입니다';
  }

  @override
  String get yourCustomOrderWillBeLost => 'Your custom order will be lost, Are you sure?';

  @override
  String get youtube => 'YouTube';

  @override
  String get youtubeMusic => 'YouTube Music';

  @override
  String get youtubeSettingsSubtitle => 'YouTube경험 사용자 정의하기';

  @override
  String get youtubeStyleMiniplayer => 'YouTube스타일의 미니플레이어';

  @override
  String get ytPreferNewComments => '가능한 한 새로운 댓글 우선';

  @override
  String get ytPreferNewCommentsSubtitle => '캐시 버전은 연결이 없는 경우에만 사용됩니다';
}
