"""Regenerates lib/core/iso639.data.dart from the SIL ISO 639-3 code table.

usage: python scripts/gen_iso639.py iso-639-3.tab
table: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab

by claude
"""

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'lib' / 'core' / 'iso639.data.dart'
MAX_LINE = 176

# -- music friendly names for the special codes and the few verbose ones
NAME_OVERRIDES = {
    'zxx': 'Instrumental',
    'ell': 'Greek',
}

# -- only languages with a 639-2 code are kept, plus these 639-3 only ones common in music tags
EXTRA_CODES = {
    'cmn', 'yue', 'wuu', 'hak', 'nan',  # chinese
    'arb', 'arz', 'apc',  # arabic
    'pes', 'prs',  # persian
    'fil', 'zsm', 'pnb', 'ckb', 'kmr',
}


def dart_string(text):
    escaped = text.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
    return f"'{escaped}'"


def dart_map_lines(name, entries):
    lines = [f'const {name} = <String, String>{{']
    row = ''
    for key, value in entries:
        item = f'{dart_string(key)}: {dart_string(value)}, '
        if row and len(row) + len(item) > MAX_LINE:
            lines.append(f'  {row.rstrip()} //')
            row = ''
        row += item
    if row:
        lines.append(f'  {row.rstrip()} //')
    lines.append('};')
    return lines


def main():
    with open(sys.argv[1], encoding='utf-8', newline='') as f:
        rows = list(csv.DictReader(f, delimiter='\t'))

    names = []
    part1 = []
    part2b = []
    for row in rows:
        code = row['Id']
        is_kept = row['Part2b'] or row['Part2t'] or code in EXTRA_CODES
        if not is_kept:
            continue
        name = NAME_OVERRIDES.get(code) or row['Ref_Name']
        names.append((code, name))
        if row['Part1']:
            part1.append((row['Part1'], code))
        if row['Part2b'] and row['Part2b'] != code:
            part2b.append((row['Part2b'], code))

    lines = [
        '// generated by scripts/gen_iso639.py from the SIL ISO 639-3 code table, do not edit.',
        "part of 'iso639.dart';",
        '',
        '/// 639-3 code to english name.',
        *dart_map_lines('_kNames', names),
        '',
        '/// 639-1 two letter code to 639-3 code.',
        *dart_map_lines('_kPart1', part1),
        '',
        '/// 639-2/B bibliographic code to 639-3 code, only where they differ.',
        *dart_map_lines('_kPart2B', part2b),
        '',
    ]
    OUT.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    print(f'{OUT}: {len(names)} languages, {len(part1)} part1, {len(part2b)} part2b')


if __name__ == '__main__':
    main()
